import { createHash } from 'node:crypto'
import { createClient } from '@supabase/supabase-js'

const text = (value) => String(value ?? '').trim()
const hash = (value) => createHash('sha256').update(text(value)).digest('hex')
const safeData = (value) => value && typeof value === 'object' && !Array.isArray(value) ? value : {}
const publicApplication = (row = {}) => ({ id: text(row.id), status: text(row.status), version: Number(row.version || 1), data: safeData(row.application_data), updatedAt: row.updated_at || null })
function admin(env = process.env) { const url = text(env.SUPABASE_URL || env.VITE_SUPABASE_URL); const key = text(env.SUPABASE_SERVICE_ROLE_KEY); if (!url || !key) throw new Error('Rental applicant access is not configured.'); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }) }
function tokenFrom(input = {}) { const header = text(input.headers?.authorization || input.headers?.Authorization); return header.startsWith('Bearer ') ? header.slice(7).trim() : text(input.token) }

export async function handlePublicRentalApplication({ method = 'GET', headers = {}, body = {}, token = '', env = process.env } = {}) {
  const rawToken = tokenFrom({ headers, token }); if (!rawToken) return { status: 401, body: { error: 'This application link is invalid or has expired.' } }
  try {
    const db = admin(env); const now = new Date().toISOString();
    const access = await db.from('rental_application_access_tokens').select('id, application_id, expires_at, revoked_at').eq('token_hash', hash(rawToken)).maybeSingle()
    if (access.error || !access.data || access.data.revoked_at || new Date(access.data.expires_at) <= new Date(now)) return { status: 401, body: { error: 'This application link is invalid or has expired.' } }
    const application = await db.from('rental_applications').select('id, organisation_id, status, version, application_data, updated_at').eq('id', access.data.application_id).maybeSingle()
    if (application.error || !application.data) return { status: 404, body: { error: 'This application is unavailable.' } }
    await db.from('rental_application_access_tokens').update({ last_accessed_at: now }).eq('id', access.data.id)
    if (application.data.status !== 'draft') {
      if (method !== 'GET') return { status: 409, body: { error: 'This application can no longer be edited.' } }
      return { status: 200, body: { application: { id: text(application.data.id), status: text(application.data.status), updatedAt: application.data.updated_at || null }, outcomeVisible: ['approved', 'declined', 'withdrawn'].includes(application.data.status) } }
    }
    const documents = await db.from('rental_application_documents').select('id, document_type, status, file_name, uploaded_at').eq('application_id', application.data.id).order('created_at', { ascending: false })
    if (method === 'GET') return { status: 200, body: { application: publicApplication(application.data), documents: documents.data || [] } }
    if (method === 'PUT' && body?.action === 'submit') { const data = safeData(application.data.application_data); const required = ['identity','employment','income','rentalHistory']; const consentTypes = Array.isArray(body?.consents) ? body.consents.map(text) : []; const documentTypes = new Set((documents.data || []).filter((item) => item.status === 'uploaded' || item.status === 'accepted').map((item) => item.document_type)); if (required.some((key) => !Object.keys(safeData(data[key])).length) || !['privacy','credit_check','identity_verification'].every((type) => consentTypes.includes(type)) || !documentTypes.has('identity') || !documentTypes.has('proof_of_income')) return { status: 400, body: { error: 'Complete all sections, upload ID and proof of income, and accept every consent.' } }; const wordingVersion = 'rental-application-consent-v1'; const consentRows = ['privacy','credit_check','identity_verification'].map((consent_type) => ({ application_id: application.data.id, organisation_id: application.data.organisation_id, consent_type, wording_version: wordingVersion, evidence_json: { accepted: true, submitted_at: now } })); const consent = await db.from('rental_application_consents').upsert(consentRows, { onConflict: 'application_id,consent_type,wording_version' }); if (consent.error) throw consent.error; const update = await db.from('rental_applications').update({ status: 'submitted', submitted_at: now, submitted_snapshot_json: data, version: Number(application.data.version) + 1 }).eq('id', application.data.id).eq('version', application.data.version).select('id, status, version, application_data, updated_at').maybeSingle(); if (update.error || !update.data) return { status: 409, body: { error: 'This application changed. Refresh and try again.' } }; return { status: 200, body: { application: publicApplication(update.data), submitted: true } } }
    if (method === 'POST') { const documentType = text(body?.documentType); const fileName = text(body?.fileName).slice(0, 180); const content = text(body?.contentBase64); if (!['identity','proof_of_income','bank_statement','reference','other'].includes(documentType) || !fileName || !content) return { status: 400, body: { error: 'Choose a valid document and file.' } }; const binary = Buffer.from(content, 'base64'); if (!binary.length || binary.length > 8 * 1024 * 1024) return { status: 400, body: { error: 'Documents must be 8 MB or smaller.' } }; const path = `${application.data.organisation_id || 'application'}/${application.data.id}/${crypto.randomUUID()}-${fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const upload = await db.storage.from('rental-application-documents').upload(path, binary, { contentType: text(body?.mimeType) || 'application/octet-stream', upsert: false }); if (upload.error) throw upload.error; const created = await db.from('rental_application_documents').insert({ application_id: application.data.id, organisation_id: (await db.from('rental_applications').select('organisation_id').eq('id', application.data.id).single()).data.organisation_id, document_type: documentType, storage_path: path, file_name: fileName, mime_type: text(body?.mimeType) || null, file_size_bytes: binary.length, uploaded_at: now }).select('id, document_type, status, file_name, uploaded_at').single(); if (created.error) throw created.error; return { status: 201, body: { document: created.data } } }
    if (method !== 'PATCH') return { status: 405, body: { error: 'Method not allowed.' } }
    const expectedVersion = Number(body?.version); const patch = safeData(body?.patch)
    if (!Number.isInteger(expectedVersion) || expectedVersion !== Number(application.data.version)) return { status: 409, body: { error: 'This application changed. Refresh and try again.' } }
    const update = await db.from('rental_applications').update({ application_data: { ...safeData(application.data.application_data), ...patch }, version: expectedVersion + 1 }).eq('id', application.data.id).eq('version', expectedVersion).select('id, status, version, application_data, updated_at').maybeSingle()
    if (update.error || !update.data) return { status: 409, body: { error: 'This application changed. Refresh and try again.' } }
    return { status: 200, body: { application: publicApplication(update.data) } }
  } catch (error) { return { status: 500, body: { error: error?.message || 'Unable to load application.' } } }
}
export function writeNodeJsonResponse(response, result) { response.status(result.status).json(result.body) }
