
[auth.rate_limit]
email_sent = 1000
sign_in_sign_ups = 1000
token_verifications = 1000

[functions.send-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-email/*.html" ]

[functions.send-mandate-signing-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-mandate-signing-email/deno.json"
entrypoint = "./functions/send-mandate-signing-email/index.ts"

[functions.send-whatsapp]
enabled = true
verify_jwt = true
import_map = "./functions/send-whatsapp/deno.json"
entrypoint = "./functions/send-whatsapp/index.ts"

[functions.generate-mandate]
enabled = true
verify_jwt = true
import_map = "./functions/generate-mandate/deno.json"
entrypoint = "./functions/generate-mandate/index.ts"

[functions.generate-otp]
enabled = true
verify_jwt = true
import_map = "./functions/generate-otp/deno.json"
entrypoint = "./functions/generate-otp/index.ts"

[functions.document-conversion-health]
enabled = true
verify_jwt = true
import_map = "./functions/document-conversion-health/deno.json"
entrypoint = "./functions/document-conversion-health/index.ts"

[functions.generate-final-signed-document]
enabled = true
verify_jwt = true
import_map = "./functions/generate-final-signed-document/deno.json"
entrypoint = "./functions/generate-final-signed-document/index.ts"

[functions.resolve-signer-token]
enabled = true
verify_jwt = false
import_map = "./functions/resolve-signer-token/deno.json"
entrypoint = "./functions/resolve-signer-token/index.ts"

[functions.signer-signing-action]
enabled = true
verify_jwt = false
import_map = "./functions/signer-signing-action/deno.json"
entrypoint = "./functions/signer-signing-action/index.ts"
