import assert from 'node:assert/strict'
import { MATTER_PLAN_OWNER_ROLES as R } from '../../transactions/conveyancerMatterPlanContract.js'
import { buildConveyancerThreeRoleDependencyModel } from '../../transactions/conveyancerThreeRoleDependencyModel.js'
import {
  CONVEYANCER_FINANCIAL_LINE_CLASSES as LC,
  CONVEYANCER_FINANCIAL_LINE_STATUSES as LS,
  CONVEYANCER_FINANCIAL_LINE_TYPES as LT,
  CONVEYANCER_FINANCIAL_MODEL_VERSION,
  buildConveyancerFinancialModel,
} from '../../transactions/conveyancerFinancialModel.js'
import {
  CONVEYANCER_INTEGRATION_AUTHENTICATION_TYPES as A,
  CONVEYANCER_INTEGRATION_CONNECTION_STATUSES as CS,
  CONVEYANCER_INTEGRATION_DATA_CLASSIFICATIONS as D,
  CONVEYANCER_INTEGRATION_ENVIRONMENTS as E,
  CONVEYANCER_INTEGRATION_LEGAL_BASES as B,
  buildConveyancerIntegrationConnection,
  buildConveyancerIntegrationInboundEvent,
} from '../conveyancerIntegrationFramework.js'
import {
  CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION,
  SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY,
  buildSarsTransferDutyAdapterManifest,
  buildSarsTransferDutyApplication,
  buildSarsTransferDutyComplianceEvidence,
  buildSarsTransferDutyFilingProfile,
  buildSarsTransferDutyOutcome,
  buildSarsTransferDutySupportingDocumentBatch,
  buildSarsTransferDutySubmissionPacket,
  validateSarsTransferDutyApplication,
  validateSarsTransferDutyComplianceEvidence,
  validateSarsTransferDutyFilingProfile,
  validateSarsTransferDutyOutcome,
  validateSarsTransferDutySupportingDocumentBatch,
  validateSarsTransferDutySubmissionPacket,
} from '../conveyancerSarsTransferDutyIntegration.js'

function test(name, fn) { try { fn(); console.log(`ok - ${name}`) } catch (error) { console.error(`not ok - ${name}`); throw error } }
const hash = (character) => character.repeat(64)
const source = (type, referenceId) => ({ type, referenceId, evidenceHash: hash('f'), effectiveAt: '2026-07-15T08:00:00.000Z' })
const manager = { role: R.firmManager, userId: 'manager:f4', lane: 'transfer', firmId: 'firm:transfer' }
const secretary = { role: R.secretary, userId: 'secretary:f4', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const attorney = { role: R.transferAttorney, userId: 'attorney:f4', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const reviewer = { role: R.transferAttorney, userId: 'reviewer:f4', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const bindings = { transfer: { firmId: 'firm:transfer', owner: { role: R.transferAttorney, userId: 'attorney:f4', teamId: 'team:transfer' } } }

function model() { const result = buildConveyancerThreeRoleDependencyModel({ plan: { planId: 'plan:f4', planVersion: 1 }, transaction: { id: 'transaction:f4', organisation_id: 'organisation:f4', transaction_type: 'resale', property_tenure: 'freehold', finance_type: 'cash', seller_has_existing_bond: false, buyer_entity_type: 'individual', seller_entity_type: 'individual' }, roleBindings: bindings, generatedAt: '2026-07-15T08:00:00.000Z', generatedBy: { role: R.system, userId: 'system:f4' } }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model }
function financialModel(taxTreatment = 'transfer_duty') { const result = buildConveyancerFinancialModel({ modelVersion: CONVEYANCER_FINANCIAL_MODEL_VERSION, financialModelId: `financial-model:f4:${taxTreatment}`, revision: 1, planId: 'plan:f4', planVersion: 1, transactionId: 'transaction:f4', organisationId: 'organisation:f4', lane: 'transfer', currency: 'ZAR', consideration: { purchasePrice: '1000000.00', taxTreatment, source: source('signed_agreement', 'otp:f4') }, lines: [{ lineId: 'cash', lineClass: LC.funding, lineType: LT.cashContribution, label: 'Cash purchase funding', liableParty: 'buyer', recipientParty: 'trust_account', amount: '1000000.00', status: LS.confirmed, source: source('bank_confirmation', 'funding:f4') }], preparedAt: '2026-07-15T09:00:00.000Z', preparedBy: { role: R.accounts, userId: 'accounts:f4' }, approval: { decisionReferenceId: 'approval:f4:d5', summary: 'Approved tax treatment and consideration.', approvedAt: '2026-07-15T10:00:00.000Z', approvedBy: { role: R.transferAttorney, userId: 'attorney:d5:f4' } } }, { asOf: '2026-07-15T10:30:00.000Z' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model }
function manifest() { const result = buildSarsTransferDutyAdapterManifest({ adapterId: 'sars-adapter', adapterVersion: '1.0.0', environments: [E.sandbox, E.production], authenticationTypes: [A.oauth2, A.signedWebhook], createdAt: '2026-07-15T08:00:00.000Z', createdBy: 'integration-governance:f4' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.manifest }
function connection(adapter = manifest()) { const result = buildConveyancerIntegrationConnection({ connectionId: 'connection:f4:sars', organisationId: 'organisation:f4', environment: E.production, status: CS.active, capabilities: adapter.capabilities, allowedLanes: ['transfer'], credentialReferenceId: 'vault:sars:f4', secretVersion: 'version:4', webhook: { endpointReferenceId: 'route:sars:f4', secretReferenceId: 'vault:webhook:f4', signingAlgorithm: 'hmac_sha256', replayWindowSeconds: 300 }, dataPolicy: { purpose: 'Prepare and reconcile SARS transfer-duty declarations and evidence for the bound matter.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.personal, D.financial, D.specialPersonal], retentionDays: 2555 }, verifiedAt: '2026-07-15T08:30:00.000Z', createdAt: '2026-07-15T08:00:00.000Z', createdBy: 'integration-admin:f4' }, { manifest: adapter }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.connection }
function profile(adapter = manifest(), activeConnection = connection(adapter), overrides = {}) { return buildSarsTransferDutyFilingProfile({ profileId: 'sars-profile:f4', firmId: 'firm:transfer', sarsFinancialAccountReferenceId: 'sars-financial-account:f4', sarsFinancialAccountHash: hash('a'), conveyancerRegistrationReferenceId: 'conveyancer-registration:f4', conveyancerRegistrationHash: hash('b'), efilingProfileReferenceId: 'efiling-profile:f4', efilingProfileHash: hash('c'), approvedAt: '2026-07-15T09:00:00.000Z', approvedBy: manager, createdAt: '2026-07-15T08:45:00.000Z', createdBy: 'integration-admin:f4', ...overrides }, { manifest: adapter, connection: activeConnection }) }
const parties = [{ partyRole: 'seller', partyReferenceId: 'party:seller:f4', partyReferenceHash: hash('1'), natureOfPerson: 'individual', taxIdentityReferenceId: 'identity:seller:f4', taxIdentityHash: hash('2'), declarationReferenceId: 'declaration:seller:f4', declarationHash: hash('3') }, { partyRole: 'purchaser', partyReferenceId: 'party:purchaser:f4', partyReferenceHash: hash('4'), natureOfPerson: 'individual', taxIdentityReferenceId: 'identity:purchaser:f4', taxIdentityHash: hash('5'), declarationReferenceId: 'declaration:purchaser:f4', declarationHash: hash('6') }]
const properties = [{ propertyReferenceId: 'property:f4', propertyReferenceHash: hash('7'), propertyType: 'freehold', descriptionEvidenceReferenceId: 'deeds-description:f4', descriptionEvidenceHash: hash('8'), allocatedConsiderationMinor: 100000000 }]
const retainedDocuments = [{ documentId: 'document:otp:f4', category: 'signed_agreement', referenceId: 'otp:f4', documentHash: hash('9'), retainedAt: '2026-07-15T10:00:00.000Z' }, { documentId: 'document:property:f4', category: 'property_description', referenceId: 'deeds-description:f4', documentHash: hash('a'), retainedAt: '2026-07-15T10:00:00.000Z' }]
function application(context = {}, overrides = {}) { const dependencyModel = context.model || model(); const finance = context.financialModel || financialModel(); const adapter = context.manifest || manifest(); const activeConnection = context.connection || connection(adapter); const filingProfile = context.profile || profile(adapter, activeConnection).profile; return buildSarsTransferDutyApplication({ applicationId: 'sars-application:f4:r1', basis: finance.consideration.taxTreatment === 'exempt' ? 'exemption_claimed' : 'duty_payable', parties, properties, calculation: { referenceId: 'calculation:f4', calculationHash: hash('b'), estimatedDutyMinor: finance.consideration.taxTreatment === 'exempt' ? 0 : 300000, calculatedAt: '2026-07-15T10:45:00.000Z' }, retainedDocuments, preparedAt: '2026-07-15T11:00:00.000Z', preparedBy: secretary, approvedAt: '2026-07-15T11:30:00.000Z', approvedBy: attorney, approvalReferenceId: 'approval:sars-application:f4', ...overrides }, { dependencyModel, financialModel: finance, manifest: adapter, connection: activeConnection, profile: filingProfile, previousApplication: context.previousApplication || null, currentOutcome: context.currentOutcome || null }) }
function inbound(type, sequence = 1, context = {}) { const dependencyModel = context.model || model(); const adapter = context.manifest || manifest(); const activeConnection = context.connection || connection(adapter); const minute = String(30 + sequence).padStart(2, '0'); const result = buildConveyancerIntegrationInboundEvent({ recordId: `sars-event:f4:${sequence}`, type, lane: 'transfer', firmId: 'firm:transfer', idempotencyKey: `sars-event-f4-${sequence}`, providerEventId: `provider:sars:f4:${sequence}`, payloadReferenceId: `quarantine:sars:f4:${sequence}`, payloadHash: hash(sequence % 2 ? 'd' : 'e'), dataPolicy: { purpose: 'Reconcile signed SARS transfer-duty status evidence.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.personal, D.financial], retentionDays: 365 }, signature: { verified: true, algorithm: 'hmac_sha256', keyReferenceId: 'vault:webhook:f4', nonceHash: hash('f'), payloadHash: hash(sequence % 2 ? 'd' : 'e'), signedAt: `2026-07-15T13:${minute}:00.000Z` }, occurredAt: `2026-07-15T13:${minute}:30.000Z`, receivedAt: `2026-07-15T13:${minute}:45.000Z` }, { dependencyModel, manifest: adapter, connection: activeConnection }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.event }

function fixture(taxTreatment = 'transfer_duty') { const dependencyModel = model(); const finance = financialModel(taxTreatment); const adapter = manifest(); const activeConnection = connection(adapter); const profileResult = profile(adapter, activeConnection); assert.equal(profileResult.ok, true, JSON.stringify(profileResult.errors)); const appResult = application({ model: dependencyModel, financialModel: finance, manifest: adapter, connection: activeConnection, profile: profileResult.profile }); assert.equal(appResult.ok, true, JSON.stringify(appResult.errors)); return { dependencyModel, finance, adapter, activeConnection, filingProfile: profileResult.profile, app: appResult.application } }
function outcome(value, status, revision, event, previousOutcome = null, overrides = {}) { return buildSarsTransferDutyOutcome({ outcomeId: `sars-outcome:f4:${revision}`, revision, providerTransferDutyReferenceId: 'TDE:1234567', providerTransferDutyReferenceHash: hash('6'), providerRevision: revision, status, paymentStatus: status === 'payment_received' || status === 'receipt_issued' ? 'confirmed_in_full' : 'pending', occurredAt: event.occurredAt, ...overrides }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, inboundEvent: event, previousOutcome }) }
function paidReceiptChain(value = fixture()) { const e1 = inbound('sars_transfer_duty_status_received', 1, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const submitted = outcome(value, 'submitted', 1, e1).outcome; const e2 = inbound('sars_transfer_duty_assessment_received', 2, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const assessed = outcome(value, 'assessment_issued', 2, e2, submitted, { assessment: { noticeReferenceId: 'assessment:f4', noticeHash: hash('a'), assessedDutyMinor: 300000, penaltyInterestMinor: 0, issuedAt: e2.occurredAt } }).outcome; const e3 = inbound('sars_transfer_duty_status_received', 3, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const pending = outcome(value, 'payment_pending', 3, e3, assessed).outcome; const e4 = inbound('sars_transfer_duty_status_received', 4, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const paid = outcome(value, 'payment_received', 4, e4, pending).outcome; const e5 = inbound('sars_transfer_duty_receipt_received', 5, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const receipt = outcome(value, 'receipt_issued', 5, e5, paid, { receipt: { state: 'available', documentReferenceId: 'tdrecpt:f4', documentHash: hash('c'), issuedAt: e5.occurredAt } }).outcome; return { submitted, assessed, pending, paid, receipt, receiptEvent: e5 } }

test('creates a governed SARS adapter and manager-approved filing profile', () => { const adapter = manifest(); const activeConnection = connection(adapter); const result = profile(adapter, activeConnection); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(adapter.category, 'tax_authority'); assert.equal(result.profile.version, CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION); assert.equal(validateSarsTransferDutyFilingProfile(result.profile, { manifest: adapter, connection: activeConnection }).valid, true) })
test('rejects missing registration references, forged profiles and non-manager approval', () => { const adapter = manifest(); const activeConnection = connection(adapter); assert.equal(profile(adapter, activeConnection, { conveyancerRegistrationHash: 'bad' }).errors.includes('sars_profile_reference_invalid'), true); assert.equal(profile(adapter, activeConnection, { approvedBy: attorney }).errors.includes('sars_profile_approval_invalid'), true); const changed = structuredClone(profile(adapter, activeConnection).profile); changed.accountActivated = true; assert.equal(validateSarsTransferDutyFilingProfile(changed, { manifest: adapter, connection: activeConnection }).errors.includes('sars_profile_side_effect_boundary_violated'), true) })
test('builds an independently approved TDC01 application evidence contract', () => { const value = fixture(); assert.equal(value.app.financialModel.purchasePriceMinor, 100000000); assert.equal(value.app.properties.reduce((sum, item) => sum + item.allocatedConsiderationMinor, 0), 100000000); assert.equal(value.app.calculation.authoritative, false); assert.equal(value.app.retainedDocuments.every((item) => item.submittedToSars === false), true); assert.equal(validateSarsTransferDutyApplication(value.app, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile }).valid, true) })
test('blocks VAT/unknown routing, property variance and self-approval', () => { const value = fixture(); assert.equal(application({ ...value, financialModel: financialModel('vat_inclusive') }).errors.includes('sars_application_tax_basis_invalid'), true); assert.equal(application(value, { properties: [{ ...properties[0], allocatedConsiderationMinor: 99999999 }] }).errors.includes('sars_application_properties_invalid'), true); assert.equal(application(value, { preparedBy: attorney, approvedBy: attorney }).errors.includes('sars_application_independent_approval_invalid'), true) })
test('supports append-only pre-payment corrections with a distinct F1 command', () => { const value = fixture(); const event = inbound('sars_transfer_duty_status_received', 1, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const submitted = outcome(value, 'submitted', 1, event).outcome; const correction = application({ ...value, previousApplication: value.app, currentOutcome: submitted }, { applicationId: 'sars-application:f4:r2', revision: 2, correctionReason: 'Correct purchaser declaration evidence.', approvedBy: reviewer }); assert.equal(correction.ok, true, JSON.stringify(correction.errors)); assert.equal(correction.application.previousFingerprint, value.app.fingerprint); assert.equal(value.app.revision, 1); assert.equal(Object.isFrozen(value.app), true); const packet = buildSarsTransferDutySubmissionPacket({ packetId: 'sars-correction-packet:f4', commandId: 'sars-correction-command:f4', idempotencyKey: 'sars-correction-f4', payloadReferenceId: 'approved-tdc01-correction:f4', payloadHash: hash('9'), preparedAt: '2026-07-15T12:00:00.000Z', preparedBy: attorney, retentionDays: 1825 }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: correction.application }); assert.equal(packet.ok, true, JSON.stringify(packet.errors)); assert.equal(packet.outboundCommand.type, 'sars_transfer_duty_correction_requested') })
test('blocks ordinary corrections once payment or receipt compliance exists', () => { const value = fixture(); const chain = paidReceiptChain(value); const correction = application({ ...value, previousApplication: value.app, currentOutcome: chain.paid }, { applicationId: 'sars-application:f4:r2', revision: 2, correctionReason: 'Late correction.', approvedBy: reviewer }); assert.equal(correction.ok, false); assert.equal(correction.errors.includes('sars_application_correction_lineage_invalid'), true) })
test('rejects inline taxpayer, property and document content from application records', () => { const value = fixture(); const identity = application(value, { parties: [{ ...parties[0], taxNumber: 'SECRET' }, parties[1]] }); assert.equal(identity.errors.includes('sars_application_inline_party_identity_prohibited'), true); const propertyData = application(value, { properties: [{ ...properties[0], address: 'SECRET' }] }); assert.equal(propertyData.errors.includes('sars_application_inline_property_data_prohibited'), true); const document = application(value, { retainedDocuments: [{ ...retainedDocuments[0], content: 'SECRET' }] }); assert.equal(document.errors.includes('sars_application_inline_document_prohibited'), true); assert.equal(JSON.stringify(value.app).includes('SECRET'), false) })
test('prepares an idempotent F1 declaration submission without filing it', () => { const value = fixture(); const first = buildSarsTransferDutySubmissionPacket({ packetId: 'sars-packet:f4', commandId: 'sars-command:f4', idempotencyKey: 'sars-submit-f4', payloadReferenceId: 'approved-tdc01:f4', payloadHash: hash('d'), preparedAt: '2026-07-15T12:00:00.000Z', preparedBy: attorney, retentionDays: 1825 }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app }); assert.equal(first.ok, true, JSON.stringify(first.errors)); assert.equal(first.packet.status, 'prepared'); assert.equal(first.outboundCommand.controls.dispatchPerformed, false); assert.equal(first.packet.controls.sarsSubmissionPerformed, false); assert.equal(validateSarsTransferDutySubmissionPacket(first.packet, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, outboundCommand: first.outboundCommand }).valid, true); const duplicate = buildSarsTransferDutySubmissionPacket({ packetId: 'sars-packet:f4', commandId: 'sars-command:f4', idempotencyKey: 'sars-submit-f4', payloadReferenceId: 'approved-tdc01:f4', payloadHash: hash('d'), preparedAt: '2026-07-15T12:00:00.000Z', preparedBy: attorney, retentionDays: 1825 }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, existingCommands: [first.outboundCommand] }); assert.equal(duplicate.packet.status, 'duplicate') })
test('reconciles submitted, assessment, payment and receipt as separate states', () => { const value = fixture(); const chain = paidReceiptChain(value); assert.equal(chain.submitted.complianceEligible, false); assert.equal(chain.assessed.complianceEligible, false); assert.equal(chain.paid.complianceEligible, false); assert.equal(chain.receipt.complianceEligible, true); assert.equal(chain.receipt.revision, 5); assert.equal(chain.receipt.previousFingerprint, chain.paid.fingerprint); assert.equal(validateSarsTransferDutyOutcome(chain.receipt, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, inboundEvent: chain.receiptEvent, previousOutcome: chain.paid }).valid, true) })
test('never treats an assessment, payment status or unverified receipt as compliance', () => { const value = fixture(); const chain = paidReceiptChain(value); const falseReceiptEvent = inbound('sars_transfer_duty_receipt_received', 6, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const falseReceipt = outcome(value, 'receipt_issued', 5, falseReceiptEvent, chain.paid, { paymentStatus: 'pending', receipt: { state: 'available', documentReferenceId: 'tdrecpt:bad', documentHash: hash('d'), issuedAt: falseReceiptEvent.occurredAt } }); assert.equal(falseReceipt.ok, false); assert.equal(falseReceipt.errors.includes('sars_outcome_receipt_or_exemption_invalid'), true); assert.equal(chain.assessed.complianceEligible, false) })
test('requires exact signed event type, application and provider-reference lineage', () => { const value = fixture(); const chain = paidReceiptChain(value); const wrongEvent = inbound('sars_transfer_duty_status_received', 7, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); assert.equal(validateSarsTransferDutyOutcome(chain.receipt, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, inboundEvent: wrongEvent, previousOutcome: chain.paid }).errors.includes('sars_outcome_inbound_evidence_invalid'), true); const forged = structuredClone(chain.receipt); forged.providerTransferDutyReferenceHash = hash('e'); assert.equal(validateSarsTransferDutyOutcome(forged, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, inboundEvent: chain.receiptEvent, previousOutcome: chain.paid }).errors.includes('sars_outcome_transition_invalid'), true) })
test('prepares supporting documents only after a signed SARS category request', () => { const value = fixture(); const submittedEvent = inbound('sars_transfer_duty_status_received', 1, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const submitted = outcome(value, 'submitted', 1, submittedEvent).outcome; const requestEvent = inbound('sars_transfer_duty_supporting_documents_requested', 2, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const requested = outcome(value, 'supporting_documents_requested', 2, requestEvent, submitted, { supportingDocumentRequest: { caseReferenceId: 'sars-case:f4', requestHash: hash('b'), requestedCategories: ['signed_agreement'], requestedAt: requestEvent.occurredAt } }).outcome; const result = buildSarsTransferDutySupportingDocumentBatch({ batchId: 'sars-supporting-batch:f4', documentIds: ['document:otp:f4'], commandId: 'sars-supporting-command:f4', idempotencyKey: 'sars-supporting-f4', payloadReferenceId: 'approved-supporting-pack:f4', payloadHash: hash('e'), preparedAt: '2026-07-15T14:00:00.000Z', preparedBy: secretary, approvedAt: '2026-07-15T14:15:00.000Z', approvedBy: attorney, approvalReferenceId: 'approval:sars-supporting:f4', retentionDays: 1825 }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, requestOutcome: requested, requestInboundEvent: requestEvent, previousOutcome: submitted }); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.deepEqual(result.batch.documents.map((item) => item.category), ['signed_agreement']); assert.equal(result.outboundCommand.controls.dispatchPerformed, false); assert.equal(result.batch.controls.supportingDocumentsUploaded, false); assert.equal(validateSarsTransferDutySupportingDocumentBatch(result.batch, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, requestOutcome: requested, requestInboundEvent: requestEvent, previousOutcome: submitted, outboundCommand: result.outboundCommand }).valid, true) })
test('blocks unsolicited or non-requested supporting-document categories', () => { const value = fixture(); const chain = paidReceiptChain(value); const unsolicited = buildSarsTransferDutySupportingDocumentBatch({ batchId: 'unsolicited', documentIds: ['document:otp:f4'], preparedAt: '2026-07-15T14:00:00.000Z', preparedBy: secretary, approvedAt: '2026-07-15T14:15:00.000Z', approvedBy: attorney, approvalReferenceId: 'approval:bad' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, requestOutcome: chain.assessed, requestInboundEvent: inbound('sars_transfer_duty_assessment_received', 9, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }), previousOutcome: chain.submitted }); assert.equal(unsolicited.errors.includes('sars_supporting_batch_documents_invalid'), true) })
test('requires explicit acceptance evidence for no-payment and exemption receipts', () => { const value = fixture('exempt'); const e1 = inbound('sars_transfer_duty_status_received', 1, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const submitted = outcome(value, 'submitted', 1, e1, null, { paymentStatus: 'not_required' }).outcome; const e2 = inbound('sars_transfer_duty_status_received', 2, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const accepted = outcome(value, 'accepted', 2, e2, submitted, { paymentStatus: 'not_required' }).outcome; const e3 = inbound('sars_transfer_duty_receipt_received', 3, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const invalid = outcome(value, 'exemption_issued', 3, e3, accepted, { paymentStatus: 'not_required', receipt: { state: 'available', documentReferenceId: 'tdexmpt:f4', documentHash: hash('d'), issuedAt: e3.occurredAt } }); assert.equal(invalid.ok, false); const valid = outcome(value, 'exemption_issued', 3, e3, accepted, { paymentStatus: 'not_required', receipt: { state: 'available', documentReferenceId: 'tdexmpt:f4', documentHash: hash('d'), issuedAt: e3.occurredAt, acceptanceEvidenceReferenceId: 'acceptance:f4', acceptanceEvidenceHash: hash('e') } }); assert.equal(valid.ok, true, JSON.stringify(valid.errors)); assert.equal(valid.outcome.complianceEligible, true) })
test('creates lodgement evidence only after independent legal receipt review', () => { const value = fixture(); const chain = paidReceiptChain(value); const result = buildSarsTransferDutyComplianceEvidence({ evidenceId: 'sars-compliance:f4', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: reviewer, reviewReferenceId: 'review:sars-receipt:f4' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, outcome: chain.receipt, inboundEvent: chain.receiptEvent, previousOutcome: chain.paid }); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.evidence.status, 'approved_for_lodgement_evidence'); assert.equal(result.evidence.documentHash, chain.receipt.receipt.documentHash); assert.equal(result.evidence.controls.lodgementReadinessMutated, false); assert.equal(validateSarsTransferDutyComplianceEvidence(result.evidence, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, outcome: chain.receipt, inboundEvent: chain.receiptEvent, previousOutcome: chain.paid }).valid, true) })
test('revokes compliance when SARS locks or revokes a previously available receipt', () => { const value = fixture(); const chain = paidReceiptChain(value); const event = inbound('sars_transfer_duty_receipt_status_received', 8, { model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); const revoked = outcome(value, 'receipt_revoked', 6, event, chain.receipt, { paymentStatus: 'reversed', receipt: { state: 'locked', documentReferenceId: 'tdrecpt:f4', documentHash: hash('c'), issuedAt: chain.receipt.receipt.issuedAt } }); assert.equal(revoked.ok, true, JSON.stringify(revoked.errors)); assert.equal(revoked.outcome.complianceEligible, false); const evidence = buildSarsTransferDutyComplianceEvidence({ evidenceId: 'sars-compliance:revoked', reviewedAt: '2026-07-15T14:30:00.000Z', reviewedBy: reviewer, reviewReferenceId: 'review:revoked:f4' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, outcome: revoked.outcome, inboundEvent: event, previousOutcome: chain.receipt }); assert.equal(evidence.errors.includes('sars_compliance_eligible_outcome_required'), true) })
test('detects application, outcome, evidence and side-effect tampering', () => { const value = fixture(); const chain = paidReceiptChain(value); const changed = structuredClone(chain.receipt); changed.complianceEligible = false; changed.controls.receiptSynthesised = true; const validation = validateSarsTransferDutyOutcome(changed, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.filingProfile, application: value.app, inboundEvent: chain.receiptEvent, previousOutcome: chain.paid }); assert.equal(validation.errors.includes('sars_outcome_compliance_derivation_invalid'), true); assert.equal(validation.errors.includes('sars_outcome_fingerprint_invalid'), true); assert.equal(validation.errors.includes('sars_outcome_side_effect_boundary_violated'), true); assert.equal(SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY.paymentInitiated, false) })

console.log('F4 SARS/transfer-duty integration tests passed.')
