import assert from 'node:assert/strict'
import { MATTER_PLAN_OWNER_ROLES as R } from '../../transactions/conveyancerMatterPlanContract.js'
import { buildConveyancerThreeRoleDependencyModel } from '../../transactions/conveyancerThreeRoleDependencyModel.js'
import {
  CONVEYANCER_FINANCIAL_LINE_CLASSES as LC,
  CONVEYANCER_FINANCIAL_LINE_STATUSES as LS,
  CONVEYANCER_FINANCIAL_LINE_TYPES as LT,
  CONVEYANCER_FINANCIAL_MODEL_VERSION,
  buildConveyancerFinancialModel,
} from '../../transactions/conveyancerFinancialModel.js'
import {
  CONVEYANCER_INTEGRATION_AUTHENTICATION_TYPES as A,
  CONVEYANCER_INTEGRATION_CONNECTION_STATUSES as CONNECTION_STATUS,
  CONVEYANCER_INTEGRATION_DATA_CLASSIFICATIONS as D,
  CONVEYANCER_INTEGRATION_ENVIRONMENTS as E,
  CONVEYANCER_INTEGRATION_LEGAL_BASES as B,
  buildConveyancerIntegrationConnection,
  buildConveyancerIntegrationInboundEvent,
} from '../conveyancerIntegrationFramework.js'
import {
  CONVEYANCER_MUNICIPAL_LEVY_INTEGRATION_VERSION,
  PROPERTY_CLEARANCE_INTEGRATION_BOUNDARY,
  buildPropertyClearanceAdapterManifest,
  buildPropertyClearanceCommandPacket,
  buildPropertyClearanceComplianceEvidence,
  buildPropertyClearanceOutcome,
  buildPropertyClearanceProfile,
  buildPropertyClearanceRequest,
  validatePropertyClearanceCommandPacket,
  validatePropertyClearanceComplianceEvidence,
  validatePropertyClearanceOutcome,
  validatePropertyClearanceProfile,
  validatePropertyClearanceRequest,
} from '../conveyancerMunicipalLevyIntegration.js'

function test(name, fn) { try { fn(); console.log(`ok - ${name}`) } catch (error) { console.error(`not ok - ${name}`); throw error } }
const hash = (character) => character.repeat(64)
const source = (type, referenceId) => ({ type, referenceId, evidenceHash: hash('f'), effectiveAt: '2026-07-15T08:00:00.000Z' })
const manager = { role: R.firmManager, userId: 'manager:f5', lane: 'transfer', firmId: 'firm:transfer' }
const secretary = { role: R.secretary, userId: 'secretary:f5', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const attorney = { role: R.transferAttorney, userId: 'attorney:f5', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const reviewer = { role: R.transferAttorney, userId: 'reviewer:f5', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const bindings = { transfer: { firmId: 'firm:transfer', owner: { role: R.transferAttorney, userId: 'attorney:f5', teamId: 'team:transfer' } } }

function model(clearanceType = 'municipal') {
  const tenure = clearanceType === 'sectional_levy' ? 'sectional_title' : clearanceType === 'hoa_levy' ? 'estate_hoa' : 'freehold'
  const result = buildConveyancerThreeRoleDependencyModel({ plan: { planId: 'plan:f5', planVersion: 1 }, transaction: { id: 'transaction:f5', organisation_id: 'organisation:f5', transaction_type: 'resale', property_tenure: tenure, finance_type: 'cash', seller_has_existing_bond: false, buyer_entity_type: 'individual', seller_entity_type: 'individual' }, roleBindings: bindings, generatedAt: '2026-07-15T08:00:00.000Z', generatedBy: { role: R.system, userId: 'system:f5' } })
  assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model
}
function financialModel(clearanceType = 'municipal', includeExpectation = true, amount = '15000.00') {
  const type = clearanceType === 'municipal' ? LT.ratesClearance : clearanceType === 'sectional_levy' ? LT.levyClearance : LT.homeownersAssociation
  const recipient = clearanceType === 'municipal' ? 'municipality' : clearanceType === 'sectional_levy' ? 'body_corporate' : 'homeowners_association'
  const lines = [{ lineId: 'cash:f5', lineClass: LC.funding, lineType: LT.cashContribution, label: 'Cash purchase funding', liableParty: 'buyer', recipientParty: 'trust_account', amount: '1000000.00', status: LS.confirmed, source: source('bank_confirmation', 'funding:f5') }]
  if (includeExpectation) lines.push({ lineId: `clearance:${clearanceType}`, lineClass: LC.sellerDeduction, lineType: type, label: 'Approved clearance expectation', liableParty: 'seller', recipientParty: recipient, amount, status: LS.confirmed, source: source('statutory_assessment', `clearance-expectation:${clearanceType}`) })
  const result = buildConveyancerFinancialModel({ modelVersion: CONVEYANCER_FINANCIAL_MODEL_VERSION, financialModelId: `financial-model:f5:${clearanceType}:${includeExpectation}`, revision: 1, planId: 'plan:f5', planVersion: 1, transactionId: 'transaction:f5', organisationId: 'organisation:f5', lane: 'transfer', currency: 'ZAR', consideration: { purchasePrice: '1000000.00', taxTreatment: 'transfer_duty', source: source('signed_agreement', 'otp:f5') }, lines, preparedAt: '2026-07-15T09:00:00.000Z', preparedBy: { role: R.accounts, userId: 'accounts:f5' }, approval: { decisionReferenceId: 'approval:f5:d5', summary: 'Approved clearance expectation.', approvedAt: '2026-07-15T10:00:00.000Z', approvedBy: { role: R.transferAttorney, userId: 'attorney:f5' } } })
  assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model
}
function manifest(clearanceType = 'municipal') { const result = buildPropertyClearanceAdapterManifest({ adapterId: `clearance-${clearanceType}`, adapterVersion: '1.0.0', providerKey: clearanceType === 'municipal' ? 'municipal_portal' : 'scheme_management_portal', clearanceType, environments: [E.sandbox], authenticationTypes: [A.oauth2, A.signedWebhook], createdAt: '2026-07-15T08:00:00.000Z', createdBy: 'integration-admin:f5' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.manifest }
function connection(adapter) { const result = buildConveyancerIntegrationConnection({ connectionId: `connection:${adapter.adapterId}`, organisationId: 'organisation:f5', environment: E.sandbox, status: CONNECTION_STATUS.active, capabilities: adapter.capabilities, allowedLanes: ['transfer'], credentialReferenceId: 'vault:clearance:f5', secretVersion: '1', webhook: { endpointReferenceId: 'edge:clearance:f5', secretReferenceId: 'vault:webhook:f5', signingAlgorithm: 'hmac_sha256', replayWindowSeconds: 300 }, dataPolicy: { purpose: 'Obtain and reconcile property clearance evidence.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.personal, D.financial], retentionDays: 1825 }, verifiedAt: '2026-07-15T08:30:00.000Z', createdAt: '2026-07-15T08:15:00.000Z', createdBy: 'integration-admin:f5' }, { manifest: adapter }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.connection }
function profile(clearanceType, adapter, activeConnection, overrides = {}) { const providerType = clearanceType === 'municipal' ? 'municipality' : clearanceType === 'sectional_levy' ? 'body_corporate' : 'homeowners_association'; return buildPropertyClearanceProfile({ profileId: `profile:f5:${clearanceType}`, clearanceType, providerType, firmId: 'firm:transfer', providerReferenceId: `provider:${clearanceType}`, providerReferenceHash: hash('a'), accountNamespaceReferenceId: `namespace:${clearanceType}`, accountNamespaceHash: hash('b'), approvedAt: '2026-07-15T09:00:00.000Z', approvedBy: manager, createdAt: '2026-07-15T08:45:00.000Z', createdBy: 'integration-admin:f5', ...overrides }, { manifest: adapter, connection: activeConnection }) }
function request(context, overrides = {}) { return buildPropertyClearanceRequest({ requestId: `request:f5:${context.clearanceType}`, propertyReferenceId: 'property:f5', propertyReferenceHash: hash('c'), ownerReferenceId: 'seller:f5', ownerReferenceHash: hash('d'), accountReferenceId: `account:f5:${context.clearanceType}`, accountReferenceHash: hash('e'), periodEnd: '2026-10-31T00:00:00.000Z', preparedAt: '2026-07-15T11:00:00.000Z', preparedBy: secretary, approvedAt: '2026-07-15T11:30:00.000Z', approvedBy: attorney, approvalReferenceId: `approval:f5:${context.clearanceType}`, ...overrides }, { dependencyModel: context.dependencyModel, financialModel: context.finance, manifest: context.adapter, connection: context.activeConnection, profile: context.clearanceProfile }) }
function fixture(clearanceType = 'municipal', includeExpectation = true) { const dependencyModel = model(clearanceType); const finance = financialModel(clearanceType, includeExpectation); const adapter = manifest(clearanceType); const activeConnection = connection(adapter); const profileResult = profile(clearanceType, adapter, activeConnection); assert.equal(profileResult.ok, true, JSON.stringify(profileResult.errors)); const context = { clearanceType, dependencyModel, finance, adapter, activeConnection, clearanceProfile: profileResult.profile }; const requestResult = request(context); assert.equal(requestResult.ok, true, JSON.stringify(requestResult.errors)); return { ...context, clearanceRequest: requestResult.request } }
function inbound(value, type, sequence) { const minute = String(30 + sequence).padStart(2, '0'); const result = buildConveyancerIntegrationInboundEvent({ recordId: `clearance-event:f5:${value.clearanceType}:${sequence}`, type, lane: 'transfer', firmId: 'firm:transfer', idempotencyKey: `clearance-event-f5-${value.clearanceType}-${sequence}`, providerEventId: `provider-event:f5:${value.clearanceType}:${sequence}`, payloadReferenceId: `quarantine:clearance:f5:${sequence}`, payloadHash: hash(sequence % 2 ? 'a' : 'b'), dataPolicy: { purpose: 'Reconcile signed property-clearance evidence.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.personal, D.financial], retentionDays: 1825 }, signature: { verified: true, algorithm: 'hmac_sha256', keyReferenceId: 'vault:webhook:f5', nonceHash: hash('f'), payloadHash: hash(sequence % 2 ? 'a' : 'b'), signedAt: `2026-07-15T13:${minute}:00.000Z` }, occurredAt: `2026-07-15T13:${minute}:30.000Z`, receivedAt: `2026-07-15T13:${minute}:45.000Z` }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.event }
function outcome(value, status, revision, event, previousOutcome = null, overrides = {}) { return buildPropertyClearanceOutcome({ outcomeId: `clearance-outcome:f5:${value.clearanceType}:${revision}`, revision, providerClearanceReferenceId: `provider-clearance:f5:${value.clearanceType}`, providerClearanceReferenceHash: hash('9'), status, occurredAt: event.occurredAt, ...overrides }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, inboundEvent: event, previousOutcome }) }
function chain(value = fixture()) { const e1 = inbound(value, 'property_clearance_figures_received', 1); const figures = outcome(value, 'figures_issued', 1, e1, null, { figures: { referenceId: 'figures:f5', evidenceHash: hash('1'), amountDueMinor: 1500000, issuedAt: e1.occurredAt, validUntil: '2026-08-31T00:00:00.000Z' } }).outcome; const e2 = inbound(value, 'property_clearance_payment_evidence_acknowledged', 2); const payment = outcome(value, 'payment_evidence_acknowledged', 2, e2, figures, { paymentEvidence: { acknowledgementReferenceId: 'payment-ack:f5', evidenceHash: hash('2'), amountAcknowledgedMinor: 1500000, acknowledgedAt: e2.occurredAt } }).outcome; const e3 = inbound(value, 'property_clearance_certificate_received', 3); const certificate = outcome(value, 'certificate_issued', 3, e3, payment, { certificate: { state: 'available', documentReferenceId: 'certificate:f5', documentHash: hash('3'), settlementBasis: 'paid', issuedAt: e3.occurredAt, validUntil: '2026-09-30T00:00:00.000Z' } }).outcome; return { figures, figuresEvent: e1, payment, paymentEvent: e2, certificate, certificateEvent: e3 } }

test('creates governed municipal and community-scheme adapters and profiles', () => { for (const type of ['municipal', 'sectional_levy', 'hoa_levy']) { const adapter = manifest(type); const activeConnection = connection(adapter); const result = profile(type, adapter, activeConnection); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.profile.version, CONVEYANCER_MUNICIPAL_LEVY_INTEGRATION_VERSION); assert.equal(validatePropertyClearanceProfile(result.profile, { manifest: adapter, connection: activeConnection }).valid, true); assert.equal(adapter.category, type === 'municipal' ? 'municipal_authority' : 'community_scheme') } })
test('blocks mismatched provider types, unsafe profiles and non-manager approval', () => { const adapter = manifest('municipal'); const activeConnection = connection(adapter); assert.equal(profile('municipal', adapter, activeConnection, { providerType: 'body_corporate' }).errors.includes('property_clearance_profile_identity_invalid'), true); assert.equal(profile('municipal', adapter, activeConnection, { approvedBy: attorney }).errors.includes('property_clearance_profile_governance_invalid'), true); const unsafe = structuredClone(profile('municipal', adapter, activeConnection).profile); unsafe.providerRegistered = true; assert.equal(validatePropertyClearanceProfile(unsafe, { manifest: adapter, connection: activeConnection }).errors.includes('property_clearance_profile_side_effect_boundary_violated'), true) })
test('builds an independently approved E2 and D5-bound municipal request', () => { const value = fixture(); assert.equal(value.clearanceRequest.clearanceType, 'municipal'); assert.equal(value.clearanceRequest.financialModel.financialModelFingerprint, value.finance.fingerprint); assert.equal(validatePropertyClearanceRequest(value.clearanceRequest, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile }).valid, true) })
test('requires sectional and HOA tenure for their respective levy streams', () => { const sectional = fixture('sectional_levy'); assert.equal(sectional.clearanceRequest.clearanceType, 'sectional_levy'); const wrongModel = model('municipal'); const result = buildPropertyClearanceRequest({ ...sectional.clearanceRequest, requestId: 'wrong-tenure', preparedBy: secretary, approvedBy: attorney }, { dependencyModel: wrongModel, financialModel: sectional.finance, manifest: sectional.adapter, connection: sectional.activeConnection, profile: sectional.clearanceProfile }); assert.equal(result.errors.includes('property_clearance_request_tenure_invalid'), true); assert.equal(fixture('hoa_levy').clearanceRequest.clearanceType, 'hoa_levy') })
test('rejects self-approval, invalid periods and inline property or account data', () => { const value = fixture(); assert.equal(request(value, { preparedBy: attorney, approvedBy: attorney }).errors.includes('property_clearance_request_independent_approval_invalid'), true); assert.equal(request(value, { periodEnd: '2026-07-15T10:00:00.000Z' }).errors.includes('property_clearance_request_period_invalid'), true); assert.equal(request(value, { propertyAddress: 'SECRET' }).errors.includes('property_clearance_request_inline_private_data_prohibited'), true) })
test('prepares idempotent figures requests without dispatching them', () => { const value = fixture(); const input = { packetId: 'packet:f5:figures', action: 'figures_request', commandId: 'command:f5:figures', idempotencyKey: 'figures-f5', payloadReferenceId: 'approved-request-payload:f5', payloadHash: hash('4'), preparedAt: '2026-07-15T12:00:00.000Z', preparedBy: attorney, retentionDays: 1825 }; const first = buildPropertyClearanceCommandPacket(input, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest }); assert.equal(first.ok, true, JSON.stringify(first.errors)); assert.equal(first.outboundCommand.controls.dispatchPerformed, false); assert.equal(first.packet.controls.providerRequestDispatched, false); assert.equal(validatePropertyClearanceCommandPacket(first.packet, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, outboundCommand: first.outboundCommand }).valid, true); const duplicate = buildPropertyClearanceCommandPacket(input, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, existingCommands: [first.outboundCommand] }); assert.equal(duplicate.packet.status, 'duplicate') })
test('prepares payment evidence only against exact current figures', () => { const value = fixture(); const current = chain(value).figures; const result = buildPropertyClearanceCommandPacket({ packetId: 'packet:f5:payment', action: 'payment_evidence_submission', commandId: 'command:f5:payment', idempotencyKey: 'payment-f5', paymentAmountMinor: 1500000, payloadReferenceId: 'approved-payment-proof:f5', payloadHash: hash('5'), preparedAt: '2026-07-15T14:00:00.000Z', preparedBy: attorney, retentionDays: 1825 }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, currentOutcome: current }); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.outboundCommand.type, 'property_clearance_payment_evidence_submission_requested'); assert.equal(result.packet.controls.paymentEvidenceUploaded, false); const wrong = buildPropertyClearanceCommandPacket({ packetId: 'wrong', action: 'payment_evidence_submission', commandId: 'wrong-command', idempotencyKey: 'wrong-payment-f5', paymentAmountMinor: 1499999, payloadReferenceId: 'proof:wrong', payloadHash: hash('5'), preparedAt: '2026-07-15T14:00:00.000Z', preparedBy: attorney }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, currentOutcome: current }); assert.equal(wrong.errors.includes('property_clearance_payment_command_lineage_invalid'), true) })
test('reconciles figures, payment acknowledgement and certificate as separate states', () => { const value = fixture(); const result = chain(value); assert.equal(result.figures.financialReconciliation.status, 'matched'); assert.equal(result.figures.complianceEligible, false); assert.equal(result.payment.complianceEligible, false); assert.equal(result.certificate.complianceEligible, true); assert.equal(validatePropertyClearanceOutcome(result.certificate, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, inboundEvent: result.certificateEvent, previousOutcome: result.payment }).valid, true) })
test('surfaces D5 variances and missing expectations without changing D5', () => { const varianceValue = fixture('municipal'); const event = inbound(varianceValue, 'property_clearance_figures_received', 1); const variance = outcome(varianceValue, 'figures_issued', 1, event, null, { figures: { referenceId: 'figures:variance', evidenceHash: hash('6'), amountDueMinor: 1600000, issuedAt: event.occurredAt, validUntil: '2026-08-31T00:00:00.000Z' } }); assert.equal(variance.outcome.financialReconciliation.status, 'variance'); assert.equal(variance.outcome.financialReconciliation.varianceMinor, 100000); const noExpectation = fixture('municipal', false); const noEvent = inbound(noExpectation, 'property_clearance_figures_received', 1); const noMatch = outcome(noExpectation, 'figures_issued', 1, noEvent, null, { figures: { referenceId: 'figures:none', evidenceHash: hash('7'), amountDueMinor: 1600000, issuedAt: noEvent.occurredAt, validUntil: '2026-08-31T00:00:00.000Z' } }); assert.equal(noMatch.outcome.financialReconciliation.status, 'no_approved_expectation'); assert.equal(varianceValue.finance.lines.find((item) => item.lineType === LT.ratesClearance).amountMinor, 1500000) })
test('requires signed event types and exact provider lineage', () => { const value = fixture(); const result = chain(value); const wrongEvent = inbound(value, 'property_clearance_status_received', 4); assert.equal(validatePropertyClearanceOutcome(result.certificate, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, inboundEvent: wrongEvent, previousOutcome: result.payment }).errors.includes('property_clearance_outcome_inbound_evidence_invalid'), true); const forged = structuredClone(result.certificate); forged.providerClearanceReferenceHash = hash('8'); assert.equal(validatePropertyClearanceOutcome(forged, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, inboundEvent: result.certificateEvent, previousOutcome: result.payment }).errors.includes('property_clearance_outcome_transition_invalid'), true) })
test('does not treat figures, payment acknowledgement or expired certificates as compliance', () => { const value = fixture(); const result = chain(value); assert.equal(result.figures.complianceEligible, false); assert.equal(result.payment.complianceEligible, false); const event = inbound(value, 'property_clearance_certificate_received', 3); const expired = outcome(value, 'certificate_issued', 3, event, result.payment, { certificate: { state: 'available', documentReferenceId: 'expired:f5', documentHash: hash('3'), settlementBasis: 'paid', issuedAt: event.occurredAt, validUntil: '2026-07-15T13:00:00.000Z' } }); assert.equal(expired.ok, false); assert.equal(expired.errors.includes('property_clearance_certificate_invalid'), true) })
test('permits body-corporate satisfactory provision but not municipal provision', () => { const levy = fixture('sectional_levy'); const levyChain = chain(levy); const levyEvent = inbound(levy, 'property_clearance_certificate_received', 3); const levyCertificate = outcome(levy, 'certificate_issued', 3, levyEvent, levyChain.payment, { certificate: { state: 'available', documentReferenceId: 'levy:f5', documentHash: hash('3'), settlementBasis: 'provision_accepted', issuedAt: levyEvent.occurredAt, validUntil: '2026-09-30T00:00:00.000Z' } }); assert.equal(levyCertificate.ok, true, JSON.stringify(levyCertificate.errors)); const municipal = fixture(); const municipalChain = chain(municipal); const municipalEvent = inbound(municipal, 'property_clearance_certificate_received', 3); const municipalCertificate = outcome(municipal, 'certificate_issued', 3, municipalEvent, municipalChain.payment, { certificate: { state: 'available', documentReferenceId: 'municipal:f5', documentHash: hash('3'), settlementBasis: 'provision_accepted', issuedAt: municipalEvent.occurredAt, validUntil: '2026-09-30T00:00:00.000Z' } }); assert.equal(municipalCertificate.errors.includes('property_clearance_certificate_invalid'), true) })
test('creates E5-compatible evidence only after independent legal review', () => { const value = fixture(); const result = chain(value); const evidence = buildPropertyClearanceComplianceEvidence({ evidenceId: 'evidence:f5:municipal', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: reviewer, reviewReferenceId: 'review:f5:municipal' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, outcome: result.certificate, inboundEvent: result.certificateEvent, previousOutcome: result.payment }); assert.equal(evidence.ok, true, JSON.stringify(evidence.errors)); assert.equal(evidence.evidence.checkKey, 'rates_clearance'); assert.equal(evidence.evidence.validUntil, result.certificate.certificate.validUntil); assert.equal(evidence.evidence.controls.lodgementReadinessMutated, false); assert.equal(validatePropertyClearanceComplianceEvidence(evidence.evidence, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, outcome: result.certificate, inboundEvent: result.certificateEvent, previousOutcome: result.payment }).valid, true) })
test('requires explicit financial review when issued figures differ from D5', () => { const value = fixture(); const e1 = inbound(value, 'property_clearance_figures_received', 1); const figures = outcome(value, 'figures_issued', 1, e1, null, { figures: { referenceId: 'figures:variance', evidenceHash: hash('1'), amountDueMinor: 1600000, issuedAt: e1.occurredAt, validUntil: '2026-08-31T00:00:00.000Z' } }).outcome; const e2 = inbound(value, 'property_clearance_certificate_received', 2); const certificate = outcome(value, 'certificate_issued', 2, e2, figures, { certificate: { state: 'available', documentReferenceId: 'certificate:variance', documentHash: hash('3'), settlementBasis: 'paid', issuedAt: e2.occurredAt, validUntil: '2026-09-30T00:00:00.000Z' } }).outcome; const missing = buildPropertyClearanceComplianceEvidence({ evidenceId: 'evidence:variance', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: reviewer, reviewReferenceId: 'review:variance' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, outcome: certificate, inboundEvent: e2, previousOutcome: figures }); assert.equal(missing.errors.includes('property_clearance_compliance_financial_review_required'), true); const accepted = buildPropertyClearanceComplianceEvidence({ evidenceId: 'evidence:variance', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: reviewer, reviewReferenceId: 'review:variance', financialReviewReferenceId: 'd5-review:variance' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, outcome: certificate, inboundEvent: e2, previousOutcome: figures }); assert.equal(accepted.ok, true, JSON.stringify(accepted.errors)) })
test('maps levy evidence to the E5 levy check and retains revoked certificate lineage', () => { const value = fixture('sectional_levy'); const result = chain(value); const evidence = buildPropertyClearanceComplianceEvidence({ evidenceId: 'evidence:f5:levy', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: reviewer, reviewReferenceId: 'review:f5:levy' }, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, outcome: result.certificate, inboundEvent: result.certificateEvent, previousOutcome: result.payment }); assert.equal(evidence.evidence.checkKey, 'levy_clearance'); const event = inbound(value, 'property_clearance_status_received', 4); const revoked = outcome(value, 'revoked', 4, event, result.certificate); assert.equal(revoked.ok, true, JSON.stringify(revoked.errors)); assert.equal(revoked.outcome.complianceEligible, false); assert.equal(revoked.outcome.certificate.state, 'revoked'); assert.equal(revoked.outcome.certificate.documentHash, result.certificate.certificate.documentHash) })
test('detects outcome and side-effect tampering', () => { const value = fixture(); const result = chain(value); const changed = structuredClone(result.certificate); changed.complianceEligible = false; changed.controls.certificateSynthesised = true; const validation = validatePropertyClearanceOutcome(changed, { dependencyModel: value.dependencyModel, financialModel: value.finance, manifest: value.adapter, connection: value.activeConnection, profile: value.clearanceProfile, request: value.clearanceRequest, inboundEvent: result.certificateEvent, previousOutcome: result.payment }); assert.equal(validation.errors.includes('property_clearance_compliance_derivation_invalid'), true); assert.equal(validation.errors.includes('property_clearance_outcome_fingerprint_invalid'), true); assert.equal(validation.errors.includes('property_clearance_outcome_side_effect_boundary_violated'), true); assert.equal(PROPERTY_CLEARANCE_INTEGRATION_BOUNDARY.paymentInitiated, false) })

console.log('F5 municipal and levy integration tests passed.')
