import assert from 'node:assert/strict'
import { MATTER_PLAN_OWNER_ROLES as R } from '../../transactions/conveyancerMatterPlanContract.js'
import { buildConveyancerThreeRoleDependencyModel } from '../../transactions/conveyancerThreeRoleDependencyModel.js'
import { buildConveyancerGuaranteeWorkspace } from '../../../services/attorneyWorkflow/conveyancerGuaranteeWorkspace.js'
import {
  CONVEYANCER_INTEGRATION_AUTHENTICATION_TYPES as A,
  CONVEYANCER_INTEGRATION_CONNECTION_STATUSES as CS,
  CONVEYANCER_INTEGRATION_DATA_CLASSIFICATIONS as D,
  CONVEYANCER_INTEGRATION_ENVIRONMENTS as E,
  CONVEYANCER_INTEGRATION_LEGAL_BASES as B,
  buildConveyancerIntegrationConnection,
  buildConveyancerIntegrationInboundEvent,
} from '../conveyancerIntegrationFramework.js'
import {
  BANK_GUARANTEE_INTEGRATION_BOUNDARY,
  CONVEYANCER_BANK_GUARANTEE_INTEGRATION_VERSION,
  buildBankCancellationFigures,
  buildBankGuaranteeAdapterManifest,
  buildBankGuaranteeEvidence,
  buildBankGuaranteeOutcome,
  buildBankGuaranteeRequest,
  buildBankIntegrationProfile,
  buildBankLodgementApproval,
  buildBankLodgementApprovalEvidence,
  buildBankMatterInstruction,
  validateBankCancellationFigures,
  validateBankGuaranteeEvidence,
  validateBankGuaranteeOutcome,
  validateBankGuaranteeRequest,
  validateBankIntegrationProfile,
  validateBankLodgementApprovalEvidence,
  validateBankMatterInstruction,
} from '../conveyancerBankGuaranteeIntegration.js'

function test(name, fn) { try { fn(); console.log(`ok - ${name}`) } catch (error) { console.error(`not ok - ${name}`); throw error } }
const hash = (character) => character.repeat(64)
const bondManager = { role: R.firmManager, userId: 'manager:bond:f6', lane: 'bond', firmId: 'firm:bond' }
const cancellationManager = { role: R.firmManager, userId: 'manager:cancellation:f6', lane: 'cancellation', firmId: 'firm:cancellation' }
const bondSecretary = { role: R.secretary, userId: 'secretary:bond:f6', teamId: 'team:bond', lane: 'bond', firmId: 'firm:bond' }
const bondAttorney = { role: R.bondAttorney, userId: 'attorney:bond:f6', teamId: 'team:bond', lane: 'bond', firmId: 'firm:bond' }
const bondReviewer = { role: R.bondAttorney, userId: 'reviewer:bond:f6', teamId: 'team:bond', lane: 'bond', firmId: 'firm:bond' }
const bindings = {
  transfer: { firmId: 'firm:transfer', owner: { role: R.transferAttorney, userId: 'transfer:f6', teamId: 'team:transfer' } },
  bond: { firmId: 'firm:bond', owner: { role: R.bondAttorney, userId: 'attorney:bond:f6', teamId: 'team:bond' } },
  cancellation: { firmId: 'firm:cancellation', owner: { role: R.cancellationAttorney, userId: 'attorney:cancellation:f6', teamId: 'team:cancellation' } },
}

function model() { const result = buildConveyancerThreeRoleDependencyModel({ plan: { planId: 'plan:f6', planVersion: 1 }, transaction: { id: 'transaction:f6', organisation_id: 'organisation:f6', transaction_type: 'resale', property_tenure: 'freehold', finance_type: 'bond', seller_has_existing_bond: true, buyer_entity_type: 'individual', seller_entity_type: 'individual' }, roleBindings: bindings, generatedAt: '2026-07-15T08:00:00.000Z', generatedBy: { role: R.system, userId: 'system:f6' } }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model }
function manifest() { const result = buildBankGuaranteeAdapterManifest({ adapterId: 'bank-conveyancing:f6', adapterVersion: '1.0.0', providerKey: 'bank_conveyancing_gateway', environments: [E.sandbox], authenticationTypes: [A.oauth2, A.signedWebhook], createdAt: '2026-07-15T08:00:00.000Z', createdBy: 'integration-admin:f6' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.manifest }
function connection(adapter = manifest()) { const result = buildConveyancerIntegrationConnection({ connectionId: 'connection:bank:f6', organisationId: 'organisation:f6', environment: E.sandbox, status: CS.active, capabilities: adapter.capabilities, allowedLanes: ['bond', 'cancellation'], credentialReferenceId: 'vault:bank:f6', secretVersion: 'version:1', webhook: { endpointReferenceId: 'route:bank:f6', secretReferenceId: 'vault:webhook:f6', signingAlgorithm: 'hmac_sha256', replayWindowSeconds: 300 }, dataPolicy: { purpose: 'Reconcile bank instructions, guarantees, figures and approvals for appointed conveyancers.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.personal, D.financial, D.legallyPrivileged], retentionDays: 2555 }, verifiedAt: '2026-07-15T08:30:00.000Z', createdAt: '2026-07-15T08:15:00.000Z', createdBy: 'integration-admin:f6' }, { manifest: adapter }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.connection }
function profile(lane, value, overrides = {}) { const manager = lane === 'bond' ? bondManager : cancellationManager; return buildBankIntegrationProfile({ profileId: `profile:bank:f6:${lane}`, lane, firmId: `firm:${lane}`, bankReferenceId: 'bank:f6', bankReferenceHash: hash('a'), portalRegistrationReferenceId: `portal:f6:${lane}`, portalRegistrationHash: hash('b'), conveyancerPanelReferenceId: `panel:f6:${lane}`, conveyancerPanelHash: hash('c'), approvedAt: '2026-07-15T09:00:00.000Z', approvedBy: manager, createdAt: '2026-07-15T08:45:00.000Z', createdBy: 'integration-admin:f6', ...overrides }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }) }
function inbound(value, lane, type, sequence) { const minute = String(20 + sequence).padStart(2, '0'); const result = buildConveyancerIntegrationInboundEvent({ recordId: `bank-event:f6:${lane}:${sequence}`, type, lane, firmId: `firm:${lane}`, idempotencyKey: `bank-event-f6-${lane}-${sequence}`, providerEventId: `provider-event:f6:${lane}:${sequence}`, payloadReferenceId: `quarantine:bank:f6:${lane}:${sequence}`, payloadHash: hash(sequence % 2 ? 'd' : 'e'), dataPolicy: { purpose: 'Reconcile signed bank conveyancing evidence.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.personal, D.financial], retentionDays: 2555 }, signature: { verified: true, algorithm: 'hmac_sha256', keyReferenceId: 'vault:webhook:f6', nonceHash: hash('f'), payloadHash: hash(sequence % 2 ? 'd' : 'e'), signedAt: `2026-07-15T10:${minute}:00.000Z` }, occurredAt: `2026-07-15T10:${minute}:30.000Z`, receivedAt: `2026-07-15T10:${minute}:45.000Z` }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.event }
function instruction(value, lane, event, overrides = {}) { const selectedProfile = lane === 'bond' ? value.bondProfile : value.cancellationProfile; return buildBankMatterInstruction({ instructionId: `instruction:f6:${lane}`, status: 'active', providerInstructionReferenceId: `provider-instruction:f6:${lane}`, providerInstructionReferenceHash: hash('1'), appointmentReferenceId: `appointment:f6:${lane}`, appointmentEvidenceHash: hash('2'), propertyReferenceId: 'property:f6', propertyReferenceHash: hash('3'), customerReferenceId: lane === 'bond' ? 'buyer:f6' : 'seller:f6', customerReferenceHash: hash('4'), approvedAmountMinor: lane === 'bond' ? 180000000 : undefined, currency: 'ZAR', occurredAt: event.occurredAt, ...overrides }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: selectedProfile, inboundEvent: event }) }
function workspace(value) { const result = buildConveyancerGuaranteeWorkspace({ dependencyModel: value.dependencyModel, requirements: [{ requirementId: 'requirement:purchase:f6', requirementType: 'purchase_price', status: 'current', ownerLane: 'transfer', currency: 'ZAR', amountMinor: 180000000, beneficiaryReferenceHash: hash('5'), wordingHash: hash('6'), sourceReferenceId: 'otp:f6', sourceEvidenceHash: hash('7'), effectiveAt: '2026-07-15T09:30:00.000Z' }], instruments: [], allocations: [], viewer: bondAttorney, asOf: '2026-07-15T11:00:00.000Z', expectedLodgementAt: '2026-08-15T09:00:00.000Z' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.workspace }
function guaranteeRequest(value, overrides = {}, context = {}) { return buildBankGuaranteeRequest({ requestId: 'guarantee-request:f6:r1', action: 'issue', requirementId: 'requirement:purchase:f6', commandId: 'guarantee-command:f6:r1', idempotencyKey: 'guarantee-f6-r1', payloadReferenceId: 'approved-guarantee-request:f6', payloadHash: hash('8'), preparedAt: '2026-07-15T11:30:00.000Z', preparedBy: bondSecretary, approvedAt: '2026-07-15T12:00:00.000Z', approvedBy: bondAttorney, approvalReferenceId: 'approval:guarantee:f6', retentionDays: 2555, ...overrides }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, guaranteeWorkspace: value.guaranteeWorkspace, previousGuarantee: context.previousGuarantee || null, existingCommands: context.existingCommands || [] }) }
function guaranteeOutcome(value, requestValue, event, overrides = {}, previousGuarantee = null) { return buildBankGuaranteeOutcome({ guaranteeId: previousGuarantee ? 'guarantee:f6:r2' : 'guarantee:f6:r1', revision: previousGuarantee ? 2 : 1, status: 'issued', providerGuaranteeReferenceId: previousGuarantee ? 'bank-guarantee:f6:r2' : 'bank-guarantee:f6:r1', providerGuaranteeReferenceHash: previousGuarantee ? hash('b') : hash('9'), amountMinor: 180000000, currency: 'ZAR', beneficiaryReferenceHash: hash('5'), wordingHash: hash('6'), documentReferenceId: previousGuarantee ? 'guarantee-document:f6:r2' : 'guarantee-document:f6:r1', documentHash: previousGuarantee ? hash('c') : hash('a'), issuedAt: event.occurredAt, expiresAt: '2026-09-30T00:00:00.000Z', occurredAt: event.occurredAt, ...overrides }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, request: requestValue, inboundEvent: event, previousGuarantee }) }
function fixture() { const dependencyModel = model(); const adapter = manifest(); const activeConnection = connection(adapter); const base = { dependencyModel, adapter, activeConnection }; const bondProfileResult = profile('bond', base); const cancellationProfileResult = profile('cancellation', base); assert.equal(bondProfileResult.ok, true, JSON.stringify(bondProfileResult.errors)); assert.equal(cancellationProfileResult.ok, true, JSON.stringify(cancellationProfileResult.errors)); const value = { ...base, bondProfile: bondProfileResult.profile, cancellationProfile: cancellationProfileResult.profile }; const bondEvent = inbound(value, 'bond', 'bank_instruction_received', 1); const cancellationEvent = inbound(value, 'cancellation', 'bank_instruction_received', 2); const bondInstructionResult = instruction(value, 'bond', bondEvent); const cancellationInstructionResult = instruction(value, 'cancellation', cancellationEvent); assert.equal(bondInstructionResult.ok, true, JSON.stringify(bondInstructionResult.errors)); assert.equal(cancellationInstructionResult.ok, true, JSON.stringify(cancellationInstructionResult.errors)); value.bondInstruction = bondInstructionResult.instruction; value.cancellationInstruction = cancellationInstructionResult.instruction; value.bondInstructionEvent = bondEvent; value.cancellationInstructionEvent = cancellationEvent; value.guaranteeWorkspace = workspace(value); return value }

test('creates a governed bank adapter and lane-specific appointed-firm profiles', () => { const value = fixture(); assert.equal(value.adapter.category, 'banking'); assert.equal(value.bondProfile.version, CONVEYANCER_BANK_GUARANTEE_INTEGRATION_VERSION); assert.equal(validateBankIntegrationProfile(value.bondProfile, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }).valid, true); assert.equal(validateBankIntegrationProfile(value.cancellationProfile, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }).valid, true) })
test('blocks wrong appointed firms, non-manager profiles and profile side effects', () => { const value = fixture(); assert.equal(profile('bond', value, { firmId: 'firm:other' }).errors.includes('bank_profile_lane_firm_binding_invalid'), true); assert.equal(profile('bond', value, { approvedBy: bondAttorney }).errors.includes('bank_profile_governance_invalid'), true); const unsafe = structuredClone(value.bondProfile); unsafe.panelAppointmentPerformed = true; assert.equal(validateBankIntegrationProfile(unsafe, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection }).errors.includes('bank_profile_side_effect_boundary_violated'), true) })
test('reconciles signed bank appointments without selecting attorneys', () => { const value = fixture(); assert.equal(value.bondInstruction.appointedFirmId, 'firm:bond'); assert.equal(value.cancellationInstruction.appointedFirmId, 'firm:cancellation'); assert.equal(value.bondInstruction.controls.attorneySelectedByPlatform, false); assert.equal(validateBankMatterInstruction(value.bondInstruction, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, inboundEvent: value.bondInstructionEvent }).valid, true) })
test('rejects wrong-lane instruction events and inline bank or customer data', () => { const value = fixture(); const wrongEvent = inbound(value, 'cancellation', 'bank_instruction_received', 3); const wrong = buildBankMatterInstruction({ instructionId: 'instruction:wrong', providerInstructionReferenceId: 'wrong', providerInstructionReferenceHash: hash('1'), appointmentReferenceId: 'wrong', appointmentEvidenceHash: hash('2'), propertyReferenceId: 'property:f6', propertyReferenceHash: hash('3'), customerReferenceId: 'buyer:f6', customerReferenceHash: hash('4'), approvedAmountMinor: 180000000 }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, inboundEvent: wrongEvent }); assert.equal(wrong.errors.includes('bank_instruction_inbound_evidence_invalid'), true); const privateData = instruction(value, 'bond', value.bondInstructionEvent, { customerName: 'SECRET' }); assert.equal(privateData.errors.includes('bank_instruction_inline_private_data_prohibited'), true) })
test('turns signed cancellation figures into an exact E4 requirement', () => { const value = fixture(); const event = inbound(value, 'cancellation', 'bank_cancellation_figures_received', 4); const result = buildBankCancellationFigures({ figuresId: 'figures:f6:r1', providerFiguresReferenceId: 'provider-figures:f6:r1', providerFiguresReferenceHash: hash('d'), amountDueMinor: 72500000, currency: 'ZAR', beneficiaryReferenceHash: hash('e'), wordingHash: hash('f'), documentReferenceId: 'figures-document:f6:r1', documentHash: hash('1'), issuedAt: event.occurredAt, expiresAt: '2026-08-31T00:00:00.000Z' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.cancellationProfile, instruction: value.cancellationInstruction, inboundEvent: event }); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.figures.e4Requirement.requirementType, 'cancellation_settlement'); assert.equal(result.figures.e4Requirement.amountMinor, 72500000); assert.equal(result.figures.controls.cancellationFiguresCalculated, false); assert.equal(validateBankCancellationFigures(result.figures, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.cancellationProfile, instruction: value.cancellationInstruction, inboundEvent: event }).valid, true) })
test('requires valid cancellation-figure expiry and append-only replacement lineage', () => { const value = fixture(); const e1 = inbound(value, 'cancellation', 'bank_cancellation_figures_received', 4); const first = buildBankCancellationFigures({ figuresId: 'figures:f6:r1', providerFiguresReferenceId: 'provider-figures:f6:r1', providerFiguresReferenceHash: hash('d'), amountDueMinor: 72500000, beneficiaryReferenceHash: hash('e'), wordingHash: hash('f'), documentReferenceId: 'figures-document:f6:r1', documentHash: hash('1'), issuedAt: e1.occurredAt, expiresAt: '2026-08-31T00:00:00.000Z' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.cancellationProfile, instruction: value.cancellationInstruction, inboundEvent: e1 }).figures; const e2 = inbound(value, 'cancellation', 'bank_cancellation_figures_received', 5); const replacement = buildBankCancellationFigures({ figuresId: 'figures:f6:r2', revision: 2, providerFiguresReferenceId: 'provider-figures:f6:r2', providerFiguresReferenceHash: hash('2'), amountDueMinor: 72600000, beneficiaryReferenceHash: hash('e'), wordingHash: hash('f'), documentReferenceId: 'figures-document:f6:r2', documentHash: hash('3'), issuedAt: e2.occurredAt, expiresAt: '2026-09-30T00:00:00.000Z' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.cancellationProfile, instruction: value.cancellationInstruction, inboundEvent: e2, previousFigures: first }); assert.equal(replacement.ok, true, JSON.stringify(replacement.errors)); assert.equal(replacement.figures.e4Requirement.previousRequirementId, first.figuresId); const expired = buildBankCancellationFigures({ figuresId: 'bad', providerFiguresReferenceId: 'bad', providerFiguresReferenceHash: hash('d'), amountDueMinor: 1, beneficiaryReferenceHash: hash('e'), wordingHash: hash('f'), documentReferenceId: 'bad', documentHash: hash('1'), issuedAt: e1.occurredAt, expiresAt: '2026-07-01T00:00:00.000Z' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.cancellationProfile, instruction: value.cancellationInstruction, inboundEvent: e1 }); assert.equal(expired.errors.includes('bank_cancellation_figures_identity_invalid'), true) })
test('prepares an independently approved idempotent guarantee issue command', () => { const value = fixture(); const first = guaranteeRequest(value); assert.equal(first.ok, true, JSON.stringify(first.errors)); assert.equal(first.request.amountMinor, 180000000); assert.equal(first.outboundCommand.type, 'bank_guarantee_issue_requested'); assert.equal(first.outboundCommand.controls.dispatchPerformed, false); assert.equal(first.request.controls.outboundDispatchPerformed, false); assert.equal(validateBankGuaranteeRequest(first.request, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, guaranteeWorkspace: value.guaranteeWorkspace, outboundCommand: first.outboundCommand }).valid, true); const duplicate = guaranteeRequest(value, {}, { existingCommands: [first.outboundCommand] }); assert.equal(duplicate.request.status, 'duplicate') })
test('blocks self-approval, altered E4 requirements and cancellation-lane guarantee issuance', () => { const value = fixture(); assert.equal(guaranteeRequest(value, { preparedBy: bondAttorney, approvedBy: bondAttorney }).errors.includes('bank_guarantee_request_independent_approval_invalid'), true); const changed = structuredClone(value.guaranteeWorkspace); changed.requirements[0].remainingMinor = 1; assert.equal(guaranteeRequest({ ...value, guaranteeWorkspace: changed }).errors.includes('bank_guarantee_request_workspace_invalid'), true); const wrongInstruction = { ...value.bondInstruction, lane: 'cancellation' }; const result = buildBankGuaranteeRequest({ requestId: 'wrong', requirementId: 'requirement:purchase:f6', commandId: 'wrong', idempotencyKey: 'wrong-f6', payloadReferenceId: 'wrong', payloadHash: hash('8'), preparedAt: '2026-07-15T11:30:00.000Z', preparedBy: bondSecretary, approvedAt: '2026-07-15T12:00:00.000Z', approvedBy: bondAttorney, approvalReferenceId: 'wrong' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: wrongInstruction, guaranteeWorkspace: value.guaranteeWorkspace }); assert.equal(result.errors.includes('bank_guarantee_request_instruction_invalid'), true) })
test('reconciles a signed guarantee without accepting it automatically', () => { const value = fixture(); const requestResult = guaranteeRequest(value); const event = inbound(value, 'bond', 'bank_guarantee_received', 6); const result = guaranteeOutcome(value, requestResult.request, event); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.guarantee.reviewEligible, true); assert.equal(result.guarantee.controls.guaranteeAcceptedAutomatically, false); assert.equal(validateBankGuaranteeOutcome(result.guarantee, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, request: requestResult.request, inboundEvent: event }).valid, true) })
test('rejects changed amount, beneficiary, wording, expiry and wrong event types', () => { const value = fixture(); const requestResult = guaranteeRequest(value); const event = inbound(value, 'bond', 'bank_guarantee_received', 6); for (const overrides of [{ amountMinor: 179999999 }, { beneficiaryReferenceHash: hash('2') }, { wordingHash: hash('3') }, { expiresAt: '2026-07-01T00:00:00.000Z' }]) assert.equal(guaranteeOutcome(value, requestResult.request, event, overrides).errors.includes('bank_guarantee_outcome_terms_invalid'), true); const wrongEvent = inbound(value, 'bond', 'bank_guarantee_status_received', 7); assert.equal(guaranteeOutcome(value, requestResult.request, wrongEvent).errors.includes('bank_guarantee_outcome_inbound_evidence_invalid'), true) })
test('creates an E4 bank-guarantee instrument only after legal review', () => { const value = fixture(); const requestResult = guaranteeRequest(value); const event = inbound(value, 'bond', 'bank_guarantee_received', 6); const guarantee = guaranteeOutcome(value, requestResult.request, event).guarantee; const evidence = buildBankGuaranteeEvidence({ evidenceId: 'guarantee-evidence:f6', reviewedAt: '2026-07-15T13:00:00.000Z', reviewedBy: bondReviewer, reviewReferenceId: 'review:guarantee:f6' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, request: requestResult.request, guarantee, inboundEvent: event }); assert.equal(evidence.ok, true, JSON.stringify(evidence.errors)); assert.equal(evidence.evidence.instrument.instrumentType, 'bank_guarantee'); assert.equal(evidence.evidence.instrument.issuerFirmId, 'firm:bond'); assert.equal(evidence.evidence.controls.guaranteeWorkspaceMutated, false); assert.equal(validateBankGuaranteeEvidence(evidence.evidence, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, request: requestResult.request, guarantee, inboundEvent: event }).valid, true) })
test('supports reviewed append-only guarantee replacement with a new bank reference', () => { const value = fixture(); const initialRequest = guaranteeRequest(value); const e1 = inbound(value, 'bond', 'bank_guarantee_received', 6); const first = guaranteeOutcome(value, initialRequest.request, e1).guarantee; const replacementRequest = guaranteeRequest(value, { requestId: 'guarantee-request:f6:r2', action: 'replace', commandId: 'guarantee-command:f6:r2', idempotencyKey: 'guarantee-f6-r2', changeReason: 'Bank replaced the expiry and document.' }, { previousGuarantee: first }); assert.equal(replacementRequest.ok, true, JSON.stringify(replacementRequest.errors)); assert.equal(replacementRequest.outboundCommand.type, 'bank_guarantee_replacement_requested'); const e2 = inbound(value, 'bond', 'bank_guarantee_received', 8); const replacement = guaranteeOutcome(value, replacementRequest.request, e2, {}, first); assert.equal(replacement.ok, true, JSON.stringify(replacement.errors)); assert.notEqual(replacement.guarantee.providerGuaranteeReferenceHash, first.providerGuaranteeReferenceHash); const evidence = buildBankGuaranteeEvidence({ evidenceId: 'replacement-evidence:f6', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: bondReviewer, reviewReferenceId: 'review:replacement:f6' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, request: replacementRequest.request, guarantee: replacement.guarantee, inboundEvent: e2, previousGuarantee: first }); assert.equal(evidence.evidence.instrument.previousInstrumentId, first.guaranteeId) })
test('removes guarantee review eligibility on a signed revocation and retains the document', () => { const value = fixture(); const requestResult = guaranteeRequest(value); const e1 = inbound(value, 'bond', 'bank_guarantee_received', 6); const issued = guaranteeOutcome(value, requestResult.request, e1).guarantee; const e2 = inbound(value, 'bond', 'bank_guarantee_status_received', 7); const revoked = guaranteeOutcome(value, requestResult.request, e2, { guaranteeId: 'guarantee:f6:revoked', revision: 2, status: 'revoked' }, issued); assert.equal(revoked.ok, true, JSON.stringify(revoked.errors)); assert.equal(revoked.guarantee.reviewEligible, false); assert.equal(revoked.guarantee.documentHash, issued.documentHash) })
test('creates E5 bank-approval evidence only after signed approval and legal review', () => { const value = fixture(); const event = inbound(value, 'bond', 'bank_approval_to_lodge_received', 9); const approvalResult = buildBankLodgementApproval({ approvalId: 'lodgement-approval:f6:r1', status: 'approved', providerApprovalReferenceId: 'provider-approval:f6', providerApprovalReferenceHash: hash('4'), documentReferenceId: 'approval-document:f6', documentHash: hash('5'), conditionsEvidenceReferenceId: 'conditions:f6', conditionsEvidenceHash: hash('6'), approvedAt: event.occurredAt, validUntil: '2026-09-30T00:00:00.000Z' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, inboundEvent: event }); assert.equal(approvalResult.ok, true, JSON.stringify(approvalResult.errors)); assert.equal(approvalResult.approval.reviewEligible, true); const evidence = buildBankLodgementApprovalEvidence({ evidenceId: 'lodgement-evidence:f6', reviewedAt: '2026-07-15T14:00:00.000Z', reviewedBy: bondReviewer, reviewReferenceId: 'review:lodgement:f6' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, approval: approvalResult.approval, inboundEvent: event }); assert.equal(evidence.ok, true, JSON.stringify(evidence.errors)); assert.equal(evidence.evidence.checkKey, 'bank_approval_to_lodge'); assert.equal(evidence.evidence.validUntil, approvalResult.approval.validUntil); assert.equal(evidence.evidence.controls.lodgementReadinessMutated, false); assert.equal(validateBankLodgementApprovalEvidence(evidence.evidence, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, approval: approvalResult.approval, inboundEvent: event }).valid, true) })
test('revocation removes bank-approval eligibility while retaining document lineage', () => { const value = fixture(); const e1 = inbound(value, 'bond', 'bank_approval_to_lodge_received', 9); const approved = buildBankLodgementApproval({ approvalId: 'lodgement-approval:f6:r1', status: 'approved', providerApprovalReferenceId: 'provider-approval:f6', providerApprovalReferenceHash: hash('4'), documentReferenceId: 'approval-document:f6', documentHash: hash('5'), conditionsEvidenceReferenceId: 'conditions:f6', conditionsEvidenceHash: hash('6'), approvedAt: e1.occurredAt, validUntil: '2026-09-30T00:00:00.000Z' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, inboundEvent: e1 }).approval; const e2 = inbound(value, 'bond', 'bank_approval_to_lodge_status_received', 10); const revoked = buildBankLodgementApproval({ approvalId: 'lodgement-approval:f6:r2', revision: 2, status: 'revoked' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, inboundEvent: e2, previousApproval: approved }); assert.equal(revoked.ok, true, JSON.stringify(revoked.errors)); assert.equal(revoked.approval.reviewEligible, false); assert.equal(revoked.approval.documentHash, approved.documentHash); const evidence = buildBankLodgementApprovalEvidence({ evidenceId: 'revoked', reviewedAt: '2026-07-15T15:00:00.000Z', reviewedBy: bondReviewer, reviewReferenceId: 'review:revoked' }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, approval: revoked.approval, inboundEvent: e2, previousApproval: approved }); assert.equal(evidence.errors.includes('bank_lodgement_evidence_eligible_approval_required'), true) })
test('detects guarantee, approval and side-effect tampering', () => { const value = fixture(); const requestResult = guaranteeRequest(value); const event = inbound(value, 'bond', 'bank_guarantee_received', 6); const guarantee = guaranteeOutcome(value, requestResult.request, event).guarantee; const changed = structuredClone(guarantee); changed.reviewEligible = false; changed.controls.guaranteeIssuedByPlatform = true; const validation = validateBankGuaranteeOutcome(changed, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.bondProfile, instruction: value.bondInstruction, request: requestResult.request, inboundEvent: event }); assert.equal(validation.errors.includes('bank_guarantee_outcome_review_eligibility_invalid'), true); assert.equal(validation.errors.includes('bank_guarantee_outcome_fingerprint_invalid'), true); assert.equal(validation.errors.includes('bank_guarantee_outcome_side_effect_boundary_violated'), true); assert.equal(BANK_GUARANTEE_INTEGRATION_BOUNDARY.paymentInitiated, false) })

console.log('F6 bank and guarantee integration tests passed.')
