import assert from 'node:assert/strict'
import {
  CONVEYANCER_INTEGRATION_CAPABILITIES as C,
  CONVEYANCER_INTEGRATION_CONNECTION_STATUSES as S,
  CONVEYANCER_INTEGRATION_DATA_CLASSIFICATIONS as D,
  CONVEYANCER_INTEGRATION_ENVIRONMENTS as E,
  CONVEYANCER_INTEGRATION_LEGAL_BASES as B,
  CONVEYANCER_INTEGRATION_PROVIDER_CATEGORIES as P,
  buildConveyancerIntegrationAdapterManifest,
  buildConveyancerIntegrationConnection,
} from '../conveyancerIntegrationFramework.js'
import {
  CONVEYANCER_INTEGRATION_ASSURANCE_BOUNDARY,
  CONVEYANCER_INTEGRATION_ASSURANCE_VERSION,
  CONVEYANCER_INTEGRATION_MINIMUM_SCENARIOS,
  CONVEYANCER_INTEGRATION_PHASE_VERSIONS,
  CONVEYANCER_INTEGRATION_REQUIRED_PROBES,
  assureConveyancerIntegrationRelease,
  buildConveyancerIntegrationPhaseCheckpoint,
  buildConveyancerIntegrationPilotManifest,
  evaluateConveyancerIntegrationPilot,
  serializeConveyancerIntegrationAssuranceEvidence,
  validateConveyancerIntegrationPhaseCheckpoint,
} from '../conveyancerIntegrationAssurance.js'

function test(name, fn) { try { fn(); console.log(`ok - ${name}`) } catch (error) { console.error(`not ok - ${name}`); throw error } }
const hash = (character) => character.repeat(64)
const commit = 'a'.repeat(40); const createdAt = '2026-07-15T08:00:00.000Z'; const organisationId = 'organisation:f8'
const categoryConfig = {
  [P.practiceManagement]: [C.receivePracticeSnapshot, 'practice_snapshot_received'],
  [P.trustAccounting]: [C.receiveTrustLedgerSnapshot, 'trust_ledger_snapshot_received'],
  [P.taxAuthority]: [C.receiveTransferDutyOutcome, 'transfer_duty_outcome_received'],
  [P.municipalAuthority]: [C.receivePropertyClearanceOutcome, 'property_clearance_outcome_received'],
  [P.banking]: [C.receiveBankInstruction, 'bank_instruction_received'],
  [P.deeds]: [C.receiveDeedsEvent, 'deeds_event_received'],
}
const phaseCategory = { F2: P.practiceManagement, F3: P.trustAccounting, F4: P.taxAuthority, F5: P.municipalAuthority, F6: P.banking, F7: P.deeds }

function adapter(category, index) { const [capability, type] = categoryConfig[category]; const result = buildConveyancerIntegrationAdapterManifest({ adapterId: `adapter-${index}`, adapterVersion: '1.0.0', providerKey: `provider-${index}`, category, environments: [E.sandbox, E.production], authenticationTypes: ['signed_webhook'], capabilities: [capability], inboundEvents: [{ type, capability, allowedLanes: category === P.banking ? ['bond'] : ['transfer'] }], outboundCommands: [], createdAt, createdBy: 'integration-governance:f8' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.manifest }
function activeConnection(manifest, index, status = S.active) { const lane = manifest.category === P.banking ? 'bond' : 'transfer'; const result = buildConveyancerIntegrationConnection({ connectionId: `connection-${index}`, organisationId, environment: E.production, status, capabilities: manifest.capabilities, allowedLanes: [lane], credentialReferenceId: `vault:credential:${index}`, secretVersion: 'version:1', webhook: { endpointReferenceId: `route:webhook:${index}`, secretReferenceId: `vault:webhook:${index}`, signingAlgorithm: 'hmac_sha256', replayWindowSeconds: 300 }, dataPolicy: { purpose: 'Run the controlled F8 integration pilot.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential], retentionDays: 365 }, verifiedAt: '2026-07-15T08:30:00.000Z', createdAt, createdBy: 'integration-admin:f8' }, { manifest }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.connection }
function inventory(connectionStatus = S.active) { const manifests = Object.keys(categoryConfig).map(adapter); return { manifests, connections: manifests.map((manifest, index) => activeConnection(manifest, index, connectionStatus)) } }
function probes(overrides = {}) { return { ...Object.fromEntries(CONVEYANCER_INTEGRATION_REQUIRED_PROBES.map((probe) => [probe, true])), ...overrides } }
function checkpoint(phase, manifests, overrides = {}) { const category = phaseCategory[phase]; const adapterFingerprints = category ? manifests.filter((item) => item.category === category).map((item) => item.fingerprint) : manifests.map((item) => item.fingerprint); const result = buildConveyancerIntegrationPhaseCheckpoint({ checkpointId: `checkpoint:${phase}`, phase, phaseVersion: CONVEYANCER_INTEGRATION_PHASE_VERSIONS[phase], releaseCandidateId: 'release:f8:1', buildId: 'build:f8:1', sourceCommitHash: commit, environment: E.production, suiteId: `suite:${phase}`, suiteVersion: '1.0.0', scenarioCount: CONVEYANCER_INTEGRATION_MINIMUM_SCENARIOS[phase], passedCount: CONVEYANCER_INTEGRATION_MINIMUM_SCENARIOS[phase], failedCount: 0, skippedCount: 0, probes: probes(), adapterFingerprints, evidenceReferenceId: `evidence:${phase}`, evidenceHash: hash(phase === 'F1' ? '1' : String(Number(phase.slice(1)) + 1)), executedAt: '2026-07-15T09:00:00.000Z', executedBy: { role: 'integration_engineer', userId: `engineer:${phase}`, organisationId }, reviewedAt: '2026-07-15T10:00:00.000Z', reviewedBy: { role: 'firm_manager', userId: `manager:${phase}`, organisationId }, ...overrides }); return result }
function fixture(connectionStatus = S.active) { const { manifests, connections } = inventory(connectionStatus); const checkpoints = Object.keys(CONVEYANCER_INTEGRATION_PHASE_VERSIONS).map((phase) => { const result = checkpoint(phase, manifests); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.checkpoint }); return { assuranceId: 'assurance:f8', checkpoints, manifests, connections, assuredAt: '2026-07-15T11:00:00.000Z' } }

test('certifies one immutable release candidate across F1-F7', () => { const result = assureConveyancerIntegrationRelease(fixture()); assert.equal(result.version, CONVEYANCER_INTEGRATION_ASSURANCE_VERSION); assert.equal(result.decision, 'ready', JSON.stringify(result.findings)); assert.deepEqual(result.phaseStatus, { F1: true, F2: true, F3: true, F4: true, F5: true, F6: true, F7: true }); assert.equal(result.controls, CONVEYANCER_INTEGRATION_ASSURANCE_BOUNDARY); assert.equal(Object.isFrozen(result), true) })
test('requires exact phase versions and minimum scenario coverage', () => { const base = inventory(); const version = checkpoint('F6', base.manifests, { phaseVersion: 'old' }); assert.equal(version.ok, false); assert.equal(version.errors.includes('integration_checkpoint_identity_invalid'), true); const coverage = checkpoint('F7', base.manifests, { scenarioCount: 12, passedCount: 12 }); assert.equal(coverage.errors.includes('integration_checkpoint_scenario_gate_failed'), true) })
test('fails closed on skipped tests, probe failures and open exceptions', () => { const base = inventory(); const skipped = checkpoint('F4', base.manifests, { skippedCount: 1 }); assert.equal(skipped.ok, false); const badProbe = checkpoint('F4', base.manifests, { probes: probes({ tamperDetection: false }) }); assert.equal(badProbe.errors.includes('integration_checkpoint_control_probe_failed'), true); const exception = checkpoint('F4', base.manifests, { exceptions: ['known_failure'] }); assert.equal(exception.errors.includes('integration_checkpoint_open_exception'), true) })
test('enforces independent manager review in the same organisation', () => { const base = inventory(); const result = checkpoint('F2', base.manifests, { reviewedBy: { role: 'integration_engineer', userId: 'engineer:F2', organisationId } }); assert.equal(result.ok, false); assert.equal(result.errors.includes('integration_checkpoint_independent_review_invalid'), true) })
test('blocks missing or duplicate phase checkpoints', () => { const clean = fixture(); const missing = assureConveyancerIntegrationRelease({ ...clean, checkpoints: clean.checkpoints.slice(0, 6) }); assert.equal(missing.decision, 'blocked'); assert.equal(missing.findings.some((item) => item.code === 'integration_phase_checkpoint_missing'), true); const duplicate = assureConveyancerIntegrationRelease({ ...clean, checkpoints: [...clean.checkpoints, clean.checkpoints[0]] }); assert.equal(duplicate.findings.some((item) => item.code === 'integration_phase_checkpoint_duplicate'), true) })
test('blocks mixed commits, builds, environments and organisations', () => { const clean = fixture(); const changed = structuredClone(clean.checkpoints[6]); const rebuilt = buildConveyancerIntegrationPhaseCheckpoint({ ...changed, buildId: 'build:other', fingerprint: undefined }); assert.equal(rebuilt.ok, true); const result = assureConveyancerIntegrationRelease({ ...clean, checkpoints: [...clean.checkpoints.slice(0, 6), rebuilt.checkpoint] }); assert.equal(result.decision, 'blocked'); assert.equal(result.findings.some((item) => item.code === 'integration_release_binding_inconsistent'), true) })
test('validates concrete F1 manifests and connections', () => { const clean = fixture(); const tampered = structuredClone(clean.manifests[0]); tampered.providerKey = 'changed'; const result = assureConveyancerIntegrationRelease({ ...clean, manifests: [tampered, ...clean.manifests.slice(1)] }); assert.equal(result.decision, 'blocked'); assert.equal(result.findings.some((item) => item.code === 'integration_adapter_invalid'), true) })
test('requires each F2-F7 checkpoint to bind its provider category', () => { const clean = fixture(); const f6 = clean.checkpoints.find((item) => item.phase === 'F6'); const rebuilt = buildConveyancerIntegrationPhaseCheckpoint({ ...f6, adapterFingerprints: [clean.manifests[0].fingerprint] }); assert.equal(rebuilt.ok, true); const result = assureConveyancerIntegrationRelease({ ...clean, checkpoints: clean.checkpoints.map((item) => item.phase === 'F6' ? rebuilt.checkpoint : item) }); assert.equal(result.decision, 'blocked'); assert.equal(result.findings.some((item) => item.code === 'integration_checkpoint_adapter_binding_invalid' && item.phase === 'F6'), true) })
test('observes valid inactive connections without certifying production readiness', () => { const result = assureConveyancerIntegrationRelease(fixture(S.verified)); assert.equal(result.decision, 'observe'); assert.equal(result.counts.warnings, 6); assert.equal(result.findings.every((item) => item.severity === 'warning'), true) })
test('detects checkpoint fingerprint tampering', () => { const clean = fixture(); const changed = structuredClone(clean.checkpoints[0]); changed.scenarioCount += 1; const validation = validateConveyancerIntegrationPhaseCheckpoint(changed); assert.equal(validation.errors.includes('integration_checkpoint_fingerprint_invalid'), true); assert.equal(assureConveyancerIntegrationRelease({ ...clean, checkpoints: [changed, ...clean.checkpoints.slice(1)] }).decision, 'blocked') })
test('applies strict go, observe and hold pilot thresholds', () => { const ready = assureConveyancerIntegrationRelease(fixture()); assert.equal(evaluateConveyancerIntegrationPilot({ scenarios: [{ scenarioId: 'full', assurance: ready }], operationalMetrics: {} }).decision, 'go'); assert.equal(evaluateConveyancerIntegrationPilot({ scenarios: [{ scenarioId: 'full', assurance: ready }], operationalMetrics: { reconciliationBacklogRate: 0.1 } }).decision, 'observe'); assert.equal(evaluateConveyancerIntegrationPilot({ scenarios: [{ scenarioId: 'full', assurance: ready }], operationalMetrics: { privacyIncidents: 1 } }).decision, 'hold'); assert.equal(evaluateConveyancerIntegrationPilot({ scenarios: [{ scenarioId: 'full', assurance: ready }], thresholds: { maximumPrivacyIncidents: 10 } }).thresholds.maximumPrivacyIncidents, 0) })
test('builds a guarded pilot manifest with bounded scope', () => { const result = buildConveyancerIntegrationPilotManifest({ firmIds: ['firm:1', 'firm:2', 'firm:3', 'firm:4'], providerCategories: Object.keys(categoryConfig), maximumMatters: 100, startsAt: '2026-08-01T00:00:00.000Z', endsAt: '2026-08-15T00:00:00.000Z', owners: { assurance: 'a', legal: 'l', operations: 'o', security: 's', privacy: 'p', support: 'u', rollback: 'r' } }); assert.equal(result.valid, true); assert.equal(result.scope.firmIds.length, 3); assert.equal(result.scope.maximumMatters, 25); assert.equal(result.controls.productionCredentialsEnabled, false); assert.equal(result.controls.killSwitchRequired, true) })
test('serializes only redacted assurance evidence', () => { const assurance = assureConveyancerIntegrationRelease(fixture()); const serialized = serializeConveyancerIntegrationAssuranceEvidence({ assurance: { ...assurance, apiKey: 'SECRET', customerIdentity: 'SECRET' } }); assert.equal(serialized.includes('SECRET'), false); assert.equal(serialized.includes('apiKey'), false); assert.equal(serialized.includes('customerIdentity'), false) })
