import assert from 'node:assert/strict'
import { MATTER_PLAN_OWNER_ROLES as R } from '../../transactions/conveyancerMatterPlanContract.js'
import { buildConveyancerThreeRoleDependencyModel } from '../../transactions/conveyancerThreeRoleDependencyModel.js'
import {
  CONVEYANCER_FINANCIAL_LINE_CLASSES as LC,
  CONVEYANCER_FINANCIAL_LINE_STATUSES as LS,
  CONVEYANCER_FINANCIAL_LINE_TYPES as LT,
  CONVEYANCER_FINANCIAL_MODEL_VERSION,
  buildConveyancerFinancialModel,
} from '../../transactions/conveyancerFinancialModel.js'
import {
  CONVEYANCER_FINANCIAL_RECONCILIATION_COMMANDS as RC,
  CONVEYANCER_FINANCIAL_RECONCILIATION_CONTROLS,
  buildConveyancerFinancialReconciliationCommand,
  executeConveyancerFinancialReconciliation,
  startConveyancerFinancialReconciliation,
} from '../../../services/attorneyWorkflow/conveyancerFinancialReconciliation.js'
import {
  CONVEYANCER_INTEGRATION_AUTHENTICATION_TYPES as A,
  CONVEYANCER_INTEGRATION_CONNECTION_STATUSES as CS,
  CONVEYANCER_INTEGRATION_DATA_CLASSIFICATIONS as D,
  CONVEYANCER_INTEGRATION_ENVIRONMENTS as E,
  CONVEYANCER_INTEGRATION_LEGAL_BASES as B,
  buildConveyancerIntegrationConnection,
  buildConveyancerIntegrationInboundEvent,
} from '../conveyancerIntegrationFramework.js'
import {
  CONVEYANCER_TRUST_ACCOUNTING_INTEGRATION_VERSION,
  TRUST_ACCOUNTING_INTEGRATION_BOUNDARY,
  buildTrustAccountingAdapterManifest,
  buildTrustAccountingMatterAccountLink,
  buildTrustAccountingPostingBatch,
  buildTrustAccountingPostingProfile,
  buildTrustAccountingReconciliation,
  validateTrustAccountingMatterAccountLink,
  validateTrustAccountingPostingBatch,
  validateTrustAccountingPostingProfile,
  validateTrustAccountingReconciliation,
} from '../conveyancerTrustAccountingIntegration.js'

function test(name, fn) { try { fn(); console.log(`ok - ${name}`) } catch (error) { console.error(`not ok - ${name}`); throw error } }
const hash = (character) => character.repeat(64)
const at = '2026-07-15T15:00:00.000Z'
const accountsD6 = { role: R.accounts, userId: 'accounts:f3' }
const attorneyD6 = { role: R.transferAttorney, userId: 'attorney:f3' }
const reviewerD6 = { role: R.transferAttorney, userId: 'reviewer:f3' }
const accounts = { role: R.accounts, userId: 'accounts:f3', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const attorney = { role: R.transferAttorney, userId: 'attorney:f3', teamId: 'team:transfer', lane: 'transfer', firmId: 'firm:transfer' }
const manager = { role: R.firmManager, userId: 'manager:f3', lane: 'transfer', firmId: 'firm:transfer' }
const bindings = { transfer: { firmId: 'firm:transfer', owner: { role: R.transferAttorney, userId: 'attorney:f3', teamId: 'team:transfer' } }, bond: { firmId: 'firm:bond', owner: { role: R.bondAttorney, userId: 'bond:f3', teamId: 'team:bond' } } }
const source = (type, referenceId) => ({ type, referenceId, evidenceHash: hash('f'), effectiveAt: '2026-07-15T08:00:00.000Z' })

function model() {
  const result = buildConveyancerThreeRoleDependencyModel({ plan: { planId: 'plan:f3', planVersion: 1 }, transaction: { id: 'transaction:f3', organisation_id: 'organisation:f3', transaction_type: 'resale', property_tenure: 'freehold', finance_type: 'bond', seller_has_existing_bond: false, buyer_entity_type: 'individual', seller_entity_type: 'individual' }, roleBindings: bindings, generatedAt: '2026-07-15T08:00:00.000Z', generatedBy: { role: R.system, userId: 'system:f3' } })
  assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model
}

function financialLine(lineId, lineClass, lineType, amount, overrides = {}) { return { lineId, lineClass, lineType, label: lineId, liableParty: lineClass === LC.sellerDeduction ? 'seller' : 'buyer', recipientParty: lineClass === LC.funding ? 'trust_account' : 'attorney', amount, status: LS.confirmed, source: source(lineClass === LC.funding ? 'bank_confirmation' : 'invoice', `source:${lineId}`), ...overrides } }
function financialModel() {
  const result = buildConveyancerFinancialModel({ modelVersion: CONVEYANCER_FINANCIAL_MODEL_VERSION, financialModelId: 'financial-model:f3', revision: 1, planId: 'plan:f3', planVersion: 1, transactionId: 'transaction:f3', organisationId: 'organisation:f3', lane: 'transfer', currency: 'ZAR', consideration: { purchasePrice: '1000.00', taxTreatment: 'transfer_duty', source: source('signed_agreement', 'otp:f3') }, lines: [financialLine('deposit', LC.funding, LT.deposit, '200.00', { status: LS.received, source: source('receipt', 'deposit:f3') }), financialLine('guarantee', LC.funding, LT.guarantee, '800.00', { source: source('guarantee', 'guarantee:f3') }), financialLine('transfer_cost', LC.buyerCharge, LT.professionalFee, '100.00'), financialLine('bond_settlement', LC.sellerDeduction, LT.bondSettlement, '300.00', { recipientParty: 'bank', source: source('bank_confirmation', 'settlement:f3') })], preparedAt: '2026-07-15T09:00:00.000Z', preparedBy: accountsD6, approval: { decisionReferenceId: 'approval:f3:d5', summary: 'Approved.', approvedAt: '2026-07-15T10:00:00.000Z', approvedBy: attorneyD6 } }, { asOf: '2026-07-15T10:30:00.000Z' })
  assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.model
}
function d6Entry(entryId, entryKind, direction, amount, character, sourceType = 'trust_statement') { return { entryId, entryKind, direction, amount, occurredAt: '2026-07-15T10:15:00.000Z', sourceType, sourceReferenceHash: hash(character), evidenceHash: hash('e') } }
function d6Evidence() {
  const entries = [d6Entry('entry:deposit', 'cash', 'inflow', '200.00', '1'), d6Entry('entry:guarantee', 'instrument', 'inflow', '800.00', '2', 'guarantee'), d6Entry('entry:cost_collection', 'cash', 'inflow', '100.00', '3'), d6Entry('entry:cost_payment', 'cash', 'outflow', '100.00', '4'), d6Entry('entry:settlement', 'cash', 'outflow', '300.00', '5'), d6Entry('entry:seller', 'cash', 'outflow', '700.00', '6')]
  const pairs = [['deposit', 'entry:deposit', 'line:deposit', '200.00'], ['guarantee', 'entry:guarantee', 'line:guarantee', '800.00'], ['cost_collection', 'entry:cost_collection', 'line:transfer_cost:collection', '100.00'], ['cost_payment', 'entry:cost_payment', 'line:transfer_cost:disbursement', '100.00'], ['settlement', 'entry:settlement', 'line:bond_settlement', '300.00'], ['seller', 'entry:seller', 'position:seller_base_proceeds', '700.00']]
  return { entries, allocations: pairs.map(([id, entryId, targetId, amount]) => ({ allocationId: `allocation:${id}`, entryId, targetId, amount, evidenceReferenceId: `evidence:${id}` })) }
}
function approvedD6() {
  const proof = d6Evidence(); const started = startConveyancerFinancialReconciliation({ financialModel: financialModel(), statement: { statementId: 'statement:f3', accountReferenceHash: hash('a'), periodStart: '2026-07-01T00:00:00.000Z', periodEnd: '2026-07-15T10:30:00.000Z', openingBalance: '800.00', closingBalance: '0.00', evidenceHash: hash('b'), capturedAt: '2026-07-15T11:00:00.000Z', capturedBy: accountsD6 }, entries: proof.entries, allocations: proof.allocations, actor: accountsD6, occurredAt: '2026-07-15T12:00:00.000Z', commandId: 'start:f3:d6' }); assert.equal(started.ok, true, JSON.stringify(started.errors))
  const controls = Object.fromEntries(CONVEYANCER_FINANCIAL_RECONCILIATION_CONTROLS.map((item) => [item.key, true])); const recommended = executeConveyancerFinancialReconciliation({ reconciliation: started.reconciliation, command: buildConveyancerFinancialReconciliationCommand(started.reconciliation, RC.recommend, { controls, summary: 'Matched.' }), actor: accountsD6, occurredAt: '2026-07-15T12:30:00.000Z' }); const approved = executeConveyancerFinancialReconciliation({ reconciliation: recommended.reconciliation, command: buildConveyancerFinancialReconciliationCommand(recommended.reconciliation, RC.approve, { decisionReferenceId: 'approval:f3:d6', summary: 'Independently approved.' }), actor: reviewerD6, occurredAt: '2026-07-15T13:00:00.000Z' }); assert.equal(approved.ok, true, JSON.stringify(approved.errors)); return approved.reconciliation
}

function manifest() { const result = buildTrustAccountingAdapterManifest({ adapterId: 'trust-adapter', adapterVersion: '1.0.0', providerKey: 'vendor-neutral-trust', environments: [E.sandbox, E.production], authenticationTypes: [A.oauth2, A.signedWebhook], createdAt: '2026-07-15T08:00:00.000Z', createdBy: 'integration-governance:f3' }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.manifest }
function connection(adapter = manifest()) { const result = buildConveyancerIntegrationConnection({ connectionId: 'connection:f3:trust', organisationId: 'organisation:f3', environment: E.production, status: CS.active, capabilities: adapter.capabilities, allowedLanes: ['transfer'], credentialReferenceId: 'vault:trust:f3', secretVersion: 'version:3', webhook: { endpointReferenceId: 'route:trust:f3', secretReferenceId: 'vault:webhook:f3', signingAlgorithm: 'hmac_sha256', replayWindowSeconds: 300 }, dataPolicy: { purpose: 'Reconcile and prepare approved trust-accounting evidence for the linked conveyancing matter.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.financial], retentionDays: 2555 }, verifiedAt: '2026-07-15T08:30:00.000Z', createdAt: '2026-07-15T08:00:00.000Z', createdBy: 'integration-admin:f3' }, { manifest: adapter }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.connection }
function profile(adapter = manifest(), activeConnection = connection(adapter), overrides = {}) { return buildTrustAccountingPostingProfile({ profileId: 'trust-profile:f3', lane: 'transfer', firmId: 'firm:transfer', currency: 'ZAR', trustBankControlAccountReferenceId: 'chart:trust-bank-control', trustBankControlAccountHash: hash('7'), clientMatterLiabilityAccountReferenceId: 'chart:client-matter-liability', clientMatterLiabilityAccountHash: hash('8'), approvedAt: '2026-07-15T09:00:00.000Z', approvedBy: manager, createdAt: '2026-07-15T08:45:00.000Z', createdBy: 'integration-admin:f3', ...overrides }, { manifest: adapter, connection: activeConnection }) }
function link(context = {}, overrides = {}) { const dependencyModel = context.model || model(); const adapter = context.manifest || manifest(); const activeConnection = context.connection || connection(adapter); const postingProfile = context.profile || profile(adapter, activeConnection).profile; return buildTrustAccountingMatterAccountLink({ linkId: 'trust-link:f3', lane: 'transfer', firmId: 'firm:transfer', currency: 'ZAR', trustAccountReferenceHash: hash('a'), providerMatterLedgerReferenceId: 'trust-ledger:matter:f3', providerMatterLedgerReferenceHash: hash('9'), verificationEvidenceReferenceId: 'evidence:trust-link:f3', verificationEvidenceHash: hash('c'), verifiedAt: '2026-07-15T09:30:00.000Z', verifiedBy: manager, ...overrides }, { dependencyModel, manifest: adapter, connection: activeConnection, profile: postingProfile }) }
function inbound(context = {}) { const dependencyModel = context.model || model(); const adapter = context.manifest || manifest(); const activeConnection = context.connection || connection(adapter); const result = buildConveyancerIntegrationInboundEvent({ recordId: 'trust-event:f3:1', type: 'trust_ledger_snapshot_received', lane: 'transfer', firmId: 'firm:transfer', idempotencyKey: 'trust:snapshot:f3:1', providerEventId: 'provider:trust:f3:1', payloadReferenceId: 'quarantine:trust:f3:1', payloadHash: hash('d'), dataPolicy: { purpose: 'Reconcile signed trust-ledger evidence.', legalBasis: B.legalObligation, classifications: [D.professionalConfidential, D.financial], retentionDays: 365 }, signature: { verified: true, algorithm: 'hmac_sha256', keyReferenceId: 'vault:webhook:f3', nonceHash: hash('e'), payloadHash: hash('d'), signedAt: '2026-07-15T14:59:00.000Z' }, occurredAt: '2026-07-15T14:58:00.000Z', receivedAt: at }, { dependencyModel, manifest: adapter, connection: activeConnection }); assert.equal(result.ok, true, JSON.stringify(result.errors)); return result.event }
function providerEntry(id, direction, amountMinor, character) { return { ledgerEntryId: `ledger:${id}`, status: 'posted', direction, amountMinor, occurredAt: '2026-07-15T10:15:00.000Z', bankReferenceHash: hash(character), evidenceReferenceId: `evidence:ledger:${id}`, evidenceHash: hash('f') } }
function providerEvidence({ missingSeller = false } = {}) { const entries = [providerEntry('deposit', 'inflow', 20000, '1'), providerEntry('cost_collection', 'inflow', 10000, '3'), providerEntry('cost_payment', 'outflow', 10000, '4'), providerEntry('settlement', 'outflow', 30000, '5'), ...(!missingSeller ? [providerEntry('seller', 'outflow', 70000, '6')] : [])]; const pairs = [['deposit', 'entry:deposit'], ['cost_collection', 'entry:cost_collection'], ['cost_payment', 'entry:cost_payment'], ['settlement', 'entry:settlement'], ...(!missingSeller ? [['seller', 'entry:seller']] : [])]; return { providerStatement: { snapshotId: 'trust-snapshot:f3', accountReferenceHash: hash('a'), matterLedgerReferenceHash: hash('9'), periodStart: '2026-07-01T00:00:00.000Z', periodEnd: '2026-07-15T10:30:00.000Z', openingBalanceMinor: 80000, closingBalanceMinor: missingSeller ? 70000 : 0, evidenceReferenceId: 'evidence:trust-snapshot:f3', evidenceHash: hash('b'), capturedAt: '2026-07-15T14:55:00.000Z' }, providerEntries: entries, matches: pairs.map(([id, d6EntryId]) => ({ matchId: `match:${id}`, d6EntryId, ledgerEntryId: `ledger:${id}`, amountMinor: entries.find((item) => item.ledgerEntryId === `ledger:${id}`).amountMinor, evidenceReferenceId: `evidence:match:${id}` })) } }

function fixture() { const dependencyModel = model(); const adapter = manifest(); const activeConnection = connection(adapter); const profileResult = profile(adapter, activeConnection); assert.equal(profileResult.ok, true, JSON.stringify(profileResult.errors)); const linkResult = link({ model: dependencyModel, manifest: adapter, connection: activeConnection, profile: profileResult.profile }); assert.equal(linkResult.ok, true, JSON.stringify(linkResult.errors)); return { dependencyModel, adapter, activeConnection, postingProfile: profileResult.profile, matterLink: linkResult.link, d6: approvedD6(), inboundEvent: inbound({ model: dependencyModel, manifest: adapter, connection: activeConnection }) } }
function reconcile(value = fixture(), evidence = providerEvidence(), overrides = {}) { return buildTrustAccountingReconciliation({ reconciliationId: 'trust-reconciliation:f3', generatedAt: at, ...evidence, ...overrides }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile, link: value.matterLink, d6Reconciliation: value.d6, inboundEvent: value.inboundEvent }) }
function missingFixture() { const value = fixture(); const result = reconcile(value, providerEvidence({ missingSeller: true })); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.reconciliation.status, 'review_required'); return { ...value, trustReconciliation: result.reconciliation } }
function posting(value = missingFixture(), overrides = {}) { return buildTrustAccountingPostingBatch({ batchId: 'trust-batch:f3', d6EntryIds: ['entry:seller'], commandId: 'trust-command:f3', idempotencyKey: 'trust-posting-f3', payloadReferenceId: 'approved-trust-batch:f3', payloadHash: hash('1'), preparedAt: '2026-07-15T15:15:00.000Z', preparedBy: accounts, approvedAt: '2026-07-15T15:30:00.000Z', approvedBy: attorney, approvalReferenceId: 'approval:trust-posting:f3', retentionDays: 365, ...overrides }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile, link: value.matterLink, reconciliation: value.trustReconciliation, inboundEvent: value.inboundEvent, existingCommands: overrides.existingCommands || [] }) }

test('creates a governed trust-accounting adapter and posting profile', () => { const adapter = manifest(); const activeConnection = connection(adapter); const result = profile(adapter, activeConnection); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.profile.version, CONVEYANCER_TRUST_ACCOUNTING_INTEGRATION_VERSION); assert.equal(adapter.category, 'trust_accounting'); assert.equal(validateTrustAccountingPostingProfile(result.profile, { manifest: adapter, connection: activeConnection }).valid, true) })
test('rejects unsafe chart mappings, automatic posting and non-manager approval', () => { const adapter = manifest(); const activeConnection = connection(adapter); const same = profile(adapter, activeConnection, { clientMatterLiabilityAccountHash: hash('7') }); assert.equal(same.errors.includes('trust_profile_account_mapping_invalid'), true); const denied = profile(adapter, activeConnection, { approvedBy: attorney }); assert.equal(denied.errors.includes('trust_profile_approval_invalid'), true); const changed = structuredClone(profile(adapter, activeConnection).profile); changed.automaticPostingEnabled = true; assert.equal(validateTrustAccountingPostingProfile(changed, { manifest: adapter, connection: activeConnection }).errors.includes('trust_profile_side_effect_boundary_violated'), true) })
test('binds the trust and matter-ledger accounts to the exact E2 lane and firm', () => { const value = fixture(); assert.equal(validateTrustAccountingMatterAccountLink(value.matterLink, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile }).valid, true); assert.equal(value.matterLink.bankAccountChanged, false) })
test('denies non-manager links, account substitution and matter tampering', () => { const value = fixture(); assert.equal(link({ model: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile }, { verifiedBy: attorney }).errors.includes('trust_link_authority_invalid'), true); const changed = structuredClone(value.matterLink); changed.trustAccountReferenceHash = hash('z'); assert.equal(validateTrustAccountingMatterAccountLink(changed, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile }).errors.includes('trust_link_evidence_invalid'), true) })
test('three-way reconciles approved D6 cash, bank evidence and the trust ledger', () => { const value = fixture(); const result = reconcile(value); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.reconciliation.status, 'matched'); assert.equal(result.reconciliation.cashResults.length, 5); assert.deepEqual(result.reconciliation.instrumentEntryIds, ['entry:guarantee']); assert.equal(result.reconciliation.checks.every((item) => item.status === 'passed'), true); assert.equal(validateTrustAccountingReconciliation(result.reconciliation, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile, link: value.matterLink, inboundEvent: value.inboundEvent }).valid, true) })
test('does not treat a guarantee as trust cash or allow it to be ledger-matched', () => { const value = fixture(); const evidence = providerEvidence(); evidence.matches.push({ matchId: 'match:guarantee', d6EntryId: 'entry:guarantee', ledgerEntryId: 'ledger:deposit', amountMinor: 100, evidenceReferenceId: 'evidence:bad' }); const result = reconcile(value, evidence); assert.equal(result.reconciliation.findings.some((item) => item.checkKey === 'instrument_exclusion'), true); assert.equal(result.reconciliation.status, 'review_required') })
test('identifies a missing trust posting without claiming the bank payment failed', () => { const value = missingFixture(); assert.equal(value.trustReconciliation.cashResults.find((item) => item.d6EntryId === 'entry:seller').varianceMinor, -70000); assert.equal(value.trustReconciliation.findings.some((item) => item.checkKey === 'cash_coverage'), true); assert.equal(value.trustReconciliation.controls.bankMovementInitiated, false) })
test('detects wrong bank references, partial matches and orphan ledger entries', () => { const value = fixture(); const wrong = providerEvidence(); wrong.providerEntries[0].bankReferenceHash = hash('0'); assert.equal(reconcile(value, wrong).reconciliation.findings.some((item) => item.checkKey === 'match_integrity'), true); const partial = providerEvidence(); partial.matches[0].amountMinor = 19999; assert.equal(reconcile(value, partial).reconciliation.findings.some((item) => item.checkKey === 'cash_coverage'), true); const orphan = providerEvidence(); orphan.providerEntries.push(providerEntry('orphan', 'inflow', 1, '0')); orphan.providerStatement.closingBalanceMinor = 1; assert.equal(reconcile(value, orphan).reconciliation.findings.some((item) => item.checkKey === 'ledger_coverage'), true) })
test('requires signed F1 snapshot provenance and exact trust-account binding', () => { const value = fixture(); const result = buildTrustAccountingReconciliation({ reconciliationId: 'trust-reconciliation:no-event', generatedAt: at, ...providerEvidence() }, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile, link: value.matterLink, d6Reconciliation: value.d6, inboundEvent: {} }); assert.equal(result.ok, false); assert.equal(result.errors.includes('trust_reconciliation_inbound_evidence_invalid'), true); const evidence = providerEvidence(); evidence.providerStatement.accountReferenceHash = hash('0'); assert.equal(reconcile(value, evidence).errors.includes('trust_reconciliation_statement_invalid'), true) })
test('prepares balanced double-entry journals without moving money or posting them', () => { const value = missingFixture(); const result = posting(value); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.batch.status, 'prepared'); assert.equal(result.batch.journals.length, 1); assert.equal(result.batch.journals[0].totalDebitMinor, 70000); assert.equal(result.batch.journals[0].totalCreditMinor, 70000); assert.equal(result.batch.journals[0].balanced, true); assert.equal(result.outboundCommand.type, 'trust_posting_batch_requested'); assert.equal(result.outboundCommand.controls.dispatchPerformed, false); assert.equal(result.batch.controls.paymentReleased, false); assert.equal(validateTrustAccountingPostingBatch(result.batch, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile, link: value.matterLink, reconciliation: value.trustReconciliation, inboundEvent: value.inboundEvent, outboundCommand: result.outboundCommand }).valid, true) })
test('requires independent legal approval and only permits missing D6 cash entries', () => { const value = missingFixture(); assert.equal(posting(value, { approvedBy: accounts }).errors.includes('trust_posting_independent_approval_invalid'), true); assert.equal(posting(value, { d6EntryIds: ['entry:guarantee'] }).errors.includes('trust_posting_entries_not_eligible'), true); assert.equal(posting(value, { d6EntryIds: ['entry:deposit'] }).errors.includes('trust_posting_entries_not_eligible'), true) })
test('inherits F1 idempotency and rejects changed journal batch reuse', () => { const value = missingFixture(); const first = posting(value); const duplicate = posting(value, { existingCommands: [first.outboundCommand] }); assert.equal(duplicate.ok, true); assert.equal(duplicate.batch.status, 'duplicate'); const conflict = posting(value, { existingCommands: [first.outboundCommand], payloadHash: hash('2') }); assert.equal(conflict.errors.includes('trust_posting_outbound:integration_idempotency_conflict'), true) })
test('detects financial, command and side-effect tampering', () => { const value = missingFixture(); const result = posting(value); const changed = structuredClone(result.batch); changed.journals[0].lines[0].amountMinor = 1; changed.controls.paymentReleased = true; const validation = validateTrustAccountingPostingBatch(changed, { dependencyModel: value.dependencyModel, manifest: value.adapter, connection: value.activeConnection, profile: value.postingProfile, link: value.matterLink, reconciliation: value.trustReconciliation, inboundEvent: value.inboundEvent, outboundCommand: result.outboundCommand }); assert.equal(validation.errors.includes('trust_posting_journals_invalid'), true); assert.equal(validation.errors.includes('trust_posting_batch_fingerprint_invalid'), true); assert.equal(validation.errors.includes('trust_posting_side_effect_boundary_violated'), true); assert.equal(TRUST_ACCOUNTING_INTEGRATION_BOUNDARY.trustLedgerMutated, false) })

console.log('F3 trust-accounting integration tests passed.')
