import { CheckCircle2, CircleAlert, Rocket, ArrowUpRight, Copy, Download } from 'lucide-react'
import Button from '../ui/Button'

export default function DevelopmentLaunchReadinessPanel({ readiness, onOpenArea, onCopyPacket, onDownloadPacket }) {
  const { gates = [], blockers = [], score = 0, launchReady = false } = readiness || {}
  return <section className="rounded-[20px] border border-[#dce5ee] bg-white p-5 shadow-[0_10px_24px_rgba(15,23,42,0.045)]">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-[#286646]"><Rocket size={14} />Launch readiness</span><h3 className="mt-2 text-[1.15rem] font-semibold tracking-[-0.025em] text-[#142132]">{launchReady ? 'Ready to launch' : `${blockers.length} launch blocker${blockers.length === 1 ? '' : 's'} remaining`}</h3><p className="mt-1 text-sm leading-6 text-[#6b7d93]">A practical release check across stock, selling controls and public presentation.</p></div><div className="flex items-start gap-2"><span className={`inline-flex h-14 w-14 items-center justify-center rounded-full text-base font-bold ${launchReady ? 'bg-[#eaf8ef] text-[#177347]' : 'bg-[#fff6e8] text-[#a45d12]'}`}>{score}%</span></div></div>
    {onCopyPacket || onDownloadPacket ? <div className="mt-4 flex flex-wrap gap-2">{onCopyPacket ? <Button type="button" size="sm" variant="secondary" onClick={onCopyPacket}><Copy size={13} />Copy launch summary</Button> : null}{onDownloadPacket ? <Button type="button" size="sm" variant="secondary" onClick={onDownloadPacket}><Download size={13} />Download launch packet</Button> : null}</div> : null}
    <div className="mt-5 grid gap-2">{gates.map((gate) => <div key={gate.id} className="flex items-start gap-3 rounded-[14px] border border-[#e4ebf3] bg-[#fbfcfe] px-3 py-3"><span className={gate.ready ? 'text-[#1f8a4d]' : gate.required ? 'text-[#d58a18]' : 'text-[#7d8fa1]'}>{gate.ready ? <CheckCircle2 size={17} /> : <CircleAlert size={17} />}</span><div className="min-w-0 flex-1"><strong className="block text-sm text-[#1d3347]">{gate.label}{!gate.required ? <span className="ml-2 text-xs font-medium text-[#7b8ca2]">Recommended</span> : null}</strong><p className="mt-0.5 text-xs leading-5 text-[#6b7d93]">{gate.detail}</p></div>{!gate.ready ? <Button type="button" variant="ghost" size="sm" onClick={() => onOpenArea?.(gate.tab)}>Fix<ArrowUpRight size={13} /></Button> : null}</div>)}</div>
  </section>
}
