import { getDocumentUploadPolicy } from '../../../../lib/documentUploadPolicy.js'
import { useState } from 'react'
import { AlertCircle, CheckCircle2, Clock3, FileText, RefreshCw, UploadCloud, FolderOpen } from 'lucide-react'
import { buildBondDocumentWorkspace, isBondStatementHandoff } from '../documents/bondDocumentWorkspacePresentation.js'
const documentUploadPolicy = getDocumentUploadPolicy({ surface: 'bank_statement' })


const tones = { action: 'border-amber-200 bg-amber-50 text-amber-800', review: 'border-sky-200 bg-sky-50 text-sky-700', approved: 'border-emerald-200 bg-emerald-50 text-emerald-700' }
function StatusIcon({ status }) { return status === 'approved' ? <CheckCircle2 size={18} /> : status === 'review' ? <Clock3 size={18} /> : <AlertCircle size={18} /> }

function StatementHandoff({ requirement }) {
  const [files, setFiles] = useState([])
  return <div className="space-y-3 rounded-xl border border-[#dbe5ef] bg-[#f8fbff] p-3">
    <p className="text-sm leading-6 text-[#52657b]">Provide {requirement.evidencePeriodMonths || 3} consecutive months of statements, including every page. Self-employed applicants generally need 6 months.</p>
    <label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border bg-white px-3 text-sm font-semibold text-[#35546c]">Choose statements<input aria-label={`Choose statements: ${requirement.title}`} type="file" title={documentUploadPolicy.helpText} accept={documentUploadPolicy.accept} multiple className="sr-only" onChange={event => { setFiles(previous => [...previous, ...Array.from(event.target.files || []).filter(file => !previous.some(existing => existing.name === file.name && existing.size === file.size && existing.lastModified === file.lastModified))]); event.target.value = '' }} /></label>
    <span className="block text-xs font-normal text-slate-500">{documentUploadPolicy.helpText}</span>
    {files.map((file, index) => <div key={`${file.name}-${file.size}-${file.lastModified}`} className="flex items-center justify-between gap-2 text-xs"><span className="break-all">{file.name} · Selected, not sent</span><button type="button" className="min-h-11 px-2 font-semibold text-[#b5472d]" onClick={() => setFiles(previous => previous.filter((_, current) => index !== current))} aria-label={`Remove ${file.name}`}>Remove</button></div>)}
    <button type="button" disabled className="min-h-11 rounded-xl bg-[#9aa9b8] px-3 text-sm font-semibold text-white">Send to bond consultant</button>
    <p role="status" className="text-xs leading-5 text-[#61748a]">Your consultant’s secure upload connection is not set up yet. Selected files stay on this screen and have not been uploaded or saved to Arch9. Once connected, only the handoff status will be kept here.</p>
  </div>
}

export default function DocumentsChecklistScreen({ documentsController, onOpenDocument, onOpenDocuments }) {
  const { checklist, error, uploadState = {}, uploadDocument, retryUpload, reconciling, refresh } = documentsController
  const model = buildBondDocumentWorkspace(checklist)
  const [categoryKey, setCategoryKey] = useState('')
  const [selectedKey, setSelectedKey] = useState('')
  const category = model.categories.find(item => item.key === categoryKey) || model.categories[0]
  const selected = category?.items.find(item => item.requirement.key === selectedKey) || category?.items.find(item => item.presentationStatus === 'action') || category?.items[0]
  const requirement = selected?.requirement
  const busy = requirement && uploadState[requirement.key]?.status === 'uploading'
  const handoff = requirement && isBondStatementHandoff(requirement)
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-[#142132]">Documents for your application</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#52657b]">Your bond documents, together with the files already supplied in your Document Centre. Choose a document to see what is needed and upload it here.</p></div><div className="flex gap-2">{onOpenDocuments ? <button type="button" onClick={onOpenDocuments} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-3 text-xs font-semibold text-[#35546c]"><FolderOpen size={15} />Document Centre</button> : null}<button type="button" disabled={reconciling} onClick={() => void refresh({ persist: false })} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-3 text-xs font-semibold text-[#35546c]"><RefreshCw size={15} />{reconciling ? 'Refreshing...' : 'Refresh documents'}</button></div></div>
    <div className="grid grid-cols-3 gap-3 rounded-2xl border border-[#dbe5ef] bg-white p-3">
      {[['action', 'Needs your attention'], ['review', 'Being reviewed'], ['approved', 'Approved']].map(([status, label]) => <div key={status} className={`rounded-xl border p-3 ${tones[status]}`}><span className="flex items-center gap-2"><StatusIcon status={status} /><strong className="text-xl">{model.counts[status]}</strong></span><p className="mt-2 text-xs font-semibold">{label}</p></div>)}
    </div>
    <p className="text-xs leading-5 text-[#61748a]">Uploads here use the same document record as the Document Centre. Received files may still need review. Bank statements use the separate consultant handoff below.</p>
    {error ? <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}
    {model.items.length ? <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_350px]">
      <section className="min-w-0 rounded-2xl border border-[#dbe5ef] p-3"><nav aria-label="Bond document categories" className="flex gap-2 overflow-x-auto rounded-xl bg-[#f3f6fa] p-1.5">{model.categories.map(item => <button key={item.key} type="button" aria-pressed={category?.key === item.key} onClick={() => { setCategoryKey(item.key); setSelectedKey('') }} className={`min-h-11 shrink-0 rounded-lg px-3 text-xs font-semibold ${category?.key === item.key ? 'border bg-white text-[#142132]' : 'text-[#61748a]'}`}>{item.label} <span className="ml-1">{item.items.length}</span></button>)}</nav>
        <div className="mt-3 overflow-hidden rounded-xl border border-[#e4ebf3]">{category?.items.map(item => <button key={item.requirement.key} type="button" aria-pressed={selected?.requirement.key === item.requirement.key} onClick={() => setSelectedKey(item.requirement.key)} className={`flex w-full flex-wrap items-center justify-between gap-3 border-b border-[#e4ebf3] p-4 text-left last:border-b-0 ${selected?.requirement.key === item.requirement.key ? 'bg-[#eef4fa]' : 'hover:bg-[#f8fbff]'}`}><span className="flex min-w-0 items-center gap-3"><span className={`rounded-full border p-2 ${tones[item.presentationStatus]}`}><StatusIcon status={item.presentationStatus} /></span><span><strong className="block text-sm text-[#142132]">{item.requirement.title}</strong><span className="mt-1 block text-xs text-[#61748a]">{item.uploadedCount} of {item.requiredCount} files received{item.requirement.required === false ? ' · Optional' : ''}</span></span></span><span className={`rounded-full border px-2 py-1 text-xs ${tones[item.presentationStatus]}`}>{item.presentationStatusLabel}</span></button>)}</div>
      </section>
      {selected ? <aside aria-label="Selected bond document" className="space-y-4 rounded-2xl border border-[#dbe5ef] p-4 xl:self-start"><div><FileText size={22} className="mb-3 text-[#52657b]" /><h3 className="text-lg font-semibold text-[#142132]">{requirement.title}</h3><span className={`mt-2 inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${tones[selected.presentationStatus]}`}>{selected.presentationStatusLabel}</span></div><p className="text-sm leading-6 text-[#52657b]">{requirement.description}</p>{requirement.reason ? <p className="text-xs leading-5 text-[#61748a]">Why this is needed: {requirement.reason}</p> : null}<p className="text-xs text-[#61748a]">{requirement.required === false ? 'Optional' : 'Required before bank submission'} · {selected.uploadedCount} of {selected.requiredCount} files received</p>
        {(selected.documents || []).map((file, index) => <div key={file.id || index} className="rounded-xl border border-[#e4ebf3] p-3"><p className="break-all text-xs font-semibold text-[#40566d]">{file.name || file.document_label || file.file_name || 'Uploaded document'}</p>{file.rejection_reason || file.review_notes ? <p className="mt-2 text-xs text-[#b5472d]">{file.rejection_reason || file.review_notes}</p> : null}{onOpenDocument ? <button type="button" onClick={() => void onOpenDocument(file)} className="mt-2 min-h-11 text-xs font-semibold text-[#35546c]">View file</button> : null}</div>)}
        {selected.candidateDocuments?.length ? <p role="status" className="text-xs leading-5 text-amber-800">More than one possible file was found. Ask your consultant to confirm which file belongs to this request.</p> : null}
        {handoff ? <StatementHandoff key={requirement.key} requirement={requirement} /> : <div className="space-y-3"><label className={`inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl bg-[#35546c] px-4 text-sm font-semibold text-white ${busy ? 'opacity-60' : ''}`}><UploadCloud size={16} />{busy ? 'Uploading...' : selected.status === 'rejected' ? 'Replace document' : selected.uploadedCount ? 'Add or replace file' : 'Upload document'}<input aria-label={`Upload document: ${requirement.title}`} type="file" title={documentUploadPolicy.helpText} accept={documentUploadPolicy.accept} disabled={busy} className="sr-only" onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void uploadDocument(selected, file) }} /></label>
        <span className="block text-xs font-normal text-slate-500">{documentUploadPolicy.helpText}</span><p className="text-xs leading-5 text-[#61748a]">Upload each supporting file here. Your consultant reviews received documents before bank submission.</p>{uploadState[requirement.key]?.error ? <p role="alert" className="text-xs text-[#b5472d]">{uploadState[requirement.key].error}<button type="button" onClick={() => void retryUpload(selected)} className="ml-2 min-h-11 font-semibold">Retry upload</button></p> : null}</div>}
      </aside> : null}
    </div> : <p className="rounded-xl border border-dashed p-4 text-sm text-[#61748a]">No bond documents have been requested yet.</p>}
    <p className="rounded-xl bg-[#f5f8fb] p-3 text-sm leading-6 text-[#52657b]">You can continue to review your application. Any outstanding documents must be supplied before your originator sends it to a bank.</p>
  </div>
}
