import { CheckCircle2, CircleAlert, KeyRound, Link2, RefreshCw, UsersRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useOrganisation } from '../../context/OrganisationContext'
import { supabase } from '../../lib/supabaseClient'
import { fetchOrganisationSettings, listOrganisationUsersForWorkspace } from '../../lib/settingsApi'
import { SettingsBanner, SettingsEmptyState, SettingsLoadingState, SettingsSectionCard, SettingsStickySaveBar, settingsPageClass } from './settingsUi'

const INPUT = 'h-11 rounded-[12px] border border-[#d8e3ee] bg-white px-3.5 text-sm text-[#17233a] shadow-[0_1px_0_rgba(15,23,42,0.02)] placeholder:text-[#9aa8b8] focus:border-[#0f7f4f] focus:outline-none focus:ring-2 focus:ring-[#dff2e8]'
const EMPTY = { branchGuid: '', baseUrl: '', usernameSecretName: 'PRIVATE_PROPERTY_PRODUCTION_USERNAME', passwordSecretName: 'PRIVATE_PROPERTY_PRODUCTION_PASSWORD', privatePropertyAgencyId: '', webhookSecretName: 'PRIVATE_PROPERTY_WEBHOOK_SECRET', notes: '' }
const text = (value = '') => String(value || '').trim()
function Field({ label, hint, children }) { return <label className="grid gap-1.5"><span className="text-[0.78rem] font-semibold text-[#43566d]">{label}</span>{children}{hint ? <span className="text-xs leading-5 text-[#6b7d93]">{hint}</span> : null}</label> }
function Pill({ ready, children }) { return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${ready ? 'border-[#ccead8] bg-[#f2fbf5] text-[#1f7a45]' : 'border-[#f3d9a8] bg-[#fff8ec] text-[#a16207]'}`}>{ready ? <CheckCircle2 className="h-3.5 w-3.5" /> : <CircleAlert className="h-3.5 w-3.5" />}{children}</span> }
async function request(url, options = {}) { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) throw new Error('Sign in before managing Private Property.'); const response = await fetch(url, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || 'Private Property setup could not be completed.'); return payload }
function configToDraft(config = {}) { return { branchGuid: text(config.branchGuid), baseUrl: text(config.baseUrl), usernameSecretName: text(config.usernameSecretName) || EMPTY.usernameSecretName, passwordSecretName: text(config.passwordSecretName) || EMPTY.passwordSecretName, privatePropertyAgencyId: text(config.metadata?.private_property_agency_id), webhookSecretName: text(config.metadata?.private_property_webhook_secret_name) || EMPTY.webhookSecretName, notes: text(config.notes) } }

export default function SettingsPrivatePropertyPage() {
  const { organisation } = useOrganisation()
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const [organisationId, setOrganisationId] = useState(''); const [draft, setDraft] = useState(EMPTY); const [saved, setSaved] = useState(EMPTY); const [connection, setConnection] = useState(null); const [mappings, setMappings] = useState([]); const [users, setUsers] = useState([])
  const [mappingDraft, setMappingDraft] = useState({ organisationUserId: '', arch9UserId: '', privatePropertyAgentId: '', sourceReference: '' })
  const [reconciling, setReconciling] = useState(false)
  const [reconciliation, setReconciliation] = useState(null)
  async function load() { setLoading(true); setError(''); try { const context = await fetchOrganisationSettings({ forceRefresh: true }); const id = text(context.organisation?.id || organisation?.organisationId || organisation?.id); if (!id) throw new Error('Choose an organisation before connecting Private Property.'); const [connectionResult, mappingsResult, organisationUsers] = await Promise.all([request(`/api/private-property/settings/connection?organisationId=${encodeURIComponent(id)}`), request(`/api/private-property/settings/agent-mappings?organisationId=${encodeURIComponent(id)}`), listOrganisationUsersForWorkspace({ organisationId: id })]); const nextDraft = configToDraft(connectionResult.config); setOrganisationId(id); setConnection(connectionResult.config); setDraft(nextDraft); setSaved(nextDraft); setMappings(mappingsResult.mappings || []); setUsers(organisationUsers || []) } catch (loadError) { setError(loadError.message || 'Unable to load Private Property setup.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved); const connectionSaved = Boolean(connection?.id); const mappedUsers = useMemo(() => new Set(mappings.filter((item) => item.status === 'active').map((item) => item.arch9UserId).filter(Boolean)), [mappings])
  async function saveConnection() { setSaving(true); setError(''); setSuccess(''); try { const result = await request('/api/private-property/settings/connection', { method: 'PUT', body: JSON.stringify({ organisationId, ...draft }) }); const nextDraft = configToDraft(result.config); setConnection(result.config); setDraft(nextDraft); setSaved(nextDraft); setSuccess(result.message || 'Private Property connection saved as pending.') } catch (saveError) { setError(saveError.message || 'Unable to save Private Property connection.') } finally { setSaving(false) } }
  function chooseUser(organisationUserId) { const user = users.find((item) => item.id === organisationUserId) || {}; const userId = user.userId || user.user_id || ''; setMappingDraft({ organisationUserId, arch9UserId: userId, privatePropertyAgentId: '', sourceReference: userId || user.email || '' }) }
  async function saveMapping() { setError(''); setSuccess(''); try { const user = users.find((item) => item.id === mappingDraft.organisationUserId) || {}; const result = await request('/api/private-property/settings/agent-mappings', { method: 'PUT', body: JSON.stringify({ organisationId, ...mappingDraft, emailSnapshot: user.email, firstNameSnapshot: user.firstName, lastNameSnapshot: user.lastName }) }); setMappings((current) => [result.mapping, ...current.filter((item) => item.id !== result.mapping.id && item.arch9UserId !== result.mapping.arch9UserId)]); setMappingDraft({ organisationUserId: '', arch9UserId: '', privatePropertyAgentId: '', sourceReference: '' }); setSuccess('Agent mapping saved.') } catch (saveError) { setError(saveError.message || 'Unable to save the Private Property agent mapping.') } }
  async function reviewPortalInventory() {
    setReconciling(true)
    setError('')
    try {
      const report = await request(`/api/private-property/settings/reconciliation-report?organisationId=${encodeURIComponent(organisationId)}`)
      setReconciliation(report)
    } catch (reviewError) {
      setError(reviewError.message || 'Unable to compare Private Property and Arch9 listings.')
    } finally {
      setReconciling(false)
    }
  }
  if (loading) return <SettingsLoadingState label="Loading Private Property setup..." />
  if (!organisationId) return <div className={settingsPageClass}><SettingsEmptyState title="Organisation required" description="Complete organisation setup before connecting Private Property." /></div>
  return <div className={`${settingsPageClass} space-y-6`}><header className="flex flex-col gap-4 border-b border-[#e2eaf2] pb-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-[#0f7f4f]"><Link2 className="h-4 w-4" />Production connector</div><h1 className="text-2xl font-semibold text-[#142132]">Private Property</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#60758d]">Connect one Arch9 listing workflow to Private Property. Credentials are never entered or stored here.</p></div><div className="flex flex-wrap gap-2"><Pill ready={connectionSaved}>Connection {connectionSaved ? 'saved' : 'not configured'}</Pill><Pill ready={mappedUsers.size > 0}>{mappedUsers.size} agent{mappedUsers.size === 1 ? '' : 's'} mapped</Pill></div></header>{error ? <SettingsBanner>{error}</SettingsBanner> : null}{success ? <SettingsBanner tone="success">{success}</SettingsBanner> : null}
    <SettingsSectionCard title="Production connection" description="Save Private Property’s production identifiers and the names of secrets already held by the runtime. This remains pending until Arch9 verifies it."><div className="grid gap-4 md:grid-cols-2"><Field label="Private Property branch GUID" hint="Issued by Private Property for the branch."><input className={INPUT} value={draft.branchGuid} onChange={(event) => setDraft({ ...draft, branchGuid: event.target.value })} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" /></Field><Field label="Production SOAP endpoint" hint="Use the exact live AgentImport endpoint supplied by Private Property."><input className={INPUT} value={draft.baseUrl} onChange={(event) => setDraft({ ...draft, baseUrl: event.target.value })} placeholder="https://services.privateproperty.co.za/..." /></Field><Field label="Username secret name" hint="The secret’s label only, never its value."><input className={INPUT} value={draft.usernameSecretName} onChange={(event) => setDraft({ ...draft, usernameSecretName: event.target.value })} /></Field><Field label="Password secret name" hint="The secret’s label only, never its value."><input className={INPUT} value={draft.passwordSecretName} onChange={(event) => setDraft({ ...draft, passwordSecretName: event.target.value })} /></Field><Field label="Internal notes"><input className={INPUT} value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} placeholder="Onboarding contact or branch notes" /></Field></div><div className="mt-4 flex items-start gap-3 rounded-[14px] border border-[#e3ebf3] bg-[#f9fbfe] p-4 text-sm leading-6 text-[#60758d]"><KeyRound className="mt-0.5 h-4 w-4 shrink-0 text-[#0f7f4f]" />Save the actual username and password in the production runtime secret store as the two names above. This page stores only the names and cannot enable publishing.</div></SettingsSectionCard>
    <SettingsSectionCard title="Existing portal listings" description="Compare Private Property’s active inventory with Arch9. This is a read-only review: nothing is imported, linked, or published.">
      <button type="button" className="inline-flex min-h-10 items-center gap-2 rounded-[10px] border border-[#0f7f4f] bg-white px-4 text-sm font-semibold text-[#0f7f4f] disabled:opacity-60" disabled={!connectionSaved || reconciling} onClick={() => void reviewPortalInventory()}>
        <RefreshCw className={`h-4 w-4 ${reconciling ? 'animate-spin' : ''}`} />{reconciling ? 'Comparing listings…' : 'Compare active listings'}
      </button>
      {reconciliation ? <div className="mt-4 space-y-3 text-sm text-[#43566d]">
        {!reconciliation.summary?.configuredProductionBranches ? <p className="rounded-lg border border-[#f3d9a8] bg-[#fff8ec] p-3 text-[#8a5b13]">No approved production branch was checked. The counts below do not establish that Arch9 matches Private Property.</p> : null}
        <p>{reconciliation.summary?.unlinkedActivePortalListings || 0} active portal listing{reconciliation.summary?.unlinkedActivePortalListings === 1 ? '' : 's'} without an Arch9 sync link. {reconciliation.summary?.localSyncCount || 0} linked listing{reconciliation.summary?.localSyncCount === 1 ? '' : 's'} checked.</p>
        {reconciliation.summary?.localInventoryMayBeTruncated ? <p className="rounded-lg border border-[#f3d9a8] bg-[#fff8ec] p-3 text-[#8a5b13]">The local inventory reached the review limit. Treat suggested matches as provisional until the full inventory is checked.</p> : null}
        {(reconciliation.checks || []).filter((check) => check.status !== 'COMPLETE').map((check) => <p key={check.configId} className="rounded-lg border border-[#f3d9a8] bg-[#fff8ec] p-3 text-[#8a5b13]">Branch check {check.status.toLowerCase()}: {(check.blockers || []).join(', ') || check.error || 'Review the connection.'}</p>)}
        {(reconciliation.unmatchedPortalListings || []).map((item) => <div key={`${item.branchGuid}:${item.propertyId}`} className="rounded-lg border border-[#e3ebf3] bg-[#f9fbfe] p-3"><p className="font-semibold text-[#17233a]">{item.privatePropertyRef || item.propertyId} · {item.listingType || 'Listing'}</p><p className="mt-1">{item.reason}</p>{item.candidate ? <p className="mt-1">Possible Arch9 match: {item.candidate.title || item.candidate.listingReference || item.candidate.listingId}</p> : null}</div>)}
      </div> : null}
    </SettingsSectionCard><SettingsStickySaveBar dirty={dirty} saving={saving} message="You have unsaved Private Property connection changes" onDiscard={() => setDraft(saved)} onSave={() => void saveConnection()} saveLabel="Save connection" /></div>
}
