import { ArrowRight, Building2, Loader2, Plus } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { createRentalUnit, listRentalUnits } from '../../../../services/rentals/rentalUnitRepository.js'

const initialForm = { unitLabel: '', bedrooms: 0, bathrooms: 0, targetRent: 0, depositAmount: 0 }
export function RentalUnitsPanel({ property = {}, userId = '' }) {
  const [units, setUnits] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(initialForm); const [creating, setCreating] = useState(false)
  const load = useCallback(async () => { if (!property.id) return; try { setLoading(true); setUnits(await listRentalUnits({ propertyId: property.id })) } catch (cause) { setError(cause?.message || 'Unable to load units.') } finally { setLoading(false) } }, [property.id])
  useEffect(() => { void load() }, [load])
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event) => { event.preventDefault(); try { setCreating(true); setError(''); await createRentalUnit({ ...form, organisationId: property.organisationId, propertyId: property.id, branchId: property.branchId, createdBy: userId }); setForm(initialForm); await load() } catch (cause) { setError(cause?.message || 'Unable to create unit.') } finally { setCreating(false) } }
  return <section className="mt-6 rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-sky-700"/><div><h2 className="font-semibold text-slate-900">Units</h2><p className="text-sm text-slate-600">Each unit is managed independently. A house uses one default MAIN unit.</p></div></div><form onSubmit={submit} className="mt-4 grid gap-2 md:grid-cols-6"><input value={form.unitLabel} onChange={(e) => set('unitLabel', e.target.value)} placeholder="Unit label (MAIN)" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.bedrooms} onChange={(e) => set('bedrooms', e.target.value)} placeholder="Beds" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.bathrooms} onChange={(e) => set('bathrooms', e.target.value)} placeholder="Baths" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.targetRent} onChange={(e) => set('targetRent', e.target.value)} placeholder="Target rent" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.depositAmount} onChange={(e) => set('depositAmount', e.target.value)} placeholder="Deposit" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={creating} className="inline-flex items-center justify-center gap-1 rounded-lg bg-sky-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{creating ? <Loader2 className="h-4 w-4 animate-spin"/> : <Plus className="h-4 w-4"/>}Add unit</button></form>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{loading ? <Loader2 className="mx-auto mt-5 h-5 w-5 animate-spin"/> : <div className="mt-4 grid gap-2 sm:grid-cols-2">{units.map((unit) => <article key={unit.id} className="rounded-lg border bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-sky-700">{unit.status}</p><h3 className="font-semibold">{unit.unitLabel}</h3><p className="text-sm text-slate-600">{unit.bedrooms} bed · {unit.bathrooms} bath · Target rent R{unit.targetRent?.toLocaleString?.() || '0'}</p><p className="mt-1 text-sm text-slate-600">Deposit R{unit.depositAmount?.toLocaleString?.() || '0'}</p>{unit.status === 'vacant' ? <Link to={`/agent/rentals/vacancies/new?propertyId=${encodeURIComponent(property.id)}&unitId=${encodeURIComponent(unit.id)}`} className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-sky-700">Create draft vacancy <ArrowRight className="h-4 w-4" /></Link> : null}</article>)}</div>}</section>
}
