import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'
import { createRentalApplicantAccess } from './rentalApplicantAccessModel.js'

const text = (value) => String(value ?? '').trim()
const fields = 'id, organisation_id, lead_id, vacancy_id, unit_id, applicant_party_id, status, version, application_data, created_at, updated_at'
const client = (value = supabase) => { if (!value || (!isSupabaseConfigured && value === supabase)) throw new Error('Rental applications require Supabase configuration.'); return value }
const map = (row = {}) => ({ id: text(row.id), organisationId: text(row.organisation_id), leadId: text(row.lead_id), vacancyId: text(row.vacancy_id), unitId: text(row.unit_id), applicantPartyId: text(row.applicant_party_id), status: text(row.status), version: Number(row.version || 1), data: row.application_data || {}, updatedAt: row.updated_at || null })

export async function createPersistedRentalApplication(values = {}, { client: db = supabase } = {}) {
  const payload = { organisation_id: text(values.organisationId), lead_id: text(values.leadId) || null, vacancy_id: text(values.vacancyId), unit_id: text(values.unitId), applicant_party_id: text(values.applicantPartyId) || null, application_data: values.data && typeof values.data === 'object' ? values.data : {}, created_by: text(values.createdBy) || null }
  if (!payload.organisation_id || !payload.vacancy_id || !payload.unit_id) throw new Error('Organisation, vacancy and unit are required.')
  const result = await client(db).from('rental_applications').insert(payload).select(fields).single(); if (result.error) throw result.error; return map(result.data)
}
export async function savePersistedRentalApplication(application, patch = {}, { client: db = supabase } = {}) {
  const result = await client(db).from('rental_applications').update({ application_data: { ...(application.data || {}), ...(patch || {}) }, version: Number(application.version) + 1 }).eq('id', application.id).eq('version', application.version).select(fields).maybeSingle(); if (result.error) throw result.error; if (!result.data) throw new Error('Application changed elsewhere. Refresh and try again.'); return map(result.data)
}
export async function createPersistedRentalApplicantAccess(applicationId, { expiresInMinutes = 10080, createdBy = '', client: db = supabase } = {}) {
  const access = await createRentalApplicantAccess({ applicationId, expiresInMinutes }); const result = await client(db).from('rental_application_access_tokens').insert({ application_id: access.applicationId, token_hash: access.tokenHash, expires_at: access.expiresAt, created_by: text(createdBy) || null }).select('id, expires_at').single(); if (result.error) throw result.error; return { ...access, id: result.data.id, expiresAt: result.data.expires_at }
}
export async function listPersistedRentalApplications(organisationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_applications').select(fields).eq('organisation_id', text(organisationId)).order('updated_at', { ascending: false }).limit(100); if (result.error) throw result.error; return (result.data || []).map(map) }
export async function listPersistedRentalApplicationsForLead(organisationId, leadId, { client: db = supabase } = {}) { const result = await client(db).from('rental_applications').select(fields).eq('organisation_id', text(organisationId)).eq('lead_id', text(leadId)).order('updated_at', { ascending: false }).limit(100); if (result.error) throw result.error; return (result.data || []).map(map) }
export async function getRentalApplicationReview(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_review_summaries').select('id, status, version, application_data, submitted_at, updated_at, documents, consents').eq('id', text(applicationId)).maybeSingle(); if (result.error) throw result.error; return result.data ? { id: result.data.id, status: result.data.status, version: result.data.version, data: result.data.application_data || {}, submittedAt: result.data.submitted_at, updatedAt: result.data.updated_at, documents: result.data.documents || [], consents: result.data.consents || [] } : null }
const screeningFields = 'id, application_id, organisation_id, check_type, status, result_json, evidence_note, expires_at, reviewed_by, reviewed_at, updated_at'
const mapScreening = (row = {}) => ({ id: text(row.id), applicationId: text(row.application_id), organisationId: text(row.organisation_id), checkType: text(row.check_type), status: text(row.status), result: row.result_json || {}, evidenceNote: text(row.evidence_note), expiresAt: row.expires_at || null, reviewedBy: text(row.reviewed_by), reviewedAt: row.reviewed_at || null, updatedAt: row.updated_at || null })
export async function listRentalApplicationScreeningChecks(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_screening_checks').select(screeningFields).eq('application_id', text(applicationId)).order('check_type'); if (result.error) throw result.error; return (result.data || []).map(mapScreening) }
export async function saveRentalApplicationScreeningCheck(values = {}, { client: db = supabase } = {}) { const payload = { application_id: text(values.applicationId), organisation_id: text(values.organisationId), check_type: text(values.checkType), status: text(values.status) || 'not_started', result_json: values.result && typeof values.result === 'object' ? values.result : {}, evidence_note: text(values.evidenceNote) || null, expires_at: values.expiresAt || null, reviewed_by: text(values.reviewedBy) || null, reviewed_at: values.reviewedAt || null }; if (!payload.application_id || !payload.organisation_id || !payload.check_type) throw new Error('Application, organisation and screening type are required.'); const result = await client(db).from('rental_application_screening_checks').upsert(payload, { onConflict: 'application_id,check_type' }).select(screeningFields).single(); if (result.error) throw result.error; return mapScreening(result.data) }
const decisionFields = 'id, decision, reason, evidence_json, target_version, decided_by, decided_at'
const notificationFields = 'id, application_event_id, notification_type, delivery_status, retry_count, next_attempt_at, last_error, updated_at'
export async function listRentalApplicationDecisions(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_decisions').select(decisionFields).eq('application_id', text(applicationId)).order('decided_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function listRentalApplicationNotifications(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_notification_outbox').select(notificationFields).eq('application_id', text(applicationId)).order('created_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function decideRentalApplication({ applicationId, expectedVersion, decision, reason, evidence = {} } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_decide_application', { p_application_id: text(applicationId), p_expected_version: Number(expectedVersion), p_decision: text(decision), p_reason: text(reason), p_evidence_json: evidence && typeof evidence === 'object' ? evidence : {} }); if (result.error) throw result.error; return result.data }
export async function retryRentalApplicationNotification(outboxId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_retry_application_notification', { p_outbox_id: text(outboxId) }); if (result.error) throw result.error; return result.data }
export async function getRentalApplicationTenancyConversion(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_tenancies').select('id, status, intended_occupation_date, created_at, rental_leases(id, status, created_at)').eq('source_application_id', text(applicationId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function convertRentalApplicationToTenancy({ applicationId, expectedVersion } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_convert_application_to_tenancy', { p_application_id: text(applicationId), p_expected_version: Number(expectedVersion) }); if (result.error) throw result.error; return result.data }
export async function revokePersistedRentalApplicantAccess(accessId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_access_tokens').update({ revoked_at: new Date().toISOString() }).eq('id', text(accessId)).select('id, expires_at, revoked_at').single(); if (result.error) throw result.error; return result.data }
