import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'
import { createRentalPropertyLandlordPayload, createRentalPropertyMandatePayload, mapRentalPropertyLandlord, mapRentalPropertyMandate, mapRentalPropertyMarketingReadiness } from './rentalLandlordMandateModel.js'
const text = (value) => String(value ?? '').trim()
const LANDLORD_FIELDS = 'id, organisation_id, property_id, branch_id, party_id, ownership_share, is_primary_contact, relationship_status, effective_from, effective_to, metadata_json, created_at, updated_at'
const MANDATE_FIELDS = 'id, organisation_id, property_id, branch_id, mandate_status, authority_status, starts_on, ends_on, management_fee_type, management_fee_amount, metadata_json, created_at, updated_at'
function requireClient(client = supabase) { if (!isSupabaseConfigured || !client) throw new Error('Landlord mandates require Supabase configuration.'); return client }
function unavailable(error = {}) { const missing = ['42P01', 'PGRST204', 'PGRST205'].includes(String(error.code || '').toUpperCase()); return new Error(missing ? 'Rental landlord and mandate foundation is not yet applied to this environment.' : (error.message || 'Rental landlord request failed.')) }
export async function listRentalPropertyLandlords(propertyId = '', { client = supabase } = {}) { if (!text(propertyId)) return []; const result = await requireClient(client).from('rental_property_landlords').select(LANDLORD_FIELDS).eq('property_id', text(propertyId)).order('is_primary_contact', { ascending: false }).order('created_at'); if (result.error) throw unavailable(result.error); return (result.data || []).map(mapRentalPropertyLandlord) }
export async function createRentalPropertyLandlord(values = {}, { client = supabase } = {}) { const result = await requireClient(client).from('rental_property_landlords').insert(createRentalPropertyLandlordPayload(values)).select(LANDLORD_FIELDS).single(); if (result.error) throw unavailable(result.error); return mapRentalPropertyLandlord(result.data) }
export async function listRentalPropertyMandates(propertyId = '', { client = supabase } = {}) { if (!text(propertyId)) return []; const result = await requireClient(client).from('rental_property_mandates').select(MANDATE_FIELDS).eq('property_id', text(propertyId)).order('created_at', { ascending: false }); if (result.error) throw unavailable(result.error); return (result.data || []).map(mapRentalPropertyMandate) }
export async function createRentalPropertyMandate(values = {}, { client = supabase } = {}) { const result = await requireClient(client).from('rental_property_mandates').insert(createRentalPropertyMandatePayload(values)).select(MANDATE_FIELDS).single(); if (result.error) throw unavailable(result.error); return mapRentalPropertyMandate(result.data) }
export async function getRentalPropertyMarketingReadiness(propertyId = '', { client = supabase } = {}) { if (!text(propertyId)) return null; const result = await requireClient(client).from('rental_property_marketing_readiness').select('*').eq('property_id', text(propertyId)).maybeSingle(); if (result.error) throw unavailable(result.error); return result.data ? mapRentalPropertyMarketingReadiness(result.data) : null }
