import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'

const text = (value) => String(value ?? '').trim()
const requireClient = (client = supabase) => { if (!isSupabaseConfigured || !client) throw new Error('Renewals require Supabase configuration.'); return client }
export async function getRentalRenewal(tenancyId, { client = supabase } = {}) { const result = await requireClient(client).from('rental_renewals').select('id, tenancy_id, source_lease_version_id, status, proposal_version, proposed_terms, response_due_on, decision_note, decided_at, created_at, updated_at, rental_renewal_intentions(id, actor_type, intention, proposal_version, note, submitted_at), rental_renewal_events(id, event_type, payload, occurred_at)').eq('tenancy_id', text(tenancyId)).order('created_at', { ascending: false }).limit(1).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function openRentalRenewal({ tenancyId, responseDueOn = null } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_open_renewal', { p_tenancy_id: text(tenancyId), p_response_due_on: responseDueOn || null }); if (result.error) throw result.error; return result.data }
export async function saveRentalRenewalTerms({ renewalId, expectedVersion, terms, responseDueOn = null } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_save_renewal_terms', { p_renewal_id: text(renewalId), p_expected_version: Number(expectedVersion), p_terms: terms, p_response_due_on: responseDueOn || null }); if (result.error) throw result.error; return result.data }
export async function decideRentalRenewal({ renewalId, expectedVersion, decision, note = '' } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_decide_renewal', { p_renewal_id: text(renewalId), p_expected_version: Number(expectedVersion), p_decision: text(decision), p_note: text(note) || null }); if (result.error) throw result.error; return result.data }
export async function generateRentalRenewalLeaseVersion({ renewalId, expectedVersion } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_generate_renewal_lease_version', { p_renewal_id: text(renewalId), p_expected_proposal_version: Number(expectedVersion) }); if (result.error) throw result.error; return result.data }
export async function getRentalRenewalLeaseVersion(renewalId, { client = supabase } = {}) { const result = await requireClient(client).from('rental_renewal_lease_versions').select('id, renewal_lease_version_id, signing_status, generated_at, rental_lease_versions(id, version_number, status, effective_start_date, effective_end_date, occupation_date, monthly_rent, deposit_amount)').eq('renewal_id', text(renewalId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
