import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'

const text = (value) => String(value ?? '').trim()
const requireClient = (client = supabase) => { if (!isSupabaseConfigured || !client) throw new Error('Rental inspections require Supabase configuration.'); return client }
export async function listRentalInspectionTemplates(organisationId, { client = supabase } = {}) { const result = await requireClient(client).from('rental_inspection_templates').select('id, name, inspection_type, status, created_at, rental_inspection_template_items(id, item_key, item_label, sort_order, required)').eq('organisation_id', text(organisationId)).eq('status', 'active').order('created_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function listRentalInspectionSchedules({ client = supabase } = {}) { const result = await requireClient(client).from('rental_inspection_schedules').select('id, tenancy_id, template_id, scheduled_for, assigned_to, status, rental_inspection_templates(name, inspection_type)').order('scheduled_for', { ascending: true }).limit(100); if (result.error) throw result.error; return result.data || [] }
export async function createRentalInspectionTemplate({ organisationId, name, inspectionType, items } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_create_inspection_template', { o: text(organisationId), n: text(name), t: text(inspectionType), items: Array.isArray(items) ? items : [] }); if (result.error) throw result.error; return result.data }
export async function scheduleRentalInspection({ tenancyId, templateId, scheduledFor, assignedTo = null } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_schedule_inspection', { x: text(tenancyId), tplid: text(templateId), d: scheduledFor, a: text(assignedTo) || null }); if (result.error) throw result.error; return result.data }
export async function startRentalInspection(scheduleId, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_start_scheduled_inspection', { x: text(scheduleId) }); if (result.error) throw result.error; return result.data }
export async function getRentalFieldInspection(inspectionId, { client = supabase } = {}) { const result = await requireClient(client).from('rental_field_inspections').select('id, inspection_type, status, started_at, completed_at, tenancy_id, property_id, unit_id, summary_note, rental_field_inspection_items(id, item_key, item_label, status, note, evidence_link, updated_at)').eq('id', text(inspectionId)).maybeSingle(); if (result.error) throw result.error; if (!result.data) throw new Error('Inspection not found or you no longer have access.'); return { ...result.data, rental_field_inspection_items: [...(result.data.rental_field_inspection_items || [])].sort((a, b) => a.item_label.localeCompare(b.item_label)) } }
export async function recordRentalFieldInspectionItem({ itemId, status, note = '', evidenceLink = '' } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_record_field_inspection_item', { x: text(itemId), s: text(status), n: text(note) || null, e: text(evidenceLink) || null }); if (result.error) throw result.error; return result.data }
export async function completeRentalFieldInspection({ inspectionId, acknowledgementName, signatureEvidenceLink, summaryNote = '' } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_complete_field_inspection', { x: text(inspectionId), a: text(acknowledgementName), sig: text(signatureEvidenceLink), n: text(summaryNote) || null }); if (result.error) throw result.error; return result.data }
export async function getRentalInspectionFollowUp(inspectionId, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_get_inspection_follow_up', { p_inspection_id: text(inspectionId) }); if (result.error) throw result.error; return result.data || { inspection: null, items: [] } }
export async function createRentalInspectionMaintenanceRequest({ inspectionItemId, category, priority, description } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_create_inspection_maintenance_request', { p_inspection_item_id: text(inspectionItemId), p_category: text(category), p_priority: text(priority), p_description: text(description) }); if (result.error) throw result.error; return result.data }
