import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'
import { createRentalApplicantAccess } from './rentalApplicantAccessModel.js'

const text = (value) => String(value ?? '').trim()
const fields = 'id, organisation_id, vacancy_id, unit_id, applicant_party_id, status, version, application_data, created_at, updated_at'
const client = (value = supabase) => { if (!isSupabaseConfigured || !value) throw new Error('Rental applications require Supabase configuration.'); return value }
const map = (row = {}) => ({ id: text(row.id), organisationId: text(row.organisation_id), vacancyId: text(row.vacancy_id), unitId: text(row.unit_id), applicantPartyId: text(row.applicant_party_id), status: text(row.status), version: Number(row.version || 1), data: row.application_data || {}, updatedAt: row.updated_at || null })

export async function createPersistedRentalApplication(values = {}, { client: db = supabase } = {}) {
  const payload = { organisation_id: text(values.organisationId), vacancy_id: text(values.vacancyId), unit_id: text(values.unitId), applicant_party_id: text(values.applicantPartyId) || null, application_data: values.data && typeof values.data === 'object' ? values.data : {}, created_by: text(values.createdBy) || null }
  if (!payload.organisation_id || !payload.vacancy_id || !payload.unit_id) throw new Error('Organisation, vacancy and unit are required.')
  const result = await client(db).from('rental_applications').insert(payload).select(fields).single(); if (result.error) throw result.error; return map(result.data)
}
export async function savePersistedRentalApplication(application, patch = {}, { client: db = supabase } = {}) {
  const result = await client(db).from('rental_applications').update({ application_data: { ...(application.data || {}), ...(patch || {}) }, version: Number(application.version) + 1 }).eq('id', application.id).eq('version', application.version).select(fields).maybeSingle(); if (result.error) throw result.error; if (!result.data) throw new Error('Application changed elsewhere. Refresh and try again.'); return map(result.data)
}
export async function createPersistedRentalApplicantAccess(applicationId, { expiresInMinutes = 10080, createdBy = '', client: db = supabase } = {}) {
  const access = await createRentalApplicantAccess({ applicationId, expiresInMinutes }); const result = await client(db).from('rental_application_access_tokens').insert({ application_id: access.applicationId, token_hash: access.tokenHash, expires_at: access.expiresAt, created_by: text(createdBy) || null }).select('id, expires_at').single(); if (result.error) throw result.error; return { ...access, id: result.data.id, expiresAt: result.data.expires_at }
}
export async function listPersistedRentalApplications(organisationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_applications').select(fields).eq('organisation_id', text(organisationId)).order('updated_at', { ascending: false }).limit(100); if (result.error) throw result.error; return (result.data || []).map(map) }
export async function getRentalApplicationReview(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_review_summaries').select('id, status, version, application_data, submitted_at, updated_at, documents, consents').eq('id', text(applicationId)).maybeSingle(); if (result.error) throw result.error; return result.data ? { id: result.data.id, status: result.data.status, version: result.data.version, data: result.data.application_data || {}, submittedAt: result.data.submitted_at, updatedAt: result.data.updated_at, documents: result.data.documents || [], consents: result.data.consents || [] } : null }
const screeningFields = 'id, application_id, organisation_id, check_type, status, result_json, evidence_note, expires_at, reviewed_by, reviewed_at, updated_at'
const mapScreening = (row = {}) => ({ id: text(row.id), applicationId: text(row.application_id), organisationId: text(row.organisation_id), checkType: text(row.check_type), status: text(row.status), result: row.result_json || {}, evidenceNote: text(row.evidence_note), expiresAt: row.expires_at || null, reviewedBy: text(row.reviewed_by), reviewedAt: row.reviewed_at || null, updatedAt: row.updated_at || null })
export async function listRentalApplicationScreeningChecks(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_screening_checks').select(screeningFields).eq('application_id', text(applicationId)).order('check_type'); if (result.error) throw result.error; return (result.data || []).map(mapScreening) }
export async function saveRentalApplicationScreeningCheck(values = {}, { client: db = supabase } = {}) { const payload = { application_id: text(values.applicationId), organisation_id: text(values.organisationId), check_type: text(values.checkType), status: text(values.status) || 'not_started', result_json: values.result && typeof values.result === 'object' ? values.result : {}, evidence_note: text(values.evidenceNote) || null, expires_at: values.expiresAt || null, reviewed_by: text(values.reviewedBy) || null, reviewed_at: values.reviewedAt || null }; if (!payload.application_id || !payload.organisation_id || !payload.check_type) throw new Error('Application, organisation and screening type are required.'); const result = await client(db).from('rental_application_screening_checks').upsert(payload, { onConflict: 'application_id,check_type' }).select(screeningFields).single(); if (result.error) throw result.error; return mapScreening(result.data) }
const decisionFields = 'id, decision, reason, evidence_json, target_version, decided_by, decided_at'
const notificationFields = 'id, application_event_id, notification_type, delivery_status, retry_count, next_attempt_at, last_error, updated_at'
export async function listRentalApplicationDecisions(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_decisions').select(decisionFields).eq('application_id', text(applicationId)).order('decided_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function listRentalApplicationNotifications(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_notification_outbox').select(notificationFields).eq('application_id', text(applicationId)).order('created_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function decideRentalApplication({ applicationId, expectedVersion, decision, reason, evidence = {} } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_decide_application', { p_application_id: text(applicationId), p_expected_version: Number(expectedVersion), p_decision: text(decision), p_reason: text(reason), p_evidence_json: evidence && typeof evidence === 'object' ? evidence : {} }); if (result.error) throw result.error; return result.data }
export async function retryRentalApplicationNotification(outboxId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_retry_application_notification', { p_outbox_id: text(outboxId) }); if (result.error) throw result.error; return result.data }
export async function getRentalApplicationTenancyConversion(applicationId, { client: db = supabase } = {}) { const result = await client(db).from('rental_tenancies').select('id, status, intended_occupation_date, created_at, rental_leases(id, status, created_at)').eq('source_application_id', text(applicationId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function convertRentalApplicationToTenancy({ applicationId, expectedVersion } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_convert_application_to_tenancy', { p_application_id: text(applicationId), p_expected_version: Number(expectedVersion) }); if (result.error) throw result.error; return result.data }
export async function listRentalLeaseVersions(leaseId, { client: db = supabase } = {}) { const result = await client(db).from('rental_lease_versions').select('id, lease_id, version_number, status, is_current, effective_start_date, effective_end_date, occupation_date, monthly_rent, deposit_amount, escalation_json, terms_json, created_at, rental_lease_version_documents(id, document_label, document_link, created_at)').eq('lease_id', text(leaseId)).order('version_number', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function saveRentalLeaseDraft({ leaseId, expectedVersion, terms } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_save_lease_draft', { p_lease_id: text(leaseId), p_expected_version: Number(expectedVersion), p_terms_json: terms && typeof terms === 'object' ? terms : {} }); if (result.error) throw result.error; return result.data }
export async function linkRentalLeaseVersionDocument({ leaseVersionId, label, link } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_link_lease_version_document', { p_lease_version_id: text(leaseVersionId), p_document_label: text(label), p_document_link: text(link) }); if (result.error) throw result.error; return result.data }
export async function listRentalLeaseSigners(leaseVersionId, { client: db = supabase } = {}) { const result = await client(db).from('rental_lease_signers').select('id, signer_role, signer_name, signer_email, status, signed_at, signed_document_link, evidence_note, updated_at').eq('lease_version_id', text(leaseVersionId)).order('signer_role'); if (result.error) throw result.error; return result.data || [] }
export async function prepareRentalLeaseSigning({ leaseId, expectedVersion, signers } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_prepare_lease_signing', { p_lease_id: text(leaseId), p_expected_version: Number(expectedVersion), p_signers: Array.isArray(signers) ? signers : [] }); if (result.error) throw result.error; return result.data }
export async function recordRentalLeaseSignature({ signerId, outcome, documentLink = '', evidenceNote = '' } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_record_lease_signature', { p_signer_id: text(signerId), p_outcome: text(outcome), p_document_link: text(documentLink) || null, p_evidence_note: text(evidenceNote) || null }); if (result.error) throw result.error; return result.data }
export async function reopenRentalLeaseSigner({ signerId, reason } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_reopen_lease_signer', { p_signer_id: text(signerId), p_reason: text(reason) }); if (result.error) throw result.error; return result.data }
export async function listRentalMoveInReadiness(leaseId, { client: db = supabase } = {}) { const result = await client(db).from('rental_move_in_readiness_items').select('id, tenancy_id, obligation_type, required_amount, received_amount, status, evidence_link, exception_reason, reviewed_at').eq('lease_id', text(leaseId)).order('obligation_type'); if (result.error) throw result.error; return result.data || [] }
export async function recordRentalMoveInReadiness({ itemId, status, receivedAmount, evidenceLink = '', exceptionReason = '' } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_record_move_in_readiness', { p_readiness_item_id: text(itemId), p_status: text(status), p_received_amount: receivedAmount === '' || receivedAmount === null || receivedAmount === undefined ? null : Number(receivedAmount), p_evidence_link: text(evidenceLink) || null, p_exception_reason: text(exceptionReason) || null }); if (result.error) throw result.error; return result.data }
export async function assertRentalTenancyActivationReady(tenancyId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_assert_tenancy_activation_ready', { p_tenancy_id: text(tenancyId) }); if (result.error) throw result.error; return result.data }
export async function getRentalIncomingInspection(tenancyId, { client: db = supabase } = {}) { const result = await client(db).from('rental_incoming_inspections').select('id, status, scheduled_for, completed_at, acknowledged_by_name, handover_notes, rental_incoming_inspection_items(id, item_key, status, note, evidence_link), rental_incoming_inspection_media(id, media_link, caption)').eq('tenancy_id', text(tenancyId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function startRentalIncomingInspection({ tenancyId, scheduledFor = null } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_start_incoming_inspection', { p_tenancy_id: text(tenancyId), p_scheduled_for: scheduledFor || null }); if (result.error) throw result.error; return result.data }
export async function recordRentalIncomingInspectionItem({ itemId, status, note = '', evidenceLink = '' } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_record_incoming_inspection_item', { p_item_id: text(itemId), p_status: text(status), p_note: text(note) || null, p_evidence_link: text(evidenceLink) || null }); if (result.error) throw result.error; return result.data }
export async function linkRentalIncomingInspectionMedia({ inspectionId, mediaLink, caption = '' } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_link_incoming_inspection_media', { p_inspection_id: text(inspectionId), p_media_link: text(mediaLink), p_caption: text(caption) || null }); if (result.error) throw result.error; return result.data }
export async function completeRentalIncomingInspection({ inspectionId, acknowledgedByName, handoverNotes = '' } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_complete_incoming_inspection', { p_inspection_id: text(inspectionId), p_acknowledged_by_name: text(acknowledgedByName), p_handover_notes: text(handoverNotes) || null }); if (result.error) throw result.error; return result.data }
export async function getRentalTenancyActivationEvent(tenancyId, { client: db = supabase } = {}) { const result = await client(db).from('rental_tenancy_activation_events').select('id, tenancy_id, lease_id, unit_id, vacancy_id, activated_at, result_json').eq('tenancy_id', text(tenancyId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function activateRentalTenancy(tenancyId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_activate_tenancy', { p_tenancy_id: text(tenancyId) }); if (result.error) throw result.error; return result.data }
export async function getRentalTenancyWorkspaceSummary(tenancyId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_get_tenancy_workspace_summary', { p_tenancy_id: text(tenancyId) }); if (result.error) throw result.error; return result.data }
export async function getRentalTenancyLeaseDetails(tenancyId, { client: db = supabase } = {}) { const result = await client(db).from('rental_leases').select('id, status, terms_json, created_at, rental_lease_versions(id, version_number, status, is_current, effective_start_date, effective_end_date, occupation_date, monthly_rent, deposit_amount, rental_lease_version_documents(id, document_label, document_link, created_at))').eq('tenancy_id', text(tenancyId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function getRentalTenancyActivity(tenancyId, { limit = 40, client: db = supabase } = {}) { const result = await client(db).rpc('rental_get_tenancy_activity', { p_tenancy_id: text(tenancyId), p_limit: Number(limit) }); if (result.error) throw result.error; return result.data || [] }
export async function getRentalTenancyDocuments(tenancyId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_get_tenancy_documents', { p_tenancy_id: text(tenancyId) }); if (result.error) throw result.error; return result.data || [] }
export async function listRentalChargeSchedules(tenancyId, { client: db = supabase } = {}) { const result = await client(db).from('rental_charge_schedules').select('id, charge_type, amount, currency_code, start_date, end_date, due_day, status').eq('tenancy_id', text(tenancyId)).order('start_date'); if (result.error) throw result.error; return result.data || [] }
export async function listRentalFinancialCharges(tenancyId, { client: db = supabase } = {}) { const result = await client(db).from('rental_financial_charges').select('id, charge_type, effective_date, due_date, amount, currency_code, description, source_key, created_at').eq('tenancy_id', text(tenancyId)).order('due_date', { ascending: false }).limit(120); if (result.error) throw result.error; return result.data || [] }
export async function generateRentalTenancyCharges(tenancyId, throughDate = null, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_generate_tenancy_charges', { p_tenancy_id: text(tenancyId), p_through_date: throughDate || new Date().toISOString().slice(0, 10) }); if (result.error) throw result.error; return result.data }
export async function recordRentalPayment({ tenancyId, amount, receivedDate, paymentReference, paymentMethod, evidenceLink } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_record_payment', { p_tenancy_id: text(tenancyId), p_amount: Number(amount), p_received_date: receivedDate, p_payment_reference: text(paymentReference), p_payment_method: text(paymentMethod), p_evidence_link: text(evidenceLink) }); if (result.error) throw result.error; return result.data }
export async function getRentalTenancyFinancialBalances(tenancyId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_get_tenancy_financial_balances', { p_tenancy_id: text(tenancyId) }); if (result.error) throw result.error; return result.data || { charges: [], payments: [] } }
export async function allocateRentalPayment(paymentId, allocations = [], { client: db = supabase } = {}) { const result = await client(db).rpc('rental_allocate_payment', { p_payment_id: text(paymentId), p_allocations: Array.isArray(allocations) ? allocations : [] }); if (result.error) throw result.error; return result.data }
export async function listRentalFinancialCorrections(tenancyId, { client: db = supabase } = {}) { const result = await client(db).from('rental_financial_correction_requests').select('id, correction_kind, adjustment_type, amount, effective_date, reason, status, requested_by, requested_at, approved_by, approved_at, original_payment_id, applied_adjustment_id').eq('tenancy_id', text(tenancyId)).order('requested_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function requestRentalFinancialAdjustment({ tenancyId, adjustmentType, amount, effectiveDate, reason } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_request_financial_adjustment', { p_tenancy: text(tenancyId), p_type: text(adjustmentType), p_amount: Number(amount), p_date: effectiveDate, p_reason: text(reason) }); if (result.error) throw result.error; return result.data }
export async function requestRentalPaymentReversal({ paymentId, effectiveDate, reason } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_request_payment_reversal', { p_payment: text(paymentId), p_date: effectiveDate, p_reason: text(reason) }); if (result.error) throw result.error; return result.data }
export async function approveRentalFinancialCorrection(correctionId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_approve_financial_correction', { p_id: text(correctionId) }); if (result.error) throw result.error; return result.data }
export async function getRentalArrearsDashboard({ asOfDate = null, limit = 250 } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_get_arrears_dashboard', { p_as_of: asOfDate || new Date().toISOString().slice(0, 10), p_limit: Number(limit) }); if (result.error) throw result.error; return result.data || { summary: {}, rows: [] } }
export async function stageRentalFinancialImport({ sourceName, fingerprint, rows } = {}, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_stage_financial_import', { p_source: text(sourceName), p_fingerprint: text(fingerprint), p_rows: Array.isArray(rows) ? rows : [] }); if (result.error) throw result.error; return result.data }
export async function approveRentalFinancialImport(batchId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_approve_financial_import', { p_id: text(batchId) }); if (result.error) throw result.error; return result.data }
export async function postRentalFinancialImport(batchId, { client: db = supabase } = {}) { const result = await client(db).rpc('rental_post_financial_import', { p_id: text(batchId) }); if (result.error) throw result.error; return result.data }
export async function getRentalFinancialImportBatch(batchId, { client: db = supabase } = {}) { const result = await client(db).from('rental_financial_import_batches').select('id, source_name, status, row_count, valid_row_count, invalid_row_count, total_amount, created_at, approved_at, posted_at, rental_financial_import_rows(id, row_number, entry_type, tenancy_id, amount, effective_date, payment_reference, status, validation_errors)').eq('id', text(batchId)).maybeSingle(); if (result.error) throw result.error; return result.data || null }
export async function revokePersistedRentalApplicantAccess(accessId, { client: db = supabase } = {}) { const result = await client(db).from('rental_application_access_tokens').update({ revoked_at: new Date().toISOString() }).eq('id', text(accessId)).select('id, expires_at, revoked_at').single(); if (result.error) throw result.error; return result.data }
