import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'
import { createRentalDocumentLinkPayload, mapRentalActivityProjection, mapRentalDocumentLink } from './rentalEvidenceModel.js'
const text = (value) => String(value ?? '').trim()
const DOCUMENT_FIELDS = 'id, organisation_id, property_id, entity_type, entity_id, document_id, document_label, document_category, link_state, replaces_link_id, created_at'
const ACTIVITY_FIELDS = 'id, source_event_id, organisation_id, property_id, entity_type, entity_id, activity_type, title, description, occurred_at'
function requireClient(client = supabase) { if (!isSupabaseConfigured || !client) throw new Error('Rental evidence requires Supabase configuration.'); return client }
function unavailable(error = {}) { const missing = ['42P01', 'PGRST204', 'PGRST205'].includes(String(error.code || '').toUpperCase()); return new Error(missing ? 'Rental evidence foundation is not yet applied to this environment.' : (error.message || 'Rental evidence request failed.')) }
export async function listRentalDocumentLinks({ propertyId = '', entityType = '', entityId = '', limit = 100 } = {}, { client = supabase } = {}) { if (!text(propertyId)) return []; let query = requireClient(client).from('rental_entity_documents').select(DOCUMENT_FIELDS).eq('property_id', text(propertyId)).order('created_at', { ascending: false }).limit(Math.min(Math.max(Number(limit) || 100, 1), 200)); if (text(entityType)) query = query.eq('entity_type', text(entityType)); if (text(entityId)) query = query.eq('entity_id', text(entityId)); const result = await query; if (result.error) throw unavailable(result.error); return (result.data || []).map(mapRentalDocumentLink) }
export async function createRentalDocumentLink(values = {}, { client = supabase } = {}) { const result = await requireClient(client).from('rental_entity_documents').insert(createRentalDocumentLinkPayload(values)).select(DOCUMENT_FIELDS).single(); if (result.error) throw unavailable(result.error); return mapRentalDocumentLink(result.data) }
export async function listRentalActivityProjections({ propertyId = '', limit = 100 } = {}, { client = supabase } = {}) { if (!text(propertyId)) return []; const result = await requireClient(client).from('rental_activity_projections').select(ACTIVITY_FIELDS).eq('property_id', text(propertyId)).order('occurred_at', { ascending: false }).limit(Math.min(Math.max(Number(limit) || 100, 1), 200)); if (result.error) throw unavailable(result.error); return (result.data || []).map(mapRentalActivityProjection) }
