import { isSupabaseConfigured, supabase } from '../../lib/supabaseClient.js'

const text = (value) => String(value ?? '').trim()
const requireClient = (client = supabase) => { if (!isSupabaseConfigured || !client) throw new Error('Rental notices require Supabase configuration.'); return client }

export async function listRentalNotices(tenancyId, { client = supabase } = {}) { const result = await requireClient(client).from('rental_notices').select('id, source, notice_type, status, received_on, effective_on, acknowledgement_due_on, evidence_link, note, submitted_at, acknowledged_at, withdrawal_reason').eq('tenancy_id', text(tenancyId)).order('submitted_at', { ascending: false }); if (result.error) throw result.error; return result.data || [] }
export async function getRentalTenancyNoticeStatus(tenancyId, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_get_tenancy_notice_status', { p_tenancy_id: text(tenancyId) }); if (result.error) throw result.error; return result.data || { notice_given: false } }
export async function captureRentalNotice({ tenancyId, source, noticeType, receivedOn, effectiveOn, evidenceLink, note = '' } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_capture_notice', { p_tenancy_id: text(tenancyId), p_source: text(source), p_notice_type: text(noticeType), p_received_on: receivedOn || null, p_effective_on: effectiveOn || null, p_evidence_link: text(evidenceLink), p_note: text(note) || null }); if (result.error) throw result.error; return result.data }
export async function submitRentalPortalNotice({ tenancyId, noticeType, effectiveOn, evidenceLink, note = '' } = {}, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_submit_portal_notice', { p_tenancy_id: text(tenancyId), p_notice_type: text(noticeType), p_effective_on: effectiveOn || null, p_evidence_link: text(evidenceLink), p_note: text(note) || null }); if (result.error) throw result.error; return result.data }
export async function acknowledgeRentalNotice(noticeId, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_acknowledge_notice', { p_notice_id: text(noticeId) }); if (result.error) throw result.error; return result.data }
export async function withdrawRentalNotice(noticeId, reason, { client = supabase } = {}) { const result = await requireClient(client).rpc('rental_withdraw_notice', { p_notice_id: text(noticeId), p_reason: text(reason) }); if (result.error) throw result.error; return result.data }
