// @vitest-environment jsdom
import React from 'react'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const api = vi.hoisted(() => ({ list:vi.fn(), rsvps:vi.fn(), shared:true, org:'org-1' }))
vi.mock('../../../context/OrganisationContext', () => ({useOrganisation:()=>({organisation:{id:api.org}})}))
vi.mock('../../../services/marketingEventRepository', () => ({canPersistMarketingEvents:()=>api.shared,listMarketingEvents:api.list}))
vi.mock('../../../services/marketingEventOperationsService', () => ({listMarketingEventRsvps:api.rsvps,checkInMarketingEventRsvp:vi.fn(),processMarketingEventConversion:vi.fn(),updateMarketingEventRsvpInterest:vi.fn()}))
vi.mock('../../../lib/marketingEventStore',()=>({useMarketingEvents:vi.fn()}))
import { ShowDaysOverview } from '../ShowDays'
const events=[{id:'e1',title:'Parkhurst home',address:'7 Sixth Street',status:'Completed',date:'23 Aug 2026',publicToken:'t1',registrations:24,attendees:18,confirmed:20,interestedLeads:6},{id:'e2',title:'Draft home',address:'Sea Point',status:'Draft',date:'Date to be confirmed'}]
beforeEach(()=>{vi.clearAllMocks();api.shared=true;api.org='org-1';localStorage.clear();api.list.mockResolvedValue(events);api.rsvps.mockResolvedValue([{id:'v1',status:'confirmed',checked_in_at:'2026-08-23T10:00:00Z',interest_level:'high'},{id:'v2',status:'confirmed'}])})
afterEach(cleanup)
it('uses registration records for cards and totals, replacing stale saved metrics',async()=>{render(<ShowDaysOverview />);await screen.findByRole('button',{name:'View show day: Parkhurst home'});const stats=screen.getByRole('region',{name:'Show day performance'});expect(stats.querySelectorAll('article')).toHaveLength(5);expect(Array.from(stats.querySelectorAll('strong')).map(el=>el.textContent)).toEqual(['2','2','1','50%','1']);const row=document.querySelector('.show-landing-event');expect(within(row).getByText('Registrations').nextElementSibling.textContent).toBe('2');expect(api.list).toHaveBeenCalledWith('org-1','showDays')})
it('supports draft filtering, search, clear filters, sorting and both row actions',async()=>{const open=vi.fn(),create=vi.fn();render(<ShowDaysOverview onOpenShowDay={open} onCreateShowDay={create}/>);await screen.findByRole('button',{name:'View show day: Parkhurst home'});fireEvent.click(screen.getByRole('tab',{name:'Draft 1'}));expect(screen.queryByRole('button',{name:'View show day: Parkhurst home'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'View show day: Draft home'}));expect(open).toHaveBeenCalledWith('e2');fireEvent.click(screen.getByRole('button',{name:'View show day',exact:true}));expect(open).toHaveBeenCalledTimes(2);fireEvent.change(screen.getByLabelText('Search show days'),{target:{value:'nothing'}});fireEvent.click(screen.getByRole('button',{name:'Clear filters'}));fireEvent.change(screen.getByLabelText('Sort show days'),{target:{value:'title'}});expect(document.querySelector('.show-landing-event h3').textContent).toBe('Draft home');fireEvent.click(screen.getByRole('button',{name:'Create show day',exact:true}));expect(create).toHaveBeenCalledTimes(1)})
it('shows a real empty state and never substitutes demo events on shared load failures',async()=>{api.list.mockRejectedValue(new Error('Network unavailable'));render(<ShowDaysOverview/>);expect((await screen.findByRole('alert')).textContent).toBe('Network unavailable');expect(document.querySelectorAll('.show-landing-event')).toHaveLength(0);expect(screen.queryByText('Constantia Park')).toBeNull()})
it('retains saved totals only with an explicit warning when visitor records fail',async()=>{api.rsvps.mockRejectedValue(new Error('Unavailable'));render(<ShowDaysOverview/>);await screen.findByRole('status');expect(screen.getByRole('status').textContent).toContain('last saved totals');expect(document.querySelector('.show-landing-event dd').textContent).toBe('24')})
it('starts local planning empty instead of injecting demo events',async()=>{api.shared=false;const create=vi.fn();render(<ShowDaysOverview onCreateShowDay={create}/>);await screen.findByText('Make your next viewing an event');expect(api.list).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Create your first show day'}));expect(create).toHaveBeenCalledTimes(1);expect(screen.getByText('Local planner')).toBeTruthy()})
it('ignores a previous organisation response after switching scope',async()=>{let resolve;api.list.mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const {rerender}=render(<ShowDaysOverview/>);api.org='org-2';api.list.mockResolvedValue([]);rerender(<ShowDaysOverview/>);await screen.findByText('Make your next viewing an event');resolve(events);await waitFor(()=>expect(document.querySelectorAll('.show-landing-event')).toHaveLength(0))})
