// @vitest-environment jsdom
import { act, cleanup, renderHook } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import useBuyerFinanceRefresh from '../useBuyerFinanceRefresh'
beforeEach(() => {
  vi.useFakeTimers()
  Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'visible' })
  Object.defineProperty(navigator, 'onLine', { configurable: true, value: true })
})
afterEach(() => { cleanup(); vi.useRealTimers() })
const options = readFinance => ({ token: 'buyer-a', transactionId: 'matter-a', enabled: true, initialFinance: { status: 'seed' }, readFinance })
it('refreshes on opening, polling and reconnect, pauses offline, and clears stale success on failures', async () => {
  const read = vi.fn().mockResolvedValue({ bankApplications: [{ bankName: 'Nedbank' }] })
  const { result } = renderHook(() => useBuyerFinanceRefresh(options(read)))
  await act(() => vi.advanceTimersByTimeAsync(400))
  expect(result.current.finance.bankApplications).toHaveLength(1)
  read.mockResolvedValue({ offerCaptures: [{ id: 'published-quote' }] })
  await act(() => vi.advanceTimersByTimeAsync(30_000))
  expect(result.current.finance.offerCaptures[0].id).toBe('published-quote')
  Object.defineProperty(navigator,'onLine',{configurable:true,value:false})
  await act(() => vi.advanceTimersByTimeAsync(30_000))
  expect(read).toHaveBeenCalledTimes(2)
  read.mockRejectedValue(new Error('access removed'))
  Object.defineProperty(navigator,'onLine',{configurable:true,value:true})
  await act(async () => { window.dispatchEvent(new Event('online')); await vi.advanceTimersByTimeAsync(400) })
  expect(result.current.finance).toBeNull()
  expect(result.current.failed).toBe(true)
  read.mockResolvedValue({ applicationReceived: true })
  await act(async () => { await result.current.refresh() })
  expect(result.current.finance.applicationReceived).toBe(true)
  expect(result.current.failed).toBe(false)
})
it('deduplicates an in-flight refresh and ignores old matter results after switching scopes', async () => {
  let release
  const delayed = new Promise(resolve => { release = resolve })
  const read = vi.fn(token => token === 'buyer-a' ? delayed : Promise.resolve({ manager: { name: 'Matter B consultant' } }))
  const { result, rerender } = renderHook(props => useBuyerFinanceRefresh(props), { initialProps: options(read) })
  let first, duplicate
  act(() => { first = result.current.refresh(); duplicate = result.current.refresh() })
  await act(async () => { await Promise.resolve() })
  expect(read).toHaveBeenCalledTimes(1)
  rerender({ ...options(read), token: 'buyer-b', transactionId: 'matter-b', initialFinance: null })
  await act(async () => { await result.current.refresh() })
  expect(result.current.finance.manager.name).toBe('Matter B consultant')
  await act(async () => { release({ manager: { name: 'Matter A consultant' } }); await first; await duplicate })
  expect(result.current.finance.manager.name).toBe('Matter B consultant')
})
it('allows retry after a synchronous reader failure and does not poll hidden pages', async () => {
  const read = vi.fn(() => { throw new Error('unavailable') })
  const { result } = renderHook(() => useBuyerFinanceRefresh(options(read)))
  await act(async () => { await result.current.refresh() })
  read.mockResolvedValue({ applicationReceived: true })
  await act(async () => { await result.current.refresh() })
  expect(result.current.finance.applicationReceived).toBe(true)
  Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'})
  await act(() => vi.advanceTimersByTimeAsync(60_000))
  expect(read).toHaveBeenCalledTimes(2)
})
it('times out a stalled read, permits a retry and ignores the late stalled result', async () => {
  let release
  const read = vi.fn().mockImplementationOnce(()=>new Promise(resolve=>{release=resolve})).mockResolvedValue({applicationReceived:true})
  const { result }=renderHook(()=>useBuyerFinanceRefresh(options(read)))
  act(()=>{void result.current.refresh()})
  await act(()=>vi.advanceTimersByTimeAsync(15_100))
  expect(result.current.refreshing).toBe(false)
  expect(result.current.finance).toBeNull()
  await act(async()=>{await result.current.refresh()})
  expect(result.current.finance.applicationReceived).toBe(true)
  await act(async()=>{release({applicationReceived:false});await Promise.resolve()})
  expect(result.current.finance.applicationReceived).toBe(true)
})
