// @vitest-environment jsdom
import { act, cleanup, renderHook, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
vi.mock('../../lib/agencyPipelineService', () => ({ listAppointmentsAsync: vi.fn() }))
import { listAppointmentsAsync } from '../../lib/agencyPipelineService'
import usePipelineAppointments from '../usePipelineAppointments'
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); vi.resetAllMocks() })
const deferred = () => { let resolve; const promise = new Promise((done) => { resolve = done }); return { promise, resolve } }
const base = { organisationId: 'agency', agentId: 'agent' }
describe('independent appointment loading', () => {
  it('loads full lead history without a date bound', async () => {
    const rows = [{ appointmentId: 'future', dateTime: '2027-10-01T09:40:00Z' }]
    listAppointmentsAsync.mockResolvedValue(rows)
    const { result } = renderHook(() => usePipelineAppointments({ ...base, leadId: 'seller' }))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    expect(result.current.rows).toEqual(rows)
    expect(listAppointmentsAsync).toHaveBeenCalledWith('agency', expect.objectContaining({ leadId: 'seller', from: null, to: null }))
  })
  it('ignores a late response after calendar navigation or an organisation change', async () => {
    const old = deferred(); const next = deferred()
    listAppointmentsAsync.mockReturnValueOnce(old.promise).mockReturnValueOnce(next.promise)
    const { result, rerender } = renderHook((props) => usePipelineAppointments(props), { initialProps: { ...base, from: '2026-10-01' } })
    await waitFor(() => expect(listAppointmentsAsync).toHaveBeenCalledTimes(1))
    rerender({ ...base, organisationId: 'other', from: '2027-10-01' })
    await waitFor(() => expect(listAppointmentsAsync).toHaveBeenCalledTimes(2))
    await act(async () => next.resolve([{ appointmentId: 'new' }]))
    await act(async () => old.resolve([{ appointmentId: 'stale' }]))
    expect(result.current.rows).toEqual([{ appointmentId: 'new' }])
  })
  it('preserves rows after failed refresh and replaces them after a verified empty retry', async () => {
    listAppointmentsAsync.mockResolvedValueOnce([{ appointmentId: 'saved' }]).mockRejectedValueOnce(new Error('Network failed')).mockResolvedValueOnce([])
    const { result } = renderHook(() => usePipelineAppointments(base))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.reload())
    await waitFor(() => expect(result.current.error).toBe('Network failed'))
    expect(result.current.rows).toEqual([{ appointmentId: 'saved' }])
    act(() => result.current.reload())
    await waitFor(() => expect(result.current.status).toBe('ready'))
    expect(result.current.rows).toEqual([])
  })
  it('reports a timeout and ignores its late result', async () => {
    const request = deferred(); listAppointmentsAsync.mockReturnValue(request.promise)
    const { result } = renderHook(() => usePipelineAppointments({ ...base, timeoutMs: 10 }))
    await waitFor(() => expect(result.current.status).toBe('error'))
    expect(result.current.error).toContain('taking too long')
    await act(async () => request.resolve([{ appointmentId: 'late' }]))
    expect(result.current.status).toBe('error')
    expect(result.current.rows).toEqual([])
  })
  it('does not treat malformed data as an empty calendar', async () => {
    listAppointmentsAsync.mockResolvedValue(null)
    const { result } = renderHook(() => usePipelineAppointments(base))
    await waitFor(() => expect(result.current.error).toContain('could not be verified'))
  })
  it('reconciles another device’s edit even when the appointment count stays the same', async () => {
    vi.useFakeTimers()
    vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('visible')
    listAppointmentsAsync.mockResolvedValueOnce([{ appointmentId: 'same', status: 'requested' }]).mockResolvedValueOnce([{ appointmentId: 'same', status: 'cancelled' }])
    const { result } = renderHook(() => usePipelineAppointments(base))
    await act(async () => {})
    expect(result.current.rows[0].status).toBe('requested')
    await act(async () => { await vi.advanceTimersByTimeAsync(30100) })
    expect(result.current.rows).toEqual([{ appointmentId: 'same', status: 'cancelled' }])
    expect(result.current.hasSnapshot).toBe(true)
  })
  it('coalesces edits, focus and reconnect, pauses hidden polling and cleans up on unmount', async () => {
    vi.useFakeTimers()
    const visible = vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('visible')
    listAppointmentsAsync.mockResolvedValue([])
    const { unmount } = renderHook(() => usePipelineAppointments(base))
    await act(async () => {})
    act(() => { window.dispatchEvent(new Event('itg:agency-crm-updated')); window.dispatchEvent(new Event('focus')); window.dispatchEvent(new Event('online')) })
    await act(async () => { await vi.advanceTimersByTimeAsync(100) })
    expect(listAppointmentsAsync).toHaveBeenCalledTimes(2)
    visible.mockReturnValue('hidden')
    await act(async () => { await vi.advanceTimersByTimeAsync(60000) })
    expect(listAppointmentsAsync).toHaveBeenCalledTimes(2)
    visible.mockReturnValue('visible')
    act(() => document.dispatchEvent(new Event('visibilitychange')))
    await act(async () => { await vi.advanceTimersByTimeAsync(100) })
    expect(listAppointmentsAsync).toHaveBeenCalledTimes(3)
    unmount()
    window.dispatchEvent(new Event('online'))
    await vi.advanceTimersByTimeAsync(60000)
    expect(listAppointmentsAsync).toHaveBeenCalledTimes(3)
  })
  it('does not display the previous viewer’s snapshot after an account change in the same organisation', async () => {
    listAppointmentsAsync.mockResolvedValueOnce([{ appointmentId: 'private' }]).mockRejectedValueOnce(new Error('No access'))
    const { result, rerender } = renderHook((props) => usePipelineAppointments(props), { initialProps: { ...base, viewerId: 'first' } })
    await waitFor(() => expect(result.current.hasSnapshot).toBe(true))
    rerender({ ...base, viewerId: 'second' })
    expect(result.current.rows).toEqual([])
    expect(result.current.hasSnapshot).toBe(false)
    await waitFor(() => expect(result.current.status).toBe('error'))
    expect(result.current.rows).toEqual([])
  })
  it('hides a verified snapshot while workspace permissions are loading', async () => {
    listAppointmentsAsync.mockResolvedValue([{ appointmentId: 'private' }])
    const { result, rerender } = renderHook((props) => usePipelineAppointments(props), { initialProps: base })
    await waitFor(() => expect(result.current.hasSnapshot).toBe(true))
    rerender({ ...base, enabled: false })
    expect(result.current.rows).toEqual([])
    expect(result.current.hasSnapshot).toBe(false)
  })
})
