import { getPrivateListingStatusLabel } from '../../lib/privateListingLifecycle.js'
function TextField({ form, update, name, label, type = 'text', multiline = false }) {
  const Component = multiline ? 'textarea' : 'input'
  return <label className="grid gap-2"><span className="text-sm font-semibold text-[#33493e]">{label}</span><Component className="w-full rounded-xl border border-[#dce4de] bg-white px-3 py-3" type={multiline ? undefined : type} min={type === 'number' ? '0' : undefined} step={type === 'number' ? 'any' : undefined} value={form[name] ?? ''} onChange={(event) => update(name, event.target.value)} /></label>
}
function SelectField({ form, update, name, label, options }) {
  return <label className="grid gap-2"><span className="text-sm font-semibold text-[#33493e]">{label}</span><select className="w-full rounded-xl border border-[#dce4de] bg-white px-3 py-3" value={form[name] ?? ''} onChange={(event) => update(name, event.target.value)}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>
}
export function MobileDeveloperListingStock({ form, update, developments, units, unitsLoading, onSelectUnit, agents, branches, canAssign, canAssignAcross }) {
  return <div className="space-y-6"><header><h2>Development & unit</h2><p className="text-xs leading-6 text-[#627068]">Choose your stock, then add its listing details.</p></header><div className="grid gap-4"><SelectField form={form} update={update} name="developmentId" label="Development *" options={[[ '', 'Select development' ], ...developments.map((row) => [row.id, row.name || 'Development'])]} /><label className="grid gap-2"><span className="text-sm font-semibold text-[#33493e]">Unit *</span><select className="w-full rounded-xl border border-[#dce4de] bg-white px-3 py-3" value={form.unitId} disabled={!form.developmentId || unitsLoading} onChange={(event) => onSelectUnit(event.target.value)}><option value="">{unitsLoading ? 'Loading units…' : form.developmentId ? 'Select unit' : 'Select development first'}</option>{units.map((unit) => <option key={unit.id} value={unit.id}>Unit {unit.unit_number || unit.unitNumber || unit.label || 'Unnumbered'}{unit.phase ? ` · ${unit.phase}` : ''}</option>)}</select></label></div><MobileListingAssignment form={form} update={update} agents={agents} branches={branches} canAssign={canAssign} canAssignAcross={canAssignAcross} /></div>
}
export function MobileListingAssignment({ form, update, agents, branches, canAssign, canAssignAcross }) {
  const selectAgent = (name, value) => {
    const agent = agents.find((item) => String(item.userId || item.id || item.email) === value)
    update(name, value); update('assignedAgentEmail', agent?.email || ''); update('assignedAgent', agent?.fullName || agent?.email || '')
    if (agent?.branchId) update('branchId', agent.branchId)
  }
  return <details className="mobile-listing-more-fields" open><summary>Sales assignment</summary><div>{canAssign ? <SelectField form={form} update={selectAgent} name="assignedAgentId" label="Assigned sales user" options={agents.map((agent) => [agent.userId || agent.id || agent.email, agent.fullName || agent.email || 'Sales user'])} /> : <p className="text-xs text-[#627068]">Assigned to {form.assignedAgent || 'you'}.</p>}{branches.length > 0 && canAssign && <SelectField form={form} update={update} name="branchId" label="Branch" options={[[ '', 'Current branch' ], ...branches.map((row) => [row.id || row.name, row.name || 'Branch'])]} />}<SelectField form={form} update={update} name="visibility" label="Internal visibility" options={[[ 'agent', 'Assigned sales user' ], [ 'branch', 'Branch' ], ...(canAssignAcross ? [[ 'organisation', 'Organisation' ]] : [])]} /></div></details>
}
export function MobileListingSellerFields({ form, update, documentCategories, mandateTypes, maritalStatuses, complianceMethods, captureSources }) {
  const type = form.sellerType
  return <>
    <details className="mobile-listing-more-fields"><summary>Additional seller details</summary><div>
      {type === 'foreign_individual' && <><TextField form={form} update={update} name="foreignOwnerCountry" label="Country / jurisdiction" /><TextField form={form} update={update} name="foreignPassportNumber" label="Passport number" /></>}
      {type === 'deceased_estate' && <><TextField form={form} update={update} name="deceasedEstateName" label="Estate name" /><TextField form={form} update={update} name="executorName" label="Executor name" /><TextField form={form} update={update} name="executorsText" label="Executors / representatives" multiline /></>}
      {['company', 'close_corporation', 'other'].includes(type) && <TextField form={form} update={update} name="companyDirectorsText" label="Directors / authorised representatives" multiline />}
      {type === 'trust' && <TextField form={form} update={update} name="trusteesText" label="Trustees" multiline />}
      <SelectField form={form} update={update} name="maritalStatus" label="Marital status" options={maritalStatuses.map((row) => [row.value, row.label])} />
      {['married_cop', 'married_anc'].includes(form.maritalStatus) && <><TextField form={form} update={update} name="spouseName" label="Spouse name" /><TextField form={form} update={update} name="spouseEmail" label="Spouse email" type="email" /><TextField form={form} update={update} name="spousePhone" label="Spouse phone" type="tel" /></>}
    </div></details>
    <details className="mobile-listing-more-fields"><summary>Mandate terms & commission</summary><div><SelectField form={form} update={update} name="mandateType" label="Mandate type" options={mandateTypes.map((row) => [row.value, row.label])} /><TextField form={form} update={update} name="mandateStartDate" label="Mandate start date" type="date" /><TextField form={form} update={update} name="mandateEndDate" label="Mandate end date" type="date" /><SelectField form={form} update={update} name="commissionType" label="Commission type" options={[[ 'percentage', 'Percentage' ], [ 'fixed', 'Fixed amount' ]]} /><TextField form={form} update={update} name="commissionValue" label={form.commissionType === 'fixed' ? 'Commission amount (R)' : 'Commission (%)'} type="number" /><TextField form={form} update={update} name="coAgents" label="Co-agents" /></div></details>
    <details className="mobile-listing-more-fields"><summary>Seller documents & capture</summary><div>
      {[['hasSignedPropertyConditionDisclosure', 'Signed property condition disclosure'], ['hasSignedFicaForm', 'Signed FICA form']].map(([key, label]) => <label key={key} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={Boolean(form[key])} onChange={(event) => update(key, event.target.checked)} />{label}</label>)}
      <SelectField form={form} update={update} name="complianceCaptureMethod" label="Capture route" options={complianceMethods.map((row) => [row.value, row.label])} />
      {[['hasSignedMandate', 'mandateCaptureSource', 'Mandate received via'], ['hasSignedPropertyConditionDisclosure', 'disclosureCaptureSource', 'Disclosure received via'], ['hasSignedFicaForm', 'ficaCaptureSource', 'FICA received via']].map(([flag, name, label]) => form[flag] && <SelectField key={name} form={form} update={update} name={name} label={label} options={captureSources.map((row) => [row.value, row.label])} />)}
      <TextField form={form} update={update} name="complianceCaptureNotes" label="Capture note" multiline />
    </div></details>
    <details className="mobile-listing-more-fields"><summary>Seller access & source</summary><div><SelectField form={form} update={(name, value) => { update(name, value); update('sellerPortalInviteRequested', value === 'send_now') }} name="sellerPortalAccessIntent" label="Seller portal access" options={[[ 'later', 'Decide later' ], [ 'agent_managed', 'Agent-managed' ], [ 'send_now', 'Send invite after saving' ]]} />{form.sellerPortalAccessIntent === 'agent_managed' && <TextField form={form} update={update} name="sellerPortalOptOutReason" label="Offline-management note" multiline />}<SelectField form={form} update={update} name="leadSource" label="Lead source" options={['Referral', 'Website', 'Property24', 'Private Property', 'Walk-In', 'Canvassing'].map((value) => [value, value])} /></div></details>
    <details className="mobile-listing-more-fields"><summary>Supporting documents</summary><div><SelectField form={form} update={update} name="supportingDocumentCategory" label="Document category" options={documentCategories.map((category) => [category, category])} /><label className="grid gap-2 text-xs text-[#627068]">Add documents<input type="file" multiple onChange={(event) => { const files = Array.from(event.target.files || []); update('supportingDocumentFiles', files); update('supportingDocumentNames', files.map((file) => file.name)) }} /></label><p className="text-xs text-[#627068]">{form.supportingDocumentNames?.length ? form.supportingDocumentNames.join(', ') : 'Files upload when you save the listing.'}</p></div></details>
  </>
}
export function MobileListingReviewFields({ form, update, onStatusChange }) {
  return <details className="mobile-listing-more-fields" open><summary>Listing settings</summary><div><SelectField form={form} update={(_, value) => onStatusChange(value)} name="listingStatus" label="Listing status" options={[...(!['draft', 'active', 'under_offer', 'sold'].includes(form.listingStatus) ? [[form.listingStatus, getPrivateListingStatusLabel(form.listingStatus)]] : []), [ 'draft', 'Draft' ], [ 'active', 'Active' ], [ 'under_offer', 'Under offer' ], [ 'sold', 'Sold' ]]} /><TextField form={form} update={update} name="externalListingLink" label="Existing listing link" type="url" /><TextField form={form} update={update} name="transferAttorney" label="Transfer attorney" /><TextField form={form} update={update} name="bondAttorney" label="Bond attorney" /><TextField form={form} update={update} name="bondOriginator" label="Bond originator" /><TextField form={form} update={update} name="notes" label="Internal notes" multiline /><p className="text-xs leading-6 text-[#627068]">Saving retains the existing mandate and readiness checks. Portal submission remains a separate action.</p></div></details>
}
