-- Rentals Phase 14: copy and references to existing Arch9 media storage.
begin;
create table if not exists public.rental_vacancy_marketing (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, vacancy_id uuid not null unique references public.rental_vacancies(id) on delete cascade, branch_id uuid references public.organisation_branches(id) on delete set null, title text, description text, features_json jsonb not null default '[]'::jsonb, visibility text not null default 'internal', created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint rental_vacancy_marketing_visibility_check check (visibility in ('internal', 'portal_ready')));
create table if not exists public.rental_vacancy_media (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, vacancy_id uuid not null references public.rental_vacancies(id) on delete cascade, branch_id uuid references public.organisation_branches(id) on delete set null, storage_bucket text not null, storage_path text not null, media_type text not null default 'image', alt_text text, sort_order integer not null default 0, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), constraint rental_vacancy_media_type_check check (media_type in ('image', 'floorplan', 'video')), constraint rental_vacancy_media_path_unique unique(vacancy_id, storage_bucket, storage_path));
create index if not exists rental_vacancy_media_vacancy_idx on public.rental_vacancy_media(vacancy_id, sort_order);
create or replace function public.rental_vacancy_marketing_validate_scope() returns trigger language plpgsql security invoker set search_path = '' as $$ declare vacancy_org uuid; vacancy_branch uuid; begin select organisation_id, branch_id into vacancy_org, vacancy_branch from public.rental_vacancies where id = new.vacancy_id; if vacancy_org is null or vacancy_org <> new.organisation_id then raise exception 'Rental marketing must match vacancy organisation'; end if; if new.branch_id is null then new.branch_id := vacancy_branch; end if; if vacancy_branch is not null and new.branch_id is distinct from vacancy_branch then raise exception 'Rental marketing branch must match vacancy'; end if; return new; end; $$;
create trigger trg_rental_vacancy_marketing_scope before insert or update on public.rental_vacancy_marketing for each row execute function public.rental_vacancy_marketing_validate_scope();
create trigger trg_rental_vacancy_media_scope before insert or update on public.rental_vacancy_media for each row execute function public.rental_vacancy_marketing_validate_scope();
create trigger trg_rental_vacancy_marketing_updated_at before update on public.rental_vacancy_marketing for each row execute function public.rental_set_updated_at();
alter table public.rental_vacancy_marketing enable row level security; alter table public.rental_vacancy_media enable row level security; revoke all on public.rental_vacancy_marketing, public.rental_vacancy_media from anon, authenticated; grant select, insert, update on public.rental_vacancy_marketing, public.rental_vacancy_media to authenticated;
create policy rental_vacancy_marketing_scoped on public.rental_vacancy_marketing for all to authenticated using (exists (select 1 from public.rental_vacancies v join public.rental_properties p on p.id=v.property_id where v.id=vacancy_id and public.rental_branch_access(p.organisation_id,p.branch_id))) with check (exists (select 1 from public.rental_vacancies v join public.rental_properties p on p.id=v.property_id where v.id=vacancy_id and public.rental_branch_access(p.organisation_id,p.branch_id)));
create policy rental_vacancy_media_scoped on public.rental_vacancy_media for all to authenticated using (exists (select 1 from public.rental_vacancies v join public.rental_properties p on p.id=v.property_id where v.id=vacancy_id and public.rental_branch_access(p.organisation_id,p.branch_id))) with check (exists (select 1 from public.rental_vacancies v join public.rental_properties p on p.id=v.property_id where v.id=vacancy_id and public.rental_branch_access(p.organisation_id,p.branch_id)));
commit;
