function withDefaultReminders({ includeDocsReminder = false, includeDueReminder = true } = {}) {
  const base = [
    { type: 'before_start', offsetMinutes: 24 * 60, reminderType: 'appointment_reminder_24h' },
    { type: 'before_start', offsetMinutes: 2 * 60, reminderType: 'appointment_reminder_2h' },
  ]

  if (includeDueReminder) {
    base.push({ type: 'at_start', offsetMinutes: 0, reminderType: 'appointment_reminder_due' })
  }

  if (includeDocsReminder) {
    base.push({ type: 'documents_missing', offsetMinutes: 24 * 60, reminderType: 'appointment_documents_required' })
  }

  return base
}

function doc(key, label, description = '') {
  return { key, label, description }
}

export const APPOINTMENT_TYPE_TEMPLATES = {
  viewing: {
    type: 'viewing',
    label: 'Viewing',
    description: 'Client property viewing appointment.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 15,
    requiredParticipantRoles: ['agent', 'buyer'],
    optionalParticipantRoles: ['seller', 'developer_representative'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'buyer_transaction',
    linkedWorkflowStage: 'viewing',
    requiredBeforeAppointment: [],
    clientInstructions: 'Please arrive 10 minutes early and bring identification if requested.',
    internalInstructions: 'Confirm property access and parking details before the slot.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['record_viewing_outcome'],
    allowedRescheduleRoles: ['buyer', 'seller', 'agent', 'attorney', 'bond_originator', 'developer_representative'],
    calendarTitle: 'Bridge: Viewing Appointment',
    calendarDescription: 'This appointment is for viewing the property and discussing next steps.',
  },
  seller_consultation: {
    type: 'seller_consultation',
    label: 'Seller Consultation',
    description: 'Seller-side property consultation.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 15,
    requiredParticipantRoles: ['seller', 'agent'],
    optionalParticipantRoles: ['developer_representative', 'attorney'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'seller_listing',
    linkedWorkflowStage: 'seller_consultation',
    requiredBeforeAppointment: [doc('seller_property_details', 'Property details')],
    clientInstructions: 'Please have your property ownership details and key listing preferences ready.',
    internalInstructions: 'Capture mandate readiness blockers and ownership context.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['capture_seller_consultation_outcome'],
    allowedRescheduleRoles: ['seller', 'agent', 'attorney', 'developer_representative'],
    calendarTitle: 'Bridge: Seller Consultation',
    calendarDescription: 'This consultation aligns your listing process and next steps.',
  },
  buyer_consultation: {
    type: 'buyer_consultation',
    label: 'Buyer Consultation',
    description: 'Buyer-side transaction consultation.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 15,
    requiredParticipantRoles: ['buyer', 'agent'],
    optionalParticipantRoles: ['bond_originator'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'buyer_transaction',
    linkedWorkflowStage: 'buyer_consultation',
    requiredBeforeAppointment: [],
    clientInstructions: 'Bring your property preferences and any finance questions for the meeting.',
    internalInstructions: 'Confirm buyer onboarding readiness and finance path.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['capture_buyer_consultation_outcome'],
    allowedRescheduleRoles: ['buyer', 'agent', 'bond_originator'],
    calendarTitle: 'Bridge: Buyer Consultation',
    calendarDescription: 'This consultation confirms your purchase path and requirements.',
  },
  mandate_signing: {
    type: 'mandate_signing',
    label: 'Mandate Signing',
    description: 'Seller mandate signing appointment.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 20,
    requiredParticipantRoles: ['seller', 'agent'],
    optionalParticipantRoles: ['attorney'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'seller_listing',
    linkedWorkflowStage: 'mandate_signature',
    requiredBeforeAppointment: [doc('signed_mandate', 'Mandate pack')],
    clientInstructions: 'This appointment is for reviewing and signing your listing mandate.',
    internalInstructions: 'Confirm commission, duration, and authority details are final before signing.',
    reminderRules: withDefaultReminders({ includeDocsReminder: true }),
    completionEffects: ['mark_mandate_signature_complete'],
    allowedRescheduleRoles: ['seller', 'agent', 'attorney'],
    calendarTitle: 'Bridge: Mandate Signing Appointment',
    calendarDescription: 'This appointment is for reviewing and signing the seller mandate.',
  },
  otp_signing: {
    type: 'otp_signing',
    label: 'OTP Signing',
    description: 'Offer to Purchase signing appointment.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 15,
    requiredParticipantRoles: ['buyer', 'agent_or_attorney'],
    optionalParticipantRoles: ['agent', 'attorney', 'seller'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'buyer_transaction',
    linkedWorkflowStage: 'otp_signing',
    requiredBeforeAppointment: [
      doc('buyer_id_document', 'Buyer ID document', 'Required to verify identity before signing.'),
      doc('proof_of_address', 'Proof of address', 'Required for FICA verification.'),
    ],
    clientInstructions: 'This appointment is for reviewing and signing your Offer to Purchase. Please upload your ID document and proof of address before the appointment.',
    internalInstructions: 'Confirm OTP pack is prepared and signer identity is verified.',
    reminderRules: withDefaultReminders({ includeDocsReminder: true }),
    completionEffects: ['mark_otp_signing_appointment_completed', 'update_workflow_step_otp_signing', 'create_client_activity_event'],
    allowedRescheduleRoles: ['buyer', 'seller', 'agent', 'attorney', 'bond_originator'],
    calendarTitle: 'Bridge: OTP Signing Appointment',
    calendarDescription: 'This appointment is for signing the Offer to Purchase for your transaction.',
  },
  transfer_signing: {
    type: 'transfer_signing',
    label: 'Transfer Signing',
    description: 'Transfer document signing appointment.',
    defaultDurationMinutes: 60,
    defaultBufferMinutes: 30,
    requiredParticipantRoles: ['buyer_or_seller', 'attorney'],
    optionalParticipantRoles: ['agent', 'bond_originator'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'transfer_workflow',
    linkedWorkflowStage: 'transfer_document_signing',
    requiredBeforeAppointment: [
      doc('id_document', 'ID document'),
      doc('proof_of_address', 'Proof of address'),
      doc('transfer_documents_prepared', 'Transfer documents prepared'),
    ],
    clientInstructions: 'This appointment is for signing your transfer documents with the attorneys.',
    internalInstructions: 'Ensure transfer pack is fully prepared and signer sequence is confirmed.',
    reminderRules: withDefaultReminders({ includeDocsReminder: true }),
    completionEffects: ['mark_transfer_signing_step_completed', 'create_transfer_progress_update', 'unlock_next_transfer_step'],
    allowedRescheduleRoles: ['buyer', 'seller', 'attorney', 'agent', 'developer_representative'],
    calendarTitle: 'Bridge: Transfer Signing Appointment',
    calendarDescription: 'This appointment is part of your transfer process and covers transfer document signing.',
  },
  bond_signing: {
    type: 'bond_signing',
    label: 'Bond Signing',
    description: 'Bond registration signing appointment.',
    defaultDurationMinutes: 60,
    defaultBufferMinutes: 30,
    requiredParticipantRoles: ['buyer', 'bond_attorney'],
    optionalParticipantRoles: ['bond_originator', 'agent'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'bond_workflow',
    linkedWorkflowStage: 'bond_document_signing',
    requiredBeforeAppointment: [
      doc('grant_documents_prepared', 'Grant documents prepared'),
      doc('buyer_fica_complete', 'Buyer FICA complete'),
    ],
    clientInstructions: 'This appointment is for signing the bond documents required by the bank.',
    internalInstructions: 'Confirm grant docs and signing authority before the session.',
    reminderRules: withDefaultReminders({ includeDocsReminder: true }),
    completionEffects: ['mark_bond_signing_step_completed', 'update_bond_workflow', 'create_client_activity_event'],
    allowedRescheduleRoles: ['buyer', 'bond_attorney', 'bond_originator', 'agent'],
    calendarTitle: 'Bridge: Bond Signing Appointment',
    calendarDescription: 'This appointment covers signing your bond documents for bank registration.',
  },
  finance_consultation: {
    type: 'finance_consultation',
    label: 'Bond Consultation',
    description: 'Finance and lending consultation appointment.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 20,
    requiredParticipantRoles: ['buyer', 'bond_originator'],
    optionalParticipantRoles: ['agent'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'finance_workflow',
    linkedWorkflowStage: 'bond_application_review',
    requiredBeforeAppointment: [
      doc('bank_statements', 'Latest bank statements'),
      doc('proof_of_income', 'Proof of income'),
    ],
    clientInstructions: 'Please ensure your latest bank statements and proof of income are uploaded before the meeting.',
    internalInstructions: 'Check finance application completeness and lender path.',
    reminderRules: withDefaultReminders({ includeDocsReminder: true }),
    completionEffects: ['capture_finance_consultation_outcome'],
    allowedRescheduleRoles: ['buyer', 'bond_originator', 'agent'],
    calendarTitle: 'Bridge: Finance Consultation',
    calendarDescription: 'This appointment reviews your finance readiness and application process.',
  },
  attorney_consultation: {
    type: 'attorney_consultation',
    label: 'Attorney Consultation',
    description: 'Attorney legal consultation appointment.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 20,
    requiredParticipantRoles: ['attorney', 'buyer_or_seller'],
    optionalParticipantRoles: ['agent', 'bond_originator'],
    defaultVisibility: 'shared_role_players',
    linkedWorkflow: 'transfer_workflow',
    linkedWorkflowStage: 'attorney_preparation',
    requiredBeforeAppointment: [],
    clientInstructions: 'This consultation covers legal process questions and transfer readiness.',
    internalInstructions: 'Prepare transfer checklist and outstanding compliance issues.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['capture_attorney_consultation_outcome'],
    allowedRescheduleRoles: ['buyer', 'seller', 'attorney', 'agent'],
    calendarTitle: 'Bridge: Attorney Consultation',
    calendarDescription: 'This consultation helps align the legal transfer process and next steps.',
  },
  handover: {
    type: 'handover',
    label: 'Handover',
    description: 'Property handover inspection and acceptance appointment.',
    defaultDurationMinutes: 90,
    defaultBufferMinutes: 60,
    requiredParticipantRoles: ['buyer', 'developer_representative_or_agent'],
    optionalParticipantRoles: ['seller'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'handover_workflow',
    linkedWorkflowStage: 'handover_inspection',
    requiredBeforeAppointment: [
      doc('registration_complete_or_handover_approved', 'Registration complete / handover approved'),
      doc('handover_checklist_ready', 'Handover checklist ready'),
    ],
    clientInstructions: 'This appointment is for inspecting the property and recording any handover notes or snags.',
    internalInstructions: 'Have snag checklist and acceptance workflow ready for capture.',
    reminderRules: withDefaultReminders({ includeDocsReminder: true }),
    completionEffects: ['mark_handover_appointment_completed', 'open_snag_workflow_if_applicable', 'create_client_activity_event'],
    allowedRescheduleRoles: ['buyer', 'seller', 'agent', 'developer_representative'],
    calendarTitle: 'Bridge: Handover Appointment',
    calendarDescription: 'This appointment is for property handover and snag capture.',
  },
  snag_inspection: {
    type: 'snag_inspection',
    label: 'Snag Inspection',
    description: 'Snag and defect inspection appointment.',
    defaultDurationMinutes: 60,
    defaultBufferMinutes: 30,
    requiredParticipantRoles: ['buyer', 'developer_representative'],
    optionalParticipantRoles: ['agent', 'seller'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'handover_workflow',
    linkedWorkflowStage: 'snag_inspection',
    requiredBeforeAppointment: [doc('snag_checklist', 'Snag checklist')],
    clientInstructions: 'Use this session to identify and log all snags or defects for resolution.',
    internalInstructions: 'Capture snag severity and assign remediation owners.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['mark_snag_inspection_complete', 'create_client_activity_event'],
    allowedRescheduleRoles: ['buyer', 'developer_representative', 'agent'],
    calendarTitle: 'Bridge: Snag Inspection',
    calendarDescription: 'This appointment captures snag/defect issues before final acceptance.',
  },
  internal_meeting: {
    type: 'internal_meeting',
    label: 'Internal Meeting',
    description: 'Internal transaction coordination meeting.',
    defaultDurationMinutes: 30,
    defaultBufferMinutes: 10,
    requiredParticipantRoles: ['internal_staff'],
    optionalParticipantRoles: ['agent', 'attorney', 'bond_originator'],
    defaultVisibility: 'internal_only',
    linkedWorkflow: 'internal_operations',
    linkedWorkflowStage: 'coordination',
    requiredBeforeAppointment: [],
    clientInstructions: '',
    internalInstructions: 'Internal planning and execution session.',
    reminderRules: [
      { type: 'before_start', offsetMinutes: 2 * 60, reminderType: 'appointment_reminder_2h' },
      { type: 'at_start', offsetMinutes: 0, reminderType: 'appointment_reminder_due' },
    ],
    completionEffects: ['record_internal_meeting_outcome'],
    allowedRescheduleRoles: ['agent', 'attorney', 'bond_originator', 'developer_representative', 'internal_staff'],
    calendarTitle: 'Bridge: Internal Coordination Meeting',
    calendarDescription: 'Internal operational coordination meeting.',
  },
  client_meeting: {
    type: 'client_meeting',
    label: 'Client Meeting',
    description: 'General client meeting linked to a lead, client, or transaction.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 15,
    requiredParticipantRoles: ['client', 'agent'],
    optionalParticipantRoles: ['attorney', 'bond_originator'],
    defaultVisibility: 'client_visible',
    linkedWorkflow: 'client_workflow',
    linkedWorkflowStage: 'client_meeting',
    requiredBeforeAppointment: [],
    clientInstructions: 'Please review the meeting details and confirm whether the time works for you.',
    internalInstructions: 'Confirm the meeting purpose, participants, and next action before the session.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['record_client_meeting_outcome'],
    allowedRescheduleRoles: ['buyer', 'seller', 'client', 'agent', 'attorney', 'bond_originator'],
    calendarTitle: 'Bridge: Client Meeting',
    calendarDescription: 'This meeting keeps the transaction or client workflow aligned.',
  },
  other: {
    type: 'other',
    label: 'Other',
    description: 'Custom appointment type.',
    defaultDurationMinutes: 45,
    defaultBufferMinutes: 15,
    requiredParticipantRoles: ['agent'],
    optionalParticipantRoles: ['buyer', 'seller', 'client', 'attorney', 'bond_originator', 'developer_representative'],
    defaultVisibility: 'shared_role_players',
    linkedWorkflow: 'general_workflow',
    linkedWorkflowStage: 'appointment',
    requiredBeforeAppointment: [],
    clientInstructions: 'Please review the appointment details and confirm whether the time works for you.',
    internalInstructions: 'Confirm participants, location, and objective before the meeting.',
    reminderRules: withDefaultReminders({ includeDocsReminder: false }),
    completionEffects: ['record_outcome'],
    allowedRescheduleRoles: ['buyer', 'seller', 'client', 'agent', 'attorney', 'bond_originator', 'developer_representative'],
    calendarTitle: 'Bridge: Appointment',
    calendarDescription: 'This appointment is part of your Bridge workflow.',
  },
}

export const APPOINTMENT_TEMPLATE_ALIASES = {
  viewing: 'viewing',
  seller_valuation: 'seller_consultation',
  mandate_discussion: 'mandate_signing',
  buyer_meeting: 'buyer_consultation',
  follow_up_meeting: 'buyer_consultation',
  otp_offer_discussion: 'otp_signing',
  signing_appointment: 'transfer_signing',
  property_inspection: 'snag_inspection',
  inspection: 'snag_inspection',
  bond_consultation: 'finance_consultation',
  client_meeting: 'client_meeting',
  general_meeting: 'internal_meeting',
  other: 'other',
}

export const GENERIC_APPOINTMENT_TEMPLATE = {
  type: 'internal_meeting',
  label: 'Appointment',
  description: 'General appointment.',
  defaultDurationMinutes: 45,
  defaultBufferMinutes: 15,
  requiredParticipantRoles: ['agent'],
  optionalParticipantRoles: [],
  defaultVisibility: 'shared_role_players',
  linkedWorkflow: 'general_workflow',
  linkedWorkflowStage: 'appointment',
  requiredBeforeAppointment: [],
  clientInstructions: 'Please confirm your attendance and review the appointment details.',
  internalInstructions: 'Confirm participants, location, and objective before the meeting.',
  reminderRules: withDefaultReminders({ includeDocsReminder: false }),
  completionEffects: ['record_outcome'],
  allowedRescheduleRoles: ['buyer', 'seller', 'agent', 'attorney', 'bond_originator', 'developer_representative'],
  calendarTitle: 'Bridge: Appointment',
  calendarDescription: 'This appointment is part of your Bridge transaction process.',
}
