/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        app: 'var(--color-bg-app)',
        surface: 'var(--color-bg-surface)',
        surfaceAlt: 'var(--color-bg-surface-alt)',
        mutedBg: 'var(--color-bg-muted)',
        sidebar: 'var(--color-bg-sidebar)',
        sidebarAlt: 'var(--color-bg-sidebar-alt)',
        sidebarActive: 'var(--color-bg-sidebar-active)',
        textStrong: 'var(--color-text-strong)',
        textBody: 'var(--color-text-body)',
        textMuted: 'var(--color-text-muted)',
        textSoft: 'var(--color-text-soft)',
        textInverse: 'var(--color-text-inverse)',
        borderSoft: 'var(--color-border-soft)',
        borderDefault: 'var(--color-border-default)',
        borderStrong: 'var(--color-border-strong)',
        primary: 'var(--color-primary)',
        primaryHover: 'var(--color-primary-hover)',
        primarySoft: 'var(--color-primary-soft)',
        success: 'var(--color-success)',
        successSoft: 'var(--color-success-soft)',
        warning: 'var(--color-warning)',
        warningSoft: 'var(--color-warning-soft)',
        danger: 'var(--color-danger)',
        dangerSoft: 'var(--color-danger-soft)',
        info: 'var(--color-info)',
        infoSoft: 'var(--color-info-soft)',
        bridge: {
          bg: 'var(--color-bg-app)',
          surface: 'var(--color-bg-surface)',
          muted: 'var(--color-bg-muted)',
          border: 'var(--color-border-default)',
          borderStrong: 'var(--color-border-strong)',
          text: 'var(--color-text-strong)',
          subtle: 'var(--color-text-muted)',
          accent: 'var(--color-primary)',
          accentDeep: 'var(--color-primary-hover)',
          accentSoft: 'var(--color-primary-soft)',
          success: 'var(--color-success)',
          successSoft: 'var(--color-success-soft)',
          warning: 'var(--color-warning)',
          warningSoft: 'var(--color-warning-soft)',
          danger: 'var(--color-danger)',
          dangerSoft: 'var(--color-danger-soft)',
          info: 'var(--color-info)',
          infoSoft: 'var(--color-info-soft)',
          sidebar: 'var(--color-bg-sidebar)',
          sidebarSoft: 'var(--color-bg-sidebar-alt)',
          sidebarBorder: 'var(--color-bg-sidebar-active)',
        },
        marketing: {
          page: '#f6f3ee',
          pageWarm: '#f1ece6',
          panel: 'rgba(255, 253, 250, 0.82)',
          panelElevated: 'rgba(255, 251, 247, 0.94)',
          panelStrong: '#f3ede5',
          contrast: '#141414',
          ink: '#181716',
          muted: '#67615a',
          subtle: '#8a7f73',
          border: '#e6dfd7',
          borderStrong: '#d7cec4',
          accent: '#7a6243',
          accentSoft: '#f7f0e7',
          accentStrong: '#3b3228',
        },
      },
      fontFamily: {
        sans: ['Inter', 'SF Pro Text', 'SF Pro Display', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['1.75rem', { lineHeight: '1.15', letterSpacing: '-0.03em' }],
        'section-title': ['1.25rem', { lineHeight: '1.2', letterSpacing: '-0.022em' }],
        'card-title': ['1rem', { lineHeight: '1.3', letterSpacing: '-0.016em' }],
        body: ['0.9375rem', { lineHeight: '1.58', letterSpacing: '-0.004em' }],
        secondary: ['0.875rem', { lineHeight: '1.5', letterSpacing: '-0.003em' }],
        nav: ['0.875rem', { lineHeight: '1.35', letterSpacing: '-0.003em' }],
        label: ['0.75rem', { lineHeight: '1.34', letterSpacing: '0.085em' }],
        helper: ['0.75rem', { lineHeight: '1.34', letterSpacing: '-0.002em' }],
        table: ['0.875rem', { lineHeight: '1.42', letterSpacing: '-0.003em' }],
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        base: '1rem',
        lg: '1.25rem',
        section: '1.5rem',
        xl: '2rem',
        '2xl': '2.5rem',
      },
      boxShadow: {
        surface: 'var(--shadow-surface)',
        floating: 'var(--shadow-floating)',
        modal: 'var(--shadow-modal)',
        shell: 'var(--shadow-modal)',
        panel: 'var(--shadow-floating)',
        soft: 'var(--shadow-surface)',
        marketingShell: '0 44px 120px rgba(24, 23, 22, 0.12)',
        marketingPanel: '0 22px 55px rgba(24, 23, 22, 0.08)',
        marketingSoft: '0 10px 26px rgba(24, 23, 22, 0.05)',
        marketingFloat: '0 34px 90px rgba(24, 23, 22, 0.12)',
        marketingButton: '0 18px 34px rgba(20, 20, 20, 0.18)',
        marketingButtonHover: '0 24px 40px rgba(20, 20, 20, 0.24)',
      },
      borderRadius: {
        'surface-sm': 'var(--radius-surface-sm)',
        surface: 'var(--radius-surface)',
        'surface-lg': 'var(--radius-surface-lg)',
        'surface-xl': 'var(--radius-surface-xl)',
        panel: 'var(--radius-surface)',
        control: 'var(--radius-control)',
        modal: 'var(--radius-surface-xl)',
        marketing: '28px',
      },
      maxWidth: {
        shell: '1680px',
        marketing: '1280px',
      },
      letterSpacing: {
        premium: '-0.025em',
      },
    },
  },
  plugins: [],
}
