/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        app: 'var(--color-bg-app)',
        surface: 'var(--color-bg-surface)',
        surfaceAlt: 'var(--color-bg-surface-alt)',
        mutedBg: 'var(--color-bg-muted)',
        sidebar: 'var(--color-bg-sidebar)',
        sidebarAlt: 'var(--color-bg-sidebar-alt)',
        sidebarActive: 'var(--color-bg-sidebar-active)',
        textStrong: 'var(--color-text-strong)',
        textBody: 'var(--color-text-body)',
        textMuted: 'var(--color-text-muted)',
        textSoft: 'var(--color-text-soft)',
        textInverse: 'var(--color-text-inverse)',
        borderSoft: 'var(--color-border-soft)',
        borderDefault: 'var(--color-border-default)',
        borderStrong: 'var(--color-border-strong)',
        primary: 'var(--color-primary)',
        primaryHover: 'var(--color-primary-hover)',
        primarySoft: 'var(--color-primary-soft)',
        success: 'var(--color-success)',
        successSoft: 'var(--color-success-soft)',
        warning: 'var(--color-warning)',
        warningSoft: 'var(--color-warning-soft)',
        danger: 'var(--color-danger)',
        dangerSoft: 'var(--color-danger-soft)',
        info: 'var(--color-info)',
        infoSoft: 'var(--color-info-soft)',
        bridge: {
          bg: 'var(--color-bg-app)',
          surface: 'var(--color-bg-surface)',
          muted: 'var(--color-bg-muted)',
          border: 'var(--color-border-default)',
          borderStrong: 'var(--color-border-strong)',
          text: 'var(--color-text-strong)',
          subtle: 'var(--color-text-muted)',
          accent: 'var(--color-primary)',
          accentDeep: 'var(--color-primary-hover)',
          accentSoft: 'var(--color-primary-soft)',
          success: 'var(--color-success)',
          successSoft: 'var(--color-success-soft)',
          warning: 'var(--color-warning)',
          warningSoft: 'var(--color-warning-soft)',
          danger: 'var(--color-danger)',
          dangerSoft: 'var(--color-danger-soft)',
          info: 'var(--color-info)',
          infoSoft: 'var(--color-info-soft)',
          sidebar: 'var(--color-bg-sidebar)',
          sidebarSoft: 'var(--color-bg-sidebar-alt)',
          sidebarBorder: 'var(--color-bg-sidebar-active)',
        },
        marketing: {
          page: '#f6f3ee',
          pageWarm: '#f1ece6',
          panel: 'rgba(255, 253, 250, 0.82)',
          panelElevated: 'rgba(255, 251, 247, 0.94)',
          panelStrong: '#f3ede5',
          contrast: '#141414',
          ink: '#181716',
          muted: '#67615a',
          subtle: '#8a7f73',
          border: '#e6dfd7',
          borderStrong: '#d7cec4',
          accent: '#7a6243',
          accentSoft: '#f7f0e7',
          accentStrong: '#3b3228',
        },
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        shell: '0 18px 40px rgba(15, 23, 42, 0.08)',
        panel: '0 10px 24px rgba(15, 23, 42, 0.06)',
        soft: '0 4px 14px rgba(15, 23, 42, 0.05)',
        marketingShell: '0 44px 120px rgba(24, 23, 22, 0.12)',
        marketingPanel: '0 22px 55px rgba(24, 23, 22, 0.08)',
        marketingSoft: '0 10px 26px rgba(24, 23, 22, 0.05)',
        marketingFloat: '0 34px 90px rgba(24, 23, 22, 0.12)',
        marketingButton: '0 18px 34px rgba(20, 20, 20, 0.18)',
        marketingButtonHover: '0 24px 40px rgba(20, 20, 20, 0.24)',
      },
      borderRadius: {
        panel: '18px',
        control: '14px',
        marketing: '28px',
      },
      maxWidth: {
        shell: '1680px',
        marketing: '1280px',
      },
      letterSpacing: {
        premium: '-0.025em',
      },
    },
  },
  plugins: [],
}
