const issuedDate = '2026-02-12'
const submittedAt = '2026-02-13T09:15:00.000Z'

function basePortalSources(overrides = {}) {
  return {
    portalBuyer: {
      id: overrides.buyerId || 'buyer-phase0-001',
      name: overrides.buyerName || 'Jordan Mokoena',
      email: overrides.buyerEmail || 'jordan.mokoena@example.test',
      phone: overrides.buyerPhone || '+27820000001',
    },
    buyerOnboardingInformation: {
      formData: {
        first_name: overrides.firstName || 'Jordan',
        last_name: overrides.lastName || 'Mokoena',
        email: overrides.buyerEmail || 'jordan.mokoena@example.test',
        phone: overrides.buyerPhone || '+27820000001',
        street_address: '14 Sample Street',
        suburb: 'Rosebank',
        city: 'Johannesburg',
        postal_code: '2196',
        marital_status: overrides.maritalStatus || 'single',
        purchase_finance_type: 'bond',
        purchase_price: overrides.purchasePrice || '1850000',
        bond_amount: overrides.bondAmount || '1665000',
        deposit_amount: overrides.deposit || '185000',
        existing_onboarding_answer: 'preserve me',
      },
    },
    transactionInformation: {
      id: overrides.transactionId || 'transaction-phase0-001',
      purchase_price: Number(overrides.purchasePrice || 1850000),
      bond_amount: Number(overrides.bondAmount || 1665000),
      deposit_amount: Number(overrides.deposit || 185000),
      finance_type: 'bond',
      finance_managed_by: 'bond_originator',
      property_address_line_1: '14 Sample Street',
      status: 'awaiting_client_onboarding',
    },
    unitInformation: {
      id: overrides.unitId || 'unit-phase0-001',
      unit_number: overrides.unitNumber || 'A-104',
      price: Number(overrides.purchasePrice || 1850000),
      development: {
        name: overrides.developmentName || 'Sample Gardens',
      },
    },
    developmentInformation: {
      id: overrides.developmentId || 'development-phase0-001',
      name: overrides.developmentName || 'Sample Gardens',
    },
    selectedBanks: overrides.selectedBanks || ['ABSA', 'FNB'],
  }
}

function primaryApplicant(overrides = {}) {
  return {
    key: 'primary',
    label: 'Primary applicant',
    first_name: overrides.firstName || 'Jordan',
    surname: overrides.lastName || 'Mokoena',
    identity_number: overrides.identityNumber || '9001015000088',
    date_of_birth: overrides.dateOfBirth || '1990-01-01',
    marital_status: overrides.maritalStatus || 'single',
    email: overrides.email || 'jordan.mokoena@example.test',
    phone: overrides.phone || '+27820000001',
    number_of_dependants: overrides.dependants || '0',
    current_residential_status: overrides.residentialStatus || 'renting',
    first_time_home_buyer: overrides.firstTimeBuyer || 'yes',
    main_residence: 'yes',
  }
}

function baseBondApplication(overrides = {}) {
  const sources = basePortalSources(overrides)
  const primaryApplicantOverrides = {
    firstName: overrides.firstName,
    lastName: overrides.lastName,
    email: overrides.buyerEmail,
    phone: overrides.buyerPhone,
    maritalStatus: overrides.maritalStatus,
    ...(overrides.primaryApplicant || {}),
  }
  return {
    status: overrides.status || 'In Progress',
    submitted_at: overrides.submittedAt || '',
    selected_banks: sources.selectedBanks,
    applicants: [
      primaryApplicant(primaryApplicantOverrides),
      ...(overrides.coApplicant ? [overrides.coApplicant] : []),
    ],
    summary: {
      applicant_name: overrides.applicantName || sources.portalBuyer.name,
      has_co_applicant: overrides.coApplicant ? 'yes' : 'no',
      has_surety: 'no',
      property_reference: `${sources.developmentInformation.name} - Unit ${sources.unitInformation.unit_number}`,
      development_name: sources.developmentInformation.name,
      unit_reference: `Unit ${sources.unitInformation.unit_number}`,
      purchase_price: String(sources.transactionInformation.purchase_price),
      deposit_contribution: String(sources.transactionInformation.deposit_amount),
      finance_type: 'bond',
      marital_status: overrides.maritalStatus || 'single',
      main_residence: 'yes',
      first_time_home_buyer: overrides.firstTimeBuyer || 'yes',
    },
    personal_details: {
      primary: primaryApplicant(primaryApplicantOverrides),
      co_applicant: overrides.coApplicant || {},
    },
    contact_address: {
      cellphone_number: sources.portalBuyer.phone,
      email_address: sources.portalBuyer.email,
      residential_address_street: '14 Sample Street',
      residential_address_suburb: 'Rosebank',
      residential_address_city: 'Johannesburg',
      residential_address_country: 'South Africa',
      residential_address_postal_code: '2196',
      postal_same_as_residential: 'yes',
      legal_notice_delivery_method: 'email',
      future_legal_correspondence_same_as_postal: 'yes',
    },
    employment: overrides.employment || {
      primary: {
        occupation_status: 'permanent_employee',
        nature_of_occupation: 'Operations manager',
        employer_name: 'Sample Logistics (Pty) Ltd',
        employment_years: '4',
        employment_months: '3',
        works_in_south_africa: 'yes',
      },
      co_applicant: {},
    },
    credit_history: {
      currently_under_administration: 'no',
      ever_under_administration: 'no',
      judgments_taken: 'no',
      currently_under_debt_review: 'no',
      ever_declared_insolvent: 'no',
      adverse_credit_listings: 'no',
      credit_bureau_dispute: 'no',
      bound_by_surety_agreements: 'no',
    },
    loan_details: {
      erf_or_section_number: sources.unitInformation.unit_number,
      street_or_complex: 'Sample Gardens',
      suburb: 'Rosebank',
      amount_to_be_registered: String(sources.transactionInformation.bond_amount),
      debit_order_bank_name: 'FNB',
      debit_order_account_number: '62000000000',
      preferred_debit_order_date: '25',
    },
    income_deductions_expenses: overrides.incomeDeductionsExpenses || {
      primary: {
        gross_salary: '72000',
        average_commission: '0',
        rental_income: '0',
        other_income_value: '0',
        tax_paye: '15500',
        pension: '4200',
        medical_aid: '3200',
        rental_expense: '14500',
        water_electricity: '2200',
        groceries: '6500',
        transport: '3500',
        other_expenses_value: '1800',
      },
      co_applicant: {},
    },
    banking_liabilities: overrides.bankingLiabilities || {
      primary_bank_name: 'FNB',
      primary_account_type: 'cheque',
      primary_account_holder_name: sources.portalBuyer.name,
      primary_account_number: '62000000000',
      primary_balance_debit_credit: 'credit',
      primary_bank_first_consideration_consent: 'yes',
      other_finance_1_bank: 'WesBank',
      other_finance_1_account_type: 'vehicle_finance',
      other_finance_1_current_balance: '185000',
      other_finance_1_monthly_payment: '5200',
      other_finance_1_settled: 'no',
    },
    assets_liabilities: overrides.assetsLiabilities || {
      fixed_property: '0',
      vehicles: '240000',
      investments: '125000',
      furniture_and_fittings: '90000',
      liabilities_total: '185000',
      other_liabilities_value: '',
      total_assets: '455000',
      total_liabilities: '185000',
      net_asset_value: '270000',
    },
    declarations_consents: {
      loan_processing_consent: true,
      credit_bureau_fraud_bank_data_consent: true,
      insurance_third_party_communication_consent: true,
      nhfc_first_home_finance_consent: false,
      marketing_privacy_preference: 'no',
      declaration_accepted: true,
      digital_signature_name: sources.portalBuyer.name,
      digital_signature_date: issuedDate,
    },
    consent: {
      credit_check_consent: true,
      declaration_accepted: true,
    },
    offers: overrides.offers || {
      accepted_offer_document_id: '',
      accepted_bank: '',
      accepted_at: '',
      decision_state: '',
    },
  }
}

function fixtureFrom({ key, description, overrides = {} }) {
  const sources = basePortalSources(overrides)
  const bondApplication = baseBondApplication(overrides)
  const formData = {
    ...sources.buyerOnboardingInformation.formData,
    bond_application: bondApplication,
  }

  return {
    key,
    description,
    sources: {
      portalBuyer: sources.portalBuyer,
      buyerOnboardingInformation: sources.buyerOnboardingInformation,
      transactionInformation: sources.transactionInformation,
      unitInformation: sources.unitInformation,
      developmentInformation: sources.developmentInformation,
      existingBondApplication: bondApplication,
      selectedBanks: sources.selectedBanks,
    },
    portal: {
      buyer: sources.portalBuyer,
      transaction: sources.transactionInformation,
      unit: sources.unitInformation,
      development: sources.developmentInformation,
      onboardingFormData: {
        formData,
      },
    },
  }
}

const coApplicant = {
  key: 'co_applicant',
  label: 'Co-applicant',
  first_name: 'Priya',
  surname: 'Naidoo',
  identity_number: '9202020055081',
  date_of_birth: '1992-02-02',
  marital_status: 'married',
  email: 'priya.naidoo@example.test',
  phone: '+27820000002',
  number_of_dependants: '1',
  current_residential_status: 'owner',
  first_time_home_buyer: 'no',
  main_residence: 'yes',
}

export const legacyBondApplicationFixtures = {
  solePermanentEmployee: fixtureFrom({
    key: 'sole-permanent-employee',
    description: 'Sole applicant with permanent employment, standard income and selected banks.',
  }),
  soleSelfEmployed: fixtureFrom({
    key: 'sole-self-employed',
    description: 'Sole applicant with self-employed income and business bank account fields.',
    overrides: {
      buyerId: 'buyer-phase0-002',
      buyerName: 'Sam Jacobs',
      firstName: 'Sam',
      lastName: 'Jacobs',
      buyerEmail: 'sam.jacobs@example.test',
      buyerPhone: '+27820000003',
      transactionId: 'transaction-phase0-002',
      unitNumber: 'B-209',
      purchasePrice: '2450000',
      bondAmount: '2205000',
      deposit: '245000',
      employment: {
        primary: {
          occupation_status: 'self_employed',
          nature_of_occupation: 'Architecture consultant',
          employer_name: 'Sample Studio CC',
          company_registration_number: '2020/000001/23',
          employment_years: '6',
          employment_months: '0',
          works_in_south_africa: 'yes',
          own_business_income_percent: '100',
          shareholder_in_employer_business: 'yes',
          shareholding_percent: '100',
        },
        co_applicant: {},
      },
      incomeDeductionsExpenses: {
        primary: {
          gross_salary: '98000',
          investment_income: '2500',
          rental_income: '0',
          other_income_description: 'Consulting retainers',
          other_income_value: '12000',
          tax_paye: '21000',
          pension: '0',
          medical_aid: '4100',
          rental_expense: '18500',
          water_electricity: '3100',
          groceries: '8200',
          transport: '4800',
          other_expenses_value: '2700',
        },
        co_applicant: {},
      },
      bankingLiabilities: {
        primary_bank_name: 'Standard Bank',
        primary_account_type: 'business_cheque',
        primary_account_holder_name: 'Sample Studio CC',
        business_bank_account: 'yes',
        primary_account_number: '03000000000',
        primary_balance_debit_credit: 'credit',
        primary_bank_first_consideration_consent: 'yes',
        other_finance_1_bank: '',
        other_finance_1_current_balance: '',
        other_finance_1_monthly_payment: '',
      },
    },
  }),
  jointApplication: fixtureFrom({
    key: 'joint-application',
    description: 'Primary applicant plus co-applicant fields in the current applicants array.',
    overrides: {
      buyerId: 'buyer-phase0-003',
      buyerName: 'Thabo Dlamini',
      firstName: 'Thabo',
      lastName: 'Dlamini',
      buyerEmail: 'thabo.dlamini@example.test',
      buyerPhone: '+27820000004',
      maritalStatus: 'married',
      coApplicant,
      applicantName: 'Thabo Dlamini',
      selectedBanks: ['Nedbank', 'Standard Bank'],
      employment: {
        primary: {
          occupation_status: 'permanent_employee',
          nature_of_occupation: 'Financial analyst',
          employer_name: 'Sample Advisory Ltd',
          employment_years: '5',
          employment_months: '7',
          works_in_south_africa: 'yes',
        },
        co_applicant: {
          occupation_status: 'contract_employee',
          nature_of_occupation: 'Project coordinator',
          employer_name: 'Example Projects',
          employment_years: '2',
          employment_months: '4',
          works_in_south_africa: 'yes',
        },
      },
      incomeDeductionsExpenses: {
        primary: {
          gross_salary: '68000',
          tax_paye: '14200',
          medical_aid: '2900',
          groceries: '7000',
          transport: '3900',
        },
        co_applicant: {
          gross_salary: '52000',
          tax_paye: '9800',
          medical_aid: '2100',
          groceries: '5000',
          transport: '2600',
        },
      },
    },
  }),
  financialCommitments: fixtureFrom({
    key: 'financial-commitments',
    description: 'Applicant with bank accounts, debts, assets and existing financial commitments.',
    overrides: {
      buyerId: 'buyer-phase0-004',
      buyerName: 'Lerato Nkosi',
      firstName: 'Lerato',
      lastName: 'Nkosi',
      buyerEmail: 'lerato.nkosi@example.test',
      buyerPhone: '+27820000005',
      transactionId: 'transaction-phase0-004',
      status: 'Submitted',
      submittedAt,
      selectedBanks: ['ABSA', 'Nedbank', 'Other'],
      bankingLiabilities: {
        primary_bank_name: 'ABSA',
        primary_account_type: 'cheque',
        primary_account_holder_name: 'Lerato Nkosi',
        primary_account_number: '40700000000',
        primary_balance_debit_credit: 'debit',
        primary_bank_first_consideration_consent: 'yes',
        home_loan_1_bank: 'FNB',
        home_loan_1_account_holder_name: 'Lerato Nkosi',
        home_loan_1_account_number: '55000000000',
        home_loan_1_outstanding_balance: '820000',
        home_loan_1_monthly_instalment: '9200',
        home_loan_1_selling_property: 'no',
        other_finance_1_bank: 'Toyota Financial Services',
        other_finance_1_account_type: 'vehicle_finance',
        other_finance_1_current_balance: '215000',
        other_finance_1_monthly_payment: '6100',
        other_finance_1_settled: 'no',
        retail_account_name: 'Sample Retail Card',
        retail_current_balance: '18500',
        retail_monthly_payment: '1350',
        retail_settled: 'no',
      },
      assetsLiabilities: {
        fixed_property: '1250000',
        vehicles: '320000',
        investments: '210000',
        furniture_and_fittings: '150000',
        other_assets_description: 'Unit trust portfolio',
        other_assets_value: '90000',
        liabilities_total: '1053500',
        other_liabilities_description: 'Retail account and vehicle finance',
        other_liabilities_value: '233500',
        total_assets: '2020000',
        total_liabilities: '1053500',
        net_asset_value: '966500',
      },
    },
  }),
}

export default legacyBondApplicationFixtures
