import { CONVEYANCER_PRACTICE_OPERATIONS_VERSION } from './conveyancerPracticeOperationsContract.js'
import { CONVEYANCER_INFORMATION_GOVERNANCE_VERSION } from './conveyancerInformationGovernance.js'
import { CONVEYANCER_MANUAL_EVIDENCE_VERSION } from './conveyancerManualEvidenceRegister.js'
import { CONVEYANCER_CLIENT_RISK_COMPLIANCE_VERSION } from './conveyancerClientRiskCompliance.js'
import { CONVEYANCER_TRUST_MONEY_CONTROLS_VERSION } from './conveyancerTrustMoneyControls.js'
import { CONVEYANCER_MATTER_CORRESPONDENCE_VERSION } from './conveyancerMatterCorrespondenceRegister.js'
import { CONVEYANCER_FIRM_OPERATIONS_VERSION } from './conveyancerFirmOperationsConfiguration.js'
import { CONVEYANCER_EXTERNAL_PORTAL_VERSION } from './conveyancerExternalPortal.js'
import { CONVEYANCER_MATTER_CLOSEOUT_RECOVERY_VERSION } from './conveyancerMatterCloseoutRecovery.js'

export const CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION = 'conveyancer_practice_assurance_g10_v1'
export const PRACTICE_ASSURANCE_G10_PHASES = Object.freeze({ G1:'G1',G2:'G2',G3:'G3',G4:'G4',G5:'G5',G6:'G6',G7:'G7',G8:'G8',G9:'G9' })
export const PRACTICE_ASSURANCE_G10_PHASE_VERSIONS = Object.freeze({G1:CONVEYANCER_PRACTICE_OPERATIONS_VERSION,G2:CONVEYANCER_INFORMATION_GOVERNANCE_VERSION,G3:CONVEYANCER_MANUAL_EVIDENCE_VERSION,G4:CONVEYANCER_CLIENT_RISK_COMPLIANCE_VERSION,G5:CONVEYANCER_TRUST_MONEY_CONTROLS_VERSION,G6:CONVEYANCER_MATTER_CORRESPONDENCE_VERSION,G7:CONVEYANCER_FIRM_OPERATIONS_VERSION,G8:CONVEYANCER_EXTERNAL_PORTAL_VERSION,G9:CONVEYANCER_MATTER_CLOSEOUT_RECOVERY_VERSION})
export const PRACTICE_ASSURANCE_G10_MINIMUM_SCENARIOS = Object.freeze({G1:9,G2:9,G3:12,G4:13,G5:14,G6:14,G7:16,G8:13,G9:22})
export const PRACTICE_ASSURANCE_G10_PROBES = Object.freeze(['contractAndVersion','matterFirmPolicyBinding','accessAndEthicalWalls','manualEvidence','ficaScenarios','trustPaymentControls','correspondencePrivacy','portalIsolation','migrationReconciliation','recoveryAndRollback','tamperDetection','sideEffectBoundary'])
export const PRACTICE_ASSURANCE_G10_SCENARIOS = Object.freeze(['individual_cash_purchaser','financed_purchase','existing_bond_cancellation','company_party','trust_party','enhanced_due_diligence','third_party_payment','changed_beneficiary_bank_details','restricted_privileged_matter','attorney_replacement','imported_historical_matter','failed_provider_manual_fallback','closed_matter_reopening'])
export const PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES = Object.freeze(['compliance','legal','trust','privacy','operations'])
export const PRACTICE_ASSURANCE_G10_BOUNDARY = Object.freeze({readOnly:true,databaseWritesPerformed:false,workflowMutated:false,portalAccessGranted:false,evidenceApproved:false,complianceDecisionMade:false,trustPaymentExecuted:false,correspondenceSent:false,importExecuted:false,webhookReplayed:false,databaseRestored:false,rollbackExecuted:false,deploymentPerformed:false,notificationSent:false})
export const PRACTICE_ASSURANCE_G10_THRESHOLDS = Object.freeze({minimumScenarioPassRate:1,maximumCriticalFindings:0,maximumAuthorityViolations:0,maximumAccessIncidents:0,maximumFicaFailures:0,maximumTrustControlBreaches:0,maximumPrivacyIncidents:0,maximumEvidenceIntegrityFailures:0,maximumMigrationImbalances:0,maximumRecoveryFailures:0,maximumSideEffectAttempts:0,observeManualBacklogRate:0.05,maximumManualBacklogRate:0.15})

const PHASES=Object.values(PRACTICE_ASSURANCE_G10_PHASES);const HASH=/^(sha256:)?[a-f0-9]{64}$/i;const FP=/^fnv1a_[a-f0-9]{8}$/i
const text=(v='')=>String(v??'').trim();const iso=v=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toISOString():null;const unique=(v=[])=>[...new Set(v.filter(Boolean))]
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=='object')return v;return Object.keys(v).sort().reduce((r,k)=>{r[k]=stable(v[k]);return r},{})}function fnv(v){const s=JSON.stringify(stable(v));let h=0x811c9dc5;for(let i=0;i<s.length;i+=1){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)}return`fnv1a_${(h>>>0).toString(16).padStart(8,'0')}`}function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;Object.values(v).forEach(freeze);return Object.freeze(v)}function snap(v){const c=JSON.parse(JSON.stringify(v));delete c.fingerprint;return c}function finding(code,phase,category,severity='critical',evidenceId=null,details=[]){return{code,phase,category,severity,evidenceId,details:unique(details.map(text))}}function boundary(v){return Object.entries(PRACTICE_ASSURANCE_G10_BOUNDARY).every(([k,x])=>v.controls?.[k]===x)}

export function validatePracticeAssuranceG10Checkpoint(input={}){const v=JSON.parse(JSON.stringify(input||{})),e=[]
  if(v.version!==CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION||!v.checkpointId||!PHASES.includes(v.phase)||v.phaseVersion!==PRACTICE_ASSURANCE_G10_PHASE_VERSIONS[v.phase])e.push('g10_checkpoint_identity_invalid')
  if(!v.releaseCandidateId||!v.buildId||!/^[a-f0-9]{40}$|^[a-f0-9]{64}$/i.test(text(v.sourceCommitHash))||!['test','staging','production_candidate'].includes(v.environment)||!v.organisationId||!v.attorneyFirmId||!v.policyFingerprint)e.push('g10_checkpoint_release_binding_invalid')
  if(!v.suiteId||!v.suiteVersion||!iso(v.executedAt)||!iso(v.reviewedAt)||new Date(v.reviewedAt)<new Date(v.executedAt))e.push('g10_checkpoint_provenance_invalid')
  if(!Number.isInteger(v.scenarioCount)||v.scenarioCount<PRACTICE_ASSURANCE_G10_MINIMUM_SCENARIOS[v.phase]||v.passedCount!==v.scenarioCount||v.failedCount!==0||v.skippedCount!==0)e.push('g10_checkpoint_scenario_gate_failed')
  if(PRACTICE_ASSURANCE_G10_PROBES.some(p=>v.probes?.[p]!==true)||Object.keys(v.probes||{}).some(p=>!PRACTICE_ASSURANCE_G10_PROBES.includes(p)))e.push('g10_checkpoint_probe_failed')
  if(!v.evidenceReference||!HASH.test(text(v.evidenceHash))||!(v.artifactFingerprints||[]).length||v.artifactFingerprints.some(x=>!FP.test(text(x))))e.push('g10_checkpoint_evidence_invalid')
  if(!['system','quality_engineer'].includes(v.executedBy?.role)||!v.executedBy?.userId||v.reviewedBy?.role!=='firm_manager'||!v.reviewedBy?.userId||v.executedBy.userId===v.reviewedBy.userId||v.executedBy.organisationId!==v.reviewedBy.organisationId||v.executedBy.attorneyFirmId!==v.reviewedBy.attorneyFirmId)e.push('g10_checkpoint_independent_review_invalid')
  if((v.exceptions||[]).length)e.push('g10_checkpoint_open_exception');if(!boundary(v))e.push('g10_checkpoint_boundary_violated');if(v.fingerprint!==fnv(snap(v)))e.push('g10_checkpoint_fingerprint_invalid');return freeze({valid:!e.length,errors:unique(e),checkpoint:v})}

export function buildPracticeAssuranceG10Checkpoint(input={}){const phase=text(input.phase).toUpperCase();const actor=v=>({userId:text(v?.userId),role:text(v?.role).toLowerCase(),organisationId:text(v?.organisationId),attorneyFirmId:text(v?.attorneyFirmId)});const v={version:CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION,checkpointId:text(input.checkpointId),phase,phaseVersion:text(input.phaseVersion||PRACTICE_ASSURANCE_G10_PHASE_VERSIONS[phase]),releaseCandidateId:text(input.releaseCandidateId),buildId:text(input.buildId),sourceCommitHash:text(input.sourceCommitHash).toLowerCase(),environment:text(input.environment).toLowerCase(),organisationId:text(input.organisationId),attorneyFirmId:text(input.attorneyFirmId),policyFingerprint:text(input.policyFingerprint),suiteId:text(input.suiteId),suiteVersion:text(input.suiteVersion),scenarioCount:Number(input.scenarioCount||0),passedCount:Number(input.passedCount||0),failedCount:Number(input.failedCount||0),skippedCount:Number(input.skippedCount||0),probes:Object.fromEntries(PRACTICE_ASSURANCE_G10_PROBES.map(p=>[p,input.probes?.[p]===true])),artifactFingerprints:unique((input.artifactFingerprints||[]).map(text)).sort(),evidenceReference:text(input.evidenceReference),evidenceHash:text(input.evidenceHash),exceptions:(input.exceptions||[]).map(text).filter(Boolean),executedAt:iso(input.executedAt),executedBy:actor(input.executedBy),reviewedAt:iso(input.reviewedAt),reviewedBy:actor(input.reviewedBy),controls:PRACTICE_ASSURANCE_G10_BOUNDARY,fingerprint:null};v.fingerprint=fnv(snap(v));const check=validatePracticeAssuranceG10Checkpoint(v);return freeze({ok:check.valid,errors:check.errors,checkpoint:check.checkpoint})}

export function assureConveyancerPracticeG10(input={}){const checkpoints=Array.isArray(input.checkpoints)?input.checkpoints:[],findings=[]
  for(const phase of PHASES){const rows=checkpoints.filter(x=>x.phase===phase);if(rows.length!==1)findings.push(finding(rows.length?'g10_phase_checkpoint_duplicate':'g10_phase_checkpoint_missing',phase,'coverage'));for(const row of rows){const v=validatePracticeAssuranceG10Checkpoint(row);if(!v.valid)findings.push(finding('g10_phase_checkpoint_invalid',phase,'contract','critical',row.checkpointId,v.errors))}}
  const releases=unique(checkpoints.map(x=>`${x.releaseCandidateId}|${x.buildId}|${x.sourceCommitHash}|${x.environment}`));if(releases.length!==1)findings.push(finding('g10_release_binding_inconsistent','G10','binding'))
  const tenants=unique(checkpoints.map(x=>`${x.organisationId}|${x.attorneyFirmId}|${x.policyFingerprint}`));if(tenants.length!==1)findings.push(finding('g10_tenant_policy_binding_inconsistent','G10','binding'))
  const scenarioRows=(input.scenarioEvidence||[]).map(x=>({scenarioId:text(x.scenarioId),decision:text(x.decision),evidenceReference:text(x.evidenceReference),evidenceHash:text(x.evidenceHash),phases:unique(x.phases||[])}));for(const id of PRACTICE_ASSURANCE_G10_SCENARIOS){const rows=scenarioRows.filter(x=>x.scenarioId===id);if(rows.length!==1||rows[0].decision!=='ready'||!rows[0].evidenceReference||!HASH.test(rows[0].evidenceHash))findings.push(finding('g10_required_scenario_not_ready','G10','scenario','critical',id))}
  const signoffs=(input.signoffs||[]).filter(x=>x.decision==='approved'&&PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES.includes(text(x.role))&&text(x.approvedBy)&&text(x.reason)&&iso(x.approvedAt));for(const role of PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES)if(!signoffs.some(x=>x.role===role))findings.push(finding(`g10_${role}_signoff_missing`,'G10','signoff'));if(new Set(signoffs.map(x=>x.approvedBy)).size!==PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES.length)findings.push(finding('g10_signoff_separation_required','G10','signoff'))
  if(input.portalIsolation?.version!==CONVEYANCER_EXTERNAL_PORTAL_VERSION||input.portalIsolation?.passed!==true||!FP.test(text(input.portalIsolation?.fingerprint)))findings.push(finding('g10_portal_isolation_evidence_invalid','G8','privacy'))
  if(input.migrationRecovery?.version!==CONVEYANCER_MATTER_CLOSEOUT_RECOVERY_VERSION||input.migrationRecovery?.migrationBalanced!==true||input.migrationRecovery?.recoveryPassed!==true||!FP.test(text(input.migrationRecovery?.fingerprint)))findings.push(finding('g10_migration_recovery_evidence_invalid','G9','recovery'))
  const critical=findings.filter(x=>x.severity==='critical').length,warnings=findings.filter(x=>x.severity==='warning').length;const report={version:CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION,assuranceId:text(input.assuranceId),releaseCandidateId:checkpoints[0]?.releaseCandidateId||null,buildId:checkpoints[0]?.buildId||null,sourceCommitHash:checkpoints[0]?.sourceCommitHash||null,environment:checkpoints[0]?.environment||null,organisationId:checkpoints[0]?.organisationId||null,attorneyFirmId:checkpoints[0]?.attorneyFirmId||null,policyFingerprint:checkpoints[0]?.policyFingerprint||null,assuredAt:iso(input.assuredAt),decision:critical?'blocked':warnings?'observe':'ready',phaseStatus:Object.fromEntries(PHASES.map(p=>[p,!findings.some(f=>f.phase===p&&f.severity==='critical')])),scenarioStatus:Object.fromEntries(PRACTICE_ASSURANCE_G10_SCENARIOS.map(id=>[id,!findings.some(f=>f.evidenceId===id)])),signoffs:signoffs.map(x=>({role:x.role,approvedBy:text(x.approvedBy),reason:text(x.reason),approvedAt:iso(x.approvedAt)})),counts:{checkpoints:checkpoints.length,scenarios:scenarioRows.length,critical,warnings},findings,providerDependency:{externalProvidersRequired:false,manualFallbackRequired:true},controls:PRACTICE_ASSURANCE_G10_BOUNDARY,fingerprint:null};if(!report.assuranceId||!report.assuredAt)report.findings.push(finding('g10_assurance_identity_invalid','G10','contract'));report.counts.critical=report.findings.filter(x=>x.severity==='critical').length;report.decision=report.counts.critical?'blocked':report.counts.warnings?'observe':'ready';report.fingerprint=fnv(snap(report));return freeze(report)}

function thresholds(input={}){return Object.fromEntries(Object.entries(PRACTICE_ASSURANCE_G10_THRESHOLDS).map(([k,v])=>{const n=Number(input[k]);if(!Number.isFinite(n))return[k,v];return k.startsWith('minimum')?[k,Math.max(v,Math.min(1,n))]:[k,Math.min(v,Math.max(0,n))]}))}
export function evaluateConveyancerPracticeG10Pilot({assurances=[],operationalMetrics={},thresholds:input={}}={}){const t=thresholds(input),rows=assurances.map((a,i)=>({scenarioId:text(a.scenarioId)||`scenario_${i+1}`,decision:text(a.assurance?.decision),passed:text(a.assurance?.decision)===(text(a.expectedDecision)||'ready')})),rate=rows.length?rows.filter(x=>x.passed).length/rows.length:0;const hard=['criticalFindings','authorityViolations','accessIncidents','ficaFailures','trustControlBreaches','privacyIncidents','evidenceIntegrityFailures','migrationImbalances','recoveryFailures','sideEffectAttempts'];const metrics=Object.fromEntries([...hard,'manualBacklogRate'].map(k=>[k,Math.max(0,Number(operationalMetrics[k]||0))])),holds=[];if(!rows.length)holds.push('pilot_assurances_required');if(rate<t.minimumScenarioPassRate)holds.push('scenario_pass_rate_below_minimum');for(const k of hard)if(metrics[k]>t[`maximum${k[0].toUpperCase()}${k.slice(1)}`])holds.push(`${k.replace(/[A-Z]/g,l=>`_${l.toLowerCase()}`)}_threshold_exceeded`);if(metrics.manualBacklogRate>t.maximumManualBacklogRate)holds.push('manual_backlog_rate_threshold_exceeded');return freeze({version:CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION,decision:holds.length?'hold':metrics.manualBacklogRate>t.observeManualBacklogRate?'observe':'go',thresholds:t,scenarioPassRate:rate,assurances:rows,operationalMetrics:metrics,holds})}

export function buildConveyancerPracticeG10PilotManifest(input={}){const firmIds=unique((input.firmIds||[]).map(text)).slice(0,3),lanes=unique((input.lanes||[]).map(x=>text(x).toLowerCase())).filter(x=>['transfer','bond','cancellation'].includes(x)),maximumMatters=Math.max(1,Math.min(25,Number(input.maximumMatters||5))),owners=Object.fromEntries([...PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES,'assurance','support','rollback'].map(k=>[k,text(input.owners?.[k])||null])),errors=[];if(!firmIds.length)errors.push('g10_pilot_firm_required');if(!lanes.length)errors.push('g10_pilot_lane_required');if(!iso(input.startsAt)||!iso(input.endsAt)||new Date(input.startsAt)>=new Date(input.endsAt))errors.push('g10_pilot_window_invalid');if(Object.values(owners).some(x=>!x))errors.push('g10_pilot_owner_required');return freeze({version:CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION,valid:!errors.length,errors,scope:{firmIds,lanes,maximumMatters,startsAt:iso(input.startsAt),endsAt:iso(input.endsAt)},requiredScenarios:PRACTICE_ASSURANCE_G10_SCENARIOS,owners,controls:{humanReleaseApprovalRequired:true,killSwitchRequired:true,rollbackOwnerRequired:true,manualFallbackRequired:true,externalProvidersRequired:false,productionCredentialsEnabled:false,databaseWritesEnabled:false,trustPaymentExecutionEnabled:false,portalAccessActivationEnabled:false,deploymentEnabled:false}})}
export function serializeConveyancerPracticeG10Evidence({assurance={},pilot=null,manifest=null}={}){return JSON.stringify(stable({version:CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION,assurance:{assuranceId:assurance.assuranceId||null,releaseCandidateId:assurance.releaseCandidateId||null,buildId:assurance.buildId||null,sourceCommitHash:assurance.sourceCommitHash||null,environment:assurance.environment||null,organisationId:assurance.organisationId||null,attorneyFirmId:assurance.attorneyFirmId||null,policyFingerprint:assurance.policyFingerprint||null,assuredAt:assurance.assuredAt||null,decision:assurance.decision||null,phaseStatus:assurance.phaseStatus||{},scenarioStatus:assurance.scenarioStatus||{},counts:assurance.counts||{},findings:assurance.findings||[],providerDependency:assurance.providerDependency||{},controls:assurance.controls||{},fingerprint:assurance.fingerprint||null},pilot:pilot?{decision:pilot.decision,thresholds:pilot.thresholds,scenarioPassRate:pilot.scenarioPassRate,operationalMetrics:pilot.operationalMetrics,holds:pilot.holds}:null,manifest:manifest?{valid:manifest.valid,errors:manifest.errors,scope:manifest.scope,requiredScenarios:manifest.requiredScenarios,owners:manifest.owners,controls:manifest.controls}:null}))}
