export const attorneyOpportunityData = {
  potentialMonthlyTransactions: 38,
  monthlyOpportunityValue: 1300000,
  confidenceScore: 84,
  marketShareVolume: 4.4,
  marketShareValue: 5.1,
  predictedRegistrations: 31,
  revenueForecast: 2700000,
  missedOpportunity: 1300000,
}

export const mockAgents = [
  {
    id: 'agent-melissa',
    name: 'Melissa van Rensburg',
    agency: 'Prime Residential Group',
    area: 'Pretoria East',
    activeListings: 25,
    estimatedMonthlyTransactions: 12,
    currentAppointments: 0,
    estimatedRevenueOpportunity: 480000,
    opportunityScore: 91,
    reliabilityScore: 88,
    matchScore: 95,
    avatar: 'MV',
    relationship: 'No attorney relationship detected',
    listings: [
      { id: 'm1', title: '2 Bed Apartment', location: 'Pretoria East', price: 'R1.35M', status: 'Active' },
      { id: 'm2', title: '3 Bed Townhouse', location: 'Pretoria East', price: 'R1.85M', status: 'Active' },
      { id: 'm3', title: 'New Development Unit', location: 'Pretoria East', price: 'R1.48M', status: 'Active' },
    ],
  },
  {
    id: 'agent-jason',
    name: 'Jason Mokoena',
    agency: 'UrbanNest Realty',
    area: 'Boksburg',
    activeListings: 19,
    estimatedMonthlyTransactions: 9,
    currentAppointments: 1,
    estimatedRevenueOpportunity: 310000,
    opportunityScore: 84,
    reliabilityScore: 83,
    matchScore: 89,
    avatar: 'JM',
  },
  {
    id: 'agent-carla',
    name: 'Carla Pretorius',
    agency: 'Platinum Property Co.',
    area: 'Midrand',
    activeListings: 17,
    estimatedMonthlyTransactions: 8,
    currentAppointments: 1,
    estimatedRevenueOpportunity: 240000,
    opportunityScore: 79,
    reliabilityScore: 81,
    matchScore: 85,
    avatar: 'CP',
  },
]

export const mockDevelopments = [
  {
    id: 'dev-brookstone',
    name: 'Brookstone Heights',
    developer: 'Axis Property Group',
    area: 'Boksburg',
    units: 86,
    listingsActive: 31,
    expectedTransfersPerMonth: 18,
    currentPreferredAttorney: 'Not assigned',
    estimatedRevenueOpportunity: 620000,
    opportunityScore: 88,
  },
  {
    id: 'dev-ridge',
    name: 'The Ridge Estate',
    developer: 'Zenith Urban',
    area: 'Pretoria East',
    units: 64,
    listingsActive: 24,
    expectedTransfersPerMonth: 12,
    currentPreferredAttorney: 'Competitor',
    estimatedRevenueOpportunity: 350000,
    opportunityScore: 76,
  },
  {
    id: 'dev-willow',
    name: 'Willow Park',
    developer: 'Marble Homes',
    area: 'Midrand',
    units: 58,
    listingsActive: 18,
    expectedTransfersPerMonth: 10,
    currentPreferredAttorney: 'Not assigned',
    estimatedRevenueOpportunity: 270000,
    opportunityScore: 74,
  },
]

export const mockAreas = [
  {
    id: 'pretoria-east',
    name: 'Pretoria East',
    activeListings: 142,
    monthlyTransactions: 64,
    marketShare: 2.1,
    topFirmShare: 8.4,
    gap: 6.3,
    estimatedOpportunity: 740000,
    opportunityLevel: 'High',
    trend: 'up',
    heat: 92,
    suburbs: ['Silver Lakes', 'Moreleta Park', 'Faerie Glen', 'Olympus'],
  },
  {
    id: 'boksburg',
    name: 'Boksburg',
    activeListings: 119,
    monthlyTransactions: 52,
    marketShare: 6.8,
    topFirmShare: 9.1,
    gap: 2.3,
    estimatedOpportunity: 420000,
    opportunityLevel: 'Medium',
    trend: 'up',
    heat: 74,
    suburbs: ['Sunward Park', 'Parkrand', 'Beyers Park', 'Bartlett'],
  },
  {
    id: 'midrand',
    name: 'Midrand',
    activeListings: 101,
    monthlyTransactions: 41,
    marketShare: 3.4,
    topFirmShare: 7.3,
    gap: 3.9,
    estimatedOpportunity: 360000,
    opportunityLevel: 'Emerging',
    trend: 'flat',
    heat: 58,
    suburbs: ['Waterfall', 'Noordwyk', 'Kyalami', 'Carlswald'],
  },
  {
    id: 'centurion',
    name: 'Centurion',
    activeListings: 93,
    monthlyTransactions: 37,
    marketShare: 5.9,
    topFirmShare: 8.1,
    gap: 2.2,
    estimatedOpportunity: 310000,
    opportunityLevel: 'Strong Existing Position',
    trend: 'up',
    heat: 67,
    suburbs: ['Irene', 'Rooihuiskraal', 'Eldoraigne', 'Hennopspark'],
  },
]

export const mockPartners = {
  topPartnerValue: 38000000,
  referralConcentration: 58,
  newPartnerMatches: 12,
  partnerGrowthPotential: 1100000,
  networkNodes: [
    { id: 'firm', label: 'Your Firm', type: 'firm', value: 100, strength: 'core' },
    { id: 'agent-1', label: 'Prime Residential', type: 'agency', value: 86, strength: 'strong' },
    { id: 'agent-2', label: 'UrbanNest Realty', type: 'agency', value: 62, strength: 'medium' },
    { id: 'dev-1', label: 'Axis Property', type: 'developer', value: 78, strength: 'strong' },
    { id: 'dev-2', label: 'Zenith Urban', type: 'developer', value: 56, strength: 'medium' },
    { id: 'bond-1', label: 'Bridge Bond Desk', type: 'bond_originator', value: 49, strength: 'emerging' },
  ],
  topCurrentPartners: [
    { name: 'Prime Residential Group', type: 'Agency', volume: 42, value: 38000000, reliability: 91 },
    { name: 'Axis Property Group', type: 'Developer', volume: 36, value: 33500000, reliability: 89 },
    { name: 'UrbanNest Realty', type: 'Agency', volume: 28, value: 24100000, reliability: 84 },
    { name: 'Bridge Bond Desk', type: 'Bond Originator', volume: 21, value: 18600000, reliability: 82 },
    { name: 'Platinum Property Co.', type: 'Agency', volume: 19, value: 15200000, reliability: 79 },
  ],
  missingHighValuePartners: [
    { name: 'Melissa van Rensburg', type: 'Agent', volume: 12, estimatedOpportunity: 480000, match: 95, avatar: 'MV' },
    { name: 'Brookstone Heights', type: 'Development', volume: 18, estimatedOpportunity: 620000, match: 93, avatar: 'BH' },
    { name: 'Willow Park', type: 'Development', volume: 10, estimatedOpportunity: 270000, match: 86, avatar: 'WP' },
  ],
}

export const mockRevenueForecast = {
  currentMonthForecast: 2700000,
  next90Days: 7900000,
  pipelineCoverage: 1.8,
  revenueGap: 1300000,
  lineItems: [
    { month: 'Current Month', value: 2700000 },
    { month: 'Next Month', value: 3000000 },
    { month: 'Month 3', value: 3200000 },
  ],
  funnel: [
    { stage: 'Instruction Received', count: 48, delayRisk: 'low' },
    { stage: 'Docs Collected', count: 39, delayRisk: 'medium' },
    { stage: 'Lodgement', count: 29, delayRisk: 'medium' },
    { stage: 'Registration', count: 21, delayRisk: 'high' },
  ],
  recommendations: [
    'Add 3 agent relationships to unlock R480k/month',
    'Target Brookstone Heights for R620k/month',
    'Increase Pretoria East share by 2% for R740k/month',
    'Reduce delays to increase capacity by 9 files/month',
  ],
}

export const attorneyIntelligenceNavItems = [
  { key: 'dashboard', label: 'Dashboard', to: '/attorney/intelligence/dashboard' },
  { key: 'opportunity_engine', label: 'Opportunity Engine', to: '/attorney/intelligence/opportunity-engine' },
  { key: 'partner_intelligence', label: 'Partner Intelligence', to: '/attorney/intelligence/partner-intelligence' },
  { key: 'market_position', label: 'Market Position', to: '/attorney/intelligence/market-position' },
  { key: 'revenue_forecast', label: 'Revenue Forecast', to: '/attorney/intelligence/revenue-forecast' },
]
