// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import AddDevelopmentModal from '../AddDevelopmentModal.jsx'
import { createDevelopmentWorkspace, fetchDeveloperPartnersWorkspace } from '../../lib/api.js'
import { sendWhatsAppNotification } from '../../lib/whatsapp'
import { upsertAreaFromAddress } from '../../lib/location/upsertArea'
import { useWorkspace } from '../../context/WorkspaceContext'
import { invokeEdgeFunction } from '../../lib/supabaseClient.js'

vi.mock('../../lib/api.js', () => ({
  createDevelopmentWorkspace: vi.fn(),
  fetchDeveloperAccessOptions: vi.fn(async () => []),
  fetchDeveloperPartnersWorkspace: vi.fn(async () => ({ relationships: [], preferredPartners: [] })),
}))
vi.mock('../../lib/location/upsertArea', () => ({ upsertAreaFromAddress: vi.fn(async () => null) }))
vi.mock('../../lib/supabaseClient.js', () => ({ isSupabaseConfigured: true, invokeEdgeFunction: vi.fn(async () => ({})) }))
vi.mock('../../lib/whatsapp', () => ({ formatSouthAfricanWhatsAppNumber: (number) => number, sendWhatsAppNotification: vi.fn(async () => ({})) }))
vi.mock('../../context/WorkspaceContext', () => {
  const context = { profile: { fullName: 'Test Agent', email: 'agent@example.test' }, workspace: { id: 'agency', name: 'Test Agency' } }
  return { useWorkspace: vi.fn(() => context) }
})

const testWorkspace = { profile: { fullName: 'Test Agent', email: 'agent@example.test' }, workspace: { id: 'agency', name: 'Test Agency' } }

beforeEach(() => {
  window.localStorage.clear()
  vi.clearAllMocks()
  useWorkspace.mockReturnValue(testWorkspace)
  createDevelopmentWorkspace.mockResolvedValue({ id: 'saved-development', warnings: [] })
  upsertAreaFromAddress.mockResolvedValue(null)
})
afterEach(cleanup)

function open() {
  const callbacks = { onClose: vi.fn(), onCreated: vi.fn() }
  const view = render(<AddDevelopmentModal open contextRole="agent" {...callbacks} />)
  return { ...callbacks, rerender: view.rerender }
}
function details() {
  fireEvent.change(screen.getByLabelText('Development Name'), { target: { value: 'Willow Park' } })
  fireEvent.change(screen.getByLabelText('Location / Address'), { target: { value: '12 Test Road' } })
}
function next() { fireEvent.click(screen.getByRole('button', { name: 'Next' })) }
function review() { details(); next(); next(); next() }
function layout(fields = {}, save = true) {
  fireEvent.click(screen.getByRole('button', { name: 'Add unit layout' }))
  const values = { 'Layout name': 'A1', 'Property type': 'Apartment', Bedrooms: '2', Bathrooms: '2', 'Size (m²)': '80', 'List price (R)': '1500000', 'How many units?': '4', ...fields }
  Object.entries(values).forEach(([label, value]) => fireEvent.change(screen.getByLabelText(label), { target: { value } }))
  if (save) fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
}
function setupLayouts() {
  details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
}


it('shows open details and defers developer access until Sales setup', () => {
  open()
  expect(screen.queryByText('Development Summary')).toBeNull()
  expect(screen.queryByText('Advanced Settings')).toBeNull()
  expect(screen.getByLabelText('City')).toBeTruthy()
  expect(screen.getByLabelText(/Launch Date/)).toBeTruthy()
  expect(screen.queryByLabelText(/Status/)).toBeNull()
  expect(screen.queryByLabelText('Developer / Organisation')).toBeNull()
  details(); next(); next()
  expect(screen.getByLabelText('Developer / Organisation')).toBeTruthy()
  expect(screen.getByText('Developer access')).toBeTruthy()
  expect(screen.queryByRole('button', { name: 'Choose another' })).toBeNull()
})

it('checks required details before a draft save and saves the type with manual address details', async () => {
  const callbacks = open()
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('Development name is required')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  details()
  fireEvent.click(screen.getByRole('radio', { name: 'Mixed-use' }))
  fireEvent.change(screen.getByLabelText('City'), { target: { value: 'Johannesburg' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  await screen.findByText('Willow Park saved as a draft.')
  expect(callbacks.onClose).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Done' }))
  expect(callbacks.onClose).toHaveBeenCalledTimes(1)
  const payload = createDevelopmentWorkspace.mock.calls[0][0]
  expect(payload.details).toMatchObject({ status: 'draft', address: '12 Test Road', city: 'Johannesburg', marketingContent: { listingOverview: { developmentType: 'mixed_use' } } })
  expect(payload.units).toEqual([])
  expect(payload.developmentSettings.stakeholderTeams.developers).toEqual([])
  expect(invokeEdgeFunction).not.toHaveBeenCalled()
  expect(sendWhatsAppNotification).not.toHaveBeenCalled()
})

it('rejects invalid dates and fractional planned units before any save', () => {
  open(); details()
  fireEvent.change(screen.getByLabelText(/Launch Date/), { target: { value: '2026-12-01' } })
  fireEvent.change(screen.getByLabelText(/Expected Completion/), { target: { value: '2026-11-01' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('on or after')
  fireEvent.change(screen.getByLabelText(/Expected Completion/), { target: { value: '2027-01-01' } })
  next()
  fireEvent.change(screen.getByLabelText('Planned Units'), { target: { value: '1.5' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('whole number')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
})

it('does not create on an early Enter submit and creates once after Review', async () => {
  const callbacks = open(); details()
  fireEvent.submit(screen.getByLabelText('Development Name').closest('form'))
  expect(screen.getByLabelText('Planned Units')).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  next(); next()
  expect(screen.getByText('Set up units later')).toBeTruthy()
  expect(screen.queryByText('Status')).toBeNull()
  expect(screen.queryByText('Unnamed unit type')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(callbacks.onCreated).toHaveBeenCalledTimes(1))
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
  expect(createDevelopmentWorkspace.mock.calls[0][0].details.status).toBe('active')
})

it('cancels the Next click default before replacing it with the submit button', () => {
  open(); details(); next(); next()
  const clickContinues = fireEvent.click(screen.getByRole('button', { name: 'Next' }))
  expect(clickContinues).toBe(false)
  expect(screen.getByRole('button', { name: 'Create Development →' })).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
})

it('generates building and floor stock with explicit allocations and no release phases', async () => {
  const callbacks = open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' }))
  next()
  expect(screen.queryByRole('button', { name: 'By phase' })).toBeNull()
  fireEvent.click(screen.getByRole('radio', { name: 'Buildings + Units' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add floor to Building A' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add floor to Building A' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add building' }))
  next()
  layout({}, false)
  fireEvent.change(screen.getByLabelText('Units in Building A / Ground floor'), { target: { value: '1' } })
  fireEvent.change(screen.getByLabelText('Units in Building A / Floor 1'), { target: { value: '1' } })
  fireEvent.change(screen.getByLabelText('Units in Building B'), { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' })); next()
  expect(screen.getByText('Check your units')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Remove Ground floor from Building A' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add floor to Building A' }))
  next(); next()
  expect(screen.getByRole('alert').textContent).toContain('3 assigned')
  fireEvent.click(screen.getByRole('button', { name: 'Edit layout A1' }))
  fireEvent.change(screen.getByLabelText('Units in Building A / Ground floor'), { target: { value: '1' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Use these units' }))
  expect(screen.getByLabelText('Developer / Organisation')).toBeTruthy()
  next()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(callbacks.onCreated).toHaveBeenCalledTimes(1))
  const payload = createDevelopmentWorkspace.mock.calls[0][0]
  expect(payload.structureNodes).toHaveLength(4)
  expect(payload.units).toHaveLength(4)
  expect(payload.units.every((unit) => unit.phase === '' && payload.structureNodes.some((node) => node.id === unit.structureNodeId))).toBe(true)
  expect(payload.details).toMatchObject({ status: 'active', totalUnitsExpected: 4 })
  expect(payload.units.map((unit) => unit.unitNumber)).toEqual(['001', '002', '003', '004'])
})

it('blocks incomplete stock on draft save and allows the agent to defer stock instead', async () => {
  const callbacks = open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' }))
  next()
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('Add at least one unit layout')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units later' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  await waitFor(() => expect(callbacks.onCreated).toHaveBeenCalledTimes(1))
  expect(createDevelopmentWorkspace.mock.calls[0][0].units).toEqual([])
  expect(createDevelopmentWorkspace.mock.calls[0][0].structureNodes).toEqual([])
})

it('keeps two unit methods below Planned Units and opens setup only when the agent clicks Next', () => {
  const callbacks = open(); details(); next()
  const method = screen.getByRole('group', { name: 'Unit Configuration Method' })
  expect(within(method).getAllByRole('button')).toHaveLength(2)
  expect(within(method).getByRole('button', { name: 'Set up units later' }).getAttribute('aria-pressed')).toBe('true')
  expect(screen.getByLabelText('Planned Units').compareDocumentPosition(method) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  fireEvent.change(screen.getByLabelText('Planned Units'), { target: { value: '12' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' }))
  expect(screen.getByRole('button', { name: 'Set up units now' }).getAttribute('aria-pressed')).toBe('true')
  expect(within(screen.getByRole('list', { name: 'Development setup progress' })).getAllByRole('listitem')).toHaveLength(4)
  expect(screen.queryByRole('group', { name: 'How are the units organised?' })).toBeNull()
  next()
  expect(screen.getByRole('group', { name: 'How are the units organised?' })).toBeTruthy()
  expect(screen.getByRole('list', { name: 'Development setup progress' }).querySelector('[aria-current="step"]').textContent).toContain('Units')
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  expect(screen.getByLabelText('Planned Units').value).toBe('12')
  expect(screen.getByRole('button', { name: 'Set up units now' }).getAttribute('aria-pressed')).toBe('true')
  fireEvent.click(screen.getByRole('button', { name: 'Set up units later' }))
  expect(within(screen.getByRole('list', { name: 'Development setup progress' })).getAllByRole('listitem')).toHaveLength(4)
  next()
  expect(screen.getByText('Developer access')).toBeTruthy()
  expect(callbacks.onClose).not.toHaveBeenCalled()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
})

it('preserves saved layouts when returning to Units and resuming setup', () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({ 'Property type': 'Townhouse' })
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Set up units later' }))
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  expect(screen.getByText('A1 · Townhouse')).toBeTruthy()
})

it('keeps layout edits local until saved and prevents draft or next actions from losing them', () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({}, false)
  expect(screen.getByRole('button', { name: 'Save Draft' }).disabled).toBe(true)
  expect(screen.getByRole('button', { name: 'Next' }).disabled).toBe(true)
  expect(screen.getByRole('button', { name: 'Back' }).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Cancel layout' }))
  expect(screen.queryByText('A1 · Apartment')).toBeNull()
  layout()
  fireEvent.click(screen.getByRole('button', { name: 'Edit layout A1' }))
  fireEvent.change(screen.getByLabelText('How many units?'), { target: { value: '9' } })
  fireEvent.click(screen.getByRole('button', { name: 'Cancel layout' })); next()
  expect(screen.getByText('4 units will be created from 1 layout.')).toBeTruthy()
  expect(screen.getByText('001–004')).toBeTruthy()
  expect(screen.getByText('Change unit numbering').closest('details').open).toBe(false)
})

it('retains optional floor plans and room details through the draft payload without creating duplicate documents', async () => {
  const callbacks = open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({}, false)
  const attachment = new File(['floor plan'], 'A1.pdf', { type: 'application/pdf' })
  fireEvent.change(screen.getByLabelText('Floor plan or unit image (optional)'), { target: { files: [attachment] } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.getByText('A1.pdf')).toBeTruthy()
  expect(screen.queryByRole('region', { name: 'Building allocation' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  await waitFor(() => expect(callbacks.onCreated).toHaveBeenCalled())
  const payload = createDevelopmentWorkspace.mock.calls[0][0]
  expect(payload.productCatalogue.unitTypes[0]).toMatchObject({ bedrooms: 2, bathrooms: 2 })
  expect(payload.productCatalogue.floorplans[0].file).toBe(attachment)
  expect(payload.documents).toEqual([])
})

it('returns draft validation errors to Sales setup even when Unit setup adds a step', () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({ 'How many units?': '2' })
  next(); fireEvent.click(screen.getByRole('button', { name: 'Use these units' }))
  fireEvent.click(screen.getByRole('button', { name: 'Invite developer' }))
  fireEvent.change(screen.getByLabelText('Developer company name'), { target: { value: 'Builder' } })
  for (let i = 0; i < 5; i += 1) fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  expect(screen.getByLabelText('Development Name')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('company name, contact name, and email')
  expect(screen.getByText('Developer access')).toBeTruthy()
  expect(screen.getByRole('list', { name: 'Development setup progress' }).querySelector('[aria-current="step"]').textContent).toContain('Sales setup')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
})

it('validates developer invitations on draft save after returning to Details', () => {
  open(); details(); next(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Invite developer' }))
  fireEvent.change(screen.getByLabelText('Developer company name'), { target: { value: 'Builder' } })
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('company name, contact name, and email')
  expect(screen.getByText('Developer access')).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
})

it('lets the agent defer access after starting an invitation without saving or sending that invitation', async () => {
  const callbacks = open(); details(); next(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Invite developer' }))
  fireEvent.change(screen.getByLabelText('Developer company name'), { target: { value: 'Builder' } })
  fireEvent.click(screen.getByRole('button', { name: 'Add access later' }))
  next()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Ready to go')
  expect(callbacks.onClose).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Done' }))
  expect(callbacks.onClose).toHaveBeenCalledTimes(1)
  expect(createDevelopmentWorkspace.mock.calls[0][0].developmentSettings.stakeholderTeams.developers).toEqual([])
  expect(invokeEdgeFunction).not.toHaveBeenCalled()
  expect(sendWhatsAppNotification).not.toHaveBeenCalled()
})

it('requires a valid reservation amount when the deposit default is enabled', () => {
  open(); details(); next(); next()
  fireEvent.click(screen.getByLabelText(/Reservation deposit applies/))
  next()
  expect(screen.getByRole('alert').textContent).toContain('positive reservation deposit amount')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.change(screen.getByLabelText(/^Reservation Deposit Amount/), { target: { value: '5000' } })
  next()
  expect(screen.getByText(/^R5\s?000$/)).toBeTruthy()
})

it('keeps a saved development visible when area indexing fails and prevents another create', async () => {
  upsertAreaFromAddress.mockRejectedValue(new Error('Area indexing unavailable'))
  const callbacks = open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('The development was saved, but its area directory entry could not be updated.')
  expect(screen.getByRole('link', { name: 'Open development' }).getAttribute('href')).toBe('/developments/saved-development')
  expect(screen.queryByRole('button', { name: 'Save Draft' })).toBeNull()
  expect(screen.getByText('Saved · needs attention')).toBeTruthy()
  expect(callbacks.onClose).not.toHaveBeenCalled()
  expect(callbacks.onCreated).toHaveBeenCalledTimes(1)
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
})

it('opens the existing record when some creation setup fails after the development is saved', async () => {
  createDevelopmentWorkspace.mockRejectedValue(Object.assign(new Error('Some unit setup could not be saved.'), { developmentId: 'existing-development' }))
  const callbacks = open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Some unit setup could not be saved.')
  expect(screen.getByRole('link', { name: 'Open development' }).getAttribute('href')).toBe('/developments/existing-development')
  expect(screen.queryByRole('button', { name: 'Create Development →' })).toBeNull()
  expect(screen.queryByText(/units added/)).toBeNull()
  expect(callbacks.onCreated).toHaveBeenCalledWith({ id: 'existing-development', name: 'Willow Park' })
})

it('offers two structure choices and keeps internal storeys with the saved duplex layout', async () => {
  const callbacks = open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next()
  const structureChoices = within(screen.getByRole('group', { name: 'How are the units organised?' })).getAllByRole('radio')
  expect(structureChoices).toHaveLength(2)
  expect(screen.getByRole('radio', { name: 'Units', exact: true }).checked).toBe(true)
  expect(screen.getByRole('radio', { name: 'Buildings + Units', exact: true })).toBeTruthy()
  expect(screen.queryByRole('radio', { name: 'Blocks / clusters' })).toBeNull()
  next()
  layout({ 'Layout name': 'D1', 'Property type': 'Duplex', 'Size (m²)': '120', 'List price (R)': '1800000', 'How many units?': '3' }, false)
  const storeys = screen.getByLabelText('Storeys inside each unit')
  expect(storeys.value).toBe('1')
  fireEvent.change(storeys, { target: { value: '1.5' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.getByRole('alert').textContent).toContain('whole number of storeys')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.change(storeys, { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Edit layout D1' }))
  expect(screen.getByLabelText('Storeys inside each unit').value).toBe('2')
  fireEvent.click(screen.getByRole('button', { name: 'Cancel layout' })); next()
  expect(screen.getByText('2 storeys per unit')).toBeTruthy()
  expect(screen.getByText('001–003')).toBeTruthy()
  expect(screen.queryByRole('table')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(callbacks.onCreated).toHaveBeenCalledTimes(1))
  const payload = createDevelopmentWorkspace.mock.calls[0][0]
  expect(payload.structureNodes).toEqual([])
  expect(payload.units).toHaveLength(3)
  const savedLayout = payload.productCatalogue.floorplans[0]
  expect(savedLayout.storeys).toBe(2)
  expect(payload.units.every((unit) => unit.catalogueFloorplanId === savedLayout.id && unit.structureNodeId === null)).toBe(true)
})

it('edits details directly from Review, validates them, and returns without creating', async () => {
  open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Edit development details' }))
  fireEvent.change(screen.getByLabelText('Development Name'), { target: { value: '' } })
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  expect(screen.getByRole('alert').textContent).toContain('Development name is required')
  fireEvent.change(screen.getByLabelText('Development Name'), { target: { value: 'Willow Gardens' } })
  expect(fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))).toBe(false)
  expect(screen.getByRole('heading', { name: 'Willow Gardens' })).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1))
  expect(createDevelopmentWorkspace.mock.calls[0][0].details.name).toBe('Willow Gardens')
})

it('keeps extra sales settings collapsed and retains changes after direct review editing', async () => {
  open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Edit sales setup' }))
  const more = screen.getByText('More settings').closest('details')
  expect(more.open).toBe(false)
  more.open = true
  fireEvent.click(screen.getByLabelText('Multiple agents allowed'))
  fireEvent.click(screen.getByLabelText('Buyer may use own bond originator'))
  fireEvent.click(screen.getByLabelText('Auto-invite selected bond originator'))
  expect(screen.getByLabelText('Approve buyer-appointed originators').disabled).toBe(true)
  fireEvent.click(screen.getByLabelText('Reservation deposit applies'))
  fireEvent.change(screen.getByLabelText('Amount Type'), { target: { value: 'percentage' } })
  fireEvent.change(screen.getByLabelText(/^Reservation Deposit Amount/), { target: { value: '101' } })
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  expect(screen.getByRole('alert').textContent).toContain('100 or less')
  fireEvent.change(screen.getByLabelText(/^Reservation Deposit Amount/), { target: { value: '5' } })
  fireEvent.change(screen.getByLabelText('Payable To'), { target: { value: 'agency_trust' } })
  more.open = false
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  expect(screen.getByText('5%')).toBeTruthy()
  expect(screen.getByText('Agency trust account')).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Edit sales setup' }))
  expect(screen.getByLabelText('Multiple agents allowed').checked).toBe(false)
  expect(screen.getByLabelText('Auto-invite selected bond originator').checked).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1))
  const settings = createDevelopmentWorkspace.mock.calls[0][0].developmentSettings
  expect(settings.rolePlayerDefaults).toMatchObject({ multipleAgentsAllowed: false, buyerAppointedBondOriginatorAllowed: false, buyerAppointedBondOriginatorRequiresApproval: false, autoInviteSelectedBondOriginator: true })
  expect(settings).toMatchObject({ reservation_deposit_amount: 5, reservation_deposit_amount_type: 'percentage', reservation_deposit_payable_to: 'agency_trust' })
})

it('regenerates the edited layouts before returning directly to final Review', async () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  expect(screen.getByText('2 bed · 2 bath · 80 m²')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Edit units' }))
  next(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Edit layout A1' }))
  fireEvent.change(screen.getByLabelText('How many units?'), { target: { value: '6' } })
  expect(screen.getByRole('button', { name: 'Next' }).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  expect(screen.getByText('Apartment · 6 units')).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1))
  expect(createDevelopmentWorkspace.mock.calls[0][0].units.map((unit) => unit.unitNumber)).toEqual(['001', '002', '003', '004', '005', '006'])
})

it('can defer generated units from Review without leaking the retained layouts into the save', async () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Edit units' }))
  fireEvent.click(screen.getByRole('button', { name: 'Set up units later' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  expect(screen.getByText('Planned units')).toBeTruthy()
  expect(screen.queryByRole('list', { name: 'Unit layouts' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1))
  expect(createDevelopmentWorkspace.mock.calls[0][0].units).toEqual([])
})

it('shows invitation recipients before save and sends nothing while reviewing or editing', () => {
  open(); details(); next(); next()
  fireEvent.change(screen.getByLabelText('Developer / Organisation'), { target: { value: 'Old company' } })
  fireEvent.click(screen.getByRole('button', { name: 'Invite developer' }))
  const invitation = { 'Developer company name': 'Builder', 'Developer contact name': 'Jane', 'Developer email': 'jane@example.test', 'Developer phone': '+27820000000' }
  Object.entries(invitation).forEach(([label, value]) => fireEvent.change(screen.getByLabelText(label), { target: { value } }))
  next()
  expect(screen.getByText('On save: email invitation to jane@example.test + WhatsApp to +27820000000.')).toBeTruthy()
  expect(screen.getByText('Builder')).toBeTruthy()
  expect(screen.queryByText('Old company')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Edit sales setup' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  expect(invokeEdgeFunction).not.toHaveBeenCalled()
  expect(sendWhatsAppNotification).not.toHaveBeenCalled()
})


it('keeps partner defaults optional and saves the selected preferred sales team', async () => {
  fetchDeveloperPartnersWorkspace.mockResolvedValueOnce({ defaults: [{ id: 'agency-default', relationshipId: 'agency-relationship', partnerType: 'agency', companyName: 'Preferred Agency', isActive: true, isPreferredDefault: true }] })
  open(); details(); next(); next()
  await screen.findByRole('option', { name: 'Preferred Agency (preferred partner)' })
  const agent = screen.getByLabelText('Selling agent')
  expect(agent.value).toBe('none')
  fireEvent.change(agent, { target: { value: 'developer_partner_default' } })
  next()
  expect(screen.getByText('Preferred Agency')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Edit sales setup' }))
  expect(screen.getByLabelText('Selling agent').value).toBe('developer_partner_default')
  fireEvent.click(screen.getByRole('button', { name: 'Back to review' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1))
  expect(createDevelopmentWorkspace.mock.calls[0][0].developmentSettings.rolePlayerDefaults).toMatchObject({ defaultAgentSource: 'developer_partner_default', defaultAgentRelationshipId: 'agency-relationship', defaultAgentPreferredPartnerId: 'agency-default', defaultAgentName: 'Preferred Agency' })
})

it('recovers the current screen and sales choices after a remount without saving remotely', async () => {
  open(); details(); next(); next()
  fireEvent.click(screen.getByLabelText('Reservation deposit applies'))
  fireEvent.change(screen.getByLabelText(/^Reservation Deposit Amount/), { target: { value: '5000' } })
  await screen.findByText('Saved on this device')
  cleanup(); open()
  expect(screen.getByText('Continue your draft?')).toBeTruthy()
  expect(screen.queryByLabelText('Development Name')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Resume draft' }))
  await screen.findByLabelText('Developer / Organisation')
  expect(screen.getByLabelText(/^Reservation Deposit Amount/).value).toBe('5000')
  expect(screen.getByLabelText('Reservation deposit applies').checked).toBe(true)
  next()
  expect(screen.getByRole('heading', { name: 'Willow Park' })).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  expect(invokeEdgeFunction).not.toHaveBeenCalled()
})

it('recovers unfinished layout edits and still requires Save layout before continuing', async () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({ 'Layout name': 'Unfinished' }, false)
  cleanup(); open()
  fireEvent.click(screen.getByRole('button', { name: 'Resume draft' }))
  await screen.findByLabelText('Layout name')
  expect(screen.getByLabelText('Layout name').value).toBe('Unfinished')
  expect(screen.getByLabelText('How many units?').value).toBe('4')
  expect(screen.getByRole('button', { name: 'Next' }).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' })); next()
  expect(screen.getByText('001–004')).toBeTruthy()
})

it('starts fresh only after an explicit choice and removes the previous draft', () => {
  open(); details(); next()
  cleanup(); open()
  fireEvent.click(screen.getByRole('button', { name: 'Start fresh' }))
  expect(screen.getByLabelText('Development Name').value).toBe('')
  expect(window.localStorage.length).toBe(0)
  cleanup(); open()
  expect(screen.queryByText('Continue your draft?')).toBeNull()
})

it('clears recovery after a successful server save', async () => {
  open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await waitFor(() => expect(window.localStorage.length).toBe(0))
  cleanup(); open()
  expect(screen.queryByText('Continue your draft?')).toBeNull()
  expect(screen.getByLabelText('Development Name').value).toBe('')
})

it('recovers the saved record rather than a createable draft after a partial server save', async () => {
  createDevelopmentWorkspace.mockRejectedValue(Object.assign(new Error('Units need attention.'), { developmentId: 'partial-record' }))
  open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Units need attention.')
  cleanup(); open()
  expect(screen.getByText('Development already saved')).toBeTruthy()
  expect(screen.getByRole('link', { name: 'Open development' }).getAttribute('href')).toBe('/developments/partial-record')
  expect(screen.queryByRole('button', { name: 'Create Development →' })).toBeNull()
  expect(screen.queryByRole('button', { name: 'Resume draft' })).toBeNull()
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
})

it('keeps recovery on a failed save and restores the completed Review step', async () => {
  createDevelopmentWorkspace.mockRejectedValue(new Error('Connection unavailable'))
  open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Connection unavailable')
  cleanup(); open()
  fireEvent.click(screen.getByRole('button', { name: 'Resume draft' }))
  await screen.findByRole('heading', { name: 'Willow Park' })
  expect(screen.getByRole('button', { name: 'Create Development →' })).toBeTruthy()
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
})

it('requires missing recovered attachments to be reattached or explicitly removed', async () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({}, false)
  fireEvent.change(screen.getByLabelText('Floor plan or unit image (optional)'), { target: { files: [new File(['%PDF-1.4'], 'A1.pdf', { type: 'application/pdf' })] } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  cleanup(); open()
  fireEvent.click(screen.getByRole('button', { name: 'Resume draft' }))
  await screen.findByText('Reattach A1.pdf')
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  expect(screen.getByRole('alert').textContent).toContain('Reattach or remove')
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Edit layout A1' }))
  fireEvent.click(screen.getByRole('button', { name: 'Remove attachment' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save Draft' }))
  await waitFor(() => expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1))
})

it('shows a clear saving state and prevents repeated server saves', async () => {
  let resolveSave
  createDevelopmentWorkspace.mockImplementation(() => new Promise((resolve) => { resolveSave = resolve }))
  open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  expect(screen.getAllByRole('button', { name: 'Saving…' }).every((button) => button.disabled)).toBe(true)
  fireEvent.click(screen.getAllByRole('button', { name: 'Saving…' })[0])
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
  resolveSave({ id: 'saved-record', warnings: [] })
  await screen.findByText('Willow Park has been created.')
})

it('keeps edits when local storage fails and asks before leaving without recovery', async () => {
  const setItem = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Quota exceeded') })
  try {
    const callbacks = open(); details()
    await screen.findByText('Recovery unavailable')
    fireEvent.click(screen.getByRole('button', { name: 'Close dialog' }))
    await screen.findByText('Leave without recovery?')
    expect(callbacks.onClose).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Keep editing' }))
    expect(screen.getByLabelText('Development Name').value).toBe('Willow Park')
    fireEvent.click(screen.getByRole('button', { name: 'Close dialog' }))
    await screen.findByText('Leave without recovery?')
    fireEvent.click(screen.getByRole('button', { name: 'Leave' }))
    expect(callbacks.onClose).toHaveBeenCalledTimes(1)
  } finally { setItem.mockRestore() }
})


it('isolates a live account switch and preserves edits during profile refreshes', async () => {
  const callbacks = open(); details()
  await screen.findByText('Saved on this device')
  const bob = { ...testWorkspace, profile: { id: 'bob', fullName: 'Bob', email: 'bob@example.test' } }
  useWorkspace.mockReturnValue(bob)
  callbacks.rerender(<AddDevelopmentModal open contextRole="agent" onClose={callbacks.onClose} />)
  expect(screen.queryByText('Continue your draft?')).toBeNull()
  expect(screen.getByLabelText('Development Name').value).toBe('')
  fireEvent.change(screen.getByLabelText('Development Name'), { target: { value: 'Bob development' } })
  useWorkspace.mockReturnValue({ ...bob, profile: { ...bob.profile, fullName: 'Bob updated' } })
  callbacks.rerender(<AddDevelopmentModal open contextRole="agent" onClose={callbacks.onClose} />)
  expect(screen.getByLabelText('Development Name').value).toBe('Bob development')
  useWorkspace.mockReturnValue(testWorkspace)
  callbacks.rerender(<AddDevelopmentModal open contextRole="agent" onClose={callbacks.onClose} />)
  expect(screen.getByText('Continue your draft?')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Resume draft' }))
  await screen.findByLabelText('Development Name')
  expect(screen.getByLabelText('Development Name').value).toBe('Willow Park')
})


it('does not display a late server result in a different account or overwrite its recovery', async () => {
  let resolveSave
  createDevelopmentWorkspace.mockImplementation(() => new Promise((resolve) => { resolveSave = resolve }))
  const callbacks = open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  useWorkspace.mockReturnValue({ ...testWorkspace, profile: { id: 'bob', fullName: 'Bob', email: 'bob@example.test' } })
  callbacks.rerender(<AddDevelopmentModal open contextRole="agent" onClose={callbacks.onClose} onCreated={callbacks.onCreated} />)
  fireEvent.change(screen.getByLabelText('Development Name'), { target: { value: 'Bob development' } })
  resolveSave({ id: 'alice-record', warnings: [] })
  await waitFor(() => expect(JSON.stringify([...Array(localStorage.length)].map((_, i) => localStorage.getItem(localStorage.key(i))))).toContain('alice-record'))
  expect(screen.getByLabelText('Development Name').value).toBe('Bob development')
  expect(screen.queryByRole('link', { name: 'Open development' })).toBeNull()
  expect(callbacks.onCreated).not.toHaveBeenCalled()
  expect(callbacks.onClose).not.toHaveBeenCalled()
})

it('duplicates layout details and attachments without adding stock until the copy is saved', async () => {
  open(); setupLayouts(); layout({}, false)
  const file = new File(['plan'], 'A1.pdf', { type: 'application/pdf' })
  fireEvent.change(screen.getByLabelText('Floor plan or unit image (optional)'), { target: { files: [file] } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Duplicate layout A1' }))
  expect(screen.getByLabelText('Layout name').value).toBe('A1 copy')
  expect(screen.getByLabelText('Bedrooms').value).toBe('2')
  expect(screen.getByLabelText('Size (m²)').value).toBe('80')
  expect(screen.getByLabelText('How many units?').value).toBe('')
  expect(screen.getByText('A1.pdf')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.getByRole('alert').textContent).toContain('quantity')
  fireEvent.change(screen.getByLabelText('How many units?'), { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.getByRole('article', { name: 'Layout A1' })).toBeTruthy()
  expect(screen.getByRole('article', { name: 'Layout A1 copy' })).toBeTruthy()
  next(); fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Ready to go')
  const payload = createDevelopmentWorkspace.mock.calls[0][0]
  expect(payload.units).toHaveLength(6)
  expect(new Set(payload.productCatalogue.floorplans.map((entry) => entry.id)).size).toBe(2)
  expect(new Set(payload.productCatalogue.unitTypes.map((entry) => entry.id)).size).toBe(2)
  expect(payload.productCatalogue.floorplans.every((entry) => entry.file === file)).toBe(true)
  expect(screen.getByText('6 units added')).toBeTruthy()
})

it('names repeated copies uniquely and cancelling a copy preserves the original total', () => {
  const callbacks = open(); setupLayouts(); layout()
  fireEvent.click(screen.getByRole('button', { name: 'Duplicate layout A1' }))
  fireEvent.change(screen.getByLabelText('How many units?'), { target: { value: '1' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Duplicate layout A1' }))
  expect(screen.getByLabelText('Layout name').value).toBe('A1 copy 2')
  fireEvent.keyDown(screen.getByLabelText('Layout name'), { key: 'Escape' })
  expect(screen.getAllByRole('article')).toHaveLength(2)
  expect(screen.getByText('5 units')).toBeTruthy()
  expect(callbacks.onClose).not.toHaveBeenCalled()
})

it('requires fresh building allocations for a copied layout', () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next()
  fireEvent.click(screen.getByRole('radio', { name: 'Buildings + Units' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add building' })); next()
  layout({}, false)
  fireEvent.change(screen.getByLabelText('Units in Building A'), { target: { value: '2' } })
  fireEvent.change(screen.getByLabelText('Units in Building B'), { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Duplicate layout A1' }))
  expect(screen.getByLabelText('Units in Building A').value).toBe('')
  expect(screen.getByLabelText('Units in Building B').value).toBe('')
  fireEvent.change(screen.getByLabelText('How many units?'), { target: { value: '1' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.getByRole('alert').textContent).toContain('allocate exactly 1')
  fireEvent.change(screen.getByLabelText('Units in Building B'), { target: { value: '1' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.getByRole('article', { name: 'Layout A1 copy' })).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
})

it('undoes a removed layout with its attachment and does not override later edits', async () => {
  open(); setupLayouts(); layout({}, false)
  const file = new File(['original'], 'original.pdf', { type: 'application/pdf' })
  fireEvent.change(screen.getByLabelText('Floor plan or unit image (optional)'), { target: { files: [file] } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Remove layout A1' }))
  expect(screen.queryByRole('article', { name: 'Layout A1' })).toBeNull()
  fireEvent.keyDown(screen.getByRole('button', { name: 'Undo' }), { key: 'z', ctrlKey: true })
  expect(screen.getByRole('article', { name: 'Layout A1' })).toBeTruthy()
  expect(screen.getByText('original.pdf')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Remove layout A1' }))
  layout({ 'Layout name': 'B1' }, false)
  expect(screen.getByRole('button', { name: 'Undo' }).disabled).toBe(true)
  fireEvent.keyDown(screen.getByLabelText('Layout name'), { key: 'z', metaKey: true })
  expect(screen.getByLabelText('Layout name').value).toBe('B1')
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  expect(screen.queryByRole('button', { name: 'Undo' })).toBeNull()
  next(); fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Ready to go')
  expect(createDevelopmentWorkspace.mock.calls[0][0].productCatalogue.floorplans.map((entry) => entry.name)).toEqual(['B1'])
})

it('restores deleted buildings and floors together with their allocations', async () => {
  open(); details(); next()
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next()
  fireEvent.click(screen.getByRole('radio', { name: 'Buildings + Units' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add floor to Building A' }))
  fireEvent.click(screen.getByRole('button', { name: 'Add floor to Building A' })); next()
  layout({}, false)
  fireEvent.change(screen.getByLabelText('Units in Building A / Ground floor'), { target: { value: '2' } })
  fireEvent.change(screen.getByLabelText('Units in Building A / Floor 1'), { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Remove Ground floor from Building A' }))
  fireEvent.click(screen.getByRole('button', { name: 'Undo' }))
  fireEvent.click(screen.getByRole('button', { name: 'Remove Building A' }))
  fireEvent.click(screen.getByRole('button', { name: 'Undo' }))
  fireEvent.click(screen.getByRole('radio', { name: 'Units', exact: true }))
  fireEvent.click(screen.getByRole('button', { name: 'Undo' }))
  next()
  fireEvent.click(screen.getByRole('button', { name: 'Edit layout A1' }))
  expect(screen.getByLabelText('Units in Building A / Ground floor').value).toBe('2')
  expect(screen.getByLabelText('Units in Building A / Floor 1').value).toBe('2')
  fireEvent.click(screen.getByRole('button', { name: 'Save layout' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Ready to go')
  const payload = createDevelopmentWorkspace.mock.calls[0][0]
  expect(payload.structureNodes).toHaveLength(3)
  expect(new Set(payload.units.map((entry) => entry.structureNodeId)).size).toBe(2)
})

it('uses keyboard shortcuts for validated progress and layout save without creating from Review', () => {
  open()
  fireEvent.keyDown(screen.getByLabelText('Development Name'), { key: 'Enter', ctrlKey: true })
  expect(screen.getByRole('alert').textContent).toContain('Development name')
  details()
  fireEvent.keyDown(screen.getByLabelText('Development Name'), { key: 'Enter', metaKey: true })
  fireEvent.click(screen.getByRole('button', { name: 'Set up units now' })); next(); next()
  layout({}, false)
  fireEvent.keyDown(screen.getByLabelText('Layout name'), { key: 'Enter', metaKey: true })
  expect(screen.getByRole('article', { name: 'Layout A1' })).toBeTruthy()
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  next(); fireEvent.click(screen.getByRole('button', { name: 'Use these units' })); next()
  fireEvent.keyDown(screen.getByRole('button', { name: 'Create Development →' }), { key: 'Enter', ctrlKey: true })
  expect(createDevelopmentWorkspace).not.toHaveBeenCalled()
  expect(screen.getByRole('button', { name: 'Create Development →' })).toBeTruthy()
})

it('saves a workspace draft with Ctrl S and requires Done or Open after completion', async () => {
  const callbacks = open(); details()
  fireEvent.keyDown(screen.getByLabelText('Development Name'), { key: 's', ctrlKey: true })
  await screen.findByText('Draft saved')
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
  expect(createDevelopmentWorkspace.mock.calls[0][0].details.status).toBe('draft')
  expect(screen.queryByLabelText('Development Name')).toBeNull()
  expect(screen.queryByRole('list', { name: 'Development setup progress' })).toBeNull()
  expect(screen.getByRole('link', { name: 'Open development' }).getAttribute('href')).toBe('/developments/saved-development')
  expect(callbacks.onClose).not.toHaveBeenCalled()
  expect(fireEvent.keyDown(screen.getByRole('button', { name: 'Done' }), { key: 's', ctrlKey: true })).toBe(false)
  expect(createDevelopmentWorkspace).toHaveBeenCalledTimes(1)
  fireEvent.click(screen.getByRole('button', { name: 'Done' }))
  expect(callbacks.onClose).toHaveBeenCalledTimes(1)
})

it('keeps completion actions disabled until post-save work has finished', async () => {
  let finishArea
  upsertAreaFromAddress.mockReturnValue(new Promise((resolve) => { finishArea = resolve }))
  const callbacks = open(); review()
  fireEvent.click(screen.getByRole('button', { name: 'Create Development →' }))
  await screen.findByText('Finishing setup…')
  expect(screen.getByRole('button', { name: 'Done' }).disabled).toBe(true)
  expect(screen.queryByRole('link', { name: 'Open development' })).toBeNull()
  expect(screen.queryByRole('button', { name: 'Create Development →' })).toBeNull()
  expect(callbacks.onCreated).not.toHaveBeenCalled()
  finishArea(null)
  await screen.findByText('Ready to go')
  expect(screen.getByRole('button', { name: 'Done' }).disabled).toBe(false)
  expect(screen.getByRole('link', { name: 'Open development' })).toBeTruthy()
  expect(callbacks.onCreated).toHaveBeenCalledTimes(1)
})
