import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useOrganisation } from '../../context/OrganisationContext'
import { ArrowLeft, BadgeCheck, CalendarDays, CheckCircle2, ChevronDown, ChevronRight, Clock3, FileCheck2, Gavel, Landmark, MapPin, MoreHorizontal, Search, TicketCheck, UserCheck, UsersRound, X } from 'lucide-react'
import { auctionTabs, auctions, launchTabs, launches as seededLaunches } from '../../data/launchesAuctions'
import { formatEventDate, useMarketingEvents } from '../../lib/marketingEventStore'

const metricIcons = { upcoming: CalendarDays, invited: UsersRound, registrations: TicketCheck, leads: UserCheck, active: Gavel, bidders: UsersRound, lots: CalendarDays, clearance: CheckCircle2 }
const launchImage = 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=520&q=84'

function OverviewStats({ stats, label }) { return <section className="wa-stats" aria-label={label}>{stats.map((stat) => { const Icon = metricIcons[stat.id]; return <article className={`wa-stat la-stat la-stat-${stat.id}`} key={stat.id}><span className="wa-stat-icon"><Icon size={19} /></span><span className="wa-stat-copy"><strong>{stat.value}</strong><span>{stat.label}</span><small>{stat.detail}</small></span></article> })}</section> }
function StatusBadge({ status }) { return <span className={`wa-status la-status la-status-${status.toLowerCase().replaceAll(' ', '-')}`}>{status}</span> }

function LaunchCard({ launch }) {
  return <article className="la-card"><img src={launch.image || launchImage} alt="" /><div className="la-card-main"><div className="la-card-heading"><div><span className="la-card-kicker">{launch.development}</span><h3>{launch.title}</h3><p><MapPin size={12} /> {launch.location}</p></div><StatusBadge status={launch.status} /></div><div className="la-card-date"><span><CalendarDays size={13} /> {launch.date}</span><span><Clock3 size={13} /> {launch.time}</span><span><BadgeCheck size={13} /> {launch.readiness}</span></div><dl className="la-card-metrics"><div><dt>Invited</dt><dd>{launch.invited}</dd></div><div><dt>Registrations</dt><dd>{launch.registrations}</dd></div><div><dt>Attending</dt><dd>{launch.attending}</dd></div><div><dt>Qualified Leads</dt><dd>{launch.leads}</dd></div></dl>{launch.publicToken ? <Link className="marketing-rsvp-link" to={`/marketing/rsvp/${launch.publicToken}`}>Open RSVP page</Link> : null}</div><button className="wa-more" type="button" aria-label={`More options for ${launch.title}`}><MoreHorizontal size={18} /></button></article>
}

function AuctionCard({ auction, onOpen }) {
  const open = () => onOpen(auction.id)
  return <article className="la-card auction-card" role="link" tabIndex={0} onClick={open} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open() } }}><img src={auction.image} alt="" /><div className="la-card-main"><div className="la-card-heading"><div><span className="la-card-kicker">Property auction</span><h3>{auction.title}</h3><p><MapPin size={12} /> {auction.address}</p></div><StatusBadge status={auction.status} /></div><div className="la-card-date"><span><CalendarDays size={13} /> {auction.date}</span><span><Clock3 size={13} /> {auction.time}</span><span><BadgeCheck size={13} /> Documents {auction.documents.toLowerCase()}</span></div><dl className="la-card-metrics"><div><dt>{auction.status === 'Bidding open' ? 'Current bid' : 'Guide price'}</dt><dd>{auction.status === 'Bidding open' ? auction.currentBid : auction.guidePrice}</dd></div><div><dt>Registered bidders</dt><dd>{auction.bidders}</dd></div><div><dt>Property views</dt><dd>{auction.viewings}</dd></div><div><dt>Documents</dt><dd>{auction.documents}</dd></div></dl></div><button className="wa-more" type="button" aria-label={`More options for ${auction.title}`} onClick={(event) => event.stopPropagation()}><MoreHorizontal size={18} /></button></article>
}

function AuctionDetail({ auction, onBack }) {
  return <div className="wa-page auctions-page auction-detail-page">
    <button className="wa-back-link" type="button" onClick={onBack}><ArrowLeft size={15} /> Auctions</button>
    <section className="auction-detail-hero"><img src={auction.image} alt="" /><div><span className="la-card-kicker">Property auction</span><h1>{auction.title}</h1><p><MapPin size={15} /> {auction.address}</p><div className="auction-detail-meta"><span><CalendarDays size={15} /> {auction.date}</span><span><Clock3 size={15} /> {auction.time}</span><StatusBadge status={auction.status} /></div></div></section>
    <section className="auction-bidding-panel"><div><span className="md-eyebrow">BIDDING STATUS</span><strong>{auction.status === 'Bidding open' ? auction.currentBid : auction.guidePrice}</strong><p>{auction.status === 'Bidding open' ? `Opening bid ${auction.openingBid}` : 'Guide price for qualified bidders'}</p></div><div><span className="md-eyebrow">REGISTRATION</span><strong>{auction.bidders} bidders registered</strong><p>Closes {auction.registrationClose}</p></div><button className="wa-primary-button" type="button">Register a bidder <ChevronRight size={16} /></button></section>
    <section className="auction-detail-grid"><article className="auction-detail-card"><span className="md-eyebrow">PROPERTY OVERVIEW</span><h2>Ready for auction day</h2><p>{auction.description}</p><div className="auction-detail-list"><span><MapPin size={16} /><b>Venue</b>{auction.venue}</span><span><Gavel size={16} /><b>Auctioneer</b>{auction.auctioneer}</span><span><Landmark size={16} /><b>Deposit</b>{auction.deposit}</span><span><FileCheck2 size={16} /><b>Documents</b>{auction.documents}</span></div></article><aside className="auction-detail-card auction-detail-summary"><span className="md-eyebrow">AUCTION SNAPSHOT</span><div><small>Guide price</small><strong>{auction.guidePrice}</strong></div><div><small>Opening bid</small><strong>{auction.openingBid}</strong></div><div><small>Property views</small><strong>{auction.viewings}</strong></div><div><small>Registered bidders</small><strong>{auction.bidders}</strong></div></aside></section>
  </div>
}

function LaunchForm({ onClose, onCreate }) {
  const [values, setValues] = useState({ title: '', development: '', location: '', date: '', time: '10:00 – 13:00', status: 'Planning' })
  const update = (field) => (event) => setValues((current) => ({ ...current, [field]: event.target.value }))
  const submit = async (event) => { event.preventDefault(); if (!values.title.trim() || !values.date) return; await onCreate({ ...values, startDate: values.date, startTime: values.time.split('–')[0].trim(), title: values.title.trim(), date: formatEventDate(values.date), readiness: 'In progress', invited: '0', registrations: '0', attending: '0', leads: '0', image: launchImage }); onClose() }
  return <section className="marketing-event-form" aria-label="Create launch"><div><div><span>New event</span><h2>Create launch</h2><p>Plan the development event, then track invitations, RSVPs and qualified leads here.</p></div><button className="wa-more" type="button" aria-label="Close launch form" onClick={onClose}><X size={18} /></button></div><form onSubmit={submit}><label>Launch name<input required value={values.title} onChange={update('title')} placeholder="e.g. Parkside Residences launch" /></label><label>Development<input required value={values.development} onChange={update('development')} placeholder="Development name" /></label><label>Location<input required value={values.location} onChange={update('location')} placeholder="City or venue" /></label><label>Date<input required type="date" value={values.date} onChange={update('date')} /></label><label>Time<input value={values.time} onChange={update('time')} /></label><label>Status<select value={values.status} onChange={update('status')}><option>Planning</option><option>Upcoming</option></select></label><footer><button type="button" className="wa-secondary-button" onClick={onClose}>Cancel</button><button className="wa-primary-button" type="submit">Save launch <ChevronRight size={16} /></button></footer></form></section>
}

function LaunchWorkspaceFilters({ query, onQuery, status, onStatus }) { return <section className="wa-filter-row"><label className="wa-search"><Search size={17} /><span className="sr-only">Search launches</span><input type="search" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search launches..." /></label><label className="wa-filter-control"><span className="sr-only">Filter launches by status</span><select value={status} onChange={(event) => onStatus(event.target.value)}><option value="All">All statuses</option><option>Upcoming</option><option>Planning</option><option>Completed</option></select><ChevronDown size={15} /></label><span className="wa-filter-control"><CalendarDays size={16} /> Local event plan</span></section> }

export function LaunchesOverview() {
  const { organisation } = useOrganisation()
  const organisationId = organisation?.organisationId || organisation?.id || ''
  const { events, createEvent } = useMarketingEvents('launches', seededLaunches, { organisationId })
  const [activeTab, setActiveTab] = useState(launchTabs[0]); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [creating, setCreating] = useState(false)
  const visible = useMemo(() => events.filter((event) => (activeTab === 'All Launches' || event.status === activeTab) && (status === 'All' || event.status === status) && `${event.title} ${event.development} ${event.location}`.toLowerCase().includes(query.toLowerCase())), [activeTab, events, query, status])
  const stats = [{ id: 'upcoming', label: 'Upcoming Launches', value: String(events.filter((event) => event.status === 'Upcoming').length), detail: 'In your local plan' }, { id: 'invited', label: 'Invited', value: String(events.reduce((total, event) => total + Number(event.invited || 0), 0)), detail: 'Across active launches' }, { id: 'registrations', label: 'Registrations', value: String(events.reduce((total, event) => total + Number(event.registrations || 0), 0)), detail: 'Across active launches' }, { id: 'leads', label: 'Qualified Leads', value: String(events.reduce((total, event) => total + Number(event.leads || 0), 0)), detail: 'Tracked locally' }]
  return <div className="wa-page launches-page"><OverviewStats stats={stats} label="Launch performance" /><section className="wa-campaigns-panel"><div className="wa-panel-toolbar"><div className="wa-tabs" role="tablist">{launchTabs.map((tab) => <button className={activeTab === tab ? 'wa-tab-active' : ''} type="button" role="tab" aria-selected={activeTab === tab} onClick={() => setActiveTab(tab)} key={tab}>{tab}</button>)}</div><button className="wa-primary-button" type="button" onClick={() => setCreating(true)}>Create Launch <ChevronRight size={16} /></button></div><div className="wa-campaigns-content"><LaunchWorkspaceFilters query={query} onQuery={setQuery} status={status} onStatus={setStatus} />{creating ? <LaunchForm onClose={() => setCreating(false)} onCreate={createEvent} /> : null}<div className="wa-campaign-list">{visible.length ? visible.map((launch) => <LaunchCard launch={launch} key={launch.id} />) : <p className="marketing-event-empty">No launches match these filters.</p>}</div><footer className="wa-list-footer"><span>Showing {visible.length} of {events.length} launches</span></footer></div></section></div>
}

export function AuctionsOverview() {
  const [activeTab, setActiveTab] = useState(auctionTabs[0])
  const [auctionId, setAuctionId] = useState('')
  const selectedAuction = auctions.find((auction) => auction.id === auctionId)
  const visible = auctions.filter((auction) => activeTab === 'All Auctions' || auction.status.toLowerCase() === activeTab.toLowerCase())
  const stats = [
    { id: 'active', label: 'Active Auctions', value: String(auctions.filter((auction) => auction.status === 'Bidding open').length), detail: 'Bidding open now' },
    { id: 'bidders', label: 'Registered Bidders', value: String(auctions.reduce((total, auction) => total + Number(auction.bidders || 0), 0)), detail: 'Across current lots' },
    { id: 'lots', label: 'Upcoming Lots', value: String(auctions.filter((auction) => ['Bidding open', 'Upcoming'].includes(auction.status)).length), detail: 'Next 30 days' },
    { id: 'clearance', label: 'Clearance Rate', value: '82%', detail: 'Last 90 days' },
  ]
  if (selectedAuction) return <AuctionDetail auction={selectedAuction} onBack={() => setAuctionId('')} />
  return <div className="wa-page auctions-page"><OverviewStats stats={stats} label="Auction performance" /><section className="wa-campaigns-panel"><div className="wa-panel-toolbar"><div className="wa-tabs" role="tablist">{auctionTabs.map((tab) => <button className={activeTab === tab ? 'wa-tab-active' : ''} type="button" role="tab" aria-selected={activeTab === tab} onClick={() => setActiveTab(tab)} key={tab}>{tab}</button>)}</div></div><div className="wa-campaigns-content"><div className="wa-campaign-list">{visible.length ? visible.map((auction) => <AuctionCard auction={auction} onOpen={setAuctionId} key={auction.id} />) : <p className="marketing-event-empty">No auctions match this view.</p>}</div></div></section></div>
}
