import { FileText, History, Loader2, Plus } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { createRentalDocumentLink, listRentalActivityProjections, listRentalDocumentLinks } from '../../../../services/rentals/rentalEvidenceRepository.js'

const initialForm = { documentId: '', documentLabel: '', documentCategory: '' }
export function RentalPropertyEvidencePanel({ property = {}, userId = '' }) {
  const [documents, setDocuments] = useState([]); const [activities, setActivities] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState(initialForm)
  const load = useCallback(async () => { if (!property.id) return; try { setLoading(true); setError(''); const [nextDocuments, nextActivities] = await Promise.all([listRentalDocumentLinks({ propertyId: property.id }), listRentalActivityProjections({ propertyId: property.id })]); setDocuments(nextDocuments); setActivities(nextActivities) } catch (cause) { setError(cause?.message || 'Unable to load shared evidence.') } finally { setLoading(false) } }, [property.id])
  useEffect(() => { void load() }, [load])
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); await createRentalDocumentLink({ ...form, organisationId: property.organisationId, propertyId: property.id, branchId: property.branchId, entityType: 'rental_property', entityId: property.id, createdBy: userId }); setForm(initialForm); await load() } catch (cause) { setError(cause?.message || 'Unable to link canonical document.') } finally { setSaving(false) } }
  return <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><FileText className="mt-1 h-5 w-5 text-sky-700"/><div><h2 className="font-semibold text-slate-900">Documents & activity</h2><p className="text-sm text-slate-600">Links point to Arch9 canonical documents; activity is an immutable projection of Rental events.</p></div></div>{loading ? <Loader2 className="mx-auto mt-6 h-5 w-5 animate-spin"/> : <><form onSubmit={submit} className="mt-4 grid gap-2 md:grid-cols-4"><input required value={form.documentId} onChange={(event) => setForm((current) => ({ ...current, documentId: event.target.value }))} placeholder="Canonical document ID" className="rounded-lg border px-3 py-2 text-sm"/><input value={form.documentLabel} onChange={(event) => setForm((current) => ({ ...current, documentLabel: event.target.value }))} placeholder="Label" className="rounded-lg border px-3 py-2 text-sm"/><input value={form.documentCategory} onChange={(event) => setForm((current) => ({ ...current, documentCategory: event.target.value }))} placeholder="Category" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={saving} className="inline-flex items-center justify-center gap-1 rounded-lg bg-sky-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin"/> : <Plus className="h-4 w-4"/>}Link document</button></form><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="font-medium text-slate-900">Linked documents</h3><ul className="mt-2 space-y-2">{documents.length ? documents.map((document) => <li key={document.id} className="rounded-lg border bg-slate-50 p-3 text-sm"><p className="font-medium">{document.documentLabel || document.documentId}</p><p className="text-xs text-slate-600">{document.documentCategory || 'General'} · {document.linkState}</p></li>) : <li className="text-sm text-slate-500">No documents linked.</li>}</ul></div><div><h3 className="flex items-center gap-2 font-medium text-slate-900"><History className="h-4 w-4"/>Activity</h3><ul className="mt-2 space-y-2">{activities.length ? activities.map((activity) => <li key={activity.id} className="rounded-lg border bg-slate-50 p-3 text-sm"><p className="font-medium">{activity.title}</p>{activity.description && <p className="mt-1 text-slate-600">{activity.description}</p>}</li>) : <li className="text-sm text-slate-500">No projected Rental activity yet.</li>}</ul></div></div></>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}</section>
}
