import { useEffect, useState } from 'react'
import { getRentalApplicationTenancyConversion, linkRentalLeaseVersionDocument, listRentalLeaseVersions, saveRentalLeaseDraft } from '../../../../services/rentals/rentalApplicationRepository.js'

const blank = { lease_start_date: '', lease_end_date: '', occupation_date: '', monthly_rent: '', deposit_amount: '', escalation_percent: '' }
const toForm = (version) => ({ lease_start_date: version?.terms_json?.lease_start_date || version?.effective_start_date || '', lease_end_date: version?.terms_json?.lease_end_date || version?.effective_end_date || '', occupation_date: version?.terms_json?.occupation_date || version?.occupation_date || '', monthly_rent: version?.monthly_rent ?? '', deposit_amount: version?.deposit_amount ?? '', escalation_percent: version?.escalation_json?.percent ?? '' })

export default function RentalLeaseVersionPanel({ application }) {
  const [leaseId, setLeaseId] = useState(''); const [versions, setVersions] = useState([]); const [form, setForm] = useState(blank); const [documentLabel, setDocumentLabel] = useState(''); const [documentLink, setDocumentLink] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = async () => { if (!application?.id) return; try { const conversion = await getRentalApplicationTenancyConversion(application.id); const id = conversion?.rental_leases?.id; setLeaseId(id || ''); if (!id) { setVersions([]); return }; const next = await listRentalLeaseVersions(id); setVersions(next); setForm(toForm(next.find((item) => item.is_current) || next[0])) } catch (cause) { setError(cause.message) } }
  useEffect(() => { setError(''); void load() }, [application])
  const current = versions.find((item) => item.is_current)
  const set = (key, value) => setForm((valueSet) => ({ ...valueSet, [key]: value }))
  const save = async (event) => { event.preventDefault(); if (!current) return; try { setSaving(true); setError(''); await saveRentalLeaseDraft({ leaseId, expectedVersion: current.version_number, terms: { lease_start_date: form.lease_start_date, lease_end_date: form.lease_end_date, occupation_date: form.occupation_date, monthly_rent: form.monthly_rent, deposit_amount: form.deposit_amount, escalation: form.escalation_percent ? { percent: Number(form.escalation_percent) } : {} } }); await load() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  const linkDocument = async (event) => { event.preventDefault(); if (!current) return; try { setSaving(true); setError(''); await linkRentalLeaseVersionDocument({ leaseVersionId: current.id, label: documentLabel, link: documentLink }); setDocumentLabel(''); setDocumentLink(''); await load() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  if (application?.status !== 'approved' || !leaseId) return null
  return <section className="mt-5 border-t pt-5"><h3 className="font-semibold">Lease versions</h3><p className="mt-1 text-sm text-slate-600">The current draft is editable. Each save creates an auditable new version.</p>{current ? <form onSubmit={save} className="mt-3 grid gap-3 rounded-lg bg-slate-50 p-3"><div className="grid gap-3 sm:grid-cols-2">{[['lease_start_date', 'Lease start'], ['lease_end_date', 'Lease end'], ['occupation_date', 'Occupation date']].map(([key, label]) => <label key={key} className="text-sm font-medium">{label}<input required type="date" value={form[key]} onChange={(event) => set(key, event.target.value)} className="mt-1 block w-full rounded border p-2" /></label>)}<label className="text-sm font-medium">Monthly rent<input required min="0.01" step="0.01" type="number" value={form.monthly_rent} onChange={(event) => set('monthly_rent', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label className="text-sm font-medium">Deposit<input required min="0" step="0.01" type="number" value={form.deposit_amount} onChange={(event) => set('deposit_amount', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label className="text-sm font-medium">Escalation % (optional)<input min="0" step="0.01" type="number" value={form.escalation_percent} onChange={(event) => set('escalation_percent', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label></div><button disabled={saving || current.status !== 'draft'} className="w-fit rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save new lease version'}</button></form> : <p className="mt-3 text-sm text-slate-600">Lease version is loading.</p>}<div className="mt-4"><h4 className="text-sm font-semibold">Document links</h4>{current?.rental_lease_version_documents?.map((document) => <a key={document.id} href={document.document_link} target="_blank" rel="noreferrer" className="mt-1 block text-sm text-sky-700 underline">{document.document_label}</a>)}{current ? <form onSubmit={linkDocument} className="mt-2 flex flex-col gap-2 sm:flex-row"><input required value={documentLabel} onChange={(event) => setDocumentLabel(event.target.value)} placeholder="Document label" className="rounded border p-2 text-sm" /><input required value={documentLink} onChange={(event) => setDocumentLink(event.target.value)} placeholder="Secure document URL" className="flex-1 rounded border p-2 text-sm" /><button disabled={saving} className="rounded border px-3 py-2 text-sm">Link document</button></form> : null}</div>{versions.length ? <div className="mt-4"><h4 className="text-sm font-semibold">Version history</h4>{versions.map((version) => <p key={version.id} className="mt-1 text-sm">v{version.version_number} · {version.status}{version.is_current ? ' · current' : ''}</p>)}</div> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}</section>
}
