import { useEffect, useState } from 'react'
import { getRentalApplicationTenancyConversion, listRentalLeaseSigners, listRentalLeaseVersions, prepareRentalLeaseSigning, recordRentalLeaseSignature, reopenRentalLeaseSigner } from '../../../../services/rentals/rentalApplicationRepository.js'

const initialSigners = { tenantName: '', tenantEmail: '', landlordName: '', landlordEmail: '' }

export default function RentalLeaseSigningPanel({ application }) {
  const [leaseId, setLeaseId] = useState(''); const [current, setCurrent] = useState(null); const [signers, setSigners] = useState([]); const [form, setForm] = useState(initialSigners); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = async () => { if (!application?.id) return; try { const conversion = await getRentalApplicationTenancyConversion(application.id); const id = conversion?.rental_leases?.id; setLeaseId(id || ''); if (!id) return; const versions = await listRentalLeaseVersions(id); const version = versions.find((item) => item.is_current); setCurrent(version || null); if (!version) return; const nextSigners = await listRentalLeaseSigners(version.id); setSigners(nextSigners); setForm((value) => ({ ...value, tenantName: value.tenantName || `${application?.data?.identity?.firstName || ''} ${application?.data?.identity?.lastName || ''}`.trim(), tenantEmail: value.tenantEmail || application?.data?.identity?.email || '' })) } catch (cause) { setError(cause.message) } }
  useEffect(() => { setError(''); void load() }, [application])
  const set = (key, value) => setForm((currentForm) => ({ ...currentForm, [key]: value }))
  const prepare = async (event) => { event.preventDefault(); if (!current) return; try { setSaving(true); setError(''); await prepareRentalLeaseSigning({ leaseId, expectedVersion: current.version_number, signers: [{ role: 'tenant', name: form.tenantName, email: form.tenantEmail }, { role: 'landlord', name: form.landlordName, email: form.landlordEmail }] }); await load() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  const record = async (signer, outcome) => { const documentLink = outcome === 'signed' ? window.prompt('Signed document link (required):', signer.signed_document_link || '') : ''; if (outcome === 'signed' && !documentLink) return; const evidenceNote = window.prompt('Evidence note (optional):', signer.evidence_note || '') || ''; try { setSaving(true); setError(''); await recordRentalLeaseSignature({ signerId: signer.id, outcome, documentLink, evidenceNote }); await load() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  const reopen = async (signer) => { const reason = window.prompt('Reason for reopening this signer:'); if (!reason) return; try { setSaving(true); setError(''); await reopenRentalLeaseSigner({ signerId: signer.id, reason }); await load() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  if (application?.status !== 'approved' || !leaseId || !current) return null
  return <section className="mt-5 border-t pt-5"><h3 className="font-semibold">Manual lease signing</h3><p className="mt-1 text-sm text-slate-600">No external signing provider is connected. Record the signed evidence against this exact lease version.</p>{signers.length === 0 ? <form onSubmit={prepare} className="mt-3 grid gap-3 rounded-lg bg-slate-50 p-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Tenant signer<input required value={form.tenantName} onChange={(event) => set('tenantName', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label className="text-sm font-medium">Tenant email<input type="email" value={form.tenantEmail} onChange={(event) => set('tenantEmail', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label className="text-sm font-medium">Landlord signer<input required value={form.landlordName} onChange={(event) => set('landlordName', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label className="text-sm font-medium">Landlord email<input type="email" value={form.landlordEmail} onChange={(event) => set('landlordEmail', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label></div><button disabled={saving} className="w-fit rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Preparing…' : 'Prepare manual signing'}</button></form> : <div className="mt-3 space-y-2">{signers.map((signer) => <div key={signer.id} className="rounded-lg border p-3 text-sm"><b>{signer.signer_role}: {signer.signer_name}</b><p className="mt-1 text-slate-600">{signer.status}{signer.signed_at ? ` · ${new Date(signer.signed_at).toLocaleString()}` : ''}</p>{signer.signed_document_link ? <a href={signer.signed_document_link} target="_blank" rel="noreferrer" className="mt-1 block text-sky-700 underline">Signed evidence</a> : null}{signer.status === 'pending' ? <div className="mt-2 flex gap-2"><button type="button" disabled={saving} onClick={() => void record(signer, 'signed')} className="rounded border px-2 py-1">Record signed</button><button type="button" disabled={saving} onClick={() => void record(signer, 'declined')} className="rounded border px-2 py-1">Record declined</button></div> : signer.status === 'declined' ? <button type="button" disabled={saving} onClick={() => void reopen(signer)} className="mt-2 rounded border px-2 py-1">Reopen signer</button> : null}</div>)}</div>}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}</section>
}
