import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { activateRentalTenancy, getRentalApplicationTenancyConversion, getRentalIncomingInspection, getRentalTenancyActivationEvent, listRentalMoveInReadiness } from '../../../../services/rentals/rentalApplicationRepository.js'

const title = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

export default function RentalTenancyActivationPanel({ application, onActivated }) {
  const [tenancy, setTenancy] = useState(null); const [lease, setLease] = useState(null); const [readiness, setReadiness] = useState([]); const [inspection, setInspection] = useState(null); const [activation, setActivation] = useState(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = async () => { if (!application?.id) return; try { const conversion = await getRentalApplicationTenancyConversion(application.id); const nextLease = conversion?.rental_leases || null; setTenancy(conversion || null); setLease(nextLease); if (!conversion?.id || !nextLease?.id) { setReadiness([]); setInspection(null); setActivation(null); return }; const [items, nextInspection, nextActivation] = await Promise.all([listRentalMoveInReadiness(nextLease.id), getRentalIncomingInspection(conversion.id), getRentalTenancyActivationEvent(conversion.id)]); setReadiness(items); setInspection(nextInspection); setActivation(nextActivation) } catch (cause) { setError(cause.message) } }
  useEffect(() => { setError(''); setMessage(''); void load() }, [application])
  const completeReadiness = readiness.length > 0 && readiness.every((item) => ['verified', 'waived'].includes(item.status))
  const completeInspection = inspection?.status === 'completed'
  const activate = async () => { try { setSaving(true); setError(''); const result = await activateRentalTenancy(tenancy.id); setMessage(result.idempotent ? 'This tenancy is already active.' : 'Tenancy activated. The unit is now occupied and the vacancy is closed.'); await load(); await onActivated?.() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  if (application?.status !== 'approved' || !tenancy || !lease) return null
  const isActive = tenancy.status === 'active'
  return <section className="mt-5 border-t pt-5"><h3 className="font-semibold">Tenancy activation</h3><p className="mt-1 text-sm text-slate-600">This is the final controlled move-in command. It changes the tenancy, lease, unit, vacancy and internal marketing state together.</p><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p className={`rounded-lg p-3 ${lease.status === 'signed' || lease.status === 'active' ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}>Lease: <b>{title(lease.status)}</b></p><p className={`rounded-lg p-3 ${completeReadiness ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}>Readiness: <b>{completeReadiness ? 'Complete' : 'Outstanding'}</b></p><p className={`rounded-lg p-3 ${completeInspection ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}>Handover: <b>{completeInspection ? 'Complete' : 'Outstanding'}</b></p></div>{isActive ? <div className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">Active since {activation?.activated_at ? new Date(activation.activated_at).toLocaleString() : 'activation'}. <Link to={`/agent/rentals/tenancies/${tenancy.id}`} className="font-semibold underline">Open tenancy workspace</Link></div> : <button type="button" disabled={saving} onClick={() => void activate()} className="mt-4 rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Activating…' : 'Activate tenancy and occupy unit'}</button>}{message ? <p className="mt-3 text-sm text-emerald-700">{message}</p> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}</section>
}
