import { useRef, useState } from 'react'
import { useWorkspace } from '../../../../context/WorkspaceContext'
import { resolveRentalWorkspaceScope } from '../../../../services/rentals/rentalWorkspaceScope.js'
import { createPersistedRentalApplicantAccess, revokePersistedRentalApplicantAccess } from '../../../../services/rentals/rentalApplicationRepository.js'
import Button from '../../../../components/ui/Button.jsx'
export default function RentalApplicationCollectionLink({ application }) {
  const workspace = useWorkspace()
  const guard = useRef(false)
  const [subjectId, setSubjectId] = useState('')
  const [access, setAccess] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  if (!['submitted', 'under_review'].includes(application.status)) return null
  const run = async (action) => { if (guard.current) return; guard.current = true; setBusy(true); setError(''); setNotice(''); try { await action() } catch (cause) { setError(cause.message) } finally { guard.current = false; setBusy(false) } }
  const create = () => run(async () => { const result = await createPersistedRentalApplicantAccess(application.id, { createdBy: resolveRentalWorkspaceScope(workspace).assignedAgentId, ...(subjectId ? { subjectId } : {}) }); setAccess({ ...result, url: `${window.location.origin}/rental-application/${result.token}` }) })
  return <section className="mt-4 space-y-3 rounded-xl border bg-slate-50 p-4"><h3 className="font-semibold">Collect outstanding documents</h3><p className="text-sm text-slate-600">The applicant can keep using their original link while it is valid. Create a new link if they need more time; their submitted answers stay locked.</p><label className="block text-sm">Link recipient<select aria-label="Link recipient" disabled={busy} value={subjectId} onChange={(event) => { setSubjectId(event.target.value); setAccess(null); setNotice('') }} className="ml-3 rounded-lg border p-2"><option value="">Primary applicant — complete application</option>{(application.data?.people || []).map((person) => <option key={person.id} value={person.id}>{person.firstName} {person.lastName} — own documents and permissions</option>)}</select></label>{access ? <><label className="block text-sm">Document upload link<input readOnly value={access.url} className="mt-1 w-full rounded-lg border bg-white p-2" /></label><p className="text-xs text-slate-500">Expires {new Date(access.expiresAt).toLocaleString('en-ZA')}. Existing links keep their current expiry.</p><div className="flex gap-2"><Button disabled={busy} onClick={() => void run(async () => { await navigator.clipboard.writeText(access.url); setNotice('Link copied. Share it with the applicant.') })}>Copy upload link</Button><Button variant="secondary" disabled={busy} onClick={() => void run(async () => { await revokePersistedRentalApplicantAccess(access.id); setAccess(null); setNotice('This upload link has been revoked.') })}>Revoke this link</Button></div></> : <Button disabled={busy} onClick={() => void create()}>Create document upload link</Button>}{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}{notice ? <p role="status" className="text-sm text-emerald-700">{notice}</p> : null}</section>
}
