import { getDocumentUploadPolicy } from '../../../../lib/documentUploadPolicy.js'
import { rentalDocumentGuidance } from '../../../../services/rentals/rentalApplicationDocumentGuidance.js'
import { useState } from 'react'
import { Upload } from 'lucide-react'
import { DOCUMENT_UPLOAD_ACCEPT } from '../../../../lib/documentUploadPolicy.js'
import { rentalApplicationSavedDocumentSlots, rentalApplicationDocumentForSlot, rentalApplicationDocumentsForSlot } from '../../../../services/rentals/rentalApplicationWizardModel.js'
const documentUploadPolicy = getDocumentUploadPolicy({ surface: 'rental_application' })

export default function RentalApplicationDocuments({ data, documents = [], requirements, preview = false, afterSubmission = false, onUpload, onUploadMany, onOpen, disabled = false }) {
  const [openedAt] = useState(() => Date.now())
  return <div className="space-y-3"><p className="text-sm text-[#60758b]">Upload evidence for the named person or entity. PDF, Word, JPG or PNG; up to 8 MB. You can submit your details before these documents are ready and return using the same link. You can select several files for one requirement, such as monthly bank statements. All files in a required pack must be accepted before approval. Selecting a new pack replaces the current pack; previous files remain in the history.</p>{preview ? <p role="status" className="text-sm text-amber-800">Document preview: save your answers to update the checklist. Selecting a file saves first.</p> : requirements !== undefined && !requirements?.length ? <p className="text-sm text-amber-800">Save this draft to prepare its document checklist.</p> : null}{rentalApplicationSavedDocumentSlots(data, requirements, preview ? { version: 4 } : undefined).map((slot) => {
    const document = preview ? undefined : rentalApplicationDocumentForSlot(slot, documents, data)
    const pack = preview ? [] : rentalApplicationDocumentsForSlot(slot, documents, data)
    const accepted = afterSubmission && slot.state === 'accepted' && (!slot.expiresAt || Date.parse(slot.expiresAt) > openedAt)
  return <div key={slot.key} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#dce7f2] p-4"><div className="min-w-0"><p className="font-semibold text-[#29435d]">{slot.title} {slot.required ? <span className="text-xs font-normal text-[#8a641d]">Required for approval</span> : null}</p><p className="mt-2 max-w-xl text-xs text-slate-600">{rentalDocumentGuidance[slot.purpose]}</p><p className="mt-1 break-all text-xs text-[#60758b]">{document ? `${document.file_name || document.fileName || document.name} · ${slot.saved ? slot.state : document.status}` : slot.state === 'accepted' ? 'Permission recorded' : 'Not uploaded'}</p>{pack.map((item) => <div key={item.id} className="mt-2 text-xs"><span>{item.file_name || item.name} · {item.status}</span>{onOpen ? <button type="button" disabled={disabled} className="ml-3 underline" onClick={() => void onOpen(item)}>Open {item.file_name || item.name}</button> : null}</div>)}{slot.purpose === 'signed_consent' && slot.state === 'accepted' && !document ? <p className="mt-2 text-xs text-emerald-700">Personal permission recorded.</p> : null}</div>{accepted ? <span className="text-sm font-semibold text-emerald-700">Accepted — contact your agent for corrections</span> : onUpload ? <><label className={`inline-flex cursor-pointer items-center gap-2 rounded-lg border border-[#dce7f2] bg-white px-3 py-2 text-sm font-semibold text-[#315b7a] ${disabled ? 'opacity-50' : ''}`}><Upload size={15} />{document ? 'Replace' : 'Upload'}<input aria-label={`Upload ${slot.title}`} type="file" title={documentUploadPolicy.helpText} multiple={Boolean(onUploadMany)} accept={documentUploadPolicy.accept} disabled={disabled} className="sr-only" onChange={(event) => { const files = Array.from(event.target.files || []); event.target.value = ''; if (files.length) { if (onUploadMany) void onUploadMany(files, slot); else void onUpload(files[0], slot) } }} />
  </label>
<span className="block text-xs font-normal text-slate-500">{documentUploadPolicy.helpText}</span></> : null}</div>
  })}</div>
}
