import { createElement, useState } from 'react'
import { Building2, Landmark, UserRound, Users, BriefcaseBusiness, Plus, Trash2, CheckCircle2 } from 'lucide-react'
import Button from '../../../../components/ui/Button'
import { RENTAL_APPLICATION_FIELD_GROUPS, RENTAL_APPLICATION_SETUP_STEPS, RENTAL_APPLICANT_ROLES, RENTAL_EMPLOYMENT_TYPES } from '../../../../services/rentals/rentalApplicationFieldContract.js'
import { isRentalEntityApplicant, rentalApplicationPersonFields, rentalApplicationVisibleFields, rentalApplicationReviewErrors, updateRentalApplicationGroup } from '../../../../services/rentals/rentalApplicationWizardModel.js'
const label = (value) => ({ sa_id: 'SA ID', whatsapp: 'WhatsApp', co_tenant: 'Co-tenant', self_employed: 'Self-employed', contract: 'Contract / freelance' })[value] || String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const entities = [['individual', 'Individual', UserRound], ['joint_individuals', 'Joint tenants', Users], ['company', 'Company', Building2], ['close_corporation', 'Close corporation', BriefcaseBusiness], ['trust', 'Trust', Landmark]]
const choices = { employmentType: RENTAL_EMPLOYMENT_TYPES, role: RENTAL_APPLICANT_ROLES, identityType: ['sa_id', 'passport'], preferredContactMethod: ['email', 'phone', 'whatsapp'], housingSituation: ['renting', 'living_with_family', 'owner', 'other'], primaryContactRole: ['authorised_signatory', 'trustee', 'contact_only'] }
function ValueField({ field, value, onChange, disabled, prefix = '' }) {
  const id = `${prefix}${field.key}`
  if (field.type === 'boolean' || field.key === 'pets') return <fieldset className="min-w-0"><legend className="mb-2 text-sm font-medium text-[#29435d]">{field.label}</legend><div className="flex gap-2">{[true, false].map((answer) => {
    const selected = field.key === 'pets' ? value === (answer ? 'yes' : 'no') : value === answer
    return <button key={String(answer)} type="button" data-rental-control="application-answer" aria-label={`${field.label}: ${answer ? 'Yes' : 'No'}`} aria-pressed={selected} disabled={disabled} onClick={() => onChange(field.key === 'pets' ? answer ? 'yes' : 'no' : answer)} className={`min-w-20 rounded-xl border px-4 py-2 text-sm font-semibold ${selected ? 'border-[#102d4a] bg-[#102d4a] text-white' : 'border-[#dce7f2] bg-white text-[#526b83]'} disabled:opacity-60`}>{answer ? 'Yes' : 'No'}</button>
  })}</div></fieldset>
  const options = choices[field.key]
  return <label className="form-field" htmlFor={id}><span>{field.label}</span>{options ? <select id={id} value={value ?? ''} disabled={disabled} onChange={(event) => onChange(event.target.value)}><option value="">Choose {field.label.toLowerCase()}</option>{options.map((option) => <option key={option} value={option}>{label(option)}</option>)}{value && !options.includes(value) ? <option value={value}>{value}</option> : null}</select> : <input id={id} type={field.type} min={field.type === 'number' ? 0 : undefined} step={['occupantCount', 'leasePeriodMonths'].includes(field.key) ? 1 : 'any'} value={value ?? ''} disabled={disabled} onChange={(event) => onChange(event.target.value)} />}</label>
}
export default function RentalApplicationWizard({ data, onChange, onSave, busy = false, readOnly = false, documentsContent, declarationsContent, agent = false }) {
  const [step, setStep] = useState(0)
  const selected = RENTAL_APPLICATION_SETUP_STEPS[step]
  const disabled = readOnly || busy
  const update = (group, key, value) => onChange(updateRentalApplicationGroup(data, group, key, value))
  const reviewErrors = rentalApplicationReviewErrors(data)
  const collection = (group) => {
    const values = Array.isArray(data[group.key]) ? data[group.key] : []
    const add = () => onChange({ ...data, [group.key]: [...values, { id: crypto.randomUUID(), ...(group.key === 'people' ? { role: data.entity?.type === 'joint_individuals' ? 'co_tenant' : 'guarantor' } : {}) }] })
    return <section key={group.key} className="mt-5 rounded-2xl border border-[#e1eaf3] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold text-[#203a54]">{group.title}</h3>{!readOnly ? <Button type="button" variant="secondary" size="sm" disabled={busy} onClick={add}><Plus size={15} />Add {group.key === 'people' ? 'person' : 'reference'}</Button> : null}</div>{values.length === 0 ? <p className="mt-3 text-sm text-[#60758b]">{group.key === 'people' ? 'Add joint tenants, representatives or guarantors when applicable.' : 'Add supporting references when available.'}</p> : values.map((person, index) => <details key={person.id || index} open className="mt-4 rounded-xl bg-[#f8fbfe] p-4"><summary className="cursor-pointer font-semibold text-[#29435d]">{[person.firstName, person.lastName].filter(Boolean).join(' ') || person.name || `${group.key === 'people' ? 'Person' : 'Reference'} ${index + 1}`}{person.role ? ` · ${label(person.role)}` : ''}</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{(group.key === 'people' ? rentalApplicationPersonFields(group, person) : group.fields.filter((field) => field.key !== 'id')).map((field) => <ValueField key={field.key} field={field.key === 'type' ? { ...field, label: 'Reference type' } : field} prefix={`${group.key}-${index}-`} value={person[field.key]} disabled={disabled} onChange={(value) => onChange({ ...data, [group.key]: values.map((record, itemIndex) => itemIndex === index ? { ...record, [field.key]: value } : record) })} />)}</div>{!readOnly ? <button type="button" aria-label={`Remove ${group.key === 'people' ? 'person' : 'reference'} ${index + 1}`} disabled={busy} onClick={() => onChange({ ...data, [group.key]: values.filter((_, itemIndex) => itemIndex !== index) })} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[#a53b36]"><Trash2 size={14} />Remove</button> : null}</details>)}</section>
  }
  async function next() { if (!readOnly && onSave && await onSave() === false) return; setStep((current) => Math.min(current + 1, 7)) }
  return <div className="grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)]">
    <nav aria-label="Tenant application sections" className="grid grid-cols-2 content-start gap-2 lg:grid-cols-1">{RENTAL_APPLICATION_SETUP_STEPS.map((item, index) => <button key={item.key} type="button" data-rental-control="application-step" disabled={busy} aria-current={index === step ? 'step' : undefined} onClick={() => setStep(index)} className={`flex min-w-0 items-center gap-3 rounded-xl border p-3 text-left text-sm font-semibold ${index === step ? 'border-[#102d4a] bg-[#102d4a] text-white' : 'border-[#e3edf5] bg-[#f8fbfe] text-[#526b83]'}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full text-xs ${index === step ? 'bg-white/15' : 'bg-[#eaf2fa]'}`}>{index + 1}</span>{item.title}</button>)}</nav>
    <div className="min-w-0 rounded-2xl border border-[#e1eaf3] bg-white p-4 sm:p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#7890a6]">Step {step + 1} of 8</p><h3 className="mt-1 text-xl font-semibold text-[#102033]">{selected.title}</h3>
      {selected.key === 'entity' ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{entities.map(([type, title, Icon]) => <button key={type} type="button" data-rental-control="tenant-entity" disabled={disabled} aria-pressed={data.entity?.type === type} onClick={() => update('entity', 'type', type)} className={`flex items-center gap-3 rounded-xl border p-4 text-left text-sm font-semibold ${data.entity?.type === type ? 'border-[#102d4a] bg-[#edf4fa] text-[#102d4a]' : 'border-[#e1eaf3] text-[#526b83]'}`}>{createElement(Icon, { size: 20 })}{title}</button>)}</div> : null}
      {selected.groups.map((key) => {
        const group = RENTAL_APPLICATION_FIELD_GROUPS.find((item) => item.key === key)
        if (group.collection) return collection(group)
        if (group.readOnly) return <section key={key} className="mt-5 rounded-xl bg-[#f5f9fd] p-4"><h4 className="font-semibold text-[#29435d]">{data.property?.title || data.property?.address || 'Selected rental property'}</h4>{data.property?.address && data.property.address !== data.property.title ? <p className="mt-1 text-sm text-[#60758b]">{data.property.address}</p> : null}<p className="mt-2 text-sm text-[#60758b]">{data.property?.monthlyRent ? `R ${Number(data.property.monthlyRent).toLocaleString('en-ZA')} per month` : 'Rent to be confirmed'}</p>{data.property?.depositAmount != null ? <p className="mt-1 text-sm text-[#60758b]">Deposit: R {Number(data.property.depositAmount).toLocaleString('en-ZA')}</p> : null}</section>
        const fields = rentalApplicationVisibleFields(group, data).filter((field) => !(key === 'entity' && field.key === 'type'))
        if (fields.length === 0) return key === 'employment' && isRentalEntityApplicant(data) ? <p key={key} className="mt-4 text-sm text-[#60758b]">Capture the entity’s income on the Affordability step. Individual representatives can add their own details under People & contacts.</p> : null
        return <section key={key} className="mt-5">{key !== 'entity' ? <h4 className="mb-3 text-sm font-semibold text-[#29435d]">{group.title}</h4> : null}<div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <ValueField key={field.key} field={field} prefix={`${key}-`} value={data[key]?.[field.key]} disabled={disabled} onChange={(value) => update(key, field.key, value)} />)}</div></section>
      })}
      {selected.key === 'documents' ? <div className="mt-5">{documentsContent}</div> : null}
      {selected.key === 'review' ? <div className="mt-5 space-y-4">{reviewErrors.length ? <div className="rounded-xl bg-[#fff9ec] p-4 text-sm text-[#8a641d]"><p className="font-semibold">Complete these details</p><ul className="mt-2 list-disc space-y-1 pl-4">{reviewErrors.map((error) => <li key={error}>{error}</li>)}</ul></div> : <p className="flex items-center gap-2 rounded-xl bg-[#effaf3] p-4 text-sm text-[#26724c]"><CheckCircle2 size={16} />Application details are complete.</p>}<p className="text-sm text-[#60758b]">{agent ? 'Agent capture remains a draft. Share the online form so the applicant can confirm their details and declarations.' : 'Your declarations apply to your own information and authority to submit this application. Additional people’s consent evidence must be reviewed separately.'}</p>{declarationsContent}</div> : null}
      <footer className="mt-6 flex flex-wrap justify-between gap-3 border-t border-[#edf3f8] pt-4"><Button type="button" variant="secondary" disabled={busy || step === 0} onClick={() => setStep((current) => current - 1)}>Back</Button><div className="flex gap-2">{!readOnly && onSave ? <Button type="button" variant="secondary" disabled={busy} onClick={() => void onSave()}>{busy ? 'Saving…' : agent ? 'Save application profile' : 'Save draft'}</Button> : null}{step < 7 ? <Button type="button" disabled={busy} onClick={() => void next()}>Continue</Button> : null}</div></footer>
    </div>
  </div>
}
