import { useEffect, useState } from 'react'
import { assertRentalTenancyActivationReady, getRentalApplicationTenancyConversion, listRentalMoveInReadiness, recordRentalMoveInReadiness } from '../../../../services/rentals/rentalApplicationRepository.js'

const title = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

export default function RentalMoveInReadinessPanel({ application }) {
  const [leaseId, setLeaseId] = useState(''); const [tenancyId, setTenancyId] = useState(''); const [items, setItems] = useState([]); const [drafts, setDrafts] = useState({}); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = async () => { if (!application?.id) return; try { const conversion = await getRentalApplicationTenancyConversion(application.id); const nextLeaseId = conversion?.rental_leases?.id; setLeaseId(nextLeaseId || ''); setTenancyId(conversion?.id || ''); if (!nextLeaseId) { setItems([]); return }; const nextItems = await listRentalMoveInReadiness(nextLeaseId); setItems(nextItems); setDrafts(Object.fromEntries(nextItems.map((item) => [item.id, { status: item.status, receivedAmount: item.received_amount, evidenceLink: item.evidence_link || '', exceptionReason: item.exception_reason || '' }]))) } catch (cause) { setError(cause.message) } }
  useEffect(() => { setError(''); void load() }, [application])
  const update = (id, key, value) => setDrafts((current) => ({ ...current, [id]: { ...(current[id] || {}), [key]: value } }))
  const save = async (item) => { const draft = drafts[item.id] || {}; try { setSaving(true); setError(''); setMessage(''); await recordRentalMoveInReadiness({ itemId: item.id, ...draft }); await load() } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  const verify = async () => { try { setSaving(true); setError(''); const result = await assertRentalTenancyActivationReady(tenancyId); setMessage(result.ready ? 'All move-in readiness obligations are complete.' : '') } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  if (application?.status !== 'approved' || !leaseId) return null
  return <section className="mt-5 border-t pt-5"><h3 className="font-semibold">Deposit and first-rent readiness</h3><p className="mt-1 text-sm text-slate-600">Operational readiness only — this does not post or allocate money.</p><div className="mt-3 space-y-3">{items.map((item) => { const draft = drafts[item.id] || {}; return <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-2"><b>{title(item.obligation_type)}</b><span>{title(item.status)}</span></div><p className="mt-1 text-slate-600">Required: {item.required_amount} · Recorded: {item.received_amount}</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><label>Outcome<select value={draft.status || item.status} onChange={(event) => update(item.id, 'status', event.target.value)} className="mt-1 block w-full rounded border p-2"><option value="required">Required</option><option value="partial">Partial</option><option value="received">Received</option><option value="verified">Verified</option><option value="waived">Waived</option></select></label><label>Amount received<input type="number" min="0" step="0.01" value={draft.receivedAmount ?? ''} onChange={(event) => update(item.id, 'receivedAmount', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label>Evidence link<input value={draft.evidenceLink || ''} onChange={(event) => update(item.id, 'evidenceLink', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label><label>Exception / waiver reason<input value={draft.exceptionReason || ''} onChange={(event) => update(item.id, 'exceptionReason', event.target.value)} className="mt-1 block w-full rounded border p-2" /></label></div><button type="button" disabled={saving} onClick={() => void save(item)} className="mt-3 rounded border px-3 py-1">Save obligation</button></div> })}</div><button type="button" disabled={saving || !tenancyId} onClick={() => void verify()} className="mt-4 rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">Check activation readiness</button>{message ? <p className="mt-3 text-sm text-emerald-700">{message}</p> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}</section>
}
