import Image from 'next/image'

type TeamMember = { id: string; name: string; role: string; avatarUrl?: string }

export function LwpAboutPage({ team }: { team: TeamMember[] }) {
  return <>
    <section className="lwp-about-hero"><div><p className="eyebrow">ABOUT LWP PROPERTIES</p><h1>Property is personal.<br />So is our work.</h1><p>Since 2008, LWP has brought a more considered kind of property advice to the places we know best — with local insight, straight answers and people who stay close to the move.</p><a href="#our-standard">The LWP standard <span aria-hidden="true">↘</span></a></div><p className="lwp-about-hero-note">ESTABLISHED LOCALLY<br />BUILT FOR WHAT’S NEXT</p></section>
    <section className="lwp-about-intro"><p className="eyebrow">A MODERN AGENCY WITH A HUMAN CENTRE</p><div><h2>Beyond the board.<br />Beyond the sale.</h2><div><p>We believe a property decision deserves more than a listing, a price guide and a follow-up call.</p><p>LWP brings local experience, thoughtful marketing and direct advice together — to make every next move clearer, more personal and better prepared.</p><a href="#our-team">Meet the people <span aria-hidden="true">↘</span></a></div></div></section>
    <section className="lwp-about-way"><div><p className="eyebrow">THE WAY WE WORK</p><h2>Close to the work.<br />Closer to people.</h2><p>Our job is not to make property feel complicated. It is to understand what matters, make the decision clearer and keep the move moving.</p></div><p className="lwp-swipe-cue" aria-hidden="true"><span>Swipe through our approach</span><b>→</b></p><ol><li><span>01</span><strong>Listen before we list.</strong></li><li><span>02</span><strong>Make the decision clearer.</strong></li><li><span>03</span><strong>Keep the momentum real.</strong></li></ol></section>
    <section className="lwp-about-standard" id="our-standard"><div><p className="eyebrow">THE LWP STANDARD</p><h2>Care, with a<br /><span>point of view.</span></h2><p>Our way of working keeps the advice grounded, the relationships personal and the outcome in focus.</p></div><div className="lwp-standard-list"><article><span>01</span><h3>People before process.</h3><p>A move is rarely just a transaction. We make room for the real context before prescribing the next step.</p></article><article><span>02</span><h3>Local, properly.</h3><p>The useful detail lives beyond a suburb name: the street, the timing and the lived-in view.</p></article><article><span>03</span><h3>Momentum matters.</h3><p>Clear advice only counts when it leads somewhere. We keep the work moving and communication close.</p></article></div></section>
    <section className="lwp-team-section" id="our-team"><div className="lwp-team-heading"><div><p className="eyebrow">THE PEOPLE AT LWP</p><h2>Meet the team<br />behind the move.</h2></div><p>Knowledgeable, connected and ready to understand what your next chapter needs.</p></div>{team.length ? <><p className="lwp-swipe-cue" aria-hidden="true"><span>Swipe through the team</span><b>→</b></p><div className="lwp-team-grid">{team.map((member, index) => <article key={member.id} className="lwp-team-card">{member.avatarUrl ? <Image src={member.avatarUrl} alt={member.name} width={420} height={490} unoptimized /> : <div className="lwp-team-placeholder" aria-hidden="true"><span>{member.name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2)}</span></div>}<div><span>0{index + 1}</span><h3>{member.name}</h3><p>{member.role}</p><a href="/contact">Start a conversation <b aria-hidden="true">↗</b></a></div></article>)}</div></> : <div className="lwp-team-empty"><p>Our local team is ready to help with your next move.</p><a href="/contact">Talk to LWP <span aria-hidden="true">↗</span></a></div>}</section>
    <section className="lwp-about-local"><p className="eyebrow">FOR THE PEOPLE WHO LIVE HERE</p><h2>Local knowledge<br />gets personal.</h2><p>Each neighbourhood has its own rhythm. We pair practical detail with a genuine understanding of what makes an address feel like home.</p><a href="/areas">Explore our local collection <span aria-hidden="true">↗</span></a></section>
    <section className="lwp-about-close"><p className="eyebrow">START WITH A CONVERSATION</p><h2>Let’s make what’s<br />next clearer.</h2><p>Whether you are selling, buying, renting or simply weighing up the options, our first job is to understand the move in front of you.</p><a href="/contact">Talk to the LWP team <span aria-hidden="true">↗</span></a></section>
  </>
}
