// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import RentalListingCreatePage from '../RentalListingCreatePage'

window.scrollTo = vi.fn()

const mocks = vi.hoisted(() => ({ create: vi.fn(), update: vi.fn(), navigate: vi.fn(), loadMaps: vi.fn() }))
vi.mock('react-router-dom', async (original) => ({ ...await original(), useNavigate: () => mocks.navigate }))
vi.mock('../../../context/WorkspaceContext', () => ({ useWorkspace: () => ({}) }))
vi.mock('../../../services/rentals/rentalWorkspaceScope', () => ({ resolveRentalWorkspaceScope: () => ({ organisationId: 'org-1', assignedAgentId: 'agent-1', branchId: '' }) }))
vi.mock('../../../services/rentals/rentalListingDraftService', () => ({ createRentalListingDraft: mocks.create, updateRentalListingDraft: mocks.update, getRentalListingForAgent: async () => null }))
vi.mock('../../../lib/googleMaps', () => ({ hasGoogleMapsApiKey: () => true, loadGoogleMaps: mocks.loadMaps }))
vi.mock('../../../services/rentals/rentalLeadService', () => ({ listRentalLeads: async () => [] }))
vi.mock('../../../services/rentals/rentalLandlordListingHandoffService', () => ({ linkRentalLandlordLeadToListing: async () => null }))
afterEach(() => { cleanup(); vi.clearAllMocks(); window.sessionStorage.clear() })

it('searches and selects an address, wires property cards and neutral counters, and restores the saved fields', async () => {
  const address = '81 Wild Avenue, Newlands, Pretoria, South Africa'
  const predictions = vi.fn((request, callback) => callback([{ description: address, place_id: 'place-81' }], 'OK'))
  const details = vi.fn((request, callback) => callback({ formatted_address: address, place_id: 'place-81', geometry: { location: { lat: () => -25.79, lng: () => 28.29 } }, address_components: [['81', 'street_number'], ['Wild Avenue', 'route'], ['Newlands', 'sublocality'], ['Pretoria', 'locality'], ['Gauteng', 'administrative_area_level_1'], ['0081', 'postal_code']].map(([long_name, type]) => ({ long_name, types: [type] })) }, 'OK'))
  mocks.loadMaps.mockResolvedValue({ maps: { places: { AutocompleteService: class { getPlacePredictions = predictions }, PlacesService: class { getDetails = details }, AutocompleteSessionToken: class {}, PlacesServiceStatus: { OK: 'OK', ZERO_RESULTS: 'ZERO_RESULTS' } } } })
  window.sessionStorage.setItem('arch9:rental-listing:create-draft', JSON.stringify({ activeStep: 'property', form: { landlordName: 'Test Owner', propertyAddress: 'Old address', streetNumber: '999', streetName: 'Old Road', suburb: 'Old Suburb', monthlyRent: '11000', rentalPriceFrequency: 'monthly', depositPolicy: 'no_deposit', availableFrom: '2026-10-01', description: 'Rental home' } }))
  mocks.create.mockResolvedValue({ listing: { id: 'listing-1' } })
  const view = render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  const categoryGroup = await screen.findByRole('group', { name: 'Property category' })
  expect(within(categoryGroup).getAllByRole('button')).toHaveLength(6)
  expect(screen.queryByText('Step 2 of 6')).toBeNull()
  expect(screen.queryByText('Add the property details.')).toBeNull()
  fireEvent.click(within(screen.getByRole('group', { name: 'Retirement accommodation' })).getByRole('button', { name: 'Yes' }))
  fireEvent.click(within(categoryGroup).getByRole('button', { name: 'Industrial' }))
  fireEvent.change(screen.getByLabelText('Property type'), { target: { value: 'Warehouse' } })
  const increase = screen.getByRole('button', { name: 'Increase Bedrooms' })
  expect(increase.hasAttribute('data-rental-control')).toBe(true)
  fireEvent.click(increase)
  fireEvent.click(increase)
  fireEvent.click(screen.getByRole('button', { name: 'Decrease Bedrooms' }))
  const search = screen.getByRole('combobox', { name: '' })
  fireEvent.focus(search)
  await waitFor(() => expect(mocks.loadMaps).toHaveBeenCalled())
  fireEvent.change(search, { target: { value: '81 Wild' } })
  fireEvent.click(await screen.findByRole('option', { name: address }))
  await waitFor(() => expect(search.value).toBe(address))
  expect(predictions.mock.calls[0][0]).toMatchObject({ componentRestrictions: { country: 'za' }, types: ['address'] })
  expect(details.mock.calls[0][0].placeId).toBe('place-81')
  const values = { propertyCategory: 'industrial', propertyType: 'Warehouse', retirementAccommodation: 'yes', bedrooms: '1', propertyAddress: address, streetNumber: '81', streetName: 'Wild Avenue', suburb: 'Newlands', city: 'Pretoria', province: 'Gauteng', postalCode: '0081', latitude: -25.79, longitude: 28.29, googlePlaceId: 'place-81' }
  fireEvent.click(screen.getByRole('button', { name: 'Save draft' }))
  expect(JSON.parse(window.sessionStorage.getItem('arch9:rental-listing:create-draft')).form).toMatchObject(values)
  view.unmount()
  render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  expect((await screen.findByRole('button', { name: 'Industrial' })).getAttribute('aria-pressed')).toBe('true')
  expect(screen.getByLabelText('Property type').value).toBe('Warehouse')
  expect(screen.queryByRole('group', { name: 'Retirement accommodation' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: /Review/ }))
  fireEvent.click(await screen.findByRole('button', { name: 'Create rental listing' }))
  await waitFor(() => expect(mocks.create).toHaveBeenCalledTimes(1))
  expect(mocks.create.mock.calls[0][0]).toMatchObject(values)
})

it('clears saved address components and location when the address search is cleared', async () => {
  window.sessionStorage.setItem('arch9:rental-listing:create-draft', JSON.stringify({ activeStep: 'property', form: { propertyAddress: 'Old address', streetNumber: '999', streetName: 'Old Road', suburb: 'Old Suburb', city: 'Old City', postalCode: '1234', latitude: -25, longitude: 28, googlePlaceId: 'old-place' } }))
  render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  fireEvent.click(await screen.findByRole('button', { name: 'Clear address' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save draft' }))
  expect(JSON.parse(window.sessionStorage.getItem('arch9:rental-listing:create-draft')).form).toMatchObject({ propertyAddress: '', streetNumber: '', streetName: '', suburb: '', city: '', province: '', postalCode: '', latitude: '', longitude: '', googlePlaceId: '' })
})

it('wires every landlord and mandate field into the session draft and final listing save', async () => {
  window.sessionStorage.setItem('arch9:rental-listing:create-draft', JSON.stringify({ activeStep: 'landlord', form: { propertyAddress: '12 Example Road', monthlyRent: '11000', rentalPriceFrequency: 'monthly', depositPolicy: 'no_deposit', availableFrom: '2026-10-01', description: 'Rental home' } }))
  mocks.create.mockResolvedValue({ listing: { id: 'listing-1' } })
  const view = render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  fireEvent.click(await screen.findByRole('button', { name: /Trust A trust owns/ }))
  const values = { landlordType: 'trust', landlordName: 'Family Property Trust', landlordPhone: '+27 82 123 4567', landlordEmail: 'trust@example.com', mandateStatus: 'signed_uploaded', marketingApprovalStatus: 'approved', mandateStartDate: '2026-10-02', mandateEndDate: '2027-10-01' }
  const labels = { landlordName: 'Trust name *', landlordPhone: 'Mobile', landlordEmail: 'Email', mandateStatus: 'Rental mandate', marketingApprovalStatus: 'Marketing approval', mandateStartDate: 'Mandate start date', mandateEndDate: 'Mandate end / expiry date' }
  for (const [name, value] of Object.entries(values)) {
    if (name !== 'landlordType') fireEvent.change(screen.getByLabelText(labels[name]), { target: { value } })
  }
  fireEvent.click(screen.getByRole('button', { name: 'Save draft' }))
  expect(JSON.parse(window.sessionStorage.getItem('arch9:rental-listing:create-draft')).form).toMatchObject(values)
  view.unmount()
  render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  await screen.findByRole('button', { name: /Trust A trust owns/ })
  for (const [name, value] of Object.entries(values)) {
    if (name !== 'landlordType') expect(screen.getByLabelText(labels[name]).value).toBe(value)
  }
  fireEvent.click(screen.getByRole('button', { name: /Review/ }))
  fireEvent.click(await screen.findByRole('button', { name: 'Create rental listing' }))
  await waitFor(() => expect(mocks.create).toHaveBeenCalledTimes(1))
  expect(mocks.create.mock.calls[0][0]).toMatchObject(values)
})

it('shows photo progress, prevents duplicate submissions, and retries the existing draft after upload failure', async () => {
  window.sessionStorage.setItem('arch9:rental-listing:create-draft', JSON.stringify({ activeStep: 'review', form: { landlordName: 'Test Owner', propertyAddress: '12 Example Road', monthlyRent: '11000', rentalPriceFrequency: 'monthly', depositPolicy: 'no_deposit', availableFrom: '2026-10-01', description: 'Rental home' } }))
  let rejectSave
  mocks.create.mockImplementation((form, context) => {
    context.onListingCreated('listing-1')
    context.onUploadProgress({ completed: 1, total: 26 })
    return new Promise((resolve, reject) => { rejectSave = reject })
  })
  mocks.update.mockResolvedValue({ listing: { id: 'listing-1' } })
  const { container } = render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  const submit = await screen.findByRole('button', { name: 'Create rental listing' })
  fireEvent.click(submit)
  fireEvent.submit(container.querySelector('form'))
  expect(mocks.create).toHaveBeenCalledTimes(1)
  expect(screen.getByRole('status').textContent).toBe('Saving photos: 1 of 26…')
  expect(screen.getByRole('button', { name: 'Saving rental…' }).disabled).toBe(true)
  rejectSave(Object.assign(new Error('Could not save photos: statement timeout'), { listingId: 'listing-1', galleryImages: [{ id: 'photo-0', url: 'https://storage.example/0.jpg' }] }))
  const retry = await screen.findByRole('button', { name: 'Retry saving rental' })
  fireEvent.click(retry)
  await waitFor(() => expect(mocks.update).toHaveBeenCalled())
  expect(mocks.create).toHaveBeenCalledTimes(1)
  expect(mocks.update.mock.calls[0][0]).toBe('listing-1')
  expect(mocks.update.mock.calls[0][1].galleryImages[0].url).toBe('https://storage.example/0.jpg')
  await waitFor(() => expect(mocks.navigate).toHaveBeenCalledWith('/agent/rentals/listings/listing-1/marketing', expect.any(Object)))
})

it('asks documented category questions, filters property types, and retains hidden answers across category/title changes', async () => {
  window.sessionStorage.setItem('arch9:rental-listing:create-draft', JSON.stringify({ activeStep: 'property', form: {} }))
  render(<MemoryRouter><RentalListingCreatePage /></MemoryRouter>)
  const title = await screen.findByLabelText('Ownership / title type')
  expect(screen.queryByLabelText('Unit number')).toBeNull()
  fireEvent.change(title, { target: { value: 'Unit' } })
  fireEvent.change(screen.getByLabelText('Unit number'), { target: { value: '12B' } })
  fireEvent.change(screen.getByLabelText('Complex / building'), { target: { value: 'The Atrium' } })
  fireEvent.change(title, { target: { value: 'Erf' } })
  expect(screen.queryByLabelText('Unit number')).toBeNull()
  fireEvent.click(within(screen.getByRole('group', { name: 'Property category' })).getByRole('button', { name: 'Industrial' }))
  expect(screen.getByLabelText('Property type').value).toBe('Warehouse')
  expect(within(screen.getByLabelText('Property type')).queryByRole('option', { name: 'Apartment' })).toBeNull()
  expect(screen.queryByLabelText('Pool')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: /Additional property details/ }))
  fireEvent.click(screen.getByRole('button', { name: 'Open Warehouse & loading' }))
  fireEvent.change(screen.getByLabelText('Truck access'), { target: { value: 'Superlink' } })
  fireEvent.change(screen.getByLabelText('Roller shutter doors'), { target: { value: '0' } })
  fireEvent.click(screen.getByRole('button', { name: 'Done' }))
  fireEvent.click(screen.getByRole('button', { name: 'Open Business premises' }))
  fireEvent.click(within(screen.getByRole('group', { name: 'Multi tenanted' })).getByRole('button', { name: 'No' }))
  fireEvent.click(screen.getByRole('button', { name: 'Done' }))
  fireEvent.click(screen.getByRole('button', { name: 'Step 2: Property details' }))
  fireEvent.click(within(screen.getByRole('group', { name: 'Property category' })).getByRole('button', { name: 'Residential' }))
  expect(screen.queryByLabelText('Truck access')).toBeNull()
  fireEvent.change(screen.getByLabelText('Ownership / title type'), { target: { value: 'Unit' } })
  expect(screen.getByLabelText('Unit number').value).toBe('12B')
  expect(screen.getByLabelText('Complex / building').value).toBe('The Atrium')
  fireEvent.click(within(screen.getByRole('group', { name: 'Property category' })).getByRole('button', { name: 'Industrial' }))
  fireEvent.click(screen.getByRole('button', { name: /Additional property details/ }))
  fireEvent.click(screen.getByRole('button', { name: 'Open Warehouse & loading' }))
  expect(screen.getByLabelText('Truck access').value).toBe('Superlink')
  expect(screen.getByLabelText('Roller shutter doors').value).toBe('0')
  fireEvent.click(screen.getByRole('button', { name: 'Done' }))
  fireEvent.click(screen.getByRole('button', { name: 'Open Business premises' }))
  expect(within(screen.getByRole('group', { name: 'Multi tenanted' })).getByRole('button', { name: 'No' }).getAttribute('aria-pressed')).toBe('true')
})
