import { ArrowLeft, ArrowRight, Bath, BedDouble, Car, ChevronDown, Search, SlidersHorizontal } from 'lucide-react'
import { useState } from 'react'
import './HomeSeekersDemo.css'

const properties = [
  { status: 'For sale', price: 'R 4 950 000', suburb: 'Bedfordview', beds: '4', baths: '3', cars: '2', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=88' },
  { status: 'For sale', price: 'R 3 650 000', suburb: 'Edenvale', beds: '3', baths: '2.5', cars: '2', image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=88' },
  { status: 'To let', price: 'R 28 000 / pm', suburb: 'Greenstone Hill', beds: '2', baths: '2', cars: '2', image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=88' },
  { status: 'Sold', price: 'R 4 300 000', suburb: 'Melrose', beds: '4', baths: '3', cars: '2', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=88' },
  { status: 'For sale', price: 'R 7 950 000', suburb: 'Waterkloof Ridge', beds: '5', baths: '4', cars: '3', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=88' },
]
const areas = [
  { name: 'Bedfordview', count: '42 properties', image: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=900&q=82' },
  { name: 'Edenvale', count: '36 properties', image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=82' },
  { name: 'Greenstone', count: '28 properties', image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=82' },
  { name: 'Sandton', count: '52 properties', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=82' },
]
const navItems = ['Buy', 'Sell', 'Rent', 'Developments', 'Our people', 'About', 'Contact']

function TextLink({ children, href = '#top' }) { return <a className="hs-link" href={href}>{children} <ArrowRight size={16} strokeWidth={1.7} /></a> }

function HomeSeekersDemo() {
  const [query, setQuery] = useState('')
  const [start, setStart] = useState(0)
  const shownProperties = properties.slice(start, start + 4)
  return <main className="hs-site" id="top">
    <header className="hs-header">
      <a className="hs-logo" href="#top" aria-label="Home Seekers home"><img src="/brand/homeseekers/logo.png" alt="Home Seekers" /></a>
      <nav className="hs-nav" aria-label="Main navigation">{navItems.map((item, index) => <a href={item === 'Buy' ? '/demo/homeseekers/buy' : item === 'Sell' ? '/demo/homeseekers/sell' : item === 'Our people' ? '#people' : '#properties'} key={item}>{item}{index < 3 && <ChevronDown size={13} />}</a>)}</nav>
    </header>
    <section className="hs-hero"><div className="hs-hero-copy"><p className="hs-eyebrow">Gauteng property. Done differently.</p><h1>Find where<br />life happens.</h1><p className="hs-intro">We help people buy, sell and move through Gauteng with more clarity, better marketing and people who genuinely know their neighbourhoods.</p><div className="hs-hero-links"><TextLink href="#properties">Buy</TextLink><TextLink href="#promise">Sell</TextLink><TextLink href="#areas">Rent</TextLink></div></div><div className="hs-hero-image"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90" alt="Contemporary Gauteng home at sunset" /></div></section>
    <form className="hs-search-bar" id="property-search" onSubmit={(event) => event.preventDefault()}><Search size={25} strokeWidth={1.5} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search suburb, estate or property" aria-label="Search suburb, estate or property" /><button type="button">Advanced search <SlidersHorizontal size={18} /></button></form>
    <section className="hs-promise" id="promise"><div className="hs-promise-main"><p className="hs-eyebrow">The Home Seekers promise</p><h2>45 days.</h2><p className="hs-promise-lead">That’s how serious we are about selling.</p></div><div className="hs-promise-principles"><a className="hs-promise-card" href="#property-search"><span>01</span><h3>We sell<br />or you save</h3><p>Sell your home in 45 days or we’ll halve our commission.*</p><b>Get a valuation <ArrowRight size={15} /></b></a><a className="hs-promise-card" href="#properties"><span>02</span><h3>Maximum<br />exposure</h3><p>Premium marketing, targeted buyers and maximum reach.</p><b>See our listings <ArrowRight size={15} /></b></a><a className="hs-promise-card" href="#people"><span>03</span><h3>Local people.<br />Local knowledge.</h3><p>Our agents live here. We know this market because it’s our home.</p><b>Meet our people <ArrowRight size={15} /></b></a></div><div className="hs-promise-image"><img src="https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1100&q=85" alt="Warm modern dining room" /><TextLink href="#people">Find out more</TextLink></div></section>
    <section className="hs-section hs-properties" id="properties"><div className="hs-section-top"><div><p className="hs-eyebrow">01 / Property</p><h2>Worth a look.</h2></div><div className="hs-section-controls"><TextLink>View all properties</TextLink><button aria-label="Previous properties" disabled={start === 0} onClick={() => setStart((value) => Math.max(value - 1, 0))}><ArrowLeft size={20} /></button><button aria-label="Next properties" disabled={start === properties.length - 4} onClick={() => setStart((value) => Math.min(value + 1, properties.length - 4))}><ArrowRight size={20} /></button></div></div><div className="hs-property-grid">{shownProperties.map((property) => <article className="hs-property-card" key={`${property.suburb}-${property.price}`}><div className="hs-property-image"><img src={property.image} alt={`${property.suburb} property`} /><span>{property.status}</span></div><div className="hs-property-details"><strong>{property.price}</strong><p>{property.suburb}</p><div><span><BedDouble size={15} /> {property.beds}</span><span><Bath size={15} /> {property.baths}</span><span><Car size={15} /> {property.cars}</span><ArrowRight size={18} /></div></div></article>)}</div></section>
    <section className="hs-section hs-areas" id="areas"><div className="hs-area-intro"><p className="hs-eyebrow">02 / Explore</p><h2>Find your<br />part of<br />Gauteng.</h2><TextLink>Explore areas</TextLink></div><div className="hs-area-grid">{areas.map((area) => <a className="hs-area-tile" href="#properties" key={area.name}><img src={area.image} alt="" /><div><h3>{area.name}</h3><p>{area.count} <ArrowRight size={16} /></p></div></a>)}</div></section>
    <section className="hs-utility" id="people"><a className="hs-utility-card" href="#promise"><i>◇</i><h3>Thinking of selling?</h3><p>Get a free, no obligation valuation of your home.</p><b>Get a valuation <ArrowRight size={16} /></b></a><a className="hs-utility-card" href="#people"><i>◎</i><h3>Meet our people</h3><p>Local agents. Real people. Real results.</p><b>Our people <ArrowRight size={16} /></b></a><a className="hs-utility-card" href="#areas"><i>▥</i><h3>Stay up to date</h3><p>Market insights, property news and local guides.</p><b>Visit the journal <ArrowRight size={16} /></b></a><a className="hs-utility-card" href="#property-search"><i>◔</i><h3>Let’s chat</h3><p>Have a question? We’re here to help.</p><b>Contact us <ArrowRight size={16} /></b></a></section>
    <footer className="hs-footer"><div><img src="/brand/homeseekers/logo.png" alt="Home Seekers" /><p>Gauteng property. Done differently.</p></div><div><h3>Properties</h3><a href="#properties">Buy</a><a href="#areas">Rent</a><a href="#properties">Developments</a><a href="#areas">Areas</a></div><div><h3>Sell</h3><a href="#promise">Sell with Home Seekers</a><a href="#promise">Request a valuation</a><a href="#promise">45 Day Promise</a></div><div><h3>Company</h3><a href="#people">About</a><a href="#people">Our people</a><a href="#people">Journal</a><a href="#people">Contact</a></div><div className="hs-footer-bottom"><span>© Home Seekers</span><span>Privacy · Terms · POPIA</span><span>Powered by Arch9</span></div></footer>
  </main>
}
export default HomeSeekersDemo
