import { ArrowLeft, ArrowRight, ArrowUpRight, Bath, BedDouble, Car, ChevronLeft, ChevronRight, Heart, Mail, MapPin, Maximize2, Phone, Share2, X } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { useState } from 'react'
import HomeSeekersFooter from './HomeSeekersFooter'
import HomeSeekersViewingModal from './HomeSeekersViewingModal'
import './HomeSeekersProperty.css'

const homes = {
  'waterkloof-estate': { type: 'For sale', place: 'Waterkloof, Pretoria', price: 'R25,800,000', beds: '05', baths: '07', parking: '05', erf: '2 421 m²', title: 'A private estate residence, designed for family life at its best.', intro: 'A considered Waterkloof home where arrival, entertaining and everyday family life each have their own generous moment.', detail: 'Set back behind a leafy approach, this five-bedroom residence combines a full-scale garden, gracious reception spaces and the kind of privacy that is increasingly rare. The arrangement is made for long lunches, busy family mornings and quiet time away from the city.', highlights: ['Five en-suite bedrooms', 'Garden and pool setting', 'Separate entertainment wing', 'Secure estate environment'], agent: { name: 'Hannah Botha', initials: 'HB', role: 'Senior listing advisor', note: 'Ask me about the garden, the entertaining spaces and the rhythm of this home beyond the photographs.' }, image: 'https://d21tw07c6rnmp0.cloudfront.net/media/uploads/869/residential/2026/2/869_42e792e711594d22ad9df15a573182f4_t_w_1540_h_635.avif' },
  'steyn-city': { type: 'For sale', place: 'Steyn City, Midrand', price: 'R12,995,000', beds: '03', baths: '03', parking: '02', erf: '1 083 m²', title: 'Architectural simplicity with a considered indoor-outdoor rhythm.', intro: 'An effortlessly composed contemporary home in Steyn City, shaped around light, landscape and low-key living.', detail: 'Quiet material choices and a clean architectural line give this home its confidence. The living spaces open naturally to the garden, while intimate private rooms sit apart from the entertaining zones.', highlights: ['Architect-designed layout', 'Three private suites', 'Indoor-outdoor living', 'Steyn City lifestyle'], agent: { name: 'Ryan Jacobs', initials: 'RJ', role: 'Senior listing advisor', note: 'I can walk you through the material decisions, the garden connection and what makes the floor plan work.' }, image: 'https://d21tw07c6rnmp0.cloudfront.net/media/uploads/869/residential/2025/8/869_97bcc14546414da09ea8ba586b858759_t_w_505_h_490.avif' },
  'waterkloof-land': { type: 'Vacant land', place: 'Waterkloof, Pretoria', price: 'R3,490,000', beds: '—', baths: '—', parking: '—', erf: '1 510 m²', title: 'A rare canvas for a home with a point of view.', intro: 'A quiet Waterkloof site ready for a home designed exactly around the way you want to live.', detail: 'Opportunities to begin with a clean slate are rare in this established pocket of Pretoria. The site gives you room to make a deliberate architectural decision, with mature surroundings already in place.', highlights: ['Established Waterkloof address', 'Generous site footprint', 'Build your own brief', 'Secure, quiet setting'], agent: { name: 'Lara van Wyk', initials: 'LW', role: 'Local property advisor', note: 'Let’s talk through the site, the possibilities and the practical detail before you build a brief.' }, image: 'https://d21tw07c6rnmp0.cloudfront.net/media/uploads/869/residential/2025/8/869_f02bc109f42a499fb43e3e7b41af6c13_t_w_505_h_490.avif' },
  'menlo-park-residence': { type: 'For sale', place: 'Menlo Park, Pretoria', price: 'R8,950,000', beds: '04', baths: '03', parking: '02', erf: '1 142 m²', title: 'A composed home for easy everyday living.', intro: 'A warm contemporary home in Menlo Park, balanced between quiet family life and a connected city address.', detail: 'The plan gives every part of the day a place to land: generous shared rooms, a sheltered garden and private spaces that feel properly separate. It is a home with enough presence for entertaining, without losing the ease of the everyday.', highlights: ['Four-bedroom family layout', 'Sheltered garden setting', 'Light-filled living rooms', 'Sought-after Menlo Park address'], agent: { name: 'Mia van der Merwe', initials: 'MV', role: 'Senior listing advisor', note: 'I can show you how the home works across the day, from the garden spaces to the private family wing.' }, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=90' },
  'brooklyn-courtyard-home': { type: 'For sale', place: 'Brooklyn, Pretoria', price: 'R6,750,000', beds: '03', baths: '02', parking: '02', erf: '864 m²', title: 'Light, privacy and a courtyard at its centre.', intro: 'A quietly confident Brooklyn home with a considered relationship to the garden, daylight and daily life.', detail: 'Designed around a protected courtyard, this home keeps the atmosphere calm while giving the living spaces a generous sense of connection. It is practical, polished and placed close to the energy of Brooklyn without feeling exposed to it.', highlights: ['Central courtyard living', 'Three-bedroom residence', 'Quiet, connected location', 'Secure double parking'], agent: { name: 'Sophie Naidoo', initials: 'SN', role: 'Local property advisor', note: 'Ask me about the courtyard, the natural light and what makes this Brooklyn pocket so easy to live in.' }, image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=90' },
  'moreleta-park-family-home': { type: 'For sale', place: 'Moreleta Park, Pretoria', price: 'R4,850,000', beds: '04', baths: '03', parking: '02', erf: '1 286 m²', title: 'A practical family home with room to grow.', intro: 'An established Moreleta Park home shaped around the routines, gatherings and quieter moments of family life.', detail: 'The spaces are adaptable and the garden gives the home a natural place to slow down. From everyday breakfast to weekends with friends, it has been arranged with a straightforward generosity that is increasingly hard to find.', highlights: ['Four adaptable bedrooms', 'Established garden', 'Family-friendly entertaining', 'Close to everyday amenities'], agent: { name: 'Thabo Molefe', initials: 'TM', role: 'Senior listing advisor', note: 'I’ll take you through the family flow, the outdoor areas and the small practical details that make this home work.' }, image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=90' },
}

export default function HomeSeekersProperty() {
  const { propertyId } = useParams()
  const home = homes[propertyId]
  const [activeImage, setActiveImage] = useState(0)
  const [galleryOpen, setGalleryOpen] = useState(false)
  const [viewingOpen, setViewingOpen] = useState(false)
  if (!home) return <main className="hs-property hs-property--missing"><p>❯ HOME SEEKERS / PROPERTY</p><h1>This home has<br />moved on.</h1><a href="/demo/homeseekers/buying">Browse current homes <ArrowRight size={18} /></a></main>
  const facts = [[BedDouble, home.beds, 'Bedrooms'], [Bath, home.baths, 'Bathrooms'], [Car, home.parking, 'Parking'], [Maximize2, home.erf, 'Erf size']]
  const gallery = [home.image, 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=90', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=90', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=90']
  const selectImage = (index) => setActiveImage((index + gallery.length) % gallery.length)
  return <main className="hs-property">
    <header className="hs-property__header"><a href="/demo/homeseekers/buying"><ArrowLeft size={18} /> All homes</a><a className="hs-property__brand" href="/demo/homeseekers"><img src="/brand/homeseekers/home-seekers-horizontal-black.svg" alt="Home Seekers" /></a><div><button type="button" aria-label="Save property"><Heart size={18} /></button><button type="button" aria-label="Share property"><Share2 size={18} /></button></div></header>
    <section className="hs-property__hero"><img src={gallery[activeImage]} alt={`${home.place} gallery image ${activeImage + 1}`} /><div className="hs-property__shade" /><div className="hs-property__hero-dossier"><p>❯ {home.type} <strong>/ SELECT HOME</strong></p><span><MapPin size={14} /> {home.place}</span><h1>{home.title}</h1><strong className="hs-property__hero-price">{home.price}</strong><div className="hs-property__hero-facts"><span><BedDouble size={15} /> {home.beds} Beds</span><span><Bath size={15} /> {home.baths} Baths</span><span><Car size={15} /> {home.parking} Parking</span></div><button type="button" onClick={() => setViewingOpen(true)}>Arrange a private viewing <ArrowRight size={17} /></button></div><div className="hs-property__hero-gallery"><span className="hs-property__count">{String(activeImage + 1).padStart(2, '0')} <i>/ {String(gallery.length).padStart(2, '0')}</i></span><div className="hs-property__filmstrip" aria-label="Property image gallery">{gallery.map((image, index) => <button className={index === activeImage ? 'is-active' : ''} type="button" key={image} onClick={() => selectImage(index)} aria-label={`View image ${index + 1} of ${gallery.length}`}><img src={image} alt="" /><span>{String(index + 1).padStart(2, '0')}</span></button>)}</div><div className="hs-property__gallery"><button type="button" onClick={() => selectImage(activeImage - 1)} aria-label="Previous image"><ChevronLeft size={20} /></button><button type="button" onClick={() => selectImage(activeImage + 1)} aria-label="Next image"><ChevronRight size={20} /></button><button type="button" onClick={() => setGalleryOpen(true)}><Maximize2 size={17} /> View all {gallery.length} photos</button></div></div></section>
    <section className="hs-property__summary"><div><p>❯ {home.type} <strong>/ HOME SEEKERS SELECT</strong></p><h1>{home.title}</h1></div><aside><span>Asking price</span><strong>{home.price}</strong><button className="hs-property__viewing-trigger" type="button" onClick={() => setViewingOpen(true)}>Arrange a private viewing <ArrowRight size={18} /></button></aside></section>
    <section className="hs-property__facts">{facts.map(([Icon, value, label]) => <div key={label}><Icon size={21} /><strong>{value}</strong><span>{label}</span></div>)}<p>Property details are representative for this design preview and will be connected to the approved live feed.</p></section>
    <section className="hs-property__story"><div><p>❯ THE <strong>STORY</strong></p><h2>More than<br />a listing.</h2><p>{home.detail}</p><a href="#enquire">Request the full property pack <ArrowUpRight size={18} /></a></div><figure><img src={home.image} alt="Property view" /><figcaption>HOME SEEKERS<br />CURATED HOMES</figcaption></figure></section>
    <section className="hs-property__agent"><div className="hs-property__agent-heading"><p>❯ THE PERSON <strong>BEHIND THE LISTING</strong></p><h2>Speak to<br />someone who<br /><em>knows the home.</em></h2></div><article><div className="hs-property__agent-monogram"><span>{home.agent.initials}</span><i>LISTING<br />ADVISOR</i></div><div className="hs-property__agent-details"><span>{home.agent.role}</span><h3>{home.agent.name}</h3><p>{home.agent.note}</p><div><button className="hs-property__viewing-trigger" type="button" onClick={() => setViewingOpen(true)}><Phone size={16} /> Arrange a viewing</button><a href="mailto:info@homeseeker.co.za?subject=Property%20enquiry"><Mail size={16} /> Send an enquiry</a></div></div><small>HOME SEEKERS / PRIVATE PROPERTY VIEWING</small></article></section>
    <section className="hs-property__highlights"><p>❯ DESIGNED FOR <strong>THE WAY YOU LIVE</strong></p><div>{home.highlights.map((highlight, index) => <article key={highlight}><span>0{index + 1}</span><h3>{highlight}</h3><i>↗</i></article>)}</div></section>
    <section className="hs-property__enquire" id="enquire"><div><p>❯ MAKE YOUR <strong>NEXT MOVE</strong></p><h2>See it<br />properly.</h2><p>{home.intro} Share a few details and we will arrange a private viewing around your schedule.</p></div><form action="mailto:info@homeseeker.co.za" method="post" encType="text/plain"><label>Your name<input required name="name" placeholder="Your name" /></label><label>Mobile number<input required name="mobile" placeholder="Your mobile number" /></label><label>Email address<input required type="email" name="email" placeholder="you@example.com" /></label><input type="hidden" name="Property" value={home.title} /><button type="submit">Request a private viewing <ArrowUpRight size={18} /></button></form></section>
    <HomeSeekersFooter />
    {viewingOpen && <HomeSeekersViewingModal home={home} onClose={() => setViewingOpen(false)} />}
    {galleryOpen && <div className="hs-property__lightbox" role="presentation" onMouseDown={() => setGalleryOpen(false)}><section role="dialog" aria-modal="true" aria-label="Property image gallery" onMouseDown={(event) => event.stopPropagation()}><button type="button" className="hs-property__lightbox-close" onClick={() => setGalleryOpen(false)} aria-label="Close gallery"><X size={22} /></button><img src={gallery[activeImage]} alt={`${home.place} gallery image ${activeImage + 1}`} /><div><span>PROPERTY GALLERY</span><strong>{String(activeImage + 1).padStart(2, '0')} / {String(gallery.length).padStart(2, '0')}</strong><p>Browse the image set</p><button type="button" onClick={() => selectImage(activeImage - 1)} aria-label="Previous gallery image"><ChevronLeft size={20} /></button><button type="button" onClick={() => selectImage(activeImage + 1)} aria-label="Next gallery image"><ChevronRight size={20} /></button></div></section></div>}
  </main>
}
