import { ArrowRight, ArrowUpRight, Check, Compass, Users } from 'lucide-react'
import { useState } from 'react'
import HomeSeekersValuationModal from './HomeSeekersValuationModal'
import HomeSeekersMobileNav from './HomeSeekersMobileNav'
import HomeSeekersFooter from './HomeSeekersFooter'
import './HomeSeekersJoin.css'
import './HomeSeekersBrand.css'

const paths = [
  { id: 'start', number: '01', title: 'Start in property', eyebrow: 'FOR PEOPLE AT THE BEGINNING', copy: 'Build the habits, local knowledge and confidence that turn a first opportunity into a career with momentum.', points: ['Structured introduction to the work', 'Real-world feedback from the start', 'A clear next step, not guesswork'] },
  { id: 'grow', number: '02', title: 'Grow what you have', eyebrow: 'FOR AGENTS READY TO LEVEL UP', copy: 'Bring your experience. We bring a sharper operating rhythm, support around the details and a team that expects more.', points: ['Personal development plan', 'Mentorship built into the week', 'A brand made to earn trust locally'] },
  { id: 'lead', number: '03', title: 'Lead locally', eyebrow: 'FOR PEOPLE WITH A POINT OF VIEW', copy: 'Turn genuine area knowledge into a career with range, autonomy and a meaningful place inside the Home Seekers story.', points: ['Own your local relationships', 'A team behind the ambition', 'Room to build something lasting'] },
]
const nav = [['Selling', 'selling'], ['Buying', 'buying'], ['Renting', 'renting'], ['Areas', 'areas'], ['About', 'about'], ['Join us', 'join']]

export default function HomeSeekersJoin() {
  const [activeId, setActiveId] = useState('start')
  const [valuationOpen, setValuationOpen] = useState(false)
  const active = paths.find((path) => path.id === activeId) || paths[0]
  return <main className="hs-join">
    <header className="hs-join__header"><a href="/demo/homeseekers" aria-label="Home Seekers home"><img src="/brand/homeseekers/home-seekers-horizontal-black.svg" alt="Home Seekers" /></a><nav>{nav.map(([label, slug]) => <a className={slug === 'join' ? 'is-active' : ''} href={`/demo/homeseekers/${slug}`} key={slug}>{label}</a>)}</nav><button type="button" onClick={() => setValuationOpen(true)}>Book a free valuation</button><HomeSeekersMobileNav links={nav.map(([label, slug]) => [label, `/demo/homeseekers/${slug}`])} active="join us" onValuation={() => setValuationOpen(true)} /></header>
    <section className="hs-join__hero"><div className="hs-join__hero-image"><img src="https://d21tw07c6rnmp0.cloudfront.net/media/uploads/869/pages/2025/12/869_424ce675e29a4906a0d709d7ef138c88_t_w_639_h_728.avif" alt="Home Seekers team members" /><div className="hs-join__hero-mark"><Compass size={22} /><span>YOUR<br />DIRECTION</span></div></div><div className="hs-join__hero-copy"><p>❯ JOIN <strong>HOME SEEKERS</strong></p><h1>Build a career<br />that moves<br /><em>with you.</em></h1><p>More than a desk and a logo. A modern property business for people who want to do the work properly—and move forward, faster.</p><a href="#path">Find your path <ArrowRight size={18} /></a><div><span>01</span><p>Training with intent</p><span>02</span><p>Mentorship that matters</p><span>03</span><p>A real local pipeline</p></div></div></section>
    <section className="hs-join__intro"><div className="hs-join__intro-lede"><p>❯ THIS ISN’T A <strong>GENERIC JOB POST</strong></p><span>01 / THE HOME SEEKERS ACADEMY</span><p>We are creating a team built around local knowledge, honest work and people who care about the outcome. That needs a better place to learn the craft.</p></div><div className="hs-join__intro-statement"><h2>Property is<br />personal.<br /><em>So is your<br />growth.</em></h2><p>Build a career with feedback, a real local pipeline and people close enough to care how the work gets done.</p><div><span>TRAINING</span><span>MENTORSHIP</span><span>MOMENTUM</span></div></div></section>
    <section className="hs-join__path" id="path"><div className="hs-join__path-nav"><p>❯ CHOOSE YOUR <strong>STARTING POINT</strong></p>{paths.map((path) => <button className={path.id === activeId ? 'is-active' : ''} type="button" key={path.id} onClick={() => setActiveId(path.id)}><span>{path.number}</span>{path.title}<i>↗</i></button>)}</div><article className="hs-join__path-detail"><span>{active.eyebrow}</span><h2>{active.title}.</h2><p>{active.copy}</p><ul>{active.points.map((point) => <li key={point}><Check size={17} /> {point}</li>)}</ul><a href="#apply">Talk about joining us <ArrowUpRight size={18} /></a><small>Home Seekers academy / {active.number} of {paths.length.toString().padStart(2, '0')}</small></article></section>
    <section className="hs-join__principles"><div><p>❯ WHAT WE BUILD <strong>AROUND YOU</strong></p><h2>Support with<br />a standard.</h2></div><div>{[['Training', 'Learn the foundations, then apply them in real conversations and real local work.'], ['Mentorship', 'Get the perspective, accountability and direct feedback that shortens the learning curve.'], ['Momentum', 'Do meaningful work every week, with a clearer view of what to do next.']].map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="hs-join__apply" id="apply"><div><p>❯ YOUR NEXT <strong>MOVE</strong></p><h2>Let’s see<br />where you fit.</h2><p>Tell us a little about where you are and what you want to build. This is a conversation, not a conveyor belt.</p><span><Users size={18} /> Conversations start locally.</span></div><form action="mailto:info@homeseeker.co.za" method="post" encType="text/plain"><label>Your name<input required name="name" placeholder="Your name" /></label><label>Email address<input required name="email" type="email" placeholder="you@example.com" /></label><label>Tell us where you are in your property journey<textarea required name="message" rows="3" placeholder="A few lines is perfect" /></label><button type="submit">Start the conversation <ArrowUpRight size={18} /></button></form></section>
    <HomeSeekersFooter />
    {valuationOpen && <HomeSeekersValuationModal onClose={() => setValuationOpen(false)} />}
  </main>
}
