import { EMPLOYMENT_TYPE_VALUES } from '../flow/bondApplicationFlowContract.js'

export const BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION = 'phase-4-v1'

export const BOND_APPLICATION_DOCUMENT_TIMING = {
  requiredBeforeSignature: 'required_before_signature',
  requiredBeforeBankSubmission: 'required_before_bank_submission',
  requestedAfterOriginatorReview: 'requested_after_originator_review',
}

export const BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES = {
  uploaded: 'uploaded',
  accepted: 'accepted',
}

export const BOND_APPLICATION_DOCUMENT_PARTICIPANT_ROLES = {
  primaryApplicant: 'primary_applicant',
  coApplicant: 'co_applicant',
  surety: 'surety',
}

export const BOND_APPLICATION_DOCUMENT_CANONICAL_TYPES = new Set([
  'buyer_id_document',
  'buyer_proof_of_address',
  'bank_statements',
  'proof_of_funds',
  'payslips',
  'employment_contract',
  'buyer_company_registration',
  'financial_statements',
  'commission_income_evidence',
  'pension_income_evidence',
  'proof_of_income',
  'property_finance_existing_bond',
  'debt_settlement_letter',
  'credit_history_supporting_documents',
])

function employmentTypeRule(group) {
  return { field: 'participants.primaryApplicant.employment.occupation_status', in: EMPLOYMENT_TYPE_VALUES[group] || [] }
}

export const BOND_APPLICATION_DOCUMENT_RULES = [
  {
    key: 'bond_application_primary_applicant_identity',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_id_document',
    title: 'Identity document',
    description: 'Used to verify your identity for the bond application.',
    reason: 'Identity verification is required for the primary applicant.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Applicant documents',
    order: 10,
    matching: {
      canonicalTypes: ['buyer_id_document', 'id_document', 'identity_document', 'passport_copy'],
    },
  },
  {
    key: 'bond_application_primary_applicant_address',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_proof_of_address',
    title: 'Proof of residential address',
    description: 'A recent document showing your residential address.',
    reason: 'Address verification is required for the primary applicant.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Applicant documents',
    order: 20,
    matching: {
      canonicalTypes: ['buyer_proof_of_address', 'proof_of_address', 'residential_address_proof'],
    },
  },
  {
    key: 'bond_application_primary_applicant_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'bank_statements',
    title: 'Latest 3 months bank statements',
    description: 'The latest 3 months of bank statements for the accounts used in your application.',
    reason: 'Three months of bank statements support income and affordability review.',
    visibleWhen: { not: employmentTypeRule('selfEmployed') },
    requiredWhen: { not: employmentTypeRule('selfEmployed') },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 3,
    category: 'Financial documents',
    order: 30,
    matching: {
      canonicalTypes: ['bank_statements', 'bank_statement'],
    },
  },
  {
    key: 'bond_application_self_employed_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'bank_statements',
    title: 'Latest 6 months bank statements',
    description: 'The latest 6 months of bank statements for the business and personal accounts used in your application.',
    reason: 'Self-employed or company income requires a 6-month bank-statement history.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 6,
    category: 'Financial documents',
    order: 35,
    matching: {
      canonicalTypes: ['bank_statements', 'bank_statement'],
    },
  },
  {
    key: 'bond_application_deposit_proof',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'proof_of_funds',
    title: 'Proof of deposit',
    description: 'Evidence for the deposit or buyer contribution recorded in your application.',
    reason: 'A deposit amount has been recorded.',
    visibleWhen: { field: 'application.finance.depositAmount', greaterThan: 0 },
    requiredWhen: { field: 'application.finance.depositAmount', greaterThan: 0 },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Financial documents',
    order: 40,
    matching: {
      canonicalTypes: ['proof_of_funds', 'reservation_deposit_pop', 'proof_of_payment', 'deposit_proof'],
    },
  },
  {
    key: 'bond_application_salary_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'payslips',
    title: 'Salary or income evidence',
    description: 'A recent payslip or income document from your employer.',
    reason: 'This supports your employed income.',
    visibleWhen: { any: [employmentTypeRule('permanent'), employmentTypeRule('contract'), employmentTypeRule('commission')] },
    requiredWhen: { any: [employmentTypeRule('permanent'), employmentTypeRule('contract'), employmentTypeRule('commission')] },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 50,
    matching: {
      canonicalTypes: ['payslips', 'payslip', 'proof_of_income', 'salary_slip'],
    },
  },
  {
    key: 'bond_application_employment_contract',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'employment_contract',
    title: 'Employment contract',
    description: 'Your current employment or contract agreement.',
    reason: 'Contract employment has been selected.',
    visibleWhen: employmentTypeRule('contract'),
    requiredWhen: employmentTypeRule('contract'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 60,
    matching: {
      canonicalTypes: ['employment_contract', 'contract_of_employment'],
    },
  },
  {
    key: 'bond_application_business_registration',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_registration',
    title: 'Business registration documents',
    description: 'Registration documents for your business, where applicable.',
    reason: 'Self-employed income has been selected.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 70,
    matching: {
      canonicalTypes: ['buyer_company_registration', 'company_registration_documents', 'cipc_registration'],
    },
  },
  {
    key: 'bond_application_self_employed_financials',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'financial_statements',
    title: 'Business financial information',
    description: 'Financial information supporting your self-employed income.',
    reason: 'Self-employed income has been selected.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 80,
    matching: {
      canonicalTypes: ['financial_statements', 'management_accounts', 'business_financials'],
    },
  },
  {
    key: 'bond_application_commission_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'commission_income_evidence',
    title: 'Commission income evidence',
    description: 'Documents showing your commission income history.',
    reason: 'Commission-based income has been selected.',
    visibleWhen: employmentTypeRule('commission'),
    requiredWhen: employmentTypeRule('commission'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 90,
    matching: {
      canonicalTypes: ['commission_income_evidence', 'commission_letter', 'commission_statement', 'proof_of_income'],
    },
  },
  {
    key: 'bond_application_retirement_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'pension_income_evidence',
    title: 'Retirement income evidence',
    description: 'Documents showing your recurring pension, annuity or retirement income.',
    reason: 'Retirement income has been selected.',
    visibleWhen: employmentTypeRule('retired'),
    requiredWhen: employmentTypeRule('retired'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 100,
    matching: {
      canonicalTypes: ['pension_income_evidence', 'pension_statement', 'annuity_statement'],
    },
  },
  {
    key: 'bond_application_other_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'proof_of_income',
    title: 'Other income evidence',
    description: 'Documents supporting the other recurring income recorded in your application.',
    reason: 'Other recurring income has been selected.',
    visibleWhen: { any: [employmentTypeRule('other'), { field: 'participants.primaryApplicant.employment.has_additional_income', equals: 'yes' }] },
    requiredWhen: { any: [employmentTypeRule('other'), { field: 'participants.primaryApplicant.employment.has_additional_income', equals: 'yes' }] },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 110,
    matching: {
      canonicalTypes: ['proof_of_income', 'other_income_evidence', 'income_confirmation'],
    },
  },
  {
    key: 'bond_application_existing_property_bond_statement',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'property_finance_existing_bond',
    title: 'Existing property bond statement',
    description: 'A recent statement for an existing property bond, where applicable.',
    reason: 'Existing property ownership has been recorded.',
    visibleWhen: { field: 'participants.primaryApplicant.credit.owns_property', equals: 'yes' },
    requiredWhen: { field: 'participants.primaryApplicant.credit.owns_property', equals: 'yes' },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Property documents',
    order: 120,
    matching: {
      canonicalTypes: ['property_finance_existing_bond', 'home_loan_statement', 'bond_statement'],
    },
  },
  {
    key: 'bond_application_debt_settlement_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'debt_settlement_letter',
    title: 'Debt or settlement evidence',
    description: 'Documents for debts or credit agreements recorded in your application.',
    reason: 'Existing debts have been recorded.',
    visibleWhen: { field: 'participants.primaryApplicant.credit.has_debts', equals: 'yes' },
    requiredWhen: { field: 'participants.primaryApplicant.credit.has_debts', equals: 'yes' },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Financial documents',
    order: 130,
    matching: {
      canonicalTypes: ['debt_settlement_letter', 'settlement_letter', 'credit_agreement_statement'],
    },
  },
  {
    key: 'bond_application_credit_history_support',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'credit_history_supporting_documents',
    title: 'Credit history supporting documents',
    description: 'Supporting documents for the credit-history details you disclosed.',
    reason: 'A credit-history matter has been disclosed.',
    visibleWhen: {
      any: [
        { field: 'participants.primaryApplicant.credit.under_debt_review', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_judgment', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_arrears', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.declared_insolvent', equals: 'yes' },
      ],
    },
    requiredWhen: {
      any: [
        { field: 'participants.primaryApplicant.credit.under_debt_review', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_judgment', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_arrears', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.declared_insolvent', equals: 'yes' },
      ],
    },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Credit documents',
    order: 140,
    matching: {
      canonicalTypes: ['credit_history_supporting_documents', 'debt_review_documents', 'judgment_documents', 'arrears_documents'],
    },
  },
]

export function getBondApplicationDocumentManagedKeys(contract = BOND_APPLICATION_DOCUMENT_RULES) {
  return new Set(contract.map((requirement) => requirement.key))
}
