import { EMPLOYMENT_TYPE_VALUES } from '../flow/bondApplicationFlowContract.js'
import {
  BOND_APPLICATION_INTENTS,
  BOND_APPLICATION_PRE_APPROVAL_STATUSES,
} from '../bondApplicationState.js'

export const BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION = 'phase-4-v1'

export const BOND_APPLICATION_DOCUMENT_TIMING = {
  requiredBeforeSignature: 'required_before_signature',
  requiredBeforeBankSubmission: 'required_before_bank_submission',
  requestedAfterOriginatorReview: 'requested_after_originator_review',
}

export const BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES = {
  uploaded: 'uploaded',
  accepted: 'accepted',
}

export const BOND_APPLICATION_DOCUMENT_PARTICIPANT_ROLES = {
  primaryApplicant: 'primary_applicant',
  coApplicant: 'co_applicant',
  surety: 'surety',
}

export const BOND_APPLICATION_DOCUMENT_CANONICAL_TYPES = new Set([
  'buyer_id_document',
  'buyer_proof_of_address',
  'bank_statements',
  'personal_bank_statements',
  'business_bank_statements',
  'proof_of_funds',
  'offer_to_purchase',
  'marriage_certificate',
  'antenuptial_contract',
  'payslips',
  'employment_contract',
  'buyer_company_registration',
  'buyer_company_resolution',
  'buyer_director_identity_documents',
  'buyer_company_financial_statements',
  'buyer_company_tax_documents',
  'buyer_company_beneficial_ownership',
  'buyer_trust_deed',
  'buyer_letters_of_authority',
  'buyer_trustee_identity_documents',
  'buyer_trust_resolution',
  'buyer_trust_beneficial_ownership',
  'financial_statements',
  'management_accounts',
  'accountant_letter',
  'tax_documents',
  'assets_liabilities_statement',
  'commission_income_evidence',
  'contract_income_history',
  'pension_income_evidence',
  'rental_income_evidence',
  'maintenance_income_evidence',
  'investment_income_evidence',
  'trust_income_evidence',
  'proof_of_income',
  'property_finance_existing_bond',
  'debt_settlement_letter',
  'credit_history_supporting_documents',
  'credit_check_consent',
  'affordability_assessment',
  'pre_approval_certificate',
  'surety_undertaking',
])

function employmentTypeRule(group) {
  return { field: 'participants.primaryApplicant.employment.occupation_status', in: EMPLOYMENT_TYPE_VALUES[group] || [] }
}

function notEmploymentTypeRule(group) {
  return { not: employmentTypeRule(group) }
}

function maritalStatusRule(value) {
  if (value === 'married') return { field: 'participants.primaryApplicant.personal.marital_status', in: ['married', 'Married'] }
  return { field: 'participants.primaryApplicant.personal.marital_status', equals: value }
}

function maritalRegimeRule(values = []) {
  return { field: 'participants.primaryApplicant.marital.regime', in: values }
}

function selfEmployedFinancialsOlderThanSixMonthsRule() {
  return {
    all: [
      employmentTypeRule('selfEmployed'),
      { field: 'participants.primaryApplicant.employment.financials_older_than_6_months', equals: 'yes' },
    ],
  }
}

function buyerEntityTypeRule(types = []) {
  return { field: 'application.buyerEntity.entityType', in: types }
}

function applicationIntentRule(intents = []) {
  return { field: 'application.intent', in: intents }
}

function notPreApprovalOnlyRule() {
  return { not: applicationIntentRule([BOND_APPLICATION_INTENTS.preApproval]) }
}

function fullApplicationBuyerEntityTypeRule(types = []) {
  return { all: [notPreApprovalOnlyRule(), buyerEntityTypeRule(types)] }
}

function preApprovalOnlyRule() {
  return applicationIntentRule([BOND_APPLICATION_INTENTS.preApproval])
}

function existingPreApprovalRule() {
  return {
    any: [
      applicationIntentRule([BOND_APPLICATION_INTENTS.bondApplicationWithPreApproval]),
      { field: 'application.preApproval.status', in: [
        BOND_APPLICATION_PRE_APPROVAL_STATUSES.existing,
        BOND_APPLICATION_PRE_APPROVAL_STATUSES.approved,
      ] },
    ],
  }
}

function incomeSourceTypeRule(types = []) {
  return {
    field: 'participants.primaryApplicant.incomeSources',
    collectionContains: {
      field: 'type',
      in: types,
    },
  }
}

export const BOND_APPLICATION_DOCUMENT_RULES = [
  {
    key: 'bond_application_offer_to_purchase',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'offer_to_purchase',
    title: 'Offer to Purchase / Sale Agreement',
    description: 'The signed sale agreement or Offer to Purchase for this property.',
    reason: 'Banks require the signed purchase agreement before bond submission.',
    visibleWhen: notPreApprovalOnlyRule(),
    requiredWhen: notPreApprovalOnlyRule(),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Property documents',
    order: 5,
    matching: {
      canonicalTypes: ['offer_to_purchase', 'signed_offer_to_purchase', 'sale_agreement', 'sales_agreement', 'purchase_agreement', 'otp', 'signed_otp', 'accepted_offer_document', 'signed_offer_document'],
    },
  },
  {
    key: 'bond_application_buyer_company_registration',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_registration',
    title: 'Company registration documents',
    description: 'CIPC registration documents for the purchasing company.',
    reason: 'A company purchaser requires entity verification before bank submission.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Juristic purchaser documents',
    order: 6,
    matching: {
      canonicalTypes: ['buyer_company_registration', 'company_registration_documents', 'cipc_registration', 'ck_documents'],
    },
  },
  {
    key: 'bond_application_buyer_company_director_ids',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_director_identity_documents',
    title: 'Director identity documents',
    description: 'Identity documents for company directors and authorised signatories.',
    reason: 'Banks need to verify the people controlling and signing for the company purchaser.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Juristic purchaser documents',
    order: 7,
    matching: {
      canonicalTypes: ['buyer_director_identity_documents', 'director_id_documents', 'director_ids', 'authorised_signatory_id'],
    },
  },
  {
    key: 'bond_application_buyer_company_resolution',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_resolution',
    title: 'Company resolution to purchase / borrow',
    description: 'Signed company resolution authorising the purchase, bond application and signatories.',
    reason: 'Banks require proof that the company is authorised to buy and borrow.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Juristic purchaser documents',
    order: 8,
    matching: {
      canonicalTypes: ['buyer_company_resolution', 'company_resolution', 'resolution_to_purchase', 'resolution_to_borrow'],
    },
  },
  {
    key: 'bond_application_buyer_company_financials',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_financial_statements',
    title: 'Company financial statements',
    description: 'Latest company financial statements supporting the juristic purchaser application.',
    reason: 'Bank affordability and credit teams review company financial capacity.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Juristic purchaser documents',
    order: 9,
    matching: {
      canonicalTypes: ['buyer_company_financial_statements', 'company_financial_statements', 'annual_financial_statements', 'afs'],
    },
  },
  {
    key: 'bond_application_buyer_company_tax_documents',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_tax_documents',
    title: 'Company SARS tax documents',
    description: 'Company tax returns, SARS assessment or tax clearance where requested.',
    reason: 'Tax records support company compliance and credit assessment.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Juristic purchaser documents',
    order: 10,
    matching: {
      canonicalTypes: ['buyer_company_tax_documents', 'company_tax_documents', 'tax_clearance', 'sars_assessment', 'tax_returns'],
    },
  },
  {
    key: 'bond_application_buyer_company_beneficial_ownership',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_beneficial_ownership',
    title: 'Beneficial ownership declaration',
    description: 'Beneficial-owner, shareholder or controlling-person information for the company.',
    reason: 'Entity purchaser FICA requires beneficial ownership and control checks.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['company']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Juristic purchaser documents',
    order: 11,
    matching: {
      canonicalTypes: ['buyer_company_beneficial_ownership', 'beneficial_ownership', 'shareholder_register', 'controlling_persons'],
    },
  },
  {
    key: 'bond_application_buyer_trust_deed',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_trust_deed',
    title: 'Trust deed',
    description: 'Trust deed and amendments for the purchasing trust.',
    reason: 'Banks need to verify the trust and its powers before submission.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Juristic purchaser documents',
    order: 12,
    matching: {
      canonicalTypes: ['buyer_trust_deed', 'trust_deed', 'trust_deed_amendments'],
    },
  },
  {
    key: 'bond_application_buyer_letters_of_authority',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_letters_of_authority',
    title: 'Letters of authority',
    description: 'Master of the High Court letters of authority for the trustees.',
    reason: 'Trustees must be authorised to act for the trust.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Juristic purchaser documents',
    order: 13,
    matching: {
      canonicalTypes: ['buyer_letters_of_authority', 'letters_of_authority', 'master_letters_of_authority'],
    },
  },
  {
    key: 'bond_application_buyer_trustee_ids',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_trustee_identity_documents',
    title: 'Trustee identity documents',
    description: 'Identity documents for trustees and authorised trust signatories.',
    reason: 'Banks need to verify the people controlling and signing for the trust purchaser.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Juristic purchaser documents',
    order: 14,
    matching: {
      canonicalTypes: ['buyer_trustee_identity_documents', 'trustee_id_documents', 'trustee_ids', 'authorised_trustee_id'],
    },
  },
  {
    key: 'bond_application_buyer_trust_resolution',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_trust_resolution',
    title: 'Trust resolution to purchase / borrow',
    description: 'Signed trustee resolution authorising the purchase, bond application and signatories.',
    reason: 'Banks require proof that trustees have authorised the purchase and borrowing.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Juristic purchaser documents',
    order: 15,
    matching: {
      canonicalTypes: ['buyer_trust_resolution', 'trust_resolution', 'trustee_resolution', 'resolution_to_purchase', 'resolution_to_borrow'],
    },
  },
  {
    key: 'bond_application_buyer_trust_beneficial_ownership',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_trust_beneficial_ownership',
    title: 'Trust beneficial ownership declaration',
    description: 'Beneficial-owner, founder, trustee, protector and beneficiary information for the trust.',
    reason: 'Trust purchaser FICA requires beneficial ownership and control checks.',
    visibleWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredWhen: fullApplicationBuyerEntityTypeRule(['trust']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Juristic purchaser documents',
    order: 16,
    matching: {
      canonicalTypes: ['buyer_trust_beneficial_ownership', 'trust_beneficial_ownership', 'beneficiary_schedule', 'trust_controlling_persons'],
    },
  },
  {
    key: 'bond_application_primary_applicant_identity',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_id_document',
    title: 'Identity document',
    description: 'Used to verify your identity for the bond application.',
    reason: 'Identity verification is required for the primary applicant.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Applicant documents',
    order: 10,
    matching: {
      canonicalTypes: ['buyer_id_document', 'id_document', 'identity_document', 'passport_copy'],
    },
  },
  {
    key: 'bond_application_primary_applicant_address',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_proof_of_address',
    title: 'Proof of residential address',
    description: 'A recent document showing your residential address.',
    reason: 'Address verification is required for the primary applicant.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Applicant documents',
    order: 20,
    matching: {
      canonicalTypes: ['buyer_proof_of_address', 'proof_of_address', 'residential_address_proof'],
    },
  },
  {
    key: 'bond_application_pre_approval_credit_check_consent',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'credit_check_consent',
    title: 'Credit check consent',
    description: 'Signed consent allowing credit bureau and affordability checks for pre-approval.',
    reason: 'A pre-approval assessment requires consent before credit information can be checked.',
    visibleWhen: preApprovalOnlyRule(),
    requiredWhen: preApprovalOnlyRule(),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Pre-approval documents',
    order: 21,
    matching: {
      canonicalTypes: ['credit_check_consent', 'credit_bureau_consent', 'pre_approval_credit_consent'],
    },
  },
  {
    key: 'bond_application_pre_approval_affordability_declaration',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'affordability_assessment',
    title: 'Affordability and expense declaration',
    description: 'Signed income, expense and affordability declaration for the pre-approval assessment.',
    reason: 'Pre-approval depends on the applicant declared income, expenses and credit commitments.',
    visibleWhen: preApprovalOnlyRule(),
    requiredWhen: preApprovalOnlyRule(),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Pre-approval documents',
    order: 22,
    matching: {
      canonicalTypes: ['affordability_assessment', 'affordability_declaration', 'income_expense_declaration', 'pre_approval_affordability'],
    },
  },
  {
    key: 'bond_application_existing_pre_approval_certificate',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'pre_approval_certificate',
    title: 'Pre-approval certificate',
    description: 'Certificate or written confirmation for the existing pre-approval.',
    reason: 'Existing pre-approval should be verified and attached as supporting evidence for the final bond application.',
    visibleWhen: existingPreApprovalRule(),
    requiredWhen: existingPreApprovalRule(),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Pre-approval documents',
    order: 23,
    matching: {
      canonicalTypes: ['pre_approval_certificate', 'preapproval_certificate', 'pre_approval_letter', 'pre_qualification_certificate'],
    },
  },
  {
    key: 'bond_application_primary_applicant_marriage_certificate',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'marriage_certificate',
    title: 'Marriage certificate',
    description: 'Marriage certificate for the applicant, where applicable.',
    reason: 'Marital status affects bank, FICA and legal checks.',
    visibleWhen: maritalStatusRule('married'),
    requiredWhen: maritalStatusRule('married'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Marital documents',
    order: 25,
    matching: {
      canonicalTypes: ['marriage_certificate', 'marriage_cert'],
    },
  },
  {
    key: 'bond_application_primary_applicant_antenuptial_contract',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'antenuptial_contract',
    title: 'Antenuptial contract',
    description: 'Registered antenuptial contract or proof of marital property regime.',
    reason: 'Banks may require the ANC when an applicant is married out of community of property.',
    visibleWhen: {
      all: [
        maritalStatusRule('married'),
        maritalRegimeRule(['out_of_community', 'out-of-community', 'out of community', 'anc', 'ANC', 'married_out_of_community', 'out_of_community_of_property', 'out_of_community_with_accrual', 'out_of_community_without_accrual']),
      ],
    },
    requiredWhen: {
      all: [
        maritalStatusRule('married'),
        maritalRegimeRule(['out_of_community', 'out-of-community', 'out of community', 'anc', 'ANC', 'married_out_of_community', 'out_of_community_of_property', 'out_of_community_with_accrual', 'out_of_community_without_accrual']),
      ],
    },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Marital documents',
    order: 26,
    matching: {
      canonicalTypes: ['antenuptial_contract', 'anc', 'marital_contract'],
    },
  },
  {
    key: 'bond_application_surety_identity',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'buyer_id_document',
    title: 'Identity document',
    description: 'Identity document or passport for the surety.',
    reason: 'Banks and attorneys need to verify the surety before suretyship can be relied on.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Surety documents',
    order: 27,
    matching: {
      canonicalTypes: ['buyer_id_document', 'surety_id_document', 'surety_identity_document', 'passport_copy'],
    },
  },
  {
    key: 'bond_application_surety_address',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'buyer_proof_of_address',
    title: 'Proof of residential address',
    description: 'A recent document showing the surety residential address.',
    reason: 'Surety FICA checks require current residential-address verification.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Surety documents',
    order: 28,
    matching: {
      canonicalTypes: ['buyer_proof_of_address', 'surety_proof_of_address', 'proof_of_address', 'residential_address_proof'],
    },
  },
  {
    key: 'bond_application_primary_applicant_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'bank_statements',
    title: 'Latest 3 months bank statements',
    description: 'Recent 3 months bank statements for the accounts used in your application.',
    reason: 'Bank statements support income and affordability review.',
    visibleWhen: notEmploymentTypeRule('selfEmployed'),
    requiredWhen: notEmploymentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Financial documents',
    order: 30,
    matching: {
      canonicalTypes: ['bank_statements', 'bank_statement', 'bank_statements_3_months'],
    },
  },
  {
    key: 'bond_application_primary_applicant_self_employed_personal_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'personal_bank_statements',
    title: 'Latest 6 months personal bank statements',
    description: 'Latest 6 consecutive months personal bank statements reflecting self-employed income.',
    reason: 'Self-employed income requires a longer personal statement history for affordability review.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 6,
    category: 'Financial documents',
    order: 31,
    matching: {
      canonicalTypes: ['personal_bank_statements', 'personal_bank_statement', 'personal_bank_statements_6_months', 'bank_statements_6_months'],
    },
  },
  {
    key: 'bond_application_primary_applicant_self_employed_business_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'business_bank_statements',
    title: 'Latest 6 months business bank statements',
    description: 'Latest 6 consecutive months business bank statements, where business banking is used.',
    reason: 'Banks review business account conduct and income consistency for self-employed applicants.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 6,
    category: 'Financial documents',
    order: 32,
    matching: {
      canonicalTypes: ['business_bank_statements', 'business_bank_statement', 'business_bank_statements_6_months'],
    },
  },
  {
    key: 'bond_application_surety_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'bank_statements',
    title: 'Latest 3 months bank statements',
    description: 'Recent 3 months bank statements for the surety personal accounts.',
    reason: 'Banks review surety account conduct and affordability where a surety supports the application.',
    visibleWhen: notEmploymentTypeRule('selfEmployed'),
    requiredWhen: notEmploymentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 3,
    category: 'Surety financial documents',
    order: 33,
    matching: {
      canonicalTypes: ['bank_statements', 'surety_bank_statements', 'bank_statement', 'bank_statements_3_months'],
    },
  },
  {
    key: 'bond_application_surety_self_employed_personal_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'personal_bank_statements',
    title: 'Latest 6 months personal bank statements',
    description: 'Latest 6 consecutive months personal bank statements reflecting the surety self-employed income.',
    reason: 'Self-employed surety income requires a longer personal statement history for affordability review.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 6,
    category: 'Surety financial documents',
    order: 34,
    matching: {
      canonicalTypes: ['personal_bank_statements', 'surety_personal_bank_statements', 'personal_bank_statement', 'personal_bank_statements_6_months', 'bank_statements_6_months'],
    },
  },
  {
    key: 'bond_application_surety_self_employed_business_bank_statements',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'business_bank_statements',
    title: 'Latest 6 months business bank statements',
    description: 'Latest 6 consecutive months business bank statements for the surety business, where business banking is used.',
    reason: 'Banks review business account conduct and income consistency for self-employed sureties.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 6,
    category: 'Surety financial documents',
    order: 35,
    matching: {
      canonicalTypes: ['business_bank_statements', 'surety_business_bank_statements', 'business_bank_statement', 'business_bank_statements_6_months'],
    },
  },
  {
    key: 'bond_application_deposit_proof',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'application',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'proof_of_funds',
    title: 'Proof of deposit',
    description: 'Evidence for the deposit or buyer contribution recorded in your application.',
    reason: 'A deposit amount has been recorded.',
    visibleWhen: {
      all: [
        notPreApprovalOnlyRule(),
        { field: 'application.finance.depositAmount', greaterThan: 0 },
      ],
    },
    requiredWhen: {
      all: [
        notPreApprovalOnlyRule(),
        { field: 'application.finance.depositAmount', greaterThan: 0 },
      ],
    },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Financial documents',
    order: 40,
    matching: {
      canonicalTypes: ['proof_of_funds', 'reservation_deposit_pop', 'proof_of_payment', 'deposit_proof'],
    },
  },
  {
    key: 'bond_application_salary_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'payslips',
    title: 'Latest payslip / salary income evidence',
    description: 'Latest payslip or salary income document from your employer.',
    reason: 'This supports your employed income.',
    visibleWhen: { any: [employmentTypeRule('permanent'), employmentTypeRule('contract'), employmentTypeRule('commission')] },
    requiredWhen: { any: [employmentTypeRule('permanent'), employmentTypeRule('contract'), employmentTypeRule('commission')] },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 50,
    matching: {
      canonicalTypes: ['payslips', 'payslip', 'proof_of_income', 'salary_slip'],
    },
  },
  {
    key: 'bond_application_surety_salary_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'payslips',
    title: 'Latest payslip / salary income evidence',
    description: 'Latest payslip or salary income document from the surety employer.',
    reason: 'Surety income must be evidenced before it can support the bond application.',
    visibleWhen: { any: [employmentTypeRule('permanent'), employmentTypeRule('contract'), employmentTypeRule('commission')] },
    requiredWhen: { any: [employmentTypeRule('permanent'), employmentTypeRule('contract'), employmentTypeRule('commission')] },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Surety income documents',
    order: 55,
    matching: {
      canonicalTypes: ['payslips', 'surety_payslip', 'surety_proof_of_income', 'proof_of_income', 'salary_slip'],
    },
  },
  {
    key: 'bond_application_employment_contract',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'employment_contract',
    title: 'Signed employment contract',
    description: 'Your current signed employment or fixed-term contract.',
    reason: 'Contract employment has been selected.',
    visibleWhen: employmentTypeRule('contract'),
    requiredWhen: employmentTypeRule('contract'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 60,
    matching: {
      canonicalTypes: ['employment_contract', 'contract_of_employment', 'signed_employment_contract', 'fixed_term_contract'],
    },
  },
  {
    key: 'bond_application_business_registration',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'buyer_company_registration',
    title: 'Business registration documents',
    description: 'Registration documents for your business, where applicable.',
    reason: 'Self-employed income has been selected.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 70,
    matching: {
      canonicalTypes: ['buyer_company_registration', 'company_registration_documents', 'cipc_registration'],
    },
  },
  {
    key: 'bond_application_self_employed_accountant_letter',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'accountant_letter',
    title: 'Accountant letter / letter of drawings',
    description: 'Dated and signed accountant letter confirming income, drawings and business status.',
    reason: 'Self-employed applicants often need accountant confirmation instead of a traditional payslip.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 75,
    matching: {
      canonicalTypes: ['accountant_letter', 'letter_of_drawings', 'auditor_letter', 'accountant_confirmation'],
    },
  },
  {
    key: 'bond_application_surety_self_employed_accountant_letter',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'accountant_letter',
    title: 'Accountant letter / letter of drawings',
    description: 'Dated and signed accountant letter confirming the surety income, drawings and business status.',
    reason: 'Self-employed sureties often need accountant confirmation instead of a traditional payslip.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Surety income documents',
    order: 76,
    matching: {
      canonicalTypes: ['accountant_letter', 'surety_accountant_letter', 'letter_of_drawings', 'auditor_letter', 'accountant_confirmation'],
    },
  },
  {
    key: 'bond_application_self_employed_financials',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'financial_statements',
    title: 'Latest 2 years annual financial statements',
    description: 'Latest 2 years signed annual financial statements for the business.',
    reason: 'Banks review business trading history and profitability for self-employed applicants.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodYears: 2,
    category: 'Income documents',
    order: 80,
    matching: {
      canonicalTypes: ['financial_statements', 'annual_financial_statements', 'afs', 'business_financials', 'income_statement_balance_sheet'],
    },
  },
  {
    key: 'bond_application_surety_self_employed_financials',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'financial_statements',
    title: 'Latest 2 years annual financial statements',
    description: 'Latest 2 years signed annual financial statements for the surety business.',
    reason: 'Banks review trading history and profitability for self-employed sureties.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodYears: 2,
    category: 'Surety income documents',
    order: 80.5,
    matching: {
      canonicalTypes: ['financial_statements', 'surety_financial_statements', 'annual_financial_statements', 'afs', 'business_financials'],
    },
  },
  {
    key: 'bond_application_self_employed_management_accounts',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'management_accounts',
    title: 'Recent management accounts',
    description: 'Recent management accounts when annual financial statements are older than 6 months.',
    reason: 'Banks may require current management accounts when signed annuals are no longer recent.',
    visibleWhen: selfEmployedFinancialsOlderThanSixMonthsRule(),
    requiredWhen: selfEmployedFinancialsOlderThanSixMonthsRule(),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 81,
    matching: {
      canonicalTypes: ['management_accounts', 'recent_management_accounts', 'ma'],
    },
  },
  {
    key: 'bond_application_self_employed_tax_documents',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'tax_documents',
    title: 'SARS tax assessment / tax returns',
    description: 'Latest SARS income tax assessment, IT34 or tax returns supporting declared income.',
    reason: 'Tax records help banks validate self-employed income and tax standing.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Income documents',
    order: 82,
    matching: {
      canonicalTypes: ['tax_documents', 'tax_return', 'tax_returns', 'it34', 'ita34', 'sars_assessment', 'income_tax_assessment'],
    },
  },
  {
    key: 'bond_application_self_employed_assets_liabilities_statement',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'assets_liabilities_statement',
    title: 'Personal assets and liabilities statement',
    description: 'Statement of personal assets, liabilities, monthly income and expenses.',
    reason: 'Banks commonly request a personal balance sheet for self-employed affordability assessment.',
    visibleWhen: employmentTypeRule('selfEmployed'),
    requiredWhen: employmentTypeRule('selfEmployed'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Financial documents',
    order: 83,
    matching: {
      canonicalTypes: ['assets_liabilities_statement', 'personal_assets_liabilities', 'statement_of_assets_and_liabilities', 'income_expenses_assets_liabilities'],
    },
  },
  {
    key: 'bond_application_surety_assets_liabilities_statement',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'assets_liabilities_statement',
    title: 'Personal assets and liabilities statement',
    description: 'Statement of the surety personal assets, liabilities, monthly income and expenses.',
    reason: 'Banks and attorneys need evidence of surety capacity before relying on the suretyship.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Surety financial documents',
    order: 84,
    matching: {
      canonicalTypes: ['assets_liabilities_statement', 'surety_assets_liabilities', 'personal_assets_liabilities', 'statement_of_assets_and_liabilities'],
    },
  },
  {
    key: 'bond_application_surety_undertaking',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'surety',
    canonicalDocumentType: 'surety_undertaking',
    title: 'Signed surety undertaking',
    description: 'Signed suretyship undertaking, surety terms or approved surety declaration pack.',
    reason: 'The suretyship must be recorded before the signing package can be treated as complete.',
    visibleWhen: true,
    requiredWhen: true,
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Surety legal documents',
    order: 85,
    matching: {
      canonicalTypes: ['surety_undertaking', 'suretyship_agreement', 'surety_terms', 'surety_declaration', 'surety_signature_pack'],
    },
  },
  {
    key: 'bond_application_commission_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'commission_income_evidence',
    title: 'Latest 6 months commission income evidence',
    description: 'Latest 6 months commission statements, commission payslips or employer confirmation.',
    reason: 'Commission-based income has been selected.',
    visibleWhen: employmentTypeRule('commission'),
    requiredWhen: employmentTypeRule('commission'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 6,
    category: 'Income documents',
    order: 90,
    matching: {
      canonicalTypes: ['commission_income_evidence', 'commission_letter', 'commission_statement', 'commission_statements_6_months', 'commission_payslips', 'proof_of_income'],
    },
  },
  {
    key: 'bond_application_contract_income_history',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'contract_income_history',
    title: 'Contract income history',
    description: 'Recent income history supporting continuity of contract earnings.',
    reason: 'Banks may request income continuity evidence for contract workers.',
    visibleWhen: employmentTypeRule('contract'),
    requiredWhen: employmentTypeRule('contract'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    evidencePeriodMonths: 6,
    category: 'Income documents',
    order: 95,
    matching: {
      canonicalTypes: ['contract_income_history', 'contract_payslips', 'prior_contract_income', 'income_continuity_evidence'],
    },
  },
  {
    key: 'bond_application_retirement_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'pension_income_evidence',
    title: 'Pension / annuity income evidence',
    description: 'Pension, annuity or retirement income confirmation and proof of recurring deposits.',
    reason: 'Retirement income has been selected.',
    visibleWhen: employmentTypeRule('retired'),
    requiredWhen: employmentTypeRule('retired'),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeSignature,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 100,
    matching: {
      canonicalTypes: ['pension_income_evidence', 'pension_statement', 'annuity_statement', 'retirement_income_evidence', 'pension_deposit_proof'],
    },
  },
  {
    key: 'bond_application_additional_pension_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'pension_income_evidence',
    title: 'Additional pension / annuity income evidence',
    description: 'Evidence for additional pension or annuity income recorded in the application.',
    reason: 'Additional pension income must be supported for affordability review.',
    visibleWhen: incomeSourceTypeRule(['pension']),
    requiredWhen: incomeSourceTypeRule(['pension']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 101,
    matching: {
      canonicalTypes: ['additional_pension_income_evidence', 'pension_statement', 'annuity_statement', 'pension_deposit_proof'],
    },
  },
  {
    key: 'bond_application_rental_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'rental_income_evidence',
    title: 'Rental income evidence',
    description: 'Lease agreement and proof of rental deposits for rental income recorded in the application.',
    reason: 'Rental income must be supported before it can be used in affordability.',
    visibleWhen: incomeSourceTypeRule(['rental_income']),
    requiredWhen: incomeSourceTypeRule(['rental_income']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Income documents',
    order: 102,
    matching: {
      canonicalTypes: ['rental_income_evidence', 'lease_agreement', 'rental_deposit_proof', 'rental_bank_deposits'],
    },
  },
  {
    key: 'bond_application_maintenance_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'maintenance_income_evidence',
    title: 'Maintenance income evidence',
    description: 'Maintenance agreement, court order or proof of recurring maintenance receipts.',
    reason: 'Maintenance income must be supported before it can be used in affordability.',
    visibleWhen: incomeSourceTypeRule(['maintenance_received']),
    requiredWhen: incomeSourceTypeRule(['maintenance_received']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Income documents',
    order: 103,
    matching: {
      canonicalTypes: ['maintenance_income_evidence', 'maintenance_order', 'maintenance_agreement', 'maintenance_receipts'],
    },
  },
  {
    key: 'bond_application_investment_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'investment_income_evidence',
    title: 'Investment income evidence',
    description: 'Investment statement or confirmation showing recurring investment income.',
    reason: 'Investment income must be supported before it can be used in affordability.',
    visibleWhen: incomeSourceTypeRule(['investment_income']),
    requiredWhen: incomeSourceTypeRule(['investment_income']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Income documents',
    order: 104,
    matching: {
      canonicalTypes: ['investment_income_evidence', 'investment_statement', 'dividend_statement', 'interest_income_statement'],
    },
  },
  {
    key: 'bond_application_trust_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'trust_income_evidence',
    title: 'Trust income evidence',
    description: 'Trustee confirmation, trust distribution statement or supporting proof of trust income.',
    reason: 'Trust income must be supported before it can be used in affordability.',
    visibleWhen: incomeSourceTypeRule(['trust_income']),
    requiredWhen: incomeSourceTypeRule(['trust_income']),
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    allowMultipleFiles: true,
    category: 'Income documents',
    order: 105,
    matching: {
      canonicalTypes: ['trust_income_evidence', 'trustee_confirmation', 'trust_distribution_statement', 'trust_income_confirmation'],
    },
  },
  {
    key: 'bond_application_other_income_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'proof_of_income',
    title: 'Other income evidence',
    description: 'Documents supporting the other recurring income recorded in your application.',
    reason: 'Other recurring income has been selected.',
    visibleWhen: { any: [employmentTypeRule('other'), incomeSourceTypeRule(['other', 'part_time_income'])] },
    requiredWhen: { any: [employmentTypeRule('other'), incomeSourceTypeRule(['other', 'part_time_income'])] },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Income documents',
    order: 110,
    matching: {
      canonicalTypes: ['proof_of_income', 'other_income_evidence', 'income_confirmation'],
    },
  },
  {
    key: 'bond_application_existing_property_bond_statement',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'property_finance_existing_bond',
    title: 'Existing property bond statement',
    description: 'A recent statement for an existing property bond, where applicable.',
    reason: 'Existing property ownership has been recorded.',
    visibleWhen: { field: 'participants.primaryApplicant.credit.owns_property', equals: 'yes' },
    requiredWhen: { field: 'participants.primaryApplicant.credit.owns_property', equals: 'yes' },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Property documents',
    order: 120,
    matching: {
      canonicalTypes: ['property_finance_existing_bond', 'home_loan_statement', 'bond_statement'],
    },
  },
  {
    key: 'bond_application_debt_settlement_evidence',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'debt_settlement_letter',
    title: 'Debt or settlement evidence',
    description: 'Documents for debts or credit agreements recorded in your application.',
    reason: 'Existing debts have been recorded.',
    visibleWhen: { field: 'participants.primaryApplicant.credit.has_debts', equals: 'yes' },
    requiredWhen: { field: 'participants.primaryApplicant.credit.has_debts', equals: 'yes' },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Financial documents',
    order: 130,
    matching: {
      canonicalTypes: ['debt_settlement_letter', 'settlement_letter', 'credit_agreement_statement'],
    },
  },
  {
    key: 'bond_application_credit_history_support',
    ruleSetVersion: BOND_APPLICATION_DOCUMENT_RULE_SET_VERSION,
    scope: 'participant',
    participantRole: 'primary_applicant',
    canonicalDocumentType: 'credit_history_supporting_documents',
    title: 'Credit history supporting documents',
    description: 'Supporting documents for the credit-history details you disclosed.',
    reason: 'A credit-history matter has been disclosed.',
    visibleWhen: {
      any: [
        { field: 'participants.primaryApplicant.credit.under_debt_review', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_judgment', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_arrears', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.declared_insolvent', equals: 'yes' },
      ],
    },
    requiredWhen: {
      any: [
        { field: 'participants.primaryApplicant.credit.under_debt_review', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_judgment', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.has_arrears', equals: 'yes' },
        { field: 'participants.primaryApplicant.credit.declared_insolvent', equals: 'yes' },
      ],
    },
    requiredBefore: BOND_APPLICATION_DOCUMENT_TIMING.requiredBeforeBankSubmission,
    satisfactionMode: BOND_APPLICATION_DOCUMENT_SATISFACTION_MODES.uploaded,
    minimumFileCount: 1,
    category: 'Credit documents',
    order: 140,
    matching: {
      canonicalTypes: ['credit_history_supporting_documents', 'debt_review_documents', 'judgment_documents', 'arrears_documents'],
    },
  },
]

export function getBondApplicationDocumentManagedKeys(contract = BOND_APPLICATION_DOCUMENT_RULES) {
  return new Set(contract.map((requirement) => requirement.key))
}
