import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const detail = readFileSync(resolve(repositoryRoot, 'the-it-guy/src/pages/DevelopmentDetail.jsx'), 'utf8')
const workspace = readFileSync(resolve(repositoryRoot, 'the-it-guy/src/components/developments/DevelopmentAvailabilityWorkspace.jsx'), 'utf8')

assert.match(detail, /\{ id: 'availability', label: 'Availability' \}/, 'Availability is a first-class development tab')
assert.match(detail, /<DevelopmentAvailabilityWorkspace[\s\S]*units=\{unitRows\}/, 'Availability uses the canonical development unit rows')
assert.match(detail, /onCreateTransaction=\{\(unit\) => openDevelopmentTransactionWizard/, 'Availability starts the existing transaction flow')
assert.match(detail, /onChangeUnitStatus=\{\(unit, status\) => void handleUnitStatusQuickChange/, 'Availability uses the existing status-save path')
assert.match(workspace, /available:[\s\S]*reserved:[\s\S]*sold:[\s\S]*unreleased:/, 'Availability presents the required stock states')
assert.match(workspace, /Search unit, type, block, or buyer/, 'Availability supports inventory search')
assert.match(workspace, /All availability/, 'Availability supports status filtering')
assert.match(workspace, /Agency sales view/, 'Agency users receive a sales-oriented experience')
assert.match(workspace, /Developer inventory view/, 'Developer users receive an inventory-oriented experience')
assert.match(workspace, /Start buyer sale/, 'Agency users can begin the existing sales flow from a unit')
assert.match(workspace, /Edit unit/, 'Inventory managers can edit a selected unit')
assert.match(workspace, /Interactive site plan/, 'Availability includes an interactive site-plan surface')
assert.match(workspace, /Upload plan/, 'Inventory managers can upload a master plan')
assert.match(workspace, /Position selected unit/, 'Inventory managers can position a unit on the plan')
assert.match(workspace, /onSaveSitePlanMap/, 'Unit positions are persisted through the workspace callback')
assert.match(workspace, /Zoom in/, 'The site plan supports map zoom controls')
assert.match(detail, /sitePlanMap/, 'Site-plan position metadata is included in marketing persistence')
assert.match(detail, /createAgencyIntroducedDeveloperLead/, 'Agency-created buyer leads use the protected developer-lead handoff flow')
assert.match(detail, /createDeveloperFedLead/, 'Developer-created buyer leads use the existing developer-lead flow')
assert.match(detail, /updateDeveloperLeadWorkspaceSetup/, 'Sales actions are recorded against the existing developer-lead workspace')
assert.match(detail, /buyerLeads=\{developmentLeadRows\}/, 'Availability receives the development lead context')
assert.match(workspace, /Sales desk/, 'Availability includes the agent sales desk')
assert.match(workspace, /Add a new buyer lead/, 'Agents can create a buyer lead from a unit')
assert.match(workspace, /Comparison \(/, 'Agents can compare selected units')
assert.match(workspace, /Share summary/, 'Agents can prepare and record a unit share')
assert.match(workspace, /Request viewing/, 'Agents can log a viewing request')
assert.match(workspace, /Log follow-up/, 'Agents can record buyer follow-up')
assert.match(workspace, /Request reserve/, 'Agents can hand a reservation request into the transaction flow')
assert.match(workspace, /Developer controls/, 'Inventory managers receive a developer-only control surface')
assert.match(workspace, /Save price/, 'Developer controls can persist a governed unit price')
assert.match(workspace, /Release for sale/, 'Developer controls can release unreleased stock')
assert.match(workspace, /Move to unreleased/, 'Developer controls can protect released stock from sale')
assert.match(workspace, /Reservation default:/, 'Developer controls expose the active reservation policy')
assert.match(detail, /onSaveUnitPrice=\{\(unit, salesPrice\) => handleUnitQuickSave/, 'Availability pricing uses the existing unit-save path')
assert.match(detail, /onSetReleaseState=\{\(unit, status\) => handleUnitStatusQuickChange/, 'Availability release actions use the existing unit-status path')
assert.doesNotMatch(workspace, /Commercial pulse/, 'Availability removes the redundant commercial pulse panel')
assert.doesNotMatch(workspace, /Copy summary/, 'Availability removes the redundant internal summary panel')
assert.ok(workspace.indexOf('Total units') < workspace.indexOf('Availability workspace'), 'Availability metrics lead the workspace content')
assert.match(workspace, /min-w-\[650px\]/, 'Unit availability keeps its columns readable instead of clipping them')
assert.match(workspace, /Client presentation/, 'Teams can open a buyer-safe presentation view')
assert.match(workspace, /Exit presentation/, 'Presenters can return to internal operations')
assert.match(workspace, /Find the right home, with confidence\./, 'Presentation mode has buyer-facing landing-page messaging')
assert.match(workspace, /Available homes/, 'Presentation mode renders live available stock')

console.log('development availability workspace checks passed')
