import assert from 'node:assert/strict'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { chromium } from 'playwright'
import { unzipSync, strFromU8 } from 'fflate'
import { startBondVerificationServer } from './fixtures/bond-verification/server.mjs'
const base = process.env.BOND_VERIFICATION_URL || 'http://127.0.0.1:4179'
if (!['127.0.0.1','localhost'].includes(new URL(base).hostname)) throw new Error('Offline verification must use a loopback URL.')
const server = process.env.BOND_VERIFICATION_URL ? null : await startBondVerificationServer()
const output = process.env.BOND_VERIFICATION_OUTPUT || '/tmp/bond-application-verification'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
const errors = [], externalRequests = [], checks = []
const check = (message) => { checks.push(message); console.log(message) }
await context.route('**/*', async (route) => {
  const url = new URL(route.request().url())
  if (['http:','https:'].includes(url.protocol) && url.origin !== new URL(base).origin) { externalRequests.push(url.origin); return route.abort() }
  return route.continue()
})
const page = await context.newPage()
page.setDefaultTimeout(15000)
page.setDefaultNavigationTimeout(15000)
page.on('pageerror', (error) => errors.push(error.message))
const open = async (scenario) => { await page.goto(`${base}/?scenario=${scenario}`, { waitUntil: 'commit', timeout: 30_000 }); await page.waitForSelector('h1') }
try {
  await open('capture')
  await page.getByRole('textbox', { name: 'First name', exact: true }).fill('André')
  await page.getByRole('button', { name: 'Save and exit', exact: true }).click()
  await page.waitForFunction(() => localStorage.getItem('bond-verification-capture')?.includes('André'))
  await page.reload()
  await page.getByRole('textbox', { name: 'First name', exact: true }).waitFor()
  assert.equal(await page.getByRole('textbox', { name: 'First name', exact: true }).inputValue(), 'André')
  assert.equal(await page.getByRole('heading', { name: 'Update your details', level: 1 }).count(), 1)
  check('Captured answers and current screen survive saving and reloading')
  await page.screenshot({ path: `${output}/capture-desktop.png`, fullPage: true })
  await open('signing')
  await page.getByText('Draw your signature', { exact: false }).waitFor()
  const signaturePad = page.getByLabel('Bond application signature pad')
  const bounds = await signaturePad.boundingBox()
  assert.ok(bounds)
  await page.mouse.move(bounds.x + 30, bounds.y + 70)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 160, bounds.y + 100)
  await page.mouse.up()
  await page.getByText('I confirm that the information', { exact: false }).click()
  assert.equal(await page.getByRole('button', { name: 'Sign application', exact: true }).first().isEnabled(), true)
  assert.equal(await page.getByRole('button', { name: 'Save and exit' }).isEnabled(), true)
  await page.getByRole('button', { name: 'Save and exit' }).click()
  await page.waitForFunction(() => localStorage.getItem('bond-verification-signing')?.includes('html_canvas'))
  check('Applicant can draw, confirm, and save an in-application signature')
  await open('handoff')
  await page.getByRole('button', { name: 'Accept document', exact: true }).click()
  await page.getByRole('button', { name: 'Record external submission', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Record external submission', exact: true }).click()
  await page.getByLabel('Lender or bank names').fill('Verification Bank')
  await page.getByLabel('External reference', { exact: true }).fill('TEST-REFERENCE-42')
  await page.getByRole('button', { name: 'Record submission', exact: true }).click()
  await page.getByText('External submission history (1)', { exact: true }).click()
  await page.getByText('Reference: TEST-REFERENCE-42', { exact: true }).waitFor()
  check('Originator accepts a request and records the displayed signed version with lender/time/reference')
  await page.getByRole('button', { name: 'Request a document', exact: true }).click()
  await page.getByLabel('Request title', { exact: true }).fill('Proof of income')
  await page.getByLabel('Buyer instruction', { exact: true }).fill('Upload the latest proof of income.')
  await page.getByRole('button', { name: 'Create request', exact: true }).click()
  const request = page.locator('article').filter({ hasText: 'Proof of income' })
  await request.getByLabel('Feedback visible to the buyer').fill('This duplicate request is no longer needed.')
  await request.getByRole('button', { name: 'Withdraw request' }).click()
  await request.getByText('Proof of income · withdrawn', { exact: true }).waitFor()
  check('New request appears immediately; withdrawal and review history are visible')
  await page.getByLabel('Request an application correction', { exact: true }).fill('Correct the purchase price.')
  await page.getByRole('button', { name: 'Request correction', exact: true }).click()
  await page.getByRole('button', { name: 'Accept corrected signed application', exact: true }).click()
  await page.getByText('A newly signed current application version is required before resolving corrections.', { exact: false }).waitFor()
  check('Correction cannot be closed without new signed evidence (simulated API rejection)')
  await page.screenshot({ path: `${output}/handoff-desktop.png`, fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true)
  await page.screenshot({ path: `${output}/handoff-mobile.png`, fullPage: true })
  check('Mobile handoff has no horizontal overflow at 390px')
  await open('download')
  let pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download draft', exact: true }).click()
  const draft = await pending
  await draft.saveAs(`${output}/application-draft.pdf`)
  assert.match(draft.suggestedFilename(), /\.pdf$/)
  pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download final', exact: true }).click()
  const zip = await pending
  await zip.saveAs(`${output}/application-pack.zip`)
  const archive = unzipSync(await readFile(`${output}/application-pack.zip`))
  for (const filename of ['application.pdf','application-data.json','document-index.json','signed-evidence/original-signed-application.pdf']) assert.ok(archive[filename], filename)
  assert.ok(strFromU8(archive['signed-evidence/original-signed-application.pdf']).includes('SYNTHETIC VERIFICATION'))
  await writeFile(`${output}/application-final.pdf`, archive['application.pdf'])
  check('Browser produces a draft PDF and complete ZIP using synthetic evidence')
  let unexpectedDownload = false
  page.on('download', () => { unexpectedDownload = true })
  await page.route('**/verification-file.pdf', (route) => route.fulfill({ status: 403, body: 'Denied' }))
  await page.getByRole('button', { name: 'Download final', exact: true }).click()
  await page.getByRole('status').filter({ hasText: /could not be downloaded|not be downloaded|access/i }).waitFor()
  assert.equal(unexpectedDownload, false)
  check('Denied file access produces an error and no partial download')
  assert.deepEqual(errors, [])
  assert.deepEqual(externalRequests, [])
  await writeFile(`${output}/browser-results.json`, JSON.stringify({ type: 'offline-browser-integration', checks, liveAuthenticationVerified: false, realSigningVerified: false, externalRequests, errors }, null, 2))
  console.log(JSON.stringify({ output, checks, liveAuthenticationVerified: false, realSigningVerified: false }, null, 2))
} catch (error) { console.error(await page.locator('body').innerText()); await page.screenshot({ path: `${output}/failure.png`, fullPage: true }); throw error } finally { await browser.close(); server?.httpServer?.closeAllConnections(); await server?.close() }
