import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync(new URL('../src/pages/agency/AgencyPipelinePage.jsx', import.meta.url), 'utf8')

const profileStart = source.indexOf('data-testid="buyer-profile-onboarding-fields"')
const profileEnd = source.indexOf("resolveBuyerWorkspaceTabKey(leadWorkspaceTab) === 'legacy_overview'", profileStart)

assert.notEqual(profileStart, -1, 'buyer profile workspace should still render the existing onboarding field surface')
assert.notEqual(profileEnd, -1, 'buyer profile workspace block should remain before the legacy overview tab')

const profileBlock = source.slice(profileStart, profileEnd)
const routeFieldsStart = source.indexOf('const routeFields = [')
const routeFieldsEnd = source.indexOf('...onboardingSections', routeFieldsStart)
const profileModelStart = source.indexOf('function buildBuyerOnboardingProfileModel')
const profileModelEnd = source.indexOf('function renderBuyerOnboardingCompanyDetails', profileModelStart)
assert.notEqual(routeFieldsStart, -1, 'buyer profile setup fields should still be modelled')
assert.notEqual(routeFieldsEnd, -1, 'buyer profile setup fields should remain before adaptive onboarding sections')
assert.notEqual(profileModelStart, -1, 'buyer profile model builder should exist')
assert.notEqual(profileModelEnd, -1, 'buyer profile model builder should end before document rendering helpers')
const profileSetupModelBlock = source.slice(routeFieldsStart, routeFieldsEnd)
const profileModelBlock = source.slice(profileModelStart, profileModelEnd)

assert.match(profileBlock, /id="buyer-profile-onboarding-form"/, 'buyer profile should keep the existing save form id')
assert.match(profileBlock, /onSubmit=\{handleSaveBuyerProfile\}/, 'buyer profile should keep the existing save handler')
assert.match(profileBlock, /downloadBuyerOnboardingForm\(selectedLeadBuyerProfileModel\)/, 'buyer profile should keep onboarding form download plumbing')
assert.match(profileBlock, /data-testid="buyer-profile-source-awareness"/, 'buyer profile should show read-only source awareness metadata')
assert.match(profileBlock, /Source: \{selectedLeadBuyerProfileModel\.sourceLabel\}/, 'buyer profile should display the derived source label')
assert.match(profileBlock, /selectedLeadBuyerProfileModel\.sourceDetailLabel/, 'buyer profile should display the source timestamp detail')
assert.match(profileBlock, /selectedLeadBuyerProfileModel\.sourceRevisionLabel/, 'buyer profile should display later agent edits when available')
assert.match(profileBlock, /selectedLeadBuyerProfileModel\.sourceMergeSummaryLabel/, 'buyer profile should summarize buyer and agent differences when detected')
assert.match(profileBlock, /data-testid="buyer-profile-source-merge-summary"/, 'buyer profile should expose a source merge summary badge')
assert.match(profileBlock, /selectedLeadBuyerProfileModel\.completionActionLabel/, 'buyer profile header should expose the completion CTA')
assert.match(profileBlock, /selectedLeadBuyerProfileModel\.nextIncompleteSectionId \|\| 'buyer-profile-completion-panel'/, 'completion CTA should target the next incomplete profile section or readiness panel')
assert.match(profileBlock, /data-testid="buyer-profile-completion-panel"/, 'buyer profile should include a profile readiness panel')
assert.match(profileBlock, /data-testid="buyer-profile-missing-required-sections"/, 'buyer profile should list missing required sections when incomplete')
assert.match(profileBlock, /selectedLeadBuyerProfileModel\.missingRequiredSections\.map/, 'missing required sections should render as jump links')
assert.match(profileBlock, /document\.getElementById\(section\.sectionId\)\?\.scrollIntoView/, 'missing required section links should jump to the matching form section')
assert.match(profileBlock, /id=\{section\.sectionId\}/, 'each buyer profile form section should expose a stable jump target')
assert.match(profileBlock, /data-testid="buyer-profile-summary-strip"/, 'buyer profile should render one compact summary strip')
assert.match(profileBlock, /Required Fields[\s\S]*remaining[\s\S]*Fields Captured[\s\S]*Completion[\s\S]*Last Updated/, 'summary strip should include all requested metrics and remaining required fields')
assert.match(profileBlock, /style=\{\{ width: `\$\{selectedLeadBuyerProfileModel\.completionPercent\}%` \}\}/, 'completion metric should include a progress bar driven by completion percent')
assert.match(profileBlock, /section\.groupLabel[\s\S]*\{section\.groupLabel\}/, 'adaptive profile sections should expose concise section grouping labels')
assert.match(profileBlock, /lg:grid-cols-3/, 'buyer profile fields should use three columns on desktop')
assert.match(profileBlock, /md:grid-cols-2/, 'buyer profile fields should use two columns on tablet')
assert.match(profileBlock, /data-testid="buyer-profile-field"/, 'fields should be rendered as flat field groups')
assert.match(profileBlock, /field\.sourceMeta\?\.badge[\s\S]*data-testid="buyer-profile-field-source-badge"/, 'buyer profile fields should show compact source badges only when useful')
assert.match(profileBlock, /field\.sourceMeta\?\.conflict[\s\S]*data-testid="buyer-profile-field-source-conflict"/, 'buyer profile should show field-level buyer and agent conflicts')
assert.match(profileBlock, /field\.sourceMeta\.conflictLabel[\s\S]*field\.sourceMeta\.buyerDisplayValue/, 'buyer profile conflicts should show the buyer-submitted value')
assert.match(profileBlock, /onClick=\{\(\) => handleChange\(field\.sourceMeta\.buyerValue\)\}/, 'buyer profile conflicts should let the agent use the buyer-submitted value')
assert.match(profileBlock, /onClick=\{\(\) => handleChange\(value\)\}/, 'buyer profile conflicts should let the agent keep the current agent value')
assert.match(profileBlock, /isProfileSetupChoiceField = section\.key === 'routing' && field\.type === 'select'/, 'Profile Setup select fields should get a dedicated choice renderer')
assert.match(profileBlock, /data-testid="buyer-profile-setup-choice-group"/, 'Profile Setup should render compact choice groups instead of plain dropdowns')
assert.match(profileBlock, /aria-pressed=\{selected\}/, 'Profile Setup choices should expose selected state')
assert.match(profileBlock, /onClick=\{\(\) => handleChange\(option\.value\)\}/, 'Profile Setup choices should keep the existing update path')
assert.match(profileBlock, /\.filter\(\(option\) => normalizeText\(option\.value\)\)/, 'Profile Setup choices should omit placeholder options from the button group')
assert.doesNotMatch(profileBlock, /rounded-\[14px\] border border-\[#e4edf6\] bg-white px-3 py-3/, 'fields should not use the old per-field card treatment')
assert.doesNotMatch(profileBlock, /grid gap-4 px-6 py-5 sm:px-8 lg:grid-cols-4/, 'summary should not use four separate stat cards')
assert.match(profileBlock, /Use these details to identify the purchaser and prepare the transaction correctly\./, 'Your Details should use the refined helper copy')
assert.match(profileSetupModelBlock, /Profile Setup/, 'routing section should be reframed as Profile Setup')
assert.match(profileSetupModelBlock, /Set the buyer profile type so Arch9 shows the right details, documents, and offer requirements\./, 'Profile Setup should use agent-facing helper copy')
assert.match(profileSetupModelBlock, /Buyer Type/, 'purchaser type should be labelled as Buyer Type')
assert.match(profileSetupModelBlock, /Funding/, 'finance type should be labelled as Funding')
assert.match(profileSetupModelBlock, /Capture Method/, 'buyer intake mode should be labelled as Capture Method')
assert.doesNotMatch(profileSetupModelBlock, /Onboarding Routing|Purchaser Type|Finance Type|Buyer Intake Mode|These fields decide/, 'profile setup should not expose internal routing language')
assert.match(source, /buildBuyerProfileAdaptiveSections\(buildBuyerOnboardingSectionRows\(detailStep\?\.sections \|\| \[\], enrichedFormData\)\)/, 'adaptive onboarding sections should be transformed only after the existing conditional engine runs')
assert.match(source, /BUYER_PROFILE_ADAPTIVE_SECTION_GROUPS[\s\S]*personal_identity[\s\S]*Contact Details[\s\S]*Address & Compliance/, 'individual buyer details should be split into clearer buyer detail groups')
assert.match(source, /BUYER_PROFILE_ADAPTIVE_SECTION_GROUPS[\s\S]*company_details[\s\S]*Representative[\s\S]*company_authority/, 'company buyer details should be split into entity, representative, and authority groups')
assert.match(source, /BUYER_PROFILE_ADAPTIVE_SECTION_GROUPS[\s\S]*trust_details[\s\S]*trust_authority/, 'trust buyer details should be split into trust details and authority groups')
assert.match(source, /BUYER_PROFILE_ADAPTIVE_SECTION_PRESENTATION[\s\S]*Proof of Funds[\s\S]*Finance Readiness[\s\S]*Pre-Approval & Consent/, 'funding sections should use clearer cash and bond readiness language')
assert.match(profileModelBlock, /sourceLabel = hasBuyerSubmittedProfile[\s\S]*'Buyer onboarding'[\s\S]*'Agent captured'[\s\S]*'Not captured'/, 'profile source should be derived from existing onboarding and capture state')
assert.match(profileModelBlock, /sourceDetailLabel = hasBuyerSubmittedProfile && submittedAt[\s\S]*Submitted \$\{formatDateTime\(submittedAt\)\}[\s\S]*Last edited by agent \$\{formatDateTime\(updatedAt\)\}/, 'profile source should expose submitted and agent-edited timestamps')
assert.match(profileModelBlock, /sourceRevisionLabel = hasBuyerSubmittedProfile && isLaterBuyerProfileTimestamp\(updatedAt, submittedAt\)/, 'buyer-submitted profiles should show later agent edits when timestamps prove it')
assert.match(source, /function buildBuyerProfileSubmittedFormData/, 'buyer profile should derive the buyer-submitted form snapshot separately from the editable profile')
assert.match(source, /function buildBuyerProfileFieldSourceMeta/, 'buyer profile should compute field-level buyer and agent source metadata')
assert.match(source, /function readBuyerProfileSourceFieldValue/, 'buyer profile source metadata should read both top-level and repeatable field values')
assert.match(source, /function applyBuyerProfileFieldSourceMetaToSections/, 'buyer profile should decorate display sections with source metadata')
assert.match(profileModelBlock, /buyerSubmittedFormData = \{\}/, 'buyer profile model should accept the buyer-submitted snapshot without changing persisted fields')
assert.match(profileModelBlock, /agentUpdatedAfterSubmission = hasBuyerSubmittedProfile && isLaterBuyerProfileTimestamp\(updatedAt, submittedAt\)/, 'buyer profile should only infer agent edits after a buyer submission when timestamps prove it')
assert.match(profileModelBlock, /sourceConflictFields = sectionsWithSourceMeta\.flatMap/, 'buyer profile should count buyer and agent field differences')
assert.match(profileModelBlock, /sourceMergeSummaryLabel: sourceConflictFields\.length/, 'buyer profile should expose a compact source merge summary label')
assert.match(profileModelBlock, /sections: sectionsWithSourceMeta/, 'buyer profile should render source-decorated sections')
assert.doesNotMatch(profileSetupModelBlock, /sourceLabel|sourceDetailLabel|sourceRevisionLabel/, 'source awareness should not be another editable Profile Setup field')
assert.match(source, /function formatBuyerProfileSectionDomId/, 'buyer profile sections should have stable DOM ids for jump links')
assert.match(profileModelBlock, /missingRequiredSections = sections[\s\S]*field\.required && !field\.complete/, 'profile readiness should derive missing fields from existing required completion state')
assert.match(profileModelBlock, /requiredRemainingCount = missingRequiredSections\.reduce/, 'profile readiness should expose remaining required field count')
assert.match(profileModelBlock, /isReadyForOnboardingOtp = requiredCount > 0 && requiredRemainingCount === 0/, 'profile readiness should switch on only when all required fields are captured')
assert.match(profileModelBlock, /completionActionLabel: isReadyForOnboardingOtp \? 'Ready for Onboarding \/ OTP' : 'Complete Profile'/, 'profile CTA should switch to ready state once required fields are complete')
assert.match(profileModelBlock, /nextIncompleteSectionId: missingRequiredSections\[0\]\?\.sectionId \|\| ''/, 'profile model should expose the first incomplete section id')

console.log('buyer profile UI refinement contract tests passed')
