import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const agentLeadsPageShimSource = await readFile(new URL('../src/pages/AgentLeadsPage.jsx', import.meta.url), 'utf8')
const agencyPipelinePageSource = await readFile(new URL('../src/pages/agency/AgencyPipelinePage.jsx', import.meta.url), 'utf8')
const clientOnboardingSource = await readFile(new URL('../src/pages/ClientOnboarding.jsx', import.meta.url), 'utf8')
const onboardingVisualStepSource = await readFile(new URL('../src/components/onboarding/OnboardingVisualStep.jsx', import.meta.url), 'utf8')
const buyerOnboardingBackfillAuditSql = await readFile(new URL('./sql/buyer-onboarding-phase6-backfill-audit.sql', import.meta.url), 'utf8')
const buyerOnboardingTransactionBootstrapSql = await readFile(new URL('../../supabase/migrations/202608140003_buyer_onboarding_transaction_bootstrap.sql', import.meta.url), 'utf8')
const transactionLifecycleSource = await readFile(new URL('../src/lib/transactionLifecycleService.js', import.meta.url), 'utf8')
const packageSource = await readFile(new URL('../package.json', import.meta.url), 'utf8')
const simplifiedViewingPlannerStart = agencyPipelinePageSource.indexOf('data-testid="simplified-viewing-planner"')
const simplifiedViewingPlannerEnd = agencyPipelinePageSource.indexOf('{false ? (', simplifiedViewingPlannerStart)
assert.ok(simplifiedViewingPlannerStart > -1, 'Simplified viewing planner should exist.')
assert.ok(simplifiedViewingPlannerEnd > simplifiedViewingPlannerStart, 'Simplified viewing planner should be sliced before the legacy hidden planner.')
const simplifiedViewingPlannerSource = agencyPipelinePageSource.slice(simplifiedViewingPlannerStart, simplifiedViewingPlannerEnd)
const sendBuyerOnboardingFromAppointmentStart = agencyPipelinePageSource.indexOf('async function handleSendBuyerOnboardingFromAppointment')
const sendBuyerOnboardingFromAppointmentEnd = agencyPipelinePageSource.indexOf('function openBuyerOtpUploadPicker', sendBuyerOnboardingFromAppointmentStart)
assert.ok(sendBuyerOnboardingFromAppointmentStart > -1, 'Appointment buyer onboarding sender should exist.')
assert.ok(sendBuyerOnboardingFromAppointmentEnd > sendBuyerOnboardingFromAppointmentStart, 'Appointment buyer onboarding sender should be sliceable.')
const sendBuyerOnboardingFromAppointmentSource = agencyPipelinePageSource.slice(sendBuyerOnboardingFromAppointmentStart, sendBuyerOnboardingFromAppointmentEnd)
const sendBuyerOnboardingFromLeadStart = agencyPipelinePageSource.indexOf('async function handleSendBuyerOnboardingFromLead')
const sendBuyerOnboardingFromLeadEnd = agencyPipelinePageSource.indexOf('function updateFinanceReadinessField', sendBuyerOnboardingFromLeadStart)
assert.ok(sendBuyerOnboardingFromLeadStart > -1, 'Lead buyer onboarding sender should exist.')
assert.ok(sendBuyerOnboardingFromLeadEnd > sendBuyerOnboardingFromLeadStart, 'Lead buyer onboarding sender should be sliceable.')
const sendBuyerOnboardingFromLeadSource = agencyPipelinePageSource.slice(sendBuyerOnboardingFromLeadStart, sendBuyerOnboardingFromLeadEnd)
const buyerAppointmentsStart = agencyPipelinePageSource.indexOf('data-testid="buyer-lead-appointments-simplified"')
assert.ok(buyerAppointmentsStart > -1, 'Simplified buyer appointments workspace should exist.')
const saveBuyerProfileStart = agencyPipelinePageSource.indexOf('async function handleSaveBuyerProfile')
const saveBuyerProfileEnd = agencyPipelinePageSource.indexOf('function handleToggleViewingPlanProperty', saveBuyerProfileStart)
assert.ok(saveBuyerProfileStart > -1, 'Buyer profile save handler should exist.')
assert.ok(saveBuyerProfileEnd > saveBuyerProfileStart, 'Buyer profile save handler should be sliceable.')
const saveBuyerProfileSource = agencyPipelinePageSource.slice(saveBuyerProfileStart, saveBuyerProfileEnd)
const buyerProfileHydrationStart = agencyPipelinePageSource.indexOf('function buildBuyerProfileHydrationFormData')
const buyerProfileHydrationEnd = agencyPipelinePageSource.indexOf('function isOptionalOnboardingFormDataTableMissing', buyerProfileHydrationStart)
assert.ok(buyerProfileHydrationStart > -1, 'Buyer profile hydration builder should exist.')
assert.ok(buyerProfileHydrationEnd > buyerProfileHydrationStart, 'Buyer profile hydration builder should be sliceable.')
const buyerProfileHydrationSource = agencyPipelinePageSource.slice(buyerProfileHydrationStart, buyerProfileHydrationEnd)

assert.match(agentLeadsPageShimSource, /import AgencyPipelinePage from '\.\/agency\/AgencyPipelinePage'/)
assert.match(agentLeadsPageShimSource, /<AgencyPipelinePage initialViewMode="leads" \/>/)

assert.match(agencyPipelinePageSource, /BUYER_ONBOARDING_OTP_WORKSPACE_TAB_KEY = 'onboarding_otp'/)
assert.match(agencyPipelinePageSource, /function normalizeLeadWorkspaceTabKey/)
assert.match(agencyPipelinePageSource, /'offers'[\s\S]*return BUYER_ONBOARDING_OTP_WORKSPACE_TAB_KEY/)
assert.match(
  agencyPipelinePageSource,
  /\{ key: 'overview', label: 'Overview', meta: '' \},\s*\{ key: BUYER_PROFILE_WORKSPACE_TAB_KEY, label: 'Buyer Profile', meta: '' \},\s*\{ key: BUYER_ONBOARDING_OTP_WORKSPACE_TAB_KEY, label: 'Transaction Setup \/ Offer'[\s\S]*?\{ key: 'properties', label: 'Properties'[\s\S]*?\{ key: 'appointments', label: 'Appointments'[\s\S]*?\{ key: 'activity', label: 'Activity'/,
)
assert.match(agencyPipelinePageSource, /BUYER_PROFILE_WORKSPACE_TAB_KEY = 'buyer_profile'/)
assert.match(agencyPipelinePageSource, /resolveBuyerWorkspaceTabKey\(leadWorkspaceTab\) === 'overview' && !selectedLeadIsSeller \? \(/)
assert.match(agencyPipelinePageSource, /resolveBuyerWorkspaceTabKey\(leadWorkspaceTab\) === BUYER_PROFILE_WORKSPACE_TAB_KEY && !selectedLeadIsSeller \? \(/)
assert.match(agencyPipelinePageSource, /resolveBuyerWorkspaceTabKey\(leadWorkspaceTab\) === BUYER_ONBOARDING_OTP_WORKSPACE_TAB_KEY/)
assert.match(agencyPipelinePageSource, /Open Setup \/ Offer/)
assert.match(agencyPipelinePageSource, /Upload Signed OTP/)
assert.match(agencyPipelinePageSource, /buyer-transaction-setup-checklist/)
assert.match(agencyPipelinePageSource, /buyer-offer-upload-confirmations/)
assert.match(agencyPipelinePageSource, /onClick=\{openBuyerOtpUploadPicker\}/)
assert.match(agencyPipelinePageSource, /ref=\{buyerOtpUploadInputRef\}/)
assert.match(agencyPipelinePageSource, /form="buyer-onboarding-otp-send-form"/)
assert.match(agencyPipelinePageSource, /id="buyer-onboarding-otp-send-form"/)
assert.match(agencyPipelinePageSource, /lastBuyerOnboardingLink/)
assert.match(agencyPipelinePageSource, /async function createAndSendBuyerOnboardingForLead/)
assert.match(agencyPipelinePageSource, /async function ensureBuyerOnboardingTransactionForLead/)
assert.match(agencyPipelinePageSource, /type: 'client_onboarding'/)
assert.match(agencyPipelinePageSource, /buyer_onboarding_otp_workspace/)
assert.match(agencyPipelinePageSource, /buyer_lead_workspace_transaction_bootstrap/)
assert.match(agencyPipelinePageSource, /allowDirectLeadConversion: true/)
assert.match(transactionLifecycleSource, /creation_mode: creationCommand\.creationMode/, 'Direct buyer onboarding transaction bootstrap should mark creation_mode for the RPC.')
assert.match(buyerOnboardingTransactionBootstrapSql, /v_allow_direct_lead_conversion := v_offer_id is null and v_creation_mode in \('onboarding_capture', 'manual_intake', 'manual_capture'\)/, 'Buyer onboarding capture should be allowed without an accepted offer.')
assert.match(buyerOnboardingTransactionBootstrapSql, /if v_offer_id is null and not v_allow_direct_lead_conversion then[\s\S]*accepted offer and idempotency key/, 'Accepted offer should remain required for non-onboarding transaction creation.')
assert.match(buyerOnboardingTransactionBootstrapSql, /if v_offer_id is not null then[\s\S]*update public\.offers/, 'Offer linkage updates should only run when an accepted offer exists.')
assert.match(agencyPipelinePageSource, /Buyer onboarding link ready: \{offerLinkForm\.lastBuyerOnboardingLink\}/)
assert.doesNotMatch(agencyPipelinePageSource, /Buyer onboarding link ready: \{offerLinkForm\.lastBuyerOnboardingLink \|\| offerLinkForm\.lastOfferLink\}/)
assert.doesNotMatch(agencyPipelinePageSource, /Offer link still available/)
assert.doesNotMatch(sendBuyerOnboardingFromAppointmentSource, /createAndSendOfferLinkForLead/)
assert.doesNotMatch(sendBuyerOnboardingFromAppointmentSource, /buyer_offer_link/)
assert.doesNotMatch(sendBuyerOnboardingFromAppointmentSource, /\/offers/)
assert.match(sendBuyerOnboardingFromAppointmentSource, /createAndSendBuyerOnboardingForLead/)
assert.doesNotMatch(sendBuyerOnboardingFromLeadSource, /createAndSendOfferLinkForLead/)
assert.match(sendBuyerOnboardingFromLeadSource, /createAndSendBuyerOnboardingForLead/)
assert.match(agencyPipelinePageSource, /function AppointmentOverviewPanel/)
assert.match(agencyPipelinePageSource, /function UpcomingAppointmentsPanel/)
assert.match(agencyPipelinePageSource, /function LeadAppointmentsPanel/)
assert.match(agencyPipelinePageSource, /getLeadAppointmentDashboardRows/)
assert.match(agencyPipelinePageSource, /getLeadAppointmentFilterOptions/)
assert.match(agencyPipelinePageSource, /No appointments scheduled/)
assert.match(agencyPipelinePageSource, /Your upcoming appointments and client meetings will appear here\./)
assert.match(agencyPipelinePageSource, /Your next scheduled appointments will appear here\./)
assert.match(agencyPipelinePageSource, /All Appointments/)
assert.match(agencyPipelinePageSource, /Date &amp; Time/)
assert.match(agencyPipelinePageSource, /md:hidden/)
assert.doesNotMatch(agencyPipelinePageSource, /Viewing Workspace/)
assert.doesNotMatch(agencyPipelinePageSource, /Book a Viewing/)
assert.doesNotMatch(agencyPipelinePageSource, /Complete Viewing Outcome/)
assert.doesNotMatch(agencyPipelinePageSource, /Appointment History/)
assert.doesNotMatch(agencyPipelinePageSource, /Buyer Onboarding \+ OTP Transaction/)
assert.doesNotMatch(agencyPipelinePageSource, /Send onboarding first, then prepare or upload the OTP as the transaction source of truth\./)
assert.doesNotMatch(agencyPipelinePageSource, /OTP Transaction History/)
assert.doesNotMatch(agencyPipelinePageSource, /Buyer Preview/)
for (const overviewPanelLabel of ['Buyer Qualification', 'What’s next', 'Activity Logger', 'Viewing Planner']) {
  assert.match(agencyPipelinePageSource, new RegExp(overviewPanelLabel), `${overviewPanelLabel} should render from the buyer overview workspace.`)
}

assert.match(agencyPipelinePageSource, /getOnboardingStepDefinitions/)
assert.match(agencyPipelinePageSource, /buildBuyerOnboardingProfileModel/)
assert.match(agencyPipelinePageSource, /function buildBuyerProfileHydrationFormData/)
assert.match(agencyPipelinePageSource, /function mergeBuyerOnboardingFormDataSources/)
assert.match(agencyPipelinePageSource, /function unwrapBuyerOnboardingFormDataCandidate/)
assert.match(agencyPipelinePageSource, /function isOfferFlowBuyerOnboardingMigrationArtifact/)
assert.match(agencyPipelinePageSource, /function getMigrationGuardedBuyerOnboardingSnapshot/)
assert.match(agencyPipelinePageSource, /buyer_offer_link/)
assert.match(agencyPipelinePageSource, /canonical_buyer_offer_link/)
assert.match(agencyPipelinePageSource, /async function persistBuyerProfileOnboardingFormData/)
assert.match(agencyPipelinePageSource, /buildBuyerProfileHydrationFormData\(\{\s*lead: selectedLead,\s*diagnostic: selectedLeadLifecycleDiagnostic,\s*\}\)/)
assert.match(buyerProfileHydrationSource, /getMigrationGuardedBuyerOnboardingSnapshot\(rawPayload\?\.buyerOnboarding\)/)
assert.match(buyerProfileHydrationSource, /getMigrationGuardedBuyerOnboardingSnapshot\(lead\?\.buyer_onboarding\)/)
assert.match(agencyPipelinePageSource, /\.from\('onboarding_form_data'\)/)
assert.match(saveBuyerProfileSource, /persistBuyerProfileOnboardingFormData/)
assert.match(saveBuyerProfileSource, /setSelectedLeadLifecycleDiagnostic/)
assert.match(saveBuyerProfileSource, /getMigrationGuardedBuyerOnboardingSnapshot\(rawPayload\?\.buyerOnboarding\)/)
assert.match(saveBuyerProfileSource, /getMigrationGuardedBuyerOnboardingSnapshot\(selectedLead\?\.buyer_onboarding\)/)
assert.doesNotMatch(agencyPipelinePageSource, /selectedLeadLifecycleDiagnostic\?\.onboarding\?\.form_data \|\|/)
assert.match(agencyPipelinePageSource, /data-testid="buyer-profile-onboarding-fields"/)
assert.match(agencyPipelinePageSource, /This profile mirrors the buyer onboarding form fields/)
assert.match(agencyPipelinePageSource, /Download onboarding form/)
assert.match(agencyPipelinePageSource, /downloadBuyerOnboardingForm/)
assert.match(agencyPipelinePageSource, /id="buyer-profile-onboarding-form"/)
assert.match(agencyPipelinePageSource, /onSubmit=\{handleSaveBuyerProfile\}/)
assert.match(agencyPipelinePageSource, /Save profile/)
assert.match(agencyPipelinePageSource, /PURCHASER_ENTITY_OPTIONS/)
assert.match(agencyPipelinePageSource, /BUYER_PROFILE_FINANCE_TYPE_OPTIONS/)
assert.match(agencyPipelinePageSource, /updateBuyerProfileOnboardingField/)
assert.match(agencyPipelinePageSource, /handleToggleBuyerProfileMultiSelect/)
assert.match(agencyPipelinePageSource, /handleAddBuyerProfileRepeatableRow/)
assert.match(agencyPipelinePageSource, /buyer-onboarding-document/)
assert.match(agencyPipelinePageSource, /data-buyer-onboarding-pdf-style/)
assert.match(agencyPipelinePageSource, /document\.head\.appendChild\(styleElement\)/)
assert.match(agencyPipelinePageSource, /pdfStage\.querySelector\('\.buyer-onboarding-document'\)/)
assert.match(agencyPipelinePageSource, /buildBuyerOnboardingBrandingRows/)
assert.match(agencyPipelinePageSource, /organisationLogoDarkUrl/)
assert.match(agencyPipelinePageSource, /selectedLeadBuyerProfileModel\.sections\.map/)

assert.match(clientOnboardingSource, /function resolveBuyerOnboardingTheme/)
assert.match(clientOnboardingSource, /function BuyerBrandBar/)
assert.match(clientOnboardingSource, /resolveOnboardingBranding\([\s\S]*payload\?\.branding[\s\S]*payload\?\.organisation\?\.settingsJson\?\.agencyOnboarding\?\.branding[\s\S]*payload\?\.transaction/)
assert.match(clientOnboardingSource, /style=\{onboardingTheme\.cssVars\}/)
assert.match(clientOnboardingSource, /<BuyerBrandBar brand=\{onboardingBrand\} \/>/)
assert.match(clientOnboardingSource, /--buyer-brand-action/)
assert.match(clientOnboardingSource, /bg-\[var\(--buyer-brand-action\)\]/)
assert.match(onboardingVisualStepSource, /function resolveOnboardingHeaderTheme/)
assert.match(onboardingVisualStepSource, /style=\{resolveOnboardingHeaderTheme\(brand\)\}/)
assert.match(onboardingVisualStepSource, /linear-gradient\(90deg,var\(--buyer-brand-primary\) 0%,var\(--buyer-brand-action\) 100%\)/)

assert.match(buyerOnboardingBackfillAuditSql, /migration\/backfill audit only/i)
assert.match(buyerOnboardingBackfillAuditSql, /buyer_offer_link/)
assert.match(buyerOnboardingBackfillAuditSql, /canonical_buyer_offer_link/)
assert.match(buyerOnboardingBackfillAuditSql, /offer_artifact_skip/)
assert.match(buyerOnboardingBackfillAuditSql, /true_buyer_onboarding_candidate/)
assert.match(buyerOnboardingBackfillAuditSql, /ambiguous_manual_review/)
assert.doesNotMatch(buyerOnboardingBackfillAuditSql, /\b(update|insert|delete|upsert|merge)\b/i)

assert.match(agencyPipelinePageSource, /data-testid="simplified-viewing-planner"/)
assert.match(agencyPipelinePageSource, /Plan the viewing in 3 simple steps\./)
assert.match(agencyPipelinePageSource, /const viewingPlannerWizardSteps = \[/)
assert.match(agencyPipelinePageSource, /label: 'Date & Time'/)
assert.match(simplifiedViewingPlannerSource, /xl:grid-cols-\[minmax\(420px,1\.15fr\)_minmax\(360px,0\.85fr\)\]/)
assert.match(simplifiedViewingPlannerSource, /aspect-\[16\/9\]/)
assert.match(simplifiedViewingPlannerSource, /<span className="sr-only">Select date<\/span>/)
assert.match(simplifiedViewingPlannerSource, /xl:grid-cols-\[minmax\(280px,0\.8fr\)_minmax\(520px,1\.2fr\)\]/)
assert.match(simplifiedViewingPlannerSource, /xl:grid-cols-\[minmax\(480px,1fr\)_minmax\(360px,0\.85fr\)\]/)
assert.doesNotMatch(simplifiedViewingPlannerSource, /Choose the preferred date and time for each property\./)
assert.doesNotMatch(simplifiedViewingPlannerSource, /Choose how this viewing should be handled\./)
assert.match(simplifiedViewingPlannerSource, /Already confirmed/)
assert.match(simplifiedViewingPlannerSource, /Seller needs to RSVP/)
assert.match(agencyPipelinePageSource, /Viewing scheduled/)
assert.match(agencyPipelinePageSource, /RSVP request sent/)
assert.match(agencyPipelinePageSource, /viewingPlannerPropertyScheduleById/)
assert.match(agencyPipelinePageSource, /slotStartTime/)
assert.match(agencyPipelinePageSource, /slotEndTime/)

assert.doesNotMatch(agencyPipelinePageSource, /\{ key: 'offers', label: 'Offers' \}/)
assert.doesNotMatch(agencyPipelinePageSource, /activeTab === 'offers'/)
assert.doesNotMatch(agencyPipelinePageSource, /setActiveTab\('offers'\)/)
assert.doesNotMatch(agencyPipelinePageSource, /\?tab=offers/)
assert.doesNotMatch(agencyPipelinePageSource, /Open Offers/)
assert.doesNotMatch(agencyPipelinePageSource, /Offers \/ Transactions/)
assert.doesNotMatch(agencyPipelinePageSource, /lead_workspace_offers_tab/)

assert.match(
  packageSource,
  /"test:buyer-process-agent-leads-onboarding-otp-phase7": "node scripts\/buyer-process-agent-leads-onboarding-otp-phase7\.test\.mjs"/,
)

console.log('Buyer process Phase 7 Agent Leads onboarding / OTP workspace contract passed.')
