import assert from 'node:assert/strict'
import fs from 'node:fs'
const watchdog = fs.readFileSync('../supabase/functions/legal-document-watchdog/index.ts', 'utf8'); const reconcile = fs.readFileSync('scripts/legal-document-phase5-reconcile.mjs', 'utf8'); const incident = fs.readFileSync('scripts/legal-document-phase5-acknowledge-incident.mjs', 'utf8'); const scale = fs.readFileSync('scripts/legal-document-phase5-scale-gate.mjs', 'utf8'); const smoke = fs.readFileSync('scripts/legal-document-phase5-watchdog-staging-smoke.mjs', 'utf8'); const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))
const workflow = fs.readFileSync('../.github/workflows/legal-document-watchdog.yml', 'utf8'); const supabaseConfig = fs.readFileSync('../supabase/config.toml', 'utf8')
for (const token of ['legal_document_watchdog_started', 'legal_document_watchdog_completed', 'legal_document_watchdog_failed', 'system_health_snapshots', 'UNRESOLVED_GENERATION_FAILURES', 'STALE_SIGNING_PACKETS', 'COMPLETED_PACKET_FINAL_ARTIFACT_MISSING', 'FINAL_ARTIFACT_EVIDENCE_MISSING', 'FINAL_DELIVERY_INCOMPLETE', 'PORTAL_PUBLICATION_MISSING']) assert.match(watchdog, new RegExp(token))
assert.match(reconcile, /LEGAL_DOCUMENT_RECONCILIATION_WRITE/); assert.match(reconcile, /safeToArchive/); assert.match(reconcile, /manualReview/); assert.match(incident, /LEGAL_DOCUMENT_INCIDENT_WRITE/); assert.match(incident, /legal_document_incident_acknowledgement_v1/); assert.doesNotMatch(scale, /\.insert\(|\.update\(|\.upsert\(|\.delete\(/); assert.match(smoke, /LEGAL_DOCUMENT_WATCHDOG_STAGING_WRITE/)
assert.match(workflow, /cron: '17 \* \* \* \*'/); assert.match(workflow, /SUPABASE_STAGING_SERVICE_ROLE_KEY/); assert.match(workflow, /--max-time 90/); assert.match(supabaseConfig, /\[functions\.legal-document-watchdog\][\s\S]*verify_jwt = false/)
for (const name of ['test:legal-documents-phase5', 'verify:legal-documents:phase5-watchdog-staging', 'verify:legal-documents:phase5-reconcile', 'verify:legal-documents:phase5-scale', 'export:legal-documents:phase5-evidence', 'acknowledge:legal-documents:phase5-incident']) assert.ok(pkg.scripts?.[name], `Missing ${name}`)
console.log('Legal document Phase 5 operations contract passed')
