import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const listingSource = fs.readFileSync(path.join(process.cwd(), 'src/pages/AgentListingDetail.jsx'), 'utf8')
const emailSource = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/functions/send-email/index.ts'), 'utf8')
const signingSource = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/functions/listing-mandate-signing/index.ts'), 'utf8')
const atomicCompletionMigration = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/migrations/20260917084424_listing_seller_document_signing_atomic_completion.sql'), 'utf8')
const signingPackMigration = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/migrations/20260917192158_seller_signing_pack_snapshot.sql'), 'utf8')
const atomicPackSignatureMigration = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/migrations/20260917192826_seller_signing_pack_atomic_signature.sql'), 'utf8')
const signingPageSource = fs.readFileSync(path.join(process.cwd(), 'src/pages/ListingMandateSigning.jsx'), 'utf8')
const deliveryHandler = listingSource.match(/async function sendListingMandateSigningLink\(\)[\s\S]*?\n  }\n\n  async function handleStartListingMandateDocument/)?.[0] || ''

assert.match(deliveryHandler, /invokeEdgeFunction\('listing-mandate-signing'/)
assert.match(deliveryHandler, /const selectedDocuments = \['mandate'\]/)
assert.match(deliveryHandler, /selectedDocuments,/)
assert.doesNotMatch(deliveryHandler, /generateSigningLinks\(/)
assert.match(signingSource, /action === "issue"/)
assert.match(signingSource, /type: "seller_mandate_sent"/)
assert.match(signingSource, /token_hash: await hash\(rawToken\)/)
assert.match(signingSource, /const signingPackVersion = "seller_signing_pack_v1"/)
assert.match(signingSource, /function signingPack\(/)
assert.match(signingSource, /signing_pack_snapshot: packSnapshot/)
assert.match(signingSource, /signing_pack_digest: packDigest/)
assert.match(signingSource, /signingPackFrozenAt: session\.signing_pack_frozen_at/)
assert.match(signingSource, /action === "sign-pack"/)
assert.match(signingSource, /complete_private_listing_seller_signing_pack/)
assert.match(signingSource, /action === "status" \|\| action === "revoke"/)
assert.match(signingSource, /status: "revoked"/)
assert.match(signingSource, /admin\.rpc\("complete_private_listing_seller_document_signing"/)
assert.match(atomicCompletionMigration, /for update/)
assert.match(atomicCompletionMigration, /insert into public\.private_listing_documents/)
assert.match(atomicCompletionMigration, /update public\.private_listing_mandate_signing_sessions/)
assert.match(atomicCompletionMigration, /revoke all on function .* from public, anon, authenticated/i)
assert.match(atomicCompletionMigration, /grant execute .* to service_role/i)
assert.match(signingPackMigration, /add column if not exists signing_pack_snapshot jsonb not null/i)
assert.match(signingPackMigration, /signing_pack_digest text/i)
assert.match(signingPackMigration, /signing_pack_frozen_at timestamptz/i)
assert.match(atomicPackSignatureMigration, /for v_document_key in select jsonb_array_elements_text\(v_session\.selected_documents\)/)
assert.match(atomicPackSignatureMigration, /update public\.private_listing_mandate_signing_sessions/)
assert.match(atomicPackSignatureMigration, /revoke all on function .* from public, anon, authenticated/i)
assert.match(listingSource, /Send signing link/)
assert.match(listingSource, /Fixed Rand amount/)
assert.match(listingSource, /commissionBasis/)
assert.match(listingSource, /Send seller documents/)
assert.match(listingSource, /<option value="sole">Exclusive<\/option>/)
assert.doesNotMatch(listingSource, /Seller document link status/)
assert.match(listingSource, /resolveOnboardingBranding\(listingRecord\?\.branding, currentWorkspace\?\.branding, currentWorkspace\)/)
assert.match(listingSource, /function buildSellerSigningPackSnapshot\(/)
assert.match(listingSource, /function getCombinedSellerSigningPackReadiness\(/)
assert.match(listingSource, /isPropertyDisclosureDigitallyComplete\(form\.propertyDisclosure \|\| form\.property_disclosure \|\| \{\}\)/)
assert.match(listingSource, /getSellerSigningDocumentOptions\(\)\.options/)
assert.match(listingSource, /selected\.includes\('disclosure'\) \|\| selected\.includes\('fica'\)/)
assert.match(listingSource, /signers: signingPlan\.recipients\.map/)
assert.match(listingSource, /signingPack: buildSellerSigningPackSnapshot\(selected\)/)
assert.match(deliveryHandler, /signingPack: buildSellerSigningPackSnapshot\(selectedDocuments\)/)
assert.match(signingPageSource, /resolveOnboardingBranding\(mandate\.branding\)/)
assert.match(signingPageSource, /Seller document centre/)
assert.match(signingPageSource, /Secure signing/)
assert.match(signingPageSource, /Your signing pack/)
assert.match(signingPageSource, /action: 'sign-pack'/)
assert.match(signingPageSource, /one signature/)
assert.match(signingPageSource, /commissionLabel/)
assert.match(signingSource, /mandate\.commissionBasis/)
assert.match(emailSource, /handleSellerMandateSentEmail/)
assert.doesNotMatch(emailSource, /SELLER_MANDATE_SIGNING_LINKS_RETIRED/)

console.log('listing mandate signing delivery phase 3 tests passed')
