import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const listingSource = fs.readFileSync(path.join(process.cwd(), 'src/pages/AgentListingDetail.jsx'), 'utf8')
const emailSource = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/functions/send-email/index.ts'), 'utf8')
const signingSource = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/functions/listing-mandate-signing/index.ts'), 'utf8')
const atomicCompletionMigration = fs.readFileSync(path.join(process.cwd(), '..', 'supabase/migrations/20260917084424_listing_seller_document_signing_atomic_completion.sql'), 'utf8')
const signingPageSource = fs.readFileSync(path.join(process.cwd(), 'src/pages/ListingMandateSigning.jsx'), 'utf8')
const deliveryHandler = listingSource.match(/async function sendListingMandateSigningLink\(\)[\s\S]*?\n  }\n\n  async function handleStartListingMandateDocument/)?.[0] || ''

assert.match(deliveryHandler, /invokeEdgeFunction\('listing-mandate-signing'/)
assert.match(deliveryHandler, /selectedDocuments: selectedDocuments\.length \? selectedDocuments : \['mandate'\]/)
assert.doesNotMatch(deliveryHandler, /generateSigningLinks\(/)
assert.match(signingSource, /action === "issue"/)
assert.match(signingSource, /type: "seller_mandate_sent"/)
assert.match(signingSource, /token_hash: await hash\(rawToken\)/)
assert.match(signingSource, /action === "status" \|\| action === "revoke"/)
assert.match(signingSource, /status: "revoked"/)
assert.match(signingSource, /admin\.rpc\("complete_private_listing_seller_document_signing"/)
assert.match(atomicCompletionMigration, /for update/)
assert.match(atomicCompletionMigration, /insert into public\.private_listing_documents/)
assert.match(atomicCompletionMigration, /update public\.private_listing_mandate_signing_sessions/)
assert.match(atomicCompletionMigration, /revoke all on function .* from public, anon, authenticated/i)
assert.match(atomicCompletionMigration, /grant execute .* to service_role/i)
assert.match(listingSource, /Send signing link/)
assert.match(listingSource, /Fixed Rand amount/)
assert.match(listingSource, /commissionBasis/)
assert.match(listingSource, /Send seller documents/)
assert.match(listingSource, /<option value="sole">Exclusive<\/option>/)
assert.doesNotMatch(listingSource, /Seller document link status/)
assert.match(listingSource, /resolveOnboardingBranding\(listingRecord\?\.branding, currentWorkspace\?\.branding, currentWorkspace\)/)
assert.match(signingPageSource, /resolveOnboardingBranding\(mandate\.branding\)/)
assert.match(signingPageSource, /Seller document centre/)
assert.match(signingPageSource, /Secure signing/)
assert.match(signingPageSource, /Your signing progress/)
assert.match(signingPageSource, /commissionLabel/)
assert.match(signingSource, /mandate\.commissionBasis/)
assert.match(emailSource, /handleSellerMandateSentEmail/)
assert.doesNotMatch(emailSource, /SELLER_MANDATE_SIGNING_LINKS_RETIRED/)

console.log('listing mandate signing delivery phase 3 tests passed')
