import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const dashboardPath = path.join(root, 'src/services/bondDashboardService.js')
const dashboardComponentPath = path.join(root, 'src/components/bond/BondDashboard.jsx')
const queuePanelComponentPath = path.join(root, 'src/components/bond/BondQueuePanel.jsx')
const queueItemComponentPath = path.join(root, 'src/components/bond/BondApplicationQueueItem.jsx')
const scopeBannerComponentPath = path.join(root, 'src/components/bond/BondReportingScopeBanner.jsx')
const queuePath = path.join(root, 'src/services/bondOperationalQueueService.js')
const commandCenterPath = path.join(root, 'src/services/bondCommandCenterService.js')
const diagnosticsPath = path.join(root, 'src/services/bondOperationalDiagnosticsService.js')
const workflowOwnershipPath = path.join(root, 'src/services/bondFinanceWorkflowOwnershipService.js')
const assignmentPath = path.join(root, 'src/services/bondAssignmentService.js')
const hierarchyPath = path.join(root, 'src/services/bondWorkspaceHierarchyService.js')

const dashboardSource = fs.readFileSync(dashboardPath, 'utf8')
const dashboardComponentSource = fs.readFileSync(dashboardComponentPath, 'utf8')
const queuePanelComponentSource = fs.readFileSync(queuePanelComponentPath, 'utf8')
const queueItemComponentSource = fs.readFileSync(queueItemComponentPath, 'utf8')
const scopeBannerComponentSource = fs.readFileSync(scopeBannerComponentPath, 'utf8')
const queueSource = fs.readFileSync(queuePath, 'utf8')
const commandCenterSource = fs.readFileSync(commandCenterPath, 'utf8')
const diagnosticsSource = fs.readFileSync(diagnosticsPath, 'utf8')
const workflowOwnershipSource = fs.readFileSync(workflowOwnershipPath, 'utf8')
const assignmentSource = fs.readFileSync(assignmentPath, 'utf8')
const hierarchySource = fs.readFileSync(hierarchyPath, 'utf8')

assert.match(dashboardSource, /export async function getBondDashboardContext/)
assert.match(dashboardSource, /export async function getBondDashboardSummary/)
assert.match(dashboardSource, /export async function getBondDashboardQueues/)
assert.match(dashboardSource, /export async function getBondDashboardReportingScope/)
assert.match(dashboardSource, /export async function getBondDashboardFilters/)

assert.match(dashboardSource, /resolveBondOperationalQueues/)
assert.match(dashboardSource, /canViewFinanceWorkflow/)
assert.match(dashboardSource, /resolveEffectiveBondAssignment/)
assert.match(dashboardSource, /getUserBondScope/)
assert.match(dashboardSource, /getWorkspaceHierarchy/)
assert.match(dashboardComponentSource, /bondCommandCenterService/)
assert.match(dashboardComponentSource, /BondHqCommandCentre/)
assert.match(dashboardComponentSource, /snapshot\.reportingScope/)
assert.match(dashboardComponentSource, /loading/i)
assert.match(dashboardComponentSource, /missing_workspace_context/)
assert.match(queueItemComponentSource, /transactionId/)
assert.match(queueItemComponentSource, /applicationReference/)
assert.match(queueItemComponentSource, /clientName/)
assert.match(scopeBannerComponentSource, /Independent workspace/)

assert.match(dashboardSource, /my_applications/)
assert.match(dashboardSource, /processing_queue/)
assert.match(dashboardSource, /missing_documents/)
assert.match(dashboardSource, /bank_feedback/)
assert.match(dashboardSource, /submission_readiness/)
assert.match(dashboardSource, /overdue_applications/)
assert.match(dashboardSource, /compliance_review/)
assert.match(dashboardSource, /manager_escalations/)

assert.match(queueSource, /resolveBondOperationalQueues/)
assert.match(queueSource, /awaiting_grant/)
assert.match(queueSource, /grant_received/)
assert.match(queueSource, /grant_signed/)
assert.match(queueSource, /ready_for_instruction/)
assert.match(commandCenterSource, /operationalDiagnostics/)
assert.match(commandCenterSource, /buildBondOperationalDiagnostics/)
assert.match(diagnosticsSource, /buildBondOperationalDiagnostics/)
assert.match(diagnosticsSource, /remediationPlan/)
assert.match(diagnosticsSource, /actionHref/)
assert.match(diagnosticsSource, /missing_grant_document/)
assert.match(diagnosticsSource, /missing_instruction_evidence/)
assert.match(workflowOwnershipSource, /resolveFinanceWorkflowOwners/)
assert.match(assignmentSource, /resolveEffectiveBondAssignment/)
assert.match(hierarchySource, /resolveBondScopeForMembership/)
assert.doesNotMatch(dashboardComponentSource, /assigned_bond_originator_email/)
assert.doesNotMatch(dashboardComponentSource, /\bbond_originator\b/)

assert.doesNotMatch(dashboardSource, /drop\s+table/i)
assert.doesNotMatch(dashboardSource, /drop\s+column/i)
assert.doesNotMatch(diagnosticsSource, /drop\s+table/i)
assert.doesNotMatch(diagnosticsSource, /drop\s+column/i)

console.log('Phase 4 bond dashboard safety test passed')
