import assert from 'node:assert/strict'
import fs from 'node:fs'

function read(path) {
  return fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
}

const listingDetail = read('src/pages/AgentListingDetail.jsx')

assert.match(listingDetail, /Where this listing appears/)
assert.match(listingDetail, /Manage Property24/)
assert.match(listingDetail, /previewProperty24Listing/)
assert.match(listingDetail, /publishProperty24Listing/)
assert.match(listingDetail, /refreshProperty24ListingStatus/)
assert.match(listingDetail, /updateProperty24ListingStatus/)
assert.match(listingDetail, /pullProperty24ListingLeads/)
assert.match(listingDetail, /Refresh Status/)
assert.match(listingDetail, /Update Status/)
assert.match(listingDetail, /Check Leads/)
assert.match(listingDetail, /Import Leads/)
assert.match(listingDetail, /Listing data status/)
assert.match(listingDetail, /openPropertyDetailsFromMarketing/)
assert.match(listingDetail, /Back to Marketing/)
assert.match(listingDetail, /\/lead-sources\/property24\.png/)
assert.match(listingDetail, /\/lead-sources\/private-property\.jpeg/)
assert.match(listingDetail, /View Live Listing/)
assert.doesNotMatch(listingDetail, /Manage how this property appears and where it is published\./)
assert.doesNotMatch(listingDetail, /name="Arch9 Listing Page"/)
assert.match(listingDetail, /Preview Readiness/)
assert.match(listingDetail, /Publish New Listing/)
assert.match(listingDetail, /Update Existing Listing/)
assert.match(listingDetail, /Status actions unlock after Property24 returns a listing reference/)
assert.match(listingDetail, /property24HasReference/)
assert.match(listingDetail, /property24HasPreviewBlockers/)
assert.match(listingDetail, /disabled=\{Boolean\(property24Action\) \|\| !property24HasReference\}/)
assert.match(listingDetail, /PROPERTY24_STATUS_UPDATE_OPTIONS/)
assert.match(listingDetail, /refresh: 'true'/)
assert.match(listingDetail, /applyLeads/)
assert.match(listingDetail, /PROPERTY24_LISTING_API_BASE_PATH/)
assert.match(listingDetail, /supabase\.auth\.getSession/)
assert.match(listingDetail, /Authorization: `Bearer \$\{accessToken\}`/)
assert.match(listingDetail, /getProperty24ApiMessage/)
assert.match(listingDetail, /property24PreviewCounts/)
assert.match(listingDetail, /property24LeadImportCounts/)
assert.match(listingDetail, /property24StatusCheck/)
assert.match(listingDetail, /Published to Property24/)
assert.doesNotMatch(listingDetail, /PROPERTY24_API_INTERNAL_TOKEN/)

const apiSource = read('server/property24/api.js')
assert.match(apiSource, /canUseBrowserProperty24ListingAuth/)
assert.match(apiSource, /authenticateBrowserProperty24ListingRequest/)
assert.match(apiSource, /Only the assigned agent or an agency admin can publish this listing to Property24/)
assert.match(apiSource, /\['previewListing', 'publishListing', 'listingStatus', 'updateListingStatus', 'listingLeads'\]/)
assert.match(apiSource, /recordProperty24ListingSync/)

console.log('Property24 listing publish UI contract passed')
