import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const migration = await readFile('../supabase/migrations/202607190004_transaction_progress_notification_reliability_phase4.sql', 'utf8')
const schedulerMigration = await readFile('../supabase/migrations/20260719130913_transaction_progress_supabase_schedule.sql', 'utf8')
const webhook = await readFile('../supabase/functions/resend-webhook/index.ts', 'utf8')
const config = await readFile('../supabase/config.toml', 'utf8')
const cron = await readFile('api/cron/transaction-progress-notifications.js', 'utf8')
const vercel = JSON.parse(await readFile('vercel.json', 'utf8'))
const dispatcher = await readFile('../supabase/functions/send-email/handlers/transactionProgressDispatch.ts', 'utf8')
const service = await readFile('src/services/transactionSharedProgressService.js', 'utf8')
const envExample = await readFile('.env.example', 'utf8')

assert.match(migration, /create table if not exists public\.notification_recipient_preferences/i)
assert.match(migration, /create table if not exists public\.notification_provider_webhook_events/i)
assert.match(migration, /unique \(provider, provider_event_id\)/i)
assert.match(migration, /bridge_notification_recipient_preference_guard_phase4/i)
assert.match(migration, /email_disabled_by_preference/i)
assert.match(migration, /whatsapp_disabled_by_preference/i)
assert.match(migration, /bridge_set_notification_recipient_preference_phase4/i)
assert.match(migration, /bridge_transaction_progress_notification_health_phase4/i)
assert.match(migration, /failedRetryable/)
assert.match(migration, /failedExhausted/)

assert.equal(vercel.crons, undefined)
assert.match(schedulerMigration, /create extension if not exists pg_cron/i)
assert.match(schedulerMigration, /create extension if not exists pg_net/i)
assert.match(schedulerMigration, /arch9-transaction-progress-assurance-5m/)
assert.match(schedulerMigration, /'\*\/5 \* \* \* \*'/)
assert.match(schedulerMigration, /vault\.decrypted_secrets/)
assert.match(schedulerMigration, /transaction_progress_dispatch/)
assert.match(schedulerMigration, /bridge_run_transaction_progress_assurance_phase7/)
assert.match(cron, /CRON_SECRET/)
assert.match(cron, /SUPABASE_SERVICE_ROLE_KEY/)
assert.match(cron, /transaction_progress_dispatch/)
assert.match(dispatcher, /isServiceRequest/)
assert.match(dispatcher, /p_transaction_id: transactionId \|\| null/)

assert.match(config, /\[functions\.resend-webhook\][\s\S]*verify_jwt = false/)
assert.match(webhook, /RESEND_WEBHOOK_SECRET/)
assert.match(webhook, /verifySvixSignature/)
assert.match(webhook, /constantTimeEqual/)
assert.match(webhook, /Math\.abs\(Date\.now\(\) \/ 1000 - timestampSeconds\) > 300/)
assert.match(webhook, /email\.delivered/)
assert.match(webhook, /email\.bounced/)
assert.match(webhook, /email\.complained/)
assert.match(webhook, /email\.suppressed/)
assert.match(webhook, /notification_recipient_preferences/)

assert.match(service, /getNotificationRecipientPreferences/)
assert.match(service, /setNotificationRecipientPreference/)
assert.match(service, /getTransactionProgressNotificationHealth/)
assert.match(envExample, /RESEND_WEBHOOK_SECRET=/)
assert.match(envExample, /CRON_SECRET=/)

console.log('Transaction progress notification Phase 4 scheduling, webhook, suppression, preference, and health checks passed.')
