import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const migration = await readFile('../supabase/migrations/202607190006_transaction_progress_controlled_rollout_phase7.sql', 'utf8')
const schedulerMigration = await readFile('../supabase/migrations/202607230010_transaction_progress_scheduler_proof_phase8.sql', 'utf8')
const cron = await readFile('api/cron/transaction-progress-notifications.js', 'utf8')
const service = await readFile('src/services/transactionSharedProgressService.js', 'utf8')
const diagnosticsPage = await readFile('src/pages/PlatformDiagnosticsPage.jsx', 'utf8')
const audit = await readFile('scripts/transaction-cross-module-propagation-audit.mjs', 'utf8')
const vercel = JSON.parse(await readFile('vercel.json', 'utf8'))

assert.match(migration, /create table if not exists public\.transaction_progress_rollout_settings/i)
assert.match(migration, /create table if not exists public\.transaction_progress_rollout_history/i)
assert.match(migration, /create table if not exists public\.transaction_progress_rollout_runs/i)
assert.match(migration, /rollout_mode in \('off', 'audit_only', 'canary', 'full'\)/i)
assert.match(migration, /'production', 'audit_only', 10, false/i)
assert.match(migration, /bridge_transaction_progress_rollout_state_phase7/i)
assert.match(migration, /bridge_set_transaction_progress_rollout_phase7/i)
assert.match(migration, /bridge_run_transaction_progress_assurance_phase7/i)
assert.match(migration, /Full rollout requires zero propagation gaps and three clean canary runs/i)
assert.match(migration, /Rollout safety gate failed/i)
assert.match(migration, /v_setting\.rollout_mode = 'off'/i)
assert.match(migration, /v_setting\.rollout_mode = 'audit_only'/i)
assert.match(migration, /v_setting\.rollout_mode = 'canary'/i)
assert.match(migration, /v_decision := 'full_repair'/i)
assert.match(migration, /abs\(mod\(hashtextextended/i)
assert.match(migration, /staleClientVisible/i)
assert.match(migration, /exhaustedEmailNotifications/i)

assert.equal(vercel.crons, undefined)
assert.match(schedulerMigration, /arch9-transaction-progress-recovery-5m/i)
assert.match(schedulerMigration, /bridge_run_transaction_progress_schedule_phase8/i)
assert.match(schedulerMigration, /supabase_cron_phase8/i)
assert.match(schedulerMigration, /notification_dispatch_enabled/i)
assert.match(cron, /bridge_run_transaction_progress_assurance_phase7/)
assert.doesNotMatch(cron, /rest\/v1\/rpc\/bridge_reconcile_transaction_progress_phase6/)
assert.match(cron, /rolloutMode/)
assert.match(cron, /rolloutDecision/)
assert.match(cron, /alertRequired/)

assert.match(service, /getTransactionProgressRolloutState/)
assert.match(service, /setTransactionProgressRollout/)
assert.match(service, /runTransactionProgressRolloutAssurance/)
assert.match(diagnosticsPage, /Rollout mode/)
assert.match(diagnosticsPage, /Start canary/)
assert.match(diagnosticsPage, /Promote to full/)
assert.match(diagnosticsPage, /Pause/)
assert.match(diagnosticsPage, /Change reason/)
assert.match(audit, /transaction_progress_rollout_settings/)
assert.match(audit, /transaction_progress_rollout_runs/)
assert.match(audit, /alertRuns/)

console.log('Transaction progress Phase 7 audit-only, canary, full rollout, rollback, safety-gate, and audit checks passed.')
