import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const migration = fs.readFileSync(path.join(root, '../supabase/migrations/202605240012_unified_invites.sql'), 'utf8')
const branchInviteHardeningMigration = fs.readFileSync(path.join(root, '../supabase/migrations/202606090011_harden_branch_invites.sql'), 'utf8')
const branchInviteAcceptanceMigration = fs.readFileSync(path.join(root, '../supabase/migrations/202606090012_branch_invite_acceptance_metadata.sql'), 'utf8')
const inviteCommissionReconciliationMigration = fs.readFileSync(path.join(root, '../supabase/migrations/202606090013_invite_commission_profile_reconciliation.sql'), 'utf8')
const inviteBranchMembersMigration = fs.readFileSync(path.join(root, '../supabase/migrations/202606090014_invite_branch_members_sync.sql'), 'utf8')
const inviteService = fs.readFileSync(path.join(root, 'src/services/inviteService.js'), 'utf8')
const workspaceService = fs.readFileSync(path.join(root, 'src/services/workspaceService.js'), 'utf8')
const app = fs.readFileSync(path.join(root, 'src/App.jsx'), 'utf8')
const inviteResolver = fs.readFileSync(path.join(root, 'src/pages/InviteResolver.jsx'), 'utf8')
const agencyBranchWorkspacePage = fs.readFileSync(path.join(root, 'src/pages/agency/AgencyBranchWorkspacePage.jsx'), 'utf8')
const api = fs.readFileSync(path.join(root, 'src/lib/api.js'), 'utf8')
const agentInviteService = fs.readFileSync(path.join(root, 'src/lib/agentInviteService.js'), 'utf8')
const attorneyFirmInvitations = fs.readFileSync(path.join(root, 'src/services/attorneyFirmInvitations.js'), 'utf8')

assert.match(migration, /create table if not exists public\.invites/i, 'canonical invites table must exist')
assert.match(migration, /invite_type in \(/i, 'invite type constraint must exist')
assert.match(migration, /status in \('pending', 'accepted', 'declined', 'expired', 'revoked', 'cancelled'\)/i, 'invite status lifecycle must exist')
assert.match(migration, /create or replace function public\.bridge_accept_invite/i, 'canonical acceptance RPC must exist')
assert.match(migration, /invite_email_mismatch/i, 'RPC must enforce signed-in email validation')
assert.match(migration, /for update/i, 'acceptance must lock invite rows during mutation')
assert.match(migration, /membership_created_from_invite/i, 'workspace membership creation must be audited')
assert.match(migration, /participant_created_from_invite/i, 'transaction participant creation must be audited')
assert.match(migration, /attorney_firm_membership_created_from_invite/i, 'attorney firm invite compatibility must be audited')
assert.match(migration, /transaction_participants_invitation_token_idx/i, 'transaction invite compatibility columns must be indexed')
assert.match(migration, /from public\.workspace_invites/i, 'workspace invite compatibility backfill must exist')
assert.match(migration, /from public\.attorney_firm_invitations/i, 'attorney invite compatibility backfill must exist')

assert.match(inviteService, /export async function acceptInvite/i, 'invite service must expose acceptInvite')
assert.match(inviteService, /assertInviteCanBeAccepted/i, 'client-side invite validation helper must exist')
assert.match(inviteService, /invite_email_mismatch/i, 'client-side email mismatch guard must exist')
assert.match(inviteService, /resolveInviteAction/i, 'invite action resolver must exist')
assert.match(inviteService, /bridge_accept_invite/i, 'invite service must call canonical RPC')

assert.match(workspaceService, /createInvite\(/, 'workspace invite creation must mirror canonical invites')
assert.match(workspaceService, /acceptInvite\(inviteToken/, 'workspace invite acceptance must use canonical acceptInvite first')

assert.match(app, /path="\/invite\/:token"/, 'unified invite route must exist')
assert.match(app, /InviteResolver/, 'InviteResolver must be mounted')

assert.match(api, /bridge_create_invite/, 'transaction invites must be mirrored into canonical invites')
assert.match(api, /bridge_accept_invite/, 'stakeholder invite acceptance must try canonical flow')
assert.match(api, /Sign in as \$\{invitedEmail\}/, 'legacy stakeholder acceptance must enforce email matching')

assert.match(agentInviteService, /return `\$\{origin\}\/invite\/\$\{token\}`/, 'agent invite links must route through /invite/:token')
assert.match(attorneyFirmInvitations, /createInvite\(/, 'attorney firm invite creation must mirror canonical invites')
assert.match(attorneyFirmInvitations, /bridge_accept_invite/, 'attorney firm invite acceptance must try canonical flow')

assert.match(branchInviteHardeningMigration, /create or replace function public\.bridge_create_invite/i, 'branch invite hardening must redefine canonical invite creation')
assert.match(branchInviteHardeningMigration, /target_workspace_required/i, 'branch invites must require a target workspace')
assert.match(branchInviteHardeningMigration, /branch_workspace_mismatch/i, 'branch invites must validate branch ownership by workspace')
assert.match(branchInviteHardeningMigration, /branch_scope_required/i, 'branch managers must be forced into branch-scoped invites')
assert.match(branchInviteHardeningMigration, /branch_scope_denied/i, 'branch managers must not invite into other branches')
assert.match(branchInviteHardeningMigration, /role_not_permitted/i, 'invite creation must enforce role hierarchy')
assert.match(branchInviteHardeningMigration, /duplicate_pending_invite/i, 'invite creation must block duplicate pending branch invites')
assert.match(branchInviteHardeningMigration, /invites_pending_workspace_branch_email_idx/i, 'pending branch invite duplicate checks must have a supporting index')

assert.match(branchInviteAcceptanceMigration, /create or replace function public\.bridge_accept_invite/i, 'branch invite acceptance must redefine canonical invite acceptance')
assert.match(branchInviteAcceptanceMigration, /existing_membership_branch_mismatch/i, 'acceptance must reject existing memberships assigned to another branch')
assert.match(branchInviteAcceptanceMigration, /invite_branch_mismatch/i, 'branch mismatch rejections must be audited')
assert.match(branchInviteAcceptanceMigration, /v_invited_first_name/i, 'acceptance must read invited first-name metadata')
assert.match(branchInviteAcceptanceMigration, /v_invited_last_name/i, 'acceptance must read invited last-name metadata')
assert.match(branchInviteAcceptanceMigration, /first_name = coalesce\(nullif\(first_name, ''\), v_invited_first_name\)/i, 'acceptance must preserve existing first names while filling blank membership names')
assert.match(branchInviteAcceptanceMigration, /phone_number = coalesce\(nullif\(phone_number, ''\), v_invited_phone\)/i, 'acceptance must fill blank profile phone numbers from invite metadata')
assert.match(branchInviteAcceptanceMigration, /v_invite\.status <> 'pending'/i, 'acceptance must preserve pending-status validation')
assert.match(branchInviteAcceptanceMigration, /invite_email_mismatch/i, 'acceptance must preserve email mismatch validation')
assert.match(branchInviteAcceptanceMigration, /participant_created_from_invite/i, 'acceptance must preserve transaction participant compatibility')

assert.match(inviteCommissionReconciliationMigration, /create or replace function public\.bridge_reconcile_invite_commission_profile/i, 'commission reconciliation trigger function must exist')
assert.match(inviteCommissionReconciliationMigration, /to_regclass\('public\.organisation_user_commission_profiles'\) is null/i, 'commission reconciliation must no-op when commission profile table is absent')
assert.match(inviteCommissionReconciliationMigration, /organisation_user_id = coalesce\(organisation_user_id, v_membership\.id\)/i, 'commission reconciliation must link email profile to organisation membership')
assert.match(inviteCommissionReconciliationMigration, /user_id = coalesce\(user_id, v_user_id\)/i, 'commission reconciliation must link email profile to accepted user')
assert.match(inviteCommissionReconciliationMigration, /commission_profile_linked_from_invite/i, 'commission reconciliation must audit successful profile linking')
assert.match(inviteCommissionReconciliationMigration, /commission_profile_email_duplicate_deactivated/i, 'commission reconciliation must handle stale email-only duplicates')
assert.match(inviteCommissionReconciliationMigration, /create trigger invites_reconcile_commission_profile/i, 'accepted invites must trigger commission profile reconciliation')
assert.match(inviteCommissionReconciliationMigration, /set status = status,\s*updated_at = now\(\)/i, 'commission reconciliation migration must backfill accepted invites')

assert.match(inviteBranchMembersMigration, /create or replace function public\.bridge_sync_invite_branch_member/i, 'branch member sync trigger function must exist')
assert.match(inviteBranchMembersMigration, /to_regclass\('public\.branch_members'\) is null/i, 'branch member sync must no-op when branch_members table is absent')
assert.match(inviteBranchMembersMigration, /new\.target_branch_id is null/i, 'branch member sync must only run for branch-scoped invites')
assert.match(inviteBranchMembersMigration, /coalesce\(ou\.primary_branch_id, ou\.branch_id, new\.target_branch_id\) = new\.target_branch_id/i, 'branch member sync must respect accepted membership branch scope')
assert.match(inviteBranchMembersMigration, /on conflict \(branch_id, user_id\) do update/i, 'branch member sync must upsert by branch and user')
assert.match(inviteBranchMembersMigration, /branch_member_synced_from_invite/i, 'branch member sync must audit successful syncs')
assert.match(inviteBranchMembersMigration, /create trigger invites_sync_branch_member/i, 'accepted invites must trigger branch member sync')
assert.match(inviteBranchMembersMigration, /when v_membership_role in \('super_admin', 'admin', 'admin_staff'\) then 'admin'/i, 'branch member sync must map admin roles into branch_members role constraint')
assert.match(inviteBranchMembersMigration, /set status = status,\s*updated_at = now\(\)/i, 'branch member sync migration must backfill accepted branch invites')

assert.match(agencyBranchWorkspacePage, /BRANCH_AGENT_ROLE_VALUES/i, 'branch invite UI must define branch-safe role options')
assert.match(agencyBranchWorkspacePage, /branchAgentRoleOptions\.map/i, 'branch invite UI must render branch-safe role options')
assert.doesNotMatch(agencyBranchWorkspacePage, /AGENT_ROLE_OPTIONS\.map\(\(option\)/, 'branch invite UI must not expose every organisation role')
assert.match(inviteResolver, /existing_membership_branch_mismatch/i, 'invite resolver must handle branch mismatch errors')
assert.match(inviteResolver, /Branch Transfer Required/i, 'invite resolver must explain branch-transfer-required state')
assert.match(inviteResolver, /InviteDetailList/i, 'invite resolver must render workspace, branch, and role details')

console.log('unified invite architecture tests passed')
