// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import RecruitmentSignupModal from '../RecruitmentSignupModal'
import HomeSeekersJoin from '../../HomeSeekersJoin'

const response = (body, status = 200) => ({ ok: status < 400, status, json: async () => body })
const context = { branding: { organisationName: 'Home Seekers' } }
let requests
beforeEach(() => {
  requests = []
  vi.stubGlobal('fetch', vi.fn(async (_url, options) => {
    const body = JSON.parse(options.body); requests.push(body)
    return response(body.action === 'context' ? context : body.action === 'send_verification' ? { verificationRequested: true } : { accepted: true, contactAccepted: true, verificationRequired: true })
  }))
})
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); vi.restoreAllMocks() })
async function fill() {
  await screen.findByRole('form', { name: 'Create applicant account' })
  for (const [label,value] of [['First name','Fixture'],['Surname','Applicant'],['Email address','applicant@example.test'],['Mobile number','+27821234567'],['Password','FixturePass123']]) fireEvent.change(screen.getByLabelText(new RegExp(`^${label} `)), { target: { value } })
  fireEvent.click(screen.getByRole('checkbox'))
}
it('replaces the Home Seekers bottom form and opens signup from a Join button', async () => {
  render(<HomeSeekersJoin />)
  expect(screen.queryByRole('button', { name: 'Send my application' })).toBeNull()
  fireEvent.click(screen.getAllByRole('button', { name: /^Join Home Seekers$/i })[0])
  await screen.findByRole('dialog', { name: 'Join Home Seekers' })
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Create account & continue' }))
  await screen.findByText('Your contact details are saved')
  const signup = requests.find((request) => request.action === 'signup')
  expect(signup.submissionKey).toMatch(/^[0-9a-f-]{36}$/)
  expect(screen.getByText('Your full application has not been submitted.')).toBeTruthy()
})
it('validates consent, contact details and password without saving an incomplete request', async () => {
  render(<RecruitmentSignupModal open onClose={() => {}} organisationName="Home Seekers" />)
  await screen.findByRole('form', { name: 'Create applicant account' })
  fireEvent.click(screen.getByRole('button', { name: 'Create account & continue' }))
  expect(await screen.findByText(/Enter your first name/)).toBeTruthy()
  expect(requests).toHaveLength(1)
})
it('retries the same contact and key after account failure while leaving password editable', async () => {
  fetch.mockImplementationOnce(async () => response(context)).mockImplementationOnce(async (_url, options) => {
    requests.push(JSON.parse(options.body)); return response({ contactAccepted: true, error: 'Fixture account unavailable' },503)
  })
  render(<RecruitmentSignupModal open onClose={() => {}} />)
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Create account & continue' }))
  await screen.findByText('Fixture account unavailable')
  expect(screen.getByLabelText(/^Email address /).readOnly).toBe(true)
  fireEvent.change(screen.getByLabelText(/^Password /), { target: { value: 'RetryFixture123' } })
  fireEvent.click(screen.getByRole('button', { name: 'Retry account creation' }))
  await screen.findByText('Your contact details are saved')
  expect(requests[1].submissionKey).toBe(requests[0].submissionKey)
  expect(requests[1].contact).toEqual(requests[0].contact)
  expect(requests[1].password).toBe('RetryFixture123')
})
it('previews the next step without sending credentials or claiming a CRM save', async () => {
  fetch.mockImplementation(async (_url, options) => { requests.push(JSON.parse(options.body)); return response({ ...context, preview: true }) })
  render(<RecruitmentSignupModal open onClose={() => {}} />)
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Preview next step' }))
  await screen.findByText('Preview complete')
  expect(requests).toEqual([{ action: 'context' }])
  expect(screen.queryByText('Your contact details are saved')).toBeNull()
})
it('clears the password on close and reopens with contact details intact', async () => {
  const close = vi.fn()
  const view = render(<RecruitmentSignupModal open onClose={close} />)
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Show password' }))
  expect(screen.getByLabelText(/^Password /).type).toBe('text')
  fireEvent.click(screen.getByRole('button', { name: 'Close dialog' }))
  expect(close).toHaveBeenCalledTimes(1)
  view.rerender(<RecruitmentSignupModal open={false} onClose={close} />)
  view.rerender(<RecruitmentSignupModal open onClose={close} />)
  await screen.findByRole('form', { name: 'Create applicant account' })
  expect(screen.getByLabelText(/^Password /).value).toBe('')
  expect(screen.getByLabelText(/^Password /).type).toBe('password')
  expect(screen.getByLabelText(/^Email address /).value).toBe('applicant@example.test')
})
it('blocks duplicate submits and closing while saving, then permits a safe retry after an uncertain response', async () => {
  let reject
  fetch.mockImplementationOnce(async () => response(context)).mockImplementationOnce(async (_url, options) => {
    requests.push(JSON.parse(options.body)); return new Promise((_resolve, fail) => { reject = fail })
  })
  const close = vi.fn()
  render(<RecruitmentSignupModal open onClose={close} />)
  await fill()
  const form = screen.getByRole('form', { name: 'Create applicant account' })
  fireEvent.submit(form); fireEvent.submit(form)
  fireEvent.click(screen.getByRole('button', { name: 'Close dialog' }))
  expect(close).not.toHaveBeenCalled()
  expect(requests).toHaveLength(1)
  await act(async () => reject(new Error('Fixture lost response')))
  await screen.findByText('Fixture lost response')
  fireEvent.click(screen.getByRole('button', { name: 'Retry account creation' }))
  await screen.findByText('Your contact details are saved')
  expect(requests[1].submissionKey).toBe(requests[0].submissionKey)
})
it('shows an unavailable link instead of allowing an account request', async () => {
  fetch.mockImplementation(async () => response({ error: 'Fixture expired link' },410))
  render(<RecruitmentSignupModal open onClose={() => {}} />)
  await screen.findByText('Fixture expired link')
  await waitFor(() => expect(screen.queryByRole('form')).toBeNull())
})

const verifiedApplicant = {emailVerification:'verified',stage:'lead_received',applicationSubmitted:false,contact:{firstName:'Fixture',lastName:'Applicant',email:'applicant@example.test',phone:'+27821234567'}}
const codeContext = { ...context, verificationMethod: 'email_code' }
async function fillHomeContact() {
  await screen.findByRole('form', { name: 'Start recruitment enquiry' })
  for (const [label,value] of [['First name','Fixture'],['Surname','Applicant'],['Email address','applicant@example.test'],['Mobile number','+27821234567']]) fireEvent.change(screen.getByLabelText(new RegExp(`^${label} `)), { target: { value } })
  fireEvent.click(screen.getByRole('checkbox'))
}
it('Home Seekers saves contact without a password and continues with a code in the same popup', async () => {
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    return response(body.action==='context'?codeContext:body.action==='signup'?{accepted:true,contactAccepted:true,verificationRequired:true}:body.action==='send_verification'?{verificationRequested:true,resendAfterSeconds:60,codeLength:8}:{applicant:verifiedApplicant})
  })
  render(<HomeSeekersJoin />)
  fireEvent.click(screen.getAllByRole('button',{name:/^Join Home Seekers$/i})[0])
  await fillHomeContact()
  expect(screen.queryByLabelText(/^Password/)).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  await waitFor(()=>expect(screen.getByRole('button',{name:'Verify & continue'}).disabled).toBe(false))
  expect(screen.getByLabelText('Email address').readOnly).toBe(true)
  expect(screen.queryByRole('button',{name:'Sign in with a password'})).toBeNull()
  expect(screen.getByRole('button',{name:/Request a new code in/}).disabled).toBe(true)
  expect(requests.find(r=>r.action==='signup')).not.toHaveProperty('password')
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'12345678'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.getByRole('dialog',{name:'Join Home Seekers'})).toBeTruthy()
  expect(requests.at(-1).submissionKey).toBe(requests.find(r=>r.action==='signup').submissionKey)
  expect(requests.filter(r=>r.action==='signup')).toHaveLength(1)
})
it('Home Seekers keeps the saved lead through delivery failure, expiry and a successful resend', async () => {
  let sends=0, verifies=0
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context') return response(codeContext)
    if(body.action==='signup') return response({accepted:true,contactAccepted:true,verificationRequired:true})
    if(body.action==='send_verification') return ++sends===1?response({error:'Saved enquiry; email unavailable',retryAfterSeconds:60},503):response({verificationRequested:true,resendAfterSeconds:60})
    return ++verifies===1?response({error:'This code is invalid or has expired. Request a new code and try again.'},401):response({applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fillHomeContact();fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  await screen.findByText('Saved enquiry; email unavailable')
  expect(screen.getByText('Your contact details are saved')).toBeTruthy()
  await waitFor(()=>expect(screen.getByRole('button',{name:/Request a new code in/}).disabled).toBe(true))
  vi.spyOn(Date, 'now').mockReturnValue(Date.now() + 61000)
  fireEvent.click(await screen.findByRole('button',{name:'Send a new email code'}, { timeout: 2000 }))
  await screen.findByText(/Check your inbox for a verification code/)
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'654321'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByText(/This code is invalid or has expired/)
  expect(screen.getByText('Your contact details are saved')).toBeTruthy()
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'123456'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.filter(r=>r.action==='signup')).toHaveLength(1)
  expect(requests.filter(r=>r.action==='send_verification')).toHaveLength(2)
})
it('Home Seekers returning applicants request an email code without another contact capture', async () => {
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    return response(body.action==='context'?codeContext:body.action==='send_verification'?{verificationRequested:true}:{applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await screen.findByRole('form',{name:'Start recruitment enquiry'})
  fireEvent.click(screen.getByRole('button',{name:'Already started? Continue with an email code'}))
  fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'applicant@example.test'}})
  fireEvent.click(screen.getByRole('button',{name:'Send a new email code'}))
  await screen.findByText(/Check your inbox for a verification code/)
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'123456'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.map(r=>r.action)).toEqual(['context','send_verification','verify_email'])
})
it('Home Seekers retries preparation after capture with the same details and receipt key', async () => {
  let attempts=0
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context') return response(codeContext)
    if(body.action==='send_verification') return response({verificationRequested:true})
    return ++attempts===1?response({contactAccepted:true,error:'Contact saved; verification preparation unavailable'},503):response({accepted:true,contactAccepted:true,verificationRequired:true})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fillHomeContact();fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  await screen.findByText('Contact saved; verification preparation unavailable')
  expect(screen.getByText('Your contact details are saved')).toBeTruthy()
  expect(screen.getByLabelText(/^Email address/).readOnly).toBe(true)
  fireEvent.click(screen.getByRole('button',{name:'Retry & continue'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  const captures=requests.filter(r=>r.action==='signup')
  expect(captures).toHaveLength(2)
  expect(captures[1]).toEqual(captures[0])
  expect(captures[1]).not.toHaveProperty('password')
})
it('Home Seekers saves changed questionnaire answers before signing out', async () => {
  const saved={...verifiedApplicant,contactSubmissionKey:'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'}
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context')return response({...codeContext,applicant:saved})
    if(body.action==='save_profile')return response({saved:true,applicant:{...saved,profile:{answers:body.answers,page:body.page,complete:false},profileRevision:1}})
    return response({signedOut:true})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  fireEvent.change(screen.getByLabelText('Preferred name'),{target:{value:'Save before signing out'}})
  fireEvent.click(screen.getByRole('button',{name:'Sign out of applicant account'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  expect(requests.map(r=>r.action)).toEqual(['context','save_profile','sign_out'])
  expect(requests[1]).toMatchObject({intent:'save',answers:{preferredName:'Save before signing out'}})
})
it.each(['123456','12345678'])('sends a verification request after capture and opens the original enquiry only after successful code %s', async (code) => {
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context')return response(context)
    if(body.action==='signup')return response({accepted:true,contactAccepted:true,verificationRequired:true})
    if(body.action==='send_verification')return response({verificationRequested:true})
    return response({applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Create account & continue'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  await waitFor(()=>expect(screen.getByRole('button',{name:'Verify & continue'}).disabled).toBe(false))
  expect(requests.map(r=>r.action)).toEqual(['context','signup','send_verification'])
  expect(screen.queryByText('Email verified')).toBeNull()
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:code}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.getByLabelText(/First name/).value).toBe('Fixture')
  expect(screen.getByLabelText(/Surname/).value).toBe('Applicant')
  expect(requests.at(-1).submissionKey).toBe(requests.find(r=>r.action==='signup').submissionKey)
  expect(requests.at(-1)).not.toHaveProperty('password')
  expect(screen.queryByRole('button',{name:'Submit application'})).toBeNull()
})
it('offers existing-account sign-in after contact capture fails to create another account',async()=>{
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return body.action==='context'?response(context):body.action==='signup'?response({contactAccepted:true,error:'Contact saved; sign in to continue.'},503):response({applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Create account & continue'}))
  await screen.findByText('Contact saved; sign in to continue.')
  fireEvent.click(screen.getByRole('button',{name:'Already have an account? Sign in'}))
  await screen.findByRole('form',{name:'Sign in to applicant account'})
  expect(screen.getByLabelText('Email address').value).toBe('applicant@example.test')
  expect(screen.getByLabelText('Password').value).toBe('')
  fireEvent.change(screen.getByLabelText('Password'),{target:{value:'ExistingFixture123'}})
  fireEvent.click(screen.getByRole('button',{name:'Sign in & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.at(-1)).toMatchObject({action:'sign_in',email:'applicant@example.test',password:'ExistingFixture123'})
  expect(requests.filter(r=>r.action==='signup')).toHaveLength(1)
})
it('restores a verified enquiry from context after reload and clears personal data on applicant sign-out',async()=>{
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return response(body.action==='context'?{...context,applicant:verifiedApplicant}:{signedOut:true})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.queryByRole('form',{name:'Create applicant account'})).toBeNull()
  expect(requests).toEqual([{action:'context'}])
  fireEvent.click(screen.getByRole('button',{name:'Sign out of applicant account'}))
  await screen.findByRole('form',{name:'Sign in to applicant account'})
  expect(screen.queryByText('Fixture Applicant')).toBeNull()
  expect(screen.getByLabelText('Email address').value).toBe('')
  expect(requests.at(-1)).toEqual({action:'sign_out'})
})
it('keeps the saved enquiry usable after email delivery failure or an expired code',async()=>{
  let delivered=false
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context')return response(context)
    if(body.action==='signup')return response({accepted:true,contactAccepted:true,verificationRequired:true})
    if(body.action==='send_verification'){if(!delivered){delivered=true;return response({error:'Fixture email unavailable'},503)}return response({verificationRequested:true})}
    return response({error:'Fixture expired code'},401)
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Create account & continue'}))
  await screen.findByText('Fixture email unavailable')
  fireEvent.click(screen.getByRole('button',{name:'Send a new email code'}))
  await screen.findByText(/Check your inbox for a verification code/)
  expect(screen.queryByText('Fixture email unavailable')).toBeNull()
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'654321'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByText('Fixture expired code')
  expect(screen.getByText('Your contact details are saved')).toBeTruthy()
  expect(screen.queryByText('Email verified')).toBeNull()
})
it('prevents closing during applicant sign-in and clears the password after rejection',async()=>{
  let reject
  fetch.mockImplementationOnce(async()=>response(context)).mockImplementationOnce(()=>new Promise((_resolve,fail)=>{reject=fail}))
  const close=vi.fn();render(<RecruitmentSignupModal open onClose={close} />)
  await screen.findByRole('form',{name:'Create applicant account'})
  fireEvent.click(screen.getByRole('button',{name:'Already have an account? Sign in'}))
  fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'applicant@example.test'}})
  fireEvent.change(screen.getByLabelText('Password'),{target:{value:'FixturePass123'}})
  fireEvent.click(screen.getByRole('button',{name:'Sign in & continue'}))
  fireEvent.click(screen.getByRole('button',{name:'Close dialog'}));expect(close).not.toHaveBeenCalled()
  await act(async()=>reject(new Error('Fixture rejected login')))
  await screen.findByText('Fixture rejected login')
  expect(screen.getByLabelText('Password').value).toBe('')
})
it('previews code entry and verified enquiry without sending credentials, creating accounts or claiming a saved contact',async()=>{
  fetch.mockImplementation(async(_url,options)=>{requests.push(JSON.parse(options.body));return response({...context,preview:true})})
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Preview next step'}))
  await screen.findByText('Preview complete')
  fireEvent.click(screen.getByRole('button',{name:'Preview email verification'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'123456'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.queryByText('Verification preview')).toBeNull()
  expect(screen.queryByText('Preview — no account or enquiry will be created.')).toBeNull()
  expect(screen.queryByText('Verified contact enquiry')).toBeNull()
  expect(screen.queryByText('Email verified. Your full application has not been submitted.')).toBeNull()
  expect(screen.queryByText('Your contact details are saved')).toBeNull()
  expect(requests).toEqual([{action:'context'}])
  expect(screen.queryByRole('button',{name:'Back to preview'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Restart preview'}))
  await screen.findByRole('form',{name:'Create applicant account'})
  expect(requests).toEqual([{action:'context'}])
})

it.each(['123 456', '1234 5678'])('Home Seekers accepts the complete pasted code %s and focuses a missing code without requesting account details', async (pasted) => {
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    return response(body.action==='context'?codeContext:body.action==='send_verification'?{verificationRequested:true}:body.action==='signup'?{accepted:true,contactAccepted:true,verificationRequired:true}:{applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fillHomeContact();fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  await waitFor(()=>expect(screen.getByRole('button',{name:'Verify & continue'}).disabled).toBe(false))
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  const code=screen.getByLabelText('Verification code')
  expect(document.activeElement).toBe(code)
  expect(code.getAttribute('aria-invalid')).toBe('true')
  expect(screen.getByRole('alert').textContent).toBe('Enter the six- or eight-digit code from your email.')
  expect(requests.filter(r=>r.action==='verify_email')).toHaveLength(0)
  fireEvent.paste(code,{clipboardData:{getData:()=>pasted}})
  expect(code.value).toBe(pasted.replace(/\D/g,''))
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.at(-1)).toMatchObject({action:'verify_email',code:pasted.replace(/\D/g,''),submissionKey:requests.find(r=>r.action==='signup').submissionKey})
})

it('Home Seekers corrects a mistyped email with fresh consent and a new receipt, keeping the earlier capture intact', async () => {
  let finishSend
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context')return response(codeContext)
    if(body.action==='signup')return response({accepted:true,contactAccepted:true,verificationRequired:true})
    if(body.action==='send_verification' && !finishSend)return new Promise(resolve=>{finishSend=()=>resolve(response({verificationRequested:true}))})
    if(body.action==='send_verification')return response({verificationRequested:true})
    return response({applicant:{...verifiedApplicant,contact:{...verifiedApplicant.contact,email:'correct@example.test'}}})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fillHomeContact();fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  const different=await screen.findByRole('button',{name:'Use a different email'})
  expect(different.disabled).toBe(true)
  await act(async()=>finishSend())
  fireEvent.click(different)
  await screen.findByRole('form',{name:'Start recruitment enquiry'})
  const email=screen.getByLabelText(/^Email address/)
  expect(email.readOnly).toBe(false)
  expect(email.value).toBe('')
  expect(screen.getByRole('checkbox').checked).toBe(false)
  expect(screen.getByLabelText(/^First name/).value).toBe('Fixture')
  fireEvent.change(email,{target:{value:'correct@example.test'}})
  fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  expect(requests.filter(r=>r.action==='signup')).toHaveLength(1)
  fireEvent.click(screen.getByRole('checkbox'))
  fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  await waitFor(()=>expect(screen.getByRole('button',{name:'Verify & continue'}).disabled).toBe(false))
  const captures=requests.filter(r=>r.action==='signup')
  expect(captures).toHaveLength(2)
  expect(captures[0].contact.email).toBe('applicant@example.test')
  expect(captures[1].contact.email).toBe('correct@example.test')
  expect(captures[1].submissionKey).not.toBe(captures[0].submissionKey)
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'12345678'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.at(-1)).toMatchObject({email:'correct@example.test',submissionKey:captures[1].submissionKey})
})

it('Home Seekers closes and reopens before verification with the same saved receipt and no extra capture or email', async () => {
  fetch.mockImplementation(async (_url,options) => {
    const body=JSON.parse(options.body);requests.push(body)
    return response(body.action==='context'?codeContext:body.action==='signup'?{accepted:true,contactAccepted:true,verificationRequired:true}:body.action==='send_verification'?{verificationRequested:true}:{applicant:verifiedApplicant})
  })
  const close=vi.fn(),view=render(<RecruitmentSignupModal open onClose={close} />)
  await fillHomeContact();fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
  await waitFor(()=>expect(screen.getByRole('button',{name:'Verify & continue'}).disabled).toBe(false))
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'123456'}})
  fireEvent.click(screen.getByRole('button',{name:'Close dialog'}))
  expect(close).toHaveBeenCalledTimes(1)
  view.rerender(<RecruitmentSignupModal open={false} onClose={close} />)
  view.rerender(<RecruitmentSignupModal open onClose={close} />)
  await screen.findByRole('form',{name:'Verify applicant email'})
  expect(screen.getByLabelText('Email address').value).toBe('applicant@example.test')
  expect(screen.getByLabelText('Verification code').value).toBe('')
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'12345678'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.map(r=>r.action)).toEqual(['context','signup','send_verification','context','verify_email'])
  expect(requests.at(-1).submissionKey).toBe(requests[1].submissionKey)
})

it('Home Seekers reopens a submitted application as a receipt without another capture or submission', async () => {
  const applicant={...verifiedApplicant,applicationSubmitted:true,applicationSubmittedAt:'2026-10-10T12:00:00Z',submittedApplication:{answers:{packagePreference:'decide_later'}}}
  fetch.mockImplementation(async (_url,options) => {requests.push(JSON.parse(options.body));return response({...codeContext,applicant})})
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await screen.findByText('Application submitted')
  expect(screen.getByText(/has been received by Home Seekers/)).toBeTruthy()
  expect(screen.queryByRole('button',{name:'Submit application'})).toBeNull()
  expect(screen.queryByRole('button',{name:'Use a different email'})).toBeNull()
  expect(requests).toEqual([{action:'context'}])
})
