// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { act,cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import RecruitmentProfileQuestionnaire from '../RecruitmentProfileQuestionnaire'
import RecruitmentContactReceipt from '../RecruitmentContactReceipt'
import { validProfile } from './helpers/recruitmentProfileFixture'
const applicant={emailVerification:'verified',stage:'lead_received',applicationSubmitted:false,contact:{firstName:'Website',lastName:'Applicant',email:'website@example.test',phone:'+27821234567'}}
const response=(body,status=200)=>({ok:status<400,status,json:async()=>body})
let requests
beforeEach(()=>{
  requests=[]
  vi.stubGlobal('fetch',vi.fn(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return response({saved:true,applicant:{...applicant,profile:{version:'recruitment-profile-v1',country:'ZA',answers:body.answers,page:body.intent==='continue'?Math.min(body.page+1,3):body.page,complete:body.intent==='complete'},profileRevision:body.revision+1}})
  }))
})
afterEach(()=>{cleanup();vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks()})
const fill=(label,value)=>fireEvent.change(screen.getByLabelText(label),{target:{value}})
const next=()=>fireEvent.click(screen.getByRole('button',{name:'Save & continue'}))
const receipt='aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'
const homeApplicant={...applicant,contactSubmissionKey:receipt}
const homeProps={enhanced:true,applicant:homeApplicant,onSaved:()=>{},onBusy:()=>{},onClose:()=>{}}
const pause=async(ms=1600)=>{await act(async()=>{await vi.advanceTimersByTimeAsync(ms)})}
it('Home Seekers keeps older complete answers and asks for an explicit package preference before review',async()=>{
  const saved={...homeApplicant,profile:{answers:validProfile(),page:3,complete:true},profileRevision:4}
  render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={saved} />)
  expect(screen.getByRole('heading',{name:'Employment, address & start date',level:4})).toBeTruthy()
  expect(screen.getAllByRole('radio')).toHaveLength(4)
  expect(screen.getAllByRole('radio').every(input=>!input.checked)).toBe(true)
  expect(screen.getByLabelText(/^Current brokerage/).value).toBe('Fixture brokerage')
  fireEvent.click(screen.getByRole('button',{name:'Save & review'}))
  expect(requests).toHaveLength(0)
  expect(screen.getByText('Choose a package preference or decide later.')).toBeTruthy()
  expect(document.activeElement.id).toBe('recruitment-profile-packagePreference')
  fireEvent.click(screen.getByRole('radio',{name:/Decide later/}))
  fireEvent.click(screen.getByRole('button',{name:'Save & review'}))
  await screen.findByRole('heading',{name:'Review your application'})
  expect(requests[0]).toMatchObject({action:'save_profile',intent:'complete',revision:4,answers:{packagePreference:'decide_later'}})
  expect(screen.getByText('Home Seekers package preference')).toBeTruthy()
  expect(screen.getByText('Decide later')).toBeTruthy()
  expect(screen.getByText(/starting preference, not a commitment/)).toBeTruthy()
  expect(screen.getAllByRole('checkbox').every(input=>!input.checked)).toBe(true)
})
it('Home Seekers automatically saves and restores a changed package without submitting',async()=>{
  vi.useFakeTimers()
  const saved={...homeApplicant,profile:{answers:validProfile(),page:3,complete:false},profileRevision:4}
  const onSaved=vi.fn(),view=render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={saved} onSaved={onSaved} />)
  fireEvent.click(screen.getByRole('radio',{name:/Paid from your deals/}));await pause()
  expect(requests[0]).toMatchObject({intent:'save',revision:4,answers:{packagePreference:'deals'}})
  fireEvent.click(screen.getByRole('radio',{name:/Monthly debit order/}));await pause()
  expect(requests[1]).toMatchObject({intent:'save',revision:5,answers:{packagePreference:'monthly'}})
  const updated=onSaved.mock.calls.at(-1)[0]
  view.unmount();render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={updated} />)
  expect(screen.getByRole('radio',{name:/Monthly debit order/}).checked).toBe(true)
  expect(requests.some(row=>row.action==='submit_profile')).toBe(false)
})
it('other agencies finish the existing questionnaire without Home Seekers options',async()=>{
  render(<RecruitmentProfileQuestionnaire applicant={{...applicant,profile:{answers:validProfile(),page:3}}} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  expect(screen.queryByRole('group',{name:/Which Home Seekers option/})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Save & review'}))
  await screen.findByRole('heading',{name:'Review your application'})
  expect(requests[0].answers).not.toHaveProperty('packagePreference')
})
it('the Recruitment contact view labels the saved package as a non-binding preference',()=>{
  render(<RecruitmentContactReceipt lead={{contact_capture_json:{version:'recruitment-contact-v1'},applicant_draft_json:{version:'recruitment-profile-v1',answers:{...validProfile(),packagePreference:'upfront'}}}} />)
  expect(screen.getByText('Home Seekers package preference')).toBeTruthy()
  expect(screen.getByText('Annual upfront payment')).toBeTruthy()
  expect(screen.getByText(/starting preference, not a commitment/)).toBeTruthy()
})
it('Home Seekers automatically saves an incomplete draft and restores the saved step',async()=>{
  vi.useFakeTimers()
  const onSaved=vi.fn(), view=render(<RecruitmentProfileQuestionnaire {...homeProps} onSaved={onSaved} />)
  fill('Preferred name','Saved nickname')
  expect(screen.getByText(/Unsaved changes/)).toBeTruthy()
  await pause()
  expect(requests).toHaveLength(1)
  expect(requests[0]).toMatchObject({action:'save_profile',intent:'save',page:0,revision:0,answers:{preferredName:'Saved nickname',dateOfBirth:''}})
  expect(screen.getByText(/Draft saved at/)).toBeTruthy()
  const updated=onSaved.mock.calls[0][0]
  view.unmount();render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={{...updated,contactSubmissionKey:receipt}} />)
  expect(screen.getByLabelText('Preferred name').value).toBe('Saved nickname')
  expect(requests.some(row=>row.action==='submit_profile')).toBe(false)
})
it('Home Seekers keeps new typing during an automatic save and serializes the next revision',async()=>{
  vi.useFakeTimers()
  let resolve
  fetch.mockImplementationOnce((_url,options)=>{requests.push(JSON.parse(options.body));return new Promise(done=>{resolve=done})})
  render(<RecruitmentProfileQuestionnaire {...homeProps} />)
  fill('Preferred name','First answer');await pause()
  expect(screen.getByText('Saving draft…')).toBeTruthy()
  expect(screen.getByLabelText('Preferred name').closest('fieldset').disabled).toBe(false)
  fill('Preferred name','Latest answer')
  await act(async()=>resolve(response({saved:true,applicant:{...homeApplicant,profile:{answers:requests[0].answers,page:0,complete:false},profileRevision:1}})))
  expect(screen.getByLabelText('Preferred name').value).toBe('Latest answer')
  await pause()
  expect(requests[1]).toMatchObject({revision:1,answers:{preferredName:'Latest answer'}})
  expect(requests).toHaveLength(2)
})
it('Home Seekers retries the exact uncertain save before persisting more recent typing',async()=>{
  vi.useFakeTimers()
  fetch.mockImplementationOnce(async(_url,options)=>{requests.push(JSON.parse(options.body));throw new Error('Lost save acknowledgement')})
  render(<RecruitmentProfileQuestionnaire {...homeProps} />)
  fill('Preferred name','Committed answer');await pause()
  expect(screen.getByText('Lost save acknowledgement')).toBeTruthy()
  fill('Preferred name','Keep this latest answer');await pause(3000)
  expect(requests).toHaveLength(1)
  await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Retry saving draft'})))
  expect(requests[1]).toEqual(requests[0])
  expect(screen.getByLabelText('Preferred name').value).toBe('Keep this latest answer')
  await pause()
  expect(requests[2]).toMatchObject({revision:1,answers:{preferredName:'Keep this latest answer'}})
})
it('Home Seekers saves back navigation and prevents skipping required earlier answers',async()=>{
  vi.useFakeTimers()
  const onSaved=vi.fn()
  render(<RecruitmentProfileQuestionnaire {...homeProps} onSaved={onSaved} />)
  const nav=screen.getByRole('navigation',{name:'Questionnaire steps'})
  expect(within(nav).getByRole('button',{name:/Contact information/}).disabled).toBe(true)
  fill(/^Date of birth/,'1990-06-15')
  fireEvent.click(within(nav).getByRole('button',{name:/Professional & legal details/}))
  expect(screen.getByRole('heading',{name:'Professional & legal details',level:4})).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:'Back'}));await pause()
  expect(requests[0]).toMatchObject({intent:'save',page:1})
  expect(onSaved.mock.calls[0][0].profile.page).toBe(1)
})
it('Home Seekers warns on refresh only while answers are unsaved and focuses the first invalid field',async()=>{
  vi.useFakeTimers()
  render(<RecruitmentProfileQuestionnaire {...homeProps} />)
  fill('Preferred name','Unsaved nickname')
  const before=new Event('beforeunload',{cancelable:true});window.dispatchEvent(before)
  expect(before.defaultPrevented).toBe(true)
  await pause()
  const after=new Event('beforeunload',{cancelable:true});window.dispatchEvent(after)
  expect(after.defaultPrevented).toBe(false)
  next()
  expect(document.activeElement).toBe(screen.getByLabelText(/^Date of birth/))
  expect(requests).toHaveLength(1)
})
it('Home Seekers verifies again in the same form and saves the retained answers onto the original enquiry',async()=>{
  vi.useFakeTimers()
  const saved={...homeApplicant,profile:{answers:validProfile(),page:0,complete:false},profileRevision:4}
  let expired=true
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='send_verification')return response({verificationRequested:true})
    if(body.action==='verify_email')return response({applicant:saved})
    if(expired){expired=false;return response({error:'Session expired'},401)}
    return response({saved:true,applicant:{...saved,profile:{answers:body.answers,page:body.page,complete:false},profileRevision:5}})
  })
  render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={saved} />)
  fill('Preferred name','Retain my answers');await pause()
  expect(screen.getByText(/Your email session expired/)).toBeTruthy()
  const access=screen.getByRole('form',{name:'Verify applicant email'})
  expect(within(access).getByLabelText('Email address').readOnly).toBe(true)
  await act(async()=>fireEvent.click(within(access).getByRole('button',{name:'Send a new email code'})))
  fireEvent.change(within(access).getByLabelText('Verification code'),{target:{value:'12345678'}})
  await act(async()=>fireEvent.click(within(access).getByRole('button',{name:'Verify & continue'})))
  expect(screen.queryByRole('form',{name:'Verify applicant email'})).toBeNull()
  expect(screen.getByLabelText('Preferred name').value).toBe('Retain my answers')
  await pause()
  expect(requests.filter(row=>row.action==='send_verification'||row.action==='verify_email').every(row=>row.submissionKey===receipt)).toBe(true)
  expect(requests.at(-1)).toMatchObject({action:'save_profile',revision:4,answers:{preferredName:'Retain my answers'}})
  expect(requests.some(row=>row.action==='signup')).toBe(false)
})
it('Home Seekers retains local answers when re-verification finds a newer saved draft or another receipt',async()=>{
  vi.useFakeTimers()
  const saved={...homeApplicant,profile:{answers:validProfile(),page:0,complete:false},profileRevision:4}
  const newer={...saved,profileRevision:5,profile:{...saved.profile,answers:{...validProfile(),preferredName:'Other device'}}}
  let verified={...newer,contactSubmissionKey:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'}
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return body.action==='verify_email'?response({applicant:verified}):body.action==='resume'?response({applicant:newer}):response({error:'Session expired'},401)
  })
  render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={saved} />)
  fill('Preferred name','Unsaved local answer');await pause()
  const access=screen.getByRole('form',{name:'Verify applicant email'})
  fireEvent.change(within(access).getByLabelText('Verification code'),{target:{value:'12345678'}})
  await act(async()=>fireEvent.click(within(access).getByRole('button',{name:'Verify & continue'})))
  expect(screen.getByText(/This enquiry could not be reopened/)).toBeTruthy()
  expect(screen.getByLabelText('Preferred name').value).toBe('Unsaved local answer')
  verified=newer
  fireEvent.change(within(access).getByLabelText('Verification code'),{target:{value:'12345678'}})
  await act(async()=>fireEvent.click(within(access).getByRole('button',{name:'Verify & continue'})))
  expect(screen.getByText(/Your saved draft changed/)).toBeTruthy()
  expect(screen.getByLabelText('Preferred name').value).toBe('Unsaved local answer')
  await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Reload saved draft'})))
  expect(screen.getByLabelText('Preferred name').value).toBe('Other device')
  expect(requests.filter(row=>row.action==='save_profile')).toHaveLength(1)
})
it('Home Seekers reopens review after session expiry and requires fresh declarations',async()=>{
  const saved={...homeApplicant,profile:{answers:{...validProfile(),packagePreference:'decide_later'},page:3,complete:true},profileRevision:3}
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return body.action==='verify_email'?response({applicant:saved}):response({error:'Session expired'},401)
  })
  render(<RecruitmentProfileQuestionnaire {...homeProps} applicant={saved} />)
  for(const checkbox of screen.getAllByRole('checkbox'))fireEvent.click(checkbox)
  fireEvent.click(screen.getByRole('button',{name:'Submit application'}))
  const access=await screen.findByRole('form',{name:'Verify applicant email'})
  fireEvent.change(within(access).getByLabelText('Verification code'),{target:{value:'12345678'}})
  fireEvent.click(within(access).getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('heading',{name:'Review your application'})
  expect(screen.getAllByRole('checkbox').every(input=>!input.checked)).toBe(true)
  expect(requests.map(row=>row.action)).toEqual(['submit_profile','verify_email'])
})
it('walks through all personal and professional questions, saves each part and opens review without submitting automatically',async()=>{
  render(<RecruitmentProfileQuestionnaire applicant={applicant} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  expect(screen.getByLabelText(/^First name/).value).toBe('Website')
  fill(/^Date of birth/,'1990-06-15');fill('Middle name','Middle');fill('Preferred name','Alex');next()
  await screen.findByRole('heading',{name:'Contact information',level:4})
  expect(screen.getByLabelText(/^Email address/).readOnly).toBe(true)
  expect(screen.getByLabelText(/^Mobile country code/).value).toBe('+27')
  fill('WhatsApp country code','+44');fill('WhatsApp number','7700123456');next()
  await screen.findByRole('heading',{name:'Professional & legal details',level:4})
  fill(/^Years of experience/,'5');fill(/^License status/,'valid')
  fill(/^FFC number/,'FFC-FIXTURE-123');fill(/^FFC practitioner type/,'non_principal')
  fill(/^Properties listed/,'0');fill(/^Properties sold/,'999')
  fireEvent.click(within(screen.getByRole('group',{name:/South African citizen/})).getByLabelText('Yes'))
  fireEvent.click(within(screen.getByRole('group',{name:/sequestration or administration/})).getByLabelText('No'));next()
  await screen.findByRole('heading',{name:'Employment, address & start date',level:4})
  for(const [label,value] of [[/^Current brokerage/,'Fixture brokerage'],[/^How did you find/,'referral'],[/^Street address/,'123 Fixture Road'],[/^City \/ town/,'Pretoria'],[/^Province/,'Gauteng'],[/^Postal code/,'0001'],[/^Expected start date/,'2099-01-01']])fill(label,value)
  fireEvent.click(screen.getByRole('button',{name:'Save & review'}))
  await screen.findByRole('heading',{name:'Review your application'})
  expect(requests).toHaveLength(4);expect(requests.map(row=>row.revision)).toEqual([0,1,2,3])
  expect(requests.at(-1)).toMatchObject({action:'save_profile',page:3,intent:'complete',answers:{propertiesListed:'0',propertiesSold:'999',whatsappCountryCode:'+44',preferredName:'Alex'}})
  expect(screen.getByRole('button',{name:'Submit application'})).toBeTruthy()
  expect(requests.every(row=>row.action==='save_profile')).toBe(true)
})
it('blocks invalid age and reveals FFC requirements only for a valid licence',async()=>{
  const saved={...applicant,profile:{answers:validProfile(),page:2},profileRevision:3}
  render(<RecruitmentProfileQuestionnaire applicant={saved} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  expect(screen.getByLabelText(/^FFC number/)).toBeTruthy()
  fill(/^License status/,'pending');expect(screen.queryByLabelText(/^FFC number/)).toBeNull()
  next();await screen.findByRole('heading',{name:'Employment, address & start date',level:4})
  expect(requests[0].answers.ffcNumber).toBe('');expect(requests[0].answers.ffcType).toBe('')
  fireEvent.click(screen.getByRole('button',{name:'Back'}));fireEvent.click(screen.getByRole('button',{name:'Back'}));fireEvent.click(screen.getByRole('button',{name:'Back'}))
  fill(/^Date of birth/,'2099-01-01');next()
  expect(await screen.findByText('You must be at least 18 years old to apply.')).toBeTruthy()
  expect(requests).toHaveLength(1)
})
it('saves incomplete answers on close and restores them in a new questionnaire',async()=>{
  const close=vi.fn(),saved=vi.fn(),closeRequestRef={current:null}
  const view=render(<RecruitmentProfileQuestionnaire applicant={applicant} closeRequestRef={closeRequestRef} onSaved={saved} onBusy={()=>{}} onClose={close} />)
  fill('Preferred name','Saved nickname')
  await act(async()=>closeRequestRef.current())
  expect(close).toHaveBeenCalledTimes(1)
  expect(requests[0]).toMatchObject({intent:'save',page:0,answers:{preferredName:'Saved nickname',dateOfBirth:''}})
  const updated=saved.mock.calls[0][0]
  view.unmount();render(<RecruitmentProfileQuestionnaire applicant={updated} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  expect(screen.getByLabelText('Preferred name').value).toBe('Saved nickname')
})
it('does not close or claim a save when persistence fails and retries the same revision and answers',async()=>{
  fetch.mockImplementationOnce(async(_url,options)=>{requests.push(JSON.parse(options.body));throw new Error('Fixture connection lost')})
  const close=vi.fn();render(<RecruitmentProfileQuestionnaire applicant={applicant} onSaved={()=>{}} onBusy={()=>{}} onClose={close} />)
  fill('Preferred name','Keep my draft');fireEvent.click(screen.getByRole('button',{name:'Save & close'}))
  await screen.findByText('Fixture connection lost');expect(close).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button',{name:'Save & close'}))
  await waitFor(()=>expect(close).toHaveBeenCalledTimes(1))
  expect(requests[1]).toEqual(requests[0])
})
it('keeps a conflict visible and reloads the newer draft before permitting another save',async()=>{
  fetch.mockImplementationOnce(async()=>response({conflict:true,error:'Fixture draft changed'},409)).mockImplementationOnce(async(_url,options)=>{
    requests.push(JSON.parse(options.body));return response({applicant:{...applicant,profile:{answers:{...validProfile(),preferredName:'Other device'},page:0},profileRevision:7}})
  })
  render(<RecruitmentProfileQuestionnaire applicant={applicant} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  fill('Preferred name','Unsaved local name');fireEvent.click(screen.getByRole('button',{name:'Save & close'}))
  await screen.findByText('Fixture draft changed')
  expect(screen.getByRole('button',{name:'Save & continue'}).closest('fieldset').disabled).toBe(true)
  fireEvent.click(screen.getByRole('button',{name:'Reload saved draft'}))
  await screen.findByText('Saved progress reloaded.')
  expect(screen.getByLabelText('Preferred name').value).toBe('Other device')
  fireEvent.click(screen.getByRole('button',{name:'Save & close'}))
  await waitFor(()=>expect(requests.at(-1).revision).toBe(7))
})
it('allows exploring all questionnaire stages in preview without a remote save or a submitted claim',async()=>{
  const saved={...applicant,profile:{answers:validProfile(),page:3}}
  render(<RecruitmentProfileQuestionnaire applicant={saved} preview onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  fireEvent.click(screen.getByRole('button',{name:'Save & review'}))
  await screen.findByRole('heading',{name:'Review your application'})
  expect(fetch).not.toHaveBeenCalled()
  expect(screen.getByRole('button',{name:'Preview submission'})).toBeTruthy()
})
it('shows CRM questionnaire progress and self-declared answers without treating it as an application submission',()=>{
  render(<RecruitmentContactReceipt lead={{contact_capture_json:{version:'recruitment-contact-v1',firstName:'Website',lastName:'Applicant'},email_verification_status:'verified',applicant_draft_json:{version:'recruitment-profile-v1',complete:true,answers:validProfile()}}} />)
  expect(screen.getByText('Questionnaire saved — not submitted')).toBeTruthy()
  expect(screen.getByText('Draft answers supplied by the applicant. The full application has not been submitted.')).toBeTruthy()
  expect(screen.getByText('0')).toBeTruthy();expect(screen.queryByText('Application submitted')).toBeNull()
})
it('reloads a newer reviewed draft after a submission conflict and clears both declarations',async()=>{
  const saved={...applicant,profile:{version:'recruitment-profile-v1',country:'ZA',answers:validProfile(),page:3,complete:true},profileRevision:3}
  fetch.mockImplementationOnce(async()=>response({conflict:true,error:'Draft changed before submission'},409)).mockImplementationOnce(async()=>response({applicant:{...saved,profileRevision:4,profile:{...saved.profile,answers:{...validProfile(),preferredName:'Other device'}}}}))
  render(<RecruitmentProfileQuestionnaire applicant={saved} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  for(const checkbox of screen.getAllByRole('checkbox'))fireEvent.click(checkbox)
  fireEvent.click(screen.getByRole('button',{name:'Submit application'}))
  await screen.findByText('Draft changed before submission')
  fireEvent.click(screen.getByRole('button',{name:'Reload saved draft'}));await screen.findByText('Other device')
  expect(screen.getAllByRole('checkbox').every(input=>!input.checked)).toBe(true)
  expect(screen.getByRole('button',{name:'Submit application'}).disabled).toBe(false)
})
it('saves an edited review section and returns directly to review with declarations unchecked',async()=>{
  const saved={...applicant,profile:{version:'recruitment-profile-v1',country:'ZA',answers:validProfile(),page:3,complete:true},profileRevision:3}
  render(<RecruitmentProfileQuestionnaire applicant={saved} onSaved={()=>{}} onBusy={()=>{}} onClose={()=>{}} />)
  for(const checkbox of screen.getAllByRole('checkbox'))fireEvent.click(checkbox)
  fireEvent.click(screen.getByRole('button',{name:'Edit Professional & legal details'}))
  fill(/^Properties sold/,'0');fireEvent.click(screen.getByRole('button',{name:'Save & review'}))
  await screen.findByRole('heading',{name:'Review your application'})
  expect(requests[0]).toMatchObject({action:'save_profile',revision:3,page:2,intent:'complete',answers:{propertiesSold:'0'}})
  expect(screen.getAllByRole('checkbox').every(input=>!input.checked)).toBe(true)
})
