import { activateRecruitmentAgent } from '../../../services/recruitmentService'
import { onboardingChecks, recruitmentOnboardingDraft } from '../recruitmentOnboardingModel'
import { saveRecruitmentOnboarding } from '../../../services/recruitmentService'
// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import RecruitmentPage, { RecruitmentList, RecruitmentWorkspace } from '../RecruitmentPage'
import { recruitmentStartLocation } from '../recruitmentEntryModel'
import { createRecruitmentIntakeLink } from '../../../services/recruitmentIntakeService'
import { WorkspaceContext } from '../../../context/WorkspaceContextBase'
import { recruitmentLocalDate } from '../recruitmentSigningModel'
import { emptyRecruitmentLead, recruitmentReadiness } from '../recruitmentModel'
import { recruitmentReviewDraft } from '../recruitmentReviewModel'
import { approvalConfirmation } from '../recruitmentApprovalModel'
import RecruitmentJourney from '../RecruitmentJourney'
import { validProfile } from './helpers/recruitmentProfileFixture'
import { getRecruitmentJoiningOptions, recordRecruitmentContractSignature, approveRecruitmentApplication, getRecruitmentLead, saveRecruitmentLead, saveRecruitmentReview } from '../../../services/recruitmentService'
vi.mock('../../../services/recruitmentIntakeService', () => ({ createRecruitmentIntakeLink: vi.fn(), listRecruitmentIntakeLinks: vi.fn().mockResolvedValue([]), revokeRecruitmentIntakeLink: vi.fn() }))
vi.mock('../../../services/recruitmentService', () => ({ getRecruitmentInvitationStatus: vi.fn().mockResolvedValue({referenceStatus:'prepared',attempt:null}), sendRecruitmentInvitation: vi.fn(), getRecruitmentJoiningOptions: vi.fn().mockResolvedValue({ branches: [{id:'a1111111-1111-4111-8111-111111111111',name:'Head Office'}], commissionStructures: [] }), getRecruitmentJoiningConnections: vi.fn().mockResolvedValue({ applications: [], workspace: [] }), activateRecruitmentAgent: vi.fn(), getRecruitmentAgentAccessLink: vi.fn(), saveRecruitmentOnboarding: vi.fn(), uploadRecruitmentOnboardingDocument: vi.fn(), downloadRecruitmentOnboardingDocument: vi.fn(), recordRecruitmentContractDelivery: vi.fn(), recordRecruitmentContractSignature: vi.fn(), downloadRecruitmentSignedContract: vi.fn(), prepareRecruitmentContract: vi.fn(), downloadRecruitmentContract: vi.fn(), approveRecruitmentApplication: vi.fn(), getRecruitmentLead: vi.fn(), listRecruitmentLeads: vi.fn().mockResolvedValue([]), startRecruitmentReview: vi.fn(), saveRecruitmentReview: vi.fn(), saveRecruitmentLead: vi.fn(), uploadRecruitmentDocument: vi.fn(), openRecruitmentDocument: vi.fn() }))
afterEach(() => { cleanup(); vi.clearAllMocks() })
const lead = { ...emptyRecruitmentLead(), id: 'agent-1', name: 'Sam Agent', email: 'sam@example.test', phone: '0821234567', area: 'Pretoria', version: 1 }
const wrap = (element) => render(<MemoryRouter>{element}</MemoryRouter>)
it('requires review of matching enquiries and links a selected invitation without merging records', async () => {
  const matches = { leads: [{ id: 'prior', name: 'Prior Agent', status: 'lead_received' }], members: [], invites: [{ id: 'pending', type: 'branch_invite', role: 'agent' }, { id: 'privileged', role: 'principal' }, { id: 'linked', role: 'agent', linkedLeadId: 'prior' }] }
  const create = vi.fn().mockRejectedValueOnce(Object.assign(new Error('Review existing records.'), { outcome: 'review_required', matches })).mockResolvedValueOnce({ id: 'new' })
  wrap(<RecruitmentList leads={[]} openCreate onCreate={create} />)
  fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Sam Agent' } })
  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'sam@example.test' } })
  fireEvent.click(screen.getByRole('button', { name: 'Create Agent Lead' }))
  expect(await screen.findByRole('alert')).toHaveProperty('textContent', 'Review existing records.')
  expect(screen.getByRole('link', { name: 'Open recruitment record: Prior Agent' }).getAttribute('href')).toBe('/agency/recruitment/prior')
  expect(screen.getByRole('button', { name: 'Create Agent Lead' }).disabled).toBe(true)
  expect(within(screen.getByLabelText('Link an existing agent invitation')).getAllByRole('option')).toHaveLength(2)
  fireEvent.click(screen.getByRole('checkbox', { name: /I reviewed the matches/ }))
  fireEvent.change(screen.getByLabelText('Link an existing agent invitation'), { target: { value: 'pending' } })
  fireEvent.click(screen.getByRole('button', { name: 'Create Agent Lead' }))
  await waitFor(() => expect(create).toHaveBeenCalledTimes(2))
  expect(create.mock.calls[1][0]).toMatchObject({ email: 'sam@example.test', joining_invite_id: 'pending', joining_json: { reviewedMatches: true } })
  expect(create.mock.calls[1][0].intake_key).toBe(create.mock.calls[0][0].intake_key)
})
it('routes an existing active member to their profile and clears the match review when the email changes', async () => {
  const create = vi.fn().mockRejectedValue(Object.assign(new Error('Manage the existing member.'), { outcome: 'existing_member', matches: { leads: [], invites: [], members: [{ id: 'membership', userId: 'existing-user', role: 'agent' }, { id: 'admin-membership', userId: 'admin-user', role: 'admin' }] } }))
  wrap(<RecruitmentList leads={[]} openCreate onCreate={create} />)
  fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Sam Agent' } })
  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'sam@example.test' } })
  fireEvent.click(screen.getByRole('button', { name: 'Create Agent Lead' }))
  const profiles = await screen.findAllByRole('link', { name: 'Open existing agency member' })
  expect(profiles.map(profile => profile.getAttribute('href'))).toEqual(['/agency/agents/existing-user', '/settings/users'])
  expect(screen.getByRole('button', { name: 'Create Agent Lead' }).disabled).toBe(true)
  expect(screen.queryByRole('checkbox', { name: /I reviewed the matches/ })).toBeNull()
  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'different@example.test' } })
  expect(screen.queryByRole('link', { name: 'Open existing agency member' })).toBeNull()
  expect(screen.getByRole('button', { name: 'Create Agent Lead' }).disabled).toBe(false)
})
it('preserves the email identity of a linked legacy invitation', () => {
  wrap(<RecruitmentWorkspace lead={{ ...lead, joining_invite_id: 'legacy-invite' }} />)
  fireEvent.click(screen.getByRole('tab', { name: 'Agent Details' }))
  expect(screen.getByLabelText('Email').readOnly).toBe(true)
  expect(screen.getByLabelText('Email').value).toBe(lead.email)
})
it('saves planned setup with agent details and protects unsaved joining choices from other writes', async () => {
  const branch = 'a1111111-1111-4111-8111-111111111111', save = vi.fn()
  vi.mocked(getRecruitmentJoiningOptions).mockResolvedValueOnce({ branches: [{ id: branch, name: 'Head Office' }], commissionStructures: [] })
  wrap(<RecruitmentWorkspace lead={lead} organisationId="org" onSave={save} />)
  fireEvent.click(screen.getByRole('tab', { name: 'Agent Details' }))
  await screen.findByRole('option', { name: 'Head Office' })
  fireEvent.change(screen.getByLabelText('Intended branch'), { target: { value: branch } })
  fireEvent.change(screen.getByLabelText('Planned joining date'), { target: { value: '2026-10-15' } })
  fireEvent.click(screen.getByLabelText('Rentals'))
  expect(screen.getByRole('button', { name: 'Close Lead' }).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab', { name: 'Documents' }))
  expect(screen.getByLabelText('Upload CV').disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab', { name: 'Agent Details' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save Agent Details' }))
  expect(save).toHaveBeenCalledOnce()
  expect(save.mock.calls[0][0]).toMatchObject({ id: lead.id, version: lead.version, joining_json: { branchId: branch, startDate: '2026-10-15', businessWorkspaces: ['rentals'] } })
})
it('opens the workspace without the contact receipt or invitation containers', () => {
  wrap(<RecruitmentWorkspace lead={{ ...lead, source: 'Website', intake_channel: 'website', email_verification_status: 'pending', contact_capture_json: { version: 'recruitment-contact-v1', firstName: 'Sam', lastName: 'Agent', privacyAccepted: true } }} />)
  expect(screen.queryByRole('region', { name: 'Website recruitment contact' })).toBeNull()
  expect(screen.queryByText('Recruitment contact received')).toBeNull()
  expect(screen.queryByText('Join Us invitation')).toBeNull()
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('1Lead Received')
  const journey = screen.getByRole('region', { name: 'Agent journey stages' })
  expect(within(journey).getAllByRole('listitem').map((stage) => stage.querySelector('p').textContent)).toEqual([
    'Lead Received', 'Application Submitted', 'Documents Uploaded', 'Under Review',
    'Application Approved', 'Contract Sent', 'Contract Signed', 'Agent Activated',
  ])
})
it('shows completed, current and upcoming recruitment stages from the saved lead', () => {
  wrap(<RecruitmentWorkspace lead={{ ...lead, status: 'under_review', application_submitted_at: '2026-10-05', review_started_at: '2026-10-05', documents_json: [{ path: 'org/agent-1/cv.pdf' }] }} />)
  const stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(within(stages[0]).getByText('Complete')).toBeTruthy()
  expect(within(stages[1]).getByText('Complete')).toBeTruthy()
  expect(within(stages[2]).getByText('Complete')).toBeTruthy()
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('4Under Review')
  expect(within(stages[3]).getByText('Current Stage')).toBeTruthy()
  expect(within(stages[4]).getByText('Upcoming')).toBeTruthy()
})
it('advances the upload milestone only after an application and its documents are saved', () => {
  const documents = [{ path: 'org/agent-1/cv.pdf' }]
  const { rerender } = render(<RecruitmentJourney lead={{ ...lead, documents_json: documents }} />)
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('1Lead Received')
  const submitted = { ...lead, status: 'application_submitted', application_submitted_at: '2026-10-05' }
  rerender(<RecruitmentJourney lead={{ ...submitted, documents_json: [{ name: 'unsaved.pdf' }, { path: ' ' }] }} />)
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('2Application Submitted')
  rerender(<RecruitmentJourney lead={{ ...submitted, documents_json: documents }} />)
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('3Documents Uploaded')
  expect(screen.getByRole('heading', { name: 'Documents Uploaded' })).toBeTruthy()
  const stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(within(stages[1]).getByText('Complete')).toBeTruthy()
  expect(within(stages[3]).getByText('Upcoming')).toBeTruthy()
})
it('does not claim documents were uploaded for a later-stage record without saved files', () => {
  render(<RecruitmentJourney lead={{ ...lead, status: 'under_review', application_submitted_at: '2026-10-05', review_started_at: '2026-10-05' }} />)
  const stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(within(stages[2]).getByText('Not uploaded')).toBeTruthy()
  expect(within(stages[2]).queryByLabelText('Completed')).toBeNull()
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('4Under Review')
})
it('keeps a signed and onboarded agent awaiting activation until activation is saved', () => {
  const onboarded = { ...lead, status: 'onboarding_complete', onboarding_completed_at: '2026-10-05', documents_json: [{ path: 'org/agent-1/cv.pdf' }] }
  const { rerender } = render(<RecruitmentJourney lead={onboarded} />)
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('7Contract Signed')
  expect(screen.getByRole('heading', { name: 'Contract Signed' })).toBeTruthy()
  let stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(within(stages[7]).getByText('Upcoming')).toBeTruthy()
  expect(screen.queryByText('Onboarding Complete')).toBeNull()
  rerender(<RecruitmentJourney lead={{ ...onboarded, status: 'agent_activated', activated_at: '2026-10-06' }} />)
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('8Agent Activated')
  stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(stages.every((stage) => within(stage).queryByText('Complete'))).toBe(true)
})
it('shows where a closed lead stopped without marking a future stage as current', () => {
  wrap(<RecruitmentWorkspace lead={{ ...lead, status: 'closed_lost', application_submitted_at: '2026-10-05', review_started_at: '2026-10-05' }} />)
  const stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(screen.getByRole('region', { name: 'Agent journey stages' }).querySelector('[aria-current="step"]')).toBeNull()
  expect(within(stages[1]).getByText('Complete')).toBeTruthy()
  expect(within(stages[2]).getByText('Not uploaded')).toBeTruthy()
  expect(within(stages[3]).getByText('Stopped here')).toBeTruthy()
  expect(within(stages[4]).getByText('Not reached')).toBeTruthy()
})
it('shows a closed application stopped at uploaded documents without advancing review', () => {
  render(<RecruitmentJourney lead={{ ...lead, status: 'closed_lost', application_submitted_at: '2026-10-05', documents_json: [{ path: 'org/agent-1/cv.pdf' }] }} />)
  const stages = within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem')
  expect(document.querySelector('[aria-current="step"]')).toBeNull()
  expect(within(stages[2]).getByText('Stopped here')).toBeTruthy()
  expect(within(stages[3]).getByText('Not reached')).toBeTruthy()
})
it('keeps active and closed leads separate and filters contact details', () => {
  wrap(<RecruitmentList leads={[lead, { ...lead, id: 'closed', name: 'Joined Agent', status: 'legacy_joined' }]} onRefresh={vi.fn()} />)
  expect(screen.getByText('Sam Agent')).toBeTruthy()
  expect(screen.queryByText('Joined Agent')).toBeNull()
  fireEvent.click(screen.getByRole('tab', { name: /Closed Leads/ }))
  expect(screen.queryByText('Sam Agent')).toBeNull()
  expect(screen.getByText('Joined Agent')).toBeTruthy()
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'no-match' } })
  expect(screen.getByText('No leads match these filters')).toBeTruthy()
})
it('captures details and prevents losing edits through upload', () => {
  const onSave = vi.fn()
  wrap(<RecruitmentWorkspace lead={lead} onSave={onSave} onUpload={vi.fn()} onDownload={vi.fn()} />)
  expect(screen.getByRole('heading', { name: 'Sam Agent' })).toBeTruthy()
  expect(screen.getAllByRole('tab').map((tab) => tab.textContent)).toEqual(['Overview', 'Agent Details', 'Documents'])
  fireEvent.click(screen.getByRole('tab', { name: 'Agent Details' }))
  fireEvent.change(screen.getByLabelText('Experience & track record'), { target: { value: 'Five years in residential sales' } })
  expect(screen.getByRole('button', { name: 'Close Lead' }).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab', { name: 'Documents' }))
  expect(screen.getByLabelText('Upload CV').disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab', { name: 'Agent Details' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save Agent Details' }))
  expect(onSave.mock.calls[0][0].details_json).toMatchObject({ onboardingCaptured: false, experience: 'Five years in residential sales' })
  expect(recruitmentReadiness(lead).score).toBe(20)
})
it('reopens closed leads and uploads the selected document type', () => {
  const onSave = vi.fn(), onUpload = vi.fn()
  wrap(<RecruitmentWorkspace lead={{ ...lead, status: 'closed_lost' }} onSave={onSave} onUpload={onUpload} />)
  fireEvent.click(screen.getByRole('button', { name: 'Reopen Lead' }))
  expect(onSave.mock.calls[0][0].status).toBe('lead_received')
  fireEvent.click(screen.getByRole('tab', { name: 'Documents' }))
  const file = new File(['test'], 'certificate.pdf', { type: 'application/pdf' })
  fireEvent.change(screen.getByLabelText('Upload Qualifications'), { target: { files: [file] } })
  expect(onUpload).toHaveBeenCalledWith(file, 'Qualifications')
})
it('shows load failure with recovery, without inventing an empty lead', async () => {
  vi.mocked(getRecruitmentLead).mockRejectedValue(new Error('Agent lead not found or you do not have access.'))
  render(<WorkspaceContext.Provider value={{ currentWorkspace: { id: 'org' }, organisationMembershipRole: 'principal' }}><MemoryRouter initialEntries={['/agency/recruitment/agent-1']}><Routes><Route path="/agency/recruitment/:leadId" element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
  expect(await screen.findByRole('alert')).toBeTruthy()
  expect(screen.getByRole('button', { name: 'Reload' })).toBeTruthy()
  expect(screen.queryByRole('heading', { name: 'New Agent Lead' })).toBeNull()
})
it('restricts recruitment to organisation management', () => {
  wrap(<WorkspaceContext.Provider value={{ currentWorkspace: { id: 'org' }, organisationMembershipRole: 'agent' }}><RecruitmentPage /></WorkspaceContext.Provider>)
  expect(screen.getByText('Recruitment is available to organisation principals and administrators.')).toBeTruthy()
  expect(getRecruitmentLead).not.toHaveBeenCalled()
})
it('paginates without dropping the final page', () => {
  wrap(<RecruitmentList leads={Array.from({ length: 12 }, (_, i) => ({ ...lead, id: `lead-${i}`, name: `Candidate ${i}` }))} />)
  expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(11)
  fireEvent.click(screen.getByRole('button', { name: 'Next' }))
  expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(3)
})

it('captures a referral at Lead Received without exposing future stage controls', () => {
  const onSave = vi.fn()
  wrap(<RecruitmentWorkspace lead={emptyRecruitmentLead()} isNew onSave={onSave} />)
  fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'New Agent' } })
  fireEvent.change(screen.getByLabelText('Phone'), { target: { value: '0821234567' } })
  fireEvent.change(screen.getByLabelText('Source'), { target: { value: 'Referral' } })
  fireEvent.change(screen.getByLabelText('Referred by'), { target: { value: 'Sam' } })
  expect(screen.getByLabelText('Stage').readOnly).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Create Agent Lead' }))
  expect(onSave.mock.calls[0][0]).toMatchObject({ status: 'lead_received', source: 'Referral', details_json: { referredBy: 'Sam' } })
})
it('shows all eight journey stages and contact details without the activity feed', () => {
  wrap(<RecruitmentWorkspace lead={{ ...lead, received_at: '2026-10-05T12:00:00Z', activity_json: [{ type: 'lead_received', at: '2026-10-05T12:00:00Z' }] }} />)
  expect(screen.getByText('Agent Activated')).toBeTruthy()
  expect(screen.getByText('Application Submitted')).toBeTruthy()
  expect(document.querySelector('[aria-current="step"]').textContent).toBe('1Lead Received')
  expect(screen.getByRole('heading', { name: 'Contact details' })).toBeTruthy()
  expect(screen.queryByRole('heading', { name: 'Activity' })).toBeNull()
  expect(screen.queryByText('Lead received')).toBeNull()
})

it('keeps submitted answers available without the overview requirements section', () => {
  const application = { version:'recruitment-application-v1', channel:'website', answers:{yearsExperience:'3',dealsPerMonth:'2',activeMandates:'no',practitionerStatus:'candidate',ffcStatus:'pending',qualificationRoute:'occupational',qualificationStatus:'in_progress',pdeStatus:'not_started',practicalStatus:'in_progress',cpdStatus:'not_applicable',motivation:'Training'} }
  const onSave = vi.fn()
  wrap(<RecruitmentWorkspace lead={{...lead,status:'closed_lost',application_submitted_at:'2026-10-05',application_json:application}} onSave={onSave} />)
  expect(screen.queryByText('Application requirements')).toBeNull()
  expect(screen.queryByText('PPRA / FFC evidence')).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Reopen Lead'}))
  expect(onSave.mock.calls[0][0].status).toBe('application_submitted')
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByText('Submitted application')).toBeTruthy()
  const professional = screen.getByRole('region', {name:'Professional profile'})
  expect(within(professional.querySelector('.recruitment-details__highlights')).getByText('3 years')).toBeTruthy()
  expect(within(professional.querySelector('details')).getByText('3 years')).toBeTruthy()
})

it('groups the submitted profile and saves staff edits without changing applicant answers', () => {
  const application = {version:'recruitment-application-v1', questionnaireVersion:'recruitment-profile-v1', channel:'website', answers:{...validProfile(lead.email),packagePreference:'deals'}}
  const record = {...lead,status:'application_submitted',application_submitted_at:'2026-10-05',application_json:application}
  const onSave = vi.fn()
  wrap(<RecruitmentWorkspace lead={record} onSave={onSave} />)
  fireEvent.click(screen.getByRole('tab', {name:'Agent Details'}))
  const personal = screen.getByRole('region', {name:'Personal & contact'})
  const professional = screen.getByRole('region', {name:'Professional profile'})
  const joining = screen.getByRole('region', {name:'Joining setup'})
  const notes = screen.getByRole('region', {name:'Agency notes'})
  expect(within(personal).getByText('123 Fixture Road, Pretoria, Gauteng, 0001')).toBeTruthy()
  expect(within(personal).getByText('1990-06-15')).toBeTruthy()
  expect(within(professional).getByText('FFC FFC-FIXTURE-123')).toBeTruthy()
  expect(within(professional).getByText('Non-principal property practitioner')).toBeTruthy()
  expect(within(joining).getByText('Post Paid')).toBeTruthy()
  expect(within(joining).getByText('2099-01-01')).toBeTruthy()
  expect(within(notes).getByText('How did you find out about us?')).toBeTruthy()
  expect(screen.getAllByRole('button', {name:/^Save/})).toHaveLength(1)
  fireEvent.change(within(personal).getByLabelText('Phone'), {target:{value:'0827654321'}})
  fireEvent.change(within(professional).getByLabelText('Experience & track record'), {target:{value:'References checked with prior brokerage.'}})
  fireEvent.change(within(notes).getByLabelText('Recruitment notes'), {target:{value:'Follow up after branch introduction.'}})
  fireEvent.click(screen.getByRole('button', {name:'Save Agent Details'}))
  expect(onSave).toHaveBeenCalledOnce()
  expect(onSave.mock.calls[0][0]).toMatchObject({phone:'0827654321',details_json:{experience:'References checked with prior brokerage.',notes:'Follow up after branch introduction.'}})
  expect(onSave.mock.calls[0][0].application_json).toEqual(application)
  expect(onSave.mock.calls[0][0].joining_json).toEqual(record.joining_json)
})

const submitted = {...lead,status:'application_submitted',application_submitted_at:'2026-10-05',application_json:{version:'recruitment-application-v1',answers:{practitionerStatus:'candidate',ffcStatus:'pending',activeMandates:'no'}}}
it('starts review with a submitted application and complete documents, and protects unsaved details', () => {
  const start = vi.fn()
  const documents = ['CV','Identity document','Qualifications','Registration evidence'].map((type, index) => ({ type, name: `Document ${index + 1}.pdf`, path: `org/agent-1/${index}.pdf` }))
  wrap(<RecruitmentWorkspace lead={{ ...submitted, status: 'documents_uploaded', documents_json: documents }} onStartReview={start} />)
  fireEvent.click(screen.getByRole('button',{name:'Start review'}))
  expect(start).toHaveBeenCalledOnce()
  expect(screen.queryByRole('button',{name:'Approve application'})).toBeNull()
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Updated Agent'}})
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  expect(screen.getByRole('button',{name:'Start review'}).disabled).toBe(true)
})
it('saves review findings and protects unsaved review work from other mutations', () => {
  const save = vi.fn()
  const reviewed = {...submitted,status:'under_review',review_started_at:'2026-10-05'}
  reviewed.review_json = {...recruitmentReviewDraft(reviewed),notes:'Previous interview notes',followUpOn:'2026-10-12'}
  wrap(<RecruitmentWorkspace lead={reviewed} onSaveReview={save} />)
  fireEvent.click(screen.getByRole('button',{name:'Reject PPRA / FFC evidence',exact:true}))
  fireEvent.change(screen.getByLabelText('PPRA / FFC evidence findings'),{target:{value:'Request the current FFC and renewal details'}})
  fireEvent.click(screen.getByRole('button',{name:'Outcome'}))
  expect(screen.getByRole('button',{name:'Close Lead'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Documents'}))
  expect(screen.getByLabelText('Upload CV').disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByRole('button',{name:'Save Agent Details'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  fireEvent.click(screen.getByRole('button',{name:'Outcome'}))
  fireEvent.click(screen.getByRole('button',{name:'Save review'}))
  expect(save.mock.calls[0][0]).toMatchObject({checks:{registration:{status:'needs_information',notes:'Request the current FFC and renewal details'}},notes:'Previous interview notes',followUpOn:'2026-10-12'})
})
it('shows saved document findings and restores Under Review on reopening', () => {
  const onSave = vi.fn(), path = 'org/lead/file'
  const reviewed = {...submitted,status:'closed_lost',review_started_at:'2026-10-05',documents_json:[{path,name:'ffc.pdf',type:'Registration evidence'}]}
  reviewed.review_json = recruitmentReviewDraft(reviewed)
  for (const check of Object.values(reviewed.review_json.checks)) { check.status='verified'; check.notes='Checked by the reviewer' }
  reviewed.review_json.documents[0] = {path,status:'reviewed',notes:'File opened and details checked'}
  wrap(<RecruitmentWorkspace lead={reviewed} onSave={onSave} />)
  expect(screen.getByText('Ready for approval')).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:'Reopen Lead'}))
  expect(onSave.mock.calls[0][0].status).toBe('under_review')
  expect(screen.queryByRole('button',{name:'Save review'})).toBeNull()
  fireEvent.click(screen.getByRole('tab',{name:'Documents'}))
  expect(within(screen.getByRole('article', { name: 'Registration evidence' })).getByText('Reviewed')).toBeTruthy()
})

it('reviews matching filenames by category and preserves previously linked evidence when saving', () => {
  const onSaveReview = vi.fn(), onDownload = vi.fn()
  const documents = [{path:'org/agent-1/cv',name:'upload.jpeg',type:'CV'},{path:'org/agent-1/ffc',name:'upload.jpeg',type:'Registration evidence'}]
  const reviewed = {...submitted,status:'under_review',organisation_id:'2958d402-368e-43c9-b728-0098e10505f1',review_started_at:'2026-10-05',documents_json:documents}
  reviewed.review_json = recruitmentReviewDraft(reviewed)
  reviewed.review_json.checks.registration.evidence = [documents[1].path]
  wrap(<RecruitmentWorkspace lead={reviewed} onSaveReview={onSaveReview} onDownload={onDownload} />)
  const ffc = screen.getByRole('article', {name:'FFC certificate (upload.jpeg)'})
  expect(within(ffc).getByRole('button', {name:'Approve FFC certificate (upload.jpeg)',exact:true})).toBeTruthy()
  fireEvent.click(within(ffc).getByRole('button', {name:'Download FFC certificate (upload.jpeg)'}))
  expect(onDownload).toHaveBeenCalledWith(documents[1])
  fireEvent.click(screen.getByRole('button',{name:'Approve FFC certificate (upload.jpeg)',exact:true}))
  fireEvent.change(screen.getByLabelText('FFC certificate (upload.jpeg) findings'), {target:{value:'File opened and registration confirmed.'}})
  fireEvent.click(screen.getByRole('button', {name:'Application checks'}))
  expect(within(screen.getByRole('region',{name:'Review checklist'})).queryByRole('checkbox')).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Approve PPRA / FFC evidence',exact:true}))
  fireEvent.change(screen.getByLabelText('PPRA / FFC evidence findings'), {target:{value:'Licence details checked against the FFC.'}})
  expect(screen.getByText('1 / 4')).toBeTruthy()
  expect(screen.getByText('1 / 2')).toBeTruthy()
  expect(screen.getByText('Unsaved changes')).toBeTruthy()
  expect(screen.getAllByRole('button', {name:'Save progress'})).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', {name:'Save progress'}))
  expect(onSaveReview).toHaveBeenCalledOnce()
  expect(onSaveReview.mock.calls[0][0]).toMatchObject({checks:{registration:{status:'verified',notes:'Licence details checked against the FFC.',evidence:[documents[1].path]}},documents:[{path:documents[0].path,status:'pending',notes:''},{path:documents[1].path,status:'reviewed',notes:'File opened and registration confirmed.'}]})
})

it('keeps approved findings locked while allowing the preserved document to be downloaded', () => {
  const onDownload = vi.fn(), document = {path:'org/agent-1/ffc',name:'ffc.pdf',type:'Registration evidence'}
  wrap(<RecruitmentWorkspace lead={{...submitted,status:'application_approved',approved_at:'2026-10-06',review_started_at:'2026-10-05',documents_json:[document]}} onDownload={onDownload} />)
  const file = screen.getByRole('article', {name:'Registration evidence (ffc.pdf)'})
  expect(screen.getByRole('button',{name:'Approve Registration evidence (ffc.pdf)',exact:true}).matches(':disabled')).toBe(true)
  expect(screen.getByRole('button',{name:'Reject Registration evidence (ffc.pdf)',exact:true}).matches(':disabled')).toBe(true)
  const download = within(file).getByRole('button', {name:'Download Registration evidence (ffc.pdf)'})
  expect(download.disabled).toBe(false)
  fireEvent.click(download)
  expect(onDownload).toHaveBeenCalledWith(document)
  fireEvent.click(screen.getByRole('button', {name:'Continue to application checks'}))
  expect(screen.getByRole('button',{name:'Approve PPRA / FFC evidence',exact:true}).matches(':disabled')).toBe(true)
  expect(screen.getByRole('button',{name:'Reject PPRA / FFC evidence',exact:true}).matches(':disabled')).toBe(true)
  expect(screen.getByRole('textbox', {name:'PPRA / FFC evidence findings'}).matches(':disabled')).toBe(true)
  expect(screen.queryByRole('button', {name:'Save review'})).toBeNull()
})

const approvalReady = () => {
  const ready={...submitted,status:'under_review',review_started_at:'2026-10-05',review_status:'ready_for_approval'}
  ready.review_json=recruitmentReviewDraft(ready)
  for (const check of Object.values(ready.review_json.checks)) {check.status='verified';check.notes='Evidence reviewed by staff'}
  return ready
}
it('requires a saved resolved review and deliberate confirmation before approval without extra fields', () => {
  const approve=vi.fn()
  wrap(<RecruitmentWorkspace lead={approvalReady()} onApprove={approve} />)
  expect(screen.getByRole('button',{name:'Approve application'}).disabled).toBe(true)
  expect(screen.queryByLabelText('Approval reason')).toBeNull()
  expect(screen.queryByLabelText('Overall review / interview notes')).toBeNull()
  expect(screen.queryByLabelText('Follow-up date (optional)')).toBeNull()
  const confirmation = screen.getByRole('checkbox',{name:approvalConfirmation})
  fireEvent.click(confirmation)
  expect(screen.getByRole('button',{name:'Approve application'}).disabled).toBe(false)
  expect(screen.queryByText(/You have an unsaved approval decision/)).toBeNull()
  expect(screen.queryByText(/Uploading documents and changing the lead stage are disabled/)).toBeNull()
  fireEvent.click(confirmation)
  expect(screen.getByRole('button',{name:'Approve application'}).disabled).toBe(true)
  fireEvent.click(confirmation)
  expect(screen.getByRole('button',{name:'Close Lead'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button',{name:'Approve application'}))
  expect(approve).toHaveBeenCalledWith({confirmed:true})
})
it('blocks approval while review findings or agent details are unsaved', () => {
  wrap(<RecruitmentWorkspace lead={approvalReady()} />)
  fireEvent.click(screen.getByRole('button',{name:'Application checks'}))
  fireEvent.change(screen.getByLabelText('PPRA / FFC evidence findings'),{target:{value:'Unsaved finding'}})
  fireEvent.click(screen.getByRole('button',{name:'Outcome'}))
  expect(screen.queryByRole('button',{name:'Approve application'})).toBeNull()
  expect(screen.getByRole('button',{name:'Save review'}).disabled).toBe(false)
})
it('shows the approval decision and locks review evidence while retaining the approved stage on reopen', () => {
  const onSave=vi.fn()
  wrap(<RecruitmentWorkspace lead={{...approvalReady(),status:'closed_lost',approved_at:'2026-10-05',approved_by:'manager',approval_notes:'Approved following the evidence review'}} onSave={onSave} />)
  expect(screen.getByText('Approved following the evidence review')).toBeTruthy()
  expect(screen.queryByRole('button',{name:'Approve application'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Reopen Lead'}))
  expect(onSave.mock.calls[0][0].status).toBe('application_approved')
  fireEvent.click(screen.getByRole('tab',{name:'Documents'}))
  expect(screen.getByLabelText('Upload CV').disabled).toBe(true)
})

it('preserves a historical approval even when the record has no review-start timestamp', () => {
  wrap(<RecruitmentWorkspace lead={{...lead,status:'application_approved',approved_at:'2026-10-05',approved_by:'manager',approval_notes:'Approved in the prior recruitment process.'}} />)
  expect(screen.getByRole('region',{name:'Application approval'})).toBeTruthy()
  expect(screen.getAllByText('Approved in the prior recruitment process.')).toHaveLength(1)
  expect(screen.queryByRole('button',{name:'Approve application'})).toBeNull()
})

it.each([false,true])('keeps the guided outcome open after saving and preserves findings on failure (failure=%s)', async failure => {
  const ready=approvalReady(), notes='Interview findings checked before the decision.'
  vi.mocked(getRecruitmentLead).mockResolvedValue(ready)
  if (failure) vi.mocked(saveRecruitmentReview).mockRejectedValue(new Error('Review could not be saved. Please retry.'))
  else vi.mocked(saveRecruitmentReview).mockImplementation(async (_org, record, draft) => ({...record,review_json:draft,review_updated_at:'2026-10-10'}))
  render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'org'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={['/agency/recruitment/agent-1']}><Routes><Route path='/agency/recruitment/:leadId' element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
  await screen.findByRole('heading',{name:'Record the outcome'})
  fireEvent.click(screen.getByRole('button',{name:'Application checks'}))
  const field = screen.getByRole('textbox',{name:'PPRA / FFC evidence findings'})
  fireEvent.change(field,{target:{value:notes}})
  fireEvent.click(screen.getByRole('button',{name:'Outcome'}))
  expect(screen.queryByRole('button',{name:'Approve application'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Save review'}))
  const review = within(screen.getByRole('region',{name:'Application review'}))
  if (failure) {
    expect((await review.findByRole('alert')).textContent).toBe('Review could not be saved. Please retry.')
    expect(review.getByLabelText('PPRA / FFC evidence findings').value).toBe(notes)
    await waitFor(() => expect(review.getByRole('button',{name:'Save review'}).disabled).toBe(false))
    expect(screen.queryByRole('button',{name:'Approve application'})).toBeNull()
  } else {
    await screen.findByRole('button',{name:'Approve application'})
    expect(review.queryByRole('button',{name:'Save review'})).toBeNull()
    expect(review.getByLabelText('PPRA / FFC evidence findings').value).toBe(notes)
  }
  expect(saveRecruitmentReview).toHaveBeenCalledOnce()
  expect(saveRecruitmentReview).toHaveBeenCalledWith('org',ready,expect.objectContaining({checks:expect.objectContaining({registration:expect.objectContaining({notes})})}))
  expect(approveRecruitmentApplication).not.toHaveBeenCalled()
})

it.each([false,true])('handles an approval response and preserves the decision on failure (failure=%s)', async (failure) => {
  const ready=approvalReady()
  vi.mocked(getRecruitmentLead).mockResolvedValue(ready)
  if(failure) vi.mocked(approveRecruitmentApplication).mockRejectedValue(new Error('Approval was not saved. Reload and review.'))
  else vi.mocked(approveRecruitmentApplication).mockResolvedValue({...ready,status:'application_approved',approved_at:'2026-10-05',approved_by:'manager',approval_notes:approvalConfirmation})
  render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'org'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={['/agency/recruitment/agent-1']}><Routes><Route path='/agency/recruitment/:leadId' element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
  const confirmation = await screen.findByRole('checkbox',{name:approvalConfirmation})
  fireEvent.click(confirmation)
  fireEvent.click(screen.getByRole('button',{name:'Approve application'}))
  if(failure){
    expect(await screen.findByRole('alert')).toBeTruthy()
    expect(screen.getByRole('checkbox',{name:approvalConfirmation}).checked).toBe(true)
  }else{
    expect(await screen.findByText('Application approved. Approval email queued automatically.')).toBeTruthy()
    expect(screen.queryByRole('checkbox',{name:approvalConfirmation})).toBeNull()
    expect(screen.getByText(approvalConfirmation)).toBeTruthy()
    expect(document.querySelector('[aria-current="step"]').textContent).toBe('5Application Approved')
  }
  expect(approveRecruitmentApplication).toHaveBeenCalledWith('org',ready,{confirmed:true})
})

it('prepares contract PDFs separately from locked review evidence and protects unsaved agent edits', () => {
  const prepare=vi.fn(), download=vi.fn(), ready={...approvalReady(),status:'application_approved',approved_at:'2026-10-05',contracts_json:[{path:'org/lead/contract',version:1,name:'Agreement.pdf',preparedAt:'2026-10-05'}]}
  wrap(<RecruitmentWorkspace lead={ready} onPrepareContract={prepare} onDownloadContract={download} />)
  fireEvent.click(screen.getByRole('button',{name:'Download version 1'}))
  expect(download).toHaveBeenCalledWith(ready.contracts_json[0])
  const file=new File(['%PDF- sample'],'Agreement.pdf',{type:'application/pdf'})
  fireEvent.change(screen.getByLabelText('Prepare contract PDF'),{target:{files:[file]}})
  fireEvent.click(screen.getByRole('button', { name: 'Prepare contract PDF', exact: true }))
  expect(prepare).toHaveBeenCalledWith(file)
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Unsaved correction'}})
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  expect(screen.getByLabelText('Prepare contract PDF').disabled).toBe(true)
})

const sentForSigning=()=>({...approvalReady(),status:'contract_sent',approved_at:recruitmentLocalDate(),contracts_json:[{version:2,path:'org/lead/contract-v2',name:'Agreement.pdf'}],contract_delivery_json:{contractVersion:2,contractPath:'org/lead/contract-v2',recipientName:'Sam Agent',recipientContact:'sam@example.test',channel:'email',sentOn:recruitmentLocalDate(),notes:'Email reference 1234',recordedAt:'2026-10-05'}})
function fillSignatureForm(){
  fireEvent.change(screen.getByLabelText('Organisation representative'),{target:{value:'Agency Principal'}})
  fireEvent.change(screen.getByLabelText('Signing completed on'),{target:{value:recruitmentLocalDate()}})
  fireEvent.change(screen.getByLabelText('Signature verification findings'),{target:{value:'Compared every page against version 2 and checked both signatures'}})
  for(const label of ['The signed copy matches the delivered contract version','All contract pages and annexures are included','The agent’s signature is complete','The organisation representative’s signature is complete'])fireEvent.click(screen.getByRole('checkbox',{name:label}))
  const file=new File(['%PDF- signed sample'],'Signed agreement.pdf',{type:'application/pdf'})
  fireEvent.change(screen.getByLabelText('Complete signed PDF'),{target:{files:[file]}})
  return file
}
it('records prior delivery explicitly and blocks it while agent details are unsaved',()=>{
  const sent=sentForSigning(), record=vi.fn(), ready={...sent,status:'application_approved',contract_delivery_json:{}}
  wrap(<RecruitmentWorkspace lead={ready} onRecordDelivery={record} />)
  expect(screen.getByRole('button',{name:'Record prior delivery'}).disabled).toBe(true)
  fireEvent.change(screen.getByLabelText('Date provided to agent'),{target:{value:recruitmentLocalDate()}})
  fireEvent.change(screen.getByLabelText('Delivery evidence / reference'),{target:{value:'Provided by email, reference 1234'}})
  fireEvent.click(screen.getByRole('checkbox',{name:/I confirm this prepared version/}))
  fireEvent.click(screen.getByRole('button',{name:'Record prior delivery'}))
  expect(record.mock.calls[0][0]).toMatchObject({contractVersion:2,confirmed:true})
  expect(screen.getByRole('button',{name:'Close Lead'}).disabled).toBe(true)
})
it('requires a complete verified signed copy and retains the selected file across tabs',()=>{
  const record=vi.fn()
  wrap(<RecruitmentWorkspace lead={sentForSigning()} onRecordSignature={record} />)
  expect(screen.getByRole('button',{name:'Verify signed contract'}).disabled).toBe(true)
  const file=fillSignatureForm()
  expect(screen.getByRole('button',{name:'Close Lead'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByRole('button',{name:'Save Agent Details'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  expect(screen.getByText('Selected: Signed agreement.pdf')).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:'Verify signed contract'}))
  expect(record.mock.calls[0][0]).toMatchObject({contractVersion:2,organisationSigner:'Agency Principal',checks:{allPages:true},file})
})
it('shows retained signed evidence and restores Contract Signed on reopening',()=>{
  const save=vi.fn(), download=vi.fn()
  wrap(<RecruitmentWorkspace lead={{...sentForSigning(),status:'closed_lost',contract_signature_json:{contractVersion:2,recordedAt:'2026-10-05',signedOn:'2026-10-05',agentSigner:'Sam Agent',organisationSigner:'Agency Principal',notes:'Verified against version 2',method:'wet_ink'}}} onSave={save} onDownloadSigned={download} />)
  expect(screen.getByText('Signed contract verified · Version 2')).toBeTruthy()
  expect(screen.queryByRole('button',{name:'Verify signed contract'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Download signed contract'}))
  expect(download).toHaveBeenCalledOnce()
  fireEvent.click(screen.getByRole('button',{name:'Reopen Lead'}))
  expect(save.mock.calls[0][0].status).toBe('contract_signed')
})
it('keeps signature findings and the selected file after a failed save',async()=>{
  const sent=sentForSigning()
  vi.mocked(getRecruitmentLead).mockResolvedValue(sent)
  vi.mocked(recordRecruitmentContractSignature).mockRejectedValue(new Error('Signatures were not recorded. Reload before trying again.'))
  render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'org'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={['/agency/recruitment/agent-1']}><Routes><Route path='/agency/recruitment/:leadId' element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
  await screen.findByLabelText('Organisation representative')
  const file=fillSignatureForm()
  fireEvent.click(screen.getByRole('button',{name:'Verify signed contract'}))
  expect(await screen.findByRole('alert')).toBeTruthy()
  expect(screen.getByLabelText('Organisation representative').value).toBe('Agency Principal')
  expect(screen.getByText('Selected: Signed agreement.pdf')).toBeTruthy()
  expect(recordRecruitmentContractSignature.mock.calls[0][2].file).toBe(file)
})

const signedForOnboarding=()=>({...sentForSigning(),status:'contract_signed',contract_signature_json:{contractVersion:2,recordedAt:'2026-10-05',signedOn:'2026-10-05',agentSigner:'Sam Agent',organisationSigner:'Agency Principal',method:'wet_ink',notes:'Signed copy checked'},onboarding_documents_json:[{path:'org/agent-1/identity',name:'Joining identity.pdf',type:'Identity document',uploadedAt:'2026-10-05'}]})
function completeOnboardingForm(){
  for(const [,label] of onboardingChecks){fireEvent.change(within(screen.getByRole('region',{name:'Agent onboarding'})).getByLabelText(`${label} status`),{target:{value:'complete'}});fireEvent.change(within(screen.getByRole('region',{name:'Agent onboarding'})).getByLabelText(`${label} findings`),{target:{value:'Joining requirement checked and arrangements confirmed'}})}
  fireEvent.change(screen.getByLabelText('Joining identity.pdf onboarding review status'),{target:{value:'reviewed'}})
  fireEvent.change(screen.getByLabelText('Joining identity.pdf onboarding findings'),{target:{value:'File opened and checked against the agent record'}})
  fireEvent.change(screen.getByLabelText('Agreed joining date'),{target:{value:'2026-10-12'}})
  fireEvent.change(screen.getByLabelText('Onboarding completion findings'),{target:{value:'All joining requirements and final documents completed'}})
  fireEvent.click(screen.getByRole('checkbox',{name:'I confirm the joining requirements and final document pack are complete.'}))
}
it('saves onboarding progress, guards dirty writes and completes only a resolved final pack',()=>{
  const save=vi.fn(),complete=vi.fn()
  wrap(<RecruitmentWorkspace lead={signedForOnboarding()} onSaveOnboarding={save} onCompleteOnboarding={complete} />)
  expect(screen.getByRole('button',{name:'Complete onboarding'}).disabled).toBe(true)
  fireEvent.change(screen.getByLabelText('Identity & contact details findings'),{target:{value:'Identity review in progress'}})
  fireEvent.click(screen.getByRole('button',{name:'Save onboarding progress'}))
  expect(save.mock.calls[0][0].checks.identity.notes).toBe('Identity review in progress')
  fireEvent.click(screen.getByRole('button',{name:'Open onboarding documents'}))
  expect(screen.getByLabelText('Upload onboarding document').disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByRole('button',{name:'Save Agent Details'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  expect(screen.getByLabelText('Identity & contact details findings').value).toBe('Identity review in progress')
  completeOnboardingForm()
  expect(screen.getByRole('button',{name:'Complete onboarding'}).disabled).toBe(false)
  fireEvent.click(screen.getByRole('button',{name:'Complete onboarding'}))
  expect(complete.mock.calls[0][0]).toMatchObject({confirmed:true,startDate:'2026-10-12',documents:[{status:'reviewed'}]})
})
it('shows final pack uploads only after signatures, downloads retained evidence and restores completed stage',()=>{
  const signed=signedForOnboarding(),save=vi.fn(),download=vi.fn(),upload=vi.fn()
  const draft=recruitmentOnboardingDraft(signed)
  wrap(<RecruitmentWorkspace lead={{...signed,status:'closed_lost',onboarding_completed_at:'2026-10-05',onboarding_json:{...draft,startDate:'2026-10-12',notes:'Final arrangements confirmed'}}} onSave={save} onDownloadOnboarding={download} onUploadOnboarding={upload} />)
  expect(screen.getByText('Onboarding completed')).toBeTruthy()
  expect(screen.queryByRole('button',{name:'Complete onboarding'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Reopen Lead'}))
  expect(save.mock.calls[0][0].status).toBe('onboarding_complete')
  fireEvent.click(screen.getByRole('button',{name:'Open onboarding documents'}))
  expect(screen.queryByLabelText('Upload onboarding document')).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Download Joining identity.pdf'}))
  expect(download).toHaveBeenCalledWith(signed.onboarding_documents_json[0])
})
it('keeps onboarding findings after a failed completion save',async()=>{
  vi.mocked(getRecruitmentLead).mockResolvedValue(signedForOnboarding())
  vi.mocked(saveRecruitmentOnboarding).mockRejectedValue(new Error('Onboarding changed. Your findings were not saved.'))
  render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'org'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={['/agency/recruitment/agent-1']}><Routes><Route path='/agency/recruitment/:leadId' element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
  await screen.findByLabelText('Agreed joining date')
  completeOnboardingForm()
  fireEvent.click(screen.getByRole('button',{name:'Complete onboarding'}))
  expect(await screen.findByRole('alert')).toBeTruthy()
  expect(screen.getByLabelText('Agreed joining date').value).toBe('2026-10-12')
  expect(screen.getByRole('button',{name:'Close Lead'}).disabled).toBe(true)
  expect(saveRecruitmentOnboarding.mock.calls[0][3]).toBe(true)
})
it('uploads the final pack through Documents after signatures without changing approved evidence',()=>{
  const upload=vi.fn()
  wrap(<RecruitmentWorkspace lead={signedForOnboarding()} onUploadOnboarding={upload} />)
  fireEvent.click(screen.getByRole('tab',{name:'Documents'}))
  expect(screen.getByLabelText('Upload CV').disabled).toBe(true)
  expect(screen.getByLabelText('Upload onboarding document').disabled).toBe(false)
  fireEvent.change(screen.getByLabelText('Onboarding document type'),{target:{value:'Training / CPD'}})
  const file=new File(['evidence'],'Training.pdf',{type:'application/pdf'})
  fireEvent.change(screen.getByLabelText('Upload onboarding document'),{target:{files:[file]}})
  expect(upload).toHaveBeenCalledWith(file,'Training / CPD')
})

const readyForActivation=()=>({...signedForOnboarding(),joining_json:{...emptyRecruitmentLead().joining_json,branchId:'a1111111-1111-4111-8111-111111111111',businessWorkspaces:['rentals'],startDate:'2026-10-12'},status:'onboarding_complete',onboarding_completed_at:'2026-10-05',onboarding_json:{...recruitmentOnboardingDraft(signedForOnboarding()),notes:'Final joining requirements completed',startDate:'2026-10-12'},onboarding_snapshot:{version:'recruitment-onboarding-completion-v1'}})
const fillActivation=()=>{fireEvent.change(screen.getByLabelText('Activation findings'),{target:{value:'Joining record reviewed and agent access authorised'}});fireEvent.click(screen.getByRole('checkbox',{name:'I confirm the agent identity, completed onboarding and organisation access.'}))}
it('requires explicit activation findings and preserves dirty work across tabs while blocking other writes',()=>{
  const activate=vi.fn()
  wrap(<RecruitmentWorkspace lead={readyForActivation()} onActivate={activate} />)
  expect(screen.getByRole('button',{name:'Prepare agent access'}).disabled).toBe(true)
  fillActivation()
  expect(screen.getByRole('button',{name:'Close Lead'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByRole('button',{name:'Save Agent Details'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  fireEvent.click(screen.getByRole('button',{name:'Prepare agent access'}))
  expect(activate.mock.calls[0][0]).toEqual({notes:'Joining record reviewed and agent access authorised',confirmed:true})
})
it('shows pending access without claiming activation and exposes a shareable link on demand',async()=>{
  const getLink=vi.fn().mockResolvedValue('https://app.example.test/invite/sample-token')
  wrap(<RecruitmentWorkspace lead={{...readyForActivation(),activation_json:{state:'awaiting_acceptance',inviteId:'invite',email:'sam@example.test',preparedAt:'2026-10-05'}}} onGetAgentLink={getLink} />)
  expect(screen.getByText('Awaiting acceptance')).toBeTruthy()
  expect(screen.queryByRole('link',{name:'Open agent'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Get agent access link'}))
  expect((await screen.findByLabelText('Agent access link')).value).toBe('https://app.example.test/invite/sample-token')
  expect(screen.getByText('Preparing access does not send an email.')).toBeTruthy()
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByLabelText('Email').readOnly).toBe(true)
  fireEvent.click(screen.getByRole('tab',{name:'Overview'}))
  expect(screen.getByRole('button',{name:'Confirm agent activation'}).disabled).toBe(true)
})
it('shows a preserved activation link and closes the recruitment journey without further stage controls',()=>{
  const active={...readyForActivation(),status:'agent_activated',activated_at:'2026-10-05',activation_json:{state:'active',email:'sam@example.test',role:'agent',userId:'actual-user',notes:'Activation checked'}}
  wrap(<RecruitmentWorkspace lead={active} />)
  expect(screen.getByRole('link',{name:'Open agent'}).getAttribute('href')).toBe('/agency/agents/actual-user')
  expect(screen.queryByRole('button',{name:'Close Lead'})).toBeNull()
  expect(screen.queryByRole('button',{name:'Prepare agent access'})).toBeNull()
  expect(within(screen.getByRole('region', { name: 'Agent journey stages' })).getAllByRole('listitem').at(-1).textContent).toContain('Complete')
})
it.each([false,true])('handles activation responses and retains findings on failure (failure=%s)',async failure=>{
  const ready=readyForActivation()
  vi.mocked(getRecruitmentLead).mockResolvedValue(ready)
  if(failure) vi.mocked(activateRecruitmentAgent).mockRejectedValue(new Error('Activation was not saved.'))
  else vi.mocked(activateRecruitmentAgent).mockResolvedValue({...ready,status:'agent_activated',activated_at:'2026-10-05',activation_json:{userId:'actual-user',email:ready.email,role:'agent',notes:'Recorded'}})
  render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'org'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={['/agency/recruitment/agent-1']}><Routes><Route path='/agency/recruitment/:leadId' element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
  await screen.findByLabelText('Activation findings')
  fillActivation()
  fireEvent.click(screen.getByRole('button',{name:'Prepare agent access'}))
  if(failure){expect(await screen.findByRole('alert')).toBeTruthy();expect(screen.getByLabelText('Activation findings').value).toBe('Joining record reviewed and agent access authorised')}
  else expect(await screen.findByRole('link',{name:'Open agent'})).toBeTruthy()
})

function renderRecruitmentTable() {
  return render(<WorkspaceContext.Provider value={{ currentWorkspace: { id: 'org' }, organisationMembershipRole: 'principal' }}><MemoryRouter initialEntries={['/agency/recruitment']}><Routes><Route path="/agency/recruitment" element={<RecruitmentPage />} /><Route path="/agency/recruitment/:leadId" element={<RecruitmentPage />} /></Routes></MemoryRouter></WorkspaceContext.Provider>)
}
it('creates an agent lead in a popup and stays on the recruitment table', async () => {
  vi.mocked(saveRecruitmentLead).mockResolvedValue(lead)
  renderRecruitmentTable()
  fireEvent.click(await screen.findByRole('button', { name: 'Add Agent Lead' }))
  const dialog = within(screen.getByRole('dialog', { name: 'Add Agent Lead' }))
  expect(screen.getByRole('table')).toBeTruthy()
  fireEvent.change(dialog.getByLabelText('Name'), { target: { value: 'Sam Agent' } })
  fireEvent.change(dialog.getByLabelText('Email'), { target: { value: 'sam@example.test' } })
  fireEvent.click(dialog.getByRole('button', { name: 'Create Agent Lead' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(saveRecruitmentLead).toHaveBeenCalledWith('org', expect.objectContaining({ name: 'Sam Agent', email: 'sam@example.test', status: 'lead_received' }))
  expect(within(screen.getByRole('table')).getByRole('link', { name: 'Sam Agent' }).getAttribute('href')).toBe('/agency/recruitment/agent-1')
  expect(screen.getByRole('heading', { name: 'Recruitment' })).toBeTruthy()
  expect(getRecruitmentLead).not.toHaveBeenCalled()
})
it('retains popup details after a failed save and resets them after cancellation', async () => {
  vi.mocked(saveRecruitmentLead).mockRejectedValue(new Error('Save unavailable. Try again.'))
  renderRecruitmentTable()
  fireEvent.click(await screen.findByRole('button', { name: 'Add Agent Lead' }))
  fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Sam Agent' } })
  fireEvent.click(screen.getByRole('button', { name: 'Create Agent Lead' }))
  expect(await screen.findByRole('alert')).toHaveProperty('textContent', 'Enter an email address or phone number.')
  expect(saveRecruitmentLead).not.toHaveBeenCalled()
  fireEvent.change(screen.getByLabelText('Phone'), { target: { value: '0821234567' } })
  fireEvent.click(screen.getByRole('button', { name: 'Create Agent Lead' }))
  expect(await screen.findByText('Save unavailable. Try again.')).toBeTruthy()
  await waitFor(() => expect(screen.getByRole('button', { name: 'Create Agent Lead' }).disabled).toBe(false))
  expect(screen.getByLabelText('Name').value).toBe('Sam Agent')
  expect(screen.getByLabelText('Phone').value).toBe('0821234567')
  fireEvent.keyDown(document, { key: 'Escape' })
  expect(screen.queryByRole('dialog')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Add Agent Lead' }))
  expect(screen.getByLabelText('Name').value).toBe('')
  expect(screen.queryByRole('alert')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
  expect(screen.queryByRole('dialog')).toBeNull()
})

it('starts branch recruitment with preselected choices, retains the saved lead after a link failure and returns to the branch', async () => {
  const branchId='a1111111-1111-4111-8111-111111111111'
  vi.mocked(getRecruitmentJoiningOptions).mockResolvedValueOnce({branches:[{id:branchId,name:'Branch One'}],commissionStructures:[]})
  vi.mocked(saveRecruitmentLead).mockImplementationOnce(async(_org,draft)=>({...draft,id:'saved-joining',version:1}))
  vi.mocked(createRecruitmentIntakeLink).mockRejectedValueOnce(new Error('The application link could not be prepared.')).mockResolvedValueOnce({id:'link',url:'https://app.example.test/join-us/private-token',expires_at:'2099-01-01'})
  render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'org'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={[recruitmentStartLocation({entryPoint:'branch',organisationId:'org',branchId,returnTo:`/agency/branches/${branchId}/staff`})]}><Routes><Route path="/agency/recruitment/:leadId" element={<RecruitmentPage/>}/><Route path="/agency/branches/:branchId/staff" element={<p>Returned to branch staff</p>}/></Routes></MemoryRouter></WorkspaceContext.Provider>)
  await screen.findByRole('dialog',{name:'Invite new agent'})
  await screen.findByRole('option',{name:'Branch One'})
  expect(screen.getByLabelText('Intended branch').value).toBe(branchId)
  fireEvent.change(screen.getByLabelText('Name'),{target:{value:'New Branch Agent'}})
  fireEvent.change(screen.getByLabelText('Email'),{target:{value:'new@example.test'}})
  fireEvent.click(screen.getByRole('button',{name:'Create Agent Lead'}))
  await screen.findByText(/Joining record saved for New Branch Agent/)
  expect(saveRecruitmentLead).toHaveBeenCalledWith('org',expect.objectContaining({joining_json:expect.objectContaining({origin:{entryPoint:'branch'},branchId})}))
  expect(createRecruitmentIntakeLink).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button',{name:'Create private link'}))
  await screen.findByText('The application link could not be prepared.')
  expect(screen.getByRole('link',{name:'Open recruitment record'}).getAttribute('href')).toBe('/agency/recruitment/saved-joining')
  fireEvent.click(screen.getByRole('button',{name:'Create private link'}))
  expect((await screen.findByLabelText('Generated Join Us link')).value).toContain('/join-us/private-token')
  expect(createRecruitmentIntakeLink).toHaveBeenLastCalledWith('org','private_link','saved-joining')
  expect(saveRecruitmentLead).toHaveBeenCalledOnce()
  fireEvent.click(screen.getByRole('button',{name:'Done'}))
  await screen.findByText('Returned to branch staff')
})
it('blocks starting in another agency and keeps private application actions locked during unsaved edits',async()=>{
  const view=render(<WorkspaceContext.Provider value={{currentWorkspace:{id:'another'},organisationMembershipRole:'principal'}}><MemoryRouter initialEntries={[recruitmentStartLocation({entryPoint:'agents',organisationId:'original',returnTo:'/agency/agents'})]}><Routes><Route path="/agency/recruitment/:leadId" element={<RecruitmentPage/>}/></Routes></MemoryRouter></WorkspaceContext.Provider>)
  expect(screen.getByRole('alert').textContent).toMatch(/Switch to the agency/)
  expect(screen.queryByRole('dialog')).toBeNull()
  view.unmount()
  wrap(<RecruitmentWorkspace lead={lead} organisationId="org" returnTo="/agency/agents"/>)
  expect(screen.getByRole('link',{name:'Back to Agents'}).getAttribute('href')).toBe('/agency/agents')
  fireEvent.click(screen.getByRole('tab',{name:'Agent Details'}))
  expect(screen.getByRole('button',{name:'Create private link'}).disabled).toBe(false)
  fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Unsaved name'}})
  expect(screen.getByRole('button',{name:'Create private link'}).disabled).toBe(true)
})

it('shows the final saved setup before access and blocks unavailable branch choices until reviewed',async()=>{
  const ready={...readyForActivation(),joining_json:{...readyForActivation().joining_json,role:'senior_agent',commissionStructureId:'a2222222-2222-4222-8222-222222222222'}}
  vi.mocked(getRecruitmentJoiningOptions).mockResolvedValueOnce({branches:[{id:ready.joining_json.branchId,name:'Planned Office'}],commissionStructures:[{id:ready.joining_json.commissionStructureId,name:'Planned Split'}]})
  const activate=vi.fn()
  wrap(<RecruitmentWorkspace lead={ready} organisationId="org" onActivate={activate}/>)
  await screen.findByText('Planned Office')
  const review=screen.getByLabelText('Final joining review')
  for(const value of ['Senior agent','Rentals','Planned Split','2026-10-12'])expect(within(review).getByText(value)).toBeTruthy()
  fillActivation()
  fireEvent.click(screen.getByRole('button',{name:'Prepare agent access'}))
  expect(activate).toHaveBeenCalledTimes(1)
})
it('keeps final review errors recoverable and blocks access while saved branch choices are unavailable',async()=>{
  vi.mocked(getRecruitmentJoiningOptions).mockRejectedValueOnce(new Error('Choices unavailable')).mockResolvedValueOnce({branches:[],commissionStructures:[]})
  wrap(<RecruitmentWorkspace lead={readyForActivation()} organisationId="org" onActivate={vi.fn()}/>)
  await screen.findByText('Choices unavailable')
  fillActivation()
  expect(screen.getByRole('button',{name:'Prepare agent access'}).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button',{name:'Retry final review'}))
  await screen.findByText('Choose an active branch and commission structure in Agent Details.')
  expect(screen.getByText('Review joining setup')).toBeTruthy()
  expect(screen.getByRole('button',{name:'Prepare agent access'}).disabled).toBe(true)
})
it('preserves the reviewed setup after acceptance and links the verified agent and branch staff',()=>{
  const ready=readyForActivation(),plan={...ready.joining_json,branchName:'Verified Office',role:'senior_agent'}
  const active={...ready,status:'agent_activated',activated_at:'2026-10-08',activation_json:{state:'active',userId:'verified-user',role:'senior_agent',joiningPlan:plan}}
  wrap(<RecruitmentWorkspace lead={active}/>)
  expect(screen.getByText('Active')).toBeTruthy()
  expect(within(screen.getByLabelText('Final joining review')).getByText('Verified Office')).toBeTruthy()
  expect(screen.getByRole('link',{name:'Open agent'}).getAttribute('href')).toBe('/agency/agents/verified-user')
  expect(screen.getByRole('link',{name:'Open branch staff'}).getAttribute('href')).toBe(`/agency/branches/${plan.branchId}/staff`)
})
it('links a verified Commercial broker back to the broker directory and Commercial branches',()=>{
 const ready=readyForActivation(),plan={...ready.joining_json,branchName:'Commercial Office',role:'commercial_broker',businessWorkspaces:['commercial']}
 wrap(<RecruitmentWorkspace lead={{...ready,status:'agent_activated',activated_at:'2026-10-08',activation_json:{state:'active',userId:'verified-broker',role:'commercial_broker',joiningPlan:plan}}}/>)
 expect(screen.getByRole('link',{name:'Open broker'}).getAttribute('href')).toBe('/commercial/brokers/verified-broker')
 expect(screen.getByRole('link',{name:'Open Commercial branches'}).getAttribute('href')).toBe('/commercial/agency/branches')
 expect(screen.queryByRole('link',{name:'Open agent'})).toBeNull()
})
it('continues the guided review without a popup and shows submitted answers beside the checks', () => {
  const onDownload=vi.fn(), profile={...submitted,status:'under_review',review_started_at:'2026-10-10',documents_json:[{name:'identity.pdf',type:'Identity document',path:'org/agent-1/identity'}]}
  wrap(<RecruitmentWorkspace lead={profile} organisationId="org" onDownload={onDownload} />)
  const review = screen.getByRole('region',{name:'Application review'})
  review.scrollIntoView = vi.fn()
  expect(within(screen.getByLabelText('Next best action')).getAllByRole('button')).toHaveLength(1)
  fireEvent.click(within(screen.getByLabelText('Next best action')).getByRole('button',{name:'Continue review'}))
  expect(review.scrollIntoView).toHaveBeenCalledWith({behavior:'smooth',block:'start'})
  expect(screen.queryByRole('dialog')).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Download Identity document (identity.pdf)'}))
  expect(onDownload).toHaveBeenCalledWith(profile.documents_json[0])
  fireEvent.click(screen.getByRole('button',{name:'Application checks'}))
  const registration = within(screen.getByRole('article',{name:'PPRA / FFC evidence'}))
  expect(registration.getByText('Candidate practitioner')).toBeTruthy()
  expect(registration.getByText('Application / renewal pending')).toBeTruthy()
})
it('opens manual required document upload and records a reasoned rejection from the review outcome',async()=>{
  const onUpload=vi.fn(), onReject=vi.fn().mockResolvedValue({...submitted,status:'closed_lost'})
  const view=wrap(<RecruitmentWorkspace lead={{...submitted,status:'documents_uploaded'}} onUpload={onUpload} />)
  fireEvent.click(within(screen.getByLabelText('Next best action')).getByRole('button',{name:'Upload manually'}))
  const popup=within(screen.getByRole('dialog',{name:'Required documents'}))
  expect(popup.getAllByLabelText(/^Upload .* manually$/)).toHaveLength(4)
  const file=new File(['%PDF'],'id.pdf',{type:'application/pdf'})
  fireEvent.change(popup.getByLabelText('Upload Identity document manually'),{target:{files:[file]}})
  expect(onUpload).toHaveBeenCalledWith(file,'Identity document')
  view.unmount()
  wrap(<RecruitmentWorkspace lead={approvalReady()} onReject={onReject} />)
  fireEvent.click(screen.getByRole('button',{name:'Outcome'}))
  const decision=within(screen.getByRole('group',{name:'Application decision'}))
  expect(decision.getByRole('button',{name:'Approve application'}).disabled).toBe(true)
  expect(screen.getAllByRole('button',{name:'Reject Application'})).toHaveLength(1)
  fireEvent.click(screen.getByRole('checkbox',{name:approvalConfirmation}))
  expect(decision.getByRole('button',{name:'Approve application'}).disabled).toBe(false)
  expect(decision.getByRole('button',{name:'Reject Application'}).disabled).toBe(false)
  fireEvent.click(decision.getByRole('button',{name:'Reject Application'}))
  const rejection=within(screen.getByRole('dialog',{name:'Reject application'}))
  expect(rejection.getByRole('button',{name:'Reject Application'}).disabled).toBe(true)
  fireEvent.change(rejection.getByLabelText('Rejection reason'),{target:{value:'This opening needs more experience'}})
  fireEvent.click(rejection.getByRole('button',{name:'Reject Application'}))
  await waitFor(()=>expect(onReject).toHaveBeenCalledWith('This opening needs more experience'))
  await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull())
  expect(screen.getByRole('checkbox',{name:approvalConfirmation}).checked).toBe(false)
})
