// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import RecruitmentSignupModal from '../RecruitmentSignupModal'
import HomeSeekersJoin from '../../HomeSeekersJoin'

const response = (body, status = 200) => ({ ok: status < 400, status, json: async () => body })
const context = { branding: { organisationName: 'Home Seekers' } }
let requests
beforeEach(() => {
  requests = []
  vi.stubGlobal('fetch', vi.fn(async (_url, options) => {
    const body = JSON.parse(options.body); requests.push(body)
    return response(body.action === 'context' ? context : { accepted: true, contactAccepted: true, accountCreated: true })
  }))
})
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.restoreAllMocks() })
async function fill() {
  await screen.findByRole('form', { name: 'Create applicant account' })
  for (const [label,value] of [['First name','Fixture'],['Surname','Applicant'],['Email address','applicant@example.test'],['Mobile number','+27821234567'],['Password','FixturePass123']]) fireEvent.change(screen.getByLabelText(new RegExp(`^${label} `)), { target: { value } })
  fireEvent.click(screen.getByRole('checkbox'))
}
it('replaces the Home Seekers bottom form and opens signup from a Join button', async () => {
  render(<HomeSeekersJoin />)
  expect(screen.queryByRole('button', { name: 'Send my application' })).toBeNull()
  fireEvent.click(screen.getAllByRole('button', { name: /^Join Home Seekers$/i })[0])
  await screen.findByRole('dialog', { name: 'Join Home Seekers' })
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Create account & continue' }))
  await screen.findByText('Your contact details are saved')
  const signup = requests.find((request) => request.action === 'signup')
  expect(signup.submissionKey).toMatch(/^[0-9a-f-]{36}$/)
  expect(screen.getByText('Your full application has not been submitted.')).toBeTruthy()
})
it('validates consent, contact details and password without saving an incomplete request', async () => {
  render(<RecruitmentSignupModal open onClose={() => {}} organisationName="Home Seekers" />)
  await screen.findByRole('form', { name: 'Create applicant account' })
  fireEvent.click(screen.getByRole('button', { name: 'Create account & continue' }))
  expect(await screen.findByText(/Enter your first name/)).toBeTruthy()
  expect(requests).toHaveLength(1)
})
it('retries the same contact and key after account failure while leaving password editable', async () => {
  fetch.mockImplementationOnce(async () => response(context)).mockImplementationOnce(async (_url, options) => {
    requests.push(JSON.parse(options.body)); return response({ contactAccepted: true, error: 'Fixture account unavailable' },503)
  })
  render(<RecruitmentSignupModal open onClose={() => {}} />)
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Create account & continue' }))
  await screen.findByText('Fixture account unavailable')
  expect(screen.getByLabelText(/^Email address /).readOnly).toBe(true)
  fireEvent.change(screen.getByLabelText(/^Password /), { target: { value: 'RetryFixture123' } })
  fireEvent.click(screen.getByRole('button', { name: 'Retry account creation' }))
  await screen.findByText('Your contact details are saved')
  expect(requests[1].submissionKey).toBe(requests[0].submissionKey)
  expect(requests[1].contact).toEqual(requests[0].contact)
  expect(requests[1].password).toBe('RetryFixture123')
})
it('previews the next step without sending credentials or claiming a CRM save', async () => {
  fetch.mockImplementation(async (_url, options) => { requests.push(JSON.parse(options.body)); return response({ ...context, preview: true }) })
  render(<RecruitmentSignupModal open onClose={() => {}} />)
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Preview next step' }))
  await screen.findByText('Preview complete')
  expect(requests).toEqual([{ action: 'context' }])
  expect(screen.queryByText('Your contact details are saved')).toBeNull()
})
it('clears the password on close and reopens with contact details intact', async () => {
  const close = vi.fn()
  const view = render(<RecruitmentSignupModal open onClose={close} />)
  await fill()
  fireEvent.click(screen.getByRole('button', { name: 'Show password' }))
  expect(screen.getByLabelText(/^Password /).type).toBe('text')
  fireEvent.click(screen.getByRole('button', { name: 'Close dialog' }))
  expect(close).toHaveBeenCalledTimes(1)
  view.rerender(<RecruitmentSignupModal open={false} onClose={close} />)
  view.rerender(<RecruitmentSignupModal open onClose={close} />)
  await screen.findByRole('form', { name: 'Create applicant account' })
  expect(screen.getByLabelText(/^Password /).value).toBe('')
  expect(screen.getByLabelText(/^Password /).type).toBe('password')
  expect(screen.getByLabelText(/^Email address /).value).toBe('applicant@example.test')
})
it('blocks duplicate submits and closing while saving, then permits a safe retry after an uncertain response', async () => {
  let reject
  fetch.mockImplementationOnce(async () => response(context)).mockImplementationOnce(async (_url, options) => {
    requests.push(JSON.parse(options.body)); return new Promise((_resolve, fail) => { reject = fail })
  })
  const close = vi.fn()
  render(<RecruitmentSignupModal open onClose={close} />)
  await fill()
  const form = screen.getByRole('form', { name: 'Create applicant account' })
  fireEvent.submit(form); fireEvent.submit(form)
  fireEvent.click(screen.getByRole('button', { name: 'Close dialog' }))
  expect(close).not.toHaveBeenCalled()
  expect(requests).toHaveLength(1)
  await act(async () => reject(new Error('Fixture lost response')))
  await screen.findByText('Fixture lost response')
  fireEvent.click(screen.getByRole('button', { name: 'Retry account creation' }))
  await screen.findByText('Your contact details are saved')
  expect(requests[1].submissionKey).toBe(requests[0].submissionKey)
})
it('shows an unavailable link instead of allowing an account request', async () => {
  fetch.mockImplementation(async () => response({ error: 'Fixture expired link' },410))
  render(<RecruitmentSignupModal open onClose={() => {}} />)
  await screen.findByText('Fixture expired link')
  await waitFor(() => expect(screen.queryByRole('form')).toBeNull())
})

const verifiedApplicant = {emailVerification:'verified',stage:'lead_received',applicationSubmitted:false,contact:{firstName:'Fixture',lastName:'Applicant',email:'applicant@example.test',phone:'+27821234567'}}
it('sends a verification request after capture and opens the original enquiry only after a successful code', async () => {
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context')return response(context)
    if(body.action==='signup')return response({accepted:true,contactAccepted:true,accountCreated:true})
    if(body.action==='send_verification')return response({verificationRequested:true})
    return response({applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Create account & continue'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  await waitFor(()=>expect(screen.getByRole('button',{name:'Verify & continue'}).disabled).toBe(false))
  expect(requests.map(r=>r.action)).toEqual(['context','signup','send_verification'])
  expect(screen.queryByText('Email verified')).toBeNull()
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'123456'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.getByLabelText(/First name/).value).toBe('Fixture')
  expect(screen.getByLabelText(/Surname/).value).toBe('Applicant')
  expect(requests.at(-1).submissionKey).toBe(requests.find(r=>r.action==='signup').submissionKey)
  expect(requests.at(-1)).not.toHaveProperty('password')
  expect(screen.queryByRole('button',{name:'Submit application'})).toBeNull()
})
it('offers existing-account sign-in after contact capture fails to create another account',async()=>{
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return body.action==='context'?response(context):body.action==='signup'?response({contactAccepted:true,error:'Contact saved; sign in to continue.'},503):response({applicant:verifiedApplicant})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Create account & continue'}))
  await screen.findByText('Contact saved; sign in to continue.')
  fireEvent.click(screen.getByRole('button',{name:'Already have an account? Sign in'}))
  await screen.findByRole('form',{name:'Sign in to applicant account'})
  expect(screen.getByLabelText('Email address').value).toBe('applicant@example.test')
  expect(screen.getByLabelText('Password').value).toBe('')
  fireEvent.change(screen.getByLabelText('Password'),{target:{value:'ExistingFixture123'}})
  fireEvent.click(screen.getByRole('button',{name:'Sign in & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(requests.at(-1)).toMatchObject({action:'sign_in',email:'applicant@example.test',password:'ExistingFixture123'})
  expect(requests.filter(r=>r.action==='signup')).toHaveLength(1)
})
it('restores a verified enquiry from context after reload and clears personal data on applicant sign-out',async()=>{
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    return response(body.action==='context'?{...context,applicant:verifiedApplicant}:{signedOut:true})
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.queryByRole('form',{name:'Create applicant account'})).toBeNull()
  expect(requests).toEqual([{action:'context'}])
  fireEvent.click(screen.getByRole('button',{name:'Sign out of applicant account'}))
  await screen.findByRole('form',{name:'Sign in to applicant account'})
  expect(screen.queryByText('Fixture Applicant')).toBeNull()
  expect(screen.getByLabelText('Email address').value).toBe('')
  expect(requests.at(-1)).toEqual({action:'sign_out'})
})
it('keeps the saved enquiry usable after email delivery failure or an expired code',async()=>{
  let delivered=false
  fetch.mockImplementation(async(_url,options)=>{
    const body=JSON.parse(options.body);requests.push(body)
    if(body.action==='context')return response(context)
    if(body.action==='signup')return response({accepted:true,contactAccepted:true,accountCreated:true})
    if(body.action==='send_verification'){if(!delivered){delivered=true;return response({error:'Fixture email unavailable'},503)}return response({verificationRequested:true})}
    return response({error:'Fixture expired code'},401)
  })
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Create account & continue'}))
  await screen.findByText('Fixture email unavailable')
  fireEvent.click(screen.getByRole('button',{name:'Send a new email code'}))
  await screen.findByText(/Check your inbox for a verification code/)
  expect(screen.queryByText('Fixture email unavailable')).toBeNull()
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'654321'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByText('Fixture expired code')
  expect(screen.getByText('Your contact details are saved')).toBeTruthy()
  expect(screen.queryByText('Email verified')).toBeNull()
})
it('prevents closing during applicant sign-in and clears the password after rejection',async()=>{
  let reject
  fetch.mockImplementationOnce(async()=>response(context)).mockImplementationOnce(()=>new Promise((_resolve,fail)=>{reject=fail}))
  const close=vi.fn();render(<RecruitmentSignupModal open onClose={close} />)
  await screen.findByRole('form',{name:'Create applicant account'})
  fireEvent.click(screen.getByRole('button',{name:'Already have an account? Sign in'}))
  fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'applicant@example.test'}})
  fireEvent.change(screen.getByLabelText('Password'),{target:{value:'FixturePass123'}})
  fireEvent.click(screen.getByRole('button',{name:'Sign in & continue'}))
  fireEvent.click(screen.getByRole('button',{name:'Close dialog'}));expect(close).not.toHaveBeenCalled()
  await act(async()=>reject(new Error('Fixture rejected login')))
  await screen.findByText('Fixture rejected login')
  expect(screen.getByLabelText('Password').value).toBe('')
})
it('previews code entry and verified enquiry without sending credentials, creating accounts or claiming a saved contact',async()=>{
  fetch.mockImplementation(async(_url,options)=>{requests.push(JSON.parse(options.body));return response({...context,preview:true})})
  render(<RecruitmentSignupModal open onClose={()=>{}} />)
  await fill();fireEvent.click(screen.getByRole('button',{name:'Preview next step'}))
  await screen.findByText('Preview complete')
  fireEvent.click(screen.getByRole('button',{name:'Preview email verification'}))
  await screen.findByRole('form',{name:'Verify applicant email'})
  fireEvent.change(screen.getByLabelText('Verification code'),{target:{value:'123456'}})
  fireEvent.click(screen.getByRole('button',{name:'Verify & continue'}))
  await screen.findByRole('form',{name:'Applicant questionnaire form'})
  expect(screen.queryByText('Verification preview')).toBeNull()
  expect(screen.queryByText('Preview — no account or enquiry will be created.')).toBeNull()
  expect(screen.queryByText('Verified contact enquiry')).toBeNull()
  expect(screen.queryByText('Email verified. Your full application has not been submitted.')).toBeNull()
  expect(screen.queryByText('Your contact details are saved')).toBeNull()
  expect(requests).toEqual([{action:'context'}])
  expect(screen.queryByRole('button',{name:'Back to preview'})).toBeNull()
  fireEvent.click(screen.getByRole('button',{name:'Restart preview'}))
  await screen.findByRole('form',{name:'Create applicant account'})
  expect(requests).toEqual([{action:'context'}])
})
