import { recruitmentReviewChecks, recruitmentReviewSummary, reviewStatuses, documentReviewStatuses } from './recruitmentReviewModel'
const input = 'mt-2 block w-full rounded-xl border border-[#dbe6f1] bg-white px-3 py-2 text-sm text-[#142132]'
const button = 'rounded-xl border border-[#dbe4ee] bg-white px-4 py-3 text-sm font-semibold text-[#405b75] disabled:opacity-50'
const date = (value) => value ? new Date(value).toLocaleString('en-ZA', { timeZone:'Africa/Johannesburg' }) : '—'
export default function RecruitmentReviewPanel({ lead, draft, onChange, onStart, onSave, onDownload, busy, dirty, detailsDirty }) {
  if (!lead.application_submitted_at || !['application_submitted','under_review','application_approved','contract_sent','contract_signed','onboarding_complete','agent_activated','closed_lost'].includes(lead.status)) return null
  const summary = recruitmentReviewSummary(lead), active = lead.status === 'under_review'
  const updateCheck = (key, patch) => onChange({ ...draft, checks:{ ...draft.checks,[key]:{ ...draft.checks[key],...patch } } })
  const updateDocument = (path, patch) => onChange({ ...draft, documents:draft.documents.map((item) => item.path === path ? {...item,...patch} : item) })
  return <section className="mt-6 rounded-2xl border border-[#dbe7f2] bg-[#fbfdff] p-5" aria-label="Application review">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-[#20364c]">Application review</h3><p className="mt-2 text-sm text-[#60758b]">Review the submitted answers and record what you checked. The original application stays unchanged.</p></div><span className={`rounded-full px-3 py-2 text-xs font-semibold ${lead.approved_at || summary.status === 'ready_for_approval' ? 'bg-[#e9f7ed] text-[#26724c]' : summary.status === 'needs_information' ? 'bg-[#fff3de] text-[#8b5f13]' : 'bg-[#edf4fa] text-[#405b75]'}`}>{lead.approved_at ? 'Review preserved' : summary.label}</span></header>
    {lead.status === 'application_submitted' && <div className="mt-5"><button type="button" className={button} disabled={busy || detailsDirty} onClick={onStart}>Start review</button><p className="mt-2 text-xs text-[#7890a8]">Starting review moves the application to Under Review and records the reviewer and time.</p></div>}
    {lead.review_started_at && <><p className="mt-4 text-xs text-[#7890a8]">Started {date(lead.review_started_at)} · Last saved {date(lead.review_updated_at)} · {summary.complete}/4 checks resolved</p>{lead.approved_at && <p className="mt-3 text-sm text-[#60758b]">This review is preserved with the approval decision.</p>}{lead.status === 'closed_lost' && !lead.approved_at && <p className="mt-3 text-sm text-[#60758b]">This lead is closed. Reopen it to continue the saved review.</p>}
      <form onSubmit={(event) => { event.preventDefault(); onSave(draft) }}><fieldset disabled={!active || busy || detailsDirty} className="mt-5 space-y-4">
        {recruitmentReviewChecks(lead).map((requirement) => { const check = draft.checks[requirement.key], saved = lead.review_json?.checks?.[requirement.key]; return <article key={requirement.key} className="rounded-xl border border-[#e1eaf4] bg-white p-4"><h4 className="text-sm font-semibold text-[#20364c]">{requirement.label}</h4><p className="mt-2 text-xs text-[#60758b]">{requirement.note}</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-[#405b75]">{requirement.label} status<select className={input} value={check.status} onChange={(event) => updateCheck(requirement.key,{status:event.target.value})}>{reviewStatuses.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold text-[#405b75]">{requirement.label} findings<textarea className={input} rows={3} maxLength={2000} value={check.notes} onChange={(event) => updateCheck(requirement.key,{notes:event.target.value})} placeholder="Record the evidence checked, the information needed, or why this does not apply." /></label></div>{lead.documents_json.length > 0 && <fieldset className="mt-4"><legend className="text-xs font-semibold text-[#60758b]">Supporting documents for {requirement.label}</legend><div className="mt-2 flex flex-wrap gap-x-5 gap-y-2">{lead.documents_json.map((doc) => <label key={doc.path} className="inline-flex min-w-0 items-center gap-2 text-xs text-[#60758b]"><input type="checkbox" aria-label={`${requirement.label} evidence: ${doc.name}`} checked={check.evidence.includes(doc.path)} onChange={(event) => updateCheck(requirement.key,{evidence:event.target.checked ? [...check.evidence,doc.path] : check.evidence.filter((path) => path !== doc.path)})} /><span className="break-all">{doc.name}</span></label>)}</div></fieldset>}{saved?.updatedAt && <p className="mt-3 text-xs text-[#7890a8]">Finding last saved {date(saved.updatedAt)}</p>}</article> })}
        <article className="rounded-xl border border-[#e1eaf4] bg-white p-4"><h4 className="text-sm font-semibold text-[#20364c]">Document review</h4><p className="mt-2 text-xs text-[#60758b]">Each uploaded file starts awaiting review. Record your findings after opening the file.</p>{!lead.documents_json.length && <p className="mt-4 text-sm text-[#7890a8]">No supporting documents uploaded yet. Record missing evidence in the checks above.</p>}{lead.documents_json.map((doc) => { const review = draft.documents.find((item) => item.path === doc.path); return <div key={doc.path} className="mt-4 border-t border-[#edf2f7] pt-4"><div className="flex flex-wrap justify-between gap-3"><p className="min-w-0 break-all text-sm font-semibold text-[#20364c]">{doc.name} <span className="text-xs font-normal text-[#7890a8]">· {doc.type}</span></p><button type="button" className="text-sm font-semibold text-[#315b7a]" disabled={busy} onClick={() => onDownload(doc)}>Open {doc.name}</button></div><div className="mt-3 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-[#405b75]">{doc.name} review status<select className={input} value={review?.status || 'pending'} onChange={(event) => updateDocument(doc.path,{status:event.target.value})}>{documentReviewStatuses.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold text-[#405b75]">{doc.name} findings<textarea className={input} rows={2} maxLength={2000} value={review?.notes || ''} onChange={(event) => updateDocument(doc.path,{notes:event.target.value})} /></label></div></div> })}</article>
        <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-[#405b75]">Overall review / interview notes<textarea className={input} rows={4} maxLength={3000} value={draft.notes} onChange={(event) => onChange({...draft,notes:event.target.value})} /></label><label className="text-sm font-semibold text-[#405b75]">Follow-up date (optional)<input className={input} type="date" aria-label="Follow-up date (optional)" aria-describedby="recruitment-review-followup-help" value={draft.followUpOn} onChange={(event) => onChange({...draft,followUpOn:event.target.value})} /><span id="recruitment-review-followup-help" className="mt-2 block text-xs font-normal text-[#7890a8]">An internal follow-up date; saving it does not send an invitation or reminder.</span></label></div>
      </fieldset>{active && <div className="mt-5 flex flex-wrap items-center gap-3"><button className={`${button} !border-[#0f2743] !bg-[#0f2743] !text-white`} type="submit" disabled={busy || detailsDirty || !dirty}>{busy ? 'Saving…' : 'Save review'}</button><p className="text-xs text-[#7890a8]">{dirty ? 'You have unsaved review findings.' : 'All displayed findings are saved.'}</p></div>}</form>
      <p className="mt-4 text-xs text-[#7890a8]">{lead.approved_at ? 'The saved review findings are preserved with the approval record.' : summary.status === 'ready_for_approval' ? 'The review checks are resolved. Use Application approval below to record the decision.' : 'Resolve the four checks and review uploaded files to prepare for approval.'}</p>
    </>}
  </section>
}
