const date = (value) => value ? new Date(value).toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'}) : '—'
export default function RecruitmentContractPanel({lead,onPrepare,onDownload,busy,dirty}) {
  if (!lead.approved_at) return null
  const contracts=lead.contracts_json || [], current=contracts.at(-1)
  return <section className="mt-6 rounded-2xl border border-[#dbe7f2] bg-[#fbfdff] p-5" aria-label="Recruitment contract">
    <header className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-semibold text-[#20364c]">Recruitment contract</h3><p className="mt-2 text-sm text-[#60758b]">Keep the organisation’s agreement and each prepared version together.</p></div><span className="rounded-full bg-[#edf4fa] px-3 py-2 text-xs font-semibold text-[#405b75]">{current ? `Version ${current.version} prepared` : 'Awaiting contract'}</span></header>
    {lead.status === 'application_approved' && <div className="mt-5"><label className="block text-sm font-semibold text-[#405b75]">Prepare contract PDF<input type="file" aria-label="Prepare contract PDF" accept="application/pdf" disabled={busy || dirty} className="mt-2 block w-full rounded-xl border border-[#dbe6f1] bg-white px-3 py-2 text-sm text-[#142132]" onChange={(event)=>{const file=event.target.files?.[0];event.target.value='';if(file)onPrepare(file)}} /></label><p className="mt-2 text-xs text-[#7890a8]">PDF · up to 10 MB. Each upload creates a retained version. Preparing a version leaves the application at Application Approved.</p>{dirty && <p className="mt-2 text-xs text-[#7890a8]">Save or clear your edits before preparing a contract.</p>}</div>}
    {!contracts.length && <p className="mt-5 rounded-xl border border-dashed border-[#dbe7f2] p-4 text-sm text-[#60758b]">No contract prepared yet.</p>}
    <ol className="mt-5 space-y-3">{[...contracts].reverse().map(contract=><li key={contract.path} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e1eaf4] bg-white p-4"><div className="min-w-0"><p className="break-all text-sm font-semibold text-[#20364c]">{contract.name}</p><p className="mt-1 text-xs text-[#7890a8]">Version {contract.version} · Prepared {date(contract.preparedAt)}{contract.path===current?.path ? ' · Current version' : ''}</p></div><button type="button" disabled={busy} onClick={()=>onDownload(contract)} className="rounded-xl border border-[#dbe4ee] bg-white px-4 py-2 text-sm font-semibold text-[#405b75] disabled:opacity-50">Download version {contract.version}</button></li>)}</ol>
  </section>
}
