import { useState } from 'react'
import { Check, Download, FileText, Upload } from 'lucide-react'
import { getDocumentUploadPolicy } from '../../lib/documentUploadPolicy.js'
import { homeSeekersRecruitmentOrganisationId } from './recruitmentDocumentsModel'
const policy = getDocumentUploadPolicy({ surface: 'recruitment_contract' })
const date = value => value ? new Date(value).toLocaleString('en-ZA', { timeZone: 'Africa/Johannesburg' }) : '—'
export default function RecruitmentContractPanel({ lead, onPrepare, onPublish, onDownload, busy, dirty }) {
  const [file, setFile] = useState(null)
  if (!lead.approved_at) return null
  const contracts = lead.contracts_json || [], current = contracts.at(-1)
  const portal = lead.organisation_id === homeSeekersRecruitmentOrganisationId
  const published = lead.contract_delivery_json?.source === 'applicant_portal'
  return <section className="recruitment-contract" aria-label="Recruitment contract">
    <header className="recruitment-contract__heading"><span className="recruitment-contract__icon"><FileText size={24} aria-hidden="true" /></span><div><p className="recruitment-contract__eyebrow">{published ? 'Shared with applicant' : 'Next step'}</p><h3>Recruitment contract</h3><p>{portal ? 'Upload the agreement for the applicant to download, sign and return in My Profile.' : 'Keep the organisation’s agreement and each prepared version together.'}</p></div><span className="recruitment-contract__status">{published ? 'Available in My Profile' : current ? `Version ${current.version} prepared` : 'Awaiting contract'}</span></header>
    {portal && <ol className="recruitment-contract__steps" aria-label="Contract journey"><li><span>{published ? <Check size={15} aria-hidden="true" /> : '1'}</span>Upload & share</li><li><span>{lead.contract_returns_json?.length ? <Check size={15} aria-hidden="true" /> : '2'}</span>Applicant signs & returns</li><li><span>{lead.contract_signature_json?.recordedAt ? <Check size={15} aria-hidden="true" /> : '3'}</span>Agency verifies</li></ol>}
    {lead.status === 'application_approved' && <form className="recruitment-contract__upload" onSubmit={event => { event.preventDefault(); if (file && !busy && !dirty) onPrepare(file) }}><div><label className="recruitment-contract__choose"><Upload size={19} aria-hidden="true" /><strong>{file ? file.name : 'Choose contract PDF'}</strong><span>{policy.helpText}</span><input type="file" aria-label="Prepare contract PDF" accept={policy.accept} disabled={busy || dirty} onChange={event => setFile(event.target.files?.[0] || null)} /></label></div><button type="submit" disabled={busy || dirty || !file} className="recruitment-contract__button recruitment-ci-primary-button">{busy ? 'Saving…' : portal ? 'Upload and share contract' : 'Prepare contract PDF'}</button><p>{portal ? 'The applicant is emailed automatically. Sharing moves the application to Contract Sent.' : 'Each upload creates a retained version.'}</p>{dirty && <p>Save or clear your edits before uploading.</p>}</form>}
    {published && <p className="recruitment-contract__shared"><Check size={16} aria-hidden="true" />Available to {lead.email} · Shared {date(lead.contract_delivery_json.recordedAt)}</p>}
    {!!contracts.length && <ol className="recruitment-contract__files">{[...contracts].reverse().map(contract => <li key={contract.path}><FileText size={19} aria-hidden="true" /><div><strong>{contract.name}</strong><span>Version {contract.version} · Uploaded {date(contract.preparedAt)}</span></div><button type="button" disabled={busy} onClick={() => onDownload(contract)} className="recruitment-contract__button"><Download size={15} aria-hidden="true" />Download version {contract.version}</button>{portal && !published && lead.status === 'application_approved' && contract.path === current?.path && <button type="button" disabled={busy || dirty} className="recruitment-contract__button recruitment-ci-primary-button" onClick={onPublish}>Share in My Profile</button>}</li>)}</ol>}
  </section>
}
