export const PROPERTY24_API_BASE_PATH = '/api/property24'

export const PROPERTY24_API_ROUTES = {
  previewListing: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/preview`,
  previewRentalListing: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/preview`,
  publishListing: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/publish`,
  publishRentalListing: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/publish`,
  reassignListingAgent: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/reassign-agent`,
  reassignRentalListingAgent: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/reassign-agent`,
  listingLifecycle: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/lifecycle`,
  rentalLifecycle: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/lifecycle`,
  listingStatus: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/status`,
  rentalStatus: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/status`,
  updateListingStatus: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/status-update`,
  updateRentalStatus: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/status-update`,
  withdrawListing: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/withdraw`,
  withdrawRentalListing: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/withdraw`,
  reconcileRentalListing: `${PROPERTY24_API_BASE_PATH}/rentals/:listingId/reconcile`,
  listingLeads: `${PROPERTY24_API_BASE_PATH}/listings/:listingId/leads`,
  pullLeads: `${PROPERTY24_API_BASE_PATH}/leads/pull`,
  runReconciliation: `${PROPERTY24_API_BASE_PATH}/reconciliation/run`,
}

export const PROPERTY24_API_METHODS = {
  previewListing: 'POST',
  previewRentalListing: 'POST',
  publishListing: 'POST',
  publishRentalListing: 'POST',
  reassignListingAgent: 'POST',
  reassignRentalListingAgent: 'POST',
  listingLifecycle: 'GET',
  rentalLifecycle: 'GET',
  listingStatus: 'GET',
  rentalStatus: 'GET',
  updateListingStatus: 'POST',
  updateRentalStatus: 'POST',
  withdrawListing: 'POST',
  withdrawRentalListing: 'POST',
  reconcileRentalListing: 'POST',
  listingLeads: 'GET',
  pullLeads: 'POST',
  runReconciliation: 'POST',
}
