import { Activity, AlertTriangle, LoaderCircle, RefreshCw, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useWorkspace } from '../../context/WorkspaceContext'
import { getKnowledgeFactoryOperationsSnapshot } from '../../services/propertyIntelligence/knowledgeFactoryOperationsService'

export default function KnowledgeFactoryOperationsWorkspace() {
  const { currentWorkspace } = useWorkspace(); const organisationId = currentWorkspace?.organisationId || currentWorkspace?.organisation_id || currentWorkspace?.id || ''
  const [state, setState] = useState({ loading: true, data: null, error: '' })
  async function load() { setState((p) => ({ ...p, loading: true, error: '' })); try { setState({ loading: false, data: await getKnowledgeFactoryOperationsSnapshot({ organisationId }), error: '' }) } catch (error) { setState({ loading: false, data: null, error: error?.message || 'Operations data is unavailable.' }) } }
  useEffect(() => { void load() }, [organisationId])
  const data = state.data
  return <section className="space-y-5" data-canvassing-workspace="knowledge-factory-operations"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><ShieldCheck className="mt-0.5 text-[#1769dc]" size={20} /><div><h2 className="text-lg font-semibold">Knowledge Factory operations</h2><p className="mt-1 text-sm text-slate-500">Admin-only visibility for permissions, recorded credit usage, rollout readiness and audit activity.</p></div></div><button type="button" onClick={() => void load()} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-semibold"><RefreshCw size={15} />Refresh</button></div></div>{state.error ? <p className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><AlertTriangle size={17} />{state.error}</p> : null}{state.loading ? <div className="grid min-h-52 place-items-center"><LoaderCircle className="animate-spin" /></div> : data ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Organisation access', data.access?.enabled && !data.access?.suspended_at ? 'Enabled' : 'Disabled'], ['Named users', data.permissions.filter((p) => !p.revoked_at).length], ['Recorded credits', new Intl.NumberFormat('en-ZA').format(data.credits)], ['Pending sensitive approvals', data.pendingLookups]].map(([label, value]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></article>)}</div><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h3 className="font-semibold">Recent audited activity</h3><p className="mt-1 text-sm text-slate-500">Emergency suspension remains an explicit administrator change in the access-control record.</p></div>{data.events.length ? <div className="divide-y divide-slate-100">{data.events.map((event, index) => <div key={`${event.created_at}-${index}`} className="flex flex-wrap items-center justify-between gap-3 p-4 text-sm"><div><p className="font-medium text-slate-800">{event.operation.replace(/_/g, ' ')} · {event.outcome}</p><p className="mt-1 text-xs text-slate-500">{event.request_purpose}</p></div><span className="text-xs font-semibold text-slate-600">{Number(event.credits_consumed || 0).toLocaleString('en-ZA')} credits</span></div>)}</div> : <div className="p-10 text-center text-sm text-slate-500"><Activity className="mx-auto mb-3 text-slate-400" />No audited activity yet.</div>}</section></> : null}</section>
}
