-- Recovery only: do not run during the normal release. Restore the previous app first.
-- Preserves application, document, screening and digital-card records.
begin;
drop trigger if exists provision_agent_digital_card on public.organisation_users;
drop trigger if exists trg_rental_application_review_integrity on public.rental_applications;
drop trigger if exists trg_rental_application_draft_intake_guard on public.rental_applications;
drop trigger if exists trg_rental_application_document_intake_guard on public.rental_application_documents;
CREATE OR REPLACE FUNCTION public.home_seekers_fic_training_is_enabled(p_organisation_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select exists (
    select 1
    from public.organisations organisation
    where organisation.id = p_organisation_id
      and lower(trim(coalesce(organisation.name, ''))) = 'home seekers'
  );
$function$
;
CREATE OR REPLACE FUNCTION public.rental_convert_application_to_tenancy(p_application_id uuid, p_expected_version integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  application_row public.rental_applications%rowtype;
  unit_row public.rental_units%rowtype;
  tenancy_id uuid;
  lease_id uuid;
  occupation_date date;
begin
  if auth.uid() is null then raise exception 'Authentication is required'; end if;
  select application.* into application_row from public.rental_applications application where application.id = p_application_id for update;
  if not found then raise exception 'Rental application not found'; end if;
  if not exists (
    select 1 from public.rental_vacancies vacancy
    join public.rental_properties property on property.id = vacancy.property_id
    where vacancy.id = application_row.vacancy_id
      and public.rental_branch_access(property.organisation_id, property.branch_id)
  ) then raise exception 'You are not authorized for this rental application'; end if;

  select tenancy.id into tenancy_id from public.rental_tenancies tenancy where tenancy.source_application_id = application_row.id;
  if tenancy_id is not null then
    select lease.id into lease_id from public.rental_leases lease where lease.tenancy_id = tenancy_id;
    if application_row.lead_id is not null then
      update public.leads
      set stage = 'Converted to tenancy',
          status = 'Converted to tenancy',
          raw_enquiry_payload = coalesce(raw_enquiry_payload, '{}'::jsonb) || jsonb_build_object(
            'stage', 'converted_to_tenancy',
            'relationships', coalesce(raw_enquiry_payload->'relationships', '{}'::jsonb) || jsonb_build_object(
              'applicationId', application_row.id::text,
              'tenancyId', tenancy_id::text
            )
          ),
          updated_at = now()
      where lead_id = application_row.lead_id and organisation_id = application_row.organisation_id;
    end if;
    return jsonb_build_object('tenancy_id', tenancy_id, 'lease_id', lease_id, 'lead_id', application_row.lead_id, 'idempotent', true);
  end if;

  if application_row.status <> 'approved' then raise exception 'Only an approved application can be converted to a tenancy'; end if;
  if application_row.version <> p_expected_version then raise exception 'This application changed. Refresh and try again.' using errcode = '40001'; end if;
  select unit.* into unit_row from public.rental_units unit where unit.id = application_row.unit_id for update;
  if not found or unit_row.organisation_id <> application_row.organisation_id then raise exception 'Rental unit does not match application'; end if;
  if unit_row.active_tenancy_id is not null or unit_row.status in ('lease_pending', 'occupied', 'notice_given', 'maintenance_hold') then raise exception 'This rental unit is not available for tenancy conversion'; end if;

  occupation_date := nullif(application_row.application_data #>> '{rentalHistory,intendedOccupationDate}', '')::date;
  insert into public.rental_tenancies(organisation_id, property_id, unit_id, source_application_id, intended_occupation_date, tenant_snapshot_json, created_by)
  select application_row.organisation_id, vacancy.property_id, application_row.unit_id, application_row.id, occupation_date,
    jsonb_build_object('identity', coalesce(application_row.application_data->'identity', '{}'::jsonb), 'employment', coalesce(application_row.application_data->'employment', '{}'::jsonb)), auth.uid()
  from public.rental_vacancies vacancy where vacancy.id = application_row.vacancy_id returning id into tenancy_id;

  if application_row.applicant_party_id is not null then
    insert into public.rental_tenancy_parties(tenancy_id, organisation_id, party_id, role, is_primary)
    values (tenancy_id, application_row.organisation_id, application_row.applicant_party_id, 'tenant', true);
  end if;
  insert into public.rental_leases(tenancy_id, organisation_id, terms_json, source_application_id, created_by)
  select tenancy_id, application_row.organisation_id, jsonb_build_object('monthly_rent', vacancy.asking_rent, 'deposit_amount', vacancy.deposit_amount, 'lease_term_months', vacancy.lease_term_months, 'intended_occupation_date', occupation_date), application_row.id, auth.uid()
  from public.rental_vacancies vacancy where vacancy.id = application_row.vacancy_id returning id into lease_id;
  perform set_config('app.rental_tenancy_command', 'on', true);
  update public.rental_units set status = 'lease_pending' where id = unit_row.id;

  if application_row.lead_id is not null then
    update public.leads
    set stage = 'Converted to tenancy',
        status = 'Converted to tenancy',
        raw_enquiry_payload = coalesce(raw_enquiry_payload, '{}'::jsonb) || jsonb_build_object(
          'stage', 'converted_to_tenancy',
          'relationships', coalesce(raw_enquiry_payload->'relationships', '{}'::jsonb) || jsonb_build_object(
            'applicationId', application_row.id::text,
            'tenancyId', tenancy_id::text
          )
        ),
        updated_at = now()
    where lead_id = application_row.lead_id and organisation_id = application_row.organisation_id;
  end if;

  return jsonb_build_object('tenancy_id', tenancy_id, 'lease_id', lease_id, 'lead_id', application_row.lead_id, 'idempotent', false, 'tenant_party_reused', application_row.applicant_party_id is not null);
exception when unique_violation then
  select tenancy.id into tenancy_id from public.rental_tenancies tenancy where tenancy.source_application_id = p_application_id;
  if tenancy_id is not null then
    select lease.id into lease_id from public.rental_leases lease where lease.tenancy_id = tenancy_id;
    return jsonb_build_object('tenancy_id', tenancy_id, 'lease_id', lease_id, 'lead_id', application_row.lead_id, 'idempotent', true);
  end if;
  raise;
end; $function$
;
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=4, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the VAT, zero-rated, or exemption evidence for the selected route.", "title": "Verify VAT / Exemption Evidence"}, "stepKey": "vat_exemption_evidence_verified"}'::jsonb where lane_key='transfer' and step_key='vat_exemption_evidence_verified';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=5, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review withholding-tax requirements for a non-resident seller where applicable.", "title": "Review Non-Resident Seller Withholding"}, "stepKey": "non_resident_seller_withholding_review"}'::jsonb where lane_key='transfer' and step_key='non_resident_seller_withholding_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=6, definition='{"client": {"description": "The applicable transfer-tax clearance has been verified.", "title": "Transfer tax clearance"}, "clientVisibleAllowed": true, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the applicable SARS transfer-duty, VAT, zero-rated, or exemption proof before lodgement.", "title": "Verify SARS Transfer-Tax Receipt"}, "stepKey": "sars_transfer_tax_receipt_verified"}'::jsonb where lane_key='transfer' and step_key='sars_transfer_tax_receipt_verified';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=7, definition='{"client": {"description": "Property transfer is currently at: Review Municipal Rates Clearance.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "client_visible", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review rates figures, payment evidence, and the municipal rates-clearance certificate in one place.", "title": "Review Municipal Rates Clearance"}, "stepKey": "municipal_rates_clearance_review"}'::jsonb where lane_key='transfer' and step_key='municipal_rates_clearance_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=8, definition='{"client": {"description": "Property transfer is currently at: Review Levy / HOA Clearance.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the body-corporate or HOA clearance only where the property requires it.", "title": "Review Levy / HOA Clearance"}, "stepKey": "levy_hoa_clearance_review"}'::jsonb where lane_key='transfer' and step_key='levy_hoa_clearance_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=9, definition='{"client": {"description": "Property transfer is currently at: Review Property Compliance Certificates.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review only the compliance certificates that apply to this property and agreement.", "title": "Review Property Compliance Certificates"}, "stepKey": "property_compliance_review"}'::jsonb where lane_key='transfer' and step_key='property_compliance_review';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Prepare & Review Transfer Document Pack.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Prepare the transfer pack and review it against the OTP, parties, property, and finance route.", "title": "Prepare & Review Transfer Document Pack"}, "stepKey": "transfer_document_pack_review"}'::jsonb where lane_key='transfer' and step_key='transfer_document_pack_review';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Complete Buyer Signing.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Schedule or manage the buyer signing route, then review the signed transfer documents.", "title": "Complete Buyer Signing"}, "stepKey": "buyer_signing_review"}'::jsonb where lane_key='transfer' and step_key='buyer_signing_review';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=2, definition='{"client": {"description": "Property transfer is currently at: Complete Seller Signing.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Schedule or manage the seller signing route, then review the signed transfer documents.", "title": "Complete Seller Signing"}, "stepKey": "seller_signing_review"}'::jsonb where lane_key='transfer' and step_key='seller_signing_review';
update journey_private.task_catalog set phase_key='post_registration', phase_label='Post-Registration & Closure', phase_order=5, task_order=1, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Close the file after financial close-out, recipient-scoped registration communication, and any linked attorney lanes are complete.", "title": "Matter Closed"}, "stepKey": "matter_closed"}'::jsonb where lane_key='transfer' and step_key='matter_closed';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=7, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record the specific statutory exemption and review its supporting proof.", "title": "Verify Claimed Exemption"}, "stepKey": "transfer_duty_exemption_basis_verified"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_exemption_basis_verified';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=8, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Resolve withholding applicability independently for every potentially non-resident seller and seller type.", "title": "Review Each Non-Resident Seller"}, "stepKey": "non_resident_seller_applicability_review"}'::jsonb where lane_key='transfer' and step_key='non_resident_seller_applicability_review';
update journey_private.task_catalog set phase_key='instruction', phase_label='Instruction & File Opening', phase_order=0, task_order=4, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Any seller existing bond and cancellation requirement is confirmed.", "title": "Existing Bond or Cancellation Requirement Confirmed"}, "stepKey": "existing_bond_confirmed"}'::jsonb where lane_key='transfer' and step_key='existing_bond_confirmed';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=0, definition='{"client": {"description": "The transfer attorneys are reviewing the applicable transfer tax route.", "title": "Transfer tax review in progress"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The applicable transfer duty, exemption or VAT evidence is under review.", "title": "Transfer tax reviewed"}, "stepKey": "transfer_duty_vat_review"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_vat_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=9, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the issued directive and its reference for each seller relying on one.", "title": "Verify SARS Directive"}, "stepKey": "non_resident_seller_directive_review"}'::jsonb where lane_key='transfer' and step_key='non_resident_seller_directive_review';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=3, definition='{"client": {"description": "Property transfer is currently at: Review Payment Security.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the applicable guarantee, bond, undertaking, or cleared-trust-funds route and its evidence.", "title": "Review Payment Security"}, "stepKey": "payment_security_review"}'::jsonb where lane_key='transfer' and step_key='payment_security_review';
update journey_private.task_catalog set phase_key='lodgement_registration', phase_label='Lodgement & Registration', phase_order=4, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Lodgement Ready.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the completed lodgement pack and coordination position, then confirm that the transfer is ready for lodgement.", "title": "Lodgement Ready"}, "stepKey": "lodgement_ready"}'::jsonb where lane_key='transfer' and step_key='lodgement_ready';
update journey_private.task_catalog set phase_key='lodgement_registration', phase_label='Lodgement & Registration', phase_order=4, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Lodged at Deeds Office.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record the Deeds Office lodgement once the submission has been accepted.", "title": "Lodged at Deeds Office"}, "stepKey": "lodged_at_deeds_office"}'::jsonb where lane_key='transfer' and step_key='lodged_at_deeds_office';
update journey_private.task_catalog set phase_key='lodgement_registration', phase_label='Lodgement & Registration', phase_order=4, task_order=2, definition='{"client": {"description": "Property transfer is currently at: On Prep.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record Deeds Office prep once the matter is in preparation for registration.", "title": "On Prep"}, "stepKey": "in_prep"}'::jsonb where lane_key='transfer' and step_key='in_prep';
update journey_private.task_catalog set phase_key='lodgement_registration', phase_label='Lodgement & Registration', phase_order=4, task_order=3, definition='{"client": {"description": "Property transfer is currently at: Registered.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Confirm the transfer registration and capture its registration evidence before close-out begins.", "title": "Registered"}, "stepKey": "registered"}'::jsonb where lane_key='transfer' and step_key='registered';
update journey_private.task_catalog set phase_key='post_registration', phase_label='Post-Registration & Closure', phase_order=5, task_order=0, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the final account, proceeds, refunds, fees, and settlement position before closing the file.", "title": "Review Final Accounts"}, "stepKey": "post_registration_closeout_review"}'::jsonb where lane_key='transfer' and step_key='post_registration_closeout_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=2, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record a separate identity, beneficial ownership, representative, marital and signing authority decision for every buyer and applicable signatory.", "title": "Resolve Each Buyer Capacity"}, "stepKey": "buyer_party_capacity_review"}'::jsonb where lane_key='transfer' and step_key='buyer_party_capacity_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=3, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record a separate identity, beneficial ownership, representative, marital and signing authority decision for every seller and applicable signatory.", "title": "Resolve Each Seller Capacity"}, "stepKey": "seller_party_capacity_review"}'::jsonb where lane_key='transfer' and step_key='seller_party_capacity_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=4, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Hold the ordinary transfer route for an estate, insolvency, unknown legal type or other exceptional capacity until a reviewed specialist route is available.", "title": "Specialist Party Capacity Hold"}, "stepKey": "party_capacity_specialist_review"}'::jsonb where lane_key='transfer' and step_key='party_capacity_specialist_review';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=3, definition='{"client": {"description": "Property transfer is currently at: Review Cash Funding Source.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "For cash or hybrid funding, identify the buyer funding source and review its supporting evidence before accepting payment security.", "title": "Review Cash Funding Source"}, "stepKey": "cash_funding_source_review"}'::jsonb where lane_key='transfer' and step_key='cash_funding_source_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=5, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify vendor status, enterprise supply, agreement treatment and VAT evidence.", "title": "Verify Ordinary VAT Basis"}, "stepKey": "ordinary_vat_basis_verified"}'::jsonb where lane_key='transfer' and step_key='ordinary_vat_basis_verified';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=6, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the written going-concern agreement and the facts supporting the claimed zero rate.", "title": "Verify Going-Concern Zero Rate"}, "stepKey": "going_concern_zero_rate_verified"}'::jsonb where lane_key='transfer' and step_key='going_concern_zero_rate_verified';
update journey_private.task_catalog set phase_key='instruction', phase_label='Instruction & File Opening', phase_order=0, task_order=2, definition='{"client": {"description": "Property transfer is currently at: OTP and Source Documents Checked.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The sale agreement, parties, purchase price, suspensive conditions, and property details are checked.", "title": "OTP and Source Documents Checked"}, "stepKey": "otp_source_docs_checked"}'::jsonb where lane_key='transfer' and step_key='otp_source_docs_checked';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Buyer FICA Requested.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Buyer identity, address, and entity authority documents have been requested.", "title": "Buyer FICA Requested"}, "stepKey": "buyer_fica_requested"}'::jsonb where lane_key='transfer' and step_key='buyer_fica_requested';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Buyer FICA Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Buyer FICA and authority documents have been received for review.", "title": "Buyer FICA Received"}, "stepKey": "buyer_fica_received"}'::jsonb where lane_key='transfer' and step_key='buyer_fica_received';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=2, definition='{"client": {"description": "Property transfer is currently at: Buyer FICA Approved.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Buyer FICA and authority documents have been reviewed and approved.", "title": "Buyer FICA Approved"}, "stepKey": "buyer_fica_approved"}'::jsonb where lane_key='transfer' and step_key='buyer_fica_approved';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=3, definition='{"client": {"description": "Property transfer is currently at: Seller FICA Requested.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Seller identity, address, and authority documents have been requested.", "title": "Seller FICA Requested"}, "stepKey": "seller_fica_requested"}'::jsonb where lane_key='transfer' and step_key='seller_fica_requested';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=4, definition='{"client": {"description": "Property transfer is currently at: Seller FICA Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Seller FICA and authority documents have been received for review.", "title": "Seller FICA Received"}, "stepKey": "seller_fica_received"}'::jsonb where lane_key='transfer' and step_key='seller_fica_received';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=5, definition='{"client": {"description": "Property transfer is currently at: Seller FICA Approved.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Seller FICA and authority documents have been reviewed and approved.", "title": "Seller FICA Approved"}, "stepKey": "seller_fica_approved"}'::jsonb where lane_key='transfer' and step_key='seller_fica_approved';
update journey_private.task_catalog set phase_key='instruction', phase_label='Instruction & File Opening', phase_order=0, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Instruction Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The transfer instruction and source documents have been received.", "title": "Instruction Received"}, "stepKey": "instruction_received"}'::jsonb where lane_key='transfer' and step_key='instruction_received';
update journey_private.task_catalog set phase_key='instruction', phase_label='Instruction & File Opening', phase_order=0, task_order=1, definition='{"client": {"description": "Property transfer is currently at: File Opened and Matter Number Assigned.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The conveyancing file is opened and a matter number is recorded.", "title": "File Opened and Matter Number Assigned"}, "stepKey": "matter_opened"}'::jsonb where lane_key='transfer' and step_key='matter_opened';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Review & Approve Buyer FICA.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the buyer''s applicable identity, address and authority documents in one pack.", "title": "Review & Approve Buyer FICA"}, "stepKey": "buyer_fica_review"}'::jsonb where lane_key='transfer' and step_key='buyer_fica_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Review & Approve Seller FICA.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review the seller''s applicable identity, address and authority documents in one pack.", "title": "Review & Approve Seller FICA"}, "stepKey": "seller_fica_review"}'::jsonb where lane_key='transfer' and step_key='seller_fica_review';
update journey_private.task_catalog set phase_key='instruction', phase_label='Instruction & File Opening', phase_order=0, task_order=3, definition='{"client": {"description": "Property transfer is currently at: Title Deed or Ownership Checked.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The title deed, ownership, restrictions, and property description are checked.", "title": "Title Deed or Ownership Checked"}, "stepKey": "title_deed_checked"}'::jsonb where lane_key='transfer' and step_key='title_deed_checked';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=6, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Company, trust, spouse, marital, or signatory authority is checked where applicable.", "title": "Entity Authority Checked"}, "stepKey": "entity_authority_checked"}'::jsonb where lane_key='transfer' and step_key='entity_authority_checked';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Transfer Duty Assessment Prepared.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Transfer duty or exemption/VAT treatment is calculated and checked.", "title": "Transfer Duty Assessment Prepared"}, "stepKey": "transfer_duty_assessment_prepared"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_assessment_prepared';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Transfer Duty Submitted.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Transfer duty declaration or exemption submission has been sent.", "title": "Transfer Duty Submitted"}, "stepKey": "transfer_duty_submitted"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_submitted';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=2, definition='{"client": {"description": "Property transfer is currently at: Transfer Duty Receipt Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Transfer duty receipt or exemption confirmation has been received.", "title": "Transfer Duty Receipt Received"}, "stepKey": "transfer_duty_receipt_received"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_receipt_received';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=3, definition='{"client": {"description": "The attorneys have requested the municipal rates clearance figures and are awaiting the municipality.", "title": "Rates clearance requested"}, "clientVisibleAllowed": true, "defaultVisibility": "client_visible", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Municipal rates clearance figures have been requested and the transaction is awaiting the municipality.", "title": "Rates Figures Requested"}, "stepKey": "rates_figures_requested"}'::jsonb where lane_key='transfer' and step_key='rates_figures_requested';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=4, definition='{"client": {"description": "Property transfer is currently at: Rates Payment Confirmed.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Rates amount due has been paid or payment arrangement is confirmed.", "title": "Rates Payment Confirmed"}, "stepKey": "rates_payment_confirmed"}'::jsonb where lane_key='transfer' and step_key='rates_payment_confirmed';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=5, definition='{"client": {"description": "The attorneys have received the municipal rates clearance certificate.", "title": "Rates clearance received"}, "clientVisibleAllowed": true, "defaultVisibility": "client_visible", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The municipal rates clearance certificate has been received and checked against the matter requirements.", "title": "Rates Clearance Certificate Received"}, "stepKey": "rates_clearance_received"}'::jsonb where lane_key='transfer' and step_key='rates_clearance_received';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=6, definition='{"client": {"description": "Property transfer is currently at: Levy Clearance Requested.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Levy, HOA, or body corporate clearance has been requested where applicable.", "title": "Levy Clearance Requested"}, "stepKey": "levy_clearance_requested"}'::jsonb where lane_key='transfer' and step_key='levy_clearance_requested';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=7, definition='{"client": {"description": "Property transfer is currently at: Levy Clearance Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Levy, HOA, or body corporate clearance has been received where applicable.", "title": "Levy Clearance Received"}, "stepKey": "levy_clearance_received"}'::jsonb where lane_key='transfer' and step_key='levy_clearance_received';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=8, definition='{"client": {"description": "Property transfer is currently at: Compliance Certificates Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Electrical, gas, beetle, electric fence, plumbing, or other compliance certificates have been received as applicable.", "title": "Compliance Certificates Received"}, "stepKey": "compliance_certificates_received"}'::jsonb where lane_key='transfer' and step_key='compliance_certificates_received';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Transfer Documents Prepared.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The transfer document pack has been prepared for signature.", "title": "Transfer Documents Prepared"}, "stepKey": "transfer_documents_prepared"}'::jsonb where lane_key='transfer' and step_key='transfer_documents_prepared';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Buyer Signing Scheduled.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Buyer signing appointment or remote signing path has been scheduled.", "title": "Buyer Signing Scheduled"}, "stepKey": "buyer_signing_scheduled"}'::jsonb where lane_key='transfer' and step_key='buyer_signing_scheduled';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=2, definition='{"client": {"description": "Property transfer is currently at: Buyer Signed Transfer Documents.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Buyer signatures for the transfer pack have been received.", "title": "Buyer Signed Transfer Documents"}, "stepKey": "buyer_signed_transfer_documents"}'::jsonb where lane_key='transfer' and step_key='buyer_signed_transfer_documents';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=3, definition='{"client": {"description": "Property transfer is currently at: Seller Signing Scheduled.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Seller signing appointment or remote signing path has been scheduled.", "title": "Seller Signing Scheduled"}, "stepKey": "seller_signing_scheduled"}'::jsonb where lane_key='transfer' and step_key='seller_signing_scheduled';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=4, definition='{"client": {"description": "Property transfer is currently at: Seller Signed Transfer Documents.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Seller signatures for the transfer pack have been received.", "title": "Seller Signed Transfer Documents"}, "stepKey": "seller_signed_transfer_documents"}'::jsonb where lane_key='transfer' and step_key='seller_signed_transfer_documents';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=5, definition='{"client": {"description": "Property transfer is currently at: Guarantees Requested.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Guarantees or cash undertakings have been requested from the bond attorney, bank, or buyer.", "title": "Guarantees Requested"}, "stepKey": "guarantees_requested"}'::jsonb where lane_key='transfer' and step_key='guarantees_requested';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=6, definition='{"client": {"description": "Property transfer is currently at: Guarantees Received.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Guarantees or cash undertakings have been received.", "title": "Guarantees Received"}, "stepKey": "guarantees_received"}'::jsonb where lane_key='transfer' and step_key='guarantees_received';
update journey_private.task_catalog set phase_key='documents_guarantees', phase_label='Documents & Guarantees', phase_order=3, task_order=7, definition='{"client": {"description": "Property transfer is currently at: Guarantees Accepted.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Guarantee wording and amount have been accepted for transfer readiness.", "title": "Guarantees Accepted"}, "stepKey": "transfer_guarantees_accepted"}'::jsonb where lane_key='transfer' and step_key='transfer_guarantees_accepted';
update journey_private.task_catalog set phase_key='lodgement_registration', phase_label='Lodgement & Registration', phase_order=4, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Lodgement Pack Prepared.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "The transfer lodgement pack has been assembled and checked.", "title": "Lodgement Pack Prepared"}, "stepKey": "lodgement_pack_prepared"}'::jsonb where lane_key='transfer' and step_key='lodgement_pack_prepared';
update journey_private.task_catalog set phase_key='post_registration', phase_label='Post-Registration & Closure', phase_order=5, task_order=0, definition='{"client": {"description": "Property transfer is currently at: Final Accounts and Statement Prepared.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Final accounts, pro-rations, and statements are prepared.", "title": "Final Accounts and Statement Prepared"}, "stepKey": "final_accounts_prepared"}'::jsonb where lane_key='transfer' and step_key='final_accounts_prepared';
update journey_private.task_catalog set phase_key='post_registration', phase_label='Post-Registration & Closure', phase_order=5, task_order=1, definition='{"client": {"description": "Property transfer is currently at: Registration Letter Issued.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Registration letter and final stakeholder notifications have been issued.", "title": "Registration Letter Issued"}, "stepKey": "registration_letter_issued"}'::jsonb where lane_key='transfer' and step_key='registration_letter_issued';
update journey_private.task_catalog set phase_key='bond_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=0, definition='{"client": {"description": "Bond registration is currently at: Bond Instruction Received.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Bond attorney instruction has been received and logged.", "title": "Bond Instruction Received"}, "stepKey": "bond_instruction_received"}'::jsonb where lane_key='bond' and step_key='bond_instruction_received';
update journey_private.task_catalog set phase_key='bond_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=1, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Bank, branch, bond amount, and reference/account details are captured.", "title": "Bank and Reference Captured"}, "stepKey": "bank_reference_captured"}'::jsonb where lane_key='bond' and step_key='bank_reference_captured';
update journey_private.task_catalog set phase_key='bond_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=2, definition='{"client": {"description": "Bond registration is currently at: Grant / Approval Letter Received.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "The bank grant or bond approval letter has been received.", "title": "Grant / Approval Letter Received"}, "stepKey": "bond_approval_letter_received"}'::jsonb where lane_key='bond' and step_key='bond_approval_letter_received';
update journey_private.task_catalog set phase_key='bond_conditions', phase_label='Bank Conditions', phase_order=1, task_order=0, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Bank conditions and attorney requirements have been reviewed.", "title": "Bank Conditions Reviewed"}, "stepKey": "bank_requirements_confirmed"}'::jsonb where lane_key='bond' and step_key='bank_requirements_confirmed';
update journey_private.task_catalog set phase_key='bond_conditions', phase_label='Bank Conditions', phase_order=1, task_order=1, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Outstanding bank conditions are captured and assigned.", "title": "Bank Conditions Outstanding"}, "stepKey": "bank_conditions_outstanding"}'::jsonb where lane_key='bond' and step_key='bank_conditions_outstanding';
update journey_private.task_catalog set phase_key='bond_conditions', phase_label='Bank Conditions', phase_order=1, task_order=2, definition='{"client": {"description": "Bond registration is currently at: Bank Conditions Resolved.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Bank conditions required before lodgement have been resolved.", "title": "Bank Conditions Resolved"}, "stepKey": "bank_conditions_resolved"}'::jsonb where lane_key='bond' and step_key='bank_conditions_resolved';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=0, definition='{"client": {"description": "Bond registration is currently at: Bond Documents Prepared.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Bond documentation has been prepared for buyer signature.", "title": "Bond Documents Prepared"}, "stepKey": "bond_documents_prepared"}'::jsonb where lane_key='bond' and step_key='bond_documents_prepared';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=1, definition='{"client": {"description": "Bond registration is currently at: Buyer Bond Signing Scheduled.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Buyer signing appointment for bond documents has been scheduled.", "title": "Buyer Bond Signing Scheduled"}, "stepKey": "buyer_bond_signing_scheduled"}'::jsonb where lane_key='bond' and step_key='buyer_bond_signing_scheduled';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=2, definition='{"client": {"description": "Bond registration is currently at: Buyer Signed Bond Documents.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Buyer signatures on the bond documents have been received.", "title": "Buyer Signed Bond Documents"}, "stepKey": "buyer_signed_bond_documents"}'::jsonb where lane_key='bond' and step_key='buyer_signed_bond_documents';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=3, definition='{"client": {"description": "Bond registration is currently at: Documents Sent to Bank for Approval.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Signed bond documents have been sent to the bank for approval where applicable.", "title": "Documents Sent to Bank for Approval"}, "stepKey": "bond_documents_sent_to_bank"}'::jsonb where lane_key='bond' and step_key='bond_documents_sent_to_bank';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=4, definition='{"client": {"description": "Bond registration is currently at: Bank Approval to Lodge Received.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "The bank has approved lodgement of the bond documents.", "title": "Bank Approval to Lodge Received"}, "stepKey": "bank_approval_to_lodge_received"}'::jsonb where lane_key='bond' and step_key='bank_approval_to_lodge_received';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=5, definition='{"client": {"description": "Bond registration is currently at: Guarantees Issued.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Guarantees have been issued to the transfer attorney.", "title": "Guarantees Issued"}, "stepKey": "guarantees_issued"}'::jsonb where lane_key='bond' and step_key='guarantees_issued';
update journey_private.task_catalog set phase_key='bond_documents', phase_label='Documents & Guarantees', phase_order=2, task_order=6, definition='{"client": {"description": "Bond registration is currently at: Guarantee Wording Accepted.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Guarantee wording has been accepted by the transfer attorney.", "title": "Guarantee Wording Accepted"}, "stepKey": "guarantee_wording_accepted"}'::jsonb where lane_key='bond' and step_key='guarantee_wording_accepted';
update journey_private.task_catalog set phase_key='bond_registration', phase_label='Lodgement & Registration', phase_order=3, task_order=0, definition='{"client": {"description": "Bond registration is currently at: Bond Lodgement Pack Ready.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "The bond pack is ready to lodge simultaneously with the transfer.", "title": "Bond Lodgement Pack Ready"}, "stepKey": "bond_lodgement_ready"}'::jsonb where lane_key='bond' and step_key='bond_lodgement_ready';
update journey_private.task_catalog set phase_key='bond_registration', phase_label='Lodgement & Registration', phase_order=3, task_order=1, definition='{"client": {"description": "Bond registration is currently at: Bond Lodged Simultaneously.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "The bond documents have been lodged with the transfer.", "title": "Bond Lodged Simultaneously"}, "stepKey": "bond_lodged"}'::jsonb where lane_key='bond' and step_key='bond_lodged';
update journey_private.task_catalog set phase_key='bond_registration', phase_label='Lodgement & Registration', phase_order=3, task_order=2, definition='{"client": {"description": "Bond registration is currently at: Bond Registered.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Bond registration has been confirmed.", "title": "Bond Registered"}, "stepKey": "bond_registered"}'::jsonb where lane_key='bond' and step_key='bond_registered';
update journey_private.task_catalog set phase_key='bond_registration', phase_label='Lodgement & Registration', phase_order=3, task_order=3, definition='{"client": {"description": "Bond registration is currently at: Bank Confirmation and Close-Out Complete.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Final bank confirmation and bond close-out tasks are complete.", "title": "Bank Confirmation and Close-Out Complete"}, "stepKey": "bond_close_out_complete"}'::jsonb where lane_key='bond' and step_key='bond_close_out_complete';
update journey_private.task_catalog set phase_key='cancellation_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=0, definition='{"client": {"description": "Bond cancellation is currently at: Existing Bond Confirmed.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "The seller existing bond requiring cancellation has been confirmed.", "title": "Existing Bond Confirmed"}, "stepKey": "cancellation_existing_bond_confirmed"}'::jsonb where lane_key='cancellation' and step_key='cancellation_existing_bond_confirmed';
update journey_private.task_catalog set phase_key='cancellation_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=1, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "The cancellation bank has been captured.", "title": "Cancellation Bank Captured"}, "stepKey": "cancellation_bank_captured"}'::jsonb where lane_key='cancellation' and step_key='cancellation_bank_captured';
update journey_private.task_catalog set phase_key='cancellation_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=2, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "The seller bond account or reference number has been captured.", "title": "Bond Account Number Captured"}, "stepKey": "cancellation_bond_account_captured"}'::jsonb where lane_key='cancellation' and step_key='cancellation_bond_account_captured';
update journey_private.task_catalog set phase_key='cancellation_instruction', phase_label='Instruction & Bank', phase_order=0, task_order=3, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Instruction Received.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Cancellation instruction has been received by the cancellation attorney.", "title": "Cancellation Instruction Received"}, "stepKey": "cancellation_instruction_received"}'::jsonb where lane_key='cancellation' and step_key='cancellation_instruction_received';
update journey_private.task_catalog set phase_key='cancellation_figures', phase_label='Notice & Figures', phase_order=1, task_order=1, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Figures Requested.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Settlement or cancellation figures have been requested from the bank.", "title": "Cancellation Figures Requested"}, "stepKey": "cancellation_figures_requested"}'::jsonb where lane_key='cancellation' and step_key='cancellation_figures_requested';
update journey_private.task_catalog set phase_key='cancellation_figures', phase_label='Notice & Figures', phase_order=1, task_order=2, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Figures Received.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Cancellation figures have been received and checked.", "title": "Cancellation Figures Received"}, "stepKey": "cancellation_figures_received"}'::jsonb where lane_key='cancellation' and step_key='cancellation_figures_received';
update journey_private.task_catalog set phase_key='cancellation_figures', phase_label='Notice & Figures', phase_order=1, task_order=3, definition='{"client": {"description": "Bond cancellation is currently at: Figures Expiry Date Captured.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "internal", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "The cancellation figures expiry date has been captured.", "title": "Figures Expiry Date Captured"}, "stepKey": "figures_expiry_captured"}'::jsonb where lane_key='cancellation' and step_key='figures_expiry_captured';
update journey_private.task_catalog set phase_key='cancellation_figures', phase_label='Notice & Figures', phase_order=1, task_order=4, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Penalty or short-notice risk is captured and escalated where needed.", "title": "Penalty and Notice Risk Captured"}, "stepKey": "notice_penalty_risk_captured"}'::jsonb where lane_key='cancellation' and step_key='notice_penalty_risk_captured';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=0, definition='{"client": {"description": "Bond cancellation is currently at: Guarantees Requested.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Guarantees have been requested from the transfer or bond attorney.", "title": "Guarantees Requested"}, "stepKey": "cancellation_guarantees_requested"}'::jsonb where lane_key='cancellation' and step_key='cancellation_guarantees_requested';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=1, definition='{"client": {"description": "Bond cancellation is currently at: Guarantees Received.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Guarantees have been received for the cancellation.", "title": "Guarantees Received"}, "stepKey": "cancellation_guarantees_received"}'::jsonb where lane_key='cancellation' and step_key='cancellation_guarantees_received';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=2, definition='{"client": {"description": "Bond cancellation is currently at: Guarantees Accepted.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Guarantees have been accepted by the cancellation bank or attorney.", "title": "Guarantees Accepted"}, "stepKey": "cancellation_guarantees_accepted"}'::jsonb where lane_key='cancellation' and step_key='cancellation_guarantees_accepted';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=3, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Documents Prepared.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Cancellation documents have been prepared or received.", "title": "Cancellation Documents Prepared"}, "stepKey": "cancellation_documents_prepared"}'::jsonb where lane_key='cancellation' and step_key='cancellation_documents_prepared';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=4, definition='{"client": {"description": "Bond cancellation is currently at: Seller Cancellation Documents Signed.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Seller cancellation documents have been signed where required.", "title": "Seller Cancellation Documents Signed"}, "stepKey": "seller_cancellation_documents_signed"}'::jsonb where lane_key='cancellation' and step_key='seller_cancellation_documents_signed';
update journey_private.task_catalog set phase_key='cancellation_registration', phase_label='Registration & Close-Out', phase_order=3, task_order=0, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Lodgement Ready.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Cancellation is ready to lodge simultaneously with the transfer and bond.", "title": "Cancellation Lodgement Ready"}, "stepKey": "cancellation_lodgement_ready"}'::jsonb where lane_key='cancellation' and step_key='cancellation_lodgement_ready';
update journey_private.task_catalog set phase_key='cancellation_registration', phase_label='Registration & Close-Out', phase_order=3, task_order=1, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Lodged Simultaneously.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Cancellation has been lodged with the linked transfer and bond.", "title": "Cancellation Lodged Simultaneously"}, "stepKey": "cancellation_lodged"}'::jsonb where lane_key='cancellation' and step_key='cancellation_lodged';
update journey_private.task_catalog set phase_key='cancellation_registration', phase_label='Registration & Close-Out', phase_order=3, task_order=2, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Registered.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Seller bond cancellation has registered.", "title": "Cancellation Registered"}, "stepKey": "cancellation_registered"}'::jsonb where lane_key='cancellation' and step_key='cancellation_registered';
update journey_private.task_catalog set phase_key='cancellation_registration', phase_label='Registration & Close-Out', phase_order=3, task_order=3, definition='{"client": {"description": "Bond cancellation is currently at: Settlement / Proof of Payment Captured.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Settlement or proof of payment has been captured after cancellation registration.", "title": "Settlement / Proof of Payment Captured"}, "stepKey": "settlement_proof_captured"}'::jsonb where lane_key='cancellation' and step_key='settlement_proof_captured';
update journey_private.task_catalog set phase_key='cancellation_registration', phase_label='Registration & Close-Out', phase_order=3, task_order=4, definition='{"client": {"description": "Bond cancellation is currently at: Cancellation Close-Out Complete.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "The cancellation matter is closed out.", "title": "Cancellation Close-Out Complete"}, "stepKey": "cancellation_close_out_complete"}'::jsonb where lane_key='cancellation' and step_key='cancellation_close_out_complete';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=0, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Confirm the transfer-duty, VAT, zero-rated, exempt, or advice route from the seller facts and agreement.", "title": "Confirm Transfer Tax Route"}, "stepKey": "transfer_tax_route_confirmed"}'::jsonb where lane_key='transfer' and step_key='transfer_tax_route_confirmed';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=1, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Prepare and submit the Transfer Duty Declaration for the transfer-duty route.", "title": "Prepare & Submit TDC01"}, "stepKey": "transfer_duty_tdc01_submission"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_tdc01_submission';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=2, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Provide supporting material only where SARS has requested it.", "title": "Respond to SARS Evidence Request"}, "stepKey": "sars_evidence_request_response"}'::jsonb where lane_key='transfer' and step_key='sars_evidence_request_response';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=3, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record the assessment and payment where transfer duty is payable.", "title": "Confirm Duty Assessment & Payment"}, "stepKey": "transfer_duty_assessment_payment"}'::jsonb where lane_key='transfer' and step_key='transfer_duty_assessment_payment';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=10, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review withholding decision, remittance and proof for each applicable seller.", "title": "Verify Non-Resident Withholding"}, "stepKey": "non_resident_seller_withholding_payment_review"}'::jsonb where lane_key='transfer' and step_key='non_resident_seller_withholding_payment_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=13, definition='{"client": {"description": "Property transfer is currently at: Review Body-Corporate Clearance.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "For sectional title, review the body-corporate clearance, issuer and validity.", "title": "Review Body-Corporate Clearance"}, "stepKey": "body_corporate_levy_clearance_review"}'::jsonb where lane_key='transfer' and step_key='body_corporate_levy_clearance_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=14, definition='{"client": {"description": "Property transfer is currently at: Review HOA Clearance.", "title": "Property transfer update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Where an HOA applies, review the HOA clearance, issuer and validity.", "title": "Review HOA Clearance"}, "stepKey": "hoa_clearance_review"}'::jsonb where lane_key='transfer' and step_key='hoa_clearance_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=15, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Decide whether title restrictions and compliance certificates apply to this property and agreement.", "title": "Classify Property Conditions"}, "stepKey": "property_conditions_applicability_review"}'::jsonb where lane_key='transfer' and step_key='property_conditions_applicability_review';
update journey_private.task_catalog set phase_key='financial_preparation', phase_label='Financial Preparation', phase_order=2, task_order=16, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Review applicable title restrictions, servitudes or conditions before lodgement.", "title": "Review Title Conditions"}, "stepKey": "title_conditions_review"}'::jsonb where lane_key='transfer' and step_key='title_conditions_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=5, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Record the attorney decision, specialist owner, instrument and evidence for every exceptional route.", "title": "Classify Specialist Routes"}, "stepKey": "specialist_classification_review"}'::jsonb where lane_key='transfer' and step_key='specialist_classification_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=6, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the executor or representative authority and the applicable deceased-estate transfer path.", "title": "Review Estate Authority and Transfer"}, "stepKey": "estate_authority_transfer_review"}'::jsonb where lane_key='transfer' and step_key='estate_authority_transfer_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=7, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the trustee or liquidator authority and the applicable transfer path.", "title": "Review Insolvency Authority and Transfer"}, "stepKey": "insolvency_authority_transfer_review"}'::jsonb where lane_key='transfer' and step_key='insolvency_authority_transfer_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=8, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the order, parties, implementation authority and required transfer instrument.", "title": "Review Court Order or Divorce Transfer"}, "stepKey": "court_order_transfer_review"}'::jsonb where lane_key='transfer' and step_key='court_order_transfer_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=9, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the restriction or servitude, consents and registrable instrument.", "title": "Resolve Unusual Title Conditions"}, "stepKey": "unusual_title_resolution_review"}'::jsonb where lane_key='transfer' and step_key='unusual_title_resolution_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=10, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify whether statutory consent or an exception applies and retain the evidence.", "title": "Review Agricultural Land Consent"}, "stepKey": "agricultural_consent_review"}'::jsonb where lane_key='transfer' and step_key='agricultural_consent_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=11, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the legal instrument and whether an ordinary deeds transfer is appropriate.", "title": "Review Share Block Instrument"}, "stepKey": "share_block_instrument_review"}'::jsonb where lane_key='transfer' and step_key='share_block_instrument_review';
update journey_private.task_catalog set phase_key='fica_authority', phase_label='FICA & Authority', phase_order=1, task_order=12, definition='{"client": null, "clientVisibleAllowed": false, "defaultVisibility": "internal", "ownerRole": "transfer_attorney", "processKey": "transfer", "processLabel": "Property transfer", "professional": {"description": "Verify the specialist decision and evidence for the exceptional route.", "title": "Review Other Specialist Route"}, "stepKey": "other_specialist_execution_review"}'::jsonb where lane_key='transfer' and step_key='other_specialist_execution_review';
update journey_private.task_catalog set phase_key='bond_registration', phase_label='Lodgement & Registration', phase_order=3, task_order=0, definition='{"client": {"description": "Bond registration is currently at: Bank Lodgement Instructions Confirmed.", "title": "Bond registration update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "bond_attorney", "processKey": "bond", "processLabel": "Bond registration", "professional": {"description": "Confirm the bank instruction to lodge, its current conditions and the linked transfer lodgement arrangements.", "title": "Bank Lodgement Instructions Confirmed"}, "stepKey": "bond_lodgement_instructions_confirmed"}'::jsonb where lane_key='bond' and step_key='bond_lodgement_instructions_confirmed';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=3, definition='{"client": {"description": "Bond cancellation is currently at: Review Settlement Guarantee Allocation.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Reconcile the bank settlement figures with each guarantee and the balance payable to the seller.", "title": "Review Settlement Guarantee Allocation"}, "stepKey": "cancellation_guarantee_allocation_review"}'::jsonb where lane_key='cancellation' and step_key='cancellation_guarantee_allocation_review';
update journey_private.task_catalog set phase_key='cancellation_documents', phase_label='Guarantees & Documents', phase_order=2, task_order=6, definition='{"client": {"description": "Bond cancellation is currently at: Bondholder Consent Confirmed.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Confirm the bondholder has consented to cancellation or release on the bank instruction and guarantees.", "title": "Bondholder Consent Confirmed"}, "stepKey": "cancellation_consent_confirmed"}'::jsonb where lane_key='cancellation' and step_key='cancellation_consent_confirmed';
update journey_private.task_catalog set phase_key='cancellation_registration', phase_label='Registration & Close-Out', phase_order=3, task_order=0, definition='{"client": {"description": "Bond cancellation is currently at: Simultaneous Lodgement Confirmed.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "professional_shared", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Agree the linked transfer, cancellation and new bond lodgement arrangement where applicable.", "title": "Simultaneous Lodgement Confirmed"}, "stepKey": "cancellation_simultaneous_lodgement_confirmed"}'::jsonb where lane_key='cancellation' and step_key='cancellation_simultaneous_lodgement_confirmed';
update journey_private.task_catalog set phase_key='cancellation_figures', phase_label='Notice & Figures', phase_order=1, task_order=0, definition='{"client": {"description": "Bond cancellation is currently at: Bond Cancellation Notice Status Captured.", "title": "Bond cancellation update"}, "clientVisibleAllowed": true, "defaultVisibility": "internal", "ownerRole": "cancellation_attorney", "processKey": "cancellation", "processLabel": "Bond cancellation", "professional": {"description": "Capture the lender-specific notice period, date and any early-settlement or penalty position.", "title": "Bond Cancellation Notice Status Captured"}, "stepKey": "notice_period_captured"}'::jsonb where lane_key='cancellation' and step_key='notice_period_captured';
create or replace view public.rental_application_review_summaries with (security_invoker=true) as  SELECT id,
    organisation_id,
    vacancy_id,
    unit_id,
    status,
    version,
    application_data,
    submitted_at,
    updated_at,
    COALESCE(( SELECT jsonb_agg(jsonb_build_object('id', d.id, 'type', d.document_type, 'status', d.status, 'name', d.file_name, 'uploaded_at', d.uploaded_at) ORDER BY d.created_at DESC) AS jsonb_agg
           FROM rental_application_documents d
          WHERE d.application_id = a.id), '[]'::jsonb) AS documents,
    COALESCE(( SELECT jsonb_agg(jsonb_build_object('type', c.consent_type, 'version', c.wording_version, 'accepted_at', c.accepted_at) ORDER BY c.accepted_at DESC) AS jsonb_agg
           FROM rental_application_consents c
          WHERE c.application_id = a.id), '[]'::jsonb) AS consents
   FROM rental_applications a;
alter table public.rental_application_events drop constraint rental_application_events_event_type_check;
alter table public.rental_application_events add constraint rental_application_events_event_type_check CHECK ((event_type = ANY (ARRAY['rental_application_approved'::text, 'rental_application_declined'::text, 'rental_application_withdrawn'::text]))) not valid;
grant INSERT on public.rental_application_consents to authenticated;
grant SELECT on public.rental_application_consents to authenticated;
grant INSERT on public.rental_application_documents to authenticated;
grant SELECT on public.rental_application_documents to authenticated;
grant UPDATE on public.rental_application_documents to authenticated;
grant INSERT on public.rental_application_screening_checks to authenticated;
grant SELECT on public.rental_application_screening_checks to authenticated;
grant UPDATE on public.rental_application_screening_checks to authenticated;
revoke execute on function public.rental_record_application_review(uuid,integer,text,jsonb) from authenticated;
commit;
