import { ArrowLeft, Loader2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useWorkspace } from '../../context/WorkspaceContext'
import { RENTAL_VACANCY_STATUSES, canTransitionRentalVacancy } from '../../services/rentals/rentalVacancyModel.js'
import { getRentalVacancy, transitionRentalVacancy } from '../../services/rentals/rentalVacancyRepository.js'
import { RentalVacancyMarketingPanel } from '../../modules/rentals/shared/vacancies/RentalVacancyMarketingPanel.jsx'
import { RentalApplicationInvitePanel } from '../../modules/rentals/shared/vacancies/RentalApplicationInvitePanel.jsx'
export function RentalVacancyDetailPage() { const { vacancyId } = useParams(); const workspace = useWorkspace(); const [vacancy, setVacancy] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const load = useCallback(async () => { try { setLoading(true); setError(''); setVacancy(await getRentalVacancy(vacancyId)) } catch (cause) { setError(cause?.message || 'Unable to load vacancy.') } finally { setLoading(false) } }, [vacancyId]); useEffect(() => { void load() }, [load]); const transition = async (status) => { try { setSaving(true); setError(''); setVacancy(await transitionRentalVacancy(vacancy, status)) } catch (cause) { setError(cause?.message || 'Unable to transition vacancy.') } finally { setSaving(false) } }; return <main className="mx-auto max-w-3xl space-y-6 px-4 py-6"><Link to="/agent/rentals/vacancies" className="inline-flex items-center gap-1 text-sm font-medium text-sky-700"><ArrowLeft className="h-4 w-4"/>Vacancies</Link>{loading ? <div className="flex justify-center py-10"><Loader2 className="h-6 w-6 animate-spin"/></div> : error ? <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p> : !vacancy ? <p className="rounded-lg border p-5 text-sm text-slate-600">Vacancy not found in this workspace.</p> : <><section className="rounded-xl border bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase text-sky-700">{vacancy.status}</p><h1 className="mt-1 text-2xl font-bold">Unit vacancy</h1><p className="mt-2 text-slate-600">R{vacancy.askingRent.toLocaleString()} · deposit R{vacancy.depositAmount.toLocaleString()} · available {vacancy.availableFrom || 'TBC'}</p><p className="mt-3 text-sm text-slate-500">Vacancy and marketing stay entirely inside Rentals. External publishing is not enabled.</p></section><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Lifecycle</h2><div className="mt-3 flex flex-wrap gap-2">{RENTAL_VACANCY_STATUSES.filter((status) => canTransitionRentalVacancy(vacancy.status, status)).map((status) => <button key={status} disabled={saving} onClick={() => void transition(status)} className="rounded-lg border px-3 py-2 text-sm capitalize hover:border-sky-300 disabled:opacity-60">Move to {status.replaceAll('_', ' ')}</button>)}</div></section><RentalApplicationInvitePanel vacancy={vacancy} userId={workspace.profile?.id || workspace.userId || ''}/><RentalVacancyMarketingPanel vacancy={vacancy} userId={workspace.profile?.id || workspace.userId || ''}/></>}</main> }
export default RentalVacancyDetailPage
