import { Building2, CalendarClock, FileText, Loader2, Send, Wrench } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useParams, useSearchParams } from 'react-router-dom'
import RentalClientPortalShell from '../../components/rentals/RentalClientPortalShell'
import { supabase } from '../../lib/supabaseClient'

const label = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (character) => character.toUpperCase())
const currency = (value) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 }).format(Number(value)) : 'Not captured'
const date = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Not available'
function Card({ icon: Icon, eyebrow, title, children }) { return <section className="rounded-[20px] border border-[#dfe7f0] bg-white p-5 shadow-[0_12px_30px_rgba(15,23,42,.05)] sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[12px] bg-[#edf5ff] text-[#1769d1]"><Icon size={19} /></span><div><p className="text-[0.7rem] font-semibold uppercase tracking-[.13em] text-[#7b8491]">{eyebrow}</p><h2 className="text-xl font-semibold tracking-[-.035em]">{title}</h2></div></div>{children}</section> }
function InstructionForm({ decisionType, setDecisionType, message, setMessage, submit, saving }) { return <form onSubmit={submit} className="mt-5 grid gap-4"><label className="text-sm font-semibold text-[#344054]">Instruction type<select value={decisionType} onChange={(event) => setDecisionType(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dbe5ef] bg-white px-3 py-2.5 font-normal text-[#203247]"><option value="maintenance_approval">Maintenance approval</option><option value="listing_instruction">Listing instruction</option><option value="general">General</option></select></label><label className="text-sm font-semibold text-[#344054]">Instruction<textarea required minLength="10" maxLength="4000" rows={4} value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dbe5ef] px-3 py-2.5 font-normal text-[#203247]" placeholder="Tell your rentals team what you would like them to action." /></label><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#10213a] px-4 text-sm font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="animate-spin" size={16} /> : <Send size={16} />}Send instruction</button></form> }

export default function RentalLandlordPortalPage({ accountMembershipId = '' }) {
  const { token = '' } = useParams(); const [searchParams] = useSearchParams(); const activeKey = searchParams.get('section') || 'overview'
  const accountMode = Boolean(accountMembershipId)
  const [data, setData] = useState(null); const [decisionType, setDecisionType] = useState('maintenance_approval'); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const accountHeaders = useCallback(async () => { if (!supabase) throw new Error('Client account access is not configured.'); const { data } = await supabase.auth.getSession(); if (!data?.session?.access_token) throw new Error('Your session has expired. Please sign in again.'); return { Authorization: `Bearer ${data.session.access_token}` } }, [])
  const load = useCallback(async () => { try { setLoading(true); const headers = accountMode ? await accountHeaders() : { Authorization: `Bearer ${token}` }; const response = await fetch(accountMode ? `/api/rentals/client-portal?audience=landlord&membershipId=${encodeURIComponent(accountMembershipId)}` : '/api/public/rental-landlord-portal', { headers }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload) } catch (cause) { setError(cause?.message || 'Unable to open landlord portal.') } finally { setLoading(false) } }, [accountHeaders, accountMembershipId, accountMode, token])
  useEffect(() => { void load() }, [load])
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); const headers = accountMode ? await accountHeaders() : { Authorization: `Bearer ${token}` }; const response = await fetch(accountMode ? '/api/rentals/client-portal' : '/api/public/rental-landlord-portal', { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(accountMode ? { audience: 'landlord', membershipId: accountMembershipId, decisionType, message } : { decisionType, message }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => ({ ...current, decisions: [payload.decision, ...(current.decisions || [])] })); setMessage(''); setNotice('Instruction submitted to the rentals team.') } catch (cause) { setError(cause?.message || 'Unable to submit instruction.') } finally { setSaving(false) } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f5f7fa]"><span className="inline-flex items-center gap-2 text-sm text-[#667085]"><Loader2 className="animate-spin" size={18} />Loading your portal…</span></main>
  if (error && !data) return <main className="grid min-h-screen place-items-center bg-[#f5f7fa] p-6"><section className="max-w-md rounded-[20px] border border-[#f2c6c6] bg-white p-6 shadow-sm"><h1 className="text-xl font-semibold">Landlord portal unavailable</h1><p className="mt-2 text-sm leading-6 text-[#667085]">{error}</p></section></main>
  const property = data?.property || {}; const mandate = data?.mandate || {}; const units = data?.units || []; const documents = data?.documents || []; const decisions = data?.decisions || []
  const decisionHistory = <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{decisions.length ? decisions.map((decision) => <article key={decision.id} className="rounded-[16px] border border-[#e3eaf2] bg-[#fbfdff] p-4"><div className="flex justify-between gap-3"><strong>{label(decision.decision_type)}</strong><span className="rounded-full bg-[#edf5ff] px-2.5 py-1 text-xs font-semibold text-[#45627d]">{label(decision.status)}</span></div><p className="mt-3 text-sm leading-6 text-[#52657b]">{decision.message}</p></article>) : <p className="rounded-[16px] border border-dashed border-[#d8e4f0] p-6 text-sm text-[#667085]">No instructions submitted yet.</p>}</div>
  const overview = <div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(340px,.9fr)]"><Card icon={Building2} eyebrow="Property summary" title="Management at a glance"><dl className="mt-6 grid gap-3 sm:grid-cols-2">{[['Property type', label(property.property_type)], ['Property status', label(property.status)], ['Mandate', label(mandate.mandate_status || 'Not available')], ['Authority', label(mandate.authority_status || 'Not available')], ['Units', units.length], ['Mandate expiry', date(mandate.ends_on)]].map(([term, value]) => <div key={term} className="rounded-[14px] border border-[#e3eaf2] bg-[#fbfdff] p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-[#7b8491]">{term}</dt><dd className="mt-1 text-sm font-semibold text-[#203247]">{value}</dd></div>)}</dl></Card><Card icon={Wrench} eyebrow="Owner action" title="Send an instruction"><InstructionForm {...{ decisionType, setDecisionType, message, setMessage, submit, saving }} /></Card></div>
  const properties = <Card icon={Building2} eyebrow="Property" title="Units and occupancy"><p className="mt-4 text-sm text-[#667085]">{accountMode ? 'Your signed-in account access is scoped to' : 'This access link is scoped to'} {property.name || 'this property'}.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{units.length ? units.map((unit) => <article key={unit.id} className="rounded-[16px] border border-[#e3eaf2] bg-[#fbfdff] p-4"><div className="flex items-start justify-between gap-3"><strong>{unit.unit_label || 'Unit'}</strong><span className="rounded-full bg-[#edf5ff] px-2.5 py-1 text-xs font-semibold text-[#45627d]">{label(unit.status)}</span></div><p className="mt-3 text-sm text-[#52657b]">{unit.bedrooms} beds · {unit.bathrooms} baths</p><p className="mt-1 text-sm font-semibold text-[#203247]">Target rent {currency(unit.target_rent)}</p></article>) : <p className="rounded-[16px] border border-dashed border-[#d8e4f0] p-6 text-sm text-[#667085]">No units have been captured for this property.</p>}</div></Card>
  const approvals = <div className="grid gap-5 xl:grid-cols-[minmax(340px,.75fr)_minmax(0,1.25fr)]"><Card icon={Wrench} eyebrow="Approvals" title="Send an instruction"><InstructionForm {...{ decisionType, setDecisionType, message, setMessage, submit, saving }} /></Card><Card icon={CalendarClock} eyebrow="Activity" title="Instruction history">{decisionHistory}</Card></div>
  const docs = <Card icon={FileText} eyebrow="Mandate & documents" title="Property records"><dl className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Mandate status', label(mandate.mandate_status || 'Not available')], ['Authority', label(mandate.authority_status || 'Not available')], ['Starts', date(mandate.starts_on)], ['Ends', date(mandate.ends_on)]].map(([term, value]) => <div key={term} className="rounded-[14px] border border-[#e3eaf2] bg-[#fbfdff] p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-[#7b8491]">{term}</dt><dd className="mt-1 text-sm font-semibold text-[#203247]">{value}</dd></div>)}</dl><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{documents.length ? documents.map((document) => <article key={document.id} className="rounded-[16px] border border-[#e3eaf2] bg-[#fbfdff] p-4"><FileText size={18} className="text-[#1769d1]" /><p className="mt-4 font-semibold text-[#203247]">{document.document_label || 'Property document'}</p><p className="mt-1 text-xs text-[#667085]">{label(document.document_category || 'Supporting document')}</p></article>) : <p className="rounded-[16px] border border-dashed border-[#d8e4f0] p-6 text-sm text-[#667085]">No property documents are available in this portal yet.</p>}</div></Card>
  const support = <Card icon={CalendarClock} eyebrow="Support & activity" title="Recent instructions">{decisionHistory}</Card>
  const content = activeKey === 'properties' ? properties : activeKey === 'approvals' ? approvals : activeKey === 'documents' ? docs : activeKey === 'support' ? support : overview
  return <RentalClientPortalShell role="landlord" activeKey={activeKey} property={property} subtitle="Property oversight, approvals and instructions in one secure workspace.">{content}{error ? <p className="mt-5 rounded-xl border border-[#f2c6c6] bg-[#fff7f7] p-3 text-sm text-[#9f3131]">{error}</p> : null}{notice ? <p className="mt-5 rounded-xl border border-[#bee3ce] bg-[#effaf3] p-3 text-sm text-[#177349]">{notice}</p> : null}</RentalClientPortalShell>
}
