import { CalendarClock, Download, FileText, Home, Loader2, Send, Wrench } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import RentalClientPortalShell from '../../components/rentals/RentalClientPortalShell'
import TenantPortalHome from '../../components/rentals/TenantPortalHome'
import TenantMaintenancePage from '../../components/rentals/TenantMaintenancePage'
import TenantInspectionsPage from '../../components/rentals/TenantInspectionsPage'
import TenantDocumentsPage from '../../components/rentals/TenantDocumentsPage'
import TenantLeasePage from '../../components/rentals/TenantLeasePage'
import TenantPaymentsPage from '../../components/rentals/TenantPaymentsPage'
import { buildDefaultProspectDemoConfig, resolveProspectDemoConfig } from '../../lib/prospectDemoConfig'
import { supabase } from '../../lib/supabaseClient'

const label = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (character) => character.toUpperCase())
const currency = (value) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 }).format(Number(value)) : 'Not available'
const date = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Not available'

function Card({ icon: Icon, eyebrow, title, children }) { return <section className="rounded-[20px] border border-[#dfe7f0] bg-white p-5 shadow-[0_12px_30px_rgba(15,23,42,.05)] sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[12px] bg-[#edf5ff] text-[#1769d1]"><Icon size={19} /></span><div><p className="text-[0.7rem] font-semibold uppercase tracking-[.13em] text-[#7b8491]">{eyebrow}</p><h2 className="text-xl font-semibold tracking-[-.035em]">{title}</h2></div></div>{children}</section> }
function RequestForm({ requestType, setRequestType, message, setMessage, submit, saving, support = false }) { return <form onSubmit={submit} className="mt-5 grid gap-4"><label className="text-sm font-semibold text-[#344054]">Request type<select value={requestType} onChange={(event) => setRequestType(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dbe5ef] bg-white px-3 py-2.5 font-normal text-[#203247]"><option value="maintenance">Maintenance</option><option value="access">Access</option><option value="general">General</option></select></label><label className="text-sm font-semibold text-[#344054]">{support ? 'How can we assist?' : 'Tell us what you need'}<textarea required minLength="10" maxLength="4000" rows={4} value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dbe5ef] px-3 py-2.5 font-normal text-[#203247]" placeholder={support ? 'Ask about your renewal, notice process or tenancy.' : 'Describe what you need help with.'} /></label>{support ? <p className="text-xs leading-5 text-[#667085]">A message here starts a conversation with the rentals team. It does not replace any formal written notice required under your lease.</p> : null}<button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#10213a] px-4 text-sm font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="animate-spin" size={16} /> : <Send size={16} />}Send request</button></form> }

export default function RentalTenantPortalPage({ accountMembershipId = '', demo = false }) {
  const { token = '' } = useParams(); const [searchParams] = useSearchParams(); const activeKey = searchParams.get('section') || 'overview'
  const navigate = useNavigate()
  const accountMode = Boolean(accountMembershipId)
  const [data, setData] = useState(null); const [branding, setBranding] = useState(() => buildDefaultProspectDemoConfig(token)); const [requestType, setRequestType] = useState('maintenance'); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const accountHeaders = useCallback(async () => { if (!supabase) throw new Error('Client account access is not configured.'); const { data } = await supabase.auth.getSession(); if (!data?.session?.access_token) throw new Error('Your session has expired. Please sign in again.'); return { Authorization: `Bearer ${data.session.access_token}` } }, [])
  const load = useCallback(async () => { try { setLoading(true); if (demo) { const config = await resolveProspectDemoConfig(token); setBranding({ ...config, samplePropertyImageUrl: config.samplePropertyImageUrl || (token === 'only-realty' ? '/brand/harbour-heights-apartment-14.png' : '') }); setData({ tenancy: { tenantName: 'Jordan Taylor', status: 'active' }, lease: { status: 'active', startsOn: '2026-08-01', endsOn: '2027-07-31', occupationDate: '2026-08-01', monthlyRent: 18500, depositAmount: 18500, leaseTermMonths: 12 }, property: { name: 'Harbour Heights', unitLabel: 'Apartment 14', addressLine1: '12 Ocean View Drive', suburb: 'Sea Point', city: 'Cape Town' }, payment: { status: 'paid', amount: 18500, paidOn: '2026-09-01', nextAmount: 18500, nextDueOn: '2026-10-01' }, attention: [{ id: 'inspection-1', type: 'inspection', title: 'Incoming inspection', date: '2026-09-24', time: '10:00', detail: 'An inspection of your home is scheduled.' }], events: [{ id: 'maintenance-visit', type: 'Maintenance visit', date: '2026-09-18', time: '09:00 – 11:00', detail: 'Leaking kitchen tap' }, { id: 'inspection', type: 'incoming inspection', date: '2026-09-24', time: '10:00', detail: 'Confirm access to your home' }, { id: 'rent-due', type: 'Rent due', date: '2026-10-01', detail: 'R18 500' }], activity: [{ id: 'rent-paid', type: 'Rent payment received', detail: 'R18 500. Thank you!', occurredAt: '2026-09-01T10:24:00' }, { id: 'maintenance-update', type: 'Maintenance request updated', detail: 'Contractor scheduled for 18 Sep.', occurredAt: '2026-09-16T14:03:00' }, { id: 'message', type: 'Message from Only Realty', detail: 'We’ve confirmed your inspection time.', occurredAt: '2026-09-15T11:26:00' }], requests: [{ id: 'maintenance-1', request_type: 'maintenance', status: 'scheduled', message: 'Leaking kitchen tap', submitted_at: '2026-09-15T09:30:00' }], documents: [] }); return } const headers = accountMode ? await accountHeaders() : { Authorization: `Bearer ${token}` }; const response = await fetch(accountMode ? `/api/rentals/client-portal?audience=tenant&membershipId=${encodeURIComponent(accountMembershipId)}` : '/api/public/rental-tenant-portal', { headers }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload) } catch (cause) { setError(cause?.message || 'Unable to open tenant portal.') } finally { setLoading(false) } }, [accountHeaders, accountMembershipId, accountMode, demo, token])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (activeKey === 'support') setRequestType('general') }, [activeKey])
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); setNotice(''); if (demo) { setData((current) => ({ ...current, requests: [{ id: `demo-${Date.now()}`, request_type: requestType, status: 'submitted', message }, ...(current.requests || [])] })); setMessage(''); setNotice('Demo request recorded locally — no client data was changed.'); return } const headers = accountMode ? await accountHeaders() : { Authorization: `Bearer ${token}` }; const response = await fetch(accountMode ? '/api/rentals/client-portal' : '/api/public/rental-tenant-portal', { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(accountMode ? { audience: 'tenant', membershipId: accountMembershipId, requestType, message } : { requestType, message }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => ({ ...current, requests: [payload.request, ...(current.requests || [])] })); setMessage(''); setNotice('Request submitted to the rentals team.') } catch (cause) { setError(cause?.message || 'Unable to submit request.') } finally { setSaving(false) } }
  const submitMaintenance = async (maintenance) => { try { setSaving(true); setError(''); setNotice(''); if (demo) { const request = { id: `demo-maintenance-${Date.now()}`, category: maintenance.category, priority: maintenance.priority, description: `${maintenance.title}\n\n${maintenance.description}`, tenant_area: maintenance.area, tenant_access_preference: maintenance.accessPreference, tenant_availability: maintenance.availability, status: 'submitted', reported_at: new Date().toISOString(), assignment: null, events: [{ id: 'submitted', event_type: 'submitted', tenant_visible_status: 'Submitted', tenant_message: 'Your rental team has received your request.', created_at: new Date().toISOString() }] }; setData((current) => ({ ...current, maintenanceRequests: [request, ...(current.maintenanceRequests || [])] })); setNotice('Demo maintenance request recorded locally — no client data was changed.'); return } if (accountMode) throw new Error('Maintenance reporting for signed-in tenant accounts will be enabled with the portal maintenance migration.'); const response = await fetch('/api/public/rental-tenant-portal', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ requestType: 'maintenance', maintenance }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => ({ ...current, maintenanceRequests: [payload.maintenanceRequest, ...(current.maintenanceRequests || [])] })); setNotice('Your maintenance request has been sent to the rentals team.') } catch (cause) { setError(cause?.message || 'Unable to submit maintenance request.') } finally { setSaving(false) } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f5f7fa]"><span className="inline-flex items-center gap-2 text-sm text-[#667085]"><Loader2 className="animate-spin" size={18} />Loading your portal…</span></main>
  if (error && !data) return <main className="grid min-h-screen place-items-center bg-[#f5f7fa] p-6"><section className="max-w-md rounded-[20px] border border-[#f2c6c6] bg-white p-6 shadow-sm"><h1 className="text-xl font-semibold">Tenant portal unavailable</h1><p className="mt-2 text-sm leading-6 text-[#667085]">{error}</p></section></main>
  const tenancy = data?.tenancy || {}; const lease = data?.lease || {}; const property = data?.property || {}; const requests = data?.requests || []; const documents = data?.documents || []
  const leaseFacts = [['Tenancy', label(tenancy.status)], ['Lease', label(lease.status)], ['Starts', date(lease.startsOn)], ['Ends', date(lease.endsOn)], ['Occupation', date(lease.occupationDate)], ['Monthly rent', currency(lease.monthlyRent)], ['Deposit', currency(lease.depositAmount)], ['Lease term', lease.leaseTermMonths ? `${lease.leaseTermMonths} months` : 'Not available']]
  const requestHistory = <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{requests.length ? requests.map((request) => <article key={request.id} className="rounded-[16px] border border-[#e3eaf2] bg-[#fbfdff] p-4"><div className="flex justify-between gap-3"><strong>{label(request.request_type)}</strong><span className="rounded-full bg-[#edf5ff] px-2.5 py-1 text-xs font-semibold text-[#45627d]">{label(request.status)}</span></div><p className="mt-3 text-sm leading-6 text-[#52657b]">{request.message}</p></article>) : <p className="rounded-[16px] border border-dashed border-[#d8e4f0] p-6 text-sm text-[#667085]">No requests submitted yet.</p>}</div>
  const overview = <div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(340px,.9fr)]"><Card icon={Home} eyebrow="Your home" title={`${property.name || 'Your tenancy'}${property.unitLabel ? ` · ${property.unitLabel}` : ''}`}><p className="mt-4 text-sm text-[#667085]">{[property.addressLine1, property.suburb, property.city].filter(Boolean).join(', ') || 'Property address will appear here.'}</p><dl className="mt-5 grid gap-3 sm:grid-cols-2">{leaseFacts.slice(0, 6).map(([term, value]) => <div key={term} className="rounded-[14px] border border-[#e3eaf2] bg-[#fbfdff] p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-[#7b8491]">{term}</dt><dd className="mt-1 text-sm font-semibold text-[#203247]">{value}</dd></div>)}</dl></Card><Card icon={Wrench} eyebrow="Next step" title="How can we help?"><RequestForm {...{ requestType, setRequestType, message, setMessage, submit, saving }} /></Card></div>
  const home = <TenantLeasePage data={{ ...data, tenancy, lease, documents }} branding={demo ? branding : {}} onNavigate={(section) => navigate(`?section=${section}`)} demo={demo} />
  const maintenance = <TenantMaintenancePage data={{ ...data, branding: demo ? branding : {}, maintenanceRequests: data?.maintenanceRequests || (demo ? [{ id: 'maintenance-1', category: 'plumbing', priority: 'routine', description: 'Leaking kitchen tap\n\nThe kitchen tap is leaking from the base when turned on.', tenant_area: 'Kitchen', status: 'assigned', reported_at: '2026-09-15T09:30:00', assignment: { assignee_name: 'AquaFix Plumbing', status: 'assigned' }, events: [{ id: 'event-1', event_type: 'submitted', tenant_visible_status: 'Submitted', tenant_message: 'Your rental team has received your request.', created_at: '2026-09-15T09:30:00' }, { id: 'event-2', event_type: 'status_updated', tenant_visible_status: 'Contractor assigned', tenant_message: 'AquaFix Plumbing has been assigned.', created_at: '2026-09-16T14:03:00' }] }] : []) }} onSubmit={submitMaintenance} onNavigate={(section) => navigate(`?section=${section}`)} saving={saving} />
  const documentsPanel = <TenantDocumentsPage data={{ ...data, branding: demo ? branding : {}, documents: demo ? [{ id: 'lease', name: 'Signed lease agreement.pdf', category: 'lease', createdAt: '2026-08-01', sharedBy: 'Only Realty', status: 'signed', important: true, version: 'Version 2 · Final', fileType: 'PDF', sharedThisMonth: true }, { id: 'invoice', name: 'September rent invoice.pdf', category: 'payments', createdAt: '2026-09-01', sharedBy: 'Only Realty', status: 'current', important: true, version: 'Current invoice', fileType: 'PDF', sharedThisMonth: true }, { id: 'inspection-report', name: 'Move-in inspection report.pdf', category: 'inspections', createdAt: '2026-08-01', sharedBy: 'Sarah Mokoena', status: 'signed', important: true, version: 'Final report', fileType: 'PDF' }, { id: 'house-rules', name: 'House rules.pdf', category: 'lease', createdAt: '2026-07-28', sharedBy: 'Only Realty', status: 'current', version: 'Current version', fileType: 'PDF' }, { id: 'proof', name: 'FNB proof of payment – June.pdf', category: 'payments', createdAt: '2026-06-01', sharedBy: 'You', status: 'verified', version: 'Verified upload', fileType: 'PDF' }] : documents.map((document) => ({ id: document.id, name: document.label || 'Lease document', category: 'lease', createdAt: document.createdAt, sharedBy: 'Rental team', status: 'current', important: true, link: document.link, fileType: 'Document' })), documentAttention: demo ? { title: 'Proof of residence required', detail: 'Please upload a recent utility bill or bank statement.', dueOn: '2026-09-20', requirements: 'Upload a full-page utility bill or bank statement issued within the requested period.' } : null }} onNavigate={(section) => navigate(`?section=${section}`)} demo={demo} />
  const support = <div className="grid gap-5 xl:grid-cols-[minmax(340px,.75fr)_minmax(0,1.25fr)]"><Card icon={CalendarClock} eyebrow="Lease & renewal" title="Renewal or notice"><RequestForm requestType="general" setRequestType={setRequestType} message={message} setMessage={setMessage} submit={submit} saving={saving} support /></Card><Card icon={FileText} eyebrow="Activity" title="Your recent requests">{requestHistory}</Card></div>
  const payments = <TenantPaymentsPage data={{ ...data, tenancy, lease, property, ...(demo ? { balance: 0, paymentReference: 'HT14-JTAYLOR', paymentHistory: [{ id: 'payment-sep', invoice: 'INV-0926', amount: 18500, dueDate: '2026-09-01', paidOn: '2026-09-01', status: 'paid' }, { id: 'payment-aug', invoice: 'INV-0826', amount: 18500, dueDate: '2026-08-01', paidOn: '2026-08-01', status: 'paid' }, { id: 'payment-jul', invoice: 'INV-0726', amount: 18500, dueDate: '2026-07-01', paidOn: '2026-07-02', status: 'paid' }, { id: 'payment-jun', invoice: 'INV-0626', amount: 18500, dueDate: '2026-06-01', status: 'proof_submitted', fileName: 'FNB-payment-June.pdf' }, { id: 'payment-may', invoice: 'INV-0526', amount: 18500, dueDate: '2026-05-01', paidOn: '2026-05-01', status: 'paid' }] } : {}) }} branding={demo ? branding : {}} demo={demo} onNavigate={(section) => navigate(`?section=${section}`)} />
  const inspections = <TenantInspectionsPage data={{ ...data, branding: demo ? branding : {}, inspections: data?.inspections || (demo ? [{ id: 'inspection-routine', title: 'Routine property inspection', startsAt: '2026-09-24T10:00:00', time: '10:00 – 11:00', duration: '30–45 minutes', inspector: 'Sarah Mokoena · Only Realty', status: 'awaiting_tenant_confirmation', summary: 'An inspection of your home is scheduled.' }, { id: 'inspection-move-in', title: 'Move-in inspection', startsAt: '2026-08-01T10:00:00', inspector: 'Jordan Taylor & Sarah Mokoena', status: 'completed', reportAvailable: true, summary: 'Overall condition: Good. Seven rooms were inspected and five items were recorded.' }, { id: 'inspection-incoming', title: 'Incoming condition inspection', startsAt: '2026-07-31T10:00:00', inspector: 'Sarah Mokoena', status: 'report_available', reportAvailable: true, summary: 'Your signed incoming condition report is available.' }, { id: 'inspection-walkthrough', title: 'Pre-occupation walkthrough', startsAt: '2026-07-28T10:00:00', inspector: 'Rental team', status: 'completed', reportAvailable: true, summary: 'Property readiness and handover preparation were completed.' }] : []) }} onNavigate={(section) => navigate(`?section=${section}`)} demo={demo} />
  const messages = <Card icon={CalendarClock} eyebrow="Messages" title="Message your rental team"><RequestForm requestType="general" setRequestType={setRequestType} message={message} setMessage={setMessage} submit={submit} saving={saving} support /></Card>
  const content = activeKey === 'payments' ? payments : activeKey === 'maintenance' ? maintenance : activeKey === 'inspections' ? inspections : activeKey === 'documents' ? documentsPanel : activeKey === 'messages' ? messages : activeKey === 'lease' ? home : activeKey === 'support' ? support : <TenantPortalHome data={{ ...data, tenancy, lease, property, requests, documents }} branding={demo ? branding : {}} onNavigate={(section) => navigate(`?section=${section}`)} />
  return <RentalClientPortalShell role="tenant" activeKey={activeKey} branding={demo ? branding : {}} showPropertyHero={activeKey !== 'overview'} property={{ name: property.name || 'Your tenancy', address_line_1: property.addressLine1, suburb: property.suburb, city: property.city }} subtitle={tenancy.tenantName ? `Welcome back, ${tenancy.tenantName}` : 'Your home, lease and requests in one place.'}>{content}{error ? <p className="mt-5 rounded-xl border border-[#f2c6c6] bg-[#fff7f7] p-3 text-sm text-[#9f3131]">{error}</p> : null}{notice ? <p className="mt-5 rounded-xl border border-[#bee3ce] bg-[#effaf3] p-3 text-sm text-[#177349]">{notice}</p> : null}</RentalClientPortalShell>
}
