import { Building2, ChevronRight, Loader2, Plus, Search, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useWorkspace } from '../../context/WorkspaceContext'
import { createRentalProperty, listRentalProperties } from '../../services/rentals/rentalPropertyRepository.js'

const initialForm = { name: '', propertyType: 'house', addressLine1: '', city: '', province: '', postalCode: '' }
const propertyTypes = ['house', 'apartment', 'townhouse', 'duplex', 'studio', 'estate', 'commercial', 'other']
const text = (value) => String(value ?? '').trim()
const title = (value) => text(value).replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
function getScope(context = {}) { const membership = context.currentMembership || context.organisationMembership || {}; return { organisationId: text(context.workspace?.id || membership.organisation_id || membership.organisationId), branchId: text(membership.branch_id || membership.branchId), userId: text(context.profile?.id || context.userId) } }
function statusTone(value) { return value === 'active' ? 'border-[#cfe8dc] bg-[#effaf3] text-[#26724c]' : 'border-[#dbe6f1] bg-[#f8fbff] text-[#4d6782]' }

function CreatePropertyDrawer({ open, onClose, form, update, submit, creating }) {
  if (!open) return null
  return <div className="fixed inset-0 z-50 bg-[#102236]/35 p-4 sm:flex sm:justify-end"><form onSubmit={submit} className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#6f8398]">Portfolio</p><h2 className="mt-1 text-xl font-semibold text-[#102236]">Add managed property</h2></div><button type="button" className="grid h-9 w-9 place-items-center rounded-xl border border-[#dbe6f1] text-[#60758b]" onClick={onClose}><X size={17} /></button></div><p className="mt-2 text-sm text-[#60758b]">Keep the managed property separate from its rental listings and vacancies.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="form-field sm:col-span-2"><span>Property name</span><input required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. The View Apartments" /></label><label className="form-field"><span>Property type</span><select value={form.propertyType} onChange={(event) => update('propertyType', event.target.value)}>{propertyTypes.map((type) => <option key={type} value={type}>{title(type)}</option>)}</select></label><label className="form-field"><span>City</span><input required value={form.city} onChange={(event) => update('city', event.target.value)} /></label><label className="form-field sm:col-span-2"><span>Address</span><input required value={form.addressLine1} onChange={(event) => update('addressLine1', event.target.value)} /></label><label className="form-field"><span>Province</span><input value={form.province} onChange={(event) => update('province', event.target.value)} /></label><label className="form-field"><span>Postal code</span><input value={form.postalCode} onChange={(event) => update('postalCode', event.target.value)} /></label></div><button disabled={creating} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-[12px] bg-[#0f2743] px-4 text-sm font-semibold text-white disabled:opacity-60">{creating ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}Create property</button></form></div>
}

export default function RentalPropertiesPage() {
  const workspace = useWorkspace(); const scope = useMemo(() => getScope(workspace), [workspace]); const [properties, setProperties] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [drawer, setDrawer] = useState(false); const [form, setForm] = useState(initialForm); const [creating, setCreating] = useState(false)
  const load = useCallback(async () => { if (!scope.organisationId) { setProperties([]); setLoading(false); return } try { setLoading(true); setError(''); setProperties(await listRentalProperties(scope)) } catch (cause) { setError(cause?.message || 'Unable to load rental properties.'); setProperties([]) } finally { setLoading(false) } }, [scope])
  useEffect(() => { void load() }, [load])
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event) => { event.preventDefault(); try { setCreating(true); setError(''); await createRentalProperty({ ...scope, ...form, assignedManagerId: scope.userId, createdBy: scope.userId }); setForm(initialForm); setDrawer(false); await load() } catch (cause) { setError(cause?.message || 'Unable to create rental property.') } finally { setCreating(false) } }
  const rows = useMemo(() => properties.filter((property) => [property.name, property.propertyType, property.address?.line1, property.address?.city, property.status].join(' ').toLowerCase().includes(query.toLowerCase())), [properties, query])
  return <main className="mx-auto w-full max-w-[1600px] px-3 py-2 sm:px-5 lg:px-7"><section className="space-y-4 pb-6"><div className="flex gap-2"><label className="flex h-10 min-w-0 flex-1 items-center gap-2 rounded-[12px] border border-[#dbe4ee] bg-white px-3 sm:max-w-md"><Search size={15} className="text-[#7b8ca2]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 border-0 bg-transparent p-0 text-sm outline-none" placeholder="Search properties" /></label><button type="button" onClick={() => setDrawer(true)} className="inline-flex h-10 shrink-0 items-center gap-2 rounded-[12px] bg-[#0f2743] px-3 text-sm font-semibold text-white"><Plus size={16} />Add property</button></div>{error ? <p className="rounded-xl border border-[#f2c6c6] bg-[#fff7f7] p-3 text-sm text-[#9f3131]">{error}</p> : null}{loading ? <div className="grid min-h-56 place-items-center text-sm text-[#60758b]"><span className="inline-flex items-center gap-2"><Loader2 size={16} className="animate-spin" />Loading properties…</span></div> : rows.length ? <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map((property) => <Link key={property.id} to={`/agent/rentals/portfolio/properties/${property.id}`} className="group flex min-h-[190px] flex-col rounded-[18px] border border-[#dfe7f0] bg-white p-4 shadow-[0_10px_24px_rgba(15,23,42,.05)] transition hover:-translate-y-0.5 hover:border-[#b9cee4]"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf5ff] text-[#1769d1]"><Building2 size={20} /></span><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${statusTone(property.status)}`}>{title(property.status || 'draft')}</span></div><div className="mt-4"><p className="text-base font-semibold text-[#142132]">{property.name}</p><p className="mt-1 text-sm text-[#60758b]">{property.address?.line1 || 'Address pending'}{property.address?.city ? ` · ${property.address.city}` : ''}</p></div><div className="mt-4 flex items-center justify-between border-t border-[#edf2f7] pt-3 text-xs font-semibold text-[#1769d1]"><span>{title(property.propertyType || 'property')}</span><ChevronRight size={15} /></div></Link>)}</section> : <section className="rounded-[18px] border border-dashed border-[#d8e4f0] bg-white p-10 text-center"><Building2 className="mx-auto text-[#7b8ca2]" size={28} /><p className="mt-3 font-semibold text-[#20364d]">No managed properties in this view</p><p className="mt-1 text-sm text-[#60758b]">Add a property before creating units, mandates, or vacancies.</p><button type="button" onClick={() => setDrawer(true)} className="mt-4 inline-flex h-10 items-center gap-2 rounded-[12px] bg-[#0f2743] px-3 text-sm font-semibold text-white"><Plus size={16} />Add property</button></section>}</section><CreatePropertyDrawer open={drawer} onClose={() => setDrawer(false)} form={form} update={update} submit={submit} creating={creating} /></main>
}
