import { ArrowLeft, BriefcaseBusiness, Loader2, Plus } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useWorkspace } from '../../context/WorkspaceContext'
import { listRentalProperties } from '../../services/rentals/rentalPropertyRepository.js'
import { assignRentalPropertyToPortfolio, getRentalPortfolio, listRentalPortfolios } from '../../services/rentals/rentalPortfolioRepository.js'

const text = (value) => String(value ?? '').trim()
function getScope(context = {}) { const membership = context.currentMembership || context.organisationMembership || {}; return { organisationId: text(context.workspace?.id || membership.organisation_id || membership.organisationId), branchId: text(membership.branch_id || membership.branchId), userId: text(context.profile?.id || context.userId) } }

export function RentalPortfolioDetailPage() {
  const { portfolioId } = useParams(); const workspace = useWorkspace(); const scope = useMemo(() => getScope(workspace), [workspace])
  const [portfolio, setPortfolio] = useState(null); const [properties, setProperties] = useState([]); const [summary, setSummary] = useState(null); const [propertyId, setPropertyId] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!portfolioId || !scope.organisationId) return; try { setLoading(true); setError(''); const [current, allProperties, summaries] = await Promise.all([getRentalPortfolio(portfolioId), listRentalProperties(scope), listRentalPortfolios(scope)]); setPortfolio(current); setProperties(allProperties); setSummary(summaries.find((item) => item.id === portfolioId) || null) } catch (cause) { setError(cause?.message || 'Unable to load rental portfolio.') } finally { setLoading(false) } }, [portfolioId, scope])
  useEffect(() => { void load() }, [load])
  const submit = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); await assignRentalPropertyToPortfolio({ portfolioId, propertyId, organisationId: scope.organisationId, assignedBy: scope.userId }); setPropertyId(''); await load() } catch (cause) { setError(cause?.message || 'Unable to assign property.') } finally { setSaving(false) } }
  return <main className="mx-auto max-w-4xl space-y-6 px-4 py-6"><Link to="/agent/rentals/portfolio" className="inline-flex items-center gap-1 text-sm font-medium text-sky-700"><ArrowLeft className="h-4 w-4"/>Portfolios</Link>{loading ? <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin"/></div> : error ? <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p> : !portfolio ? <p className="rounded-lg border p-5 text-sm text-slate-600">Portfolio not found in this workspace.</p> : <><section className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><BriefcaseBusiness className="mt-1 h-6 w-6 text-sky-700"/><div><p className="text-xs font-semibold uppercase text-sky-700">{portfolio.status}</p><h1 className="text-2xl font-bold text-slate-900">{portfolio.name}</h1>{portfolio.description && <p className="mt-2 text-slate-600">{portfolio.description}</p>}<p className="mt-4 text-sm font-medium text-slate-700">{summary?.propertyCount || 0} properties · {summary?.unitCount || 0} units</p></div></div></section><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Assign a property</h2><p className="mt-1 text-sm text-slate-600">Assigning a property reassigns it from any other Rental portfolio in this organisation.</p><form onSubmit={submit} className="mt-4 flex flex-wrap gap-2"><select required value={propertyId} onChange={(event) => setPropertyId(event.target.value)} className="min-w-64 rounded-lg border px-3 py-2 text-sm"><option value="">Choose managed property</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.name} — {property.address.city}</option>)}</select><button disabled={!propertyId || saving} className="inline-flex items-center gap-1 rounded-lg bg-sky-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin"/> : <Plus className="h-4 w-4"/>}Assign</button></form></section></>}</main>
}
