import { createElement } from 'react'
import { BarChart3, CalendarDays, ChevronRight, Plus, RefreshCw, Users } from 'lucide-react'
import './rental-listing-overview.css'

const money = (value) => value === null || value === undefined || value === '' ? 'Not captured' : `R ${Number(value).toLocaleString('en-ZA')}`
const date = (value) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleDateString('en-ZA') : 'Not captured'
const panel = 'rental-overview-panel'

function Header({ title, action, onClick }) {
  return <div className="rental-overview-panel-heading"><h2>{title}</h2>{action ? <button type="button" data-rental-control="overview-link" className="rental-overview-link" onClick={onClick}>{action}<ChevronRight size={14} /></button> : null}</div>
}

export default function RentalListingOverview({ detail, snapshot, agentPanel, onOpenTab, onOpenEdit, onRefresh, onNavigate, onAddLead, onScheduleViewing }) {
  const row = detail.row
  const loaded = Boolean(snapshot)
  const value = (number) => number == null ? '—' : number
  const progress = snapshot?.documentProgress
  const gallery = (detail.listing.listingMedia || detail.listing.galleryImages || []).filter((image) => String(image.media_type || image.mediaType || 'image').toLowerCase() === 'image')
  const imageCount = gallery.length || (row.imageUrl ? 1 : 0)
  const metrics = [
    { label: 'Leads', value: value(snapshot?.leadCount), meta: loaded ? snapshot.leadCount == null ? 'Lead data unavailable' : `${snapshot.newLeadCount} new this week` : 'Loading linked leads…', icon: Users },
    { label: 'Viewings', value: value(snapshot?.viewingCount), meta: loaded ? snapshot.viewingCount == null ? 'Viewing data unavailable' : `${snapshot.upcoming.length} upcoming` : 'Loading viewings…', icon: CalendarDays },
    { label: 'Days on market', value: value(snapshot?.daysOnMarket), meta: snapshot?.daysOnMarket == null ? 'Listing date unavailable' : 'Current listing period', icon: BarChart3 },
  ]
  return <section className="rental-overview-stack">
    <section className={panel}>
      <div className="rental-overview-metrics">{metrics.map(({ label, value: metric, meta, icon: Icon }) => <article key={label}><div><span>{label}</span><span className="rental-overview-metric-icon">{createElement(Icon, { size: 17, 'aria-hidden': true })}</span></div><strong>{metric}</strong><p>{meta}</p></article>)}</div>
      <div className="rental-overview-refresh"><span>{!loaded ? 'Loading overview…' : snapshot.issues.length ? `Could not load: ${snapshot.issues.join(', ')}` : 'Overview up to date'}</span><button type="button" data-rental-control="overview-refresh" onClick={onRefresh}><RefreshCw size={15} />Refresh</button></div>
    </section>
    <div className="rental-overview-activity-grid">
      <article className={panel}><Header title="Latest Tenant Activity" action="View all leads" onClick={() => onOpenTab('leads')} /><div className="rental-overview-feed">{snapshot?.leads.length ? snapshot.leads.slice(0, 3).map((lead) => <button data-rental-control="overview-lead" type="button" key={lead.id} onClick={() => onNavigate(`/agent/rentals/pipeline/leads/${encodeURIComponent(lead.id)}`)}><strong>{lead.name}</strong><span>{lead.stageLabel}</span></button>) : <p>{!loaded ? 'Loading tenant leads…' : snapshot.issues.includes('Leads') ? 'Tenant leads could not be loaded.' : 'No tenant leads yet.'}</p>}</div><button type="button" className="rental-overview-action" data-rental-control="overview-add-lead" onClick={onAddLead}><Plus size={15} />Add Tenant Lead</button></article>
      <article className={panel}><Header title="Upcoming Viewings" /><p className="rental-overview-caption">Open a viewing to see tenant and agent details.</p><div className="rental-overview-feed">{snapshot?.upcoming.length ? snapshot.upcoming.slice(0, 3).map((viewing) => <button type="button" data-rental-control="overview-viewing" key={viewing.id} onClick={onScheduleViewing}><strong>{viewing.tenantName || 'Tenant viewing'}</strong><span>{new Date(viewing.startsAt).toLocaleString('en-ZA')}</span></button>) : <p>{!loaded ? 'Loading viewings…' : snapshot.issues.includes('Viewings & activity') ? 'Viewings could not be loaded.' : 'No upcoming viewings.'}</p>}</div><button type="button" className="rental-overview-action" data-rental-control="overview-schedule" onClick={onScheduleViewing}><CalendarDays size={15} />Schedule Viewing</button></article>
    </div>
    <div className="rental-overview-columns">
      <article className={`${panel} rental-overview-tenant`}><Header title="Tenant" /><p className="rental-overview-caption">Tenant profile and tenancy status.</p>{snapshot?.tenant ? <><div className="rental-overview-person"><span>{snapshot.tenant.name.split(' ').slice(0, 2).map((part) => part[0]).join('')}</span><div><strong>{snapshot.tenant.name}</strong><p>{snapshot.tenant.email}</p><p>{snapshot.tenant.phone}</p></div></div><dl><dt>Tenancy</dt><dd>{snapshot.tenant.status.replaceAll('_', ' ')}</dd><dt>Applications</dt><dd>{snapshot.applications.length + (snapshot.legacyApplications?.length || 0)}</dd></dl></> : <div className="rental-overview-tenant-empty"><strong>{snapshot?.issues.includes('Tenant') || snapshot?.issues.includes('Applications') ? 'Tenant details unavailable' : 'No tenant placed'}</strong><p>A tenant profile appears when an approved application has been converted to a tenancy.</p></div>}<div className="rental-overview-owner"><h3>Landlord</h3><strong>{row.landlordName || 'Not captured'}</strong><p>{row.landlordContact || 'No contact captured'}</p><dl><dt>Mandate</dt><dd>{detail.mandateStatusLabel}</dd><dt>Marketing approval</dt><dd>{detail.marketingApprovalStatusLabel}</dd></dl><button type="button" data-rental-control="overview-landlord" className="rental-overview-link" onClick={() => onOpenTab('landlord')}>Open landlord<ChevronRight size={14} /></button></div><button type="button" data-rental-control="overview-tenant" className="rental-overview-action" onClick={() => snapshot?.tenant ? onNavigate(`/agent/rentals/tenancies/${encodeURIComponent(snapshot.tenant.id)}`) : onOpenTab('leads')}>{snapshot?.tenant ? 'Open Tenant' : 'View Tenant Applications'}</button></article>
      <div className="rental-overview-column">{agentPanel}<article className={`${panel} rental-overview-marketing`}><div className="rental-overview-marketing-heading"><Header title="Marketing" action="Open marketing" onClick={() => onOpenTab('marketing')} /></div><div className="rental-overview-marketing-image">{row.imageUrl ? <img src={row.imageUrl} alt={row.title} /> : null}<span>{imageCount} image{imageCount === 1 ? '' : 's'}</span></div><div className="rental-overview-marketing-body"><strong className="rental-overview-price">{money(row.monthlyRent)}</strong><div className="rental-overview-facts">{[`${row.bedrooms || 0} bed`, `${row.bathrooms || 0} bath`, `${row.parkingBays || 0} parking`].map((fact) => <span key={fact}>{fact}</span>)}</div><p>{detail.listing.description || detail.listing.listingPublicationData?.description || 'Add a public property description in Marketing to complete this listing preview.'}</p><div className="rental-overview-listed"><h3>Listed on</h3>{detail.channels.map((channel) => <span key={channel.key}>{channel.label}<small>{channel.status?.replaceAll('_', ' ') || 'Not published'}</small></span>)}</div></div></article></div>
      <div className="rental-overview-column"><article className={panel}><Header title="Document Progress" action="Open documents" onClick={() => onOpenTab('mandate')} />{snapshot?.issues.some((issue) => ['Documents', 'Document requirements'].includes(issue)) ? <p className="rental-overview-caption">Document progress could not be loaded.</p> : progress?.total ? <div className="rental-overview-document-progress"><span role="progressbar" aria-label="Rental document completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percent} style={{ background: `conic-gradient(#177556 ${progress.percent}%, #e5ebf2 ${progress.percent}% 100%)` }}><strong>{progress.percent}%</strong></span><div><strong>{progress.complete} of {progress.total} complete</strong><p>{progress.total - progress.complete} still outstanding</p></div></div> : <p className="rental-overview-caption">{loaded ? 'No confirmed document requirements yet. Check the Documents tab.' : 'Loading document progress…'}</p>}</article><article className={panel}><Header title="Price Position" action="Edit pricing" onClick={() => onOpenEdit('terms')} /><p className="rental-overview-caption">Current monthly rent</p><strong className="rental-overview-price">{money(row.monthlyRent)}</strong><dl><dt>Available from</dt><dd>{date(row.availableFrom)}</dd><dt>Deposit</dt><dd>{money(row.depositAmount)}</dd><dt>Lease term</dt><dd>{row.leasePeriodMonths ? `${row.leasePeriodMonths} months` : 'Not captured'}</dd></dl></article><article className={panel}><Header title="Published" action="Manage" onClick={() => onOpenTab('marketing')} /><dl>{detail.channels.map((channel) => <div key={channel.key}><dt>{channel.label}</dt><dd>{channel.status?.replaceAll('_', ' ') || 'Not published'}</dd></div>)}</dl></article></div>
    </div>
  </section>
}
