import { ArrowLeft, Building2, CheckCircle2, CircleDollarSign, FileText, Landmark, Loader2, ShieldCheck, UsersRound } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, NavLink, useLocation, useParams } from 'react-router-dom'
import TransactionWorkspaceHeader from '../../components/TransactionWorkspaceHeader'
import { useWorkspace } from '../../context/WorkspaceContext'
import { listRentalPropertyOwners } from '../../services/rentals/rentalLandlordMandateRepository.js'
import { listRentalProperties } from '../../services/rentals/rentalPropertyRepository.js'
import { createRentalOwnerActivity, getRentalOwnerProfile, listRentalOwnerActivity, listRentalOwnerApprovals, upsertRentalOwnerProfile } from '../../services/rentals/rentalOwnerWorkspaceRepository.js'

const tabs = [['overview', 'Overview'], ['properties', 'Properties'], ['mandates', 'Mandates'], ['financials', 'Financials'], ['documents', 'Documents'], ['communication', 'Communication'], ['activity', 'Activity']]
const text = (value) => String(value ?? '').trim()
const title = (value) => text(value).replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const scopeOf = (workspace = {}) => { const member = workspace.currentMembership || workspace.organisationMembership || {}; return { organisationId: text(workspace.workspace?.id || member.organisation_id || member.organisationId), userId: text(workspace.profile?.id || workspace.userId) } }
const statusClass = (status) => ['verified', 'active', 'complete', 'approved'].includes(status) ? 'bg-[#e6f8ed] text-[#177349]' : ['incomplete', 'pending', 'not_started', 'not_invited'].includes(status) ? 'bg-[#fff5e4] text-[#a55a00]' : 'bg-[#eef4fb] text-[#45627d]'

function Panel({ title: heading, icon: Icon, children }) { return <section className="rounded-[20px] border border-[#dfe7f0] bg-white p-5 shadow-[0_10px_24px_rgba(15,23,42,.04)] sm:p-6"><h2 className="flex items-center gap-2 text-lg font-semibold text-[#142132]">{Icon ? <Icon size={18} className="text-[#1769d1]" /> : null}{heading}</h2>{children}</section> }

export default function RentalOwnerDetailPage() {
  const workspace = useWorkspace(); const { ownerId } = useParams(); const location = useLocation(); const scope = useMemo(() => scopeOf(workspace), [workspace]); const [owner, setOwner] = useState(null); const [properties, setProperties] = useState([]); const [profile, setProfile] = useState(null); const [approvals, setApprovals] = useState([]); const [activity, setActivity] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const current = tabs.find(([key]) => location.pathname.endsWith(`/${key}`))?.[0] || 'overview'; const basePath = `/agent/rentals/owners/${ownerId}`; const tabPath = (key) => key === 'overview' ? basePath : `${basePath}/${key}`
  const load = useCallback(async () => { if (!scope.organisationId || !ownerId) return; try { setLoading(true); setError(''); const [owners, allProperties, nextProfile] = await Promise.all([listRentalPropertyOwners(scope.organisationId), listRentalProperties({ organisationId: scope.organisationId, limit: 100 }), getRentalOwnerProfile({ organisationId: scope.organisationId, partyId: ownerId })]); const found = owners.find((item) => item.partyId === ownerId) || null; setOwner(found); setProperties(allProperties.filter((property) => found?.relationships.some((relationship) => relationship.propertyId === property.id))); setProfile(nextProfile); if (nextProfile?.id) { const [nextApprovals, nextActivity] = await Promise.all([listRentalOwnerApprovals(nextProfile.id), listRentalOwnerActivity(nextProfile.id)]); setApprovals(nextApprovals); setActivity(nextActivity) } else { setApprovals([]); setActivity([]) } } catch (cause) { setError(cause?.message || 'Unable to load owner workspace.') } finally { setLoading(false) } }, [ownerId, scope.organisationId])
  useEffect(() => { void load() }, [load])
  const saveProfile = async (updates) => { if (!owner) return; try { setSaving(true); setError(''); const saved = await upsertRentalOwnerProfile({ organisationId: scope.organisationId, partyId: owner.partyId, createdBy: scope.userId, ownerType: profile?.ownerType || 'individual', complianceStatus: profile?.complianceStatus || 'not_started', bankingStatus: profile?.bankingStatus || 'not_started', portalStatus: profile?.portalStatus || 'not_invited', ...updates }); await createRentalOwnerActivity({ organisationId: scope.organisationId, profileId: saved.id, occurredBy: scope.userId, description: 'Owner profile updated.' }); await load() } catch (cause) { setError(cause?.message || 'Unable to save owner profile.') } finally { setSaving(false) } }
  if (loading) return <main className="grid min-h-56 place-items-center text-sm text-[#60758b]"><span className="inline-flex items-center gap-2"><Loader2 size={16} className="animate-spin" />Loading owner…</span></main>
  if (error || !owner) return <main className="mx-auto w-full px-6 py-8"><Link to="/agent/rentals/portfolio/owners" className="inline-flex items-center gap-1 font-semibold text-[#1769d1]"><ArrowLeft size={15} />Back to owners</Link><p className="mt-5 rounded-xl border border-[#f2c6c6] bg-[#fff7f7] p-4 text-sm text-[#9f3131]">{error || 'This owner is not available in the current workspace.'}</p></main>
  const healthy = profile?.complianceStatus === 'verified' && profile?.bankingStatus === 'verified'
  const content = {
    overview: <div className="grid gap-5 xl:grid-cols-2"><Panel title="Owner health" icon={ShieldCheck}><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Compliance', profile?.complianceStatus || 'not_started'], ['Banking', profile?.bankingStatus || 'not_started'], ['Portal', profile?.portalStatus || 'not_invited'], ['Approvals', approvals.filter((item) => item.status === 'pending').length ? 'pending' : 'complete']].map(([label, status]) => <div key={label} className="rounded-[14px] border border-[#e1e9f1] bg-[#fbfdff] p-3"><p className="text-xs font-semibold uppercase tracking-wide text-[#718399]">{label}</p><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass(status)}`}>{title(status)}</span></div>)}</div><button type="button" disabled={saving} onClick={() => saveProfile({ complianceStatus: profile?.complianceStatus === 'verified' ? 'incomplete' : 'verified' })} className="mt-5 rounded-[10px] border border-[#dbe4ee] px-3 py-2 text-sm font-semibold text-[#35546c]">{profile?.complianceStatus === 'verified' ? 'Mark compliance incomplete' : 'Mark compliance verified'}</button></Panel><Panel title="Portfolio summary" icon={Building2}><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-[#718399]">Properties</dt><dd className="mt-1 text-xl font-semibold">{properties.length}</dd></div><div><dt className="text-[#718399]">Primary contacts</dt><dd className="mt-1 text-xl font-semibold">{owner.primaryPropertyCount}</dd></div><div><dt className="text-[#718399]">Contact</dt><dd className="mt-1 font-semibold">{owner.email || owner.phone || 'Not captured'}</dd></div><div><dt className="text-[#718399]">Owner reference</dt><dd className="mt-1 font-semibold">{profile?.ownerReference || 'Not assigned'}</dd></div></dl></Panel><Panel title="Outstanding approvals" icon={CheckCircle2}>{approvals.length ? <div className="mt-4 space-y-2">{approvals.slice(0, 4).map((approval) => <div key={approval.id} className="rounded-xl border border-[#e1e9f1] p-3"><p className="font-semibold">{approval.summary}</p><p className="mt-1 text-xs text-[#718399]">{title(approval.approvalType)} · {title(approval.status)}</p></div>)}</div> : <p className="mt-4 text-sm text-[#60758b]">No owner approvals are awaiting action.</p>}</Panel><Panel title="Recent activity" icon={UsersRound}>{activity.length ? <div className="mt-4 space-y-3">{activity.slice(0, 4).map((event) => <div key={event.id} className="border-l-2 border-[#d6e4ef] pl-3"><p className="font-semibold">{event.description}</p><p className="mt-1 text-xs text-[#718399]">{title(event.activityType)} · {event.occurredAt ? new Date(event.occurredAt).toLocaleDateString('en-ZA') : 'Recently'}</p></div>)}</div> : <p className="mt-4 text-sm text-[#60758b]">Activity will appear as profile, mandate and approval events are recorded.</p>}</Panel></div>,
    properties: <Panel title="Connected properties" icon={Building2}><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{properties.map((property) => <Link key={property.id} to={`/agent/rentals/portfolio/properties/${property.id}`} className="rounded-[14px] border border-[#dfe7f0] p-4 transition hover:border-[#9cc6b2]"><p className="font-semibold">{property.name}</p><p className="mt-1 text-sm text-[#60758b]">{property.address?.line1 || 'Address pending'}{property.address?.city ? ` · ${property.address.city}` : ''}</p></Link>)}</div></Panel>,
    mandates: <Panel title="Management mandates" icon={Landmark}><p className="mt-4 text-sm text-[#60758b]">Mandates remain property-specific. Open a connected property to view, renew or replace the signed mandate without overwriting the original record.</p><div className="mt-4 flex flex-wrap gap-2">{properties.map((property) => <Link key={property.id} to={`/agent/rentals/portfolio/properties/${property.id}/landlord`} className="rounded-[10px] border border-[#dbe4ee] px-3 py-2 text-sm font-semibold text-[#1769d1]">{property.name}</Link>)}</div></Panel>,
    financials: <Panel title="Owner financials" icon={CircleDollarSign}><p className="mt-4 text-sm text-[#60758b]">Owner statements and disbursements are retained at property level in the current financial model. A consolidated owner ledger is intentionally withheld until disbursement data is introduced.</p></Panel>,
    documents: <Panel title="Owner documents" icon={FileText}><p className="mt-4 text-sm text-[#60758b]">Compliance state is recorded for this owner. Property-specific mandate and evidence documents remain attached to the linked property so their audit trail is preserved.</p><button type="button" disabled={saving} onClick={() => saveProfile({ complianceStatus: 'under_review' })} className="mt-4 rounded-[10px] border border-[#dbe4ee] px-3 py-2 text-sm font-semibold text-[#35546c]">Request compliance review</button></Panel>,
    communication: <Panel title="Owner communication" icon={UsersRound}><p className="mt-4 text-sm text-[#60758b]">Use the owner’s recorded email or phone from the shared contact record. Unified owner communications will be added once outbound messages are stored as Rental activity events.</p></Panel>,
    activity: <Panel title="Owner activity" icon={UsersRound}>{activity.length ? <div className="mt-4 space-y-3">{activity.map((event) => <article key={event.id} className="border-l-2 border-[#d6e4ef] pl-4"><p className="font-semibold">{event.description}</p><p className="mt-1 text-xs text-[#718399]">{title(event.activityType)} · {event.occurredAt ? new Date(event.occurredAt).toLocaleString('en-ZA') : 'Recently'}</p></article>)}</div> : <p className="mt-4 text-sm text-[#60758b]">No recorded owner activity yet.</p>}</Panel>,
  }
  return <main className="mx-auto w-full px-4 py-5 sm:px-6 lg:px-8"><section className="space-y-5 pb-8"><Link to="/agent/rentals/portfolio/owners" className="inline-flex items-center gap-1 text-sm font-semibold text-[#1769d1]"><ArrowLeft size={15} />Back to owners</Link><TransactionWorkspaceHeader contextLabel="RENTAL OWNER" title={owner.name} unitLabel={profile?.ownerType ? title(profile.ownerType) : 'Owner profile'} subtitle={owner.email || owner.phone || 'Contact details pending'} pills={[{ label: `${properties.length} connected ${properties.length === 1 ? 'property' : 'properties'}`, tone: 'blue', icon: 'stage' }, { label: healthy ? 'Owner setup complete' : 'Owner setup required', tone: healthy ? 'green' : 'amber', icon: 'health' }]} stats={[{ label: 'Compliance', value: title(profile?.complianceStatus || 'not_started'), icon: 'health' }, { label: 'Banking', value: title(profile?.bankingStatus || 'not_started'), icon: 'finance' }, { label: 'Approvals', value: approvals.filter((item) => item.status === 'pending').length, helperText: 'Pending owner action', icon: 'stage' }, { label: 'Portal', value: title(profile?.portalStatus || 'not_invited'), icon: 'portal' }]} actions={[{ id: 'owner-primary-action', label: healthy ? 'View portfolio' : 'Complete profile', icon: 'user', onClick: () => saveProfile({ complianceStatus: profile?.complianceStatus || 'incomplete' }), disabled: saving }]} /><nav className="flex overflow-x-auto rounded-[18px] border border-[#dbe6f2] bg-white p-2 shadow-[0_8px_20px_rgba(15,23,42,.035)]">{tabs.map(([key, label]) => <NavLink key={key} to={tabPath(key)} end={key === 'overview'} className={({ isActive }) => `min-w-[122px] shrink-0 rounded-[12px] px-5 py-3 text-center text-sm font-semibold transition ${isActive ? 'bg-[#edf7f3] text-[#087a55] shadow-sm' : 'text-[#60758b] hover:bg-[#f8fbff]'}`}>{label}</NavLink>)}</nav>{error ? <p className="rounded-xl border border-[#f2c6c6] bg-[#fff7f7] p-3 text-sm text-[#9f3131]">{error}</p> : null}{content[current]}</section></main>
}
