import RentalListingLeadsPanel from './RentalListingLeadsPanel'
import './rental-listing-overview.css'

const name = (application) => application.data?.entity?.legalName || [application.data?.identity?.firstName, application.data?.identity?.lastName].filter(Boolean).join(' ') || 'Tenant application'
const label = (value) => String(value || '').replaceAll('_', ' ')

export default function RentalListingRelatedPanels({ activeTab, snapshot, onNavigate, onAddLead }) {
  if (!snapshot) return <section className="rental-overview-panel" role="status">Loading listing details…</section>
  if (activeTab === 'commission') return <section className="rental-overview-panel"><h2>Commission</h2>{snapshot.issues.includes('Commission') ? <p>Mandate fees could not be loaded.</p> : snapshot.mandates.length ? snapshot.mandates.map((mandate) => <article key={mandate.id} className="rental-overview-record"><h3>Rental mandate</h3><dl><dt>Status</dt><dd>{label(mandate.mandateStatus)}</dd><dt>Management fee</dt><dd>{mandate.managementFeeAmount == null ? 'Not captured' : mandate.managementFeeType === 'percentage' ? `${mandate.managementFeeAmount}%` : `R ${Number(mandate.managementFeeAmount).toLocaleString('en-ZA')}`}</dd><dt>Fee type</dt><dd>{label(mandate.managementFeeType) || 'Not captured'}</dd></dl></article>) : <p className="rental-overview-caption">No linked mandate fees have been captured for this listing.</p>}</section>
  if (activeTab === 'activity') return <section className="rental-overview-panel"><h2>Activity</h2>{snapshot.issues.includes('Viewings & activity') ? <p>Activity could not be loaded.</p> : snapshot.activity.length ? snapshot.activity.map((item) => <article className="rental-overview-record" key={item.id}><strong>{item.activity_title || label(item.activity_type)}</strong><p>{item.activity_description}</p><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString('en-ZA')}</time></article>) : <p className="rental-overview-caption">No activity captured yet.</p>}</section>
  return <div className="rental-overview-stack"><RentalListingLeadsPanel snapshot={snapshot} onNavigate={onNavigate} onAddLead={onAddLead} /><section className="rental-overview-panel"><h3 className="rental-overview-subheading">Applications</h3>{snapshot.issues.includes('Applications') ? <p>Applications could not be loaded.</p> : snapshot.applications.length ? snapshot.applications.map((application) => <button type="button" key={application.id} data-rental-control="listing-application" className="rental-overview-record rental-overview-application" onClick={() => onNavigate(`/agent/rentals/applications/${encodeURIComponent(application.id)}`)}><strong>{name(application)}</strong><span>{label(application.status)}</span></button>) : <p className="rental-overview-caption">No applications linked to this listing yet.</p>}{snapshot.legacyApplications?.length ? <><h3 className="rental-overview-subheading">Previously captured applications</h3>{snapshot.legacyApplications.map((application) => <article className="rental-overview-record" key={application.id}><strong>{application.tenantName}</strong><p>{label(application.status)}</p></article>)}</> : null}</section></div>
}
