import { useCallback, useEffect, useMemo, useState } from 'react'
import { BarChart3, Loader2, RefreshCw, Users } from 'lucide-react'
import { useWorkspace } from '../../context/WorkspaceContext'
import { getRentalLeadManagementReport } from '../../services/rentals/rentalLeadManagementReportService'
import { resolveRentalWorkspaceScope } from '../../services/rentals/rentalWorkspaceScope'

const CELL = ({ children }) => <td className="py-3 text-[#50677e]">{children}</td>
function ReportTable({ title, rows }) { return <section className="ui-panel ui-panel-body"><h2 className="text-lg font-semibold text-[#18324b]">{title}</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-[#dbe6f2] text-xs uppercase text-[#607891]"><tr><th className="pb-3 font-semibold">Owner</th><th className="pb-3 font-semibold">Active</th><th className="pb-3 font-semibold">Won</th><th className="pb-3 font-semibold">Lost</th><th className="pb-3 font-semibold">Nurture</th><th className="pb-3 font-semibold">Overdue</th><th className="pb-3 font-semibold">Open tasks</th><th className="pb-3 font-semibold">Current health</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.key} className="border-b border-[#edf2f7] last:border-0"><td className="py-3 font-semibold text-[#18324b]">{row.label}</td><CELL>{row.active}</CELL><CELL>{row.won}</CELL><CELL>{row.lost}</CELL><CELL>{row.nurture}</CELL><CELL>{row.overdue}</CELL><CELL>{row.openTasks}</CELL><td className="py-3 font-semibold text-[#18324b]">{row.currentTaskHealth === null ? '—' : `${row.currentTaskHealth}%`}</td></tr>) : <tr><td colSpan="8" className="py-8 text-center text-[#607891]">No records are visible in this scope.</td></tr>}</tbody></table></div></section> }

export default function RentalLeadManagementReportPage() {
  const workspace = useWorkspace(); const scope = useMemo(() => resolveRentalWorkspaceScope(workspace), [workspace]); const options = useMemo(() => ({ assignedAgentId: scope.assignedAgentId, branchId: scope.branchId, scopeLevel: scope.scopeLevel, includeAllOrganisationLeads: scope.scopeLevel === 'organisation' }), [scope]); const [report, setReport] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!scope.organisationId) { setLoading(false); return } try { setLoading(true); setError(''); setReport(await getRentalLeadManagementReport(scope.organisationId, options)) } catch (loadError) { setError(loadError?.message || 'Unable to load rental management reporting.') } finally { setLoading(false) } }, [options, scope.organisationId]); useEffect(() => { void load() }, [load])
  return <section className="page-content"><div className="ui-section-stack"><header className="ui-toolbar"><div className="ui-toolbar-group"><BarChart3 size={20} /><div><p className="text-xs font-semibold uppercase text-[#607891]">Rental pipeline</p><h1 className="text-2xl font-semibold text-[#18324b]">Management Report</h1><p className="mt-1 text-sm text-[#607891]">Current workload, outcomes, and follow-up health for records visible in your workspace scope.</p></div></div><button type="button" className="ui-pill-button" onClick={() => void load()} disabled={loading}>{loading ? <Loader2 className="animate-spin" size={16} /> : <RefreshCw size={16} />}Refresh</button></header>{error ? <p className="rounded-[12px] border border-[#f2c6c6] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#9f3131]">{error}</p> : null}{loading ? <p className="py-12 text-center text-sm text-[#607891]"><Loader2 className="mr-2 inline animate-spin" size={15} />Loading management report…</p> : report ? <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article className="ui-panel ui-panel-body"><Users size={18} className="text-[#1f4f78]" /><p className="mt-3 text-3xl font-semibold text-[#18324b]">{report.totals.active}</p><p className="mt-1 text-sm text-[#607891]">Active leads</p></article><article className="ui-panel ui-panel-body"><p className="text-3xl font-semibold text-[#18324b]">{report.totals.won}</p><p className="mt-1 text-sm text-[#607891]">Won outcomes</p></article><article className="ui-panel ui-panel-body"><p className="text-3xl font-semibold text-[#18324b]">{report.totals.overdue}</p><p className="mt-1 text-sm text-[#607891]">Overdue follow-ups</p></article><article className="ui-panel ui-panel-body"><p className="text-3xl font-semibold text-[#18324b]">{report.totals.currentTaskHealth === null ? '—' : `${report.totals.currentTaskHealth}%`}</p><p className="mt-1 text-sm text-[#607891]">Current open-task health</p></article></div><section className="ui-panel ui-panel-body"><h2 className="text-lg font-semibold text-[#18324b]">Active lead aging</h2><p className="mt-1 text-sm text-[#607891]">Age is based on captured lead creation time; records without it remain explicitly unknown.</p><div className="mt-4 grid gap-3 sm:grid-cols-5">{[['0–2 days', report.ageing['0_2']], ['3–7 days', report.ageing['3_7']], ['8–14 days', report.ageing['8_14']], ['15+ days', report.ageing['15_plus']], ['Unknown', report.ageing.unknown]].map(([label, value]) => <div key={label} className="rounded-[10px] bg-[#f5f8fb] p-3"><p className="text-2xl font-semibold text-[#18324b]">{value}</p><p className="mt-1 text-xs text-[#607891]">{label}</p></div>)}</div></section><div className="grid gap-6 xl:grid-cols-2"><ReportTable title="Agent workload" rows={report.agents} /><ReportTable title="Branch workload" rows={report.branches} /></div></> : <p className="py-12 text-center text-sm text-[#607891]">No reporting data is available in this scope.</p>}</div></section>
}
