import { ArrowRight, BedDouble, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, DoorOpen, Home, Loader2, Tag, UsersRound, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'

const dateTime = (value) => value ? new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const timeOnly = (value) => value ? new Intl.DateTimeFormat('en-ZA', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)) : '—'
const money = (value) => value === null || value === undefined ? '—' : `R${Number(value).toLocaleString('en-ZA', { maximumFractionDigits: 0 })}`
const statusClass = (tone) => ({ green: 'bg-[#eaf7ef] text-[#16734c]', blue: 'bg-[#eef5ff] text-[#2563a4]', amber: 'bg-[#fff6e7] text-[#9a5b08]', slate: 'bg-[#f1f5f9] text-[#52657a]' }[tone] || 'bg-[#f1f5f9] text-[#52657a]')
const severityClass = (severity) => ({ attention: 'bg-[#fff1ed] text-[#c2410c]', warning: 'bg-[#fff7e7] text-[#a16207]', info: 'bg-[#eff5ff] text-[#2563a4]' }[severity] || 'bg-[#f1f5f9] text-[#52657a]')
const imageStyle = (url) => url ? { backgroundImage: `linear-gradient(rgba(15, 32, 28, .12), rgba(15, 32, 28, .12)), url(${url})` } : undefined

export function Section({ title, action, children, className = '' }) {
  return <section className={`rounded-[20px] border border-[#e6ebf0] bg-white p-4 shadow-[0_10px_28px_rgba(15,23,42,.035)] sm:p-5 ${className}`}><div className="flex items-center justify-between gap-4"><h2 className="text-[1rem] font-semibold tracking-[-.02em] text-[#152235]">{title}</h2>{action}</div>{children}</section>
}

export function LinkAction({ to, children }) { return <Link to={to} className="inline-flex shrink-0 items-center gap-1 text-xs font-semibold text-[#087a59] hover:text-[#056447]">{children}<ArrowRight size={14} /></Link> }

function MetricCard({ icon, label, value, detail, action, href, tone = 'green', children }) {
  const MetricIcon = icon
  const iconClass = tone === 'amber' ? 'bg-[#fff5e6] text-[#a85d08]' : tone === 'dark' ? 'bg-[#e7f6ee] text-[#087a59]' : 'bg-[#edf8f2] text-[#087a59]'
  return <Link to={href} className="group rounded-[20px] border border-[#e6ebf0] bg-white p-4 shadow-[0_10px_28px_rgba(15,23,42,.035)] transition hover:-translate-y-px hover:border-[#cde5da] sm:p-5"><div className="flex items-start justify-between gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${iconClass}`}><MetricIcon size={19} /></span>{children}</div><p className="mt-4 text-[2rem] font-semibold leading-none tracking-[-.055em] text-[#101828]">{value}</p><p className="mt-2 text-sm font-medium text-[#344054]">{label}</p><p className="mt-1 text-xs text-[#667085]">{detail}</p>{action ? <p className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-[#087a59]">{action}<ArrowRight size={13} /></p> : null}</Link>
}

export function Metrics({ dashboard, loading, rangeDays }) {
  const occupancy = dashboard.occupancyRate === null ? '—' : `${dashboard.occupancyRate}%`
  return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={DoorOpen} label="Arrivals today" value={loading ? '—' : dashboard.arrivalsToday.length} detail={`${dashboard.arrivalsToday.length} upcoming`} action="View arrivals" href="/agent/rentals/short-term/bookings" /><MetricCard icon={ClipboardCheck} tone="amber" label="Departures today" value={loading ? '—' : dashboard.departuresToday.length} detail={`${dashboard.departuresToday.length} due`} action="View departures" href="/agent/rentals/short-term/bookings" /><MetricCard icon={UsersRound} label="Guests in-house" value={loading ? '—' : dashboard.guestsInHouse} detail={`${dashboard.activeStays.length} active stay${dashboard.activeStays.length === 1 ? '' : 's'}`} action="View guests" href="/agent/rentals/short-term/bookings" /><MetricCard icon={BedDouble} tone="dark" label="Occupancy rate" value={loading ? '—' : occupancy} detail={`Next ${rangeDays} days`} action="View performance" href="/agent/rentals/short-term/properties"><span className="grid h-9 w-9 place-items-center rounded-full border-[3px] border-[#9fd5bb] text-[.62rem] font-bold text-[#087a59]">{dashboard.occupancyRate ?? 0}%</span></MetricCard></section>
}

const eventIcon = (kind) => kind === 'arrival' ? DoorOpen : kind === 'turnover' ? ClipboardCheck : Clock3

export function TodayTimeline({ dashboard, loading }) {
  const title = `Today · ${new Intl.DateTimeFormat('en-ZA', { day: 'numeric', month: 'long' }).format(new Date())}`
  return <Section title={title} action={<LinkAction to="/agent/rentals/short-term/calendar">View full schedule</LinkAction>}><div className="mt-4 h-[278px] overflow-y-auto overscroll-contain pr-2" role="region" aria-label="Today’s short-term rental schedule" tabIndex={0}>{loading ? <p className="py-12 text-center text-sm text-[#667085]"><Loader2 className="mr-2 inline animate-spin" size={15} />Loading today’s schedule…</p> : dashboard.events.length ? <div className="relative">{dashboard.events.map((event, index) => { const Icon = eventIcon(event.kind); return <Link key={event.id} to={event.href} className="grid grid-cols-[44px_30px_minmax(0,1fr)_auto] gap-3 py-3 first:pt-0 hover:bg-[#fbfdfc]"><p className="pt-1 text-xs font-semibold tabular-nums text-[#344054]">{timeOnly(event.at)}</p><div className="relative flex justify-center">{index < dashboard.events.length - 1 ? <span className="absolute top-7 h-[calc(100%+2px)] w-px bg-[#dbe9e1]" /> : null}<span className="z-10 mt-0.5 grid h-7 w-7 place-items-center rounded-full border-4 border-[#eff8f3] bg-[#13885f] text-white"><Icon size={13} /></span></div><div className="min-w-0"><p className="text-sm font-semibold text-[#243348]">{event.title} <span className="font-normal text-[#60758b]">· {event.propertyName}</span></p><p className="mt-0.5 text-xs text-[#667085]">{event.detail}</p><p className="mt-0.5 text-xs text-[#8a99ab]">{event.unitLabel}</p></div><span className={`mt-1 h-fit whitespace-nowrap rounded-full px-2 py-1 text-[.66rem] font-semibold ${statusClass(event.tone)}`}>{event.status}</span></Link> })}</div> : <p className="rounded-xl border border-dashed border-[#dbe6f1] py-10 text-center text-sm text-[#667085]">Nothing scheduled for today. Your team is all caught up.</p>}</div></Section>
}

export function AttentionPanel({ dashboard, loading }) {
  return <Section title="Needs your attention" action={dashboard.attention.length ? <span className="text-xs font-medium text-[#667085]">{dashboard.attention.length} item{dashboard.attention.length === 1 ? '' : 's'}</span> : null}><div className="mt-4 grid gap-2">{loading ? <p className="py-12 text-center text-sm text-[#667085]">Loading actions…</p> : dashboard.attention.length ? dashboard.attention.slice(0, 3).map((item) => <Link key={item.id} to={item.href} className="flex items-center gap-3 rounded-xl bg-[#fffcf8] p-3 transition hover:bg-[#fff8ee]"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${severityClass(item.severity)}`}>{item.severity === 'warning' ? <Tag size={16} /> : <CheckCircle2 size={16} />}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-[#243348]">{item.title}</p><p className="truncate text-xs text-[#667085]">{item.propertyName}</p><p className="mt-0.5 text-xs text-[#8a99ab]">{item.detail}</p></div><ChevronRight className="text-[#98a2b3]" size={16} /></Link>) : <div className="rounded-xl bg-[#f4fbf7] px-4 py-8 text-center"><CheckCircle2 className="mx-auto text-[#13885f]" size={22} /><p className="mt-2 text-sm font-semibold text-[#1d5e48]">Everything is on track</p><p className="mt-1 text-xs text-[#667085]">No operational issues need attention.</p></div>} {dashboard.attention.length ? <LinkAction to="/agent/rentals/short-term/bookings">View all items</LinkAction> : null}</div></Section>
}

function GuestStayRow({ booking, type }) {
  const arrival = type === 'arrival'; const timestamp = arrival ? booking.checkInAt : booking.checkOutAt
  return <Link to="/agent/rentals/short-term/bookings" className={`flex items-center gap-3 rounded-xl p-2.5 transition ${arrival ? 'bg-[#f3faf6] hover:bg-[#edf8f2]' : 'bg-[#fffaf1] hover:bg-[#fff6e7]'}`}><div className="h-14 w-16 shrink-0 rounded-lg bg-cover bg-center" style={imageStyle(booking.propertyCoverImageUrl)} aria-label={booking.propertyCoverImageAlt || undefined} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#243348]">{booking.guestName || `Guest ${type}`}</p><p className="truncate text-xs text-[#667085]">{booking.propertyName} · {booking.unitLabel}</p><p className="mt-1 text-xs text-[#8a99ab]">{dateTime(timestamp)}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[.66rem] font-semibold ${arrival ? 'bg-white text-[#17764d]' : 'bg-white text-[#9a5b08]'}`}>{arrival ? 'Confirmed' : 'Check-out due'}</span></Link>
}

export function DailyGuestLists({ dashboard, loading }) { return <section className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,1.1fr)_minmax(300px,.8fr)]"><Section title="Today’s arrivals" action={<LinkAction to="/agent/rentals/short-term/bookings">View arrivals</LinkAction>}><div className="mt-3 grid gap-2">{loading ? <p className="py-5 text-sm text-[#667085]">Loading arrivals…</p> : dashboard.arrivalsToday.length ? dashboard.arrivalsToday.slice(0, 3).map((booking) => <GuestStayRow key={booking.id} booking={booking} type="arrival" />) : <p className="rounded-xl border border-dashed border-[#dbe6f1] p-4 text-sm text-[#667085]">No confirmed arrivals today.</p>}</div></Section><Section title="Today’s departures" action={<LinkAction to="/agent/rentals/short-term/bookings">View departures</LinkAction>}><div className="mt-3 grid gap-2">{loading ? <p className="py-5 text-sm text-[#667085]">Loading departures…</p> : dashboard.departuresToday.length ? dashboard.departuresToday.slice(0, 3).map((booking) => <GuestStayRow key={booking.id} booking={booking} type="departure" />) : <p className="rounded-xl border border-dashed border-[#dbe6f1] p-4 text-sm text-[#667085]">No in-house departures due today.</p>}</div></Section><PortfolioPerformance dashboard={dashboard} /></section> }

export function PortfolioPerformance({ dashboard }) { const points = dashboard.performance.daily.slice(0, 30).filter((_, index) => index % 2 === 0); return <section className="rounded-[20px] bg-[#102c26] p-5 text-white shadow-[0_14px_32px_rgba(15,49,41,.16)]"><div className="flex items-start justify-between gap-3"><div><h2 className="text-[1rem] font-semibold">Portfolio performance</h2><p className="mt-1 text-xs text-[#b9cfc6]">Last 30 days</p></div><WalletCards size={18} className="text-[#9ad2b6]" /></div><div className="mt-5 grid grid-cols-3 gap-2"><div><p className="text-lg font-semibold">{dashboard.performance.occupancyRate ?? 0}%</p><p className="mt-1 text-[.65rem] text-[#b9cfc6]">Occupancy</p></div><div><p className="text-lg font-semibold">{money(dashboard.performance.bookingRevenue)}</p><p className="mt-1 text-[.65rem] text-[#b9cfc6]">Booked revenue</p></div><div><p className="text-lg font-semibold">{dashboard.enabledUnitCount * 30}</p><p className="mt-1 text-[.65rem] text-[#b9cfc6]">Nights available</p></div></div><div className="mt-6 flex h-16 items-end gap-1" aria-label="30 day occupancy trend">{points.map((point) => <span key={point.date} className="flex-1 rounded-t bg-[#66bd93]" style={{ height: `${Math.max(10, point.occupancyRate || 0)}%` }} />)}</div><LinkAction to="/agent/rentals/short-term/properties">View full performance</LinkAction></section> }

export function OccupancyForecast({ dashboard }) { const days = dashboard.performance.daily.slice(0, 14); const tone = (value) => value >= 80 ? 'bg-[#16855e] text-white' : value >= 60 ? 'bg-[#dff3e7] text-[#176447]' : value >= 40 ? 'bg-[#fff0d6] text-[#9a5b08]' : 'bg-[#fbe8e7] text-[#ae3d36]'; return <Section title="Occupancy next 14 days" action={<LinkAction to="/agent/rentals/short-term/calendar">View calendar</LinkAction>}><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{days.map((point) => <Link key={point.date} to={`/agent/rentals/short-term/calendar?date=${point.date}`} className={`min-w-[74px] rounded-xl px-3 py-3 text-center transition hover:-translate-y-px ${tone(point.occupancyRate || 0)}`}><p className="text-[.62rem] font-semibold uppercase tracking-wide">{new Intl.DateTimeFormat('en-ZA', { day: 'numeric', month: 'short' }).format(new Date(`${point.date}T12:00:00`))}</p><p className="mt-1 text-lg font-semibold tracking-[-.04em]">{point.occupancyRate ?? 0}%</p></Link>)}</div></Section> }
