import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, ChevronRight, Loader2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useWorkspace } from '../../context/WorkspaceContext'
import { listShortTermBookings } from '../../services/rentals/rentalShortTermBookingRepository.js'
import { resolveRentalWorkspaceScope } from '../../services/rentals/rentalWorkspaceScope.js'

const dateLabel = (value) => new Intl.DateTimeFormat('en-ZA', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(value))
const timeLabel = (value) => new Intl.DateTimeFormat('en-ZA', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value))

export default function ShortTermRentalCalendarPage() {
  const workspace = useWorkspace(); const scope = useMemo(() => resolveRentalWorkspaceScope(workspace), [workspace]); const [bookings, setBookings] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!scope.organisationId) { setBookings([]); setLoading(false); return } try { setLoading(true); setError(''); setBookings(await listShortTermBookings({ organisationId: scope.organisationId, branchId: scope.listingBranchId, from: new Date().toISOString() })) } catch (cause) { setError(cause?.message || 'Unable to load the Short-Term calendar.') } finally { setLoading(false) } }, [scope.listingBranchId, scope.organisationId])
  useEffect(() => { void load() }, [load])
  const upcoming = bookings.filter((booking) => ['provisional', 'confirmed', 'checked_in'].includes(booking.status)).slice(0, 30)
  return <main className="mx-auto w-full max-w-[1600px] px-3 py-3 sm:px-5 lg:px-7"><section className="rounded-[18px] border border-[#e4ebf2] bg-white p-4 shadow-[0_10px_26px_rgba(15,23,42,.035)] sm:p-5"><header className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf8f2] text-[#087a59]"><CalendarDays size={19} /></span><div><h1 className="text-lg font-semibold text-[#152235]">Short-Term calendar</h1><p className="mt-1 text-sm text-[#667085]">Confirmed stays, arrivals and departures across your enabled units.</p></div></div><Link to="/agent/rentals/short-term/bookings" className="text-xs font-semibold text-[#087a59]">Manage bookings</Link></header>{error ? <p className="mt-4 rounded-xl border border-[#f2c6c6] bg-[#fff7f7] p-3 text-sm text-[#9f3131]">{error}</p> : null}<div className="mt-5 divide-y divide-[#edf2f6]">{loading ? <p className="py-10 text-center text-sm text-[#667085]"><Loader2 className="mr-2 inline animate-spin" size={15} />Loading calendar…</p> : upcoming.length ? upcoming.map((booking) => <Link key={booking.id} to="/agent/rentals/short-term/bookings" className="grid grid-cols-[100px_minmax(0,1fr)_auto] items-center gap-3 py-3 hover:bg-[#fbfdfc]"><p className="text-xs font-semibold text-[#51667f]">{dateLabel(booking.checkInAt)}<span className="mt-0.5 block font-normal text-[#98a2b3]">{timeLabel(booking.checkInAt)}</span></p><div><p className="text-sm font-semibold text-[#243348]">{booking.propertyName} · {booking.unitLabel}</p><p className="mt-0.5 text-xs text-[#667085]">{booking.guestName || 'Guest'} · check-out {dateLabel(booking.checkOutAt)}</p></div><ChevronRight size={16} className="text-[#98a2b3]" /></Link>) : <p className="rounded-xl border border-dashed border-[#dbe6f1] p-7 text-center text-sm text-[#667085]">No future stays are scheduled.</p>}</div></section></main>
}
