import { CalendarDays, ChevronLeft, ChevronRight, CircleDollarSign, Filter, List, Loader2, Search, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { calendarDateKey } from '../../services/rentals/shortTermRentalCalendarModel.js'

const dayLabel = (value) => new Intl.DateTimeFormat('en-ZA', { weekday: 'short' }).format(value)
const dateLabel = (value) => new Intl.DateTimeFormat('en-ZA', { day: '2-digit', month: 'short' }).format(value)
const dateTime = (value) => new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const money = (value) => value === null || value === undefined ? '—' : `R${Number(value).toLocaleString('en-ZA', { maximumFractionDigits: 0 })}`
const bookingTone = (booking) => booking.status === 'checked_in' ? 'border-[#b7e4cf] bg-[#eaf8f0] text-[#126344]' : booking.checkOutThisWeek ? 'border-[#f4d9ad] bg-[#fff5e8] text-[#9a5b08]' : 'border-[#cfe1ff] bg-[#eef5ff] text-[#2563a4]'
const bookingStatus = (booking) => booking.status === 'checked_in' ? 'Checked in' : booking.checkOutThisWeek ? `Check-out ${dayLabel(new Date(booking.checkOutAt))}` : 'Upcoming'
const imageStyle = (url) => url ? { backgroundImage: `url(${url})` } : undefined

function SummaryCard({ icon, value, label, detail, tone = 'green' }) { const Icon = icon; const toneClass = tone === 'blue' ? 'bg-[#edf4ff] text-[#2876ca]' : tone === 'amber' ? 'bg-[#fff3e7] text-[#d66a16]' : tone === 'purple' ? 'bg-[#f4f0ff] text-[#7659b8]' : 'bg-[#edf8f2] text-[#087a59]'; return <div className="min-w-[168px] rounded-[16px] border border-[#e8edf2] bg-white p-4"><span className={`grid h-9 w-9 place-items-center rounded-xl ${toneClass}`}><Icon size={17} /></span><p className="mt-3 text-2xl font-semibold tracking-[-.045em] text-[#132238]">{value}</p><p className="mt-1 text-xs font-semibold text-[#344054]">{label}</p><p className="mt-1 text-xs text-[#77869a]">{detail}</p></div> }

export function CalendarHeader({ summary }) { return <><header className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-semibold tracking-[-.035em] text-[#152235]">Short-Term calendar</h1><p className="mt-1 text-sm text-[#667085]">View confirmed stays, arrivals and departures across your enabled units.</p></div><Link to="/agent/rentals/short-term/bookings" className="mt-1 text-xs font-semibold text-[#087a59]">Manage bookings</Link></header><div className="mt-5 flex gap-3 overflow-x-auto pb-1"><SummaryCard icon={CalendarDays} value={summary.stays} label="Stays" detail="this week" /><SummaryCard icon={UsersRound} tone="blue" value={summary.guestsCheckingIn} label="Guests" detail="checking in" /><SummaryCard icon={UsersRound} tone="amber" value={summary.guestsCheckingOut} label="Guests" detail="checking out" /><SummaryCard icon={CalendarDays} tone="purple" value={summary.occupancyRate === null ? '—' : `${summary.occupancyRate}%`} label="Avg. occupancy" detail="this week" /><SummaryCard icon={CircleDollarSign} value={money(summary.bookedRevenue)} label="Booked revenue" detail="this week" /></div></> }

export function CalendarToolbar({ view, setView, search, setSearch, status, setStatus, weekStart, onToday, onPrevious, onNext }) { const range = `${dateLabel(weekStart)} – ${dateLabel(new Date(weekStart.getFullYear(), weekStart.getMonth(), weekStart.getDate() + 6))}`; return <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-xl border border-[#e6ecf1] bg-[#fbfcfd] p-1"><button type="button" onClick={() => setView('calendar')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view === 'calendar' ? 'bg-[#087a59] text-white' : 'text-[#52657a]'}`}>Calendar</button><button type="button" onClick={() => setView('list')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${view === 'list' ? 'bg-[#087a59] text-white' : 'text-[#52657a]'}`}><List className="mr-1 inline" size={14} />List</button><button type="button" disabled className="rounded-lg px-3 py-2 text-xs font-semibold text-[#a2adbb]" title="Timeline view is coming soon">Timeline</button></div><button type="button" onClick={onToday} className="rounded-xl border border-[#e4eaf0] bg-white px-3 py-2 text-xs font-semibold text-[#344054]">Today</button><div className="flex overflow-hidden rounded-xl border border-[#e4eaf0] bg-white"><button type="button" onClick={onPrevious} className="px-2.5 py-2 text-[#52657a]" aria-label="Previous week"><ChevronLeft size={16} /></button><button type="button" onClick={onNext} className="border-l border-[#e4eaf0] px-2.5 py-2 text-[#52657a]" aria-label="Next week"><ChevronRight size={16} /></button></div><span className="text-xs font-semibold text-[#52657a]">{range}</span></div><div className="flex flex-1 flex-wrap justify-end gap-2"><label className="relative min-w-[190px]"><Search className="absolute left-3 top-2.5 text-[#7e8da1]" size={15} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search properties" className="w-full rounded-xl border border-[#e4eaf0] bg-white py-2 pl-9 pr-3 text-xs outline-none placeholder:text-[#98a2b3] focus:border-[#8acbad]" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-[#e4eaf0] bg-white px-3 py-2 text-xs font-medium text-[#344054]"><option value="all">All statuses</option><option value="checked_in">Checked in</option><option value="confirmed">Upcoming</option><option value="provisional">Provisional</option></select><button type="button" className="grid h-9 w-9 place-items-center rounded-xl border border-[#e4eaf0] bg-white text-[#52657a]" aria-label="Advanced filters"><Filter size={15} /></button></div></div> }

function PropertyLabel({ row }) { return <div className="sticky left-0 z-20 flex h-[78px] items-center gap-2 border-b border-r border-[#e8edf2] bg-white px-3"><span className="h-12 w-12 shrink-0 rounded-lg bg-[#edf3ef] bg-cover bg-center" style={imageStyle(row.propertyCoverImageUrl)} aria-label={row.propertyCoverImageAlt || undefined} /><div className="min-w-0"><p className="truncate text-xs font-semibold text-[#243348]">{row.propertyName}</p><p className="mt-0.5 text-[.68rem] text-[#7a899c]">{row.unitLabel}</p><p className="mt-0.5 text-[.68rem] text-[#7a899c]">{row.maxGuests} guests</p></div></div> }

function BookingBar({ booking }) { const left = `${(booking.start / 7) * 100}%`; const width = `${(booking.span / 7) * 100}%`; return <Link to="/agent/rentals/short-term/bookings" title={`${booking.guestName || 'Guest'}\nCheck-in: ${dateTime(booking.checkInAt)}\nCheck-out: ${dateTime(booking.checkOutAt)}\n${booking.adults + booking.children} guests · ${booking.source || 'direct'}`} className={`absolute top-5 z-10 flex h-9 items-center gap-1.5 overflow-hidden rounded-lg border px-2 text-[.68rem] font-semibold shadow-[0_2px_6px_rgba(15,23,42,.04)] ${bookingTone(booking)}`} style={{ left: `calc(${left} + 4px)`, width: `calc(${width} - 8px)` }}><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-white/80 text-[.56rem]">{(booking.guestName || 'G').slice(0, 1)}</span><span className="truncate">{booking.guestName || 'Guest'}</span><span className="ml-auto hidden shrink-0 rounded-full bg-white/65 px-1.5 py-0.5 text-[.58rem] lg:block">{bookingStatus(booking)}</span></Link> }

export function BookingCalendar({ board, loading, today }) { return <div className="mt-4 overflow-x-auto rounded-xl border border-[#e4ebf0]"><div className="min-w-[1050px]"><div className="grid grid-cols-[220px_repeat(7,minmax(110px,1fr))]"><div className="sticky left-0 z-30 border-b border-r border-[#e8edf2] bg-[#fbfcfd] px-3 py-4 text-xs font-semibold text-[#52657a]">Properties</div>{board.days.map((day) => { const isToday = calendarDateKey(day) === calendarDateKey(today); return <div key={calendarDateKey(day)} className={`border-b border-r border-[#e8edf2] px-2 py-3 text-center ${isToday ? 'border-t-2 border-t-[#13885f] bg-[#f3fbf6]' : 'bg-[#fbfcfd]'}`}><p className={`text-[.65rem] font-semibold uppercase ${isToday ? 'text-[#087a59]' : 'text-[#6c7c91]'}`}>{dayLabel(day)}</p><p className={`mt-1 text-xs font-semibold ${isToday ? 'text-[#087a59]' : 'text-[#344054]'}`}>{dateLabel(day)}</p></div> })}</div>{loading ? <p className="py-12 text-center text-sm text-[#667085]"><Loader2 className="mr-2 inline animate-spin" size={15} />Loading bookings…</p> : board.rows.length ? board.rows.map((row) => <div key={row.id} className="grid grid-cols-[220px_minmax(770px,1fr)]"><PropertyLabel row={row} /><div className="relative h-[78px] border-b border-[#e8edf2]" style={{ backgroundImage: 'linear-gradient(to right, #eef2f5 1px, transparent 1px)', backgroundSize: '14.285714% 100%' }}>{row.bookings.map((booking) => <BookingBar key={booking.id} booking={booking} />)}</div></div>) : <p className="p-10 text-center text-sm text-[#667085]">No enabled short-term properties match these filters.</p>}</div></div> }

export function CalendarListView({ rows }) { const bookings = rows.flatMap((row) => row.bookings).sort((a, b) => new Date(a.checkInAt) - new Date(b.checkInAt)); return <div className="mt-4 divide-y divide-[#edf2f6] rounded-xl border border-[#e4ebf0] px-4">{bookings.length ? bookings.map((booking) => <Link key={booking.id} to="/agent/rentals/short-term/bookings" className="grid grid-cols-[120px_minmax(0,1fr)_auto] items-center gap-3 py-3 hover:bg-[#fbfdfc]"><p className="text-xs font-semibold text-[#51667f]">{dateLabel(new Date(booking.checkInAt))}<span className="mt-0.5 block font-normal text-[#98a2b3]">{dateTime(booking.checkInAt).split(', ')[1]}</span></p><div><p className="text-sm font-semibold text-[#243348]">{booking.propertyName} · {booking.unitLabel}</p><p className="mt-0.5 text-xs text-[#667085]">{booking.guestName || 'Guest'} · check-out {dateLabel(new Date(booking.checkOutAt))}</p></div><ChevronRight size={16} className="text-[#98a2b3]" /></Link>) : <p className="p-10 text-center text-sm text-[#667085]">No bookings match these filters.</p>}</div> }

export function CalendarLegend() { return <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-[#667085]"><div className="flex flex-wrap gap-4"><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#54ba8b]" />Checked in</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#9dc5ff]" />Upcoming</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#f5ad54]" />Check-out due</span></div><span>Updated just now</span></div> }
