-- Rentals Phase 42: approved preview before any import posts to the ledger.
begin;
create table public.rental_financial_import_batches (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete restrict, source_name text not null check(length(btrim(source_name))>0), file_fingerprint text not null check(length(btrim(file_fingerprint))>0), status text not null default 'preview_ready' check(status in ('preview_ready','approved','completed','rejected')), row_count integer not null default 0, valid_row_count integer not null default 0, invalid_row_count integer not null default 0, total_amount numeric(14,2) not null default 0, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), approved_by uuid references auth.users(id) on delete restrict, approved_at timestamptz, posted_by uuid references auth.users(id) on delete restrict, posted_at timestamptz, unique(organisation_id,file_fingerprint)
);
create table public.rental_financial_import_rows (
 id uuid primary key default gen_random_uuid(), batch_id uuid not null references public.rental_financial_import_batches(id) on delete restrict, row_number integer not null, entry_type text not null check(entry_type in ('opening_balance','payment')), tenancy_id uuid references public.rental_tenancies(id) on delete restrict, amount numeric(14,2), effective_date date, payment_reference text, payment_method text, evidence_link text, raw_json jsonb not null default '{}'::jsonb, validation_errors jsonb not null default '[]'::jsonb, status text not null default 'valid' check(status in ('valid','invalid','posted','skipped_duplicate')), posted_entry_id uuid, created_at timestamptz not null default now(), unique(batch_id,row_number)
);
create index rental_financial_import_rows_batch_status_idx on public.rental_financial_import_rows(batch_id,status);
alter table public.rental_financial_import_batches enable row level security; alter table public.rental_financial_import_rows enable row level security;
revoke all on public.rental_financial_import_batches,public.rental_financial_import_rows from anon,authenticated; grant select on public.rental_financial_import_batches,public.rental_financial_import_rows to authenticated;
create policy rental_financial_import_batches_read on public.rental_financial_import_batches for select to authenticated using(exists(select 1 from public.rental_tenancies t join public.rental_properties p on p.organisation_id=rental_financial_import_batches.organisation_id where public.rental_branch_access(p.organisation_id,p.branch_id) limit 1));
create policy rental_financial_import_rows_read on public.rental_financial_import_rows for select to authenticated using(exists(select 1 from public.rental_financial_import_batches b where b.id=batch_id and exists(select 1 from public.rental_tenancies t join public.rental_properties p on p.organisation_id=b.organisation_id where public.rental_branch_access(p.organisation_id,p.branch_id) limit 1)));
create or replace function public.rental_stage_financial_import(p_source_name text,p_fingerprint text,p_rows jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare row_data jsonb; batch_id uuid; org_id uuid; i integer:=0; errors jsonb; valid_count integer:=0; invalid_count integer:=0; total numeric(14,2):=0; entry_type text; amount_value numeric; tenancy_value uuid; date_value date; reference_value text;
begin
 if auth.uid() is null or jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)=0 or jsonb_array_length(p_rows)>1000 or length(btrim(coalesce(p_source_name,'')))=0 or length(btrim(coalesce(p_fingerprint,'')))=0 then raise exception 'Source, fingerprint and 1 to 1000 import rows are required'; end if;
 select p.organisation_id into org_id from public.rental_properties p where public.rental_branch_access(p.organisation_id,p.branch_id) limit 1; if org_id is null then raise exception 'No rental branch access'; end if;
 select id into batch_id from public.rental_financial_import_batches where organisation_id=org_id and file_fingerprint=btrim(p_fingerprint); if batch_id is not null then return jsonb_build_object('batch_id',batch_id,'idempotent',true); end if;
 insert into public.rental_financial_import_batches(organisation_id,source_name,file_fingerprint,created_by) values(org_id,btrim(p_source_name),btrim(p_fingerprint),auth.uid()) returning id into batch_id;
 for row_data in select value from jsonb_array_elements(p_rows) loop i:=i+1; errors:='[]'::jsonb; entry_type:=lower(coalesce(row_data->>'entry_type','')); amount_value:=null; date_value:=null; reference_value:=nullif(btrim(coalesce(row_data->>'payment_reference','')),''); begin amount_value:=nullif(row_data->>'amount','')::numeric; exception when invalid_text_representation then errors:=errors||jsonb_build_array('Invalid amount'); end; begin date_value:=nullif(row_data->>'effective_date','')::date; exception when invalid_datetime_format then errors:=errors||jsonb_build_array('Invalid effective date'); end; begin tenancy_value:=nullif(row_data->>'tenancy_id','')::uuid; exception when invalid_text_representation then tenancy_value:=null; errors:=errors||jsonb_build_array('Invalid tenancy id'); end;
 if entry_type not in ('opening_balance','payment') then errors:=errors||jsonb_build_array('entry_type must be opening_balance or payment'); end if; if amount_value is null or amount_value<=0 or amount_value<>round(amount_value,2) then errors:=errors||jsonb_build_array('Amount must be a positive two-decimal value'); end if; if date_value is null then errors:=errors||jsonb_build_array('effective_date is required'); end if; if tenancy_value is null or not exists(select 1 from public.rental_tenancies t join public.rental_properties p on p.id=t.property_id where t.id=tenancy_value and t.organisation_id=org_id and public.rental_branch_access(p.organisation_id,p.branch_id)) then errors:=errors||jsonb_build_array('Tenancy is not in your rental scope'); end if; if entry_type='payment' and (reference_value is null or length(coalesce(row_data->>'evidence_link',''))=0 or coalesce(row_data->>'payment_method','') not in ('bank_transfer','cash','card','other')) then errors:=errors||jsonb_build_array('Payment needs reference, method and evidence link'); end if;
 insert into public.rental_financial_import_rows(batch_id,row_number,entry_type,tenancy_id,amount,effective_date,payment_reference,payment_method,evidence_link,raw_json,validation_errors,status) values(batch_id,i,entry_type,tenancy_value,amount_value,date_value,reference_value,row_data->>'payment_method',row_data->>'evidence_link',row_data,errors,case when jsonb_array_length(errors)=0 then 'valid' else 'invalid' end); if jsonb_array_length(errors)=0 then valid_count:=valid_count+1; total:=total+amount_value; else invalid_count:=invalid_count+1; end if; end loop;
 update public.rental_financial_import_batches set row_count=i,valid_row_count=valid_count,invalid_row_count=invalid_count,total_amount=total where id=batch_id; return jsonb_build_object('batch_id',batch_id,'idempotent',false,'row_count',i,'valid_row_count',valid_count,'invalid_row_count',invalid_count,'total_amount',total);
end; $$;
create or replace function public.rental_approve_financial_import(p_batch_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare b public.rental_financial_import_batches%rowtype; begin select * into b from public.rental_financial_import_batches where id=p_batch_id for update; if not found or not public.rental_financial_manager_authorized(b.organisation_id) or b.created_by=auth.uid() then raise exception 'A different authorized manager must approve this import'; end if; if b.status<>'preview_ready' or b.invalid_row_count>0 or b.valid_row_count=0 then raise exception 'Only a clean non-empty preview can be approved'; end if; update public.rental_financial_import_batches set status='approved',approved_by=auth.uid(),approved_at=now() where id=b.id; return jsonb_build_object('batch_id',b.id,'status','approved'); end; $$;
create or replace function public.rental_post_financial_import(p_batch_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare b public.rental_financial_import_batches%rowtype; r public.rental_financial_import_rows%rowtype; entry_id uuid; posted integer:=0; skipped integer:=0; begin select * into b from public.rental_financial_import_batches where id=p_batch_id for update; if not found or not public.rental_financial_manager_authorized(b.organisation_id) then raise exception 'Manager authorization is required'; end if; if b.status='completed' then return jsonb_build_object('batch_id',b.id,'idempotent',true); end if; if b.status<>'approved' then raise exception 'An approved preview is required before posting'; end if; for r in select * from public.rental_financial_import_rows where batch_id=b.id and status='valid' order by row_number for update loop if r.entry_type='opening_balance' then insert into public.rental_financial_charges(organisation_id,tenancy_id,currency_code,charge_type,effective_date,due_date,amount,description,source_key,created_by) values(b.organisation_id,r.tenancy_id,'ZAR','opening_balance',r.effective_date,r.effective_date,r.amount,'Imported opening balance',concat('financial-import:',b.id::text,':',r.row_number),auth.uid()) on conflict(tenancy_id,source_key) do nothing returning id into entry_id; else insert into public.rental_financial_payments(organisation_id,tenancy_id,currency_code,received_date,amount,payment_reference,payment_method,evidence_link,created_by) values(b.organisation_id,r.tenancy_id,'ZAR',r.effective_date,r.amount,r.payment_reference,r.payment_method,r.evidence_link,auth.uid()) on conflict(organisation_id,payment_reference) do nothing returning id into entry_id; end if; if entry_id is null then update public.rental_financial_import_rows set status='skipped_duplicate' where id=r.id; skipped:=skipped+1; else update public.rental_financial_import_rows set status='posted',posted_entry_id=entry_id where id=r.id; posted:=posted+1; end if; entry_id:=null; end loop; update public.rental_financial_import_batches set status='completed',posted_by=auth.uid(),posted_at=now() where id=b.id; return jsonb_build_object('batch_id',b.id,'posted_count',posted,'skipped_duplicate_count',skipped,'total_amount',b.total_amount); end; $$;
revoke execute on function public.rental_stage_financial_import(text,text,jsonb),public.rental_approve_financial_import(uuid),public.rental_post_financial_import(uuid) from public,anon; grant execute on function public.rental_stage_financial_import(text,text,jsonb),public.rental_approve_financial_import(uuid),public.rental_post_financial_import(uuid) to authenticated;
commit;
