begin;

-- Keep the shared journey catalogue aligned with the Work tab's current
-- transfer definitions, including client visibility and professional copy.
-- Historical task rows and their saved outcomes remain untouched.
with current_definitions(lane_key, step_key, definition) as (
  values
    ('transfer', 'agricultural_consent_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"agricultural_consent_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Agricultural Land Consent","description":"Verify whether statutory consent or an exception applies and retain the evidence."},"client":null}'::jsonb),
    ('transfer', 'body_corporate_levy_clearance_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"body_corporate_levy_clearance_review","ownerRole":"transfer_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Review Body-Corporate Clearance","description":"For sectional title, review the body-corporate clearance, issuer and validity."},"client":{"title":"Property transfer update","description":"Property transfer is currently at: Review Body-Corporate Clearance."}}'::jsonb),
    ('transfer', 'buyer_party_capacity_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"buyer_party_capacity_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Resolve Each Buyer Capacity","description":"Record a separate identity, beneficial ownership, representative, marital and signing authority decision for every buyer and applicable signatory."},"client":null}'::jsonb),
    ('transfer', 'cash_funding_source_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"cash_funding_source_review","ownerRole":"transfer_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Review Cash Funding Source","description":"For cash or hybrid funding, identify the buyer funding source and review its supporting evidence before accepting payment security."},"client":{"title":"Property transfer update","description":"Property transfer is currently at: Review Cash Funding Source."}}'::jsonb),
    ('transfer', 'court_order_transfer_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"court_order_transfer_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Court Order or Divorce Transfer","description":"Verify the order, parties, implementation authority and required transfer instrument."},"client":null}'::jsonb),
    ('transfer', 'estate_authority_transfer_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"estate_authority_transfer_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Estate Authority and Transfer","description":"Verify the executor or representative authority and the applicable deceased-estate transfer path."},"client":null}'::jsonb),
    ('transfer', 'going_concern_zero_rate_verified', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"going_concern_zero_rate_verified","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Verify Going-Concern Zero Rate","description":"Review the written going-concern agreement and the facts supporting the claimed zero rate."},"client":null}'::jsonb),
    ('transfer', 'hoa_clearance_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"hoa_clearance_review","ownerRole":"transfer_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Review HOA Clearance","description":"Where an HOA applies, review the HOA clearance, issuer and validity."},"client":{"title":"Property transfer update","description":"Property transfer is currently at: Review HOA Clearance."}}'::jsonb),
    ('transfer', 'insolvency_authority_transfer_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"insolvency_authority_transfer_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Insolvency Authority and Transfer","description":"Verify the trustee or liquidator authority and the applicable transfer path."},"client":null}'::jsonb),
    ('transfer', 'matter_closed', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"matter_closed","ownerRole":"transfer_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":false,"professional":{"title":"Matter Closed","description":"Close the file after financial close-out, recipient-scoped registration communication, and any linked attorney lanes are complete."},"client":null}'::jsonb),
    ('transfer', 'non_resident_seller_applicability_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"non_resident_seller_applicability_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Each Non-Resident Seller","description":"Resolve withholding applicability independently for every potentially non-resident seller and seller type."},"client":null}'::jsonb),
    ('transfer', 'non_resident_seller_directive_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"non_resident_seller_directive_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Verify SARS Directive","description":"Review the issued directive and its reference for each seller relying on one."},"client":null}'::jsonb),
    ('transfer', 'non_resident_seller_withholding_payment_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"non_resident_seller_withholding_payment_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Verify Non-Resident Withholding","description":"Review withholding decision, remittance and proof for each applicable seller."},"client":null}'::jsonb),
    ('transfer', 'ordinary_vat_basis_verified', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"ordinary_vat_basis_verified","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Verify Ordinary VAT Basis","description":"Verify vendor status, enterprise supply, agreement treatment and VAT evidence."},"client":null}'::jsonb),
    ('transfer', 'other_specialist_execution_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"other_specialist_execution_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Other Specialist Route","description":"Verify the specialist decision and evidence for the exceptional route."},"client":null}'::jsonb),
    ('transfer', 'party_capacity_specialist_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"party_capacity_specialist_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Specialist Party Capacity Hold","description":"Hold the ordinary transfer route for an estate, insolvency, unknown legal type or other exceptional capacity until a reviewed specialist route is available."},"client":null}'::jsonb),
    ('transfer', 'post_registration_closeout_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"post_registration_closeout_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Final Accounts","description":"Review the final account, proceeds, refunds, fees, and settlement position before closing the file."},"client":null}'::jsonb),
    ('transfer', 'property_conditions_applicability_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"property_conditions_applicability_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Classify Property Conditions","description":"Decide whether title restrictions and compliance certificates apply to this property and agreement."},"client":null}'::jsonb),
    ('transfer', 'seller_party_capacity_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"seller_party_capacity_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Resolve Each Seller Capacity","description":"Record a separate identity, beneficial ownership, representative, marital and signing authority decision for every seller and applicable signatory."},"client":null}'::jsonb),
    ('transfer', 'share_block_instrument_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"share_block_instrument_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Share Block Instrument","description":"Verify the legal instrument and whether an ordinary deeds transfer is appropriate."},"client":null}'::jsonb),
    ('transfer', 'specialist_classification_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"specialist_classification_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Classify Specialist Routes","description":"Record the attorney decision, specialist owner, instrument and evidence for every exceptional route."},"client":null}'::jsonb),
    ('transfer', 'title_conditions_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"title_conditions_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Review Title Conditions","description":"Review applicable title restrictions, servitudes or conditions before lodgement."},"client":null}'::jsonb),
    ('transfer', 'transfer_duty_exemption_basis_verified', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"transfer_duty_exemption_basis_verified","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Verify Claimed Exemption","description":"Record the specific statutory exemption and review its supporting proof."},"client":null}'::jsonb),
    ('transfer', 'unusual_title_resolution_review', '{"processKey":"transfer","processLabel":"Property transfer","stepKey":"unusual_title_resolution_review","ownerRole":"transfer_attorney","defaultVisibility":"internal","clientVisibleAllowed":false,"professional":{"title":"Resolve Unusual Title Conditions","description":"Verify the restriction or servitude, consents and registrable instrument."},"client":null}'::jsonb)
)
update journey_private.task_catalog as catalogue
set definition = current_definitions.definition
from current_definitions
where catalogue.lane_key = current_definitions.lane_key
  and catalogue.step_key = current_definitions.step_key;


-- The new bond and cancellation handoff tasks share the same catalogue
-- contract; reconcile their display and audience metadata as well.
with current_definitions(lane_key, step_key, definition) as (
  values
    ('bond', 'bond_lodgement_instructions_confirmed', '{"processKey":"bond","processLabel":"Bond registration","stepKey":"bond_lodgement_instructions_confirmed","ownerRole":"bond_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Bank Lodgement Instructions Confirmed","description":"Confirm the bank instruction to lodge, its current conditions and the linked transfer lodgement arrangements."},"client":{"title":"Bond registration update","description":"Bond registration is currently at: Bank Lodgement Instructions Confirmed."}}'::jsonb),
    ('cancellation', 'cancellation_guarantee_allocation_review', '{"processKey":"cancellation","processLabel":"Bond cancellation","stepKey":"cancellation_guarantee_allocation_review","ownerRole":"cancellation_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Review Settlement Guarantee Allocation","description":"Reconcile the bank settlement figures with each guarantee and the balance payable to the seller."},"client":{"title":"Bond cancellation update","description":"Bond cancellation is currently at: Review Settlement Guarantee Allocation."}}'::jsonb),
    ('cancellation', 'cancellation_consent_confirmed', '{"processKey":"cancellation","processLabel":"Bond cancellation","stepKey":"cancellation_consent_confirmed","ownerRole":"cancellation_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Bondholder Consent Confirmed","description":"Confirm the bondholder has consented to cancellation or release on the bank instruction and guarantees."},"client":{"title":"Bond cancellation update","description":"Bond cancellation is currently at: Bondholder Consent Confirmed."}}'::jsonb),
    ('cancellation', 'cancellation_simultaneous_lodgement_confirmed', '{"processKey":"cancellation","processLabel":"Bond cancellation","stepKey":"cancellation_simultaneous_lodgement_confirmed","ownerRole":"cancellation_attorney","defaultVisibility":"professional_shared","clientVisibleAllowed":true,"professional":{"title":"Simultaneous Lodgement Confirmed","description":"Agree the linked transfer, cancellation and new bond lodgement arrangement where applicable."},"client":{"title":"Bond cancellation update","description":"Bond cancellation is currently at: Simultaneous Lodgement Confirmed."}}'::jsonb)
)
update journey_private.task_catalog as catalogue
set definition = current_definitions.definition
from current_definitions
where catalogue.lane_key = current_definitions.lane_key
  and catalogue.step_key = current_definitions.step_key;


with current_definitions(lane_key, step_key, definition) as (
  values
    ('cancellation', 'notice_period_captured', '{"processKey":"cancellation","processLabel":"Bond cancellation","stepKey":"notice_period_captured","ownerRole":"cancellation_attorney","defaultVisibility":"internal","clientVisibleAllowed":true,"professional":{"title":"Bond Cancellation Notice Status Captured","description":"Capture the lender-specific notice period, date and any early-settlement or penalty position."},"client":{"title":"Bond cancellation update","description":"Bond cancellation is currently at: Bond Cancellation Notice Status Captured."}}'::jsonb)
)
update journey_private.task_catalog as catalogue
set definition = current_definitions.definition
from current_definitions
where catalogue.lane_key = current_definitions.lane_key
  and catalogue.step_key = current_definitions.step_key;

commit;
