-- Phase 66: manual lease-signing controls. No envelope, signer session or provider callback exists here.
create table public.rental_signing_tasks(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),tenancy_id uuid not null references public.rental_tenancies(id),lease_version_id uuid,signer_name text not null,signer_reference text not null,status text not null default 'awaiting_signature' check(status in('awaiting_signature','reminded','signed','cancelled','expired')),due_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),completed_at timestamptz,unique(tenancy_id,lease_version_id,signer_reference));
create table public.rental_signing_reminders(id uuid primary key default gen_random_uuid(),task_id uuid not null references public.rental_signing_tasks(id) on delete cascade,reminded_by uuid not null references auth.users(id),note text,created_at timestamptz not null default now());
create table public.rental_signing_evidence(id uuid primary key default gen_random_uuid(),task_id uuid not null unique references public.rental_signing_tasks(id) on delete cascade,document_link text not null,verified_by uuid not null references auth.users(id),verified_at timestamptz not null default now(),note text);
create index rental_signing_tasks_queue_idx on public.rental_signing_tasks(organisation_id,status,due_at);create index rental_signing_tasks_created_by_idx on public.rental_signing_tasks(created_by);create index rental_signing_reminders_task_idx on public.rental_signing_reminders(task_id);create index rental_signing_reminders_by_idx on public.rental_signing_reminders(reminded_by);create index rental_signing_evidence_verified_by_idx on public.rental_signing_evidence(verified_by);
alter table public.rental_signing_tasks enable row level security;alter table public.rental_signing_reminders enable row level security;alter table public.rental_signing_evidence enable row level security;
create policy "rental_signing_tasks_manager_read" on public.rental_signing_tasks for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));create policy "rental_signing_reminders_manager_read" on public.rental_signing_reminders for select to authenticated using(exists(select 1 from public.rental_signing_tasks t where t.id=task_id and public.rental_financial_manager_authorized(t.organisation_id)));create policy "rental_signing_evidence_manager_read" on public.rental_signing_evidence for select to authenticated using(exists(select 1 from public.rental_signing_tasks t where t.id=task_id and public.rental_financial_manager_authorized(t.organisation_id)));
create or replace function public.rental_record_manual_lease_signing(p_task_id uuid,p_document_link text,p_note text default null)returns jsonb language plpgsql security definer set search_path='' as $$ declare v_org uuid;begin select organisation_id into v_org from public.rental_signing_tasks where id=p_task_id for update;if auth.uid() is null or not found or not public.rental_financial_manager_authorized(v_org) or length(btrim(coalesce(p_document_link,'')))=0 then raise exception 'Valid signed evidence is required';end if;insert into public.rental_signing_evidence(task_id,document_link,verified_by,note)values(p_task_id,btrim(p_document_link),auth.uid(),nullif(btrim(coalesce(p_note,'')),'')) on conflict(task_id)do update set document_link=excluded.document_link,verified_by=excluded.verified_by,verified_at=now(),note=excluded.note;update public.rental_signing_tasks set status='signed',completed_at=now() where id=p_task_id;return jsonb_build_object('task_id',p_task_id,'status','signed','automatic',false);end $$;
create or replace function public.rental_send_manual_signing_reminder(p_task_id uuid,p_note text default null)returns jsonb language plpgsql security definer set search_path='' as $$ declare v_org uuid;begin select organisation_id into v_org from public.rental_signing_tasks where id=p_task_id for update;if auth.uid() is null or not found or not public.rental_financial_manager_authorized(v_org) then raise exception 'Not authorized';end if;if exists(select 1 from public.rental_signing_tasks where id=p_task_id and status='signed') then raise exception 'Signed task cannot be reminded';end if;insert into public.rental_signing_reminders(task_id,reminded_by,note)values(p_task_id,auth.uid(),nullif(btrim(coalesce(p_note,'')),''));update public.rental_signing_tasks set status='reminded' where id=p_task_id;return jsonb_build_object('task_id',p_task_id,'sent',false,'status','reminded');end $$;
create or replace function public.rental_get_signing_operations(p_org uuid)returns jsonb language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org)then raise exception 'Not authorized';end if;return jsonb_build_object('tasks',coalesce((select jsonb_agg(to_jsonb(x)order by x.due_at)from(select * from public.rental_signing_tasks where organisation_id=p_org order by due_at nulls last limit 100)x),'[]'::jsonb));end $$;
revoke all on function public.rental_record_manual_lease_signing(uuid,text,text)from public,anon;revoke all on function public.rental_send_manual_signing_reminder(uuid,text)from public,anon;revoke all on function public.rental_get_signing_operations(uuid)from public,anon;grant execute on function public.rental_record_manual_lease_signing(uuid,text,text)to authenticated;grant execute on function public.rental_send_manual_signing_reminder(uuid,text)to authenticated;grant execute on function public.rental_get_signing_operations(uuid)to authenticated;
