-- Phase 72: privacy workflow records. Destructive deletion/anonymisation is
-- intentionally queued for an authorised review, never performed by a browser RPC.
create table public.rental_privacy_requests(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),subject_type text not null,subject_id uuid not null,request_type text not null check(request_type in('access','retention_review','anonymisation_review')),status text not null default 'open' check(status in('open','on_hold','approved','rejected','completed')),legal_hold boolean not null default false,requested_by uuid not null references auth.users(id),reviewed_by uuid references auth.users(id),note text,created_at timestamptz not null default now(),reviewed_at timestamptz);
create table public.rental_privileged_audit_events(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),event_key text not null,subject_type text,subject_id uuid,actor_id uuid not null references auth.users(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index rental_privacy_requests_org_status_idx on public.rental_privacy_requests(organisation_id,status,created_at desc);create index rental_privacy_requests_requested_by_idx on public.rental_privacy_requests(requested_by);create index rental_privacy_requests_reviewed_by_idx on public.rental_privacy_requests(reviewed_by);create index rental_privileged_audit_org_created_idx on public.rental_privileged_audit_events(organisation_id,created_at desc);create index rental_privileged_audit_actor_idx on public.rental_privileged_audit_events(actor_id);
alter table public.rental_privacy_requests enable row level security;alter table public.rental_privileged_audit_events enable row level security;create policy "rental_privacy_requests_manager_read" on public.rental_privacy_requests for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));create policy "rental_privileged_audit_manager_read" on public.rental_privileged_audit_events for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));
create or replace function public.rental_request_privacy_review(p_org uuid,p_subject_type text,p_subject_id uuid,p_request_type text,p_note text default null)returns jsonb language plpgsql security definer set search_path='' as $$ declare v_id uuid;begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org) or length(btrim(coalesce(p_subject_type,'')))=0 or p_subject_id is null or p_request_type not in('access','retention_review','anonymisation_review')then raise exception 'Invalid privacy request';end if;insert into public.rental_privacy_requests(organisation_id,subject_type,subject_id,request_type,requested_by,note)values(p_org,btrim(p_subject_type),p_subject_id,p_request_type,auth.uid(),nullif(btrim(coalesce(p_note,'')),''))returning id into v_id;insert into public.rental_privileged_audit_events(organisation_id,event_key,subject_type,subject_id,actor_id)values(p_org,'privacy_request_created',p_subject_type,p_subject_id,auth.uid());return jsonb_build_object('request_id',v_id,'status','open','destructive_action',false);end $$;
create or replace function public.rental_get_privacy_operations(p_org uuid)returns jsonb language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org)then raise exception 'Not authorized';end if;return jsonb_build_object('requests',coalesce((select jsonb_agg(to_jsonb(x)order by x.created_at desc)from(select * from public.rental_privacy_requests where organisation_id=p_org order by created_at desc limit 100)x),'[]'::jsonb),'audit',coalesce((select jsonb_agg(to_jsonb(x)order by x.created_at desc)from(select * from public.rental_privileged_audit_events where organisation_id=p_org order by created_at desc limit 100)x),'[]'::jsonb));end $$;
revoke all on function public.rental_request_privacy_review(uuid,text,uuid,text,text)from public,anon;revoke all on function public.rental_get_privacy_operations(uuid)from public,anon;grant execute on function public.rental_request_privacy_review(uuid,text,uuid,text,text)to authenticated;grant execute on function public.rental_get_privacy_operations(uuid)to authenticated;
