begin;

create table if not exists public.conveyancer_operational_policies (
 id uuid primary key default gen_random_uuid(),record_id uuid not null default gen_random_uuid(),revision integer not null check(revision>0),scope text not null check(scope in('global','firm')),organisation_id uuid references public.organisations(id) on delete restrict,attorney_firm_id uuid references public.attorney_firms(id) on delete restrict,window_minutes integer not null check(window_minutes between 5 and 1440),max_queue_depth integer not null check(max_queue_depth>=0),max_oldest_queue_seconds integer not null check(max_oldest_queue_seconds>=30),min_success_rate_percent numeric(5,2) not null check(min_success_rate_percent between 0 and 100),max_dead_letters integer not null check(max_dead_letters>=0),max_reconciliation_required integer not null check(max_reconciliation_required>=0),max_inbound_awaiting_review integer not null check(max_inbound_awaiting_review>=0),max_inbound_age_seconds integer not null check(max_inbound_age_seconds>=60),snapshot_freshness_seconds integer not null check(snapshot_freshness_seconds between 60 and 3600),reason text not null,contract_version text not null default 'conveyancer_operational_assurance_p8_v1',fingerprint text not null check(length(trim(fingerprint))>=8),created_by uuid not null,created_at timestamptz not null default now(),unique(record_id,revision),check((scope='global' and organisation_id is null and attorney_firm_id is null) or(scope='firm' and organisation_id is not null and attorney_firm_id is not null))
);
create table if not exists public.conveyancer_operational_signals (
 id uuid primary key default gen_random_uuid(),organisation_id uuid references public.organisations(id) on delete restrict,attorney_firm_id uuid references public.attorney_firms(id) on delete restrict,integration_profile_id uuid,signal_type text not null,severity text not null check(severity in('info','warning','critical')),numeric_value numeric,detail jsonb not null default '{}'::jsonb check(jsonb_typeof(detail)='object' and octet_length(detail::text)<=8192),occurred_at timestamptz not null default now(),check((organisation_id is null and attorney_firm_id is null)or(organisation_id is not null and attorney_firm_id is not null))
);
create table if not exists public.conveyancer_operational_snapshots (
 id uuid primary key default gen_random_uuid(),scope text not null check(scope in('global','firm')),organisation_id uuid references public.organisations(id) on delete restrict,attorney_firm_id uuid references public.attorney_firms(id) on delete restrict,health text not null check(health in('pass','warning','fail')),metrics jsonb not null check(jsonb_typeof(metrics)='object'),blockers text[] not null default '{}'::text[],warnings text[] not null default '{}'::text[],policy_fingerprint text,contract_version text not null default 'conveyancer_operational_assurance_p8_v1',captured_at timestamptz not null default now(),check((scope='global' and organisation_id is null and attorney_firm_id is null)or(scope='firm' and organisation_id is not null and attorney_firm_id is not null))
);
create table if not exists public.conveyancer_operational_alerts (
 id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id) on delete restrict,attorney_firm_id uuid not null references public.attorney_firms(id) on delete restrict,alert_key text not null,severity text not null check(severity in('warning','critical')),status text not null check(status in('open','acknowledged','resolved')),summary text not null,snapshot_id uuid references public.conveyancer_operational_snapshots(id) on delete restrict,opened_at timestamptz not null default now(),acknowledged_by uuid,acknowledged_at timestamptz,resolved_at timestamptz,updated_at timestamptz not null default now(),unique(attorney_firm_id,alert_key)
);
create table if not exists public.conveyancer_provider_incidents (
 id uuid primary key default gen_random_uuid(),record_id uuid not null default gen_random_uuid(),revision integer not null check(revision>0),scope text not null check(scope in('global','organisation','firm','profile')),organisation_id uuid references public.organisations(id) on delete restrict,attorney_firm_id uuid references public.attorney_firms(id) on delete restrict,integration_profile_id uuid,severity text not null check(severity in('sev1','sev2','sev3','sev4')),status text not null check(status in('open','mitigating','monitoring','resolved')),title text not null,summary text not null,owner_user_id uuid not null,started_at timestamptz not null,resolved_at timestamptz,contract_version text not null default 'conveyancer_operational_assurance_p8_v1',fingerprint text not null check(length(trim(fingerprint))>=8),created_by uuid not null,created_at timestamptz not null default now(),unique(record_id,revision)
);
create table if not exists public.conveyancer_provider_kill_switches (
 id uuid primary key default gen_random_uuid(),record_id uuid not null default gen_random_uuid(),revision integer not null check(revision>0),scope text not null check(scope in('global','organisation','firm','profile')),organisation_id uuid references public.organisations(id) on delete restrict,attorney_firm_id uuid references public.attorney_firms(id) on delete restrict,integration_profile_id uuid,direction text not null check(direction in('all','inbound','outbound')),enabled boolean not null,reason text not null,incident_record_id uuid,expires_at timestamptz,contract_version text not null default 'conveyancer_operational_assurance_p8_v1',fingerprint text not null check(length(trim(fingerprint))>=8),created_by uuid not null,created_at timestamptz not null default now(),unique(record_id,revision),check((scope='global' and organisation_id is null and attorney_firm_id is null and integration_profile_id is null)or(scope='organisation' and organisation_id is not null and attorney_firm_id is null and integration_profile_id is null)or(scope='firm' and organisation_id is not null and attorney_firm_id is not null and integration_profile_id is null)or(scope='profile' and organisation_id is not null and attorney_firm_id is not null and integration_profile_id is not null))
);
create table if not exists public.conveyancer_release_candidates (
 id uuid primary key default gen_random_uuid(),release_id text not null unique,release_version text not null,target_environment text not null check(target_environment in('staging','production')),rollout_mode text not null check(rollout_mode in('pilot','live')),commit_sha text not null, migration_from text,migration_to text,artifact_reference text not null,artifact_hash text not null,rollback_reference text not null,rollback_hash text not null,pilot_transaction_ids uuid[] not null default '{}'::uuid[],evidence jsonb not null check(jsonb_typeof(evidence)='object'),contract_version text not null default 'conveyancer_operational_assurance_p8_v1',fingerprint text not null check(length(trim(fingerprint))>=8),created_by uuid not null,created_at timestamptz not null default now()
);
create table if not exists public.conveyancer_release_approvals (
 id uuid primary key default gen_random_uuid(),release_candidate_id uuid not null references public.conveyancer_release_candidates(id) on delete restrict,approver_role text not null check(approver_role in('operations','security','legal')),decision text not null check(decision in('approved','rejected')),reason text not null,approved_by uuid not null,approved_at timestamptz not null default now(),unique(release_candidate_id,approver_role),unique(release_candidate_id,approved_by)
);
create table if not exists public.conveyancer_release_events (
 id uuid primary key default gen_random_uuid(),release_candidate_id uuid not null references public.conveyancer_release_candidates(id) on delete restrict,event_type text not null check(event_type in('submitted','activation_authorised','activation_blocked','activated','rolled_back')),snapshot_id uuid references public.conveyancer_operational_snapshots(id) on delete restrict,reason text not null,authorisation_expires_at timestamptz,metadata jsonb not null default '{}'::jsonb check(jsonb_typeof(metadata)='object' and octet_length(metadata::text)<=8192),created_by uuid not null,created_at timestamptz not null default now()
);

alter table public.conveyancer_provider_incidents
  add constraint conveyancer_provider_incidents_scope_binding_check check (
    (scope='global' and organisation_id is null and attorney_firm_id is null and integration_profile_id is null)
    or (scope='organisation' and organisation_id is not null and attorney_firm_id is null and integration_profile_id is null)
    or (scope='firm' and organisation_id is not null and attorney_firm_id is not null and integration_profile_id is null)
    or (scope='profile' and organisation_id is not null and attorney_firm_id is not null and integration_profile_id is not null)
  );

create index if not exists conveyancer_operational_snapshots_scope_idx on public.conveyancer_operational_snapshots(scope,organisation_id,attorney_firm_id,captured_at desc);create index if not exists conveyancer_operational_signals_scope_idx on public.conveyancer_operational_signals(organisation_id,attorney_firm_id,occurred_at desc);create index if not exists conveyancer_incidents_scope_idx on public.conveyancer_provider_incidents(organisation_id,attorney_firm_id,status,created_at desc);create index if not exists conveyancer_kill_switch_scope_idx on public.conveyancer_provider_kill_switches(scope,organisation_id,attorney_firm_id,integration_profile_id,direction,revision desc);
create unique index if not exists conveyancer_release_single_activation_idx on public.conveyancer_release_events(release_candidate_id) where event_type='activated';

do $$ declare table_name text; begin foreach table_name in array array['conveyancer_operational_policies','conveyancer_operational_signals','conveyancer_operational_snapshots','conveyancer_operational_alerts','conveyancer_provider_incidents','conveyancer_provider_kill_switches','conveyancer_release_candidates','conveyancer_release_approvals','conveyancer_release_events'] loop execute format('alter table public.%I enable row level security',table_name);execute format('revoke all on public.%I from anon,authenticated,service_role',table_name);end loop;end $$;
create policy conveyancer_operational_policy_read on public.conveyancer_operational_policies for select to authenticated using(public.bridge_is_platform_admin() or(scope='firm' and public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,null::uuid)));create policy conveyancer_operational_snapshot_read on public.conveyancer_operational_snapshots for select to authenticated using(public.bridge_is_platform_admin() or(scope='firm' and public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,null::uuid)));create policy conveyancer_operational_alert_read on public.conveyancer_operational_alerts for select to authenticated using(public.bridge_is_platform_admin() or public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,null::uuid));create policy conveyancer_incident_read on public.conveyancer_provider_incidents for select to authenticated using(public.bridge_is_platform_admin() or(organisation_id is not null and attorney_firm_id is not null and public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,null::uuid)));create policy conveyancer_kill_switch_read on public.conveyancer_provider_kill_switches for select to authenticated using(public.bridge_is_platform_admin() or(scope in('firm','profile') and public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,null::uuid)));create policy conveyancer_release_read on public.conveyancer_release_candidates for select to authenticated using(public.bridge_is_platform_admin());create policy conveyancer_release_approval_read on public.conveyancer_release_approvals for select to authenticated using(public.bridge_is_platform_admin());create policy conveyancer_release_event_read on public.conveyancer_release_events for select to authenticated using(public.bridge_is_platform_admin());
grant select on public.conveyancer_operational_policies,public.conveyancer_operational_snapshots,public.conveyancer_operational_alerts,public.conveyancer_provider_incidents,public.conveyancer_provider_kill_switches,public.conveyancer_release_candidates,public.conveyancer_release_approvals,public.conveyancer_release_events to authenticated,service_role;grant select on public.conveyancer_operational_signals to service_role;
do $$ declare table_name text;begin foreach table_name in array array['conveyancer_operational_policies','conveyancer_operational_signals','conveyancer_operational_snapshots','conveyancer_provider_incidents','conveyancer_provider_kill_switches','conveyancer_release_candidates','conveyancer_release_approvals','conveyancer_release_events'] loop execute format('drop trigger if exists %I on public.%I',table_name||'_immutable',table_name);execute format('create trigger %I before update or delete on public.%I for each row execute function public.bridge_conveyancer_reject_mutation()',table_name||'_immutable',table_name);end loop;end $$;

create or replace function public.bridge_conveyancer_provider_operation_allowed(p_organisation_id uuid,p_attorney_firm_id uuid,p_profile_id uuid,p_direction text)returns boolean language sql stable security definer set search_path=public as $$
 with latest as(select distinct on(record_id)* from public.conveyancer_provider_kill_switches order by record_id,revision desc)
 select not exists(select 1 from latest where enabled and(expires_at is null or expires_at>now())and(direction='all'or direction=p_direction)and(scope='global'or(scope='organisation'and organisation_id=p_organisation_id)or(scope='firm'and organisation_id=p_organisation_id and attorney_firm_id=p_attorney_firm_id)or(scope='profile'and organisation_id=p_organisation_id and attorney_firm_id=p_attorney_firm_id and integration_profile_id=p_profile_id)))
$$;

create or replace function public.bridge_set_conveyancer_operational_policy(payload jsonb)returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_scope text:=lower(payload->>'scope');v_org uuid;v_firm uuid;v_record uuid;v_revision integer;v_id uuid;
begin if v_user is null then raise exception 'Authentication required.' using errcode='42501';end if;begin v_org:=nullif(payload->>'organisationId','')::uuid;v_firm:=nullif(payload->>'attorneyFirmId','')::uuid;exception when invalid_text_representation then raise exception 'P8 policy identity invalid.' using errcode='22023';end;
 if not public.bridge_is_platform_admin() and not(v_scope='firm'and public.attorney_user_is_firm_admin(v_firm)and exists(select 1 from public.attorney_firms where id=v_firm and organisation_id=v_org))then raise exception 'P8 policy authority required.' using errcode='42501';end if;if v_scope not in('global','firm')or(v_scope='global'and not public.bridge_is_platform_admin())or coalesce(payload->>'version','')<>'conveyancer_operational_assurance_p8_v1'or trim(coalesce(payload->>'reason',''))=''or length(trim(coalesce(payload->>'fingerprint','')))<8 then raise exception 'P8 policy invalid.' using errcode='22023';end if;
 select record_id,revision+1 into v_record,v_revision from public.conveyancer_operational_policies where scope=v_scope and organisation_id is not distinct from v_org and attorney_firm_id is not distinct from v_firm order by revision desc limit 1;
 insert into public.conveyancer_operational_policies(record_id,revision,scope,organisation_id,attorney_firm_id,window_minutes,max_queue_depth,max_oldest_queue_seconds,min_success_rate_percent,max_dead_letters,max_reconciliation_required,max_inbound_awaiting_review,max_inbound_age_seconds,snapshot_freshness_seconds,reason,fingerprint,created_by)values(coalesce(v_record,gen_random_uuid()),coalesce(v_revision,1),v_scope,v_org,v_firm,(payload->>'windowMinutes')::integer,(payload->>'maxQueueDepth')::integer,(payload->>'maxOldestQueueSeconds')::integer,(payload->>'minSuccessRatePercent')::numeric,(payload->>'maxDeadLetters')::integer,(payload->>'maxReconciliationRequired')::integer,(payload->>'maxInboundAwaitingReview')::integer,(payload->>'maxInboundAgeSeconds')::integer,(payload->>'snapshotFreshnessSeconds')::integer,payload->>'reason',payload->>'fingerprint',v_user)returning id into v_id;return jsonb_build_object('ok',true,'id',v_id,'revision',coalesce(v_revision,1));end $$;

create or replace function public.bridge_set_conveyancer_provider_kill_switch(payload jsonb)returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_scope text:=lower(payload->>'scope');v_org uuid;v_firm uuid;v_profile uuid;v_record uuid;v_revision integer;v_id uuid;v_direction text:=lower(coalesce(payload->>'direction','all'));
begin if v_user is null then raise exception 'Authentication required.' using errcode='42501';end if;begin v_org:=nullif(payload->>'organisationId','')::uuid;v_firm:=nullif(payload->>'attorneyFirmId','')::uuid;v_profile:=nullif(payload->>'profileId','')::uuid;exception when invalid_text_representation then raise exception 'P8 kill switch identity invalid.' using errcode='22023';end;
 if not public.bridge_is_platform_admin() and not(v_scope='firm'and public.attorney_user_is_firm_admin(v_firm)and exists(select 1 from public.attorney_firms where id=v_firm and organisation_id=v_org))then raise exception 'P8 kill switch authority required.' using errcode='42501';end if;if coalesce(payload->>'version','')<>'conveyancer_operational_assurance_p8_v1'or v_scope not in('global','organisation','firm','profile')or v_direction not in('all','inbound','outbound')or trim(coalesce(payload->>'reason',''))=''or payload->>'requestedBy'<>v_user::text or length(trim(coalesce(payload->>'fingerprint','')))<8 then raise exception 'P8 kill switch invalid.' using errcode='22023';end if;
 select record_id,revision+1 into v_record,v_revision from public.conveyancer_provider_kill_switches where scope=v_scope and organisation_id is not distinct from v_org and attorney_firm_id is not distinct from v_firm and integration_profile_id is not distinct from v_profile and direction=v_direction order by revision desc limit 1;
 insert into public.conveyancer_provider_kill_switches(record_id,revision,scope,organisation_id,attorney_firm_id,integration_profile_id,direction,enabled,reason,incident_record_id,expires_at,fingerprint,created_by)values(coalesce(v_record,gen_random_uuid()),coalesce(v_revision,1),v_scope,v_org,v_firm,v_profile,v_direction,coalesce((payload->>'enabled')::boolean,false),payload->>'reason',nullif(payload->>'incidentId','')::uuid,nullif(payload->>'expiresAt','')::timestamptz,payload->>'fingerprint',v_user)returning id into v_id;return jsonb_build_object('ok',true,'id',v_id,'revision',coalesce(v_revision,1),'enabled',coalesce((payload->>'enabled')::boolean,false));end $$;

create or replace function public.bridge_record_conveyancer_operational_signal(payload jsonb)returns jsonb language plpgsql security definer set search_path=public as $$declare v_id uuid;begin if coalesce(payload->>'signalType','')=''or lower(payload->>'severity')not in('info','warning','critical')or payload::text~*'"(secret|token|credential|payload|body)"[[:space:]]*:'then raise exception 'P8 signal invalid.' using errcode='22023';end if;insert into public.conveyancer_operational_signals(organisation_id,attorney_firm_id,integration_profile_id,signal_type,severity,numeric_value,detail)values(nullif(payload->>'organisationId','')::uuid,nullif(payload->>'attorneyFirmId','')::uuid,nullif(payload->>'profileId','')::uuid,lower(payload->>'signalType'),lower(payload->>'severity'),nullif(payload->>'numericValue','')::numeric,coalesce(payload->'detail','{}'::jsonb))returning id into v_id;return jsonb_build_object('ok',true,'signalId',v_id);end $$;

create or replace function public.bridge_capture_conveyancer_operational_snapshots(p_now timestamptz default now())returns jsonb language plpgsql security definer set search_path=public as $$
declare f record;p public.conveyancer_operational_policies%rowtype;m jsonb;v_health text;v_blockers text[];v_warnings text[];v_snapshot uuid;v_count integer:=0;v_failed integer:=0;v_warning integer:=0;
begin for f in select distinct on(organisation_id,attorney_firm_id)organisation_id,attorney_firm_id from public.conveyancer_provider_transport_controls order by organisation_id,attorney_firm_id,revision desc loop
 select*into p from public.conveyancer_operational_policies where scope='firm'and organisation_id=f.organisation_id and attorney_firm_id=f.attorney_firm_id order by revision desc limit 1;if not found then p.window_minutes:=60;p.max_queue_depth:=100;p.max_oldest_queue_seconds:=900;p.min_success_rate_percent:=95;p.max_dead_letters:=0;p.max_reconciliation_required:=0;p.max_inbound_awaiting_review:=25;p.max_inbound_age_seconds:=3600;p.snapshot_freshness_seconds:=300;p.fingerprint:='default_p8_policy';end if;
 select jsonb_build_object('queueDepth',count(*)filter(where status in('queued','leased','retry_scheduled')),'oldestQueueSeconds',coalesce(extract(epoch from(p_now-min(created_at)filter(where status in('queued','leased','retry_scheduled')))),0),'succeeded',count(*)filter(where status='succeeded'and completed_at>=p_now-make_interval(mins=>p.window_minutes)),'failed',count(*)filter(where status in('dead_letter','reconciliation_required')and completed_at>=p_now-make_interval(mins=>p.window_minutes)),'deadLetters',count(*)filter(where status='dead_letter'),'reconciliationRequired',count(*)filter(where status='reconciliation_required'))into m from public.conveyancer_provider_outbound_commands where organisation_id=f.organisation_id and attorney_firm_id=f.attorney_firm_id;
 m:=m||coalesce((select jsonb_build_object('inboundAwaitingReview',count(*)filter(where status='awaiting_review'),'oldestInboundSeconds',coalesce(extract(epoch from(p_now-min(received_at)filter(where status='awaiting_review'))),0))from public.conveyancer_provider_inbound_envelopes where organisation_id=f.organisation_id and attorney_firm_id=f.attorney_firm_id),'{}'::jsonb);m:=m||jsonb_build_object('successRatePercent',case when((m->>'succeeded')::numeric+(m->>'failed')::numeric)=0 then 100 else round(100*(m->>'succeeded')::numeric/((m->>'succeeded')::numeric+(m->>'failed')::numeric),2)end);
 v_blockers:='{}'::text[];v_warnings:='{}'::text[];if(m->>'queueDepth')::numeric>p.max_queue_depth then v_blockers:=array_append(v_blockers,'queue_depth_exceeded');end if;if(m->>'oldestQueueSeconds')::numeric>p.max_oldest_queue_seconds then v_blockers:=array_append(v_blockers,'oldest_queue_age_exceeded');end if;if(m->>'successRatePercent')::numeric<p.min_success_rate_percent then v_blockers:=array_append(v_blockers,'success_rate_below_minimum');end if;if(m->>'deadLetters')::numeric>p.max_dead_letters then v_blockers:=array_append(v_blockers,'dead_letters_present');end if;if(m->>'reconciliationRequired')::numeric>p.max_reconciliation_required then v_blockers:=array_append(v_blockers,'reconciliation_required_present');end if;if(m->>'inboundAwaitingReview')::numeric>p.max_inbound_awaiting_review or(m->>'oldestInboundSeconds')::numeric>p.max_inbound_age_seconds then v_warnings:=array_append(v_warnings,'inbound_review_backlog');end if;v_health:=case when cardinality(v_blockers)>0 then'fail'when cardinality(v_warnings)>0 then'warning'else'pass'end;
 insert into public.conveyancer_operational_snapshots(scope,organisation_id,attorney_firm_id,health,metrics,blockers,warnings,policy_fingerprint,captured_at)values('firm',f.organisation_id,f.attorney_firm_id,v_health,m,v_blockers,v_warnings,p.fingerprint,p_now)returning id into v_snapshot;if v_health='pass'then update public.conveyancer_operational_alerts set status='resolved',resolved_at=p_now,updated_at=p_now where organisation_id=f.organisation_id and attorney_firm_id=f.attorney_firm_id and alert_key='provider_transport_health'and status<>'resolved';else insert into public.conveyancer_operational_alerts(organisation_id,attorney_firm_id,alert_key,severity,status,summary,snapshot_id)values(f.organisation_id,f.attorney_firm_id,'provider_transport_health',case when v_health='fail'then'critical'else'warning'end,'open','Provider transport requires operational attention.',v_snapshot)on conflict(attorney_firm_id,alert_key)do update set severity=excluded.severity,status='open',summary=excluded.summary,snapshot_id=excluded.snapshot_id,resolved_at=null,updated_at=p_now;end if;v_count:=v_count+1;if v_health='fail'then v_failed:=v_failed+1;elsif v_health='warning'then v_warning:=v_warning+1;end if;end loop;
 insert into public.conveyancer_operational_snapshots(scope,health,metrics,blockers,warnings,captured_at)values('global',case when v_failed>0 then'fail'when v_warning>0 then'warning'else'pass'end,jsonb_build_object('firms',v_count,'failingFirms',v_failed,'warningFirms',v_warning),case when v_failed>0 then array['firm_health_failures']::text[]else'{}'::text[]end,case when v_warning>0 then array['firm_health_warnings']::text[]else'{}'::text[]end,p_now);return jsonb_build_object('ok',true,'firms',v_count,'failingFirms',v_failed,'warningFirms',v_warning,'capturedAt',p_now);end $$;

create or replace function public.bridge_set_conveyancer_provider_incident(payload jsonb)returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_scope text:=lower(payload->>'scope');v_org uuid;v_firm uuid;v_profile uuid;v_incident uuid;v_record uuid;v_revision integer;v_id uuid;begin if v_user is null then raise exception'Authentication required.'using errcode='42501';end if;begin v_org:=nullif(payload->>'organisationId','')::uuid;v_firm:=nullif(payload->>'attorneyFirmId','')::uuid;v_profile:=nullif(payload->>'profileId','')::uuid;v_incident:=nullif(payload->>'incidentId','')::uuid;exception when invalid_text_representation then raise exception'P8 incident identity invalid.'using errcode='22023';end;if not public.bridge_is_platform_admin()and not(v_scope='firm'and public.attorney_user_is_firm_admin(v_firm)and exists(select 1 from public.attorney_firms where id=v_firm and organisation_id=v_org))then raise exception'P8 incident authority required.'using errcode='42501';end if;if coalesce(payload->>'version','')<>'conveyancer_operational_assurance_p8_v1'or v_scope not in('global','organisation','firm','profile')or lower(payload->>'severity')not in('sev1','sev2','sev3','sev4')or lower(payload->>'status')not in('open','mitigating','monitoring','resolved')or trim(coalesce(payload->>'title',''))=''or trim(coalesce(payload->>'summary',''))=''or length(trim(coalesce(payload->>'fingerprint','')))<8 then raise exception'P8 incident invalid.'using errcode='22023';end if;select record_id,revision+1 into v_record,v_revision from public.conveyancer_provider_incidents where id=v_incident or record_id=v_incident order by revision desc limit 1;insert into public.conveyancer_provider_incidents(record_id,revision,scope,organisation_id,attorney_firm_id,integration_profile_id,severity,status,title,summary,owner_user_id,started_at,resolved_at,fingerprint,created_by)values(coalesce(v_record,gen_random_uuid()),coalesce(v_revision,1),v_scope,v_org,v_firm,v_profile,lower(payload->>'severity'),lower(payload->>'status'),payload->>'title',payload->>'summary',(payload->>'ownerUserId')::uuid,(payload->>'startedAt')::timestamptz,nullif(payload->>'resolvedAt','')::timestamptz,payload->>'fingerprint',v_user)returning id,record_id into v_id,v_record;return jsonb_build_object('ok',true,'incidentId',v_id,'recordId',v_record,'revision',coalesce(v_revision,1));end $$;
create or replace function public.bridge_acknowledge_conveyancer_operational_alert(p_alert_id uuid,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_row public.conveyancer_operational_alerts%rowtype;begin if v_user is null or trim(coalesce(p_reason,''))=''then raise exception'P8 alert acknowledgement requires a reason.'using errcode='42501';end if;select*into v_row from public.conveyancer_operational_alerts where id=p_alert_id for update;if not found or not(public.bridge_is_platform_admin()or public.attorney_user_is_firm_admin(v_row.attorney_firm_id))then raise exception'P8 alert authority required.'using errcode='42501';end if;update public.conveyancer_operational_alerts set status='acknowledged',acknowledged_by=v_user,acknowledged_at=now(),summary=summary||' Acknowledged: '||left(trim(p_reason),300),updated_at=now()where id=v_row.id;return jsonb_build_object('ok',true,'alertId',v_row.id,'status','acknowledged');end $$;

create or replace function public.bridge_create_conveyancer_release_candidate(payload jsonb)returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_id uuid;v_pilot uuid[];begin if v_user is null or not public.bridge_is_platform_admin()then raise exception 'Platform administrator required.'using errcode='42501';end if;select coalesce(array_agg(value::uuid),'{}'::uuid[])into v_pilot from jsonb_array_elements_text(coalesce(payload->'pilotTransactionIds','[]'::jsonb))items(value);if coalesce(payload->>'version','')<>'conveyancer_operational_assurance_p8_v1'or lower(payload->>'targetEnvironment')not in('staging','production')or lower(payload->>'rolloutMode')not in('pilot','live')or length(trim(coalesce(payload->>'fingerprint','')))<8 or payload::text~*'"(secret|token|credential)"[[:space:]]*:'then raise exception 'P8 release candidate invalid.'using errcode='22023';end if;insert into public.conveyancer_release_candidates(release_id,release_version,target_environment,rollout_mode,commit_sha,migration_from,migration_to,artifact_reference,artifact_hash,rollback_reference,rollback_hash,pilot_transaction_ids,evidence,fingerprint,created_by)values(payload->>'releaseId',payload->>'releaseVersion',lower(payload->>'targetEnvironment'),lower(payload->>'rolloutMode'),payload->>'commitSha',payload->>'migrationFrom',payload->>'migrationTo',payload->>'artifactReference',payload->>'artifactHash',payload->>'rollbackReference',payload->>'rollbackHash',v_pilot,payload->'evidence',payload->>'fingerprint',v_user)returning id into v_id;insert into public.conveyancer_release_events(release_candidate_id,event_type,reason,created_by)values(v_id,'submitted','Release candidate submitted for independent approval.',v_user);return jsonb_build_object('ok',true,'releaseCandidateId',v_id);end $$;
create or replace function public.bridge_approve_conveyancer_release(p_release_candidate_id uuid,p_role text,p_decision text,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_id uuid;begin if v_user is null or not public.bridge_is_platform_admin()then raise exception 'Platform administrator required.'using errcode='42501';end if;if lower(p_role)not in('operations','security','legal')or lower(p_decision)not in('approved','rejected')or trim(coalesce(p_reason,''))=''then raise exception 'P8 release approval invalid.'using errcode='22023';end if;insert into public.conveyancer_release_approvals(release_candidate_id,approver_role,decision,reason,approved_by)values(p_release_candidate_id,lower(p_role),lower(p_decision),p_reason,v_user)returning id into v_id;return jsonb_build_object('ok',true,'approvalId',v_id);end $$;
create or replace function public.bridge_authorise_conveyancer_release(p_release_candidate_id uuid,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_snapshot public.conveyancer_operational_snapshots%rowtype;v_event uuid;begin if v_user is null or not public.bridge_is_platform_admin()then raise exception 'Platform administrator required.'using errcode='42501';end if;if(select count(*)from public.conveyancer_release_approvals where release_candidate_id=p_release_candidate_id and decision='approved')<>3 or(select count(distinct approved_by)from public.conveyancer_release_approvals where release_candidate_id=p_release_candidate_id and decision='approved')<>3 then raise exception 'P8 independent operations, security and legal approvals are required.'using errcode='42501';end if;select*into v_snapshot from public.conveyancer_operational_snapshots where scope='global'order by captured_at desc limit 1;if not found or v_snapshot.health<>'pass'or v_snapshot.captured_at<now()-interval'5 minutes'or not public.bridge_conveyancer_provider_operation_allowed(null,null,null,'outbound')then insert into public.conveyancer_release_events(release_candidate_id,event_type,snapshot_id,reason,created_by)values(p_release_candidate_id,'activation_blocked',v_snapshot.id,coalesce(nullif(p_reason,''),'Operational release gate failed.'),v_user)returning id into v_event;return jsonb_build_object('ok',false,'blocked',true,'eventId',v_event,'reason','operational_release_gate_failed');end if;insert into public.conveyancer_release_events(release_candidate_id,event_type,snapshot_id,reason,authorisation_expires_at,created_by)values(p_release_candidate_id,'activation_authorised',v_snapshot.id,p_reason,now()+interval'15 minutes',v_user)returning id into v_event;return jsonb_build_object('ok',true,'authorisationEventId',v_event,'expiresAt',now()+interval'15 minutes');end $$;
create or replace function public.bridge_rollback_conveyancer_release(p_release_candidate_id uuid,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_record uuid;v_revision integer;begin if v_user is null or not public.bridge_is_platform_admin()or trim(coalesce(p_reason,''))=''then raise exception 'P8 rollback authority and reason required.'using errcode='42501';end if;insert into public.conveyancer_release_events(release_candidate_id,event_type,reason,created_by)values(p_release_candidate_id,'rolled_back',p_reason,v_user);select record_id,revision+1 into v_record,v_revision from public.conveyancer_provider_kill_switches where scope='global'and direction='all'order by revision desc limit 1;insert into public.conveyancer_provider_kill_switches(record_id,revision,scope,direction,enabled,reason,fingerprint,created_by)values(coalesce(v_record,gen_random_uuid()),coalesce(v_revision,1),'global','all',true,'Automatic rollback stop: '||p_reason,'rollback_'||p_release_candidate_id,v_user);return jsonb_build_object('ok',true,'killSwitchEnabled',true);end $$;

create or replace function public.bridge_conveyancer_p8_guard_transport()returns trigger language plpgsql security definer set search_path=public as $$begin if not public.bridge_conveyancer_provider_operation_allowed(new.organisation_id,new.attorney_firm_id,new.integration_profile_id,case when tg_table_name='conveyancer_provider_inbound_envelopes'then'inbound'else'outbound'end)then raise exception 'P8 operational kill switch is active.'using errcode='42501';end if;return new;end $$;
drop trigger if exists conveyancer_p8_outbound_guard on public.conveyancer_provider_outbound_commands;create trigger conveyancer_p8_outbound_guard before insert on public.conveyancer_provider_outbound_commands for each row execute function public.bridge_conveyancer_p8_guard_transport();drop trigger if exists conveyancer_p8_inbound_guard on public.conveyancer_provider_inbound_envelopes;create trigger conveyancer_p8_inbound_guard before insert on public.conveyancer_provider_inbound_envelopes for each row execute function public.bridge_conveyancer_p8_guard_transport();

create or replace function public.bridge_claim_conveyancer_provider_commands(p_limit integer default 25,p_now timestamptz default now())returns jsonb language plpgsql security definer set search_path=public as $$declare v_row public.conveyancer_provider_outbound_commands%rowtype;v_lease uuid;v_commands jsonb:='[]'::jsonb;v_count integer:=0;begin for v_row in select command.*from public.conveyancer_provider_outbound_commands command join lateral(select*from public.conveyancer_provider_transport_controls control where control.organisation_id=command.organisation_id and control.attorney_firm_id=command.attorney_firm_id order by revision desc limit 1)control on true where((command.status in('queued','retry_scheduled')and command.available_at<=p_now)or(command.status='leased'and command.lease_expires_at<=p_now))and control.mode in('pilot','live')and(control.mode='live'or command.transaction_id=any(control.pilot_transaction_ids))and control.outbound_enabled and not control.kill_switch_enabled and public.bridge_conveyancer_provider_operation_allowed(command.organisation_id,command.attorney_firm_id,command.integration_profile_id,'outbound')order by command.available_at,command.created_at for update of command skip locked limit greatest(1,least(coalesce(p_limit,25),100))loop v_lease:=gen_random_uuid();update public.conveyancer_provider_outbound_commands set status='leased',attempt_count=attempt_count+1,lease_token=v_lease,lease_expires_at=p_now+(select make_interval(secs=>control.lease_seconds)from public.conveyancer_provider_transport_controls control where control.organisation_id=v_row.organisation_id and control.attorney_firm_id=v_row.attorney_firm_id order by revision desc limit 1),updated_at=p_now where id=v_row.id;v_count:=v_count+1;v_commands:=v_commands||jsonb_build_array(jsonb_build_object('id',v_row.id,'leaseToken',v_lease,'version','conveyancer_provider_runtime_p6_v1','operationId',v_row.command_id||':attempt:'||(v_row.attempt_count+1),'profileId',v_row.integration_profile_id,'organisationId',v_row.organisation_id,'attorneyFirmId',v_row.attorney_firm_id,'transactionId',v_row.transaction_id,'capability',v_row.capability,'operationType',v_row.operation_type,'lane',v_row.lane,'payloadReference',v_row.payload_reference,'payloadHash',v_row.payload_hash,'idempotencyKey',v_row.idempotency_key,'authorityReference',v_row.authority_reference,'requestedAt',v_row.requested_at,'requestedBy',v_row.requested_by,'attempt',v_row.attempt_count+1));end loop;return jsonb_build_object('ok',true,'count',v_count,'commands',v_commands);end $$;

-- Re-declare the release boundary with database-side evidence validation. This
-- prevents a privileged caller from bypassing the application contract.
create or replace function public.bridge_create_conveyancer_release_candidate(payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_id uuid;v_pilot uuid[];v_evidence jsonb:=coalesce(payload->'evidence','{}'::jsonb);
begin
 if v_user is null or not public.bridge_is_platform_admin() then raise exception 'Platform administrator required.' using errcode='42501';end if;
 begin select coalesce(array_agg(value::uuid),'{}'::uuid[]) into v_pilot from jsonb_array_elements_text(coalesce(payload->'pilotTransactionIds','[]'::jsonb)) items(value);exception when invalid_text_representation then raise exception 'P8 pilot transaction identity invalid.' using errcode='22023';end;
 if coalesce(payload->>'version','')<>'conveyancer_operational_assurance_p8_v1'
  or lower(payload->>'targetEnvironment') not in('staging','production')
  or lower(payload->>'rolloutMode') not in('pilot','live')
  or coalesce(payload->>'commitSha','')!~'^[a-fA-F0-9]{7,64}$'
  or trim(coalesce(payload->>'releaseId',''))=''
  or trim(coalesce(payload->>'releaseVersion',''))=''
  or trim(coalesce(payload->>'artifactReference',''))=''
  or coalesce(payload->>'artifactHash','')!~'^(sha256:)?[a-fA-F0-9]{64}$'
  or trim(coalesce(payload->>'rollbackReference',''))=''
  or coalesce(payload->>'rollbackHash','')!~'^(sha256:)?[a-fA-F0-9]{64}$'
  or trim(coalesce(v_evidence->>'testsReference',''))=''
  or coalesce(v_evidence->>'testsHash','')!~'^(sha256:)?[a-fA-F0-9]{64}$'
  or trim(coalesce(v_evidence->>'securityReference',''))=''
  or coalesce(v_evidence->>'securityHash','')!~'^(sha256:)?[a-fA-F0-9]{64}$'
  or trim(coalesce(v_evidence->>'recoveryReference',''))=''
  or coalesce(v_evidence->>'recoveryHash','')!~'^(sha256:)?[a-fA-F0-9]{64}$'
  or length(trim(coalesce(payload->>'fingerprint','')))<8
  or (lower(payload->>'targetEnvironment')='production' and lower(payload->>'rolloutMode')='pilot' and cardinality(v_pilot)=0)
  or payload::text~*'"(secret|token|credential)"[[:space:]]*:'
 then raise exception 'P8 release candidate invalid.' using errcode='22023';end if;
 insert into public.conveyancer_release_candidates(release_id,release_version,target_environment,rollout_mode,commit_sha,migration_from,migration_to,artifact_reference,artifact_hash,rollback_reference,rollback_hash,pilot_transaction_ids,evidence,fingerprint,created_by)
 values(payload->>'releaseId',payload->>'releaseVersion',lower(payload->>'targetEnvironment'),lower(payload->>'rolloutMode'),payload->>'commitSha',payload->>'migrationFrom',payload->>'migrationTo',payload->>'artifactReference',payload->>'artifactHash',payload->>'rollbackReference',payload->>'rollbackHash',v_pilot,v_evidence,payload->>'fingerprint',v_user)returning id into v_id;
 insert into public.conveyancer_release_events(release_candidate_id,event_type,reason,created_by)values(v_id,'submitted','Release candidate submitted for independent approval.',v_user);
 return jsonb_build_object('ok',true,'releaseCandidateId',v_id);
end $$;

create or replace function public.bridge_authorise_conveyancer_release(p_release_candidate_id uuid,p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_snapshot public.conveyancer_operational_snapshots%rowtype;v_event uuid;v_candidate public.conveyancer_release_candidates%rowtype;
begin
 if v_user is null or not public.bridge_is_platform_admin()then raise exception 'Platform administrator required.'using errcode='42501';end if;
 if trim(coalesce(p_reason,''))='' then raise exception 'P8 release authorisation reason required.'using errcode='22023';end if;
 select * into strict v_candidate from public.conveyancer_release_candidates where id=p_release_candidate_id;
 if exists(select 1 from public.conveyancer_release_events where release_candidate_id=p_release_candidate_id and event_type in('activated','rolled_back'))then raise exception 'P8 completed or rolled-back release candidates cannot be reused.'using errcode='42501';end if;
 if (select count(*)from public.conveyancer_release_approvals where release_candidate_id=p_release_candidate_id and decision='approved')<>3
  or (select count(distinct approved_by)from public.conveyancer_release_approvals where release_candidate_id=p_release_candidate_id and decision='approved')<>3
 then raise exception 'P8 independent operations, security and legal approvals are required.'using errcode='42501';end if;
 select * into v_snapshot from public.conveyancer_operational_snapshots where scope='global'order by captured_at desc limit 1;
 if not found or v_snapshot.health<>'pass' or v_snapshot.captured_at<now()-interval'5 minutes'
  or not public.bridge_conveyancer_provider_operation_allowed(null,null,null,'outbound')
  or (v_candidate.target_environment='production' and coalesce((v_snapshot.metrics->>'firms')::integer,0)=0)
 then
  insert into public.conveyancer_release_events(release_candidate_id,event_type,snapshot_id,reason,created_by)values(p_release_candidate_id,'activation_blocked',v_snapshot.id,coalesce(nullif(p_reason,''),'Operational release gate failed.'),v_user)returning id into v_event;
  return jsonb_build_object('ok',false,'blocked',true,'eventId',v_event,'reason','operational_release_gate_failed');
 end if;
 insert into public.conveyancer_release_events(release_candidate_id,event_type,snapshot_id,reason,authorisation_expires_at,created_by)values(p_release_candidate_id,'activation_authorised',v_snapshot.id,p_reason,now()+interval'15 minutes',v_user)returning id into v_event;
 return jsonb_build_object('ok',true,'authorisationEventId',v_event,'expiresAt',now()+interval'15 minutes');
exception when no_data_found then raise exception 'P8 release candidate not found.'using errcode='P0002';
end $$;

-- Deployment tooling must consume a fresh authorisation exactly once. The
-- service-role-only RPC binds the deployed artifact to the approved candidate.
create or replace function public.bridge_record_conveyancer_release_activation(p_authorisation_event_id uuid,p_deployment_reference text,p_artifact_hash text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_authorisation public.conveyancer_release_events%rowtype;v_candidate public.conveyancer_release_candidates%rowtype;v_snapshot public.conveyancer_operational_snapshots%rowtype;v_event uuid;
begin
 select * into strict v_authorisation from public.conveyancer_release_events where id=p_authorisation_event_id and event_type='activation_authorised' for update;
 select * into strict v_candidate from public.conveyancer_release_candidates where id=v_authorisation.release_candidate_id;
 if v_authorisation.authorisation_expires_at is null or v_authorisation.authorisation_expires_at<=now()
  or trim(coalesce(p_deployment_reference,''))=''
  or p_artifact_hash<>v_candidate.artifact_hash
  or exists(select 1 from public.conveyancer_release_events where release_candidate_id=v_candidate.id and event_type in('activated','rolled_back') and created_at>=v_authorisation.created_at)
 then raise exception 'P8 deployment authorisation invalid, expired or already consumed.'using errcode='42501';end if;
 select * into v_snapshot from public.conveyancer_operational_snapshots where scope='global'order by captured_at desc limit 1;
 if not found or v_snapshot.health<>'pass' or v_snapshot.captured_at<now()-interval'5 minutes'
  or not public.bridge_conveyancer_provider_operation_allowed(null,null,null,'outbound')
  or (v_candidate.target_environment='production' and coalesce((v_snapshot.metrics->>'firms')::integer,0)=0)
 then raise exception 'P8 deployment health gate closed.'using errcode='42501';end if;
 insert into public.conveyancer_release_events(release_candidate_id,event_type,snapshot_id,reason,metadata,created_by)
 values(v_candidate.id,'activated',v_snapshot.id,'Deployment tooling consumed the approved release authorisation.',jsonb_build_object('authorisationEventId',v_authorisation.id,'deploymentReference',p_deployment_reference,'artifactHash',p_artifact_hash),v_authorisation.created_by)returning id into v_event;
 return jsonb_build_object('ok',true,'activationEventId',v_event,'releaseCandidateId',v_candidate.id);
exception when no_data_found then raise exception 'P8 deployment authorisation not found.'using errcode='P0002';
end $$;

revoke all on function public.bridge_conveyancer_provider_operation_allowed(uuid,uuid,uuid,text),public.bridge_set_conveyancer_operational_policy(jsonb),public.bridge_set_conveyancer_provider_kill_switch(jsonb),public.bridge_record_conveyancer_operational_signal(jsonb),public.bridge_capture_conveyancer_operational_snapshots(timestamptz),public.bridge_set_conveyancer_provider_incident(jsonb),public.bridge_acknowledge_conveyancer_operational_alert(uuid,text),public.bridge_create_conveyancer_release_candidate(jsonb),public.bridge_approve_conveyancer_release(uuid,text,text,text),public.bridge_authorise_conveyancer_release(uuid,text),public.bridge_record_conveyancer_release_activation(uuid,text,text),public.bridge_rollback_conveyancer_release(uuid,text)from public,anon,authenticated,service_role;
grant execute on function public.bridge_conveyancer_provider_operation_allowed(uuid,uuid,uuid,text)to authenticated,service_role;grant execute on function public.bridge_set_conveyancer_operational_policy(jsonb),public.bridge_set_conveyancer_provider_kill_switch(jsonb),public.bridge_set_conveyancer_provider_incident(jsonb),public.bridge_acknowledge_conveyancer_operational_alert(uuid,text),public.bridge_create_conveyancer_release_candidate(jsonb),public.bridge_approve_conveyancer_release(uuid,text,text,text),public.bridge_authorise_conveyancer_release(uuid,text),public.bridge_rollback_conveyancer_release(uuid,text)to authenticated;grant execute on function public.bridge_record_conveyancer_operational_signal(jsonb),public.bridge_capture_conveyancer_operational_snapshots(timestamptz),public.bridge_record_conveyancer_release_activation(uuid,text,text)to service_role;
comment on table public.conveyancer_operational_snapshots is'P8 point-in-time provider transport SLO evidence used by the production release gate.';comment on table public.conveyancer_provider_kill_switches is'P8 append-only global, organisation, firm and profile stop controls. Manual conveyancing remains available.';comment on table public.conveyancer_release_approvals is'P8 independently authenticated operations, security and legal release decisions.';
notify pgrst,'reload schema';commit;
