-- Phase 63: deterministic reminder planning. A scheduler may call the same
-- run function repeatedly; the target/policy/step key prevents duplicates.
create table public.rental_reminder_targets (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id), reminder_type text not null check(reminder_type in('document','rent','inspection','renewal')),
 entity_id uuid, recipient_reference text not null, due_at timestamptz not null, status text not null default 'open' check(status in('open','completed','cancelled')),
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.rental_reminder_policies (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id), reminder_type text not null check(reminder_type in('document','rent','inspection','renewal')),
 first_offset_hours integer not null default 0 check(first_offset_hours>=0), escalation_offset_hours integer not null default 72 check(escalation_offset_hours>0), enabled boolean not null default true, created_by uuid not null references auth.users(id), unique(organisation_id,reminder_type)
);
create table public.rental_reminder_runs (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id), ran_by uuid not null references auth.users(id), created_at timestamptz not null default now(), planned_count integer not null default 0, cancelled_count integer not null default 0);
create table public.rental_reminders (id uuid primary key default gen_random_uuid(), target_id uuid not null references public.rental_reminder_targets(id) on delete cascade, policy_id uuid not null references public.rental_reminder_policies(id), run_id uuid references public.rental_reminder_runs(id), step text not null check(step in('initial','escalation')), planned_for timestamptz not null, status text not null check(status in('planned','cancelled','suppressed')), cancellation_reason text, created_at timestamptz not null default now(), unique(target_id,policy_id,step));
create index rental_reminder_targets_org_status_due_idx on public.rental_reminder_targets(organisation_id,status,due_at);
create index rental_reminders_target_idx on public.rental_reminders(target_id);
create index rental_reminders_policy_idx on public.rental_reminders(policy_id);
create index rental_reminder_runs_org_created_idx on public.rental_reminder_runs(organisation_id,created_at desc);
create index rental_reminder_targets_created_by_idx on public.rental_reminder_targets(created_by);
create index rental_reminder_policies_created_by_idx on public.rental_reminder_policies(created_by);
create index rental_reminder_runs_ran_by_idx on public.rental_reminder_runs(ran_by);
alter table public.rental_reminder_targets enable row level security; alter table public.rental_reminder_policies enable row level security; alter table public.rental_reminder_runs enable row level security; alter table public.rental_reminders enable row level security;
create policy "rental_reminder_targets_manager_read" on public.rental_reminder_targets for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));
create policy "rental_reminder_policies_manager_read" on public.rental_reminder_policies for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));
create policy "rental_reminder_runs_manager_read" on public.rental_reminder_runs for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));
create policy "rental_reminders_manager_read" on public.rental_reminders for select to authenticated using(exists(select 1 from public.rental_reminder_targets t where t.id=rental_reminders.target_id and public.rental_financial_manager_authorized(t.organisation_id)));
create or replace function public.rental_create_reminder_target(p_org uuid,p_type text,p_entity_id uuid,p_recipient text,p_due_at timestamptz)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_id uuid; begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org) or p_type not in('document','rent','inspection','renewal') or length(btrim(coalesce(p_recipient,'')))=0 or p_due_at is null then raise exception 'Invalid reminder target'; end if; insert into public.rental_reminder_targets(organisation_id,reminder_type,entity_id,recipient_reference,due_at,created_by) values(p_org,p_type,p_entity_id,btrim(p_recipient),p_due_at,auth.uid()) returning id into v_id; insert into public.rental_reminder_policies(organisation_id,reminder_type,created_by) values(p_org,p_type,auth.uid()) on conflict(organisation_id,reminder_type) do nothing; return jsonb_build_object('target_id',v_id); end $$;
create or replace function public.rental_run_reminder_orchestration(p_org uuid)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_run uuid; v_planned integer:=0; v_cancelled integer:=0; r record; begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org) then raise exception 'Not authorized'; end if; perform pg_catalog.pg_advisory_xact_lock(hashtextextended(p_org::text,63)); insert into public.rental_reminder_runs(organisation_id,ran_by) values(p_org,auth.uid()) returning id into v_run; update public.rental_reminders reminder set status='cancelled',cancellation_reason='target_no_longer_open' where status='planned' and exists(select 1 from public.rental_reminder_targets target where target.id=reminder.target_id and target.organisation_id=p_org and target.status<>'open'); get diagnostics v_cancelled=row_count; for r in select target.*,policy.id policy_id,policy.first_offset_hours,policy.escalation_offset_hours from public.rental_reminder_targets target join public.rental_reminder_policies policy on policy.organisation_id=target.organisation_id and policy.reminder_type=target.reminder_type where target.organisation_id=p_org and target.status='open' and policy.enabled loop if now()>=r.due_at-make_interval(hours=>r.first_offset_hours) then insert into public.rental_reminders(target_id,policy_id,run_id,step,planned_for,status) values(r.id,r.policy_id,v_run,'initial',now(),'planned') on conflict(target_id,policy_id,step) do nothing; if found then v_planned:=v_planned+1; end if; end if; if now()>=r.due_at+make_interval(hours=>r.escalation_offset_hours) then insert into public.rental_reminders(target_id,policy_id,run_id,step,planned_for,status) values(r.id,r.policy_id,v_run,'escalation',now(),'planned') on conflict(target_id,policy_id,step) do nothing; if found then v_planned:=v_planned+1; end if; end if; end loop; update public.rental_reminder_runs set planned_count=v_planned,cancelled_count=v_cancelled where id=v_run; return jsonb_build_object('run_id',v_run,'planned_count',v_planned,'cancelled_count',v_cancelled); end $$;
create or replace function public.rental_get_reminder_operations(p_org uuid)
returns jsonb language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org) then raise exception 'Not authorized'; end if; return jsonb_build_object('targets',coalesce((select jsonb_agg(to_jsonb(x) order by x.due_at) from(select * from public.rental_reminder_targets where organisation_id=p_org order by due_at limit 100)x),'[]'::jsonb),'runs',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from(select * from public.rental_reminder_runs where organisation_id=p_org order by created_at desc limit 20)x),'[]'::jsonb)); end $$;
revoke all on function public.rental_create_reminder_target(uuid,text,uuid,text,timestamptz) from public,anon; revoke all on function public.rental_run_reminder_orchestration(uuid) from public,anon; revoke all on function public.rental_get_reminder_operations(uuid) from public,anon;
grant execute on function public.rental_create_reminder_target(uuid,text,uuid,text,timestamptz) to authenticated; grant execute on function public.rental_run_reminder_orchestration(uuid) to authenticated; grant execute on function public.rental_get_reminder_operations(uuid) to authenticated;
