-- Phase 65: a staged, provider-neutral import queue. This layer never posts
-- a payment automatically; staff must explicitly confirm a high-confidence match.
create table public.rental_payment_import_batches(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),source_name text not null,source_hash text not null,status text not null default 'staged' check(status in('staged','reviewing','completed','rejected')),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(organisation_id,source_hash));
create table public.rental_payment_import_rows(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.rental_payment_import_batches(id) on delete cascade,external_reference text,paid_on date not null,amount numeric(14,2) not null check(amount>0),payer_reference text,raw_payload jsonb not null default '{}'::jsonb,status text not null default 'unmatched' check(status in('unmatched','suggested','matched','rejected')),created_at timestamptz not null default now());
create table public.rental_payment_match_suggestions(id uuid primary key default gen_random_uuid(),import_row_id uuid not null references public.rental_payment_import_rows(id) on delete cascade,tenancy_id uuid references public.rental_tenancies(id),confidence numeric(5,2) not null check(confidence>=0 and confidence<=100),reason text not null,status text not null default 'pending' check(status in('pending','confirmed','rejected')),reviewed_by uuid references auth.users(id),reviewed_at timestamptz,created_at timestamptz not null default now(),unique(import_row_id,tenancy_id));
create index rental_payment_import_batches_org_status_idx on public.rental_payment_import_batches(organisation_id,status);create index rental_payment_import_rows_batch_status_idx on public.rental_payment_import_rows(batch_id,status);create index rental_payment_match_suggestions_row_idx on public.rental_payment_match_suggestions(import_row_id);create index rental_payment_match_suggestions_tenancy_idx on public.rental_payment_match_suggestions(tenancy_id);create index rental_payment_import_batches_created_by_idx on public.rental_payment_import_batches(created_by);create index rental_payment_match_suggestions_reviewed_by_idx on public.rental_payment_match_suggestions(reviewed_by);
alter table public.rental_payment_import_batches enable row level security;alter table public.rental_payment_import_rows enable row level security;alter table public.rental_payment_match_suggestions enable row level security;
create policy "rental_payment_import_batches_manager_read" on public.rental_payment_import_batches for select to authenticated using(public.rental_financial_manager_authorized(organisation_id));create policy "rental_payment_import_rows_manager_read" on public.rental_payment_import_rows for select to authenticated using(exists(select 1 from public.rental_payment_import_batches b where b.id=batch_id and public.rental_financial_manager_authorized(b.organisation_id)));create policy "rental_payment_match_manager_read" on public.rental_payment_match_suggestions for select to authenticated using(exists(select 1 from public.rental_payment_import_rows r join public.rental_payment_import_batches b on b.id=r.batch_id where r.id=import_row_id and public.rental_financial_manager_authorized(b.organisation_id)));
create or replace function public.rental_review_payment_match(p_suggestion_id uuid,p_decision text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_conf numeric;v_org uuid;begin select s.confidence,b.organisation_id into v_conf,v_org from public.rental_payment_match_suggestions s join public.rental_payment_import_rows r on r.id=s.import_row_id join public.rental_payment_import_batches b on b.id=r.batch_id where s.id=p_suggestion_id for update;if auth.uid() is null or not found or not public.rental_financial_manager_authorized(v_org) or p_decision not in('confirmed','rejected') then raise exception 'Invalid payment match review';end if;if p_decision='confirmed' and v_conf<90 then raise exception 'Low-confidence matches require manual resolution and cannot post automatically';end if;update public.rental_payment_match_suggestions set status=p_decision,reviewed_by=auth.uid(),reviewed_at=now() where id=p_suggestion_id;update public.rental_payment_import_rows set status=case when p_decision='confirmed' then 'matched' else 'rejected' end where id=(select import_row_id from public.rental_payment_match_suggestions where id=p_suggestion_id);return jsonb_build_object('suggestion_id',p_suggestion_id,'decision',p_decision,'posted',false);end $$;
create or replace function public.rental_get_payment_import_operations(p_org uuid) returns jsonb language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or not public.rental_financial_manager_authorized(p_org) then raise exception 'Not authorized';end if;return jsonb_build_object('batches',coalesce((select jsonb_agg(to_jsonb(x)order by x.created_at desc)from(select * from public.rental_payment_import_batches where organisation_id=p_org order by created_at desc limit 50)x),'[]'::jsonb),'suggestions',coalesce((select jsonb_agg(to_jsonb(x)order by x.created_at desc)from(select s.* from public.rental_payment_match_suggestions s join public.rental_payment_import_rows r on r.id=s.import_row_id join public.rental_payment_import_batches b on b.id=r.batch_id where b.organisation_id=p_org order by s.created_at desc limit 100)x),'[]'::jsonb));end $$;
revoke all on function public.rental_review_payment_match(uuid,text) from public,anon;revoke all on function public.rental_get_payment_import_operations(uuid) from public,anon;grant execute on function public.rental_review_payment_match(uuid,text) to authenticated;grant execute on function public.rental_get_payment_import_operations(uuid) to authenticated;
