begin;
create index if not exists rental_tenancies_active_property_idx on public.rental_tenancies(status,property_id,id) where status='active';
create index if not exists rental_financial_charges_tenancy_due_amount_idx on public.rental_financial_charges(tenancy_id,due_date) include(amount);
create index if not exists rental_financial_adjustments_tenancy_type_date_idx on public.rental_financial_adjustments(tenancy_id,adjustment_type,effective_date) include(amount);
create or replace function public.rental_get_arrears_dashboard_rows(p_as_of date,p_limit integer) returns table(tenancy_id uuid,property_name text,unit_label text,tenant_name text,rent_roll_amount numeric,collected_amount numeric,net_outstanding_amount numeric,credit_balance_amount numeric,aging_0_30 numeric,aging_31_60 numeric,aging_61_90 numeric,aging_91_plus numeric,oldest_due_date date,next_action text) language sql stable security definer set search_path='' as $$
with scoped as (select t.id,t.tenant_snapshot_json,p.name property_name,u.unit_label from public.rental_tenancies t join public.rental_properties p on p.id=t.property_id join public.rental_units u on u.id=t.unit_id where t.status='active' and public.rental_branch_access(p.organisation_id,p.branch_id)),
charges as (select c.tenancy_id,c.due_date,c.charge_type,greatest(c.amount-coalesce(sum(a.amount),0),0) outstanding,c.amount,coalesce(sum(a.amount),0) allocated from public.rental_financial_charges c left join public.rental_financial_allocations a on a.charge_id=c.id where c.due_date<=p_as_of group by c.id,c.tenancy_id,c.due_date,c.charge_type,c.amount),
adjustments as (select tenancy_id,coalesce(sum(amount)filter(where adjustment_type='debit'),0) debits,coalesce(sum(amount)filter(where adjustment_type='credit'),0) credits from public.rental_financial_adjustments where effective_date<=p_as_of group by tenancy_id),
agg as (select s.id tenancy_id,s.property_name,s.unit_label,coalesce(s.tenant_snapshot_json->>'name',s.tenant_snapshot_json->>'full_name','Tenant') tenant_name,coalesce(sum(c.amount)filter(where c.charge_type='rent' and c.due_date between date_trunc('month',p_as_of)::date and p_as_of),0) rent_roll_amount,coalesce(sum(c.allocated)filter(where c.charge_type='rent' and c.due_date between date_trunc('month',p_as_of)::date and p_as_of),0) collected_amount,coalesce(sum(c.outstanding),0)+coalesce(a.debits,0)-coalesce(a.credits,0) raw_outstanding,coalesce(sum(c.outstanding)filter(where p_as_of-c.due_date between 0 and 30),0) aging_0_30,coalesce(sum(c.outstanding)filter(where p_as_of-c.due_date between 31 and 60),0) aging_31_60,coalesce(sum(c.outstanding)filter(where p_as_of-c.due_date between 61 and 90),0) aging_61_90,coalesce(sum(c.outstanding)filter(where p_as_of-c.due_date>90),0) aging_91_plus,min(c.due_date)filter(where c.outstanding>0) oldest_due_date from scoped s left join charges c on c.tenancy_id=s.id left join adjustments a on a.tenancy_id=s.id group by s.id,s.property_name,s.unit_label,s.tenant_snapshot_json,a.debits,a.credits)
select tenancy_id,property_name,unit_label,tenant_name,rent_roll_amount,collected_amount,greatest(raw_outstanding,0),greatest(-raw_outstanding,0),aging_0_30,aging_31_60,aging_61_90,aging_91_plus,oldest_due_date,case when raw_outstanding<=0 then 'No collection action' when aging_91_plus>0 then 'Escalate: 90+ days overdue' when aging_61_90>0 then 'Priority follow-up: 61+ days overdue' when aging_31_60>0 then 'Contact tenant: 31+ days overdue' else 'Monitor current arrears' end from agg where raw_outstanding<>0 order by raw_outstanding desc,oldest_due_date nulls last limit p_limit;$$;
create or replace function public.rental_get_arrears_dashboard(p_as_of date default current_date,p_limit integer default 250) returns jsonb language plpgsql security definer set search_path='' as $$declare d date:=coalesce(p_as_of,current_date); l integer:=greatest(1,least(coalesce(p_limit,250),1000)); result jsonb; begin if auth.uid() is null then raise exception 'Authentication is required'; end if; select jsonb_build_object('as_of_date',d,'summary',jsonb_build_object('active_tenancies',coalesce((select count(*) from public.rental_tenancies t join public.rental_properties p on p.id=t.property_id where t.status='active' and public.rental_branch_access(p.organisation_id,p.branch_id)),0),'rent_roll_amount',coalesce((select sum(r.rent_roll_amount) from public.rental_get_arrears_dashboard_rows(d,1000000) r),0),'collected_amount',coalesce((select sum(r.collected_amount) from public.rental_get_arrears_dashboard_rows(d,1000000) r),0),'outstanding_amount',coalesce((select sum(r.net_outstanding_amount) from public.rental_get_arrears_dashboard_rows(d,1000000) r),0),'arrears_tenancy_count',coalesce((select count(*) from public.rental_get_arrears_dashboard_rows(d,1000000) r where r.net_outstanding_amount>0),0)),'rows',coalesce((select jsonb_agg(jsonb_build_object('tenancy_id',r.tenancy_id,'property_name',r.property_name,'unit_label',r.unit_label,'tenant_name',r.tenant_name,'rent_roll_amount',r.rent_roll_amount,'collected_amount',r.collected_amount,'net_outstanding_amount',r.net_outstanding_amount,'credit_balance_amount',r.credit_balance_amount,'aging_0_30',r.aging_0_30,'aging_31_60',r.aging_31_60,'aging_61_90',r.aging_61_90,'aging_91_plus',r.aging_91_plus,'oldest_due_date',r.oldest_due_date,'next_action',r.next_action) order by r.net_outstanding_amount desc,r.oldest_due_date nulls last) from public.rental_get_arrears_dashboard_rows(d,l) r),'[]'::jsonb)) into result; return result; end$$;
revoke execute on function public.rental_get_arrears_dashboard(date,integer),public.rental_get_arrears_dashboard_rows(date,integer) from public,anon; grant execute on function public.rental_get_arrears_dashboard(date,integer) to authenticated; commit;;
