-- Measured baseline: keep the existing relational model, add queue/search indexes
-- and a reusable per-user action window for expensive Rentals commands.
create table public.rental_operation_rate_windows(operation_key text not null,user_id uuid not null references auth.users(id),window_started_at timestamptz not null default now(),request_count integer not null default 1 check(request_count>0),primary key(operation_key,user_id));
alter table public.rental_operation_rate_windows enable row level security;
create policy "rental_operation_rate_windows_self_read" on public.rental_operation_rate_windows for select to authenticated using((select auth.uid())=user_id);
create index if not exists rental_maintenance_requests_org_status_priority_idx on public.rental_maintenance_requests(organisation_id,status,priority);
create index if not exists rental_vacancies_org_status_created_idx on public.rental_vacancies(organisation_id,status,created_at desc);
create index if not exists rental_tenancies_org_status_idx on public.rental_tenancies(organisation_id,status);
create or replace function public.rental_assert_operation_rate(p_operation text,p_max_requests integer default 30,p_window_seconds integer default 60)returns void language plpgsql security definer set search_path='' as $$ declare n int;begin if auth.uid() is null or p_max_requests<1 or p_window_seconds<1 then raise exception 'Invalid rate control';end if;insert into public.rental_operation_rate_windows(operation_key,user_id,window_started_at,request_count)values(p_operation,auth.uid(),now(),1)on conflict(operation_key,user_id)do update set request_count=case when public.rental_operation_rate_windows.window_started_at<now()-make_interval(secs=>p_window_seconds) then 1 else public.rental_operation_rate_windows.request_count+1 end,window_started_at=case when public.rental_operation_rate_windows.window_started_at<now()-make_interval(secs=>p_window_seconds) then now() else public.rental_operation_rate_windows.window_started_at end returning request_count into n;if n>p_max_requests then raise exception 'Rate limit exceeded';end if;end $$;
revoke all on function public.rental_assert_operation_rate(text,integer,integer)from public,anon;grant execute on function public.rental_assert_operation_rate(text,integer,integer)to authenticated;
