begin;

create table if not exists public.conveyancer_provider_transport_controls (
  id uuid primary key default gen_random_uuid(), record_id uuid not null default gen_random_uuid(), revision integer not null check(revision>0), organisation_id uuid not null references public.organisations(id) on delete restrict, attorney_firm_id uuid not null references public.attorney_firms(id) on delete restrict,
  mode text not null check(mode in ('disabled','observe','pilot','live')), outbound_enabled boolean not null default false, inbound_enabled boolean not null default false, pilot_transaction_ids uuid[] not null default '{}'::uuid[], kill_switch_enabled boolean not null default true,
  max_attempts integer not null default 5 check(max_attempts between 1 and 20), lease_seconds integer not null default 120 check(lease_seconds between 30 and 900), initial_retry_seconds integer not null default 30 check(initial_retry_seconds between 5 and 3600), max_retry_seconds integer not null default 3600 check(max_retry_seconds between 30 and 86400), replay_window_seconds integer not null default 300 check(replay_window_seconds between 60 and 900), max_inbound_bytes integer not null default 65536 check(max_inbound_bytes between 1024 and 1048576),
  reason text not null check(length(trim(reason))>0), contract_version text not null default 'conveyancer_provider_transport_p7_v1', fingerprint text not null check(length(trim(fingerprint))>=8), created_by uuid not null, created_at timestamptz not null default now(), unique(record_id,revision), unique(id,organisation_id,attorney_firm_id)
);

create table if not exists public.conveyancer_provider_webhook_endpoints (
  id uuid primary key default gen_random_uuid(), record_id uuid not null default gen_random_uuid(), revision integer not null check(revision>0), endpoint_key uuid not null default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete restrict, attorney_firm_id uuid not null references public.attorney_firms(id) on delete restrict, integration_profile_id uuid not null,
  status text not null check(status in ('draft','active','paused','disabled')), signing_algorithm text not null default 'hmac_sha256' check(signing_algorithm='hmac_sha256'), secret_reference text not null check(secret_reference ~ '^env://[A-Z][A-Z0-9_]{2,127}$'), allowed_event_types text[] not null default '{}'::text[], allowed_capabilities text[] not null default '{}'::text[],
  contract_version text not null default 'conveyancer_provider_transport_p7_v1', fingerprint text not null check(length(trim(fingerprint))>=8), created_by uuid not null, created_at timestamptz not null default now(), unique(record_id,revision), unique(endpoint_key,revision), unique(id,organisation_id,attorney_firm_id), foreign key(integration_profile_id,organisation_id,attorney_firm_id) references public.conveyancer_integration_profiles(id,organisation_id,attorney_firm_id) on delete restrict, check(public.bridge_conveyancer_p6_capabilities_valid(allowed_capabilities))
);

create table if not exists public.conveyancer_provider_outbound_commands (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete restrict, attorney_firm_id uuid not null references public.attorney_firms(id) on delete restrict, transaction_id uuid not null references public.transactions(id) on delete restrict, integration_profile_id uuid not null,
  command_id text not null, capability text not null, operation_type text not null, lane text not null check(lane in ('transfer','bond','cancellation','external')), payload_reference text not null, payload_hash text not null check(length(trim(payload_hash))>=8), idempotency_key text not null, authority_reference text not null, command_fingerprint text not null check(length(trim(command_fingerprint))>=8),
  status text not null default 'queued' check(status in ('queued','leased','retry_scheduled','succeeded','dead_letter','cancelled','reconciliation_required')), attempt_count integer not null default 0 check(attempt_count>=0), max_attempts integer not null check(max_attempts between 1 and 20), initial_retry_seconds integer not null, max_retry_seconds integer not null, available_at timestamptz not null default now(), lease_token uuid, lease_expires_at timestamptz, last_error_code text, provider_reference text, response_hash text, result_payload jsonb check(result_payload is null or (jsonb_typeof(result_payload)='object' and octet_length(result_payload::text)<=8192)), requested_by uuid not null, requested_at timestamptz not null, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(attorney_firm_id,command_id), unique(attorney_firm_id,idempotency_key), unique(id,organisation_id,attorney_firm_id,transaction_id), foreign key(integration_profile_id,organisation_id,attorney_firm_id) references public.conveyancer_integration_profiles(id,organisation_id,attorney_firm_id) on delete restrict
);

create table if not exists public.conveyancer_provider_inbound_envelopes (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete restrict, attorney_firm_id uuid not null references public.attorney_firms(id) on delete restrict, transaction_id uuid not null references public.transactions(id) on delete restrict, integration_profile_id uuid not null, webhook_endpoint_id uuid not null, endpoint_key uuid not null,
  provider_event_id text not null, event_type text not null, capability text not null, lane text not null check(lane in ('transfer','bond','cancellation','external')), status text not null default 'awaiting_review' check(status in ('awaiting_review','accepted_for_review','quarantined','ignored')), signature_verified boolean not null, provider_timestamp timestamptz not null, object_bucket text not null, object_path text not null, content_hash text not null check(length(trim(content_hash))>=8), metadata jsonb not null default '{}'::jsonb check(jsonb_typeof(metadata)='object' and octet_length(metadata::text)<=8192), review_reason text, reviewed_by uuid, reviewed_at timestamptz, received_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(endpoint_key,provider_event_id), unique(id,organisation_id,attorney_firm_id,transaction_id), foreign key(integration_profile_id,organisation_id,attorney_firm_id) references public.conveyancer_integration_profiles(id,organisation_id,attorney_firm_id) on delete restrict, foreign key(webhook_endpoint_id,organisation_id,attorney_firm_id) references public.conveyancer_provider_webhook_endpoints(id,organisation_id,attorney_firm_id) on delete restrict
);

create table if not exists public.conveyancer_provider_transport_receipts (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete restrict, attorney_firm_id uuid not null references public.attorney_firms(id) on delete restrict, transaction_id uuid references public.transactions(id) on delete restrict, direction text not null check(direction in ('inbound','outbound')), record_id uuid not null, event_type text not null, idempotency_key text not null, detail jsonb not null default '{}'::jsonb check(jsonb_typeof(detail)='object' and octet_length(detail::text)<=8192), occurred_at timestamptz not null default now(), created_by uuid, unique(attorney_firm_id,idempotency_key)
);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('conveyancer-provider-inbox','conveyancer-provider-inbox',false,1048576,array['application/json']) on conflict(id) do update set public=false,file_size_limit=1048576,allowed_mime_types=array['application/json'];
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('conveyancer-provider-outbox','conveyancer-provider-outbox',false,1048576,array['application/json']) on conflict(id) do update set public=false,file_size_limit=1048576,allowed_mime_types=array['application/json'];

drop policy if exists conveyancer_provider_outbox_insert_scoped on storage.objects;
create policy conveyancer_provider_outbox_insert_scoped on storage.objects for insert to authenticated with check(bucket_id='conveyancer-provider-outbox' and case when coalesce((storage.foldername(name))[1],'') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and coalesce((storage.foldername(name))[2],'') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and coalesce((storage.foldername(name))[3],'') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then public.bridge_conveyancer_can_access_record(((storage.foldername(name))[1])::uuid,((storage.foldername(name))[2])::uuid,((storage.foldername(name))[3])::uuid) else false end);
drop policy if exists conveyancer_provider_outbox_select_scoped on storage.objects;
create policy conveyancer_provider_outbox_select_scoped on storage.objects for select to authenticated using(bucket_id='conveyancer-provider-outbox' and case when coalesce((storage.foldername(name))[1],'') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and coalesce((storage.foldername(name))[2],'') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and coalesce((storage.foldername(name))[3],'') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then public.bridge_conveyancer_can_access_record(((storage.foldername(name))[1])::uuid,((storage.foldername(name))[2])::uuid,((storage.foldername(name))[3])::uuid) else false end);

create index if not exists conveyancer_provider_transport_control_scope_idx on public.conveyancer_provider_transport_controls(organisation_id,attorney_firm_id,revision desc);
create index if not exists conveyancer_provider_outbound_dispatch_idx on public.conveyancer_provider_outbound_commands(status,available_at,created_at) where status in ('queued','retry_scheduled','leased');
create index if not exists conveyancer_provider_outbound_scope_idx on public.conveyancer_provider_outbound_commands(organisation_id,attorney_firm_id,transaction_id,created_at desc);
create index if not exists conveyancer_provider_inbound_scope_idx on public.conveyancer_provider_inbound_envelopes(organisation_id,attorney_firm_id,transaction_id,received_at desc);
create index if not exists conveyancer_provider_receipts_scope_idx on public.conveyancer_provider_transport_receipts(organisation_id,attorney_firm_id,transaction_id,occurred_at desc);

alter table public.conveyancer_provider_transport_controls enable row level security; alter table public.conveyancer_provider_webhook_endpoints enable row level security; alter table public.conveyancer_provider_outbound_commands enable row level security; alter table public.conveyancer_provider_inbound_envelopes enable row level security; alter table public.conveyancer_provider_transport_receipts enable row level security;
create policy conveyancer_provider_transport_controls_select on public.conveyancer_provider_transport_controls for select to authenticated using(public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,null::uuid));
create policy conveyancer_provider_outbound_select on public.conveyancer_provider_outbound_commands for select to authenticated using(public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,transaction_id));
create policy conveyancer_provider_inbound_select on public.conveyancer_provider_inbound_envelopes for select to authenticated using(public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,transaction_id));
create policy conveyancer_provider_receipts_select on public.conveyancer_provider_transport_receipts for select to authenticated using(public.bridge_conveyancer_can_access_record(organisation_id,attorney_firm_id,transaction_id));
revoke all on public.conveyancer_provider_transport_controls,public.conveyancer_provider_webhook_endpoints,public.conveyancer_provider_outbound_commands,public.conveyancer_provider_inbound_envelopes,public.conveyancer_provider_transport_receipts from anon,authenticated,service_role;
grant select on public.conveyancer_provider_transport_controls,public.conveyancer_provider_outbound_commands,public.conveyancer_provider_inbound_envelopes,public.conveyancer_provider_transport_receipts to authenticated,service_role; grant select on public.conveyancer_provider_webhook_endpoints to service_role;
drop trigger if exists conveyancer_provider_transport_controls_immutable on public.conveyancer_provider_transport_controls; create trigger conveyancer_provider_transport_controls_immutable before update or delete on public.conveyancer_provider_transport_controls for each row execute function public.bridge_conveyancer_reject_mutation();
drop trigger if exists conveyancer_provider_webhook_endpoints_immutable on public.conveyancer_provider_webhook_endpoints; create trigger conveyancer_provider_webhook_endpoints_immutable before update or delete on public.conveyancer_provider_webhook_endpoints for each row execute function public.bridge_conveyancer_reject_mutation();
drop trigger if exists conveyancer_provider_transport_receipts_immutable on public.conveyancer_provider_transport_receipts; create trigger conveyancer_provider_transport_receipts_immutable before update or delete on public.conveyancer_provider_transport_receipts for each row execute function public.bridge_conveyancer_reject_mutation();

create or replace function public.bridge_set_conveyancer_provider_transport_control(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_org uuid; v_firm uuid; v_record uuid; v_revision integer; v_pilot uuid[]; v_row public.conveyancer_provider_transport_controls%rowtype;
begin
 if v_user is null then raise exception 'Authentication is required.' using errcode='42501'; end if;
 begin v_org:=(payload->>'organisationId')::uuid; v_firm:=(payload->>'attorneyFirmId')::uuid; select coalesce(array_agg(distinct value::uuid),'{}'::uuid[]) into v_pilot from jsonb_array_elements_text(coalesce(payload->'pilotTransactionIds','[]'::jsonb)) items(value); exception when invalid_text_representation then raise exception 'P7 transport control identity is invalid.' using errcode='22023'; end;
 if not public.attorney_user_is_firm_admin(v_firm) or not exists(select 1 from public.attorney_firms where id=v_firm and organisation_id=v_org and is_active) then raise exception 'P7 firm administrator authority is required.' using errcode='42501'; end if;
 if coalesce(payload->>'version','')<>'conveyancer_provider_transport_p7_v1' or lower(payload->>'mode') not in ('disabled','observe','pilot','live') or trim(coalesce(payload->>'reason',''))='' or length(trim(coalesce(payload->>'fingerprint','')))<8 then raise exception 'P7 transport control is invalid.' using errcode='22023'; end if;
 if lower(payload->>'mode')='pilot' and cardinality(v_pilot)=0 then raise exception 'P7 pilot mode requires an exact transaction cohort.' using errcode='22023'; end if;
 if lower(payload->>'mode') in ('pilot','live') and coalesce((payload->>'killSwitchEnabled')::boolean,true) then raise exception 'P7 transport cannot run while its kill switch is on.' using errcode='22023'; end if;
 select record_id,revision+1 into v_record,v_revision from public.conveyancer_provider_transport_controls where organisation_id=v_org and attorney_firm_id=v_firm order by revision desc limit 1;
 insert into public.conveyancer_provider_transport_controls(record_id,revision,organisation_id,attorney_firm_id,mode,outbound_enabled,inbound_enabled,pilot_transaction_ids,kill_switch_enabled,max_attempts,lease_seconds,initial_retry_seconds,max_retry_seconds,replay_window_seconds,max_inbound_bytes,reason,fingerprint,created_by)
 values(coalesce(v_record,gen_random_uuid()),coalesce(v_revision,1),v_org,v_firm,lower(payload->>'mode'),coalesce((payload->>'outboundEnabled')::boolean,false),coalesce((payload->>'inboundEnabled')::boolean,false),v_pilot,coalesce((payload->>'killSwitchEnabled')::boolean,true),coalesce((payload->>'maxAttempts')::integer,5),coalesce((payload->>'leaseSeconds')::integer,120),coalesce((payload->>'initialRetrySeconds')::integer,30),coalesce((payload->>'maxRetrySeconds')::integer,3600),coalesce((payload->>'replayWindowSeconds')::integer,300),coalesce((payload->>'maxInboundBytes')::integer,65536),payload->>'reason',payload->>'fingerprint',v_user) returning * into v_row;
 return jsonb_build_object('ok',true,'id',v_row.id,'recordId',v_row.record_id,'revision',v_row.revision,'mode',v_row.mode);
end $$;

create or replace function public.bridge_set_conveyancer_provider_webhook_endpoint(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_org uuid; v_firm uuid; v_profile uuid; v_endpoint uuid; v_record uuid; v_revision integer; v_capabilities text[]; v_types text[]; v_row public.conveyancer_provider_webhook_endpoints%rowtype;
begin
 if v_user is null then raise exception 'Authentication is required.' using errcode='42501'; end if;
 begin v_org:=(payload->>'organisationId')::uuid; v_firm:=(payload->>'attorneyFirmId')::uuid; v_profile:=(payload->>'profileId')::uuid; v_endpoint:=coalesce(nullif(payload->>'endpointKey','')::uuid,gen_random_uuid()); exception when invalid_text_representation then raise exception 'P7 endpoint identity is invalid.' using errcode='22023'; end;
 if not public.attorney_user_is_firm_admin(v_firm) then raise exception 'Firm administrator authority is required.' using errcode='42501'; end if;
 if exists(select 1 from public.conveyancer_provider_webhook_endpoints where endpoint_key=v_endpoint and (organisation_id<>v_org or attorney_firm_id<>v_firm)) then raise exception 'P7 endpoint key belongs to another firm.' using errcode='42501'; end if;
 if not exists(select 1 from public.conveyancer_integration_profiles where id=v_profile and organisation_id=v_org and attorney_firm_id=v_firm and source_phase='P6' and profile_status in ('sandbox','active')) then raise exception 'P7 endpoint profile binding is invalid.' using errcode='22023'; end if;
 select coalesce(array_agg(distinct lower(trim(value))),'{}'::text[]) into v_capabilities from jsonb_array_elements_text(coalesce(payload->'allowedCapabilities','[]'::jsonb)) items(value); select coalesce(array_agg(distinct lower(trim(value))),'{}'::text[]) into v_types from jsonb_array_elements_text(coalesce(payload->'allowedEventTypes','[]'::jsonb)) items(value);
 if coalesce(payload->>'version','')<>'conveyancer_provider_transport_p7_v1' or lower(payload->>'status') not in ('draft','active','paused','disabled') or coalesce(payload->>'secretReference','') !~ '^env://[A-Z][A-Z0-9_]{2,127}$' or cardinality(v_types) not between 1 and 100 or exists(select 1 from unnest(v_types) as item(value) where value !~ '^[a-z0-9_.:-]{1,100}$') or cardinality(v_capabilities)=0 or not public.bridge_conveyancer_p6_capabilities_valid(v_capabilities) or length(trim(coalesce(payload->>'fingerprint','')))<8 then raise exception 'P7 endpoint configuration is invalid.' using errcode='22023'; end if;
 select record_id,revision+1 into v_record,v_revision from public.conveyancer_provider_webhook_endpoints where endpoint_key=v_endpoint and organisation_id=v_org and attorney_firm_id=v_firm order by revision desc limit 1;
 insert into public.conveyancer_provider_webhook_endpoints(record_id,revision,endpoint_key,organisation_id,attorney_firm_id,integration_profile_id,status,secret_reference,allowed_event_types,allowed_capabilities,fingerprint,created_by) values(coalesce(v_record,gen_random_uuid()),coalesce(v_revision,1),v_endpoint,v_org,v_firm,v_profile,lower(payload->>'status'),payload->>'secretReference',v_types,v_capabilities,payload->>'fingerprint',v_user) returning * into v_row;
 return jsonb_build_object('ok',true,'id',v_row.id,'endpointKey',v_row.endpoint_key,'revision',v_row.revision,'status',v_row.status);
end $$;

create or replace function public.bridge_enqueue_conveyancer_provider_command(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_org uuid; v_firm uuid; v_transaction uuid; v_profile uuid; v_role text; v_control public.conveyancer_provider_transport_controls%rowtype; v_existing public.conveyancer_provider_outbound_commands%rowtype; v_id uuid;
begin
 if v_user is null then raise exception 'Authentication is required.' using errcode='42501'; end if;
 begin v_org:=(payload->>'organisationId')::uuid; v_firm:=(payload->>'attorneyFirmId')::uuid; v_transaction:=(payload->>'transactionId')::uuid; v_profile:=(payload->>'profileId')::uuid; exception when invalid_text_representation then raise exception 'P7 command identity is invalid.' using errcode='22023'; end;
 if coalesce(payload->>'version','')<>'conveyancer_provider_transport_p7_v1' or coalesce(payload->>'commandId','')='' or coalesce(payload->>'idempotencyKey','')='' or length(trim(coalesce(payload->>'fingerprint','')))<8 or length(trim(coalesce(payload->>'payloadHash','')))<8 or payload::text ~* '"(payload|body|credential|secret|access.?token|api.?key)"[[:space:]]*:' then raise exception 'P7 commands must be secret-free references.' using errcode='22023'; end if;
 if not public.bridge_conveyancer_can_access_record(v_org,v_firm,v_transaction) then raise exception 'P7 command matter access denied.' using errcode='42501'; end if;
 select role into v_role from public.attorney_firm_members where firm_id=v_firm and user_id=v_user and status='active'; if v_role not in ('firm_admin','director_partner','transfer_attorney','bond_attorney','cancellation_attorney','conveyancing_secretary') then raise exception 'P7 provider command authority is required.' using errcode='42501'; end if;
 if payload->>'payloadReference' not like 'conveyancer-provider-outbox/'||v_org||'/'||v_firm||'/'||v_transaction||'/%' then raise exception 'P7 command payload object scope is invalid.' using errcode='22023'; end if;
 if not public.bridge_conveyancer_p6_capabilities_valid(array[lower(payload->>'capability')]::text[]) or not exists(select 1 from public.conveyancer_integration_profiles profile where profile.id=v_profile and profile.organisation_id=v_org and profile.attorney_firm_id=v_firm and profile.source_phase='P6' and profile.profile_status in ('sandbox','active') and (profile.payload->'capabilities') ? lower(payload->>'capability') and (profile.payload->'operationPaths') ? lower(payload->>'operationType') and (jsonb_array_length(coalesce(profile.payload->'allowedLanes','[]'::jsonb))=0 or (profile.payload->'allowedLanes') ? lower(payload->>'lane'))) then raise exception 'P7 command profile binding is invalid.' using errcode='22023'; end if;
 select * into v_existing from public.conveyancer_provider_outbound_commands where attorney_firm_id=v_firm and (command_id=payload->>'commandId' or idempotency_key=payload->>'idempotencyKey') limit 1;
 if found then if v_existing.command_fingerprint<>payload->>'fingerprint' then raise exception 'P7 command idempotency conflict.' using errcode='23505'; end if; return jsonb_build_object('ok',true,'duplicate',true,'commandId',v_existing.id,'status',v_existing.status); end if;
 select * into v_control from public.conveyancer_provider_transport_controls where organisation_id=v_org and attorney_firm_id=v_firm order by revision desc limit 1;
 if not found or v_control.kill_switch_enabled or not v_control.outbound_enabled or v_control.mode not in ('pilot','live') or (v_control.mode='pilot' and not(v_transaction=any(v_control.pilot_transaction_ids))) then raise exception 'P7 outbound transport is disabled for this matter.' using errcode='42501'; end if;
 insert into public.conveyancer_provider_outbound_commands(organisation_id,attorney_firm_id,transaction_id,integration_profile_id,command_id,capability,operation_type,lane,payload_reference,payload_hash,idempotency_key,authority_reference,command_fingerprint,max_attempts,initial_retry_seconds,max_retry_seconds,requested_by,requested_at)
 values(v_org,v_firm,v_transaction,v_profile,payload->>'commandId',lower(payload->>'capability'),lower(payload->>'operationType'),lower(payload->>'lane'),payload->>'payloadReference',payload->>'payloadHash',payload->>'idempotencyKey',payload->>'authorityReference',payload->>'fingerprint',v_control.max_attempts,v_control.initial_retry_seconds,v_control.max_retry_seconds,v_user,(payload->>'requestedAt')::timestamptz) returning id into v_id;
 insert into public.conveyancer_provider_transport_receipts(organisation_id,attorney_firm_id,transaction_id,direction,record_id,event_type,idempotency_key,detail,created_by) values(v_org,v_firm,v_transaction,'outbound',v_id,'queued','outbound:'||v_id||':queued',jsonb_build_object('commandFingerprint',payload->>'fingerprint'),v_user);
 return jsonb_build_object('ok',true,'duplicate',false,'commandId',v_id,'status','queued');
end $$;

create or replace function public.bridge_claim_conveyancer_provider_commands(p_limit integer default 25,p_now timestamptz default now()) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_row public.conveyancer_provider_outbound_commands%rowtype; v_lease uuid; v_commands jsonb:='[]'::jsonb; v_count integer:=0;
begin
 for v_row in select command.* from public.conveyancer_provider_outbound_commands command join lateral(select * from public.conveyancer_provider_transport_controls control where control.organisation_id=command.organisation_id and control.attorney_firm_id=command.attorney_firm_id order by revision desc limit 1) control on true where ((command.status in ('queued','retry_scheduled') and command.available_at<=p_now) or (command.status='leased' and command.lease_expires_at<=p_now)) and control.mode in ('pilot','live') and (control.mode='live' or command.transaction_id=any(control.pilot_transaction_ids)) and control.outbound_enabled and not control.kill_switch_enabled order by command.available_at,command.created_at for update of command skip locked limit greatest(1,least(coalesce(p_limit,25),100))
 loop
  v_lease:=gen_random_uuid(); update public.conveyancer_provider_outbound_commands set status='leased',attempt_count=attempt_count+1,lease_token=v_lease,lease_expires_at=p_now+(select make_interval(secs=>control.lease_seconds) from public.conveyancer_provider_transport_controls control where control.organisation_id=v_row.organisation_id and control.attorney_firm_id=v_row.attorney_firm_id order by revision desc limit 1),updated_at=p_now where id=v_row.id;
  v_count:=v_count+1; v_commands:=v_commands||jsonb_build_array(jsonb_build_object('id',v_row.id,'leaseToken',v_lease,'version','conveyancer_provider_runtime_p6_v1','operationId',v_row.command_id||':attempt:'||(v_row.attempt_count+1),'profileId',v_row.integration_profile_id,'organisationId',v_row.organisation_id,'attorneyFirmId',v_row.attorney_firm_id,'transactionId',v_row.transaction_id,'capability',v_row.capability,'operationType',v_row.operation_type,'lane',v_row.lane,'payloadReference',v_row.payload_reference,'payloadHash',v_row.payload_hash,'idempotencyKey',v_row.idempotency_key,'authorityReference',v_row.authority_reference,'requestedAt',v_row.requested_at,'requestedBy',v_row.requested_by,'attempt',v_row.attempt_count+1));
 end loop;
 return jsonb_build_object('ok',true,'count',v_count,'commands',v_commands);
end $$;

create or replace function public.bridge_complete_conveyancer_provider_command(p_command_id uuid,p_lease_token uuid,payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_row public.conveyancer_provider_outbound_commands%rowtype; v_status text; v_retry boolean:=coalesce((payload->>'retrySafe')::boolean,true); v_delay integer;
begin
 select * into v_row from public.conveyancer_provider_outbound_commands where id=p_command_id for update; if not found or v_row.status<>'leased' or v_row.lease_token<>p_lease_token then raise exception 'P7 command lease is invalid.' using errcode='42501'; end if;
 if coalesce(payload->>'decision','')='reconciliation_required' or coalesce(payload->>'code','')='provider_result_unrecorded' then v_status:='reconciliation_required'; v_retry:=false;
 elsif coalesce((payload->>'ok')::boolean,false) then v_status:='succeeded';
 elsif v_retry and v_row.attempt_count<v_row.max_attempts then v_status:='retry_scheduled';
 else v_status:='dead_letter'; end if;
 v_delay:=least(v_row.max_retry_seconds,(v_row.initial_retry_seconds*power(2,greatest(0,v_row.attempt_count-1)))::integer);
 update public.conveyancer_provider_outbound_commands set status=v_status,available_at=case when v_status='retry_scheduled' then now()+make_interval(secs=>v_delay) else available_at end,lease_token=null,lease_expires_at=null,last_error_code=nullif(payload->>'code',''),provider_reference=nullif(payload->>'providerReference',''),response_hash=nullif(payload->>'responseHash',''),result_payload=payload,completed_at=case when v_status in ('succeeded','dead_letter','reconciliation_required') then now() else null end,updated_at=now() where id=v_row.id;
 insert into public.conveyancer_provider_transport_receipts(organisation_id,attorney_firm_id,transaction_id,direction,record_id,event_type,idempotency_key,detail) values(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id,'outbound',v_row.id,v_status,'outbound:'||v_row.id||':attempt:'||v_row.attempt_count,jsonb_build_object('attempt',v_row.attempt_count,'code',payload->>'code','providerReference',payload->>'providerReference','humanReviewRequired',true));
 insert into public.conveyancer_integration_events(organisation_id,attorney_firm_id,transaction_id,integration_profile_id,direction,event_type,processing_status,idempotency_key,provider_event_id,content_hash,source_phase,contract_version,fingerprint,payload,created_by)
 values(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id,v_row.integration_profile_id,'outbound',v_row.operation_type,case when v_status='succeeded' then 'completed' when v_status='retry_scheduled' then 'pending' else 'failed' end,v_row.idempotency_key||':attempt:'||v_row.attempt_count,nullif(payload->>'providerReference',''),nullif(payload->>'responseHash',''),'P7','conveyancer_provider_transport_p7_v1',v_row.command_fingerprint,jsonb_build_object('commandId',v_row.id,'status',v_status,'attempt',v_row.attempt_count,'humanReviewRequired',true),v_row.requested_by);
 return jsonb_build_object('ok',true,'commandId',v_row.id,'status',v_status,'attempt',v_row.attempt_count,'nextAttemptAt',case when v_status='retry_scheduled' then now()+make_interval(secs=>v_delay) else null end);
end $$;

create or replace function public.bridge_retry_conveyancer_provider_command(p_command_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_role text; v_row public.conveyancer_provider_outbound_commands%rowtype;
begin
 if v_user is null or trim(coalesce(p_reason,''))='' then raise exception 'P7 retry requires authentication and a reason.' using errcode='42501'; end if; select * into v_row from public.conveyancer_provider_outbound_commands where id=p_command_id for update;
 if not found or not public.bridge_conveyancer_can_access_record(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id) or v_row.status not in ('dead_letter','reconciliation_required') then raise exception 'P7 command is not eligible for operator retry.' using errcode='42501'; end if; select role into v_role from public.attorney_firm_members where firm_id=v_row.attorney_firm_id and user_id=v_user and status='active'; if v_role not in ('firm_admin','director_partner','transfer_attorney','bond_attorney','cancellation_attorney') then raise exception 'P7 operator retry authority is required.' using errcode='42501'; end if;
 update public.conveyancer_provider_outbound_commands set status='queued',attempt_count=0,available_at=now(),lease_token=null,lease_expires_at=null,last_error_code=null,completed_at=null,updated_at=now() where id=v_row.id;
 insert into public.conveyancer_provider_transport_receipts(organisation_id,attorney_firm_id,transaction_id,direction,record_id,event_type,idempotency_key,detail,created_by) values(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id,'outbound',v_row.id,'operator_retry','outbound:'||v_row.id||':operator_retry:'||gen_random_uuid(),jsonb_build_object('reason',left(trim(p_reason),500),'previousStatus',v_row.status),v_user);
 return jsonb_build_object('ok',true,'commandId',v_row.id,'status','queued');
end $$;

create or replace function public.bridge_record_conveyancer_provider_inbound(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_endpoint public.conveyancer_provider_webhook_endpoints%rowtype; v_control public.conveyancer_provider_transport_controls%rowtype; v_transaction uuid; v_existing uuid; v_existing_hash text; v_id uuid;
begin
 select * into v_endpoint from public.conveyancer_provider_webhook_endpoints where endpoint_key=(payload->>'endpointKey')::uuid order by revision desc limit 1; if not found or v_endpoint.status<>'active' then raise exception 'P7 webhook endpoint is unavailable.' using errcode='22023'; end if;
 begin v_transaction:=(payload->>'transactionId')::uuid; exception when invalid_text_representation then raise exception 'P7 inbound transaction is invalid.' using errcode='22023'; end;
 select * into v_control from public.conveyancer_provider_transport_controls where organisation_id=v_endpoint.organisation_id and attorney_firm_id=v_endpoint.attorney_firm_id order by revision desc limit 1;
 if not found or v_control.kill_switch_enabled or not v_control.inbound_enabled or v_control.mode not in ('pilot','live') or (v_control.mode='pilot' and not(v_transaction=any(v_control.pilot_transaction_ids))) then raise exception 'P7 inbound transport is disabled for this matter.' using errcode='42501'; end if;
 if coalesce((payload->>'signatureVerified')::boolean,false)=false or coalesce(payload->>'providerEventId','')='' or not(lower(payload->>'eventType')=any(v_endpoint.allowed_event_types)) or not(lower(payload->>'capability')=any(v_endpoint.allowed_capabilities)) or lower(payload->>'lane') not in ('transfer','bond','cancellation','external') or length(trim(coalesce(payload->>'contentHash','')))<8 or coalesce(payload->>'objectBucket','')<>'conveyancer-provider-inbox' or coalesce(payload->>'objectPath','')='' then raise exception 'P7 inbound signature, routing or object evidence is invalid.' using errcode='22023'; end if;
 if not exists(select 1 from public.transactions where id=v_transaction and organisation_id=v_endpoint.organisation_id) then raise exception 'P7 inbound matter binding is invalid.' using errcode='22023'; end if;
 select id,content_hash into v_existing,v_existing_hash from public.conveyancer_provider_inbound_envelopes where endpoint_key=v_endpoint.endpoint_key and provider_event_id=payload->>'providerEventId'; if v_existing is not null then if v_existing_hash<>payload->>'contentHash' then raise exception 'P7 inbound replay content conflict.' using errcode='23505'; end if; return jsonb_build_object('ok',true,'duplicate',true,'envelopeId',v_existing,'reviewRequired',true); end if;
 insert into public.conveyancer_provider_inbound_envelopes(organisation_id,attorney_firm_id,transaction_id,integration_profile_id,webhook_endpoint_id,endpoint_key,provider_event_id,event_type,capability,lane,signature_verified,provider_timestamp,object_bucket,object_path,content_hash,metadata)
 values(v_endpoint.organisation_id,v_endpoint.attorney_firm_id,v_transaction,v_endpoint.integration_profile_id,v_endpoint.id,v_endpoint.endpoint_key,payload->>'providerEventId',lower(payload->>'eventType'),lower(payload->>'capability'),lower(payload->>'lane'),true,(payload->>'providerTimestamp')::timestamptz,payload->>'objectBucket',payload->>'objectPath',payload->>'contentHash',coalesce(payload->'metadata','{}'::jsonb)) returning id into v_id;
 insert into public.conveyancer_provider_transport_receipts(organisation_id,attorney_firm_id,transaction_id,direction,record_id,event_type,idempotency_key,detail) values(v_endpoint.organisation_id,v_endpoint.attorney_firm_id,v_transaction,'inbound',v_id,'received','inbound:'||v_id||':received',jsonb_build_object('signatureVerified',true,'contentHash',payload->>'contentHash','humanReviewRequired',true));
 insert into public.conveyancer_integration_events(organisation_id,attorney_firm_id,transaction_id,integration_profile_id,direction,event_type,processing_status,idempotency_key,provider_event_id,signature_verified,object_bucket,object_path,content_hash,source_phase,contract_version,fingerprint,payload)
 values(v_endpoint.organisation_id,v_endpoint.attorney_firm_id,v_transaction,v_endpoint.integration_profile_id,'inbound',lower(payload->>'eventType'),'received','inbound:'||v_endpoint.endpoint_key||':'||(payload->>'providerEventId')||':received',payload->>'providerEventId',true,payload->>'objectBucket',payload->>'objectPath',payload->>'contentHash','P7','conveyancer_provider_transport_p7_v1',payload->>'contentHash',jsonb_build_object('envelopeId',v_id,'capability',lower(payload->>'capability'),'lane',lower(payload->>'lane'),'humanReviewRequired',true,'legalTruthCreated',false));
 return jsonb_build_object('ok',true,'duplicate',false,'envelopeId',v_id,'reviewRequired',true);
end $$;

create or replace function public.bridge_review_conveyancer_provider_inbound(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_id uuid; v_role text; v_row public.conveyancer_provider_inbound_envelopes%rowtype; v_decision text:=lower(payload->>'decision'); v_status text; v_processing text;
begin
 if v_user is null then raise exception 'Authentication is required.' using errcode='42501'; end if; begin v_id:=(payload->>'envelopeId')::uuid; exception when invalid_text_representation then raise exception 'P7 inbound review identity is invalid.' using errcode='22023'; end;
 select * into v_row from public.conveyancer_provider_inbound_envelopes where id=v_id for update; if not found or not public.bridge_conveyancer_can_access_record(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id) or v_row.status<>'awaiting_review' then raise exception 'P7 inbound envelope is not reviewable.' using errcode='42501'; end if; select role into v_role from public.attorney_firm_members where firm_id=v_row.attorney_firm_id and user_id=v_user and status='active'; if v_role not in ('firm_admin','director_partner','transfer_attorney','bond_attorney','cancellation_attorney','conveyancing_secretary') then raise exception 'P7 inbound review authority is required.' using errcode='42501'; end if;
 if coalesce(payload->>'version','')<>'conveyancer_provider_transport_p7_v1' or v_decision not in ('accept_for_review','quarantine','ignore') or trim(coalesce(payload->>'reason',''))='' or payload->>'reviewedBy'<>v_user::text or length(trim(coalesce(payload->>'fingerprint','')))<8 then raise exception 'P7 inbound review decision is invalid.' using errcode='22023'; end if;
 v_status:=case v_decision when 'accept_for_review' then 'accepted_for_review' when 'quarantine' then 'quarantined' else 'ignored' end; v_processing:=case v_decision when 'accept_for_review' then 'accepted' when 'quarantine' then 'quarantined' else 'cancelled' end;
 update public.conveyancer_provider_inbound_envelopes set status=v_status,review_reason=left(trim(payload->>'reason'),1000),reviewed_by=v_user,reviewed_at=now(),updated_at=now() where id=v_row.id;
 insert into public.conveyancer_provider_transport_receipts(organisation_id,attorney_firm_id,transaction_id,direction,record_id,event_type,idempotency_key,detail,created_by) values(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id,'inbound',v_row.id,v_status,'inbound:'||v_row.id||':'||v_status,jsonb_build_object('reason',left(trim(payload->>'reason'),500),'legalTruthCreated',false,'workflowMutationPerformed',false),v_user);
 insert into public.conveyancer_integration_events(organisation_id,attorney_firm_id,transaction_id,integration_profile_id,direction,event_type,processing_status,idempotency_key,provider_event_id,signature_verified,object_bucket,object_path,content_hash,source_phase,contract_version,fingerprint,payload,created_by)
 values(v_row.organisation_id,v_row.attorney_firm_id,v_row.transaction_id,v_row.integration_profile_id,'inbound',v_row.event_type,v_processing,'inbound:'||v_row.id||':'||v_status,v_row.provider_event_id,true,v_row.object_bucket,v_row.object_path,v_row.content_hash,'P7','conveyancer_provider_transport_p7_v1',payload->>'fingerprint',jsonb_build_object('envelopeId',v_row.id,'decision',v_decision,'reason',left(trim(payload->>'reason'),500),'humanReviewRequired',true,'legalTruthCreated',false,'workflowMutationPerformed',false),v_user);
 return jsonb_build_object('ok',true,'envelopeId',v_row.id,'status',v_status,'legalTruthCreated',false,'workflowMutationPerformed',false);
end $$;

revoke all on function public.bridge_set_conveyancer_provider_transport_control(jsonb) from public,anon,authenticated,service_role; revoke all on function public.bridge_set_conveyancer_provider_webhook_endpoint(jsonb) from public,anon,authenticated,service_role; revoke all on function public.bridge_enqueue_conveyancer_provider_command(jsonb) from public,anon,authenticated,service_role; revoke all on function public.bridge_claim_conveyancer_provider_commands(integer,timestamptz) from public,anon,authenticated,service_role; revoke all on function public.bridge_complete_conveyancer_provider_command(uuid,uuid,jsonb) from public,anon,authenticated,service_role; revoke all on function public.bridge_retry_conveyancer_provider_command(uuid,text) from public,anon,authenticated,service_role; revoke all on function public.bridge_record_conveyancer_provider_inbound(jsonb) from public,anon,authenticated,service_role; revoke all on function public.bridge_review_conveyancer_provider_inbound(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.bridge_set_conveyancer_provider_transport_control(jsonb) to authenticated; grant execute on function public.bridge_set_conveyancer_provider_webhook_endpoint(jsonb) to authenticated; grant execute on function public.bridge_enqueue_conveyancer_provider_command(jsonb) to authenticated; grant execute on function public.bridge_retry_conveyancer_provider_command(uuid,text) to authenticated; grant execute on function public.bridge_review_conveyancer_provider_inbound(jsonb) to authenticated; grant execute on function public.bridge_claim_conveyancer_provider_commands(integer,timestamptz) to service_role; grant execute on function public.bridge_complete_conveyancer_provider_command(uuid,uuid,jsonb) to service_role; grant execute on function public.bridge_record_conveyancer_provider_inbound(jsonb) to service_role;
comment on table public.conveyancer_provider_outbound_commands is 'P7 durable reference-only provider outbox with leases, bounded retries, dead letters and reconciliation state.';
comment on table public.conveyancer_provider_inbound_envelopes is 'P7 signed, replay-protected inbound references awaiting explicit human review; inbound evidence never creates legal truth.';
notify pgrst,'reload schema';
commit;
