import assert from 'node:assert/strict'
import { buildInformationAccessAuditEvent, buildInformationAccessMatrix, buildInformationGovernancePolicy, buildInformationResource, evaluateInformationAccess } from '../conveyancerInformationGovernance.js'

const org='10000000-0000-4000-8000-000000000001';const firm='20000000-0000-4000-8000-000000000001';const otherFirm='20000000-0000-4000-8000-000000000002';const branch='30000000-0000-4000-8000-000000000001';const team='40000000-0000-4000-8000-000000000001';const matter='50000000-0000-4000-8000-000000000001';const attorney='60000000-0000-4000-8000-000000000001';const manager='70000000-0000-4000-8000-000000000001';const secretary='80000000-0000-4000-8000-000000000001';const absent='90000000-0000-4000-8000-000000000001';const at='2026-07-16T12:00:00.000Z';const hash=`sha256:${'b'.repeat(64)}`
function policy(overrides={}){return buildInformationGovernancePolicy({policyId:'information-policy:1',policyVersion:'1.0.0',organisationId:org,attorneyFirmId:firm,effectiveAt:'2026-07-01T00:00:00Z',reason:'Firm information governance policy.',...overrides}).policy}
function resource(overrides={}){return{resourceId:'resource:g2:1',resourceType:'matter_note',organisationId:org,attorneyFirmId:firm,transactionId:matter,branchId:branch,teamId:team,assignedUserId:absent,classifications:['privileged'],retentionClass:'matter_record',retainUntil:'2031-07-16T00:00:00Z',legalHold:false,exportPolicy:'watermarked',...overrides}}
function actor(role='responsible_attorney',userId=attorney,overrides={}){return{userId,membershipId:`membership:${userId}`,role,organisationId:org,attorneyFirmId:firm,branchId:branch,teamId:team,...overrides}}
function membership(overrides={}){return{active:true,organisationId:org,attorneyFirmId:firm,transactionIds:[matter],branchIds:[branch],teamIds:[team],...overrides}}
function request(overrides={}){return{decisionId:'decision:g2:1',policy:policy(),resource:resource(),actor:actor(),membership:membership(),action:'view',purpose:'Progress the instructed transfer matter.',requestedAt:at,channel:'application',...overrides}}
function test(name,fn){try{fn();console.log(`ok - ${name}`)}catch(error){console.error(`not ok - ${name}`);throw error}}

test('builds versioned firm policy and multi-classified resources',()=>{assert.equal(buildInformationGovernancePolicy(policy()).ok,true);assert.equal(buildInformationResource(resource({classifications:['personal','financial']})).ok,true)})
test('allows only matter members whose role may access every classification',()=>{assert.equal(evaluateInformationAccess(request()).allowed,true);const accounts=evaluateInformationAccess(request({actor:actor('accounts',secretary)}));assert.equal(accounts.allowed,false);assert.ok(accounts.blockers.includes('information_classification_action_denied'))})
test('fails closed across firms, branches and teams',()=>{const crossFirm=evaluateInformationAccess(request({actor:actor('responsible_attorney',attorney,{attorneyFirmId:otherFirm})}));assert.equal(crossFirm.allowed,false);assert.ok(crossFirm.blockers.includes('information_tenant_binding_mismatch'));assert.ok(evaluateInformationAccess(request({membership:membership({teamIds:[]})})).blockers.includes('information_team_access_missing'))})
test('enforces ethical walls even for ordinary matter members',()=>{const decision=evaluateInformationAccess(request({resource:resource({ethicalWallId:'wall:1'}),ethicalWalls:[{wallId:'wall:1',deniedUserIds:[attorney]}]}));assert.equal(decision.allowed,false);assert.ok(decision.blockers.includes('information_ethical_wall_denied'))})
test('permits independently approved time-limited break glass for viewing only',()=>{const common={resource:resource({ethicalWallId:'wall:1'}),ethicalWalls:[{wallId:'wall:1',deniedUserIds:[attorney]}],breakGlass:{requestedBy:attorney,approvedBy:manager,approvedByRole:'firm_manager',reason:'Urgent client safety issue.',incidentReference:'incident:g2:1',approvedAt:'2026-07-16T11:55:00Z',expiresAt:'2026-07-16T12:30:00Z'}};const view=evaluateInformationAccess(request(common));assert.equal(view.allowed,true,JSON.stringify(view.blockers));assert.ok(view.obligations.includes('notify_privacy_and_firm_manager'));assert.equal(evaluateInformationAccess(request({...common,action:'export',decisionId:'decision:g2:export'})).allowed,false)})
test('supports controlled leave substitution and temporary delegation without approval powers',()=>{const noMatter=membership({transactionIds:[]});const substitution=evaluateInformationAccess(request({actor:actor('conveyancing_secretary',secretary),membership:noMatter,substitution:{substituteUserId:secretary,absentUserId:absent,absentRole:'responsible_attorney',approvedBy:manager,startsAt:'2026-07-16T11:00:00Z',endsAt:'2026-07-16T13:00:00Z'}}));assert.equal(substitution.allowed,true,JSON.stringify(substitution.blockers));const delegated=evaluateInformationAccess(request({actor:actor('conveyancing_secretary',secretary),membership:noMatter,delegation:{delegateUserId:secretary,delegatedBy:attorney,delegatorRole:'responsible_attorney',transactionId:matter,actions:['view'],startsAt:'2026-07-16T11:00:00Z',endsAt:'2026-07-16T13:00:00Z'}}));assert.equal(delegated.allowed,true);assert.equal(evaluateInformationAccess(request({membership:membership({onLeave:true})})).allowed,false)})
test('prevents disposal under retention or legal hold and applies export controls',()=>{const held=evaluateInformationAccess(request({actor:actor('supervising_attorney'),action:'dispose',resource:resource({legalHold:true}),decisionId:'decision:g2:dispose'}));assert.ok(held.blockers.includes('information_legal_hold_active'));assert.ok(held.blockers.includes('information_retention_period_active'));const exported=evaluateInformationAccess(request({action:'export',decisionId:'decision:g2:export'}));assert.equal(exported.allowed,true);assert.ok(exported.obligations.includes('watermark_export'))})
test('produces RLS-ready action booleans while keeping database RLS authoritative',()=>{const matrix=buildInformationAccessMatrix({...request(),decisionIdPrefix:'matrix:g2'});assert.equal(matrix.canSelect,true);assert.equal(matrix.canUpdate,true);assert.match(matrix.advisory,/database RLS remains authoritative/i)})
test('records allowed and denied access in the common G1 audit shape',()=>{const decision=evaluateInformationAccess(request());const audit=buildInformationAccessAuditEvent({decision,eventId:'audit:g2:1',detailReference:'access://decision/g2/1',detailHash:hash});assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.equal(audit.event.eventType,'information_access_allowed')})
console.log('G2 information-governance tests passed.')
