import assert from 'node:assert/strict'
import {
  buildPracticeAuditEvent, buildPracticeEvidenceSource, buildPracticeOperationContract, buildPracticeOperationIdentity,
  buildPracticePolicyBinding, evaluatePracticeApprovals, evaluatePracticeOperationAuthority, PRACTICE_OPERATION_CAPABILITIES as C,
} from '../conveyancerPracticeOperationsContract.js'

const org='10000000-0000-4000-8000-000000000001';const firm='20000000-0000-4000-8000-000000000001';const branch='30000000-0000-4000-8000-000000000001';const team='40000000-0000-4000-8000-000000000001';const matter='50000000-0000-4000-8000-000000000001';const attorney='60000000-0000-4000-8000-000000000001';const supervisor='70000000-0000-4000-8000-000000000001';const secretary='80000000-0000-4000-8000-000000000001';const profile='90000000-0000-4000-8000-000000000001';const at='2026-07-16T12:00:00.000Z';const hash=`sha256:${'a'.repeat(64)}`
function identity(overrides={}){return{organisationId:org,attorneyFirmId:firm,branchId:branch,teamId:team,transactionId:matter,operationId:'operation:g1:1',lane:'transfer',...overrides}}
function actor(role='responsible_attorney',userId=attorney,overrides={}){return{userId,membershipId:`membership:${userId}`,role,organisationId:org,attorneyFirmId:firm,branchId:branch,teamId:team,...overrides}}
function policy(){return{policyId:'practice-policy:1',policyVersion:'1.0.0',policyFingerprint:'fnv1a_deadbeef',effectiveAt:at}}
function operation(overrides={}){return buildPracticeOperationContract({recordType:'manual_evidence_capture',identity:identity(),actor:actor(),capability:C.captureEvidence,policy:policy(),evidenceSource:{mode:'manual',sourceReference:'upload://evidence/1',canonicalEvidenceType:'bank_guarantee',capturedBy:attorney,receivedAt:at},payloadReference:'matter://evidence/1',payloadHash:hash,sideEffects:['persist_append_only','append_audit','queue_human_review'],occurredAt:at,reason:'Guarantee received from the issuing bank.',...overrides})}
function test(name,fn){try{fn();console.log(`ok - ${name}`)}catch(error){console.error(`not ok - ${name}`);throw error}}

test('binds every operation to organisation, firm, matter, branch, team and lane',()=>{const result=buildPracticeOperationIdentity(identity());assert.equal(result.ok,true);assert.equal(result.identity.transactionId,matter);assert.equal(Object.isFrozen(result.identity),true);assert.equal(buildPracticeOperationIdentity(identity({attorneyFirmId:'wrong'})).ok,false)})
test('requires an exact immutable firm-policy version and fingerprint',()=>{assert.equal(buildPracticePolicyBinding(policy()).ok,true);assert.equal(buildPracticePolicyBinding({...policy(),policyVersion:''}).ok,false)})
test('enforces attorney, secretary, accounts, compliance and manager boundaries',()=>{assert.equal(evaluatePracticeOperationAuthority({actor:actor('conveyancing_secretary',secretary),identity:identity(),capability:C.captureEvidence,asOf:at}).allowed,true);assert.equal(evaluatePracticeOperationAuthority({actor:actor('conveyancing_secretary',secretary),identity:identity(),capability:C.approveTrustPayment,asOf:at}).allowed,false);assert.equal(evaluatePracticeOperationAuthority({actor:actor('accounts',secretary),identity:identity(),capability:C.reconcileTrust,asOf:at}).allowed,true)})
test('allows bounded delegation but never delegates professional approval powers',()=>{const delegation={delegateUserId:secretary,delegatedBy:attorney,capability:C.reviewEvidence,organisationId:org,attorneyFirmId:firm,transactionId:matter,startsAt:'2026-07-16T11:00:00Z',endsAt:'2026-07-16T13:00:00Z'};assert.equal(evaluatePracticeOperationAuthority({actor:actor('conveyancing_secretary',secretary),identity:identity(),capability:C.reviewEvidence,delegation,asOf:at}).allowed,true);assert.equal(evaluatePracticeOperationAuthority({actor:actor('conveyancing_secretary',secretary),identity:identity(),capability:C.approveLegalInstrument,delegation:{...delegation,capability:C.approveLegalInstrument},asOf:at}).allowed,false)})
test('gives manual and integrated evidence the same canonical type without integration self-approval',()=>{const manual=buildPracticeEvidenceSource({mode:'manual',sourceReference:'upload://1',canonicalEvidenceType:'bank_guarantee',capturedBy:attorney,receivedAt:at});const integrated=buildPracticeEvidenceSource({mode:'integration',sourceReference:'provider://1',canonicalEvidenceType:'bank_guarantee',integrationProfileId:profile,providerEventId:'event:1',receivedAt:at});assert.equal(manual.ok,true);assert.equal(integrated.ok,true);assert.equal(manual.source.canonicalEvidenceType,integrated.source.canonicalEvidenceType);assert.ok(buildPracticeEvidenceSource({...integrated.source,reviewState:'approved'}).errors.includes('practice_integration_cannot_self_approve'))})
test('requires independent reasoned approvals with separation of duties',()=>{const result=evaluatePracticeApprovals({initiatedBy:attorney,requiredRoles:['supervising_attorney','compliance'],minimumApprovals:2,approvals:[{role:'supervising_attorney',decision:'approved',approvedBy:supervisor,reason:'Legal authority checked.',approvedAt:at},{role:'compliance',decision:'approved',approvedBy:secretary,reason:'Policy controls checked.',approvedAt:at}]});assert.equal(result.approved,true);assert.equal(evaluatePracticeApprovals({initiatedBy:attorney,requiredRoles:['supervising_attorney'],approvals:[{role:'supervising_attorney',decision:'approved',approvedBy:attorney,reason:'Self approved.',approvedAt:at}]}).approved,false)})
test('builds a complete reference-only operation with traceability proof',()=>{const result=operation();assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(Object.values(result.traceability).every(Boolean),true);assert.match(result.operation.fingerprint,/^fnv1a_/);assert.equal(Object.isFrozen(result.operation),true)})
test('blocks raw payloads, secrets and side effects that make legal or financial decisions',()=>{assert.ok(operation({payload:{guarantee:'raw'}}).errors.includes('practice_operation_must_be_reference_only'));assert.ok(operation({clientSecret:'raw'}).errors.includes('practice_operation_contains_secret'));assert.ok(operation({sideEffects:['execute_trust_payment']}).errors.includes('practice_side_effect_outside_boundary'))})
test('produces the common append-only audit event required by later G phases',()=>{const result=buildPracticeAuditEvent({eventId:'audit:g1:1',eventType:'evidence_captured',operationId:'operation:g1:1',organisationId:org,attorneyFirmId:firm,transactionId:matter,actorUserId:attorney,capability:C.captureEvidence,reason:'Manual guarantee captured.',occurredAt:at,correlationId:'matter:g1',detailReference:'audit://g1/1',detailHash:hash});assert.equal(result.ok,true);assert.match(result.event.fingerprint,/^fnv1a_/)})
console.log('G1 practice-operations contract tests passed.')
