import assert from 'node:assert/strict'
import { assureConveyancerPracticeG10, buildConveyancerPracticeG10PilotManifest, buildPracticeAssuranceG10Checkpoint, CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION, evaluateConveyancerPracticeG10Pilot, PRACTICE_ASSURANCE_G10_BOUNDARY, PRACTICE_ASSURANCE_G10_MINIMUM_SCENARIOS, PRACTICE_ASSURANCE_G10_PHASES, PRACTICE_ASSURANCE_G10_PROBES, PRACTICE_ASSURANCE_G10_SCENARIOS, PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES, serializeConveyancerPracticeG10Evidence, validatePracticeAssuranceG10Checkpoint } from '../conveyancerPracticeAssuranceG10.js'
import { CONVEYANCER_EXTERNAL_PORTAL_VERSION } from '../conveyancerExternalPortal.js'
import { CONVEYANCER_MATTER_CLOSEOUT_RECOVERY_VERSION } from '../conveyancerMatterCloseoutRecovery.js'

const org='10000000-0000-4000-8000-000000000001',firm='20000000-0000-4000-8000-000000000001',manager='30000000-0000-4000-8000-000000000001',hash=`sha256:${'a'.repeat(64)}`,commit='b'.repeat(40),policy='fnv1a_1234abcd'
const reviewer={userId:manager,role:'firm_manager',organisationId:org,attorneyFirmId:firm},executor={userId:'quality:g10',role:'quality_engineer',organisationId:org,attorneyFirmId:firm}
const probes=(overrides={})=>Object.fromEntries(PRACTICE_ASSURANCE_G10_PROBES.map(k=>[k,overrides[k]??true]))
function checkpoint(phase,overrides={}){return buildPracticeAssuranceG10Checkpoint({checkpointId:`checkpoint:${phase}`,phase,releaseCandidateId:'release:g10:1',buildId:'build:g10:1',sourceCommitHash:commit,environment:'staging',organisationId:org,attorneyFirmId:firm,policyFingerprint:policy,suiteId:`suite:${phase}`,suiteVersion:'1.0.0',scenarioCount:PRACTICE_ASSURANCE_G10_MINIMUM_SCENARIOS[phase],passedCount:PRACTICE_ASSURANCE_G10_MINIMUM_SCENARIOS[phase],failedCount:0,skippedCount:0,probes:probes(),artifactFingerprints:['fnv1a_2345bcde'],evidenceReference:`evidence://${phase}`,evidenceHash:hash,executedAt:'2026-07-16T08:00:00Z',executedBy:executor,reviewedAt:'2026-07-16T09:00:00Z',reviewedBy:reviewer,...overrides}).checkpoint}
const checkpoints=()=>Object.values(PRACTICE_ASSURANCE_G10_PHASES).map(checkpoint)
const scenarios=()=>PRACTICE_ASSURANCE_G10_SCENARIOS.map(id=>({scenarioId:id,decision:'ready',evidenceReference:`scenario://${id}`,evidenceHash:hash,phases:['G1','G10']}))
const signoffs=()=>PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES.map((role,index)=>({role,decision:'approved',approvedBy:`approver:g10:${index}`,reason:`${role} assurance approved.`,approvedAt:'2026-07-16T10:00:00Z'}))
function assurance(overrides={}){return assureConveyancerPracticeG10({assuranceId:'assurance:g10:1',checkpoints:checkpoints(),scenarioEvidence:scenarios(),signoffs:signoffs(),portalIsolation:{version:CONVEYANCER_EXTERNAL_PORTAL_VERSION,passed:true,fingerprint:'fnv1a_3456cdef'},migrationRecovery:{version:CONVEYANCER_MATTER_CLOSEOUT_RECOVERY_VERSION,migrationBalanced:true,recoveryPassed:true,fingerprint:'fnv1a_4567def0'},assuredAt:'2026-07-16T11:00:00Z',...overrides})}
function test(name,fn){try{fn();console.log(`ok - ${name}`)}catch(error){console.error(`not ok - ${name}`);throw error}}

test('certifies exact G1-G9 phase versions and evidence',()=>{for(const phase of Object.values(PRACTICE_ASSURANCE_G10_PHASES))assert.equal(validatePracticeAssuranceG10Checkpoint(checkpoint(phase)).valid,true,phase)})
test('requires zero failed or skipped phase scenarios',()=>{const value=buildPracticeAssuranceG10Checkpoint({...checkpoint('G8'),failedCount:1,passedCount:12});assert.ok(value.errors.includes('g10_checkpoint_scenario_gate_failed'))})
test('requires every cross-phase safety probe',()=>{const value=buildPracticeAssuranceG10Checkpoint({...checkpoint('G5'),probes:probes({trustPaymentControls:false})});assert.ok(value.errors.includes('g10_checkpoint_probe_failed'))})
test('detects checkpoint tampering and open exceptions',()=>{const value=structuredClone(checkpoint('G9'));value.evidenceHash=`sha256:${'c'.repeat(64)}`;assert.ok(validatePracticeAssuranceG10Checkpoint(value).errors.includes('g10_checkpoint_fingerprint_invalid'));assert.ok(buildPracticeAssuranceG10Checkpoint({...checkpoint('G9'),exceptions:['recovery-gap']}).errors.includes('g10_checkpoint_open_exception'))})
test('certifies G1-G9 and every required pilot scenario as ready',()=>{const value=assurance();assert.equal(value.decision,'ready',JSON.stringify(value.findings));assert.equal(value.counts.checkpoints,9);assert.equal(value.counts.scenarios,13);assert.ok(Object.values(value.phaseStatus).every(Boolean));assert.ok(Object.values(value.scenarioStatus).every(Boolean))})
test('blocks missing phases and inconsistent release bindings',()=>{const rows=checkpoints().slice(0,-1);assert.ok(assurance({checkpoints:rows}).findings.some(x=>x.code==='g10_phase_checkpoint_missing'));rows[0]=checkpoint('G1',{releaseCandidateId:'other'});assert.ok(assurance({checkpoints:rows}).findings.some(x=>x.code==='g10_release_binding_inconsistent'))})
test('blocks absent or failed required scenario evidence',()=>{const rows=scenarios().filter(x=>x.scenarioId!=='third_party_payment');const value=assurance({scenarioEvidence:rows});assert.equal(value.decision,'blocked');assert.ok(value.findings.some(x=>x.evidenceId==='third_party_payment'))})
test('requires separated compliance legal trust privacy and operations sign-off',()=>{const rows=signoffs().map(x=>({...x,approvedBy:'same-user'}));const value=assurance({signoffs:rows});assert.ok(value.findings.some(x=>x.code==='g10_signoff_separation_required'))})
test('requires concrete G8 portal-isolation evidence',()=>{const value=assurance({portalIsolation:{version:CONVEYANCER_EXTERNAL_PORTAL_VERSION,passed:false,fingerprint:'fnv1a_3456cdef'}});assert.ok(value.findings.some(x=>x.code==='g10_portal_isolation_evidence_invalid'));assert.equal(value.phaseStatus.G8,false)})
test('requires balanced migration and tested G9 recovery',()=>{const value=assurance({migrationRecovery:{version:CONVEYANCER_MATTER_CLOSEOUT_RECOVERY_VERSION,migrationBalanced:false,recoveryPassed:true,fingerprint:'fnv1a_4567def0'}});assert.ok(value.findings.some(x=>x.code==='g10_migration_recovery_evidence_invalid'));assert.equal(value.phaseStatus.G9,false)})
test('allows a clean controlled pilot to go',()=>{const result=evaluateConveyancerPracticeG10Pilot({assurances:[{scenarioId:'complete-g10',assurance:assurance(),expectedDecision:'ready'}],operationalMetrics:{}});assert.equal(result.decision,'go',JSON.stringify(result.holds))})
test('holds for FICA trust privacy migration recovery or side-effect failures',()=>{const result=evaluateConveyancerPracticeG10Pilot({assurances:[{assurance:assurance()}],operationalMetrics:{ficaFailures:1,trustControlBreaches:1,privacyIncidents:1,migrationImbalances:1,recoveryFailures:1,sideEffectAttempts:1}});assert.equal(result.decision,'hold');assert.equal(result.holds.length,6)})
test('observes a small manual backlog and holds a large backlog',()=>{const rows=[{assurance:assurance()}];assert.equal(evaluateConveyancerPracticeG10Pilot({assurances:rows,operationalMetrics:{manualBacklogRate:.1}}).decision,'observe');assert.equal(evaluateConveyancerPracticeG10Pilot({assurances:rows,operationalMetrics:{manualBacklogRate:.2}}).decision,'hold')})
test('builds a guarded pilot manifest with every required owner and scenario',()=>{const owners=Object.fromEntries([...PRACTICE_ASSURANCE_G10_SIGNOFF_ROLES,'assurance','support','rollback'].map(k=>[k,`${k}-owner`]));const value=buildConveyancerPracticeG10PilotManifest({firmIds:[firm],lanes:['transfer','bond','cancellation'],maximumMatters:100,startsAt:'2026-08-01',endsAt:'2026-08-31',owners});assert.equal(value.valid,true,JSON.stringify(value.errors));assert.equal(value.scope.maximumMatters,25);assert.deepEqual(value.requiredScenarios,PRACTICE_ASSURANCE_G10_SCENARIOS);assert.equal(value.controls.externalProvidersRequired,false);assert.equal(value.controls.killSwitchRequired,true)})
test('serializes redacted assurance without raw case or credential data',()=>{const value=serializeConveyancerPracticeG10Evidence({assurance:{...assurance(),rawParty:{name:'Secret'},credential:'secret'},pilot:evaluateConveyancerPracticeG10Pilot({assurances:[{assurance:assurance()}]})});assert.equal(value.includes('rawParty'),false);assert.equal(value.includes('"credential":"secret"'),false);assert.equal(JSON.parse(value).assurance.decision,'ready')})
test('keeps G10 completely inside its certification boundary',()=>{assert.equal(CONVEYANCER_PRACTICE_ASSURANCE_G10_VERSION,'conveyancer_practice_assurance_g10_v1');assert.equal(PRACTICE_ASSURANCE_G10_BOUNDARY.portalAccessGranted,false);assert.equal(PRACTICE_ASSURANCE_G10_BOUNDARY.trustPaymentExecuted,false);assert.equal(PRACTICE_ASSURANCE_G10_BOUNDARY.deploymentPerformed,false)})
