import assert from 'node:assert/strict'
import { acceptExternalPortalInvitation, buildExternalPortalAccessChange, buildExternalPortalAccessPolicy, buildExternalPortalDocumentSubmission, buildExternalPortalDownloadIntent, buildExternalPortalInteraction, buildExternalPortalInvitation, EXTERNAL_PORTAL_BOUNDARY, projectExternalPortalMatter } from '../conveyancerExternalPortal.js'

const org='10000000-0000-4000-8000-000000000001', firm='20000000-0000-4000-8000-000000000001', matter='30000000-0000-4000-8000-000000000001', contact='40000000-0000-4000-8000-000000000001', attorney='50000000-0000-4000-8000-000000000001'
const hashA=`sha256:${'a'.repeat(64)}`, hashB=`sha256:${'b'.repeat(64)}`, at='2026-07-16T10:00:00Z'
const actor=()=>({userId:attorney,membershipId:'membership:g8:attorney',role:'responsible_attorney',organisationId:org,attorneyFirmId:firm})
function invitation(overrides={}){const result=buildExternalPortalInvitation({invitationId:'invite:g8:1',organisationId:org,attorneyFirmId:firm,transactionId:matter,contactId:contact,participantType:'client',participantRole:'seller',permittedActions:['upload','download','comment','acknowledge'],tokenReference:'secret://portal/invite/1',tokenHash:hashA,identityChallengeReference:'challenge://portal/1',identityChallengeHash:hashB,issuedAt:at,expiresAt:'2026-07-23T10:00:00Z',invitedBy:actor(),...overrides});assert.equal(result.ok,true,JSON.stringify(result.errors));return result.invitation}
function grant(overrides={}){const result=acceptExternalPortalInvitation({invitation:invitation(),identityEvidence:{reference:'identity://g8/1',hash:hashA,matched:true},consentEvidence:{reference:'consent://g8/1',hash:hashB,accepted:true},sessionReference:'session://g8/1',acceptedAt:'2026-07-16T11:00:00Z',...overrides});assert.equal(result.ok,true,JSON.stringify(result.errors));return result.grant}
function policy(g=grant()){return buildExternalPortalAccessPolicy({grant:g,asOf:'2026-07-16T12:00:00Z'}).policy}
function test(name,fn){try{fn();console.log(`ok - ${name}`)}catch(error){console.error(`not ok - ${name}`);throw error}}

test('builds a secure reference-only client invitation',()=>{const value=invitation();assert.equal(value.sent,false);assert.equal(value.participantRole,'seller');assert.equal('token' in value,false)})
test('rejects raw invite tokens and excessive expiry windows',()=>{const result=buildExternalPortalInvitation({...invitation(),token:'raw',issuedAt:at,expiresAt:'2026-09-01',invitedBy:actor()});assert.ok(result.errors.includes('external_portal_secret_material_prohibited'));assert.ok(result.errors.includes('external_portal_invitation_invalid'))})
test('requires matched identity and affirmative consent',()=>{const result=acceptExternalPortalInvitation({invitation:invitation(),identityEvidence:{reference:'id://1',hash:hashA,matched:false},consentEvidence:{reference:'consent://1',hash:hashB,accepted:true},sessionReference:'session://1',acceptedAt:'2026-07-16T11:00:00Z'});assert.ok(result.errors.includes('external_portal_acceptance_invalid'))})
test('creates an expiring grant without granting platform access itself',()=>{const value=grant();assert.equal(value.active,true);assert.equal(value.accessGranted,false)})
test('gives clients only client-visible portal domains',()=>{const value=policy();assert.deepEqual(value.allowedVisibility,['client_visible']);assert.equal(value.internalMatterAccess,false)})
test('allows professional-shared records only for professional participants',()=>{const invite=invitation({participantType:'professional',participantRole:'bond_attorney'});const professional=acceptExternalPortalInvitation({invitation:invite,identityEvidence:{reference:'id://p',hash:hashA,matched:true},consentEvidence:{reference:'consent://p',hash:hashB,accepted:true},sessionReference:'session://p',acceptedAt:'2026-07-16T11:00:00Z'}).grant;assert.ok(policy(professional).allowedVisibility.includes('professional_shared'))})
test('filters internal risk, privilege, trust and exceptions from projections',()=>{const result=projectExternalPortalMatter({policy:policy(),records:[{recordId:'status:1',domain:'matter_status',visibility:'client_visible',label:'Registration',status:'in_progress',summaryReference:'summary://1',summaryHash:hashA},{recordId:'risk:1',domain:'client_risk_assessment',visibility:'client_visible',label:'Risk',status:'high',summaryReference:'risk://1',summaryHash:hashB},{recordId:'note:1',domain:'matter_status',visibility:'client_visible',privileged:true,label:'Legal note',summaryReference:'note://1',summaryHash:hashA}]});assert.equal(result.records.length,1);assert.equal(result.excludedCount,2);assert.equal(result.internalDomainsExcluded,true)})
test('accepts scanned uploads only as evidence proposals',()=>{const result=buildExternalPortalDocumentSubmission({grant:grant(),submissionId:'submission:g8:1',requestId:'request:g8:1',documentReference:'upload://g8/1',documentHash:hashA,fileName:'identity.pdf',mediaType:'application/pdf',malwareScanPassed:true,submittedAt:at});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.submission.status,'proposed_for_review');assert.equal(result.submission.evidenceApproved,false)})
test('blocks unscanned external uploads',()=>{const result=buildExternalPortalDocumentSubmission({grant:grant(),submissionId:'s',requestId:'r',documentReference:'upload://1',documentHash:hashA,fileName:'x.pdf',mediaType:'application/pdf',malwareScanPassed:false,submittedAt:at});assert.ok(result.errors.includes('external_portal_document_submission_invalid'))})
test('captures comments, replies, acknowledgements and preferences for review',()=>{for(const type of ['comment','reply','acknowledgement','preference_update']){const result=buildExternalPortalInteraction({grant:grant(),interactionId:`interaction:${type}`,type,contentReference:`content://${type}`,contentHash:hashA,occurredAt:at});assert.equal(result.ok,true,type);assert.equal(result.interaction.posted,false)}})
test('requires watermarked downloads and excludes privileged records',()=>{const allowed=buildExternalPortalDownloadIntent({grant:grant(),record:{recordId:'document:1',reference:'document://1',hash:hashA,downloadable:true},watermark:'Shared with seller on 2026-07-16',preparedAt:at});assert.equal(allowed.ok,true);assert.equal(allowed.intent.downloaded,false);const denied=buildExternalPortalDownloadIntent({grant:grant(),record:{recordId:'note:1',reference:'note://1',hash:hashA,downloadable:true,privileged:true},watermark:'x',preparedAt:at});assert.ok(denied.errors.includes('external_portal_download_not_allowed'))})
test('prepares revocation and replacement without changing access',()=>{for(const type of ['revoke','replace']){const result=buildExternalPortalAccessChange({grant:grant(),type,replacementInvitationId:type==='replace'?'invite:g8:2':'',reason:'Professional changed.',actor:actor(),occurredAt:at});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.intent.executed,false)}})
test('keeps every portal operation inside the isolation boundary',()=>{assert.equal(EXTERNAL_PORTAL_BOUNDARY.internalDataExposed,false);assert.ok(Object.values(EXTERNAL_PORTAL_BOUNDARY).every(value=>value===false))})
