import { MATTER_PLAN_OWNER_ROLES as R, normalizeMatterPlanOwnerRole } from '../transactions/conveyancerMatterPlanContract.js'
import { validateConveyancerThreeRoleDependencyModel } from '../transactions/conveyancerThreeRoleDependencyModel.js'
import {
  CONVEYANCER_FINANCIAL_MODEL_STATUSES,
  CONVEYANCER_FINANCIAL_TAX_TREATMENTS,
  validateConveyancerFinancialModel,
} from '../transactions/conveyancerFinancialModel.js'
import {
  CONVEYANCER_INTEGRATION_CAPABILITIES as C,
  CONVEYANCER_INTEGRATION_CONNECTION_STATUSES,
  CONVEYANCER_INTEGRATION_DATA_CLASSIFICATIONS as D,
  CONVEYANCER_INTEGRATION_PROVIDER_CATEGORIES,
  buildConveyancerIntegrationAdapterManifest,
  buildConveyancerIntegrationOutboundCommand,
  validateConveyancerIntegrationAdapterManifest,
  validateConveyancerIntegrationConnection,
  validateConveyancerIntegrationInboundEvent,
  validateConveyancerIntegrationOutboundCommand,
} from './conveyancerIntegrationFramework.js'

export const CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION = 'conveyancer_sars_transfer_duty_integration_f4_v1'
export const SARS_TRANSFER_DUTY_APPLICATION_BASES = Object.freeze({ dutyPayable: 'duty_payable', noPaymentExpected: 'no_payment_expected', exemptionClaimed: 'exemption_claimed' })
export const SARS_TRANSFER_DUTY_PARTY_ROLES = Object.freeze({ seller: 'seller', purchaser: 'purchaser' })
export const SARS_TRANSFER_DUTY_PARTY_NATURES = Object.freeze({ individual: 'individual', company: 'company', closeCorporation: 'close_corporation', trust: 'trust', deceasedEstate: 'deceased_estate', other: 'other' })
export const SARS_TRANSFER_DUTY_OUTCOME_STATUSES = Object.freeze({ submitted: 'submitted', supportingDocumentsRequested: 'supporting_documents_requested', assessmentIssued: 'assessment_issued', accepted: 'accepted', paymentPending: 'payment_pending', paymentReceived: 'payment_received', receiptIssued: 'receipt_issued', exemptionIssued: 'exemption_issued', correctionRequired: 'correction_required', rejected: 'rejected', cancelled: 'cancelled', receiptRevoked: 'receipt_revoked' })
export const SARS_TRANSFER_DUTY_PAYMENT_STATUSES = Object.freeze({ notRequired: 'not_required', pending: 'pending', confirmedInFull: 'confirmed_in_full', reversed: 'reversed' })
export const SARS_TRANSFER_DUTY_RECEIPT_STATES = Object.freeze({ none: 'none', available: 'available', locked: 'locked', revoked: 'revoked' })

const AB = SARS_TRANSFER_DUTY_APPLICATION_BASES
const OS = SARS_TRANSFER_DUTY_OUTCOME_STATUSES
const PAY = SARS_TRANSFER_DUTY_PAYMENT_STATUSES
const RS = SARS_TRANSFER_DUTY_RECEIPT_STATES

export const SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY = Object.freeze({
  statutoryRateCalculationPerformed: false, sarsSubmissionPerformed: false, supportingDocumentsUploaded: false,
  paymentInitiated: false, paymentConfirmedByPlatform: false, receiptSynthesised: false, exemptionSynthesised: false,
  externalStatusCreatesComplianceAutomatically: false, financialModelMutated: false, workflowMutated: false,
  lodgementReadinessMutated: false, registrationUpdated: false, databaseWritePerformed: false,
})

const APPLICATION_BASES = Object.values(SARS_TRANSFER_DUTY_APPLICATION_BASES)
const PARTY_ROLES = Object.values(SARS_TRANSFER_DUTY_PARTY_ROLES)
const PARTY_NATURES = Object.values(SARS_TRANSFER_DUTY_PARTY_NATURES)
const OUTCOME_STATUSES = Object.values(SARS_TRANSFER_DUTY_OUTCOME_STATUSES)
const PAYMENT_STATUSES = Object.values(SARS_TRANSFER_DUTY_PAYMENT_STATUSES)
const RECEIPT_STATES = Object.values(SARS_TRANSFER_DUTY_RECEIPT_STATES)
const TRANSFER_TREATMENTS = [CONVEYANCER_FINANCIAL_TAX_TREATMENTS.transferDuty, CONVEYANCER_FINANCIAL_TAX_TREATMENTS.exempt]
const CORRECTION_ALLOWED_STATUSES = [OS.submitted, OS.supportingDocumentsRequested, OS.assessmentIssued, OS.accepted, OS.paymentPending, OS.correctionRequired, OS.rejected]

const OUTCOME_EVENT_TYPES = Object.freeze({
  [OS.supportingDocumentsRequested]: 'sars_transfer_duty_supporting_documents_requested',
  [OS.assessmentIssued]: 'sars_transfer_duty_assessment_received',
  [OS.receiptIssued]: 'sars_transfer_duty_receipt_received',
  [OS.exemptionIssued]: 'sars_transfer_duty_receipt_received',
  [OS.receiptRevoked]: 'sars_transfer_duty_receipt_status_received',
})

export const SARS_TRANSFER_DUTY_OUTCOME_TRANSITIONS = Object.freeze({
  [OS.submitted]: Object.freeze([OS.supportingDocumentsRequested, OS.assessmentIssued, OS.accepted, OS.correctionRequired, OS.rejected, OS.cancelled]),
  [OS.supportingDocumentsRequested]: Object.freeze([OS.assessmentIssued, OS.accepted, OS.correctionRequired, OS.rejected, OS.cancelled]),
  [OS.assessmentIssued]: Object.freeze([OS.paymentPending, OS.paymentReceived, OS.receiptIssued, OS.exemptionIssued, OS.correctionRequired, OS.rejected, OS.cancelled]),
  [OS.accepted]: Object.freeze([OS.paymentPending, OS.paymentReceived, OS.receiptIssued, OS.exemptionIssued, OS.correctionRequired, OS.cancelled]),
  [OS.paymentPending]: Object.freeze([OS.paymentReceived, OS.receiptIssued, OS.correctionRequired, OS.cancelled]),
  [OS.paymentReceived]: Object.freeze([OS.receiptIssued, OS.receiptRevoked, OS.cancelled]),
  [OS.receiptIssued]: Object.freeze([OS.receiptRevoked, OS.cancelled]),
  [OS.exemptionIssued]: Object.freeze([OS.receiptRevoked, OS.cancelled]),
  [OS.correctionRequired]: Object.freeze([OS.submitted, OS.cancelled]),
  [OS.rejected]: Object.freeze([OS.submitted, OS.cancelled]),
  [OS.cancelled]: Object.freeze([]),
  [OS.receiptRevoked]: Object.freeze([]),
})

function text(value = '') { return String(value ?? '').trim() }
function key(value = '') { return text(value).toLowerCase().replace(/[\s/-]+/g, '_').replace(/[^a-z0-9_.:]+/g, '') }
function enumValue(value, allowed) { const normalized = key(value); return allowed.includes(normalized) ? normalized : '' }
function validDate(value) { return Boolean(value && Number.isFinite(new Date(value).getTime())) }
function iso(value) { return validDate(value) ? new Date(value).toISOString() : value || null }
function hashValid(value) { return /^(sha256:)?[a-f0-9]{64}$/i.test(text(value)) }
function fingerprintValid(value) { return hashValid(value) || /^fnv1a_[a-f0-9]{8}$/i.test(text(value)) }
function unique(values = []) { return [...new Set(values.filter(Boolean))] }
function stable(value) { if (Array.isArray(value)) return value.map(stable); if (!value || typeof value !== 'object') return value; return Object.keys(value).sort().reduce((result, itemKey) => { result[itemKey] = stable(value[itemKey]); return result }, {}) }
function deepFreeze(value) { if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value; Object.values(value).forEach(deepFreeze); return Object.freeze(value) }
function fnv(value) { const source = JSON.stringify(stable(value)); let hash = 0x811c9dc5; for (let index = 0; index < source.length; index += 1) { hash ^= source.charCodeAt(index); hash = Math.imul(hash, 0x01000193) } return `fnv1a_${(hash >>> 0).toString(16).padStart(8, '0')}` }
function matterBinding(model = {}) { return { modelId: text(model.modelId), modelFingerprint: text(model.fingerprint), planId: text(model.plan?.planId), planVersion: Number(model.plan?.planVersion || 0), transactionId: text(model.transactionId), organisationId: text(model.organisationId) } }
function bindingMatches(binding = {}, model = {}) { const expected = matterBinding(model); return Object.keys(expected).every((itemKey) => binding[itemKey] === expected[itemKey]) }
function actor(input = {}) { return { role: normalizeMatterPlanOwnerRole(input.role), userId: text(input.userId || input.user_id) || null, teamId: text(input.teamId || input.team_id) || null, lane: key(input.lane) || null, firmId: text(input.firmId || input.firm_id) || null } }
function actorAllowed(inputActor, model, firmId, { legalOnly = false, managerOnly = false } = {}) { const value = actor(inputActor); const binding = model.roleBindings?.transfer; if (!value.userId || value.lane !== 'transfer' || value.firmId !== firmId || binding?.firmId !== firmId) return false; if (managerOnly) return value.role === R.firmManager; if (value.role === R.firmManager) return true; if (legalOnly) return [R.conveyancer, R.transferAttorney].includes(value.role); return [R.conveyancer, R.transferAttorney].includes(value.role) || (value.role === R.secretary && value.teamId && value.teamId === binding.owner?.teamId) }
function financialBinding(model = {}) { return { financialModelId: text(model.financialModelId), financialModelRevision: Number(model.revision || 0), financialModelFingerprint: text(model.fingerprint), planId: text(model.planId), planVersion: Number(model.planVersion || 0), transactionId: text(model.transactionId), organisationId: text(model.organisationId), lane: text(model.lane), currency: text(model.currency), purchasePriceMinor: Number(model.summary?.purchasePriceMinor), taxTreatment: text(model.consideration?.taxTreatment), approvedAt: model.approval?.approvedAt || null } }
function profileSnapshot(value = {}) { return stable({ version: value.version, profileId: value.profileId, revision: value.revision, connectionId: value.connectionId, connectionFingerprint: value.connectionFingerprint, adapterId: value.adapterId, adapterFingerprint: value.adapterFingerprint, organisationId: value.organisationId, environment: value.environment, firmId: value.firmId, sarsFinancialAccountReferenceId: value.sarsFinancialAccountReferenceId, sarsFinancialAccountHash: value.sarsFinancialAccountHash, conveyancerRegistrationReferenceId: value.conveyancerRegistrationReferenceId, conveyancerRegistrationHash: value.conveyancerRegistrationHash, efilingProfileReferenceId: value.efilingProfileReferenceId, efilingProfileHash: value.efilingProfileHash, approvedAt: value.approvedAt, approvedBy: value.approvedBy, createdAt: value.createdAt, createdBy: value.createdBy }) }
function applicationSnapshot(value = {}) { return stable({ version: value.version, applicationId: value.applicationId, revision: value.revision, previousApplicationId: value.previousApplicationId, previousFingerprint: value.previousFingerprint, correctionReason: value.correctionReason, correctionSourceOutcome: value.correctionSourceOutcome, connectionId: value.connectionId, connectionFingerprint: value.connectionFingerprint, profileId: value.profileId, profileFingerprint: value.profileFingerprint, matter: value.matter, financialModel: value.financialModel, basis: value.basis, parties: value.parties, properties: value.properties, calculation: value.calculation, retainedDocuments: value.retainedDocuments, preparedAt: value.preparedAt, preparedBy: value.preparedBy, approvedAt: value.approvedAt, approvedBy: value.approvedBy, approvalReferenceId: value.approvalReferenceId }) }
function packetSnapshot(value = {}) { return stable({ version: value.version, packetId: value.packetId, applicationId: value.applicationId, applicationFingerprint: value.applicationFingerprint, connectionId: value.connectionId, connectionFingerprint: value.connectionFingerprint, profileId: value.profileId, profileFingerprint: value.profileFingerprint, matter: value.matter, payloadReferenceId: value.payloadReferenceId, payloadHash: value.payloadHash, preparedAt: value.preparedAt, preparedBy: value.preparedBy, outboundCommandId: value.outboundCommandId, outboundCommandFingerprint: value.outboundCommandFingerprint, status: value.status, controls: value.controls }) }
function supportingBatchSnapshot(value = {}) { return stable({ version: value.version, batchId: value.batchId, applicationId: value.applicationId, applicationFingerprint: value.applicationFingerprint, requestOutcomeId: value.requestOutcomeId, requestOutcomeFingerprint: value.requestOutcomeFingerprint, matter: value.matter, caseReferenceId: value.caseReferenceId, requestHash: value.requestHash, documents: value.documents, payloadReferenceId: value.payloadReferenceId, payloadHash: value.payloadHash, preparedAt: value.preparedAt, preparedBy: value.preparedBy, approvedAt: value.approvedAt, approvedBy: value.approvedBy, approvalReferenceId: value.approvalReferenceId, outboundCommandId: value.outboundCommandId, outboundCommandFingerprint: value.outboundCommandFingerprint, status: value.status, controls: value.controls }) }
function outcomeSnapshot(value = {}) { return stable({ version: value.version, outcomeId: value.outcomeId, revision: value.revision, previousOutcomeId: value.previousOutcomeId, previousFingerprint: value.previousFingerprint, applicationId: value.applicationId, applicationFingerprint: value.applicationFingerprint, matter: value.matter, providerTransferDutyReferenceId: value.providerTransferDutyReferenceId, providerTransferDutyReferenceHash: value.providerTransferDutyReferenceHash, providerRevision: value.providerRevision, status: value.status, assessment: value.assessment, supportingDocumentRequest: value.supportingDocumentRequest, paymentStatus: value.paymentStatus, receipt: value.receipt, occurredAt: value.occurredAt, sourceInboundEventId: value.sourceInboundEventId, sourceInboundEventFingerprint: value.sourceInboundEventFingerprint, complianceEligible: value.complianceEligible, controls: value.controls }) }
function evidenceSnapshot(value = {}) { return stable({ version: value.version, evidenceId: value.evidenceId, applicationId: value.applicationId, applicationFingerprint: value.applicationFingerprint, outcomeId: value.outcomeId, outcomeFingerprint: value.outcomeFingerprint, matter: value.matter, evidenceType: value.evidenceType, documentReferenceId: value.documentReferenceId, documentHash: value.documentHash, providerTransferDutyReferenceHash: value.providerTransferDutyReferenceHash, reviewedAt: value.reviewedAt, reviewedBy: value.reviewedBy, reviewReferenceId: value.reviewReferenceId, status: value.status, controls: value.controls }) }

export function buildSarsTransferDutyAdapterManifest(input = {}) {
  return buildConveyancerIntegrationAdapterManifest({ adapterId: input.adapterId, adapterVersion: input.adapterVersion, providerKey: input.providerKey || 'sars_efiling', category: CONVEYANCER_INTEGRATION_PROVIDER_CATEGORIES.taxAuthority, environments: input.environments, authenticationTypes: input.authenticationTypes, capabilities: [C.receiveTransferDutyOutcome, C.submitTransferDutyDeclaration, C.submitTransferDutySupportingDocuments, C.manageTransferDutyDeclaration], inboundEvents: [{ type: 'sars_transfer_duty_status_received', capability: C.receiveTransferDutyOutcome, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_assessment_received', capability: C.receiveTransferDutyOutcome, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_receipt_received', capability: C.receiveTransferDutyOutcome, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_receipt_status_received', capability: C.receiveTransferDutyOutcome, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_supporting_documents_requested', capability: C.receiveTransferDutyOutcome, allowedLanes: ['transfer'] }], outboundCommands: [{ type: 'sars_transfer_duty_declaration_submission_requested', capability: C.submitTransferDutyDeclaration, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_correction_requested', capability: C.manageTransferDutyDeclaration, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_supporting_documents_submission_requested', capability: C.submitTransferDutySupportingDocuments, allowedLanes: ['transfer'] }, { type: 'sars_transfer_duty_cancellation_requested', capability: C.manageTransferDutyDeclaration, allowedLanes: ['transfer'] }], createdAt: input.createdAt, createdBy: input.createdBy })
}

export function validateSarsTransferDutyFilingProfile(input = {}, { manifest = {}, connection = {} } = {}) {
  const value = JSON.parse(JSON.stringify(input || {})); const errors = []; const mv = validateConveyancerIntegrationAdapterManifest(manifest); const cv = validateConveyancerIntegrationConnection(connection, { manifest })
  if (!mv.valid || manifest.category !== CONVEYANCER_INTEGRATION_PROVIDER_CATEGORIES.taxAuthority) errors.push('sars_adapter_invalid'); if (!cv.valid || connection.status !== CONVEYANCER_INTEGRATION_CONNECTION_STATUSES.active) errors.push('sars_connection_not_active')
  if (value.version !== CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION || !value.profileId || !Number.isInteger(value.revision) || value.revision < 1) errors.push('sars_profile_identity_invalid')
  if (value.connectionId !== connection.connectionId || value.connectionFingerprint !== connection.fingerprint || value.adapterId !== manifest.adapterId || value.adapterFingerprint !== manifest.fingerprint || value.organisationId !== connection.organisationId || value.environment !== connection.environment || !connection.allowedLanes?.includes('transfer')) errors.push('sars_profile_connection_binding_invalid')
  if (!value.firmId || !value.sarsFinancialAccountReferenceId || !hashValid(value.sarsFinancialAccountHash) || !value.conveyancerRegistrationReferenceId || !hashValid(value.conveyancerRegistrationHash) || !value.efilingProfileReferenceId || !hashValid(value.efilingProfileHash)) errors.push('sars_profile_reference_invalid')
  if (!validDate(value.approvedAt) || value.approvedBy?.role !== R.firmManager || !value.approvedBy?.userId || value.approvedBy?.lane !== 'transfer' || value.approvedBy?.firmId !== value.firmId) errors.push('sars_profile_approval_invalid')
  if (!validDate(value.createdAt) || !value.createdBy) errors.push('sars_profile_provenance_invalid')
  if (value.fingerprint !== fnv(profileSnapshot(value))) errors.push('sars_profile_fingerprint_invalid')
  if (value.accountActivated || value.registrationPerformed || value.databaseWritePerformed) errors.push('sars_profile_side_effect_boundary_violated')
  return deepFreeze({ valid: errors.length === 0, errors: unique(errors), profile: value })
}

export function buildSarsTransferDutyFilingProfile(input = {}, { manifest = {}, connection = {} } = {}) {
  const value = { version: CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION, profileId: text(input.profileId), revision: Number(input.revision || 1), connectionId: text(connection.connectionId), connectionFingerprint: text(connection.fingerprint), adapterId: text(manifest.adapterId), adapterFingerprint: text(manifest.fingerprint), organisationId: text(connection.organisationId), environment: text(connection.environment), firmId: text(input.firmId), sarsFinancialAccountReferenceId: text(input.sarsFinancialAccountReferenceId), sarsFinancialAccountHash: text(input.sarsFinancialAccountHash).toLowerCase(), conveyancerRegistrationReferenceId: text(input.conveyancerRegistrationReferenceId), conveyancerRegistrationHash: text(input.conveyancerRegistrationHash).toLowerCase(), efilingProfileReferenceId: text(input.efilingProfileReferenceId), efilingProfileHash: text(input.efilingProfileHash).toLowerCase(), approvedAt: iso(input.approvedAt), approvedBy: actor(input.approvedBy), createdAt: iso(input.createdAt), createdBy: text(input.createdBy), fingerprint: null, accountActivated: false, registrationPerformed: false, databaseWritePerformed: false }
  value.fingerprint = fnv(profileSnapshot(value)); const validation = validateSarsTransferDutyFilingProfile(value, { manifest, connection }); return deepFreeze({ ok: validation.valid, code: validation.valid ? 'sars_filing_profile_valid' : 'sars_filing_profile_invalid', errors: validation.errors, profile: validation.profile })
}

function party(input = {}) { return { partyRole: enumValue(input.partyRole, PARTY_ROLES), partyReferenceId: text(input.partyReferenceId), partyReferenceHash: text(input.partyReferenceHash).toLowerCase(), natureOfPerson: enumValue(input.natureOfPerson, PARTY_NATURES), taxIdentityReferenceId: text(input.taxIdentityReferenceId), taxIdentityHash: text(input.taxIdentityHash).toLowerCase(), declarationReferenceId: text(input.declarationReferenceId), declarationHash: text(input.declarationHash).toLowerCase() } }
function property(input = {}) { return { propertyReferenceId: text(input.propertyReferenceId), propertyReferenceHash: text(input.propertyReferenceHash).toLowerCase(), propertyType: key(input.propertyType), descriptionEvidenceReferenceId: text(input.descriptionEvidenceReferenceId), descriptionEvidenceHash: text(input.descriptionEvidenceHash).toLowerCase(), allocatedConsiderationMinor: Number(input.allocatedConsiderationMinor) } }
function retainedDocument(input = {}) { return { documentId: text(input.documentId), category: key(input.category), referenceId: text(input.referenceId), documentHash: text(input.documentHash).toLowerCase(), retainedAt: iso(input.retainedAt), submittedToSars: false } }

export function validateSarsTransferDutyApplication(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, previousApplication = null, currentOutcome = null } = {}) {
  const value = JSON.parse(JSON.stringify(input || {})); const errors = []; const dv = validateConveyancerThreeRoleDependencyModel(dependencyModel); const fv = validateConveyancerFinancialModel(financialModel); const pv = validateSarsTransferDutyFilingProfile(profile, { manifest, connection })
  if (!dv.valid || !dependencyModel.requiredLanes?.includes('transfer')) errors.push('sars_application_dependency_model_invalid'); if (!fv.valid || financialModel.assessment?.status !== CONVEYANCER_FINANCIAL_MODEL_STATUSES.ready || !financialModel.approval) errors.push('sars_application_approved_financial_model_required'); if (!pv.valid) errors.push('sars_application_profile_invalid')
  if (value.version !== CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION || !value.applicationId || !Number.isInteger(value.revision) || value.revision < 1) errors.push('sars_application_identity_invalid')
  if (value.connectionId !== connection.connectionId || value.connectionFingerprint !== connection.fingerprint || value.profileId !== profile.profileId || value.profileFingerprint !== profile.fingerprint) errors.push('sars_application_configuration_binding_invalid')
  if (!bindingMatches(value.matter || {}, dependencyModel) || value.financialModel?.financialModelId !== financialModel.financialModelId || value.financialModel?.financialModelRevision !== financialModel.revision || value.financialModel?.financialModelFingerprint !== financialModel.fingerprint || value.financialModel?.transactionId !== dependencyModel.transactionId || value.financialModel?.organisationId !== dependencyModel.organisationId || value.financialModel?.planId !== dependencyModel.plan?.planId || value.financialModel?.planVersion !== dependencyModel.plan?.planVersion || value.financialModel?.lane !== 'transfer' || value.financialModel?.currency !== 'ZAR') errors.push('sars_application_matter_financial_binding_invalid')
  if (!TRANSFER_TREATMENTS.includes(value.financialModel?.taxTreatment) || !APPLICATION_BASES.includes(value.basis)) errors.push('sars_application_tax_basis_invalid')
  if (value.financialModel?.taxTreatment === CONVEYANCER_FINANCIAL_TAX_TREATMENTS.exempt && value.basis !== AB.exemptionClaimed) errors.push('sars_application_exemption_basis_required')
  if (value.financialModel?.taxTreatment === CONVEYANCER_FINANCIAL_TAX_TREATMENTS.transferDuty && value.basis === AB.exemptionClaimed) errors.push('sars_application_exemption_financial_revision_required')
  const parties = value.parties || []; const partyIds = parties.map((item) => item.partyReferenceId); if (!parties.some((item) => item.partyRole === 'seller') || !parties.some((item) => item.partyRole === 'purchaser') || new Set(partyIds).size !== partyIds.length || parties.some((item) => !PARTY_ROLES.includes(item.partyRole) || !item.partyReferenceId || !hashValid(item.partyReferenceHash) || !PARTY_NATURES.includes(item.natureOfPerson) || !item.taxIdentityReferenceId || !hashValid(item.taxIdentityHash) || !item.declarationReferenceId || !hashValid(item.declarationHash))) errors.push('sars_application_parties_invalid')
  const properties = value.properties || []; const propertyIds = properties.map((item) => item.propertyReferenceId); if (!properties.length || new Set(propertyIds).size !== propertyIds.length || properties.some((item) => !item.propertyReferenceId || !hashValid(item.propertyReferenceHash) || !item.propertyType || !item.descriptionEvidenceReferenceId || !hashValid(item.descriptionEvidenceHash) || !Number.isSafeInteger(item.allocatedConsiderationMinor) || item.allocatedConsiderationMinor <= 0) || properties.reduce((sum, item) => sum + item.allocatedConsiderationMinor, 0) !== financialModel.summary?.purchasePriceMinor) errors.push('sars_application_properties_invalid')
  const calculation = value.calculation || {}; if (!calculation.referenceId || !hashValid(calculation.calculationHash) || !Number.isSafeInteger(calculation.estimatedDutyMinor) || calculation.estimatedDutyMinor < 0 || !validDate(calculation.calculatedAt) || (validDate(value.preparedAt) && new Date(calculation.calculatedAt) > new Date(value.preparedAt)) || calculation.authoritative !== false || ([AB.noPaymentExpected, AB.exemptionClaimed].includes(value.basis) && calculation.estimatedDutyMinor !== 0)) errors.push('sars_application_calculation_evidence_invalid')
  const documents = value.retainedDocuments || []; const documentIds = documents.map((item) => item.documentId); if (!documents.length || new Set(documentIds).size !== documentIds.length || documents.some((item) => !item.documentId || !item.category || !item.referenceId || !hashValid(item.documentHash) || !validDate(item.retainedAt) || (validDate(value.approvedAt) && new Date(item.retainedAt) > new Date(value.approvedAt)) || item.submittedToSars !== false)) errors.push('sars_application_retained_documents_invalid')
  if (!validDate(value.preparedAt) || !actorAllowed(value.preparedBy || {}, dependencyModel, profile.firmId) || !validDate(value.approvedAt) || new Date(value.approvedAt) < new Date(value.preparedAt) || !actorAllowed(value.approvedBy || {}, dependencyModel, profile.firmId, { legalOnly: true }) || value.approvedBy?.userId === value.preparedBy?.userId || !value.approvalReferenceId) errors.push('sars_application_independent_approval_invalid')
  if (value.revision === 1 && (value.previousApplicationId || value.previousFingerprint || value.correctionReason || value.correctionSourceOutcome)) errors.push('sars_application_initial_lineage_invalid')
  const embeddedCorrectionLineageValid = value.revision > 1 && Boolean(value.previousApplicationId) && fingerprintValid(value.previousFingerprint) && Boolean(value.correctionReason) && Boolean(value.correctionSourceOutcome?.outcomeId) && fingerprintValid(value.correctionSourceOutcome?.fingerprint) && CORRECTION_ALLOWED_STATUSES.includes(value.correctionSourceOutcome?.status)
  if (value.revision > 1 && (!embeddedCorrectionLineageValid || ((previousApplication || currentOutcome) && (!previousApplication || value.previousApplicationId !== previousApplication.applicationId || value.previousFingerprint !== previousApplication.fingerprint || previousApplication.revision + 1 !== value.revision || previousApplication.matter?.transactionId !== value.matter?.transactionId || !currentOutcome || value.correctionSourceOutcome?.outcomeId !== currentOutcome.outcomeId || value.correctionSourceOutcome?.fingerprint !== currentOutcome.fingerprint || value.correctionSourceOutcome?.status !== currentOutcome.status || currentOutcome.applicationId !== previousApplication.applicationId || !CORRECTION_ALLOWED_STATUSES.includes(currentOutcome.status) || currentOutcome.complianceEligible)))) errors.push('sars_application_correction_lineage_invalid')
  if (value.fingerprint !== fnv(applicationSnapshot(value))) errors.push('sars_application_fingerprint_invalid')
  if (Object.entries(SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY).some(([control, expected]) => value.controls?.[control] !== expected)) errors.push('sars_application_side_effect_boundary_violated')
  return deepFreeze({ valid: errors.length === 0, errors: unique(errors), application: value })
}

export function buildSarsTransferDutyApplication(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, previousApplication = null, currentOutcome = null } = {}) {
  const calculation = input.calculation || {}; const value = { version: CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION, applicationId: text(input.applicationId), revision: Number(input.revision || 1), previousApplicationId: previousApplication ? text(previousApplication.applicationId) : null, previousFingerprint: previousApplication ? text(previousApplication.fingerprint) : null, correctionReason: previousApplication ? text(input.correctionReason) : null, correctionSourceOutcome: currentOutcome ? { outcomeId: text(currentOutcome.outcomeId), fingerprint: text(currentOutcome.fingerprint), status: text(currentOutcome.status) } : null, connectionId: text(connection.connectionId), connectionFingerprint: text(connection.fingerprint), profileId: text(profile.profileId), profileFingerprint: text(profile.fingerprint), matter: matterBinding(dependencyModel), financialModel: financialBinding(financialModel), basis: enumValue(input.basis, APPLICATION_BASES), parties: (input.parties || []).map(party), properties: (input.properties || []).map(property), calculation: { referenceId: text(calculation.referenceId), calculationHash: text(calculation.calculationHash).toLowerCase(), estimatedDutyMinor: Number(calculation.estimatedDutyMinor), calculatedAt: iso(calculation.calculatedAt), authoritative: false }, retainedDocuments: (input.retainedDocuments || []).map(retainedDocument), preparedAt: iso(input.preparedAt), preparedBy: actor(input.preparedBy), approvedAt: iso(input.approvedAt), approvedBy: actor(input.approvedBy), approvalReferenceId: text(input.approvalReferenceId), controls: SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY, fingerprint: null }
  value.fingerprint = fnv(applicationSnapshot(value)); const validation = validateSarsTransferDutyApplication(value, { dependencyModel, financialModel, manifest, connection, profile, previousApplication, currentOutcome }); const errors = [...validation.errors]
  const privatePartyKeys = /^(full_?name|registered_?name|surname|initials|identity_?number|id_?number|tax_?number|income_?tax_?number|date_?of_?birth|annual_?income|address)$/i
  if ((input.parties || []).some((item) => Object.keys(item || {}).some((itemKey) => privatePartyKeys.test(itemKey)))) errors.push('sars_application_inline_party_identity_prohibited')
  if ((input.properties || []).some((item) => ['description', 'address', 'rawDescription', 'raw_description'].some((itemKey) => item?.[itemKey] !== undefined && item?.[itemKey] !== null))) errors.push('sars_application_inline_property_data_prohibited')
  if ((input.retainedDocuments || []).some((item) => ['content', 'body', 'base64', 'fileBytes', 'file_bytes'].some((itemKey) => item?.[itemKey] !== undefined && item?.[itemKey] !== null))) errors.push('sars_application_inline_document_prohibited')
  return deepFreeze({ ok: errors.length === 0, code: errors.length ? 'sars_transfer_duty_application_invalid' : 'sars_transfer_duty_application_approved', errors: unique(errors), application: validation.application })
}

export function validateSarsTransferDutySubmissionPacket(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, outboundCommand = {} } = {}) {
  const value = JSON.parse(JSON.stringify(input || {})); const errors = []; const av = validateSarsTransferDutyApplication(application, { dependencyModel, financialModel, manifest, connection, profile }); const cv = validateConveyancerIntegrationOutboundCommand(outboundCommand, { dependencyModel, manifest, connection })
  const expectedCommandType = application.revision > 1 ? 'sars_transfer_duty_correction_requested' : 'sars_transfer_duty_declaration_submission_requested'
  if (!av.valid) errors.push('sars_submission_application_invalid'); if (!cv.valid || outboundCommand.type !== expectedCommandType) errors.push('sars_submission_outbound_command_invalid')
  if (value.version !== CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION || !value.packetId || !['prepared', 'duplicate'].includes(value.status)) errors.push('sars_submission_identity_invalid')
  if (value.applicationId !== application.applicationId || value.applicationFingerprint !== application.fingerprint || value.connectionId !== connection.connectionId || value.connectionFingerprint !== connection.fingerprint || value.profileId !== profile.profileId || value.profileFingerprint !== profile.fingerprint || !bindingMatches(value.matter || {}, dependencyModel)) errors.push('sars_submission_binding_invalid')
  if (!value.payloadReferenceId || !hashValid(value.payloadHash) || !validDate(value.preparedAt) || new Date(value.preparedAt) < new Date(application.approvedAt) || !actorAllowed(value.preparedBy || {}, dependencyModel, profile.firmId, { legalOnly: true })) errors.push('sars_submission_preparation_invalid')
  if (value.outboundCommandId !== outboundCommand.recordId || value.outboundCommandFingerprint !== outboundCommand.fingerprint) errors.push('sars_submission_command_binding_invalid')
  if (value.fingerprint !== fnv(packetSnapshot(value))) errors.push('sars_submission_fingerprint_invalid')
  if (Object.entries(SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY).some(([control, expected]) => value.controls?.[control] !== expected)) errors.push('sars_submission_side_effect_boundary_violated')
  return deepFreeze({ valid: errors.length === 0, errors: unique(errors), packet: value })
}

export function buildSarsTransferDutySubmissionPacket(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, existingCommands = [] } = {}) {
  const preparedBy = actor(input.preparedBy); const commandType = application.revision > 1 ? 'sars_transfer_duty_correction_requested' : 'sars_transfer_duty_declaration_submission_requested'; const commandResult = buildConveyancerIntegrationOutboundCommand({ recordId: input.commandId, type: commandType, lane: 'transfer', firmId: profile.firmId, idempotencyKey: input.idempotencyKey, payloadReferenceId: input.payloadReferenceId, payloadHash: input.payloadHash, dataPolicy: { purpose: text(input.purpose || (application.revision > 1 ? 'Submit the independently approved transfer-duty correction through the configured SARS integration.' : 'Submit the independently approved transfer-duty declaration through the configured SARS integration.')), legalBasis: connection.dataPolicy?.legalBasis, consentReferenceId: connection.dataPolicy?.consentReferenceId, classifications: [D.professionalConfidential, D.personal, D.financial], retentionDays: Math.min(Number(input.retentionDays || connection.dataPolicy?.retentionDays || 0), Number(connection.dataPolicy?.retentionDays || 0)) }, requestedAt: input.preparedAt, requestedBy: preparedBy, authorityReferenceId: application.approvalReferenceId }, { dependencyModel, manifest, connection, existingCommands }); const errors = commandResult.ok ? [] : commandResult.errors.map((item) => `sars_submission_outbound:${item}`); const command = commandResult.command
  const value = { version: CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION, packetId: text(input.packetId), applicationId: text(application.applicationId), applicationFingerprint: text(application.fingerprint), connectionId: text(connection.connectionId), connectionFingerprint: text(connection.fingerprint), profileId: text(profile.profileId), profileFingerprint: text(profile.fingerprint), matter: matterBinding(dependencyModel), payloadReferenceId: text(input.payloadReferenceId), payloadHash: text(input.payloadHash).toLowerCase(), preparedAt: iso(input.preparedAt), preparedBy, outboundCommandId: command?.recordId || null, outboundCommandFingerprint: command?.fingerprint || null, status: command?.status === 'duplicate' ? 'duplicate' : 'prepared', controls: SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY, fingerprint: null }
  value.fingerprint = fnv(packetSnapshot(value)); const validation = errors.length ? { valid: false, errors } : validateSarsTransferDutySubmissionPacket(value, { dependencyModel, financialModel, manifest, connection, profile, application, outboundCommand: command }); return deepFreeze({ ok: validation.valid, code: validation.valid ? `sars_transfer_duty_submission_${value.status}` : 'sars_transfer_duty_submission_blocked', errors: unique(validation.errors), packet: value, outboundCommand: command })
}

function outcomeEvidence(input = {}) { const assessment = input.assessment || {}; const request = input.supportingDocumentRequest || {}; const receipt = input.receipt || {}; return { assessment: { noticeReferenceId: text(assessment.noticeReferenceId) || null, noticeHash: text(assessment.noticeHash).toLowerCase() || null, assessedDutyMinor: assessment.assessedDutyMinor === undefined ? null : Number(assessment.assessedDutyMinor), penaltyInterestMinor: assessment.penaltyInterestMinor === undefined ? null : Number(assessment.penaltyInterestMinor), issuedAt: iso(assessment.issuedAt) }, supportingDocumentRequest: { caseReferenceId: text(request.caseReferenceId) || null, requestHash: text(request.requestHash).toLowerCase() || null, requestedCategories: unique((request.requestedCategories || []).map(key)), requestedAt: iso(request.requestedAt) }, receipt: { state: enumValue(receipt.state || RS.none, RECEIPT_STATES), documentReferenceId: text(receipt.documentReferenceId) || null, documentHash: text(receipt.documentHash).toLowerCase() || null, issuedAt: iso(receipt.issuedAt), acceptanceEvidenceReferenceId: text(receipt.acceptanceEvidenceReferenceId) || null, acceptanceEvidenceHash: text(receipt.acceptanceEvidenceHash).toLowerCase() || null } } }
function complianceEligible(application, status, paymentStatus, receipt) { if (status === OS.receiptIssued) return receipt.state === RS.available && hashValid(receipt.documentHash) && Boolean(receipt.documentReferenceId) && (paymentStatus === PAY.confirmedInFull || ([AB.noPaymentExpected, AB.exemptionClaimed].includes(application.basis) && paymentStatus === PAY.notRequired && receipt.acceptanceEvidenceReferenceId && hashValid(receipt.acceptanceEvidenceHash))); if (status === OS.exemptionIssued) return application.basis === AB.exemptionClaimed && paymentStatus === PAY.notRequired && receipt.state === RS.available && Boolean(receipt.documentReferenceId) && hashValid(receipt.documentHash) && receipt.acceptanceEvidenceReferenceId && hashValid(receipt.acceptanceEvidenceHash); return false }

export function validateSarsTransferDutyOutcome(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, inboundEvent = {}, previousOutcome = null } = {}) {
  const value = JSON.parse(JSON.stringify(input || {})); const errors = []; const av = validateSarsTransferDutyApplication(application, { dependencyModel, financialModel, manifest, connection, profile }); const iv = validateConveyancerIntegrationInboundEvent(inboundEvent, { dependencyModel, manifest, connection })
  if (!av.valid) errors.push('sars_outcome_application_invalid'); const expectedEventType = OUTCOME_EVENT_TYPES[value.status] || 'sars_transfer_duty_status_received'; if (!iv.valid || inboundEvent.type !== expectedEventType || value.sourceInboundEventId !== inboundEvent.recordId || value.sourceInboundEventFingerprint !== inboundEvent.fingerprint) errors.push('sars_outcome_inbound_evidence_invalid')
  if (value.version !== CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION || !value.outcomeId || !Number.isInteger(value.revision) || value.revision < 1 || !OUTCOME_STATUSES.includes(value.status) || !validDate(value.occurredAt) || (validDate(application.approvedAt) && new Date(value.occurredAt) < new Date(application.approvedAt))) errors.push('sars_outcome_identity_invalid')
  if (value.applicationId !== application.applicationId || value.applicationFingerprint !== application.fingerprint || !bindingMatches(value.matter || {}, dependencyModel) || !value.providerTransferDutyReferenceId || !hashValid(value.providerTransferDutyReferenceHash) || !Number.isInteger(value.providerRevision) || value.providerRevision < 1) errors.push('sars_outcome_binding_invalid')
  if (!PAYMENT_STATUSES.includes(value.paymentStatus) || !RECEIPT_STATES.includes(value.receipt?.state)) errors.push('sars_outcome_payment_receipt_state_invalid')
  if (value.status === OS.assessmentIssued && (!value.assessment?.noticeReferenceId || !hashValid(value.assessment?.noticeHash) || !Number.isSafeInteger(value.assessment?.assessedDutyMinor) || value.assessment.assessedDutyMinor < 0 || !Number.isSafeInteger(value.assessment?.penaltyInterestMinor) || value.assessment.penaltyInterestMinor < 0 || !validDate(value.assessment?.issuedAt) || new Date(value.assessment.issuedAt) > new Date(value.occurredAt))) errors.push('sars_outcome_assessment_invalid')
  if (value.status === OS.supportingDocumentsRequested && (!value.supportingDocumentRequest?.caseReferenceId || !hashValid(value.supportingDocumentRequest?.requestHash) || !value.supportingDocumentRequest?.requestedCategories?.length || !validDate(value.supportingDocumentRequest?.requestedAt) || new Date(value.supportingDocumentRequest.requestedAt) > new Date(value.occurredAt))) errors.push('sars_outcome_supporting_document_request_invalid')
  if ([OS.receiptIssued, OS.exemptionIssued, OS.receiptRevoked].includes(value.status) && validDate(value.receipt?.issuedAt) && new Date(value.receipt.issuedAt) > new Date(value.occurredAt)) errors.push('sars_outcome_receipt_chronology_invalid')
  const eligible = complianceEligible(application, value.status, value.paymentStatus, value.receipt || {}); if (value.complianceEligible !== eligible) errors.push('sars_outcome_compliance_derivation_invalid')
  if ([OS.receiptIssued, OS.exemptionIssued].includes(value.status) && !eligible) errors.push('sars_outcome_receipt_or_exemption_invalid')
  if (value.status === OS.receiptRevoked && (!previousOutcome?.complianceEligible || ![RS.locked, RS.revoked].includes(value.receipt?.state) || ![PAY.reversed, PAY.notRequired].includes(value.paymentStatus))) errors.push('sars_outcome_receipt_revocation_invalid')
  if (value.revision === 1 && previousOutcome) errors.push('sars_outcome_initial_lineage_invalid')
  if (value.revision > 1 && (!previousOutcome || value.previousOutcomeId !== previousOutcome.outcomeId || value.previousFingerprint !== previousOutcome.fingerprint || previousOutcome.revision + 1 !== value.revision || previousOutcome.applicationId !== value.applicationId || previousOutcome.providerTransferDutyReferenceHash !== value.providerTransferDutyReferenceHash || !SARS_TRANSFER_DUTY_OUTCOME_TRANSITIONS[previousOutcome.status]?.includes(value.status) || new Date(value.occurredAt) < new Date(previousOutcome.occurredAt))) errors.push('sars_outcome_transition_invalid')
  if (value.fingerprint !== fnv(outcomeSnapshot(value))) errors.push('sars_outcome_fingerprint_invalid')
  if (Object.entries(SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY).some(([control, expected]) => value.controls?.[control] !== expected)) errors.push('sars_outcome_side_effect_boundary_violated')
  return deepFreeze({ valid: errors.length === 0, errors: unique(errors), outcome: value })
}

export function buildSarsTransferDutyOutcome(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, inboundEvent = {}, previousOutcome = null } = {}) {
  const evidence = outcomeEvidence(input); const status = enumValue(input.status, OUTCOME_STATUSES); const paymentStatus = enumValue(input.paymentStatus, PAYMENT_STATUSES); const value = { version: CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION, outcomeId: text(input.outcomeId), revision: Number(input.revision || 1), previousOutcomeId: previousOutcome ? text(previousOutcome.outcomeId) : null, previousFingerprint: previousOutcome ? text(previousOutcome.fingerprint) : null, applicationId: text(application.applicationId), applicationFingerprint: text(application.fingerprint), matter: matterBinding(dependencyModel), providerTransferDutyReferenceId: text(input.providerTransferDutyReferenceId), providerTransferDutyReferenceHash: text(input.providerTransferDutyReferenceHash).toLowerCase(), providerRevision: Number(input.providerRevision || 1), status, assessment: evidence.assessment, supportingDocumentRequest: evidence.supportingDocumentRequest, paymentStatus, receipt: evidence.receipt, occurredAt: iso(input.occurredAt), sourceInboundEventId: text(inboundEvent.recordId), sourceInboundEventFingerprint: text(inboundEvent.fingerprint), complianceEligible: complianceEligible(application, status, paymentStatus, evidence.receipt), controls: SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY, fingerprint: null }
  value.fingerprint = fnv(outcomeSnapshot(value)); const validation = validateSarsTransferDutyOutcome(value, { dependencyModel, financialModel, manifest, connection, profile, application, inboundEvent, previousOutcome }); return deepFreeze({ ok: validation.valid, code: validation.valid ? `sars_transfer_duty_outcome_${status}` : 'sars_transfer_duty_outcome_invalid', errors: validation.errors, outcome: validation.outcome })
}

export function validateSarsTransferDutySupportingDocumentBatch(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, requestOutcome = {}, requestInboundEvent = {}, previousOutcome = null, outboundCommand = {} } = {}) {
  const value = JSON.parse(JSON.stringify(input || {})); const errors = []; const ov = validateSarsTransferDutyOutcome(requestOutcome, { dependencyModel, financialModel, manifest, connection, profile, application, inboundEvent: requestInboundEvent, previousOutcome }); const cv = validateConveyancerIntegrationOutboundCommand(outboundCommand, { dependencyModel, manifest, connection })
  if (!ov.valid || requestOutcome.status !== OS.supportingDocumentsRequested) errors.push('sars_supporting_batch_request_outcome_invalid'); if (!cv.valid || outboundCommand.type !== 'sars_transfer_duty_supporting_documents_submission_requested') errors.push('sars_supporting_batch_outbound_command_invalid')
  if (value.version !== CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION || !value.batchId || !['prepared', 'duplicate'].includes(value.status)) errors.push('sars_supporting_batch_identity_invalid')
  if (value.applicationId !== application.applicationId || value.applicationFingerprint !== application.fingerprint || value.requestOutcomeId !== requestOutcome.outcomeId || value.requestOutcomeFingerprint !== requestOutcome.fingerprint || !bindingMatches(value.matter || {}, dependencyModel) || value.caseReferenceId !== requestOutcome.supportingDocumentRequest?.caseReferenceId || value.requestHash !== requestOutcome.supportingDocumentRequest?.requestHash) errors.push('sars_supporting_batch_binding_invalid')
  const retained = new Map((application.retainedDocuments || []).map((item) => [item.documentId, item])); const requested = new Set(requestOutcome.supportingDocumentRequest?.requestedCategories || []); const documents = value.documents || []; const documentIds = documents.map((item) => item.documentId)
  if (!documents.length || new Set(documentIds).size !== documentIds.length || documents.some((item) => { const source = retained.get(item.documentId); return !source || !requested.has(item.category) || item.category !== source.category || item.referenceId !== source.referenceId || item.documentHash !== source.documentHash })) errors.push('sars_supporting_batch_documents_invalid')
  if (!value.payloadReferenceId || !hashValid(value.payloadHash) || !validDate(value.preparedAt) || !actorAllowed(value.preparedBy || {}, dependencyModel, profile.firmId) || !validDate(value.approvedAt) || new Date(value.approvedAt) < new Date(value.preparedAt) || !actorAllowed(value.approvedBy || {}, dependencyModel, profile.firmId, { legalOnly: true }) || value.approvedBy?.userId === value.preparedBy?.userId || !value.approvalReferenceId) errors.push('sars_supporting_batch_independent_approval_invalid')
  if (value.outboundCommandId !== outboundCommand.recordId || value.outboundCommandFingerprint !== outboundCommand.fingerprint) errors.push('sars_supporting_batch_command_binding_invalid')
  if (value.fingerprint !== fnv(supportingBatchSnapshot(value))) errors.push('sars_supporting_batch_fingerprint_invalid')
  if (Object.entries(SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY).some(([control, expected]) => value.controls?.[control] !== expected)) errors.push('sars_supporting_batch_side_effect_boundary_violated')
  return deepFreeze({ valid: errors.length === 0, errors: unique(errors), batch: value })
}

export function buildSarsTransferDutySupportingDocumentBatch(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, requestOutcome = {}, requestInboundEvent = {}, previousOutcome = null, existingCommands = [] } = {}) {
  const selectedIds = unique(input.documentIds || []); const retained = new Map((application.retainedDocuments || []).map((item) => [item.documentId, item])); const documents = selectedIds.map((documentId) => retained.get(documentId)).filter(Boolean).map((item) => ({ documentId: item.documentId, category: item.category, referenceId: item.referenceId, documentHash: item.documentHash })); const preparedBy = actor(input.preparedBy); const errors = []
  if (requestOutcome.status !== OS.supportingDocumentsRequested || !selectedIds.length || documents.length !== selectedIds.length || documents.some((item) => !requestOutcome.supportingDocumentRequest?.requestedCategories?.includes(item.category))) errors.push('sars_supporting_batch_documents_invalid')
  if (!actorAllowed(preparedBy, dependencyModel, profile.firmId) || !actorAllowed(input.approvedBy || {}, dependencyModel, profile.firmId, { legalOnly: true }) || preparedBy.userId === actor(input.approvedBy).userId) errors.push('sars_supporting_batch_independent_approval_invalid')
  let command = null
  if (!errors.length) { const result = buildConveyancerIntegrationOutboundCommand({ recordId: input.commandId, type: 'sars_transfer_duty_supporting_documents_submission_requested', lane: 'transfer', firmId: profile.firmId, idempotencyKey: input.idempotencyKey, payloadReferenceId: input.payloadReferenceId, payloadHash: input.payloadHash, dataPolicy: { purpose: text(input.purpose || 'Submit only the retained supporting-document categories requested by SARS for the bound transfer-duty declaration.'), legalBasis: connection.dataPolicy?.legalBasis, consentReferenceId: connection.dataPolicy?.consentReferenceId, classifications: [D.professionalConfidential, D.personal, D.financial, D.specialPersonal], retentionDays: Math.min(Number(input.retentionDays || connection.dataPolicy?.retentionDays || 0), Number(connection.dataPolicy?.retentionDays || 0)) }, requestedAt: input.preparedAt, requestedBy: preparedBy, authorityReferenceId: input.approvalReferenceId }, { dependencyModel, manifest, connection, existingCommands }); if (!result.ok) errors.push(...result.errors.map((item) => `sars_supporting_batch_outbound:${item}`)); else command = result.command }
  const value = { version: CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION, batchId: text(input.batchId), applicationId: text(application.applicationId), applicationFingerprint: text(application.fingerprint), requestOutcomeId: text(requestOutcome.outcomeId), requestOutcomeFingerprint: text(requestOutcome.fingerprint), matter: matterBinding(dependencyModel), caseReferenceId: text(requestOutcome.supportingDocumentRequest?.caseReferenceId), requestHash: text(requestOutcome.supportingDocumentRequest?.requestHash), documents, payloadReferenceId: text(input.payloadReferenceId), payloadHash: text(input.payloadHash).toLowerCase(), preparedAt: iso(input.preparedAt), preparedBy, approvedAt: iso(input.approvedAt), approvedBy: actor(input.approvedBy), approvalReferenceId: text(input.approvalReferenceId), outboundCommandId: command?.recordId || null, outboundCommandFingerprint: command?.fingerprint || null, status: command?.status === 'duplicate' ? 'duplicate' : 'prepared', controls: SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY, fingerprint: null }
  value.fingerprint = fnv(supportingBatchSnapshot(value)); const validation = errors.length ? { valid: false, errors } : validateSarsTransferDutySupportingDocumentBatch(value, { dependencyModel, financialModel, manifest, connection, profile, application, requestOutcome, requestInboundEvent, previousOutcome, outboundCommand: command }); return deepFreeze({ ok: validation.valid, code: validation.valid ? `sars_supporting_document_batch_${value.status}` : 'sars_supporting_document_batch_blocked', errors: unique(validation.errors), batch: value, outboundCommand: command })
}

export function validateSarsTransferDutyComplianceEvidence(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, outcome = {}, inboundEvent = {}, previousOutcome = null } = {}) {
  const value = JSON.parse(JSON.stringify(input || {})); const errors = []; const ov = validateSarsTransferDutyOutcome(outcome, { dependencyModel, financialModel, manifest, connection, profile, application, inboundEvent, previousOutcome })
  if (!ov.valid || !outcome.complianceEligible) errors.push('sars_compliance_eligible_outcome_required')
  if (value.version !== CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION || !value.evidenceId || value.status !== 'approved_for_lodgement_evidence') errors.push('sars_compliance_identity_invalid')
  if (value.applicationId !== application.applicationId || value.applicationFingerprint !== application.fingerprint || value.outcomeId !== outcome.outcomeId || value.outcomeFingerprint !== outcome.fingerprint || !bindingMatches(value.matter || {}, dependencyModel)) errors.push('sars_compliance_binding_invalid')
  const expectedType = outcome.status === OS.exemptionIssued ? 'exemption' : 'receipt'; if (value.evidenceType !== expectedType || value.documentReferenceId !== outcome.receipt?.documentReferenceId || value.documentHash !== outcome.receipt?.documentHash || value.providerTransferDutyReferenceHash !== outcome.providerTransferDutyReferenceHash) errors.push('sars_compliance_document_binding_invalid')
  if (!validDate(value.reviewedAt) || new Date(value.reviewedAt) < new Date(outcome.occurredAt) || !actorAllowed(value.reviewedBy || {}, dependencyModel, profile.firmId, { legalOnly: true }) || !value.reviewReferenceId) errors.push('sars_compliance_legal_review_invalid')
  if (value.fingerprint !== fnv(evidenceSnapshot(value))) errors.push('sars_compliance_fingerprint_invalid')
  if (Object.entries(SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY).some(([control, expected]) => value.controls?.[control] !== expected)) errors.push('sars_compliance_side_effect_boundary_violated')
  return deepFreeze({ valid: errors.length === 0, errors: unique(errors), evidence: value })
}

export function buildSarsTransferDutyComplianceEvidence(input = {}, { dependencyModel = {}, financialModel = {}, manifest = {}, connection = {}, profile = {}, application = {}, outcome = {}, inboundEvent = {}, previousOutcome = null } = {}) {
  const value = { version: CONVEYANCER_SARS_TRANSFER_DUTY_INTEGRATION_VERSION, evidenceId: text(input.evidenceId), applicationId: text(application.applicationId), applicationFingerprint: text(application.fingerprint), outcomeId: text(outcome.outcomeId), outcomeFingerprint: text(outcome.fingerprint), matter: matterBinding(dependencyModel), evidenceType: outcome.status === OS.exemptionIssued ? 'exemption' : 'receipt', documentReferenceId: text(outcome.receipt?.documentReferenceId), documentHash: text(outcome.receipt?.documentHash), providerTransferDutyReferenceHash: text(outcome.providerTransferDutyReferenceHash), reviewedAt: iso(input.reviewedAt), reviewedBy: actor(input.reviewedBy), reviewReferenceId: text(input.reviewReferenceId), status: 'approved_for_lodgement_evidence', controls: SARS_TRANSFER_DUTY_INTEGRATION_BOUNDARY, fingerprint: null }
  value.fingerprint = fnv(evidenceSnapshot(value)); const validation = validateSarsTransferDutyComplianceEvidence(value, { dependencyModel, financialModel, manifest, connection, profile, application, outcome, inboundEvent, previousOutcome }); return deepFreeze({ ok: validation.valid, code: validation.valid ? 'sars_transfer_duty_compliance_evidence_approved' : 'sars_transfer_duty_compliance_evidence_invalid', errors: validation.errors, evidence: validation.evidence })
}
