// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import AgentNewDealWizard from '../../AgentNewDealWizard.jsx'
import { readAgentPrivateListings } from '../../../lib/agentListingStorage.js'
import { ensureTransactionCaptureInvitations } from '../../../services/transactionCaptureHandoffService.js'
import { createTransactionFromWizard, uploadDocument } from '../../../lib/api.js'

vi.mock('../../../lib/api.js', () => ({ createTransactionFromWizard: vi.fn(async () => ({ transactionId: 'saved-deal' })), uploadDocument: vi.fn(), fetchDevelopmentOptions: vi.fn(async () => []), fetchUnitsForTransactionSetup: vi.fn(async () => []) }))
vi.mock('../../../services/transactionCaptureHandoffService.js', () => ({ ensureTransactionCaptureInvitations: vi.fn(async () => []) }))
vi.mock('../../../services/transactionHandoffRegisterService.js', () => ({ readTransactionHandoffRegister: vi.fn(async () => ({ items: [] })) }))
vi.mock('../../../services/documents/transactionCanonicalDocumentRequirementService.js', () => ({ fetchTransactionDocumentRequirementsByTransactionIds: vi.fn(async () => ({ 'saved-deal': [] })) }))
vi.mock('../../../lib/supabaseClient.js', () => ({ isSupabaseConfigured: false, supabase: null }))
vi.mock('../../../lib/settingsApi.js', () => ({ fetchOrganisationSettings: vi.fn(async () => null), listOrganisationPartnerRoutingRules: vi.fn(async () => []), listOrganisationPreferredPartners: vi.fn(async () => []), listUserPreferredPartnerRoutingRules: vi.fn(async () => []), resolveCommissionSnapshotForAgent: vi.fn(async () => null) }))
vi.mock('../../../context/WorkspaceContext.jsx', () => {
  const context = { workspace: { id: 'all', type: 'agency' }, profile: { id: 'agent', email: 'agent@example.com', fullName: 'Agent' }, currentMembership: {}, role: 'agent' }
  return { useWorkspace: () => context }
})
vi.mock('../../../lib/agentListingStorage.js', () => ({ readAgentPrivateListings: vi.fn(() => []), writeAgentPrivateListings: vi.fn() }))
afterEach(() => { cleanup(); vi.clearAllMocks(); readAgentPrivateListings.mockReturnValue([]); window.localStorage.clear() })
it('sends separate legal entities, named people and marriage details through the transaction save path', async () => {
  render(<MemoryRouter><AgentNewDealWizard open onClose={() => {}} /></MemoryRouter>)
  await waitFor(() => expect(screen.getByRole('button', { name: 'Continue' }).disabled).toBe(false))
  fireEvent.click(screen.getByRole('button', { name: /Quick address capture/ }))
  fireEvent.change(screen.getByLabelText('Property Address'), { target: { value: '10 Test Street' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByLabelText('Yes, connect buyer'))
  const buyer = within(screen.getByRole('region', { name: 'Buyer party details' }))
  fireEvent.change(buyer.getByLabelText('Full name'), { target: { value: 'Jane Buyer' } })
  fireEvent.change(buyer.getByLabelText('Email'), { target: { value: 'jane@example.com' } })
  fireEvent.change(buyer.getByLabelText('Phone'), { target: { value: '0821234567' } })
  fireEvent.change(buyer.getByLabelText('Marital status'), { target: { value: 'married' } })
  fireEvent.change(buyer.getByLabelText('Marriage regime'), { target: { value: 'out_of_community_with_accrual' } })
  fireEvent.click(buyer.getByRole('button', { name: 'Add buyer person' }))
  const coBuyer = within(buyer.getByRole('group', { name: 'Buyer person 2' }))
  fireEvent.change(coBuyer.getByLabelText('Full name'), { target: { value: 'Alex Co-buyer' } })
  const seller = within(screen.getByRole('region', { name: 'Seller party details' }))
  fireEvent.change(seller.getByLabelText('Seller entity type'), { target: { value: 'trust' } })
  fireEvent.change(seller.getByLabelText('Seller registered entity name'), { target: { value: 'Seller Trust' } })
  fireEvent.change(seller.getByLabelText('Registration number / estate reference'), { target: { value: 'IT123/2026' } })
  fireEvent.change(seller.getByLabelText('Full name'), { target: { value: 'Pat Trustee' } })
  fireEvent.change(seller.getByLabelText("Person's role"), { target: { value: 'trustee' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await waitFor(() => expect(createTransactionFromWizard).toHaveBeenCalledTimes(1))
  const { setup } = createTransactionFromWizard.mock.calls[0][0]
  expect(setup.buyerName).toBe('Jane Buyer')
  expect(setup.transactionParties.buyer.people).toHaveLength(2)
  expect(setup.buyerParties.some((person) => person.name === 'Alex Co-buyer' && person.role === 'co_purchaser')).toBe(true)
  expect(setup.purchaserType).toBe('married_anc_accrual')
  expect(setup.transactionParties.buyer.people[0].maritalRegime).toBe('out_of_community_with_accrual')
  expect(setup.sellerName).toBe('Seller Trust')
  expect(setup.transactionParties.seller.registrationNumber).toBe('IT123/2026')
  expect(setup.transactionParties.seller.people[0].name).toBe('Pat Trustee')
})

async function startBackfill() {
  render(<MemoryRouter><AgentNewDealWizard open onClose={() => {}} /></MemoryRouter>)
  await waitFor(() => expect(screen.getByRole('button', { name: 'Continue' }).disabled).toBe(false))
  fireEvent.click(screen.getByRole('button', { name: /Quick address capture/ }))
  fireEvent.change(screen.getByLabelText('Property Address'), { target: { value: '20 Backfill Street' } })
  fireEvent.change(screen.getByLabelText(/Agreed Selling Price/), { target: { value: '1250000' } })
  fireEvent.change(screen.getByLabelText(/Sale Date/), { target: { value: '2026-08-10' } })
  const stages = within(screen.getByLabelText('Current Stage')).getAllByRole('option')
  const capturedStage = stages[stages.length - 1].value
  fireEvent.change(screen.getByLabelText('Current Stage'), { target: { value: capturedStage } })
  expect(screen.queryByLabelText('OTP uploaded')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  return capturedStage
}

it('captures actual sale terms and uploads existing documents only after the transaction is saved', async () => {
  const stage = await startBackfill()
  uploadDocument.mockResolvedValue({ id: 'saved-file' })
  fireEvent.change(screen.getByLabelText('Choose documents'), { target: { files: [new File(['signed'], 'signed-otp.pdf', { type: 'application/pdf' })] } })
  expect(screen.getByText('Ready to upload after creation')).toBeTruthy()
  expect(uploadDocument).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await waitFor(() => expect(uploadDocument).toHaveBeenCalledTimes(1))
  const { setup, status, options } = createTransactionFromWizard.mock.calls[0][0]
  expect(setup.salesPrice).toBe(1250000)
  expect(setup.saleDate).toBe('2026-08-10')
  expect(status.stage).toBe(stage)
  expect(options.handoffChecklist.signedOtpStatus).toBe('pending_upload')
  expect(options.completeness.completedItems).not.toContain('OTP upload')
  expect(uploadDocument.mock.calls[0][0].transactionId).toBe('saved-deal')
  await screen.findByText(/Saved — match to the checklist/)
})

it('retries a failed file against the saved transaction without creating another deal', async () => {
  await startBackfill()
  uploadDocument.mockRejectedValueOnce(new Error('Connection lost')).mockResolvedValueOnce({ id: 'retry-file' })
  fireEvent.change(screen.getByLabelText('Choose documents'), { target: { files: [new File(['signed'], 'retry.pdf', { type: 'application/pdf' })] } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  const retry = await screen.findByRole('button', { name: 'Retry failed uploads' })
  await waitFor(() => expect(retry.disabled).toBe(false))
  fireEvent.click(retry)
  await screen.findByText(/Saved — match to the checklist/)
  expect(createTransactionFromWizard).toHaveBeenCalledTimes(1)
  expect(uploadDocument).toHaveBeenCalledTimes(2)
  expect(uploadDocument.mock.calls.map(([payload]) => payload.transactionId)).toEqual(['saved-deal', 'saved-deal'])
})

it('allows a backfill without documents and keeps missing evidence as follow-up items', async () => {
  await startBackfill()
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await screen.findByText('Transaction created successfully')
  expect(uploadDocument).not.toHaveBeenCalled()
  expect(createTransactionFromWizard.mock.calls[0][0].options.completeness.missingItems).toEqual(expect.arrayContaining(['Signed mandate', 'OTP upload', 'Buyer ID']))
})

it('rejects unsupported evidence before creation and rejects negative prices', async () => {
  await startBackfill()
  fireEvent.change(screen.getByLabelText('Choose documents'), { target: { files: [new File(['data'], 'unsafe.exe', { type: 'application/octet-stream' })] } })
  expect(screen.getByRole('alert').textContent).toContain('Unsupported file type')
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.change(screen.getByLabelText(/Agreed Selling Price/), { target: { value: '-10' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  expect(screen.getByText(/Enter a selling price greater than zero/)).toBeTruthy()
  expect(createTransactionFromWizard).not.toHaveBeenCalled()
  expect(uploadDocument).not.toHaveBeenCalled()
})

it('opens the existing transaction when creation reports persisted but incomplete setup', async () => {
  await startBackfill()
  createTransactionFromWizard.mockRejectedValueOnce(Object.assign(new Error('Setup incomplete'), { transactionId: 'existing-incomplete' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await screen.findByRole('button', { name: 'Open Transaction' })
  expect(screen.queryByRole('button', { name: 'Create Transaction' })).toBeNull()
  expect(createTransactionFromWizard).toHaveBeenCalledTimes(1)
  expect(uploadDocument).not.toHaveBeenCalled()
})

it('prefills the linked price and seller and reuses an existing buyer lead without losing the captured stage', async () => {
  readAgentPrivateListings.mockReturnValue([{ id: 'listing', propertyAddress: 'Existing Street', askingPrice: 1750000, seller: { name: 'Existing Seller', email: 'seller@example.com', phone: '0825550000' } }])
  window.localStorage.setItem('itg:pipeline-leads:v1', JSON.stringify([{ id: 'lead', name: 'Existing Buyer', email: 'buyer@example.com', phone: '0825551111' }]))
  render(<MemoryRouter><AgentNewDealWizard open initialPrivateListingId="listing" onClose={() => {}} /></MemoryRouter>)
  await waitFor(() => expect(screen.getByRole('button', { name: 'Continue' }).disabled).toBe(false))
  expect(screen.getByLabelText(/Agreed Selling Price/).value).toBe('1750000')
  const stages = within(screen.getByLabelText('Current Stage')).getAllByRole('option')
  const capturedStage = stages[stages.length - 1].value
  fireEvent.change(screen.getByLabelText('Current Stage'), { target: { value: capturedStage } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getByLabelText(/Select From Pipeline/), { target: { value: 'lead' } })
  const buyer = within(screen.getByRole('region', { name: 'Buyer party details' }))
  await waitFor(() => expect(buyer.getByLabelText('Full name').value).toBe('Existing Buyer'))
  expect(within(screen.getByRole('region', { name: 'Seller party details' })).getByLabelText('Full name').value).toBe('Existing Seller')
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getAllByLabelText('Selection Mode')[0], { target: { value: 'buyer' } })
  fireEvent.change(screen.getByLabelText('Seller-Appointed Firm'), { target: { value: 'Existing Firm' } })
  fireEvent.change(screen.getAllByLabelText('Email')[0], { target: { value: 'firm@example.com' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await screen.findByText('Transaction created successfully')
  expect(createTransactionFromWizard.mock.calls[0][0]).toMatchObject({ setup: { salesPrice: 1750000, buyerName: 'Existing Buyer', sellerName: 'Existing Seller' }, status: { stage: capturedStage }, options: { preserveCapturedStage: true } })
})

it('captures a direct bank bond and invites an external bond attorney without assigning an originator', async () => {
  await startBackfill()
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.change(screen.getByLabelText('Finance Route'), { target: { value: 'bond' } })
  fireEvent.change(screen.getByLabelText('Buyer Bond Bank'), { target: { value: 'Buyer Bank' } })
  fireEvent.change(screen.getByLabelText('Bond Application Position'), { target: { value: 'approved' } })
  fireEvent.change(screen.getByLabelText('Seller Existing Bond'), { target: { value: 'no' } })
  fireEvent.change(screen.getByLabelText('Bond Amount'), { target: { value: '1250000' } })
  fireEvent.change(screen.getByLabelText('Deposit Amount'), { target: { value: '0' } })
  expect(screen.getByLabelText('Bond Route').value).toBe('client')
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getByLabelText('Bond attorney selection'), { target: { value: 'buyer' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  expect(screen.getByRole('alert').textContent).toContain('Capture the bond attorney firm and a valid invitation email')
  fireEvent.change(screen.getByLabelText('Bond attorney firm'), { target: { value: 'External Bond Firm' } })
  fireEvent.change(screen.getByLabelText('Bond attorney email'), { target: { value: 'bondfirm@example.com' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await waitFor(() => expect(ensureTransactionCaptureInvitations).toHaveBeenCalledTimes(1))
  const payload = createTransactionFromWizard.mock.calls[0][0]
  expect(payload.finance).toMatchObject({ bank: 'Buyer Bank', captureSnapshot: { managedBy: 'client', bondStatus: 'approved', sellerBondStatus: 'no' } })
  expect(payload.options.rolePlayers.some((item) => ['bond_originator', 'bond_attorney'].includes(item.roleType))).toBe(false)
  expect(ensureTransactionCaptureInvitations.mock.calls[0][0]).toMatchObject({ transactionId: 'saved-deal', nominations: [{ roleType: 'bond_attorney', companyName: 'External Bond Firm', email: 'bondfirm@example.com' }] })
})

it('persists seller bond cancellation facts for a cash buyer without routing buyer bond professionals', async () => {
  await startBackfill()
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.change(screen.getByLabelText('Finance Route'), { target: { value: 'cash' } })
  fireEvent.change(screen.getByLabelText('Seller Existing Bond'), { target: { value: 'yes' } })
  fireEvent.change(screen.getByLabelText('Seller Bond Bank'), { target: { value: 'Seller Bank' } })
  fireEvent.change(screen.getByLabelText('Seller Bond Reference'), { target: { value: 'Existing bond 123' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  expect(within(screen.getByLabelText('Document for')).getAllByRole('option').some((option) => option.textContent === 'Latest Existing Bond Statement')).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  expect(screen.queryByLabelText('Bond attorney selection')).toBeNull()
  expect(screen.getByText('Cancellation Attorney')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  await screen.findByText('Transaction created successfully')
  expect(createTransactionFromWizard.mock.calls[0][0].finance.captureSnapshot).toMatchObject({ sellerBondStatus: 'yes', sellerBondBank: 'Seller Bank', sellerBondReference: 'Existing bond 123', bank: '' })
  expect(createTransactionFromWizard.mock.calls[0][0].options.rolePlayers.some((item) => ['bond_originator', 'bond_attorney'].includes(item.roleType))).toBe(false)
})

it('starts a fresh capture on reopen without carrying over the property, evidence or appointed firm', async () => {
  const wizard = (open) => <MemoryRouter><AgentNewDealWizard open={open} onClose={() => {}} /></MemoryRouter>
  const view = render(wizard(true))
  await waitFor(() => expect(screen.getByRole('button', { name: 'Continue' }).disabled).toBe(false))
  fireEvent.click(screen.getByRole('button', { name: /Quick address capture/ }))
  fireEvent.change(screen.getByLabelText('Property Address'), { target: { value: 'Previous property' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getByLabelText('Choose documents'), { target: { files: [new File(['old'], 'previous.pdf', { type: 'application/pdf' })] } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getAllByLabelText('Selection Mode')[0], { target: { value: 'buyer' } })
  fireEvent.change(screen.getByLabelText('Seller-Appointed Firm'), { target: { value: 'Previous Firm' } })
  fireEvent.change(screen.getAllByLabelText('Email')[0], { target: { value: 'previous@example.com' } })
  view.rerender(wizard(false))
  view.rerender(wizard(true))
  await waitFor(() => expect(screen.getByRole('button', { name: 'Continue' }).disabled).toBe(false))
  fireEvent.click(screen.getByRole('button', { name: /Quick address capture/ }))
  expect(screen.getByLabelText('Property Address').value).toBe('')
  fireEvent.change(screen.getByLabelText('Property Address'), { target: { value: 'New property' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  expect(screen.queryByText('previous.pdf')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getAllByLabelText('Selection Mode')[0], { target: { value: 'buyer' } })
  expect(screen.getByLabelText('Seller-Appointed Firm').value).toBe('')
  expect(screen.getAllByLabelText('Email')[0].value).toBe('')
  expect(createTransactionFromWizard).not.toHaveBeenCalled()
})

it('retries professional invitations from the receipt against the saved transaction', async () => {
  const nominee = { roleType: 'transfer_attorney', companyName: 'Record Firm', email: 'record@example.com' }
  ensureTransactionCaptureInvitations.mockResolvedValueOnce([{ ...nominee, status: 'failed', message: 'Connection lost after save' }])
    .mockResolvedValueOnce([{ ...nominee, invitationId: 'persisted-invite', status: 'pending', message: 'Invitation already exists' }])
  await startBackfill()
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.change(screen.getAllByLabelText('Selection Mode')[0], { target: { value: 'buyer' } })
  fireEvent.change(screen.getByLabelText('Seller-Appointed Firm'), { target: { value: nominee.companyName } })
  fireEvent.change(screen.getAllByLabelText('Email')[0], { target: { value: nominee.email } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create Transaction' }))
  const retry = await screen.findByRole('button', { name: 'Retry unconfirmed invitations' })
  await waitFor(() => expect(retry.disabled).toBe(false))
  fireEvent.click(retry)
  await screen.findByText(/Invitation already exists/)
  expect(createTransactionFromWizard).toHaveBeenCalledTimes(1)
  expect(ensureTransactionCaptureInvitations.mock.calls.map(([payload]) => payload.transactionId)).toEqual(['saved-deal', 'saved-deal'])
  expect(ensureTransactionCaptureInvitations.mock.calls[1][0].nominations).toEqual(expect.arrayContaining([expect.objectContaining(nominee)]))
})
